### ISSUE TITLE
[Proposal] Grouping

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#100]
# Grouping

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
  * [ ] iOS Support
  * [ ] Android Support
  * [ ] macOS Support
  * [ ] Windows Support
* [ ] Unit Tests: Not Started
* [ ] Sample: Not Started
* [ ] Documentation: Not Started

## Summary
[summary]: #summary

Grouping of items by key into ObservableRange

## Detailed Design
[design]: #detailed-design

### Grouping.shared.cs

```cs
public class Grouping<TKey, TItem> : ObservableRangeCollection<TItem>
{
  public TKey Key { get; }

  public new IList<TItem> Items { get; }

  public Grouping(TKey key, IEnumerable<TItem> items)
  {
	  Key = key;
	  AddRange(items);
  }
}

public class Grouping<TKey, TSubKey, TItem> : ObservableRangeCollection<TItem>
{
  public TKey Key { get; }

  public TSubKey SubKey { get; }

  public new IList<TItem> Items { get; }

  public Grouping(TKey key, TSubKey subkey, IEnumerable<TItem> items)
  {
    Key = key;
    SubKey = subkey;
    AddRange(items);
  }
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

N/A

### C# Usage

```cs
readonly IReadOnlyList<Person> people = new[]
{
	new Person { FirstName = "Joseph", LastName = "Hill" },
	new Person { FirstName = "James", LastName = "Montemagno" },
	new Person { FirstName = "Pierce", LastName = "Boggan" },
};

[Test]
public void Grouping()
{
	var sorted = from person in people
					orderby person.FirstName
					group person by person.Group
		into personGroup
					select new Grouping<string, Person>(personGroup.Key, personGroup);

	var grouped = new ObservableRangeCollection<Grouping<string, Person>>();
	grouped.AddRange(sorted);

	Assert.AreEqual(2, grouped.Count);
	Assert.AreEqual("J", grouped[0].Key);
	Assert.AreEqual(2, grouped[0].Count);
	Assert.AreEqual(1, grouped[1].Count);
	Assert.AreEqual(2, grouped[0].Items.Count);
	Assert.AreEqual(1, grouped[1].Items.Count);
}
```

## Drawbacks
[drawbacks]: #drawbacks

This feature extends [`ObservableRangeCollection` which will not be included in the .NET MAUI Community Toolkit](https://github.com/CommunityToolkit/Maui/issues/99). 

We recommend adding this feature to the [MVVM Toolkit](https://docs.microsoft.com/en-us/windows/communitytoolkit/mvvm/introduction).

**Comment by brminnick** [comment]
Recommend adding this to MVVM Community Toolkit https://docs.microsoft.com/en-us/windows/communitytoolkit/mvvm/introduction

**Comment by Sergio0694** [comment]
This is something I've been thinking about for a while too, specifically I was looking into potentially move our grouped observable collections to the MVVM Toolkit, and then adding some slight tweaks on them too while at it. I'll definitely revisit this once the .NET Community Toolkit repo is live if there's interest from the MAUI Community Toolkit side as well. Happy to chat about this too 😄

**Comment by pictos** [comment]
> if there's interest from the MAUI Community Toolkit side as well

Hey @Sergio0694, the MAUI Community will love that feature since day zero. We normally use the `Grouping` collection when we want to have a grouped ListView. Let me know if you need any help to solve those tweaks.
