### ISSUE TITLE
[Proposal] iOS-Specific PopUp Arrow Direction

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#101]
# PopUp Arrow Direction

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
  * [ ] iOS Support
  * [ ] Android Support
  * [ ] macOS Support
  * [ ] Windows Support
* [ ] Unit Tests: Not Started
* [ ] Sample: Not Started
* [ ] Documentation: Not Started

## Summary
[summary]: #summary

iOS-specific implementation allowing the user to configure the Popup Arrow Direction

## Detailed Design
[design]: #detailed-design

### Popup.shared.cs

```cs
namespace Xamarin.CommunityToolkit.PlatformConfiguration.iOSSpecific
{
  public static class PopUp
  {
    public static readonly BindableProperty ArrowDirectionProperty = BindableProperty.Create(
	    "ArrowDirection", typeof(PopoverArrowDirection), typeof(BasePopup), PopoverArrowDirection.None);
  
    public static void SetArrowDirection(BindableObject element, PopoverArrowDirection color) =>
	    element.SetValue(ArrowDirectionProperty, color);
  
    public static PopoverArrowDirection GetArrowDirection(BindableObject element) =>
	    (PopoverArrowDirection)element.GetValue(ArrowDirectionProperty);
  
    public static IPlatformElementConfiguration<XFPC.iOS, XCTElement> UseArrowDirection(this IPlatformElementConfiguration<XFPC.iOS, XCTElement> config, PopoverArrowDirection value)
    {
	  SetArrowDirection(config.Element, value);
	  return config;
    }
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<Popup ios:Popup.ArrowDirection="up"/>
```

### C# Usage

```cs
using Xamarin.Forms.PlatformConfiguration;
using Xamarin.Forms.PlatformConfiguration.iOSSpecific;
...

var popup = new Popup();
popup .On<iOS>().SetArrowDirection(PopoverArrowDirection.Up);
```

**Comment by CliffAgius** [comment]
@brminnick is this still something we wish to add? it's not part of Popup at present and I know that @bijington has been working with the Popup service.

I am thinking that as it's so stale we can close this issue.

**Comment by bijington** [comment]
Nobody has chased this in the 3 years it's been open so I'd be fine with closing it. We can always reopen if someone wants it
