### ISSUE TITLE
[BUG] MediaElement StateChanged Event Position doesn't update after media has reached end

### ISSUE THREAD

**Issue by ChiefMonk** [CommunityToolkit/Maui#1043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When you have a handler for the StateChanged event and have enabled ShouldShowPlaybackControls; when the video has played till the end then you use onscreen controls to rewind the video, the MediaPositionChangedEventArgs's Position does not update to the current actual position, it keeps sending the video ends Timespan (=Duration).
Examples include:
-if the video is 2min long (Duration).
-you let it play until the end
-when you use the playback controls to rewind the video
-the e.Position of MediaPositionChangedEventArgs doesn't send the current (rewind) position, put keeps sending the 2mim, which is the MediaElement.Duration.

This is a problem for both Android and iOS****

### Expected Behavior

The MediaPositionChangedEventArgs's Position should update to the current rewind position, MediaElement.Position, and not the MediaElement.Duration

### Steps To Reproduce

1. And a MediaElement to any Page and enable ShouldShowPlaybackControls (=True)
2. Add the Video Url
3. Add an event handler for StateChanged
4. Monitor the MediaPositionChangedEventArgs's (e) Position until the video ends (when ~ (Position = Duration))
5. The e.Position should updates fine until the video reaches the end
6. Using the playback controls, rewind the video to any position < Duration
7. The e.Position doesn't contain the latest rewind TimeSpan, but the video's end one (which is the Duration)

### Link to public reproduction project repository

https://github.com/ChiefMonk/MauiMediaElementTesting

### Environment

```markdown
- .NET MAUI CommunityToolkit.MediaElement: 1.0.2
- OS: iOS and Android
- .NET MAUI: 7.0

Packages used:

 <ItemGroup>
   <PackageReference Include="CommunityToolkit.Maui.MediaElement " Version="1.0.2" />
   <PackageReference Include="Microsoft.Extensions.Loggin.Debug " Version="7.0.0" />	  
</ItemGroup>
```

**Comment by jfversluis** [comment]
Interesting, I will have a look soon, thanks!
