### ISSUE TITLE
[Proposal] Add a KeyboardManager for interacting with SoftInputKeyboard device

### ISSUE THREAD

**Issue by PureWeen** [CommunityToolkit/Maui#1055]
### Feature name

KeyboardManager

### Link to discussion

https://github.com/CommunityToolkit/Maui/discussions/969

### Progress tracker

- [x] Android Implementation
- [x] iOS Implementation
- [ ] MacCatalyst Implementation
- [ ] Windows Implementation
- [ ] Tizen Implementation
- [ ] Unit Tests
- [x] Samples
- [x] Documentation

### Summary

Currently MAUI lacks an API for interacting with the soft keyboard. This lack of API caused a lot of implicit behavior to get added to Xamarin.Forms. Because it's impossible to correctly cover how every user might want the keyboard to react we should add APIs to empower the developer to make these choices themselves

### Motivation

This will allow developers to hide/show and be alerted when the softkeyboard is opened. This will give developers the power to define how they want the keyboard to react vs us just making guesses and only being right for a subset of the users.

### Detailed Design

The changes will most likely match up with the code [here](https://github.com/PureWeen/ShanedlerSamples/tree/main/ShanedlerSamples/Library/Keyboard). 

### Usage Syntax

I realize it might seem odd that you need to pass a target view in but you are required to indicate the target of the keyboard when you open the soft input. This way the platform can focus that control and notify the user. 

```C#
KeyboardManager.Show(targetView)
KeyboardManager.Hide(targetView)
```

**Comment by nor0x** [comment]
Hi @PureWeen 👋
i think a KeyboardHeight property would be a very nice addition for KeyboardManager. Especially on Android with `WindowSoftInputModeAdjust.AdjustPan` set, it would be very helpful to know the inset value in order to adapt the UI to the apperance of the keyboard. What do you think?

thank you!

**Comment by jfversluis** [comment]
Anything to make you happy bot <3
