### ISSUE TITLE
[BUG] FileSaver on Mac - new GUID used for name instead of name provided

### ISSUE THREAD

**Issue by RoryRoberts** [CommunityToolkit/Maui#1059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

The Mac implementation of the FileSaver [uses a GUID](https://github.com/CommunityToolkit/Maui/blob/main/src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.macios.cs#L23) instead of the filename provided as a parameter when setting the suggested file name in the save dialog. The parameter is correctly used to set the file extension.

<img width="358" alt="image" src="https://user-images.githubusercontent.com/8151382/222671732-f382a097-c835-4c1c-b48a-2796a4565175.png">

### Expected Behavior

The filename provided as an argument should be used to set the suggested name in the save file dialog.

<img width="364" alt="image" src="https://user-images.githubusercontent.com/8151382/222672024-0cfd2979-9712-4498-a7ff-6e8c04ffeb25.png">

### Steps To Reproduce

1. Use a mac
2. [Invoke the `FileSaver.SaveAsync(fileName, stream, cancellationToken)` method](https://github.com/RoryRoberts/maui-community-toolkit-filesaver-guid-bug/blob/main/MauiApp1/Shared/MainLayout.razor#L16)
3. Observe the "Save As:" parameter in the dialog that opens

### Link to public reproduction project repository

https://github.com/RoryRoberts/maui-community-toolkit-filesaver-guid-bug

See: https://github.com/RoryRoberts/maui-community-toolkit-filesaver-guid-bug/blob/main/MauiApp1/Shared/MainLayout.razor#L16

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.0.0
- OS: macOS Ventura 13.0.1
- .NET MAUI: 7.0.100
```

### Anything else?

Suspected relevant code: https://github.com/CommunityToolkit/Maui/blob/main/src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.macios.cs#L23

**Comment by VladislavAntonyuk** [comment]
I wrote this code to make sure we don't get duplicate file name in temp folder. I will take a look if we can write file without using temporary directory

**Comment by Kapusch** [comment]
Hello @VladislavAntonyuk , I actually noticed the same on iPhone Simulator, could you please confirm your fix only covers MacOS ?
If yes, I will open a separated issue to keep track of it.

**Comment by VladislavAntonyuk** [comment]
We use the same code on Mac and iOS, it is not released yet.

**Comment by Kapusch** [comment]
Oh right, thanks!
I have actually read "macos" instead of "macios" when I did check your fix in 'FileSaverImplementation.macios.cs'
