### ISSUE TITLE
[BUG] IsListNotNullOrEmptyConverter not working in android

### ISSUE THREAD

**Issue by acaliaro** [CommunityToolkit/Maui#1060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I have an observable collection and would like to enable / disable a button when the collection is empty or has items, but the button is always disabled. I have take a look to https://github.com/CommunityToolkit/Maui/blob/main/samples/CommunityToolkit.Maui.Sample/Pages/Converters/IsListNotNullOrEmptyConverterPage.xaml but I am not able to work with the converter

### Expected Behavior

the button is disabled and when I add items to the list, the button is enabled

### Steps To Reproduce

Run the attached project on Android.
Press "Press to add items" and the "button disabled" should become enabled

### Link to public reproduction project repository

https://github.com/acaliaro/MauiAppIsListNotNullOrEmptyConverterProblem

### Environment

```markdown
- .NET MAUI CommunityToolkit:5.0.0
- OS:Android 10
- .NET MAUI:7
```

**Comment by bijington** [comment]
The converter doesn't handle `INotifyCollectionChanged` so in order to get the bevhaior you want you will need to raise the `PropertyChanged` event inside your add method after you have modified the collection.

**Comment by acaliaro** [comment]
Use [ObservableProperty] is not enough?

**Comment by brminnick** [comment]
Just FYI - You don't ever need to use `[ObservableProperty]` on an `ObservableCollection` because when the collection changes (eg calling  `ObservableCollection.Add()`), the `ObservableColltion` automatically calls `INotifyPropertyChanged` internally.  

Any time it's used in a View Model, `ObservableCollection` should be initialized like this:

```cs
public ObservableCollection Collection { get; } = new();
```

And then you just use `ObservableCollection`'s APIs like `.Add()`, `.Remove()`, `.Clear()` etc. to modify the collection.

**Comment by bijington** [comment]
To follow up from Brandon's point while you don't need to use `[ObservableProperty]` in this scenario it still doesn't mean the scenario will be solved for your issue. `[ObservableProperty]` only helps if you are assigning a new value/instance to your `Lista` property which you are not doing via the `add` method. This is why you need to raise the property changed event if you want the binding to update in the converter.

**Comment by acaliaro** [comment]
> Just FYI - You don't ever need to use `[ObservableProperty]` on an `ObservableCollection` because when the collection changes (eg calling `ObservableCollection.Add()`), the `ObservableColltion` automatically calls `INotifyPropertyChanged` internally.
> 
> Any time it's used in a View Model, `ObservableCollection` should be initialized like this:
> 
> ```cs
> public ObservableCollection Collection { get; } = new();
> ```
> 
> And then you just use `ObservableCollection`'s APIs like `.Add()`, `.Remove()`, `.Clear()` etc. to modify the collection.

So, @brminnick , do I have to use [ObservableProperty] not for List but only for objects (class) and simple types to raise INPC?

**Comment by acaliaro** [comment]
> RaisePropertyChanged

@bijington in the community sample I see

```
		StringItemSource.CollectionChanged += HandleCollectionChanged;

	void HandleCollectionChanged(object? sender, NotifyCollectionChangedEventArgs e) => OnPropertyChanged(nameof(StringItemSource));
```

is this the correct way? 
I don't see your suggestion 

`RaisePropertyChanged(nameof(Lista));
`

**Comment by bijington** [comment]
Oh try this then

`OnPropertyChanged(nameof(Lista));`

To answer your question directed to @brminnick you don't need to use `[ObservableProperty]` with `ObservableCollection` as it is a special type of collection that handles the raising of events. All other collection types like `List` will still require the use of the attribute.

I believe the importance of `ObservableCollection` is not that it implements `INotifyPropertyChanged` but actually `INotifyCollectionChanged`. This distinction helps to realise that it is firing events specific to a collection changing and therefore apply to using with controls that have an `ItemsSource` property.

This might give a little more detail:

https://learn.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.observablecollection-1?redirectedfrom=MSDN&view=net-7.0

**Comment by acaliaro** [comment]
> `OnPropertyChanged(nameof(Lista));`

this works, thanks @bijington and @brminnick
