### ISSUE TITLE
[BUG] [iOS] System.TypeLoadException when starting the iOS simulator with toolkit version 5.0.0

### ISSUE THREAD

**Issue by vasile135** [CommunityToolkit/Maui#1068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Getting the following error after including the CommunityToolkit.Maui 5.0.0 and trying to run the code on the iOS simulator:
![image](https://user-images.githubusercontent.com/58006892/223151650-b456f6ff-9343-4105-8e56-51f005d278f5.png)

### Expected Behavior

Expecting to be able to run the toolkit on iOS simulator.

### Steps To Reproduce

1. Installed the CommunityToolkit.Maui 5.0.0 nuget package.
2. Registered the toolkit in MauiProgram: (.UseMauiCommunityToolkit());
3. Added the `xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"`
4. Trying to add an animation behavior on a Border:
![image](https://user-images.githubusercontent.com/58006892/223152853-a14119d0-575c-4058-aff2-375a66112e41.png)
5. Run the code on the iOS 16.1 simulator --> the System.TypeLoadException is thrown.

Works for Android.

### Link to public reproduction project repository

https://github.com/vasile135/CommunityToolkitMauiAnimationsTest/tree/main/TestTapEffects

### Environment

```markdown
- .NET MAUI CommunityToolkit:5.0.0
- OS:iOS
- .NET MAUI:7.0.100
```

### Anything else?
Used the following documentation:
https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/behaviors/animation-behavior
_No response_

**Comment by brminnick** [comment]
@bijington FYI - I am unable to reproduce this using the sample provided on iOS 16.2 Simulator using .NET MAUI v7.0.59

<img width="682" alt="image" src="https://user-images.githubusercontent.com/13558917/223228219-51ff7146-3446-4da4-93c9-ab508b78956f.png">


![Simulator Screen Recording - iPhone 14 Pro - 2023-03-06 at 12 50 15](https://user-images.githubusercontent.com/13558917/223227763-8f4fa6c9-43a1-4ecf-8b79-6c03e1f9f3ae.gif)
