### ISSUE TITLE
[BUG] FileSaver doesn't handle non-seekable streams

### ISSUE THREAD

**Issue by henjo076** [CommunityToolkit/Maui#1077]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When using FileSaver to save a file using a stream that cannot seek, the SaveAsync method fails.

The reason seems to be that the a seek is done to "reset" the source stream to the beginning of the stream before copying to the target stream.

This can of course be useful behavior in some cases. But when e.g. downloading from the web, content is often streamed with streams that cannot seek.

### Expected Behavior

I expected streams that cannot seek to work with FileSaver

### Steps To Reproduce

1. Open and run solution from reproduction repository.
1. Click the Download button and observe the bug 🐞

### Link to public reproduction project repository

https://github.com/henjo076/FileSaverNonSeekableStream

### Environment

```markdown
- .NET MAUI CommunityToolkit:5.0.0
- OS: Windows 10 Build 19045.2604
- .NET MAUI: 7.0.59
```

### Anything else?

I have only tested on Windows, but the seek seems to happen on all platforms.

There exists a not too complicated workaround by implementing a wrapper stream that ignores the first seek, but it's a bit ugly to need to do that in my opinion.

**Comment by bijington** [comment]
We should look to check `CanSeek`on the stream before calling `Seek`
