### ISSUE TITLE
[Proposal] DrawingView

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#108]
# DrawingView

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Sample
* [x] Documentation

## Summary
[summary]: #summary

Allows you to draw one or multiple lines on a canvas

## Detailed Design
[design]: #detailed-design

### DrawingView.shared.cs

```cs
public class DrawingView : View
{
  public static readonly BindableProperty ClearOnFinishProperty;
  public static readonly BindableProperty MultiLineModeProperty;
  public static readonly BindableProperty LinesProperty;
  public static readonly BindableProperty DrawingLineCompletedCommandProperty;
  public static readonly BindableProperty DefaultLineColorProperty;
  public static readonly BindableProperty DefaultLineWidthProperty;
  
  public event EventHandler<DrawingLineCompletedEventArgs>? DrawingLineCompleted;
  
  public Color DefaultLineColor { get; set; }
  public float DefaultLineWidth { get; set; }
  public ICommand? DrawingLineCompletedCommand { get; set; }
  public ObservableCollection<Line> Lines { get; set; }
  public bool MultiLineMode { get; set; }
  public bool ClearOnFinish { get; set; }
  
  public Stream GetImageStream(double imageSizeWidth, double imageSizeHeight);
  public static Stream GetImageStream(IEnumerable<Line> lines, Size imageSize, Color backgroundColor);
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<views:DrawingView x:Name="DrawingViewControl" 
   BackgroundColor="LightGray" 
   HeightRequest="200"
   DefaultLineColor="Red"
   DefaultLineWidth="3"
   Lines="{Binding Lines, Mode=TwoWay}"
   ClearOnFinish="{Binding Source={x:Reference ClearOnFinish}, Path=IsToggled}"
   MultiLineMode="{Binding Source={x:Reference MultiLineMode}, Path=IsToggled}"/>
```

### C# Usage

```cs
new DrawingView
{
   BackgroundColor = Colors.LightGray,
   HeightRequest = 200,
   DefaultLineColor = Colors.Red,
   DefaultLineWidth = 3
}.Bind(DrawingView.Lines, nameof(ViewModel.Lines))
 .Bind(DrawingView.ClearOnFinish, nameof(ViewModel.ShouldClear))
 .Bind(DrawingView.MultiLineMode, nameof(ViewModel.ShouldAllowMultiLine));
```

## Alternatives
[alternatives]: #alternatives

Might be a duplicate of [`Microsoft.Maui.Graphics`](https://github.com/dotnet/Microsoft.Maui.Graphics)?

## Unresolved Questions
[unresolved]: #unresolved-questions

Is `DrawingView` still necessary? Or has it been superseded by [`Microsoft.Maui.Graphics`](https://github.com/dotnet/Microsoft.Maui.Graphics)?

**Comment by VladislavAntonyuk** [comment]
Duplicate #4

**Comment by VladislavAntonyuk** [comment]
DrawingView allows to draw any shape (draw the line by finger), while Maui Graphics has predefined shapes: lines, rectangles.

**Comment by brminnick** [comment]
@jsuarezruiz Could you confirm whether or not `Microsoft.Maui.Graphics` will make  DarwingView obsolete?

**Comment by VladislavAntonyuk** [comment]
@jsuarezruiz maybe DrawingView can be a part of Maui Graphics? Or it is not enough stable yet?

**Comment by brminnick** [comment]
May be duplicate of GraphicsView: https://github.com/dotnet/maui/pull/923

**Comment by VladislavAntonyuk** [comment]
@brminnick I don't think it is a duplicate.
Maui.Graphics provides control to draw - GraphicsView (consider it to be a paper), But DrawingView actually draws on it (like a pencil).
We can use controls from Maui.Graphics (https://github.com/dotnet/Microsoft.Maui.Graphics/blob/main/src/Microsoft.Maui.Graphics/Android/NativeGraphicsView.cs) instead of implementing our own (https://github.com/VladislavAntonyuk/Maui/commit/23503b47026f1e99416f8a38f5d3a717dbfc2fa1#diff-ba611d8a56be8ce1566b9bd46df26cd055b8fbc3fb05df9560d7ecb8cb48ecbcR24)
