### ISSUE TITLE
[BUG] Shell Search leaves screen darkened after navigation

### ISSUE THREAD

**Issue by RonPeters** [CommunityToolkit/Maui#1082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When I navigate to a detail page from a collection view, it looks fine. When I navigate to the same page via shell search handler, the page is darkened, like there is an opacity or overlay.

### Expected Behavior

The target page should look the same regardless of navigation technique.

### Steps To Reproduce

Using C# Markup:
```
Shell.SetSearchHandler(this, new PropertiesSearchHandler(viewModel.Properties.AsReadOnly())
{
    Placeholder = "Search",
    ShowsResults = true,
});
```

**Collection View Page**
![Screenshot_1678413503](https://user-images.githubusercontent.com/76271129/224203812-7287b0ee-a96f-479d-b0ba-0655ebead5f3.png)

**Detail Page**
![Screenshot_1678413552](https://user-images.githubusercontent.com/76271129/224203866-4b33f6d7-35dc-4e2f-8ddd-177dd195ed2f.png)

**Search**
![Screenshot_1678413574](https://user-images.githubusercontent.com/76271129/224203906-427b70a0-130b-4a5e-8bc1-4518b87e8fcf.png)

**Navigate from Search**
![Screenshot_1678413586](https://user-images.githubusercontent.com/76271129/224203939-d1ef5fa7-4b3a-4379-889f-c87a6fd3bc0f.png)

### Link to public reproduction project repository

Can provide if needed

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.0.0
- OS: Android Emulator, Pixel 5 API 33
- .NET MAUI: 7.0.59.0
```

**Comment by pictos** [comment]
@RonPeters this looks like to be a .NET MAUI issue, I didn't see any MCT element on your report. Please open this issue on the .NET MAUI repo.

**Comment by RonPeters** [comment]
@pictos Sure enough, I posted this on the wrong repo. Apologies.
