### ISSUE TITLE
FolderPicker: Default folder selection is disabled! [BUG] 

### ISSUE THREAD

**Issue by true-perfect-code** [CommunityToolkit/Maui#1085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

1.
When you open FolderPicker, the default folder is selected. Unfortunately, you cannot select / use this folder because the selection button is deactivated (see picture)! The only thing you can do is to go back one folder and then select the previous folder again, but you can't trust a user to do that!

2.
Setting a default folder does not work
`folder = await FolderPicker.PickAsync(@"C:\Users\user\Documents\", token);`

![image](https://user-images.githubusercontent.com/45635963/224334463-9d47e0c0-fcb3-44f1-a20c-bcf66680505f.png)

### Expected Behavior

Go back one folder and then reselect the previous folder again.

### Steps To Reproduce

```
    private async Task OnCLick_OpenFolder()
    {
        CancellationTokenSource source = new CancellationTokenSource();
        CancellationToken token = source.Token;

        CommunityToolkit.Maui.Storage.FolderPickerResult folder;
        try
        {
            folder = await FolderPicker.PickAsync(token);
            // or  folder = await FolderPicker.PickAsync(@"C:\Users\user\Documents\", token);
            
            if (folder.IsSuccessful)
            {

            }
        }
        catch (Exception)
        { 
            throw;
        }
    }
```

### Link to public reproduction project repository

no link

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.0
- OS: Windows
- .NET MAUI: 7
```

**Comment by VladislavAntonyuk** [comment]
Windows doesn't support selecting folders by path.
This is a Windows control and we don't have access to it. Click on "tmp" to enable the button
