### ISSUE TITLE
[BUG] MediaElement crashes on IOS when added to view tree outside of the constructor

### ISSUE THREAD

**Issue by danielftz** [CommunityToolkit/Maui#1099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When trying to add a MediaElement object into a layout object outside of the constructor and deployed on IOS, the app crashes. 

i.e.

```
Loaded += (s, e) =>
{
    MediaElement ele = new MediaElement
    {
        Source = MediaSource.FromUri("https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"),
        ShouldShowPlaybackControls = true,
    };

    AbsoluteLayout.SetLayoutFlags(ele, AbsoluteLayoutFlags.PositionProportional);
    AbsoluteLayout.SetLayoutBounds(ele, new Rect(0.5, 0.5, 300, 300));

    _view.Add(ele);
};

```

### Expected Behavior

App should not crash

### Steps To Reproduce

See example project
https://github.com/danielftz/BugExample.MCTMediaElement

### Link to public reproduction project repository

https://github.com/danielftz/BugExample.MCTMediaElement

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.0.0
- .NET MAUI CommunityToolkit MediaElement: 1.0.2
- OS: IOS 16.2
- .NET MAUI: Latest Stable
- Visual Studio For Mac: Latest Stable
```

**Comment by danielftz** [comment]
Any updates on this?

**Comment by vhugogarcia** [comment]
Hello @danielftz , the sample app is not crashing anymore on iOS, and the video plays OK on .NET MAUI 8 by using the latest version of the MAUI Community Toolkit 7.0.0. See screenshot below.

I'm also attaching the shared sample updated to .NET MAUI 8 for further references.
[BugExample.MCTMediaElement-MAUI-8.zip](https://github.com/CommunityToolkit/Maui/files/13528035/BugExample.MCTMediaElement-MAUI-8.zip)

![image](https://github.com/CommunityToolkit/Maui/assets/1047398/39f4bb22-1c50-4db8-a8f9-4241904acde6)
