### ISSUE TITLE
Add  from Xamarin.Essentials: `Contacts`, `FilePicker`, `MediaPicker` and `WebAuthenticator`

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#11]
The following APIs are included in Xamarin.Essentials, but will not be included in the first release of .NET MAUI Essentials:
- [ ] Contacts -[Working Branch](https://github.com/CommunityToolkit/Maui/tree/Add-Xamarin.Essentials.Contacts)
- [ ] FilePicker - [Working Branch](https://github.com/CommunityToolkit/Maui/tree/Add-Xamarin.Essentials.FilePicker)
- [ ] MediaPicker - [Working Branch](https://github.com/CommunityToolkit/Maui/tree/Add-Xamarin.Essentials.MediaPicker)
- [ ] WebAuthenticator - [Working Branch](https://github.com/CommunityToolkit/Maui/tree/Add-Xamarin.Essentials.WebAuthenticator)

To avoid breaking changes to developers using these Xamarin.Essentials APIs, let's bring them into the .NET MAUI Toolkit. This will also allow us to improve upon the existing APIs, making them more robust, to one day add them into .NET MAUI Essentials.

**Comment by brminnick** [comment]
Temporarily Blocked by Internal APIs

Awaiting approval of this Pull Request: https://github.com/dotnet/maui/pull/1969

**Comment by maxkoshevoi** [comment]
What was the reason for not including them into MAUI? Are they not stable or optimized?

**Comment by brminnick** [comment]
Good question! 

Yup - we had a few concerns over the stability and flexibility of the APIs and figured it'd be best to let them first mature in the MAUI Toolkit, and then eventually bring them to `Microsoft.Maui.Essentials`

**Comment by dimonovdd** [comment]
Hi. I would be happy to help with this issue. But I have a different opinion on this matter: 
1) This library should not depend on MAUI. Developers will need the ability to use it in native .NET 6 projects
2) If we want to cut up Essentials, then let's leave only a most important APIs there such as MainThread

**Comment by dimonovdd** [comment]
Hi @jamesmontemagno  thank you for your reply.
And yet, if you have really good reasons to bring it to the toolkit, then we should make a separate toolkit without MAUI for Essentials.

**Comment by dimonovdd** [comment]
If we create a separate toolkit for these APIs, then in the future we will be able to add new APIs (Calendar, AudiRecorder and etc.)

**Comment by maxkoshevoi** [comment]
Off topic: 
Good candidate for Calendar API https://github.com/TheAlmightyBob/Calendars

**Comment by dimonovdd** [comment]
> Off-topic:
> Good candidate for Calendar API https://github.com/TheAlmightyBob/Calendars

https://github.com/xamarin/Essentials/pull/1406

**Comment by brminnick** [comment]
Hi Friends. Please open a [Discussion](https://github.com/CommunityToolkit/Maui/discussions) to discuss creating a second Toolkit. 

Let's keep this Feature Request focused on the `Contacts`, `FilePicker`, `MediaPicker` and `WebAuthenticator` APIs.

**Comment by brminnick** [comment]
These features will remain in Maui.Essentials
