### ISSUE TITLE
[Proposal] GravatarImageSource

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#110]
# GravatarImageSource

* [x] Proposed
* [x] Prototype
* [ ] Implementation: Not Started
  * [ ] iOS Support
  * [ ] Android Support
  * [ ] macOS Support
  * [ ] Windows Support
* [ ] Unit Tests: Not Started
* [ ] Sample: Not Started
* [ ] Documentation: Not Started

## Summary
[summary]: #summary

Allows the use of Gravatar Images

## Detailed Design
[design]: #detailed-design

### GravatarImageSource.shared.cs
```cs
public class GravatarImageSource : ImageSource
{
  public static readonly BindableProperty EmailProperty;
  public static readonly BindableProperty SizeProperty;
  public static readonly BindableProperty DefaultProperty;
  public static readonly BindableProperty CachingEnabledProperty;
  public static readonly BindableProperty CacheValidityProperty;
  
  public string? Email { get; set; }
  public int Size { get; set; }
  public DefaultGravatar Default { get; set; }
  public bool CachingEnabled { get; set; }
  public TimeSpan CacheValidity { get; set; }
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<Image>
  <Image.Source>
     <local:GravatarImageSource Email="{Binding Email}"
                                                 Size="{Binding Size}"
                                                 CachingEnabled="{Binding EnableCache}" />
  </Image.Source>
</Image>
```

### C# Usage

```cs
new Image
{
  Source = new GravatarImageSource
                    .Bind(GravatarImageSource.EmailProperty, nameof(ViewModel.Email))
                    .Bind(GravatarImageSource.SizeProperty, nameof(ViewModel.Size))
                    .Bind(GravatarImageSource.CachingEnabled, nameof(ViewModel.EnableCache))
};
```

**Comment by GeorgeLeithead** [comment]
I looked at this proposal and having worked on AvatarView, I thought I would have a look as it appeared to be in the same "ball park".  Taking advantage of the fact that when an `Image` control has its _source_ property set, it's `FromUri` returns an `UriImageSource` that downloads and reads an image from a specified URI, we can then take advantage of the this as it supports Image Caching.

See [Load a remote image](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/image#load-a-remote-image).

As such I have produced a working fork and branch, that adds Gravatar as an enhancement to AvatarView. There are still a couple items to resolve, but it can be found here, along with a samples page.  There are as yet no unit tests and no documentation:

[110-GravatarView](https://github.com/GeorgeLeithead/CommunityToolkitMaui/tree/110-GravatarView)

Some example screenshots from the above:
![Screenshot_1659025915](https://user-images.githubusercontent.com/43666574/181594268-024b7d09-6fd9-442e-ad56-934e6aaff09c.png) 
![Screenshot_1659025974](https://user-images.githubusercontent.com/43666574/181594309-786386e2-8f20-4661-a954-d8840155c502.png) 
![Screenshot-Windows2](https://user-images.githubusercontent.com/43666574/181594332-47fa91fe-db2d-4858-847c-9afca332695d.png) 
![Screenshot-Windows2](https://user-images.githubusercontent.com/43666574/181594364-33e67696-cbb1-4175-a166-720bdd50e5f8.png)

**Comment by brminnick** [comment]
Thanks @GeorgeLeithead! This hasn’t yet been approved. I’ll raise it in our next standup 👍

**Comment by GeorgeLeithead** [comment]
> Thanks @GeorgeLeithead! This Proposal hasn’t yet been approved. I’ll raise it in our next standup 👍 

@brminnick I could see it wasn't yet approved, but I thought I'd strike whilst my AvatarView iron was still hot, and I worked on the clipping bug.

**Comment by dansiegel** [comment]
This is a great direction @GeorgeLeithead

**Comment by GeorgeLeithead** [comment]
> This is a great direction @GeorgeLeithead 

@dansiegel You'll notice in the sample, I kept using your Gravatar. Got to keep and give appreciation for the original effort. 😁

**Comment by bijington** [comment]
I'm happy to vote to approve it now. More than happy to accept the contribution. 

It's a yes from me

✅

**Comment by GeorgeLeithead** [comment]
@dansiegel I'd really like to keep referencing *your* Gravatar in the sample.  However, I don't just want to assume this is OK, and I wanted check with you and verify that is, OK?

**Comment by bijington** [comment]
I am going to champion this proposal, we have the standup this coming Thursday so if others haven't found time to vote I will raise it and expect it to get approved.

The general design looks good to me. Only one small point I have is to suggest we rename `CachingEnabled` to `IsCachingEnabled` to fit with common naming conventions

**Comment by dansiegel** [comment]
@GeorgeLeithead I appreciate you, and thanks for asking. Yes you do have my permission to continue using my gravatar for the sample.

**Comment by GeorgeLeithead** [comment]
> I am going to champion this proposal, we have the standup this coming Thursday so if others haven't found time to vote I will raise it and expect it to get approved.
> 
> The general design looks good to me. Only one small point I have is to suggest we rename `CachingEnabled` to `IsCachingEnabled` to fit with common naming conventions

@bijington I can very easily change `CachingEnabled` to `IsCachingEnabled` and agree with the reasoning.  However, the properties I used were taken directly from the `UriImageSource` control, so not sure if this may introduce some end user confusion?  In this instance I would vote for making the change to `IsCachingEnabled` but want to make sure.

**Comment by bijington** [comment]
@GeorgeLeithead you make a good point here... Let's seek a collective vote on that from the team too.

**Comment by GeorgeLeithead** [comment]
API definition

### AvatarView.shared.cs
```csharp
public class AvatarView : Border, IAvatarView, IBorderElement, IFontElement, ITextElement, IImageElement, ITextAlignmentElement, ILineHeightElement, ICornerElement
{
	public static readonly BindableProperty BorderColorProperty;
	public static readonly BindableProperty BorderWidthProperty;
	public static readonly BindableProperty CornerRadiusProperty;
	public static readonly BindableProperty DefaultGravatarProperty;
	public static readonly BindableProperty FontAttributesProperty;
	public static readonly BindableProperty FontAutoScalingEnabledProperty;
	public static readonly BindableProperty FontFamilyProperty;
	public static readonly BindableProperty FontSizeProperty;
	public static readonly BindableProperty? GravatarEmailProperty;
	public static readonly BindableProperty ImageSourceProperty;
	public static readonly BindableProperty TextColorProperty;
	public static readonly BindableProperty TextProperty;
	public static readonly BindableProperty TextTransformProperty;

	public Color BorderColor { get; set; }
	public double BorderWidth { get; set; }
	public double CharacterSpacing { get; set; }
	public CornerRadius CornerRadius { get; set; }
	public DefaultGravatarImage DefaultGravatar { get; set; }
	public FontAttributes FontAttributes { get; set; }
	public bool FontAutoScalingEnabled { get; set; }
	public string FontFamily { get; set; }
	public double FontSize { get; set; }
	public string? GravatarEmail { get; set; }
	public ImageSource ImageSource { get; set; }
	public string Text { get; set; }
	public Color TextColor { get; set; }
	public TextTransform TextTransform { get; set; }
}
```

### Usage Syntax
#### XAML usage
```xml
<ContentPage
	x:Class="MyApp.MyPage"
	xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
	xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
	xmlns:mct="clr-namespace:CommunityToolkit.Maui.Controls;assembly=CommunityToolkit.Maui">
	<StackLayout>
		<mct:AvatarView
			BorderColor="{Binding BorderColor}"
			BorderWidth="{Binding BorderWidth}"
			CornerRadius="{Binding CornerRadius}"
			DefaultGravatar="{Binding DefaultGravatarImage}"
			FontAttributes="{Binding FontAttributes}"
			FontSize="{Binding FontSize}"
			GravatarEmail="{Binding Email}"
			Text="{Binding Text}"
			TextColor="{Binding TextColor}">
				<mct:AvatarView.ImageSource>
					<UriImageSource CacheValidity="{Binding CacheValidityTimespan}" CachingEnabled="{Binding EnableCache}" />
				</mct:AvatarView.ImageSource>
		</mct:AvatarView>
	</StackLayout>
</ContentPage>
```

#### C# Usage
```csharp
class MyPage : ContentPage
{
	public MyPage()
	{
		Content = ContentPage
		{
			new AvatarView
			{
				BorderColor = Colors.Yellow,
				BorderWidth = 2,
				CornerRadius = new CornerRadius(32),
				DefaultGravatar = DefaultGravatarImage.MosterId,
				FontAttributes = FontAttributes.Bold,
				FontSize = 18,
				GravatarEmail = "dsiegel@avantipoint.com",
				Text = "ZS", // Zoe Saldana
				TextColor = Colors.Yellow,
				ImageSource = new UriImageSource {
					Uri = new Uri("https://aka.ms/campus.jpg"),
					CachingEnabled = true,
					CacheValidity = new TimeSpan(7,0,0)
				}
			},			
		}
	}
}
```

**Comment by brminnick** [comment]
Hey George! We don't need to add anything from GravatarImageSource into AvatarView. 

AvatarView already has the property `public ImageSource ImageSource { get; set; }` and since `GravatarImageSource : ImageSource`, users are already able to use `GravatarImageSource` for their `AvatarView.ImageSource`.

**Comment by bijington** [comment]
> Gravatar allows users to self-rate their images so that they can indicate if an image is appropriate for a certain audience. By default, only 'G' rated images are displayed unless you indicate that you would like to see higher ratings.
> 
> Should we add a property (linked to enum) to allow the developer to specify higher ratings? I do not believe that it is our place to dictate that the developer 'cant' use higher rating images?
> 
> * g: suitable for display on all websites with any audience type.
> * pg: may contain rude gestures, provocatively dressed individuals, the lesser swear words, or mild violence.
> * r: may contain such things as harsh profanity, intense violence, nudity, or hard drug use.
> * x: may contain hardcore sexual imagery or extremely disturbing violence.

I am ok with shipping with the default approach (only g) at least in the initial version. If someone really needs something above a G rating then we could look at it then or there is the possibility of inheriting from our implementation and providing support for it

**Comment by GeorgeLeithead** [comment]
API definition

### GravatarImageSource.shared.cs
```csharp
public class GravatarImageSource : ImageSource, IGravatarImageSource
{
	public static readonly BindableProperty CacheValidityProperty;
	public static readonly BindableProperty CachingEnabledProperty;
	public static readonly BindableProperty? EmailProperty;
	public static readonly BindableProperty ImageProperty;

	public DefaultImage Image { get; set; }
	public string? Email { get; set; }
	public TimeSpan CacheValidity { get; set; }
	public bool CachingEnabled{ get; set; }
}
```

### Usage Syntax
#### XAML usage
```xml
<ContentPage
	x:Class="MyApp.MyPage"
	xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
	xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
	xmlns:mct="clr-namespace:CommunityToolkit.Maui.Controls;assembly=CommunityToolkit.Maui">
	<StackLayout>
        <Image>
            <Image.Source>
                <mct:GravatarImageSource
                    CacheValidity="{Binding CacheValidityTimespan}"
                    CachingEnabled="{Binding EnableCache}"
                    Email="{Binding Email}"
                    Image="{Binding DefaultGravatarSelected}" />
            </Image.Source>
        </Image>
	</StackLayout>
</ContentPage>
```

#### C# Usage
```csharp
class MyPage : ContentPage
{
	public MyPage()
	{
		Content = new Image()
		{
			Source = new GravatarImageSource()
			{
				CacheValidity = new TimeSpan(1, 0, 0, 0),
				CachingEnabled = true,
				Email = "dsiegel@avantipoint.com",
				Image = Core.DefaultImage.MysteryPerson,
			},
		};
	}
}
```

**Comment by bijington** [comment]
@GeorgeLeithead to your points about issue/approach I will aim to look through them a bit more thoroughly this week but I'll need to do some reading so I fully understand things.

In the meantime my first initial questions back would be:

- If we can't inherit from `UriImageSource` could we encapsulate it and expose the bits we need?
- If not on the above do our ImageSourceServices provide anything different to the .NET MAUI ones? If not can we 'just' use those?

Like I said I'll come back with a more in depth response over this week.

**Comment by pictos** [comment]
I did some tests on my end, and realise that at the end of the day, the `GravatarImage` is just a URL so [I created a very silly ](https://gist.github.com/pictos/2df3ced9b4d78c58c5c5133940715a5b)implementation (that works) and set the `Image.Source` to the generated URL. And I know that in XCT we have a `GravatarImageSource` and all that jazz, but we can make things simpler here.

So my question is, Why do we not use the `UriImageSource`? We can create a converter or some kind of helper that will handle and generate the URL schema. And will be much easier to maintain than the full `ImageSourceHandler` implementation

**Comment by dansiegel** [comment]
I think perhaps the best way to do this is to register a custom IGravatarImageSourceService... which can then convert the GravatarImageSource to a UriImageSource. I've done something similar for another custom imagesource that I did for Maui.
```cs
public class GravatarImageSource : ImageSource, IImageSource
{
    // implement interface with bindable properties include getter & setter
}

public interface IGravatarImageSource : IImageSource
{
    TimeSpan CacheValidity { get; }
    bool CachingEnabled { get; }
    string? Email { get; }
    DefaultGravatar Default { get; }
}

public class GravatarImageSourceService : IImageSourceService<IGravatarImageSource>
{
    private UriImageSourceService _baseService { get; }
    public GravatarImageSourceService(UriImageSourceService baseService)
    {
        _baseService = baseService;
    }
    
    // Implement as required per platform...
    // Convert to UriImageSource... pass to UriImageSourceService... return result
}

builder.ConfigureImageSources(images => images.AddService<IGravatarImageSource, GravatarImageSourceService>());

**Comment by pictos** [comment]
@dansiegel but why do we need to implement it per platform? Like if we have a converter o something like that will be just one implementation and will hook up into the shared layer.

In this case, I'm assuming that we just need to care about the `Image` control, that has the Source property, so we can just provide the right gravatar URL and let the built-in `UriImageSource` handle the rest. It already has cache, loading stuff, etc. I'm advocating here to keep the code simple, so it will be easier to maintain

**Comment by dansiegel** [comment]
@pictos you could do a XAML Extension that returns a UriImageSource certainly that would be pretty easy but it would create an API that isn't particularly friendly for those building UI in code. Maintaining this as an ImageSource keeps it clean where you can use it anywhere an image source can be used and a XAML extension becomes syntax sugar...

Because UriImageSource is sealed this can not use UriImageSource as a base class. The best course then is to provide it as an image source. This means the best hook with the minimal code to handle the caching and everything else is as I showed above

**Comment by GeorgeLeithead** [comment]
With guidance from @dansiegel and help from @bijington we should now have this licked. All in the draft PR if you fancy a look see.
