### ISSUE TITLE
[BUG] Media opacity cannot be changed

### ISSUE THREAD

**Issue by mikejos** [CommunityToolkit/Maui#1101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Setting the Opacity property on MediaElement to any value - 0.1, 0.5, etc. - does not affect the opacity of the playing video.

### Expected Behavior

I expect the opacity of the playing video to change based on the Opacity property

### Steps To Reproduce

1. Open the solution from the repository and run it
2. You will see 2 media elements
4. The top one has Opacity set to 0.5
5. The bottom one has Opacity set to 1.0
6. Play both videos
7. Video opacity is the same for both (100%)  (although the playback control panels are affected by the Opacity setting)

### Link to public reproduction project repository

https://github.com/mikejos/MauiAppTestMediaElement 

### Environment

```markdown
.NET MAUI CommunityToolkit: 5.0.0
.NET MAUI MediaElement: 1.0.2
OS: Windows 11
.NET MAUI: 7.0.0
```

**Comment by ramonB1996** [comment]
Can confirm this on `Android Emulator`. Opacity will only change the Playbackcontrols-Opacity, not of the video itself. Even wrapping the `MediaElement` in a Layout with Opacity will not change the Opacity of the video.

**Comment by ne0rrmatrix** [comment]
If you put media element in a grid, disable controls, and add a frame you can dim the video using:
```
 <Grid>
<toolkit:MediaElement
            x:Name="mediaElement"
            ShouldAutoPlay="True"
            ShouldKeepScreenOn="True"
            ShouldShowPlaybackControls="False" />
<Frame
            BackgroundColor="Black"
            IsEnabled="{Binding Source= YourVariable}"
            IsVisible="{Binding Source= YourVariable}"
            Opacity="0.5" />
 </Grid>
```
This works for windows and android. I imagine it works on ios and mac too. Just not tested. I implemented custom controls inside a content view to get around this problem.

**Comment by jfversluis** [comment]
I would doubt if this is supported by the platforms. There seems to be a decent workaround for this, I don't think we're going to spend our time anytime soon on this edge case. If someone does find this important/annoying enough, feel free to take let us know and take it up.
