### ISSUE TITLE
[BUG] Cannot hide actionbar when popup is showing 

### ISSUE THREAD

**Issue by vinhdp195** [CommunityToolkit/Maui#1104]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [x] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When popup is showing, action bar is not hidden

### Expected Behavior

When popup is showing, action bar must be hidden

### Steps To Reproduce

1/ For Android device, Hide Status Bar, Hide Actionbar with code:
Window.DecorView.SystemUiVisibility = (StatusBarVisibility) (SystemUiFlags.ImmersiveSticky | SystemUiFlags.HideNavigation |SystemUiFlags.Fullscreen | SystemUiFlags.Immersive);

2/ Create a button showing popup with code var popup = new SpinnerPopup(); this.ShowPopup(popup);

At Init MainPage, action bar is hidden, but popup is showing then action bar is showing too.

### Link to public reproduction project repository

https://github.com/andreas-nesheim/SpinnerPopup

### Environment

```markdown
- NET MAUI CommunityToolkit: 1.2.0
- OS: Android 10
- .NET MAUI: 6.0.547
```

**Comment by TRybina132** [comment]
Hello, it seems like problem with obsolete method that you're using to hide action bar:
```c#
 Window.DecorView.SystemUiVisibility = (StatusBarVisibility) (SystemUiFlags.ImmersiveSticky | SystemUiFlags.HideNavigation |SystemUiFlags.Fullscreen | SystemUiFlags.Immersive);
 ```
You should try using .AddFlags method to hide action bar: 
```c#
public class MainActivity : MauiAppCompatActivity
{
    protected override void OnCreate(Bundle savedInstanceState)
    {
        base.OnCreate(savedInstanceState);

        Window.AddFlags(WindowManagerFlags.Fullscreen);
    }
}
```

**Comment by bijington** [comment]
Yes you should be able to use the suggestion by @TRybina132 or also check out the solution at: https://github.com/CommunityToolkit/Maui/issues/698#issuecomment-1576013634
