### ISSUE TITLE
[BUG] NullReferenceException on Target when calling CleanUp method in MauiPopup

### ISSUE THREAD

**Issue by duindain** [CommunityToolkit/Maui#1105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I am getting null reference exceptions when closing a popup on WinUI, I currently catch this exception and swallow it

### Expected Behavior

No null reference exceptions coming from the community toolkit when closing a Popup

### Steps To Reproduce

I'm still trying to create a reproducible example so the one I've added is not ready

I believe this is from Opening a popup on Page A
Running some long running tasks
Navigating to another page or having other popups come up in the meantime
Attempting to now close the existing popup page which has possibly already been closed by the framework

### Link to public reproduction project repository

https://github.com/duindain/CommunityPopup

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.0.0
- OS: Windows
- .NET MAUI: 7
```

### Anything else?

The null reference exception is from MauiPopup.windows.cs on Target.ContextFlyout = null;
Target is null which causes the exception

![43671638-6cf2-4977-a944-fd9645222133](https://user-images.githubusercontent.com/4401594/227084660-0d1bd27a-d283-4768-9159-2edd9d210de9.PNG)

**Comment by vrishe** [comment]
Hey, @duindain.

In a similar scenario I am experiencing this exact issue too. Though, my was able to mitigate/avoid after noticing that an explicitly Close'd popup instance is still alive somewhere in fathoms of GC space.  So, basically I made sure that right before closing I unsubscribe from all the codebehind events and set the popup's **BindingContext** to `null`.

**Comment by taimo42** [comment]
I also had this issue.
I created a popup window which executed some tasks and closed automatically after they finished.
I was able to solve it by setting `CanBeDismissedByTappingOutsideOfPopup` to `False`

**Comment by brminnick** [comment]
Hey Gang! Apologies for taking so long to fix this. We have a PR open now to fix the bug.

Along with [@taimo42's recommendation](https://github.com/CommunityToolkit/Maui/issues/1105#issuecomment-1537848214) to set `CanBeDismissedByTappingOutsideOfPopup = false`, I also recommend calling `.Close()` inside of a try/catch block to suppress the `NullReferenceException`.

```cs

var popup = new Popup
{
  CanBeDismissedByTappingOutsideOfPopup = false
};

this.ShowPopup(popup);

await Task.Delay(TimeSpan.FromSeconds(3)); // Display the Popup for 3 seconds

try
{
	popup.Close();
}
catch (NullReferenceException)
{
	// work-around until bug fix PR is merged + released
}
```
