### ISSUE TITLE
[BUG]  DisplayAlert cannot be opened from poupu on IOS

### ISSUE THREAD

**Issue by vcechak** [CommunityToolkit/Maui#1106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When trying to open DisplayAlert from CommunityToolkit popup on iOS nothing happens.

### Expected Behavior

DisplayAlert should be opened.

### Steps To Reproduce

Created testing app with following code:
```
class NewPopup : Popup
{
    public NewPopup()
    {
        var button = new Button() { Text = "Click this"};
        button.Clicked += Button_Clicked;

        Content = new VerticalStackLayout()
        {
            Children =
            {
                button
            }
        };
    }

    private void Button_Clicked(object sender, EventArgs e)
    {
        MainThread.BeginInvokeOnMainThread(async () =>
        {
            await Application.Current.MainPage.DisplayAlert("Title", "Text", "Close");
        });
    }
    }
}
```

Click button -> nothing happens on IOS.
On android DisplayAlert is shown.

### Link to public reproduction project repository

none

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5
- OS: 16.3.1, 16.2
- .NET MAUI:7.0.59
```

### Anything else?

Temporary solution:  https://stackoverflow.com/questions/75242427/in-net-maui-for-ios-can-you-display-an-alert-from-a-community-popup/75249242#75249242?newreg=6a9d47e48b4e4db5929e9c0b73842337

**Comment by marekm294** [comment]
It seems like MAUI problem. MAUI doesn't support show display alert from PresentedViewController.
