### ISSUE TITLE
[BUG] MAUI POPUP is not working similarly in IOS & Android

### ISSUE THREAD

**Issue by sbkrishnan2506** [CommunityToolkit/Maui#1107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Hi ,

I am trying to implement the MAUI popup using the Community Toolkit.
It is working differently in Android & iOS. in Android it is working fine, but in iOS I could not work as same as android.
I am able to show the popup for the full width of the device in android, but in iOS it is not showing for Full width and there is no option.
If we are setting the Vertical option/Horizontal option for the popup view it is working fine in android, but it is not working in iOS, It is always showing in the middle of the screen.
Please find the attached sample code to reproduce.
also find the attached screenshots.

### Expected Behavior

If we set the horizontal option to fill it should be set the full screen of the device in android & iPhone.
If we set the vertical option, it should follow the options.
It is always showing on center only.

### Steps To Reproduce

[BMauiAppNet7.zip](https://github.com/CommunityToolkit/Maui/files/11063401/BMauiAppNet7.zip)

### Link to public reproduction project repository

https://github.com/sbkrishnan2506/MAUI-PopupSample

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS:
- .NET MAUI:
.NET7.0
iPhone
```

### Anything else?

![1679669530669](https://user-images.githubusercontent.com/56611791/227566518-bfe7feb3-bf80-49d6-b0cf-3b64e632d464.jpg)
![Popup2](https://user-images.githubusercontent.com/56611791/227566558-d0865306-8b27-4ea2-bcb9-2c0ef8c098aa.jpg)
![1679669530652](https://user-images.githubusercontent.com/56611791/227566570-78e7aee0-85c9-45a0-a7af-7946052abc1c.jpg)
![Popup](https://user-images.githubusercontent.com/56611791/227566573-bfb12019-f406-4019-986b-520248c4c301.jpg)
![1679669530634](https://user-images.githubusercontent.com/56611791/227566576-98a83c51-9a43-4b33-b880-09ee403b6feb.jpg)
![1679669530613](https://user-images.githubusercontent.com/56611791/227566580-a265cb90-7aae-4038-8f60-1e55ad474175.jpg)
![1679669530687](https://user-images.githubusercontent.com/56611791/227566586-0867eb24-d3b6-48a0-a465-cfc01c58698a.jpg)

**Comment by Bjerghus** [comment]
I had a similar issue with iOS.
It seems that the Popup is compressed and aligned to one side if the content is bigger than the screen width + the size property of the popup is not set.

My workaround was, to set the Size of the popup in the code behind via this
https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/device/display
and then set whatever margin or borders I need in the content view that I put inside the popup.

**Comment by brminnick** [comment]
Fixed in https://github.com/CommunityToolkit/Maui/pull/1320
