### ISSUE TITLE
[BUG] MediaElement 1.0.2 crashes on iOS when exiting full screen mode and using AppShell

### ISSUE THREAD

**Issue by blackforest-tom** [CommunityToolkit/Maui#1110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Using an untouched new MAUI project (using AppShell) with CommunityToolkit.MediaElement 1.0.2 from NuGet and adding a video player (MediaElement tag) it is not possible to exit full screen mode on iOS without the App crashing with the following exception:

```
ObjCRuntime.ObjCException
  Nachricht = Objective-C exception thrown.  Name: UIViewControllerHierarchyInconsistency Reason: child view controller:<AVPlayerViewController: 0x10e94dc00> should have parent view controller:<Microsoft_Maui_Controls_Platform_Compatibility_ShellSectionRootRenderer: 0x10563de00> but actual parent is:<Microsoft_Maui_Platform_PageViewController: 0x1057bd2e0>
Native stack trace:
	0   CoreFoundation                      0x0000000180c63c94 309E77AA-4FF2-35B9-8AF6-33AF9C2B7929 + 601236
	1   libobjc.A.dylib                     0x0000000198489ee4 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000180cb6e84 309E77AA-4FF2-35B9-8AF6-33AF9C2B7929 + 941700
	3   UIKitCore                           0x00000001833be11c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 4919580
	4   UIKitCore                           0x00000001832f8334 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 4109108
	5   UIKitCore                           0x00000001830b8350 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749840
	6   UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	7   UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	8   UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	9   UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	10  UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	11  UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	12  UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	13  UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	14  UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	15  UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	16  UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	17  UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	18  UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	19  UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	20  UIKitCore                           0x0000000183086604 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1545732
	21  AVKit                               0x0000000199d26874 D49827F4-890B-380B-AF26-74D929D46993 + 714868
	22  UIKitCore                           0x00000001830702c4 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1454788
	23  AVKit                               0x0000000199d2596c D49827F4-890B-380B-AF26-74D929D46993 + 711020
	24  AVKit                               0x0000000199d43358 D49827F4-890B-380B-AF26-74D929D46993 + 832344
	25  UIKitCore                           0x0000000183396fd0 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 4759504
	26  UIKitCore                           0x00000001831d5500 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 2917632
	27  UIKitCore                           0x00000001832480c4 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 3387588
	28  UIKitCore                           0x00000001832ceb84 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 3939204
	29  UIKitCore                           0x0000000183172278 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 2511480
	30  UIKitCore                           0x000000018379d3cc 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 8979404
	31  UIKitCore                           0x0000000183219234 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 3195444
	32  UIKitCore                           0x0000000183134764 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 2258788
	33  UIKitCore                           0x0000000183062ea4 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1400484
	34  UIKitCore                           0x0000000183063570 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1402224
	35  UIKitCore                           0x000000018306373c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1402684
	36  CoreFoundation                      0x0000000180c0f78c 309E77AA-4FF2-35B9-8AF6-33AF9C2B7929 + 255884
	37  CoreFoundation                      0x0000000180be09b4 309E77AA-4FF2-35B9-8AF6-33AF9C2B7929 + 63924
	38  CoreFoundation                      0x0000000180bdbf3c 309E77AA-4FF2-35B9-8AF6-33AF9C2B7929 + 44860
	39  CoreFoundation                      0x0000000180bef194 CFRunLoopRunSpecific + 572
	40  GraphicsServices                    0x00000001a1726988 GSEventRunModal + 160
	41  UIKitCore                           0x00000001833f2a88 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 5134984
	42  UIKitCore                           0x000000018318bfc8 UIApplicationMain + 336
	43  VideoPlaybackTest                   0x0000000104abc5a4 xamarin_UIApplicationMain + 60
	44  VideoPlaybackTest                   0x0000000104ddc6f0 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2368984
	45  VideoPlaybackTest                   0x0000000104ddb410 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2364152
	46  VideoPlaybackTest                   0x0000000104dd0dec _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2321620
	47  VideoPlaybackTest                   0x0000000104dce9c0 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2312360
	48  VideoPlaybackTest                   0x0000000104d9f9c8 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2119856
	49  VideoPlaybackTest                   0x0000000104cee9c0 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1394856
	50  VideoPlaybackTest                   0x0000000104cf5268 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1421648
	51  VideoPlaybackTest                   0x0000000104da4bc4 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2140844
	52  VideoPlaybackTest                   0x0000000104ae7528 xamarin_get_original_working_directory_path + 4016
	53  VideoPlaybackTest                   0x0000000104e0ad8c _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2559092
	54  dyld                                0x00000001054984d0 start + 444

  Quelle = Microsoft.iOS
  Stapelüberwachung:
   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at VideoPlaybackTest.Program.Main(String[] args) in D:\Code\test\VideoPlaybackTest\VideoPlaybackTest\Platforms\iOS\Program.cs:line 13

```

### Expected Behavior

The app should not crash when exiting full screen on iOS devices.

### Steps To Reproduce

1. Open and run the solution from the provided repository
2. Run the app on an iOS device
3. Enter and exit full screen mode of the video.

### Link to public reproduction project repository

https://github.com/blackforest-tom/maui-mediaelement-bug-102

### Environment

```markdown
- .NET MAUI CommunityToolkit.MediaElement: 1.0.2
- OS: iOS 15.7.1
- .NET MAUI: 7.0.59
```

### Anything else?

The issue is **not reproducible if you use MediaElement v1.0.1**, or if you swap out the AppShell and directly instantiate the MainPage by changing
`		MainPage = new AppShell();`
to
`		MainPage = new MainPage();`
in App.xaml.cs

**Comment by dj-dev** [comment]
I am also seeing this on iOS after updating to v1.0.2. It wasn't happening before updating to this version.

Same as reported by @blackforest-tom, the issue happens when MainPage is defined as:
`MainPage = new AppShell();`

Copy of the exception message:
`ObjCRuntime.ObjCException: 'Objective-C exception thrown.  Name: UIViewControllerHierarchyInconsistency Reason: child view controller:<AVPlayerViewController: 0x11c974400> should have parent view controller:<Microsoft_Maui_Platform_PageViewController: 0x11bb04c10> but actual parent is:<Microsoft_Maui_Controls_Platform_Compatibility_ShellFlyoutRenderer: 0x1056c8ab0>`

**Comment by dplattipswich** [comment]
I am encountering the same problem using MediaElement 1.0.2. Swapping out the AppShell and directly instantiating the MainPage, as discussed above in the "Anything Else" section, made it go away for me. I'm not doing anything important in the AppShell anyway. 

Although I did encounter one strange thing. I am using a custom image for a slider thumb. It worked properly with simple declaration in the XAML. However, when I made the change away from the AppShell, that custom image appeared correctly the first time the app appeared on the screen. But when the user moves the app to background and then brings it back to the foreground, the custom image was gone, replaced by the original default purple dot. Really strange. Probably has something to do with resource processing in the AppShell. I was able to work around it by explicitly resetting the property in my OnAppearing method. Hope this helps.

**Comment by MateuszLas421** [comment]
Any information, changes?  Anyone knows how to solve this in AppShell ?

**Comment by jfversluis** [comment]
Would you be able to test the resulting NuGet package from [this PR](https://github.com/CommunityToolkit/Maui/pull/1279) and see if that revolves your issue?

If you're not sure how to do that, please review [this wiki article](https://github.com/CommunityToolkit/Maui/wiki/Preview-Packages#pull-requests-).

**Comment by MateuszLas421** [comment]
Version: 1.0.0-build-1279.95284+9eb8d25

This problem persists. Maybe I'll describe what my case looks like. I have a ScrollView with a CarouselView containing pictures and recordings. I can move the pictures and recordings right left. On Android it works without a problem on iOS when swiping to recordings the app crashes

`ObjCRuntime.ObjCException: 'Objective-C exception thrown.  Name: UIViewControllerHierarchyInconsistency Reason: child view controller:<AVPlayerViewController: 0x7f8f874acc00> should have parent view controller:<Microsoft_Maui_Controls_Handlers_Items_CarouselViewController: 0x7f8f85caf4f0> but actual parent is:<Microsoft_Maui_Controls_Platform_Compatibility_ShellFlyoutRenderer: 0x7f8f84fb44f0>
Native stack trace:
	0   CoreFoundation                      0x000000010e0da78b __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x000000011d5aeb73 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010e0da669 -[NSException initWithCoder:] + 0
	3   UIKitCore                           0x000000012adf8222 -[UIView(Hierarchy) _associatedViewControllerForwardsAppearanceCallbacks:performHierarchyCheck:isRoot:] + 299
	4   UIKitCore                           0x000000012adf8af0 -[UIView(Hierarchy) _willMoveToWindow:withAncestorView:] + 257
	5   UIKitCore                           0x000000012adf99c0 _makeSubTreePerformSelector + 661
	6   UIKitCore                           0x000000012adf9a0a _makeSubTreePerformSelector + 735
	7   UIKitCore                           0x000000012adf9a0a _makeSubTreePerformSelector + 735
	8   UIKitCore                           0x000000012ae095da -[UIView(Internal) _addSubview:positioned:relativeTo:] + 502
	9   libxamarin-dotnet-debug.dylib       0x000000010b461149 xamarin_dyn_objc_msgSend + 217
	10  ???                                 0x000000015edceca7 0x0 + 5886504103
	11  libmonosgen-2.0.dylib               0x000000010bc283fa ves_pinvoke_method + 474
	12  libmonosgen-2.0.dylib               0x000000010bc1a675 interp_exec_method + 3717
	13  libmonosgen-2.0.dylib               0x000000010bc17e23 interp_runtime_invoke + 259
	14  libmonosgen-2.0.dylib               0x000000010ba3d258 mono_runtime_invoke_checked + 136
	15  libmonosgen-2.0.dylib               0x000000010ba40ece mono_runtime_invoke + 142
	16  libxamarin-dotnet-debug.dylib       0x000000010b45850f xamarin_invoke_trampoline + 6335
	17  libxamarin-dotnet-debug.dylib       0x000000010b45fde9 xamarin_arch_trampoline + 105
	18  libxamarin-dotnet-debug.dylib       0x000000010b460fca xamarin_x86_64_common_trampoline + 118
	19  UIKitCore                           0x0000000129cbd586 -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:] + 1248
	20  UIKitCore                           0x0000000129cbd0a0 -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:] + 31
	21  UIKitCore                           0x0000000129cc85c7 -[UICollectionView _createVisibleViewsForSingleCategoryAttributes:limitCreation:fadeForBoundsChange:] + 1774
	22  UIKitCore                           0x0000000129cc8b0b -[UICollectionView _createVisibleViewsForAttributes:fadeForBoundsChange:notifyLayoutForVisibleCellsPass:] + 376
	23  UIKitCore                           0x0000000129cc67c3 -[UICollectionView _updateVisibleCellsNow:] + 2372
	24  UIKitCore                           0x0000000129ccdad0 -[UICollectionView layoutSubviews] + 375
	25  UIKitCore                           0x000000012ae10083 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2313
	26  QuartzCore                          0x000000011ce1ed98 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 526
	27  QuartzCore                          0x000000011ce2a849 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 65
	28  QuartzCore                          0x000000011cd3a15e _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 624
	29  QuartzCore                          0x000000011cd70805 _ZN2CA11Transaction6commitEv + 723
	30  QuartzCore                          0x000000011cd71cb8 _ZN2CA11Transaction25flush_as_runloop_observerEb + 60
	31  CoreFoundation                      0x000000010e037c12 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	32  CoreFoundation                      0x000000010e03257f __CFRunLoopDoObservers + 515
	33  CoreFoundation                      0x000000010e032aa2 __CFRunLoopRun + 1121
	34  CoreFoundation                      0x000000010e032264 CFRunLoopRunSpecific + 560
	35  GraphicsServices                    0x000000012366824e GSEventRunModal + 139
	36  UIKitCore                           0x000000012a7d57bf -[UIApplication _run] + 994
	37  UIKitCore                           0x000000012a7da5de UIApplicationMain + 123
	38  libxamarin-dotnet-debug.dylib       0x000000010b41b64a xamarin_UIApplicationMain + 58
	39  libmonosgen-2.0.dylib               0x000000010bc295c9 do_icall + 345
	40  libmonosgen-2.0.dylib               0x000000010bc280d3 do_icall_wrapper + 291
	41  libmonosgen-2.0.dylib               0x000000010bc1a4cf interp_exec_method + 3295
	42  libmonosgen-2.0.dylib               0x000000010bc17e23 interp_runtime_invoke + 259
	43  libmonosgen-2.0.dylib               0x000000010ba3d258 mono_runtime_invoke_checked + 136
	44  libmonosgen-2.0.dylib               0x000000010ba4526c do_exec_main_checked + 92
	45  libmonosgen-2.0.dylib               0x000000010bb73e12 mono_jit_exec + 354
	46  libxamarin-dotnet-debug.dylib       0x000000010b45fc77 xamarin_main + 1927
	47  App.Mobile                          0x00000001023c7e74 main + 52
	48  dyld                                0x000000010afe5384 start_sim + 10
	49  ???                                 0x0000000202c4c41f 0x0 + 8636384287
'
`

**Comment by jfversluis** [comment]
@MateuszLas421 would you be able to put your scenario in a reproduction project so I'm sure that I'm looking at the right thing? The reproduction attached to this issue seems to work fine (even without the fix)

**Comment by jfversluis** [comment]
@blackforest-tom you're completely right. I was holding it wrong. Looking at it again I can see this happening. Thanks for retrying.

**Comment by MateuszLas421** [comment]
@jfversluis  https://github.com/MateuszLas421/VideoPlayerBug  
Example project that shows the problem with MediaElement as item on iOS

Visual Studio 17.6.4 
XCode 14.3.1

**Comment by briankanelson** [comment]
I am getting the same crash when trying to close Full Screen mode on iOS using MediaElement v3.1.0 on MAUI.
child view controller:<AVPlayerViewController:.xxxxx> should have parent view controller.

On my case, my project is not a Shell app.

Is there any updates or plans to fix this? Or at least, provide a way to hide the FullScreen button, until it is fixed?

**Comment by jfversluis** [comment]
@ne0rrmatrix @vhugogarcia is this a scenario that you saw in all the latest MediaElement developments?

**Comment by ne0rrmatrix** [comment]
> @ne0rrmatrix @vhugogarcia is this a scenario that you saw in all the latest MediaElement developments?

I figured out what the issue was. Will have a PR out in another hour or so with a fix. It was `MediaElement.Handler?.DisconnectHandler();` issue again.

**Comment by briankanelson** [comment]
The issue is marked as closed but I can still reproduce this issue.
For what I see in the changes made, is that the page that holds the MediaElement calls to:

`	protected override void OnNavigatedFrom(NavigatedFromEventArgs args)
	{
		base.OnNavigatedFrom(args);
		MediaElement.Stop();
		MediaElement.Handler?.DisconnectHandler();
	}`

However, I am still getting the crash after exiting full-screen on iOS:
_Unhandled managed exception: Objective-C exception thrown.  Name: UIViewControllerHierarchyInconsistency Reason: child view controller:<AVPlayerViewController: 0x12bcb2000> should have parent view controller:<Microsoft_Maui_Platform_PageViewController: 0x12d878a30> but actual parent is:<Microsoft_Maui_Controls_Platform_ControlsModalWrapper: 0x113362c40>_

@ne0rrmatrix  Is there any other work around for this?

**Comment by ne0rrmatrix** [comment]
Can you try this PR and see if it fixes your issue? https://github.com/CommunityToolkit/Maui/pull/1813

**Comment by ne0rrmatrix** [comment]
Can you try this PR https://github.com/CommunityToolkit/Maui/pull/1813

**Comment by briankanelson** [comment]
Thanks @ne0rrmatrix for that quick response!
Just wondering, is there any planned date of a new release including this fix for MediaElement?

**Comment by briankanelson** [comment]
@jfversluis I didn't tried the fix. I would like to do so. For what I see, the fix is implemented deeply inside the MediaElement class.

On my project, I have the CommunityToolkit.Maui.MediaElement (v 3.1.0).

In order to test the fix, should I replace the usage of that nuget and include all MediaElements files on a separate project inside my solution? or is there any easier way to test this on my project?

**Comment by jfversluis** [comment]
There definitely is an easier method, check this: https://github.com/CommunityToolkit/Maui/wiki/Preview-Packages

**Comment by briankanelson** [comment]
@jfversluis thanks for providigind that. It is very useful.
I was able to download the nugets but not able to install the packages.

I am running Visual Studio for Mac. I think those commands are meant for Windows? Visual Studio for Mac does not seem to have a Nuget Package Console. I used the visual studio Terminal, and instead used:
dotnet add {myproject} package {path}/CommunityToolkit.Maui.99.0.0-build-1813.105074.nupkg 

I am getting this error: error: There are no versions available for the package '/Users/brian/Downloads/nuget/CommunityToolkit.Maui.99.0.0-build-1813.105074.nupkg'.

Am I doing something wrong?

**Comment by briankanelson** [comment]
@jfversluis that is very useful! I followed the instructions. I was able to configure the PR feed and update the nugets using the Package Manager from Visual Studio for Mac. But after removing bin, obj, clean, and rebuild, I am getting this error: Error: One or more duplicate file names were detected.  All image output filenames must be unique: fullscreen (/{path}/.nuget/packages/communitytoolkit.maui.mediaelement/99.0.0-build-1813.105074/buildTransitive/Images/fullscreen.svg), fullscreen (/{path}/.nuget/packages/communitytoolkit.maui.mediaelement/99.0.0-build-1813.105074/buildTransitive/Images/fullscreen.svg)

Any ideas?

**Comment by briankanelson** [comment]
@jfversluis it looks like my core (common) project has a "fullscreen.svg" at the root, but that is being added automatically, even if I manually remove it.

**Comment by ne0rrmatrix** [comment]
I tested both against Main and the #1813 and was unable to replicate the described behavior. The only changed files on the PR do not alter the behavior of file copy. The fullscreen.svg is only copied in media element nuget from my testing. I tested this by building each of the packages from source and then unzipping them and checking the directories. Only media element had the included file. It was in the expected location in BuildTransitive directory. I am not sure how this issue has cropped up. I am unable to replicate.

I tested the nuget package from azure and created a new maui sample app to demonstrate both navigation page and shell page to see if either made any difference. No issues and everything worked as expected. No build issues at all.

Can you try cleaning out your bin and obj directories and build again?

**Comment by ne0rrmatrix** [comment]
I tested with Main, #1813 and the associated nuget packages to see what the behavior was. I tested against windows and mac. On mac it was a mac build host and a physical ipad all controlled from windows. I did test against main, PR, and for the PR I built from source and used nuget from azure feeds.

**Comment by luisabreu84** [comment]
> I tested both against Main and the #1813 and was unable to replicate the described behavior. The only changed files on the PR do not alter the behavior of file copy. The fullscreen.svg is only copied in media element nuget from my testing. I tested this by building each of the packages from source and then unzipping them and checking the directories. Only media element had the included file. It was in the expected location in BuildTransitive directory. I am not sure how this issue has cropped up. I am unable to replicate.
> 
> I tested the nuget package from azure and created a new maui sample app to demonstrate both navigation page and shell page to see if either made any difference. No issues and everything worked as expected. No build issues at all.
> 
> Can you try cleaning out your bin and obj directories and build again?

@ne0rrmatrix Could you please to use the package (3.1.1) in a solution composed by a MAUI Class Library and the main MAUI project. (Add the nuget to both projects) and then just try to build/deploy it. 

With the previous scenario, i'm receiving the error initially described by @briankanelson 
Error: One or more duplicate file names were detected.  All image output filenames must be unique: fullscreen (/Users/admin/.nuget/packages/communitytoolkit.maui.mediaelement/3.1.1/buildTransitive/Images/fullscreen.svg)

<img width="1301" alt="Screenshot 2024-05-04 at 9 13 18 AM" src="https://github.com/CommunityToolkit/Maui/assets/67016876/366dbe3a-6651-4db3-91cb-cd8705a3d023">

any way to solve this?

CC @jfversluis

**Comment by jfversluis** [comment]
Moved the "fullscreen icon bug" into its own issue so we can track it properly: #1862 please move the discussion and any relevant details there, thanks!
