### ISSUE TITLE
[BUG] Microsoft.Maui.Media.mediapicker is asking permission  2 times only in android, iOS working fine.

### ISSUE THREAD

**Issue by sbkrishnan2506** [CommunityToolkit/Maui#1115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Hi,

I tried to use the media picker functionality, Used the media picker from the MAUI essentials. When i click on the CapturePhotoAsync() method it is asking the permission popup 2 times (1 for photos & media, another one for take pictures & record video).

I have added the sample code with both the approaches.

If I tried with the same functionality with Xam.plugin.media it is asking the permission only ones.

### Expected Behavior

It should ask only one permission.

### Steps To Reproduce

1. open the application and run in a android device.
2. Click on the button (Capture Photo MAUI media).
3. you can see the 2 permission popups.

Remove the permission from device settings.
try with Capture photo button it will ask only one permission(Implemented by xam.plugin.media).

### Link to public reproduction project repository

https://github.com/sbkrishnan2506/MAUIMedia

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS:
- .NET MAUI:
Media Picker
Android Permission
```

### Anything else?

![AndroidPermission2](https://user-images.githubusercontent.com/56611791/228140144-3ae81bf2-4171-40ce-847d-58783059ad9a.png)
![AndroidPermission1](https://user-images.githubusercontent.com/56611791/228140152-f70af8b0-d822-467e-8e06-1debab4f1950.png)

**Comment by ramonB1996** [comment]
I tried your repository and I can see the bug you mention. However, you do not do anything with `CommunityToolkit.Maui`, but only use `Xam.Plugin.Media`. 

I think you should move this issue to the right Github-repository.

**Comment by bijington** [comment]
@ramonB1996 is correct this is not the repository you want. You want to raise your issue directly against .NET MAUI here https://github.com/dotnet/maui

This repository is for a toolkit built on top of .NET MAUI

**Comment by sbkrishnan2506** [comment]
Thanks @bijington 
I will report this issue in the repository you mentioned.
