### ISSUE TITLE
[Proposal] LazyView

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#112]
# LazyView

* [x] Proposed
* [x] Prototype:
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Sample
* [x] Documentation: https://github.com/MicrosoftDocs/CommunityToolkit/pull/245

## Summary
[summary]: #summary

The LazyView control allows you to delay the initialization of a View. You need to provide the type of the View that you want to be rendered, using the x:TypeArguments XAML namespace attribute, and handle its initialization using the LoadViewAsync method. The IsLoaded property can be examined to determine when the LazyView is loaded.

> Note: This proposal is a to port the existing LazyView functionality from the Xamarin Community Toolkit
* [Existing Docs](https://learn.microsoft.com/en-us/xamarin/community-toolkit/views/lazyview)
* [Xamarin Community Toolkit Implementation](https://github.com/xamarin/XamarinCommunityToolkit/tree/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/LazyView)

## Motivation
[motivation]: #motivation
LazyView is one of the views that exist in the Xamarin Community Toolkit that has been requested as a missing piece in the migration of some big apps from Xamarin to MAUI.

## Detailed Design
[design]: #detailed-design

### Properties:
Property | Type | Description
-- | -- | --
IsLoaded | bool | Gets the loaded status of the LazyView.

### Methods:
Method | Return Type | Description
-- | -- | --
LoadViewAsync | ValueTask | Initialize the View.
Dispose | void | Cleans up the View, if required.

### BaseLazyView.shared.cs

```cs
public abstract class BaseLazyView : ContentView, IDisposable
{
  internal static readonly BindablePropertyKey IsLoadedPropertyKey = BindableProperty.CreateReadOnly(nameof(IsLoaded), typeof(bool), typeof(BaseLazyView), default);
  public static readonly BindableProperty IsLoadedProperty = IsLoadedPropertyKey.BindableProperty;
  
  public bool IsLoaded => (bool)GetValue(IsLoadedProperty);
  
  protected void SetIsLoaded(bool isLoaded) => SetValue(IsLoadedPropertyKey, isLoaded);
  
  public abstract ValueTask LoadViewAsync();
  
  public void Dispose()
  {
    if (Content is IDisposable disposable)
    disposable.Dispose();
  }
  
  protected override void OnBindingContextChanged()
  {
    if (Content != null && !(Content is ActivityIndicator))
    Content.BindingContext = BindingContext;
  }
}
```

### LazyView.shared.cs

```cs
public class LazyView<TView> : BaseLazyView where TView : View, new()
{
  public override ValueTask LoadViewAsync()
  {
    View view = new TView { BindingContext = BindingContext };
    
    Content = view;
    
    SetIsLoaded(true);
    return new ValueTask(Task.FromResult(true));
  }
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
             x:Class="MyLittleApp.MainPage"
             xmlns:local="clr-namespace:Xamarin.CommunityToolkit.Sample.Pages.Views.TabView">

     <StackLayout>

        <xct:LazyView x:TypeArguments="local:LazyTestView" IsLoaded = "{Binding IsLoaded}" />

    </StackLayout>

</ContentPage>
```

### C# Usage

```cs
new StackLayout
{
  Children = 
  {
    new LazyView<Button>()
      .Bind(LazyView.IsLoadedProperty, nameof(ViewModel.IsLoaded))
  }
};
```

**Comment by ChaplinMarchais** [comment]
@brminnick if this proposal doesn't have anyone working on it yet, my friend @Karuption might be interested in doing the implementation! He has been looking for something to help on!

**Comment by pictos** [comment]
@ChaplinMarchais please, ask him to comment here, that way we can assign this issue to your friend

**Comment by VladislavAntonyuk** [comment]
I don't know details of LazyView, but according to the article DelayedView is LazyView with the overloaded method GetView. 

From the article:
the DelayedView give a far better experience to our user by giving him a simple feedback saying "we acknowledge your action pal, everything is A-OK!".

**Comment by pictos** [comment]
I would say that we should ask permission to the author before we adding the features from `DelayedView`
