### ISSUE TITLE
[BUG] Popup not showing in NavigatedTo event on Shell.

### ISSUE THREAD

**Issue by cat0363** [CommunityToolkit/Maui#1120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

In the NavigatedTo event on the Shell, when I show the Popup it doesn't 
show up and when I close it I get an exception. 

### Expected Behavior

The Popup should be displayed when the Popup is displayed in the NavigatedTo 
event on the Shell. The Popup should be closed without throwing an exception 
when closing the Popup.

### Steps To Reproduce

Please follow the steps below to reproduce.

1. Create MainPage as Shell.
2. Call the Page's ShowPopup method in the NavigatedTo event.
3. Do something.
4. Call the Popup's Close method in the NavigateTo event.

Popup is not displayed at 3.
The following exception occurs at 4.

```
**System.NullReferenceException:** 'Object reference not set to an instance of an object.'

**System.NullReferenceException:** 'Object reference not set to an instance of an object.'

[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
[mono-rt]    at CommunityToolkit.Maui.Views.Popup.CommunityToolkit.Maui.Core.IPopup.OnClosed(Object result) in /_/src/CommunityToolkit.Maui/Views/Popup/Popup.shared.cs:line 268
[mono-rt]    at CommunityToolkit.Maui.Views.Popup.OnClosed(Object result, Boolean wasDismissedByTappingOutsideOfPopup) in /_/src/CommunityToolkit.Maui/Views/Popup/Popup.shared.cs:line 230
[mono-rt]    at CommunityToolkit.Maui.Views.Popup.Close(Object result) in /_/src/CommunityToolkit.Maui/Views/Popup/Popup.shared.cs:line 210
[mono-rt]    at MauiComm_IssueShellPopup.Page2.OnNavigatedTo(NavigatedToEventArgs args) in C:\Users\Tester\source\repos\MauiComm-IssueShellPopup\Page2.xaml.cs:line 27
[mono-rt]    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
[mono-rt]    at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
[mono-rt]    at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 36
[mono-rt]    at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Java.Lang.IRunnable.cs:line 84
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22
[HostConnection] HostConnection::get() New Host Connection established 0xf2968170, tid 29640
[HostConnection] HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_2 
```

### Link to public reproduction project repository

https://github.com/cat0363/MauiComm-IssueShellPopup

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.0.0
- OS: Windows 11 Build 22621.1413
- .NET MAUI: 7.0.59
```

### Anything else?

This problem was described based on Discussion #1116.
This issue occurred on Android 11.0.  Since the build environment has 
not been prepared, it cannot be confirmed on iOS.

Even in the same Navigate To event, if I make the Main Page as a Navigation 
Page instead of Shell, the Popup shows up just fine.

Try changing the code uploaded on github to:

[App.xaml.cs]

    // MainPage = new AppShell(); 
    MainPage = new NavigationPage(new Page1());

[Page1.xaml.cs]

    // await Navigation.PushAsync(new Page2(), false);
    await Shell.Current.Navigation.PushAsync(new Page2(), false);

Below are the execution results of NavigationPage and Shell respectively.

[Execution result on NavigationPage]

https://user-images.githubusercontent.com/125236133/228179615-002a3aca-d252-4ef0-9483-d0f2132652af.mp4

[Execution result on Shell]

https://user-images.githubusercontent.com/125236133/228179580-b8c07818-a980-4a7e-8edf-f6d325cda431.mp4

You can't see it in the video, but in the shell case, it's throwing an exception.

**Comment by bijington** [comment]
You mention that you are using .NET MAUI 6.0 however version 5.0.0 of this toolkit is built for .NET MAUI 7.0. Can you try updating to 7.0 and seeing if this is still an issue? 

Out of interest do you see warnings about version issues between the toolkit and .NET MAUI?

**Comment by cat0363** [comment]
@bijington, The .NET MAUI version I wrote was wrong. 
6.0.552 is incorrect and 7.0.59 is correct. 
The source code on github references 7.0.59 for .NET MAUI.

.NET MAUI is upgraded by the method on the following site.
https://www.youtube.com/watch?v=z68VNaTZk5g

The execution result of the dotnet workload list command is described below.
maui-windows            7.0.59/7.0.100         VS 17.6.33513.286
maui-maccatalyst        7.0.59/7.0.100         VS 17.6.33513.286
maui-ios                7.0.59/7.0.100         VS 17.6.33513.286
maui-android            7.0.59/7.0.100         VS 17.6.33513.286
android                 33.0.26/7.0.100        VS 17.6.33513.286
maccatalyst             16.2.1030/7.0.100      VS 17.6.33513.286
ios                     16.2.1030/7.0.100      VS 17.6.33513.286

**Comment by cat0363** [comment]
@bijington, I forgot to mention it earlier, but this problem also occurs in .NET MAUI 7.0.

**Comment by cat0363** [comment]
I checked the Popup class implementation in CommunityToolkit.
Checking the implementation of the ShowPopup method, the trigger 
for calling the CreateAndShowPopup method is the NavigateTo event.

    void handler(object? sender, NavigatedToEventArgs args)
    {
        page.NavigatedTo -= handler;

        CreateAndShowPopup(page, popup);
    }

    page.NavigatedTo += handler;

This is why the Popup is not shown when the Popup.ShowPopup 
method is called in the NavigateTo event. A NavigateTo event 
is never fired within a NavigateTo event. This is the cause 
of this issue. A NullReferenceException occurs at Close because 
the Popup is not displayed.

There is no workaround other than using a timer to shift the timing 
of the processing in the NavigatedTo event or processing it in the 
Loaded event.

If possible, I would like to display the popup within the NavigatedTo event.

**Comment by bijington** [comment]
We should only be doing that if the `IsPlatformEnabled` property of the page is false. I believe it should be true in the `OnNavigatedTo` method.

Thanks for looking into this

**Comment by cat0363** [comment]
Hi, @bijington 

This issue was resolved by changing the source code of the Community Toolkit.
Changed the timing of calling CreateAndShowPopup from the NavigatedTo event to the Loaded event.
With this change, the PopupShow method now works in both OnNavigatedTo and OnAppearing.

[PopupExtensions.shared.cs]

    public static void ShowPopup<TPopup>(this Page page, TPopup popup) where TPopup : Popup
    {
        if (page.IsPlatformEnabled)
        {
            CreateAndShowPopup(page, popup);
        }
        else
        {
            void handler(object? sender, EventArgs args)
            {
                page.Loaded -= handler;

                CreateAndShowPopup(page, popup);
            }
            page.Loaded += handler;
        }
    }

    public static Task<object?> ShowPopupAsync<TPopup>(this Page page, TPopup popup) where TPopup : Popup
    {
        if (page.IsPlatformEnabled)
        {
            return CreateAndShowPopupAsync(page, popup);
        }
        else
        {
            var taskCompletionSource = new TaskCompletionSource<object?>();

            async void handler(object? sender, EventArgs args)
            {
                page.Loaded -= handler;

                try
                {
                    var result = await CreateAndShowPopupAsync(page, popup);

                    taskCompletionSource.TrySetResult(result);
                }
                catch (Exception ex)
                {
                    taskCompletionSource.TrySetException(ex);
                }
            }
            page.Loaded += handler;

            return taskCompletionSource.Task;
        }
    }

Below is the execution result.

[Android]

https://github.com/CommunityToolkit/Maui/assets/125236133/822ded8e-a1bb-44fa-966b-84ab54f31649

[iOS]

https://github.com/CommunityToolkit/Maui/assets/125236133/98cff17d-2465-4a0f-ae10-f2e72f2e2160

Can anyone confirm that this change is fine?
If this problem is resolved, the available timing will expand.
Thank you.

**Comment by brminnick** [comment]
Awesome! Thanks!!

Could you submit a PR with this? It'll help us a ton to review the code in a PR 💯

**Comment by cat0363** [comment]
Hi, @brminnick 
Thank you for your reply.
This is my first time creating a PR. What should I refer to?
I hope I can be of some help.

**Comment by bijington** [comment]
@cat0363 thank you for looking into this! I will try and compare it back to the MAUI source that we took inspiration from because `IsPlatformEnabled` and `OnNavigatedTo` were working for this and also things like `DisplayAlert`

**Comment by cat0363** [comment]
Hi, @bijington 
Thank you for sharing the background to the current implementation.
I will look into it too. If I find out anything, I'll post it here.

**Comment by brminnick** [comment]
> Hi, @brminnick
> Thank you for your reply.
> This is my first time creating a PR. What should I refer to?
> I hope I can be of some help.

No problem! Check out this video https://youtu.be/x24fOAPclL4?t=129

**Comment by cat0363** [comment]
@brminnick, Thanks for the helpful information.
I would like to try it using your recommended GitHub Desktop.

**Comment by cat0363** [comment]
Hi, @brminnick 
I created a PR, but received the following message from the dotnet-policy-service bot.

    please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.

    @dotnet-policy-service agree [company="{your company}"]

Should I reply by entering the following in the comment field?

    @dotnet-policy-service agree

I'm sorry if I made a mistake in creating a PR.
Thank you.

**Comment by cat0363** [comment]
Hi, @bijington 
I wrote the reason why the ShowPopup did not show the Popup in the OnAppearing and OnNavigatedTo events in the PR.
This issue seems to be affected by the timing at which page.Handler is initialized.

**Comment by cat0363** [comment]
Hi, @brminnick 
It's a pleasure to help you. Looking forward to merging the fix.
Thank you to all who have contributed to the resolution of this issue.
