### ISSUE TITLE
[BUG] embed:// uri not working from c# code

### ISSUE THREAD

**Issue by jakopo87** [CommunityToolkit/Maui#1122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

The [MediaElement](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/mediaelement) docs says that it's possible to use the `embed://` scheme to set the `Source` property of a `MediaElement` to load a media embedded in the app, however this works only from XAML code and not from C# .

### Expected Behavior

Loading an embedded media, using the same string with the `embed://` scheme, should work from XAML and C# both.

### Steps To Reproduce

1. Create a .NET MAUI app.
2. Add CommunityToolkit.Maui.MediaElement package.
3. Put a supported media file in the Resource\Raw folder.
4. Add a MediaElement in the XAML code.
5. Set the Source property from C# code (using a button).
6. Call the Play() method of the MediaElement.
7. The MediaElement will show the message `Error: Unsupported video type or invalid path`

### Link to public reproduction project repository

https://github.com/jakopo87/TestMediaElementEmbed

### Environment

```markdown
- .NET MAUI CommunityToolkit: 1.0.0 and up
- OS: Android 13, Windows 10.19045.2728
- .NET MAUI: 7.0
```

### Anything else?

Using the file `Resource\Raw\test.wav` as example, it's possible to load correctly the media with `MediaSource.FromResource("test.wav")` as a workaround.

**Comment by TeguSolutions** [comment]
Almost three months later, the same.
False documentation, fake error codes, wasted hours, and one barely findable unverified bug.
Again, again and again.
Please mark this whole Maui project as BETA. Basically, nothing works except listing some monkeys.
