### ISSUE TITLE
[BUG] Expander doesn't (visibly) expand on Windows when using Gridlength.Auto

### ISSUE THREAD

**Issue by SmartmanApps** [CommunityToolkit/Maui#1136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When using Gridlength.Auto on Windows, Expander doesn't (visibly) expand when clicked on in a collapsed state - works as expected with Gridlength.Star (but defeats the purpose of using Expander!) - works fine on Android and Mac (iOS not tested). I'm not sure if this is because it isn't expanding to start with, or it's expanding but hidden by the next Grid row somehow, so **potentially** an issue with Grid row resizing when Expander changes size? Not sure if it's that or it's just not expanding. Note that if you set the initial state to IsExpanded=true, you can see it in the expanded state, but once you collapse it you can't (see it) expanded again. The arrow on the right changes, but you can't see the expanded content.

### Expected Behavior

It should expand. :-)

### Steps To Reproduce

1. The master branch in https://github.com/SmartmanApps/ExpandersSharp contains the original (non-working on Windows) code, which actually comes from this video - [Dotnet MAUI Expander Static and Dynamic in C#](https://www.youtube.com/watch?v=p_4nj1R14k0). See lines 19-20 in NewSharpPage.cs.
2. I've added a Workaround branch which has changed the 1st Grid row to Star instead of Auto, and demonstrably works (but defeats purpose of having an Expander).

### Link to public reproduction project repository

https://github.com/SmartmanApps/ExpandersSharp

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.0.0
- OS: Windows: 19044.2728
- .NET MAUI: 7.0.59
```

**Comment by techcat18** [comment]
Hi. I couldn't reproduce this issue on Windows.

![image](https://github.com/CommunityToolkit/Maui/assets/92333402/f2b1bb62-bebb-4582-a043-ee78ea670779)
![image](https://github.com/CommunityToolkit/Maui/assets/92333402/923593ab-d4dd-4bcc-a69d-07ef0b4b003f)

**Comment by SmartmanApps** [comment]
Hi @techcat18 

> Hi. I couldn't reproduce this issue on Windows.

   I just tried it again with my since updated version of VS, and yes indeed, it works now! Some update somewhere along the way has fixed the issue, so I'll close this now. :-)
