### ISSUE TITLE
[Proposal] Popup

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#114]
# Popup

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Sample
* [x] Documentation

## Summary
[summary]: #summary

A customizable popup

## Detailed Design
[design]: #detailed-design

### Popup.shared.cs

```cs
public class Popup<T> : BasePopupView
{  
  public static readonly BindableProperty ContentProperty;
  public static readonly BindableProperty ColorProperty;
  public static readonly BindableProperty SizeProperty;
  public static readonly BindableProperty VerticalOptionsProperty;
  public static readonly BindableProperty HorizontalOptionsProperty;
  
  public Task<T?> Result { get; }
  public virtual View? Content { get; set; }
  public Color Color { get; set; }
  public LayoutOptions VerticalOptions { get; set; }
  public LayoutOptions HorizontalOptions { get; set; }
  public View? Anchor { get; set; }
  public Size Size { get; set; }
  public bool IsLightDismissEnabled { get; set; }
  public event EventHandler<PopupDismissedEventArgs> Dismissed;
  public event EventHandler<PopupOpenedEventArgs> Opened;
  
  public void Reset();
  public void Dismiss(T? result);
}

// Both `Popup` and `Snackbar` should inherit from `BasePopupView` 
public abstract class BasePopupView
{
  public static readonly BindableProperty IsShown; // One-way binding
  public static readonly BindableProperty AnchorProperty; // Two-way binding
  public static readonly BindableProperty AppearingAnimationProperty; // Two-way binding
  public static readonly BindableProperty DisappearingAnimationProperty; // Two-way binding

  public bool IsShown { get; private set; }

  public IView Anchor { get; set; } = GetDefaultAnchor();
  public Animation AppearingAnimation { get; set; } = GetDefaultAnimation();
  public Animation DisappearingAnimation { get; set; } = GetDefaultAnimation();

  public event EventHandler Shown;
  public event EventHandler Dismissed;

  public abstract Task Show();
  public abstract Task Dismiss();

  private Animation GetDefaultAnimation();

  private IView GetDefaultAnchor();
}
```

**Comment by davidbuckleyni** [comment]
Can the popup allow stack layouts and grids. If u have a look at dev express one its works really excellent. U dont have to do anything special to access the cotrols from code behind.

**Comment by pictos** [comment]
@davidbuckleyni this popup will be the same as the XCT one, and it allows the usage of all Maui layouts, so far

**Comment by Vroomer** [comment]
Given that MAUI targets desktop as well, it would be really useful to add option to position and size a popup in reference to a control from which the popup got called. For example clicking on a button in top right corner would always bring up a popup right next to it in direction that has enough space to accommodate it. This would allow a lot of very important features like custom context menus, tooltips, dropdowns...

**Comment by maxkoshevoi** [comment]
Maybe it's too late, but how are you looking at using `Rg.Plugins.Popups` port as a popup view in the toolkit? It has more features and is already widely used.

CC: @LuckyDucko
