### ISSUE TITLE
[BUG] Filesaver on Android requires WRITE_EXTERNAL_STORAGE permission, but since API level 33 it could not be requested

### ISSUE THREAD

**Issue by IvanMi773** [CommunityToolkit/Maui#1146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

For Android MAUI projects targeting API level 33 it is impossible to request READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE permissions (see [Android documentation](https://developer.android.com/reference/android/Manifest.permission#WRITE_EXTERNAL_STORAGE):
> Note: If your app targets [Build.VERSION_CODES.R](https://developer.android.com/reference/android/os/Build.VERSION_CODES#R) or higher, this permission has no effect.

). And if user is trying to store some file the `PermissionException` is throwing

### Expected Behavior

Filesaver should not require WRITE_EXTERNAL_STORAGE permission and PermissionException should not be thrown for the projects which targeting API level 33 

### Steps To Reproduce

1. Run solution from reproduction repository which is targeting API level 33
2. See that modal window with requesting storage permissions is not showing
3. Click on `Store file` button. See in output that PermissionException is throwing

4. Change target API level to 32 in AndroidManifest.xml
5. Rerun app and see that modal window with requesting storage permissions is showing
6. After click on button file picker is opened

### Link to public reproduction project repository

https://gitlab.com/IvanMi773/maui-filesaver-bug-reproduction/-/tree/main/

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.1.0
- OS: Windows 10
- .NET MAUI: 7.0.200
```

**Comment by lochidev** [comment]
still having this issue

**Comment by CobaltGoldCS** [comment]
Same here
