### ISSUE TITLE
Mask Behavior Date does not work[BUG] 

### ISSUE THREAD

**Issue by gabsamples6** [CommunityToolkit/Maui#1157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I am trying to type a date in the format dd/mm/yyyy in the MCT sample Masked behavior page, when I type the date is all wrong Hard to describe but you cannot type a date in that format at all.

### Expected Behavior

When I type I.E 25/03/2000 for example I need the typing to flow and see this as a result.

### Steps To Reproduce

Open the MCT sample
Go to the MaskedBehavior page and type a date like 25/03/2000

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui/tree/main/samples

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.1.0
- OS: 11 Pro Build 10.0.22621
- .NET MAUI: 7.0.81
```

### Anything else?

Am I missing the obvious here? I tried on android

**Comment by IeuanWalker** [comment]
@gabsamples6 not sure what your mask looks like, but the default masked character is X

So your mask should be 'XX/XX/XXXX'

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/behaviors/masked-behavior

**Comment by gabsamples6** [comment]
@IeuanWalker  thanks for your reply

1. Launch the MCT Sample app
2. Go to Masked Behavior page 
3. Go to the date one  which has  xx/xx/xxxx
4. Start typing a date like 23/04/2023 
5. when typing the dd is fine as soon as you type the month the date goes pear shaped

**Comment by IeuanWalker** [comment]
@gabsamples6 is this the issue you're having? https://github.com/CommunityToolkit/Maui/issues/460

Looks like ab issue with MAUI itself and not the toolkit

**Comment by gabsamples6** [comment]
It sounds as if is the same issue . I can’t wait till November it’s madness I will have to find a workaround .Is there any nullable date picker in Maui ?

**Comment by vhugogarcia** [comment]
The related issue has been fixed, also I ran a couple of tests using the latest stable version of .NET MAUI and all worked as expected. It looks like .NET MAUI fixed the issue.

I'm closing this issue, we can re-open it in case it is back again.
