### ISSUE TITLE
[Proposal] SemanticOrderView

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#116]
# SemanticOrderView

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Sample
* [x] Documentation: https://github.com/MicrosoftDocs/CommunityToolkit/pull/236

## Summary
[summary]: #summary

Accessibility augmentation to set the order of VisualElements for screen readers

## Detailed Design
[design]: #detailed-design

### SemanticOrderView.shared.cs

```cs
public class SemanticOrderView : ContentView
{
  public static readonly BindableProperty ViewOrderProperty =
	  BindableProperty.Create(nameof(ViewOrder), typeof(IEnumerable), typeof(SemanticOrderView), Array.Empty<View>());
  
  public IEnumerable ViewOrder
  {
	  get => (IEnumerable)GetValue(ViewOrderProperty);
	  set => SetValue(ViewOrderProperty, value);
  }
  
  public SemanticOrderView()
  {
  }
}
```

## Usage Syntax
[usage]: #usage-syntax

<!-- Here is an example from CharactersValidationBehavior:

### XAML Usage

```xml
<StackLayout Margin="20">
    <Button Text="Element outside the Semantic View"></Button>
    <xct:SemanticOrderView x:Name="acv">
        <StackLayout>
            <Label x:Name="second" Text="Second" Margin="0,20" />
            <Button x:Name="third" Text="Third" Margin="0,20" />
            <Label x:Name="fourth" Text="Fourth" Margin="0,20" />
            <Button x:Name="fifth" Text="Fifth and last" Margin="0,20" />
            <Button x:Name="first" Text="First" Margin="0,20" />
        </StackLayout>
    </xct:SemanticOrderView>
</StackLayout>
```

### C# Usage

```cs
public partial class SemanticOrderViewPage : BasePage
{
  public SemanticOrderViewPage()
  {
    InitializeComponent();
    acv.ViewOrder = new List<View> { first, second, third, fourth, fifth };
  }
}
```

**Comment by pictos** [comment]
I believe this is the same case as #83 
I'll ping @pureween and @rachelkang  to give the final word and close this issue.

**Comment by jfversluis** [comment]
I think this is superseded by all the stuff going on in .NET MAUI in terms of accessibility. Unless the above pinged people will tell us otherwise, I don't think we need this.

**Comment by jfversluis** [comment]
I was wrong about this one! The `SemanticEffect` can go, that will go into .NET MAUI. The `SemanticOrderView` or something similar ideally as well, but that is some time in the future. I would like to add it to the .NET MAUI Toolkit because of that and deprecate it at a later stage when we get to add it to the .NET MAUI box.
