### ISSUE TITLE
[BUG] Controls on Popup not working when popup is resized

### ISSUE THREAD

**Issue by acaliaro** [CommunityToolkit/Maui#1169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I have a Popup that auto resizes itself by pressing a button, displaying other controls. These controls appear to be unusable as they are not receiving focus

### Expected Behavior

When the popup resizes and the controls appear, you should be able to use them

### Steps To Reproduce

1. Execute the project
2. Press "Open popup"
3. Press "Show other controls"
4. Press the button, or the checkbox, or the entry... nothing happens

### Link to public reproduction project repository

https://github.com/acaliaro/MauiPicker

### Environment

```markdown
- .NET MAUI CommunityToolkit:5.1.0
- OS: iOS 15.7
- .NET MAUI: 

ID carico di lavoro installato      Versioni del manifesto      Origine dell'installazione
------------------------------------------------------------------------------------------
maui-windows                        7.0.81/7.0.100              VS 17.5.33627.172
maui-maccatalyst                    7.0.81/7.0.100              VS 17.5.33627.172
maccatalyst                         16.2.2035/7.0.100           VS 17.5.33627.172
maui-ios                            7.0.81/7.0.100              VS 17.5.33627.172
ios                                 16.2.2035/7.0.100           VS 17.5.33627.172
maui-android                        7.0.81/7.0.100              VS 17.5.33627.172
android                             33.0.46/7.0.100             VS 17.5.33627.172
```

**Comment by acaliaro** [comment]
if i send the app to the background and then bring it back to the foreground, the controls are usable

**Comment by brminnick** [comment]
Fixed in https://github.com/CommunityToolkit/Maui/pull/1320
