### ISSUE TITLE
[BUG] Popup over a popup is not centered

### ISSUE THREAD

**Issue by acaliaro** [CommunityToolkit/Maui#1170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I have a popup A. If in popup A I have a button that opens a popup B, popup B opens but is not centered. What is the logic of the location of popup B? How do you center it?

Another problem: if I click outside popup B, popup A also closes.

### Expected Behavior

Popup B should be centered with respect to popup A, or you should add properties that allow you to position the popup

If I click outside popup B, I expect only popup B to close

### Steps To Reproduce

Run the project
Press "Open Popup"
Press "Show second popup"

### Link to public reproduction project repository

https://github.com/acaliaro/MauiPicker

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.1.0
- OS: iOS 15.7
- .NET MAUI: 

ID carico di lavoro installato      Versioni del manifesto      Origine dell'installazione
------------------------------------------------------------------------------------------
maui-windows                        7.0.81/7.0.100              VS 17.5.33627.172
maui-maccatalyst                    7.0.81/7.0.100              VS 17.5.33627.172
maccatalyst                         16.2.2035/7.0.100           VS 17.5.33627.172
maui-ios                            7.0.81/7.0.100              VS 17.5.33627.172
ios                                 16.2.2035/7.0.100           VS 17.5.33627.172
maui-android                        7.0.81/7.0.100              VS 17.5.33627.172
android                             33.0.46/7.0.100             VS 17.5.33627.172
```

**Comment by alibabaan** [comment]
workaround:

private static CommunityToolkit.Maui.Core.Views.MauiPopup parentpopup;
    static void OnOpened(object? sender, PopupOpenedEventArgs e)
    {
        (sender as Popup).Opened -= OnOpened;
        var window = UIApplication.SharedApplication.Delegate.GetWindow();
        if (window.RootViewController.PresentedViewController != null)
        {
            var popup = sender as IPopup;
            (popup?.Handler?.PlatformView as MauiPopup).PopoverPresentationController.SourceRect = parentpopup.View.Bounds;
        }
    }

CommunityToolkit.Maui.Core.Handlers.PopupHandler.PopUpMapper.AppendToMapping("custopoup", (handler, view) => {
            try
            {
                var window = UIApplication.SharedApplication.Delegate.GetWindow();
                if (window.RootViewController.PresentedViewController == null)
                {
                    parentpopup = handler?.PlatformView;
                    return;
                }
                (view as Popup).Opened += OnOpened;                                                      
            }
                catch { }
            });

**Comment by brminnick** [comment]
Fixed in https://github.com/CommunityToolkit/Maui/pull/1320
