### ISSUE TITLE
[BUG] XFC0000 Cannot resolve type "http://schemas.microsoft.com/dotnet/2022/maui/toolkit:toolkit:InvertedBoolConverter

### ISSUE THREAD

**Issue by tallmanBS** [CommunityToolkit/Maui#1176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When I create a class library (Maui) with the instructions and place the folowing statement in the XAML
 `            xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
`
and try to use 
```
  <ContentPage.Resources>
    <ResourceDictionary>
      <toolkit:InvertedBoolConverter x:Key="InvertedBoolConverter" />
    </ResourceDictionary>
  </ContentPage.Resources>

```
I receive the error
XFC0000	Cannot resolve type "http://schemas.microsoft.com/dotnet/2022/maui/toolkit:toolkit:InvertedBoolConverter".	

After research if I change to 
`xmlns:toolkit="clr-namespace:CommunityToolkit.Maui.Converters;assembly=CommunityToolkit.Maui"
`I am able to get it to not error; however this isn't in the instructions, was harder to find and then requires me to list each namespace if I use multiple toolkit items.  What is the correct way to solve this?  I've included the project with commented line in instructions for reproduction.

### Expected Behavior

Expect it to compile without errors.

### Steps To Reproduce

1. Open provided project and uncomment out and swap the toolkit lines in NewPage1.xaml.

### Link to public reproduction project repository

https://www.nuget.org/packages/BrentSaferXFC000Bug/1.0.0

### Environment

```markdown
- .NET MAUI CommunityToolkit 5.1.0:
- OS:
- .NET MAUI 7.0:
```

**Comment by tallmanBS** [comment]
How do I do that in a library?  I don't have a MauiProgram.cs or executables. This is a compiletime issue.
Thanks for your response and review.


________________________________

**Comment by tallmanBS** [comment]
Hello @VladislavAntonyuk 
How do I do that in a library?  I don't have a MauiProgram.cs or executables. This is a compiletime issue.
Thanks for your response and review.  I had seen this mentioned, but don't see a way to do it in this situation.

**Comment by VladislavAntonyuk** [comment]
Create extension method in you library that calls UseMauiCommunityToolkit.
It might help.

**Comment by Saccomani** [comment]
same issue here

**Comment by brminnick** [comment]
@Saccomani Please see the recommended workarounds above and this Stackoverflow answer: https://stackoverflow.com/a/76452761/5953643
