### ISSUE TITLE
[Proposal] Snackbar

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#118]
# Snackbar

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Sample
* [ ] Documentation: Not Started

## Summary
[summary]: #summary

Adds a snackbar.
It has to use Native Android Snackbar (`Google.Android.Material.Snackbar`) internally.
All other platforms implement a default popup container with text and a button.

## Detailed Design
[design]: #detailed-design

### Snackbar.shared.cs

```cs
namespace CommunityToolkit.Maui.Controls.Snackbar;

public class Snackbar : ISnackbar
{
	Action Action { get; set; }
	string ActionButtonText { get; set; }
	IView? Anchor { get; set; }
	TimeSpan Duration { get; set; }
	bool IsShown { get; }
	string Text { get; set; }
	SnackbarOptions VisualOptions { get; set; }

	event EventHandler? Dismissed;
	event EventHandler<ShownEventArgs>? Shown;

	Task Dismiss();
	Task Show();

    public static ISnackBar Make();
}

public interface Snackbar
{
	Action Action { get; }
	string ActionButtonText { get; }
	IView? Anchor { get;  }
	TimeSpan Duration { get; }
	bool IsShown { get; }
	string Text { get; }
	SnackbarOptions VisualOptions { get; }

	event EventHandler? Dismissed;
	event EventHandler<ShownEventArgs>? Shown;

	Task Dismiss();
	Task Show();
}

public class ShownEventArgs : EventArgs
{
	public ShownEventArgs(bool isShown)
	{
		IsShown = isShown;
	}

	public bool IsShown { get; }
}

public class SnackbarOptions : ITextStyle
{
	public double CharacterSpacing { get; set; } = 0.0d;

	public Font Font { get; set; } = Font.SystemFontOfSize(14);

	public Color TextColor { get; set; } = Colors.Black;

	public Color ActionTextColor { get; set; } = Colors.Black;

	public Color BackgroundColor { get; set; } = Colors.LightGray;

	public CornerRadius CornerRadius { get; set; } = new CornerRadius(4, 4, 4, 4);
}
```

## Visual with default settings

Android:
![image](https://user-images.githubusercontent.com/33021114/143035138-1aa460d7-9ab3-4af5-86aa-256e517367c8.png)

**Comment by VladislavAntonyuk** [comment]
Duplicate #3 
Implementation #5

**Comment by brminnick** [comment]
@VladislavAntonyuk FYI - this Proposal needs someone on the core Maui Community Toolkit team to Champion  it before we can move to the implementation stage. We've documented the steps of this new workflow here: https://github.com/CommunityToolkit/Maui#3-proposal-championed

**Comment by jfversluis** [comment]
To be honest I think we might want to rethink some things about the API here. I love what it does, but I think there are some things we might want to rethink. For example:

- Multiple vs 1 button, since this is different across platforms
- More styling options, can we allow views in here somehow? Templates?
- Do we actually want to anchor it to a VisualElement or only allow it on pages?

**Comment by VladislavAntonyuk** [comment]
1 and 2 as for the multiple buttons and templates. Let's decide the preferable way. Do we rely on native implementation (Google -> 1 button by default but allow to extend the template with multiple buttons) or we can add a simple popup with a predefined template.

3. I like that we can display it in any part of the screen (it solves the problem with the position of the snack bar).

My opinion about the styling options. We have Popup control which has template customization.
as for the snackbar it should be pretty simple like Alert and ConfirmationDialog.

**Comment by VladislavAntonyuk** [comment]
@pictos what do you mean with the pending items?

**Comment by pictos** [comment]
> My opinion about the styling options. We have Popup control which has template customization.
as for the snackbar it should be pretty simple like Alert and ConfirmationDialog.

If we move to use the PopUp as a Snackbar container we will have less code to maintain and that's something that I like. We can mimic the Google style in our default template and allow users to customize their snackbar according to their needs.

Thoughts @VladislavAntonyuk  and @jfversluis 

I would like to bring @ahoefling to this discussion since he's the author of PopUp control.

**Comment by VladislavAntonyuk** [comment]
as for the user experience, I would prefer (and strongly recommend) to use a native Android snack bar. as for iOS and other platforms I am ok with popup.

**Comment by brminnick** [comment]
I've updated the [`Detailed Design`](https://github.com/CommunityToolkit/Maui/issues/118) to mirror the [Android Snackbar API surface](https://material.io/components/snackbars/android#using-snackbars).

I know they're redundant, but I think it's important to keep methods like `static Snackbar Make()` and `void Set[Property]()` because these methods are used (required, actually) by the `Google.Android.Material.Snackbar` implementation. This will ensure that Android developers who have experience with `Google.Android.Material.Snackbar` will easily be able to use `CommunityToolkit.Maui.Controls.Snackbar`.

**Comment by VladislavAntonyuk** [comment]
Thank you for the updates.
Why do we need BindableProperties? Snackbar is not actually UI control which we add in xaml. It is similar to Alert, Prompt and other from Maui.
To show the Snackbar:
```
var snackbar = Snackbar.Make(...);
snackbar.ShowAsync(); // let's keep async here even if we don't have just Show(). Or maybe it can be void.
```

Also how Content property should work together with TextColor, Action. The user can remove the whole predefined content and it will look like popup rather than Snackbar. What do you think if we remove this property?

**Comment by brminnick** [comment]
> snackbar.ShowAsync

We can keep the method as `Show()`. The `Async` suffix is only necessary when there is a sibling non-async method. I.e. If we had two methods, `Show()` and `ShowAsync()`, we would absolutely keep the `Async` suffix. Plus, the Android API also uses `Show()`.

> Why do we need BindableProperties? Snackbar not actually UI control which we add in xaml

A Few Reasons:
- It is a UI Control and all UI Controls should implement Bindable Properties
  - It implements `IView` (technically it implements `IBorder` which implements `IView`)
    - This means it can be added to an `ILayout`; while not the intended use, it is doable and there may be a decent use-case for it
  - The business logic may need to update the text displayed via bindings (see code example, below)
- It can be created in XAML
  - I purposefully didn't create a private constructor (`private Snackbar() { }`) so that it _can_ be created in both XAML and C# using the default constructor
    - Again, this won't be the most typical method that devs use, but because it implements `IView` it is doable and a few devs may choose to do so
  - Remember that XAML isn't the only option for creating UIs in .NET MAUI
    - Other developers, like me, don't use XAML; I create all of my UIs in C#
- Here's an example on how bindings would be used:
    ```cs
    public MyPage : ContentPage
    {
      readonly Snackbar _snackbar = Snackbar.Make(...)

      public MyPage()
      {
        _snackbar.SetBinding(TextProperty, nameof(ViewModel.SnackbarText);
      }
    }
    ```

> Also how Content property should work together with TextColor, Action. The user can remove the whole predefined content and it will look like popup rather than Snackbar.

Good point! I may have gotten ahead of myself here; I was looking towards the future where we merge `Popup` and `Snackbar` functionality. Maybe, instead, we have `Popup` and `Snackbar` be separate UI Controls that both use the same base class for the logic around anchoring, showing, dismissing, etc. I'll note this on the `Popup` proposal.

I've removed `Content` from the design 👍.

**Comment by brminnick** [comment]
What do you think about making a base class, `abstract class BasePopupView`, in this PR so that `Popup` can also inherit from it?

```cs
// Both `Popup` and `Snackbar` should inherit from `BasePopupView` 
public abstract class BasePopupView : IBorder
{
  public static readonly BindableProperty IsShown; // One-way binding
  public static readonly BindableProperty AnchorProperty; // Two-way binding
  public static readonly BindableProperty AppearingAnimationProperty; // Two-way binding
  public static readonly BindableProperty DisappearingAnimationProperty; // Two-way binding

  public bool IsShown { get; private set; }

  public IView Anchor { get; set; } = GetDefaultAnchor();
  public Animation AppearingAnimation { get; set; } = GetDefaultAnimation();
  public Animation DisappearingAnimation { get; set; } = GetDefaultAnimation();

  public event EventHandler Shown;
  public event EventHandler Dismissed;

  public abstract Task Show();
  public abstract Task Dismiss();

  private Animation GetDefaultAnimation();

  private IView GetDefaultAnchor();
}
```

**Comment by VladislavAntonyuk** [comment]
Looks good to me.
The only one thing which I don't like is that Snackbar becomes UI control. What is the difference between Snackbar and Alert/Prompt from MAUI? As I understand making Snackbar UI control will allow the user to put it in xaml. I understand xaml as something that should be rendered, mostly on specific view. Snackbar doesn't belong to the view, it belongs to the Current Activity/Window.
Also a question about visual element extension methods. Do we need them?

**Comment by brminnick** [comment]
> What is the difference between Snackbar and Alert/Prompt from MAUI?

The biggest difference is that only Android has a native implementation. For iOS, macOS and Windows, we are essentially creating a new custom UI Control.

> Also a question about visual element extension methods. Do we need them?

Which ones? In general, if it it's a useful extension method and/or it makes the code cleaner, I'm all for it 💯

**Comment by VladislavAntonyuk** [comment]
ok, I hope to find some time this week to start the implementation.
as for the extension methods:
```
view.ShowSnackbarAsync(snackbarOptions);
CurrentPage.ShowSnackbarAsync(duration, text, buttonText, Action<Task>);
```

**Comment by brminnick** [comment]
Those extensions sound good to me! (Minus the `Async` suffix 😄)

**Comment by VladislavAntonyuk** [comment]
@pictos @brminnick could you please approve the current detailed design?

**Comment by brminnick** [comment]
Looks good! A few thoughts (none of these are blockers, and I'm happy moving forward with this implementation!)
- Let's explicitly add the default value for `CharacterSpacing`, ` = 0.0d`
  - [`Microsoft.Maui.Controls TextElement` uses `0.0d`](https://github.com/dotnet/maui/blob/316a95fbbc09af9d79dc2893b5d2d7336a11e89a/src/Controls/src/Core/TextElement.cs#L11-L13), which means that MAUI must implement a default spacing when it is set to `0.0d`
  - It's a bit redundant, but it at least shows that we've done our due-diligence and didn't overlook it
- Should `ISnackbar` Implement `IText`?

**Comment by pictos** [comment]
@VladislavAntonyuk we should make all properties read-only on the `ISnackbar` interface since the flow is from xplat -> native level.

**Comment by VladislavAntonyuk** [comment]
How in that case do we set the property in snackbar?
the usage:
```
var snackbar = new Snackbar();
snackbar.Text="test";
snackbar.Action=()=>{};
await snackbar.Show();

snackbar.Text = "test2";
await snackbar.Show();
```

**Comment by pictos** [comment]
You can implement the `set` in the concrete type, but the interface should be read-only...
For example:
the `ITextInput` has the MaxLenght property read-only.

https://github.com/dotnet/maui/blob/main/src/Core/src/Core/ITextInput.cs#L31

The class that implements that interface also implements the set.

https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/InputView.cs#L31

But the `Text` property in that interface has the `set` defined, that happens because you can change the Text value from the native platform (When user types). If I'm not wrong nothing on the native side can change snackbar values.

**Comment by VladislavAntonyuk** [comment]
I am agree and disagree with that.

In Maui in xaml and in code we create components. Real instances of the specific class. And work with getters and setters. I cannot imagine Entry with Text {get;}.

With Snackbar we can do the same. But we limit ourselves to the specific implementation.
I want to return ISnackbar for example as a result of VisualElementExtrensions.DisplaySnackbar.
In that case I cannot use all setters.

I expect this code to work:
```

ISnackbar snackbar = new Snackbar();
snackbar.Text="test";
snackbar.Action=()=>{};
await snackbar.Show();

snackbar.Text = "test2";
await snackbar.Show();

Or

ISnackbar snackbar = Snackbar.Make("test", action);
await snackbar.Show();

Snackbar.Anchor = someIView;
snackbar.Text = "test2";
await snackbar.Show();
```

**Comment by pictos** [comment]
@VladislavAntonyuk, not sure if you're aware of the MAUI architecture, if you're probably I'll say something that you already know... So bear with me...

When you're building an MAUI application you don't use the `interfaces` you use the concrete type, so the user will not do 

`ISnackbar snackbar = new Snackbar();`

will do  `Snackbar snackbar = new Snackbar();`  instead. And the concrete type `Snackbar` will have the `set` implemented in all properties.

If someone uses the `interface` is just to read the values and not to change them. 

So when you implement the Snackbar control you should extend from the interface and also implement the `set` accessor.
```csharp
class Snackbar : ISnackbar 
{
    public string Text { get; set; }
}
```

Does it make sense for you?

**Comment by VladislavAntonyuk** [comment]
Do we need interface at all for Snackbar? Why do I need it if I can access the class getters?

**Comment by brminnick** [comment]
Hey Gang! 

Let's not get too caught up in the weeds here. I think we have a solid plan that we can always iterate on in the future 💯 

Here's what I recommend:

### Interface

For `Snackbar` v1.0, let's move forward with the readonly interface that Pedro recommends, because it best follows the MAUI Interfaces (which are also read-only).

Since we're treating `Snackbar` like an alert (like `DisplayAlert`), there shouldn't be a need for a user to edit the properties. And if the user wants to display something different on an `ISnackbar`, they can just make + display a new one.

Do we even need an interface? Probably not; for example, `DisplayAlert` doesn't have an interface. But, having an interface doesn't hurt us and we can likely leverage it for more things in the future.

### Snackbar.Make + VisualElementExtrensions.DisplaySnackbar

Regarding `Make` an `VisualElementExtrensions.DisplaySnackbar`, these methods can include parameters to allow the user to pass in all of the parameters to create the Snackbar:

#### Snackbar.Make
```cs
public static ISnackbar Make(string text, string actionButtonText, TimeSpan? duration = null, Action? action = null, IView? anchor = null, SnackbarOptions? visualOptions = null);
```

### VisualElementExtrensions.DisplaySnackbar
```cs
public static ISnackbar DisplaySnackbar(this VisualElement, string text, string actionButtonText, TimeSpan? duration = null, Action? action = null, IView? anchor = null, SnackbarOptions? visualOptions = null) => Snackbar.Make(text, actionButtonText, duration, action, anchor, visualOptions);
```

This way, users can fully implement their Snackbar and we can still return `ISnackbar` .

**Comment by VladislavAntonyuk** [comment]
Sorry, just want to make sure that we do not make a mistake on the planning step

**Comment by pictos** [comment]
Sorry, my intention wasn't to be rude. I just want to make sure that we're all in the same page

**Comment by brminnick** [comment]
Reopening for Docs implementation
