### ISSUE TITLE
[BUG] CS0436 compiler warning because of source generators when using InternalsVisibleTo

### ISSUE THREAD

**Issue by omghb** [CommunityToolkit/Maui#1185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

The source generators of the CommunityToolkit.Maui generate compiler warnings in our solution.

We use the `[assembly: InternalsVisibleTo(..]` attribute so that we can access internal members within unit tests. But the source generators create the same internal classes in all projects. So the compiler warns about:

`Warning CS0436: The type 'ColorAnimationExtensions_TimePicker' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\TimePickerTextColorTo.g.shared.cs' conflicts with the imported type...`

**Complete warning text**:
`
[warning]D:\7\s\...\Foo.Test\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\TimePickerTextColorTo.g.shared.cs(63,89): Warning CS0436: The type 'ColorAnimationExtensions_TimePicker' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\TimePickerTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_TimePicker' in 'FooLib, Version=3.0.400.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\TimePickerTextColorTo.g.shared.cs'.
`

### Expected Behavior

no compiler warnings

### Workaround

I have added `<NoWarn>1701;1702;CS0436</NoWarn>` to the unit test project file. This suppress the compiler warning.

### Steps To Reproduce

- Just add a C# project (e.g. unit test project) that references a project which includes the CommunityToolkti.Maui.
- Add `InternalsVisibleTo` attribute so that the newly added project can access the internal members of the referenced project.
- Build and see the compiler warnings

### Link to public reproduction project repository

- 

### Environment

```markdown
- .NET MAUI CommunityToolkit:5.0.0
```

**Comment by omghb** [comment]
- Extract: [WarningCS0436.zip](https://github.com/CommunityToolkit/Maui/files/11478621/WarningCS0436.zip)
- Open solution
- Build TestProject1
- See that it produces the CS0436 compiler warnings

**Comment by VladislavAntonyuk** [comment]
We do not support zip archives. Publish your code to repository

**Comment by omghb** [comment]
Here is the repo: https://github.com/omghb/CommunityToolkitMauiIssue1185

**Comment by pictos** [comment]
@omghb if you remove `net7.0` from [here](https://github.com/omghb/CommunityToolkitMauiIssue1185/blob/main/MauiApp1/MauiApp1/MauiApp1.csproj#L3) did your project still works? For a MAUI app you don't need it, as you can see on our [sample](https://github.com/CommunityToolkit/Maui/blob/main/samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj#L4-L6)

**Comment by omghb** [comment]
@pictos the `net7.0` target is important for unit tests - I can't remove it. 

I believe it is the same reason why the `CommunityToolkit.Maui` use this `net7.0` target as well. 😃

**Comment by pictos** [comment]
@omghb you need compare apples with apples with apples, the CommunityToolkit.Maui is a class library your project is a mobile app. The best practice to unit test it is to use device runners.

If you can't redactor your project in order to run the device runners you can disable the SG for the platform targets, [here](https://stackoverflow.com/a/66130446) you can see how to do it.

**Comment by VladislavAntonyuk** [comment]
You should not include analyzers/source generators etc in test project:
```xml
<PackageReference Include="CommunityToolkit.Maui" Version="5.1.0">
	<PrivateAssets>all</PrivateAssets>
</PackageReference>
```

Exclude them to remove warnings:
![image](https://github.com/CommunityToolkit/Maui/assets/33021114/61e99585-4895-48bd-8f56-e9970234e689)

**Comment by omghb** [comment]
@pictos we are using multiple MAUI class libraries for our "larger" App. And we use unit tests where appropriate and UI tests with Appium. The workaround you propose is very hacky and not suitable to us.

@VladislavAntonyuk Our production class library is referencing `CommunityToolkit.Maui`. So all dependent projects get this library as well - which is by design. We can't use `<PrivateAssets>all</PrivateAssets>` as it has other side-effects. We want to exclude only the `analyzers` from the `CommunityToolkit.Maui` but this is not supported:

- https://github.com/dotnet/sdk/issues/1212

**Comment by omghb** [comment]
@VladislavAntonyuk just saw that you closed my issue already. As mentioned in my previous post - your workaround does not work in our case.

Please, re-open my issue again.

**Comment by pictos** [comment]
@omghb, What I posted isn't a workaround, it's how you can exclude SG from the build. Your sample project doesn't reflect the reality of your project, since you just added a Maui app and Unit test, there are no external libs there... We can just provide options for what we see

**Comment by MichaelLHerman** [comment]
I needed to do this as well for unit tests to compile, but I also had trouble compiling another config due to PrivateAssets="All".   Also needed CommunityToolkit.Maui.Core to be transitively included in my .Test project, so I explicitly referenced it without PrivateAssets="All".


```
   <TargetFrameworks>net8.0-ios;net8.0</TargetFrameworks>
    ...
    <PackageReference Include="CommunityToolkit.Maui.Core" Version="7.0.0" />
    <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
    <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
  </ItemGroup>
  <Choose>
    <When Condition="'$(TargetFramework)' == 'net8.0'">
      <!-- Compilation error from source generators due to InternalsVisibleTo -->
      <ItemGroup>
        <PackageReference Include="CommunityToolkit.Maui" Version="7.0.0" PrivateAssets="All" />
        <PackageReference Include="CommunityToolkit.Maui.Markup" Version="4.0.0" PrivateAssets="All" />
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <PackageReference Include="CommunityToolkit.Maui" Version="7.0.0" />
        <PackageReference Include="CommunityToolkit.Maui.Markup" Version="4.0.0" />
      </ItemGroup>
    </Otherwise>
  </Choose>
```
