### ISSUE TITLE
[BUG] FileSaver throws same exception for failed download as for when the user cancels the file save dialog

### ISSUE THREAD

**Issue by hellqvist** [CommunityToolkit/Maui#1186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When using FileSave.Default.SaveAsync a file saver dialog pops up. If the user press cancel in the dialog a FileSaverException is thrown with the text **Path does not exist**. It's not possible to determine based on the exception if the user pressed Cancel or if the path is incorrect. 

### Expected Behavior

I would prefer if either the FileSaveResult had some property that specifies that the user pressed Cancel or if a specific exception was thrown so I know that it wasn't the actual save that failed. 

### Steps To Reproduce

1. Open and run solution from reproduction repository
2. Click the Save file button
3. Press cancel in the dialog and observer the error message

### Link to public reproduction project repository

https://github.com/hellqvist/CommunityToolkitFileSaveCancelDialog.git

### Environment

```markdown
- .NET MAUI CommunityToolkit:5.1.0
- OS: Windows 10 Build 10.0.19041.0
- .NET MAUI: 7.0
```

**Comment by VladislavAntonyuk** [comment]
unfortunately, we cannot determine if a user canceled the operation or selected an invalid folder. we return an exception with the text: Operation canceled or Path doesn't exist.

**Comment by VladislavAntonyuk** [comment]
related: https://github.com/CommunityToolkit/Maui/issues/974
