### ISSUE TITLE
[Proposal] Shield

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#119]
# Shield

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
  * [ ] iOS Support
  * [ ] Android Support
  * [ ] macOS Support
  * [ ] Windows Support
* [ ] Unit Tests: Not Started
* [ ] Sample: Not Started
* [ ] Documentation: Not Started

## Summary
[summary]: #summary

The Shield is a type of badge that has two colored sections that contain text.
![](https://docs.microsoft.com/en-us/xamarin/community-toolkit/views/shield-images/example-shields.png)

## Detailed Design
[design]: #detailed-design

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
             x:Class="MyLittleApp.MainPage">

     <StackLayout>

        <xct:Shield
                Subject="chat"
                Status="on discord"
                StatusBackgroundColor="SeaGreen"
                StatusTextColor="White"
                Margin="2,0" />

    </StackLayout>

</ContentPage>
```

### C# Usage

```cs
new StackLayout
{
  Children = 
  {
    new Shield
    {
      Subject = "chat",
      Status = "on discord",
      StatusBackgroundColor= Colors.SeaGreen,
      StatusTextColor = Colors.White,
      Margin = new Thickness(2, 0)
    }
  };
}
```

**Comment by jfversluis** [comment]
My gut feeling is that this isn't used that much? Maybe let's leave it behind for now and see if that triggers any response and re-add if people are missing it.
