### ISSUE TITLE
[BUG] Page cannot show multiple popups

### ISSUE THREAD

**Issue by daltzctr** [CommunityToolkit/Maui#1191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

1. Launch Popup with `Application.Current.MainPage.ShowPopup(MyPopup1)`
2. In `MyPopup1`, Launch Popup with `Application.Current.MainPage.ShowPopup(MyPopup2)`

Behavior: `MyPopup2` does not appear

### Expected Behavior

`MyPopup2` appears on top of `MyPopup1`

### Steps To Reproduce

See current behavior for steps

### Link to public reproduction project repository

NA

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.1.0
- OS: Windows 11
- .NET MAUI: 7.0.81
```

**Comment by daltzctr** [comment]
Adding onto this, it seems like because `Popup` does not implement `Page`, it cannot show a popup.

**Comment by pictos** [comment]
@daltzctr this isn't a bug. It's by design. If you want to see this, implemented, please open a discussion linking with the docs for each platform that we support saying this is possible.

**Comment by daltzctr** [comment]
`Rg.Popups` does allow multiple popups on popups, so it should be possible. It does break the philosophy of page owning it's popup, since now popup lives shared alongside a page.

**Comment by pictos** [comment]
@daltzctr if I'm not wrong `Rg.Popups` uses a `ContentPage` to mimic a popup. Here we use what each platform provides us as popup
