### ISSUE TITLE
[BUG] IconTintColorBehavior stops working after changing Image Source on iOS

### ISSUE THREAD

**Issue by v0idzz** [CommunityToolkit/Maui#1196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

IconTintColorBehavior stops working after changing the Source of Image control, which results in the image being displayed in its original colors.

### Expected Behavior

TintColor is reapplied to every new image source.

### Steps To Reproduce

1. Open and run the solution from the reproduction repository
2. Click the 'Click me' button

### Link to public reproduction project repository

https://github.com/v0idzz/maui-ct-icontintcolorbehavior-issue-repro

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.1.0
- OS: macOS 13.3.1 (a)
- .NET MAUI: 7.0.86
```

### Anything else?

Proposed fix: https://github.com/v0idzz/Maui/commit/69065ce29272623d4da1e63d22a170befb2095fd

**Comment by rupisaini123** [comment]
I have seen same issue with app for Mac.
