### ISSUE TITLE
[BUG] MultiConverter only compatible with ICommunityToolkitValueConverter

### ISSUE THREAD

**Issue by daltzctr** [CommunityToolkit/Maui#1205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

MAUI CMT `MultiConverter` takes in a List of converters that implement `ICommunityToolkitValueConverter`. This means that you cannot put your own converters (without implementing this) in a `MultiConverter`. This is different behavior from Xamarin Community Toolkit that takes `IValueConverter`. This also breaks users migrating from Xamarin.

MAUI Source Reference: https://github.com/CommunityToolkit/Maui/blob/642b77849dd3992bfca6cae16f415e7a0ff2541c/src/CommunityToolkit.Maui/Converters/MultiConverter.shared.cs

Xamarin Source Reference: https://github.com/xamarin/XamarinCommunityToolkit/blob/9b80d796cb2cbeb46a304d724157249528fca422/src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/MultiConverter.shared.cs#L11

### Expected Behavior

Ability to use `IValueConverter` converters in a MultiConverter

### Steps To Reproduce

1. Create your own converter implementing `IValueConverter`
2. Place in a `MultiConverter`
3. Observe XAML failure

### Link to public reproduction project repository

NA

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.2.0
- OS: Windows 11
- .NET MAUI: 7.X
```

**Comment by brminnick** [comment]
Yes, our converters require `ICommunityToolkitValueConverter.FromType` and `ICommunityToolkitValueConverter.ToType`.

If you can provide a reproduction demonstrating your use case we may be able to help with a solution.

**Comment by daltzctr** [comment]
I'd like to use my own converters as part of a MultiConverter. That's the use case. Why is this change necessary and different from Xamarin.Forms?

**Comment by brminnick** [comment]
You can absolutely use your own converters: inherit from `ICommunityToolkitValueConverter` instead of `IValueConverter`. 

> Why is this change necessary and different from Xamarin.Forms

This is a different library for a different framework and has a different architecture.
