### ISSUE TITLE
[BUG]  IconTintColorBehavior with DynamicResource is not working

### ISSUE THREAD

**Issue by TheSundayDev** [CommunityToolkit/Maui#1206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

the colos is not applied if use <toolkit:IconTintColorBehavior TintColor= {DynamicResource Primary}/>
Primary is defined in standard styles/color.xaml

### Expected Behavior

the color must be applied

### Steps To Reproduce

<ImageButton    WidthRequest="70" HeightRequest="70" VerticalOptions="Center" HorizontalOptions="Center"  Source="add"   >
         <ImageButton.Behaviors>
               <toolkit:IconTintColorBehavior TintColor="{DynamicResource Primary}" />
          </ImageButton.Behaviors>
</ImageButton>

### Link to public reproduction project repository

http

### Environment

```markdown
- .NET MAUI CommunityToolkit:
5.2.0
- OS:
ios and android
- .NET MAUI:
7.0.86
```

**Comment by TheSundayDev** [comment]
sorry the issue with {DynamicResource Primary} is not related to the toolkit but to the framework of MAUI.
works just with StatisResource.
You can close or delete.
thanks

**Comment by rctec-at** [comment]
Is there any related issue regarding this in the Maui repo? i cant find any.
