### ISSUE TITLE
[BUG] IconTintColorBehavior misaligns tinted image on Windows

### ISSUE THREAD

**Issue by PieEatingNinjas** [CommunityToolkit/Maui#1212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When applying the IconTintColorBehavior on an image, the tinted image is misaligned on Windows; it's offset is not correct.
![image](https://github.com/CommunityToolkit/Maui/assets/13808075/1d9210be-c94e-45f5-adcd-d0b522d6d75b)

### Expected Behavior

Expecting the tinted image to correctly overlay the original image.

### Steps To Reproduce

1. New MAUI app
2. Add MAUI Community Toolkit NuGet
3. Add IcontTintColorBehavior to the dotnet_bot on MainPage.xaml
4. Run

### Link to public reproduction project repository

https://github.com/PieEatingNinjas/BugRep_MauiToolkit_IconTintWindow

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.2.0
- OS: Win11
- .NET MAUI: 7.0.100
```

### Anything else?

When looking at the source code, I noticed this:
`currentSpriteVisual.Offset = offset;`
(https://github.com/CommunityToolkit/Maui/blob/61a64de37e7dc461cc1ea97db4c941c020a59185/src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.windows.cs#LL181C3-L181C39)
which is calculated using this formula:
`var offset = new Vector3(-width * .5f, -height * .5f, 0f);`
(https://github.com/CommunityToolkit/Maui/blob/61a64de37e7dc461cc1ea97db4c941c020a59185/src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.windows.cs#LL160C3-L160C61)

It seems when I run locally and leave this offset logic out, it does behave as expected:
![image](https://github.com/CommunityToolkit/Maui/assets/13808075/00ad06ae-ea4b-4b80-ae98-7e4e259fc9d8)

I don't know why the above offset-logic is in there, maybe @kperdlich can explain? As said, removing this logic fixes the issue, in my particular use case.

**Comment by pictos** [comment]
cc: @kperdlich

**Comment by victorsigga** [comment]
how did you edit the files to aply the Workaround ?

**Comment by kperdlich** [comment]
Originally the offset was used to align the image correctly. A better way would be to use the `AnchorPoint`.

In the example it looks like the attribute `HeightRequest` breaks the position of the tinted image. I found a fix https://github.com/kperdlich/Maui/commit/27010e7f75255ec69ea2eb67dc5eb7aa6c919301 by first using the `AnchorPoint` instead of the `Offset` to align the image correctly + applying the offset whenever a size is requested. However, I'm still not sure why an additional offset is required. Perhaps its something done in the layout calculation.

**Comment by brminnick** [comment]
Thanks @kperdlich!

Do you think there's a bug fix we need to add to the toolkit to resolve this?

**Comment by kperdlich** [comment]
@brminnick Yeah I'll prepare one.

**Comment by PieEatingNinjas** [comment]
> how did you edit the files to aply the Workaround ? @PieEatingNinjas I'm having the same problem here, but in my case, there is some parts that this issue doesn't occurr, just in my initial page

I created my own behavior and copied this code in there. This allowed me to quickly debug and try out some stuff.

@kperdlich Great to see you are looking at it!

**Comment by kperdlich** [comment]
@brminnick Can you approve this issue?

**Comment by SamuelJames101** [comment]
I am having this issue in .Net 8
