### ISSUE TITLE
[BUG] MediaElement crash on iOS after opening the browser if in an AppShell (iOS)

### ISSUE THREAD

**Issue by cl3m** [CommunityToolkit/Maui#1214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

After opening a browser url inside the app, the app crash when going back to a page with a MediaElement with the error :
	NSException	{child view controller:<AVPlayerViewController: 0x7fe28b51ee00> should have parent view controller:<Microsoft_Maui_Controls_Platform_Compatibility_ShellSectionRootRenderer: 0x7fe2aaf79d80> but actual parent is:<Microsoft_Maui_Platform_PageViewController: 0x7fe2…}	Foundation.NSException

The error comes from the fixes https://github.com/CommunityToolkit/Maui/pull/1008 when using a AppShell.

### Expected Behavior

The app should not crash. It was the case in version 1.0.1.

### Steps To Reproduce

* Add a media element in a shell main page. 
* Open a Browser with Browser.OpenAsync
* Got back to the app

### Link to public reproduction project repository

https://github.com/cl3m/MediaElementShellBug

### Environment

```markdown
- .NET MAUI CommunityToolkit: 2.0.0
- OS: iOS 16
- .NET MAUI: 7.0
```

**Comment by MateuszLas421** [comment]
https://github.com/CommunityToolkit/Maui/issues/1110 
https://github.com/CommunityToolkit/Maui/issues/1110#issuecomment-1618065517

**Comment by alexanderdibenedetto** [comment]
I'm also seeing this issue:

``` 
2023-10-16 17:01:36.044 HawaiianAirlines[11756:811929] [AppCenterXamarinCrashes] ERROR: +[MSACWrapperLogger MSACWrapperLog:tag:level:]/10 Unhandled Exception:
ObjCRuntime.ObjCException: Objective-C exception thrown.  Name: UIViewControllerHierarchyInconsistency Reason: child view controller:<AVPlayerViewController: 0x15bb9aa00> should have parent view controller:<Maui_FixesAndWorkarounds_CustomShellSectionRootRenderer: 0x155f9d7d0> but actual parent is:<Microsoft_Maui_Platform_PageViewController: 0x15c950650>
```

Even when I don't use the Maui Fixes and WorkArounds package, same issue as above.

**Comment by alexanderdibenedetto** [comment]
@jfversluis

**Comment by krisadamstv** [comment]
Is there any workaround or replacement control you guys have used on Maui for video playing?

**Comment by mattleibow** [comment]
I also see this parent searching:

https://github.com/CommunityToolkit/Maui/blob/4168e5ab5446cc73f15e351a27245b1c8c597607/src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.macios.cs#L23-L35

**Comment by ne0rrmatrix** [comment]
I just checked the sample against main and it appears not to be an issue with dotnet 8.0.x. I verified it is still an issue with 7.0.x But testing against both main and 3.0.0 media element it works fine for me.
