### ISSUE TITLE
[BUG] ANDROID: buttons in Expander can't be clicked

### ISSUE THREAD

**Issue by glenn2223** [CommunityToolkit/Maui#1216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

After expanding the Expander, none of the buttons inside work - they should trigger a toast. 

Windows works as expected

### Expected Behavior

The click events to trigger

### Steps To Reproduce

1. Run the project on an Android device/emulator
2. Expand the expander at the bottom
3. Try to click on either button and no toast is fired

### Link to public reproduction project repository

https://github.com/glenn2223/Community-Toolkit-Mail-Android-Expander-Issue

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.2.0
- OS: Windows10 (issue produced on physical and emulated Android device)
- .NET MAUI: 7 & 8-preview
```

### Anything else?

Sorry for the shoddy code 😁

**Comment by brminnick** [comment]
I've confirmed this is not a bug in `Expander`.

The issue is that you've aded a GestureRecognizer to your `Button` which is overriding the `Clicked` action:

```xml
  <Button x:Name="AddButton"
          Clicked="AddClicked"
          Text="Add"
          HorizontalOptions="Start"
          VerticalOptions="End"
          WidthRequest="100">
      <Button.GestureRecognizers>
          <PointerGestureRecognizer PointerEntered="PointerGestureRecognizer_PointerEntered" />
      </Button.GestureRecognizers>
  </Button>
```

When you remove the `GestureRecognizer`, the `Clicked` event fires:

```xml
  <Button x:Name="AddButton"
          Clicked="AddClicked"
          Text="Add"
          HorizontalOptions="Start"
          VerticalOptions="End"
          WidthRequest="100">
  </Button>
```

I do not know if this behavior is intended by the .NET MAUI engineering team. I recommend opening this Issue on the [.NET MAUI GitHub Repo](https://github.com/dotnet/maui)

**Comment by glenn2223** [comment]
Ahh, I see. For some reason I thought I already had the gesture recogniser in place this when I switched from a horizontal stack to an expander - sorry about that.

Thanks for checking on this for me
