### ISSUE TITLE
[Proposal] UniformItemsLayout

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#122]
# UniformGrid

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Sample
* [x] Documentation https://github.com/MicrosoftDocs/CommunityToolkit/pull/75

## Summary
[summary]: #summary

The UniformItemsLayout is like the Grid, with the possibility of multiple rows and columns, but with one important difference: all rows and columns have the same size. That size is determined by the largest width and height of all the child elements. The child element with the largest width does not necessarily have to be the child element with the largest height.

Use the UniformItemsLayout when you need the Grid behavior without the need to specify different sizes for the rows and columns

## Detailed Design
[design]: #detailed-design

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
             x:Class="MyLittleApp.MainPage">

    <toolkit:UniformItemsLayout >
        <BoxView Color="Red" />
        <BoxView Color="Yellow" />
        <BoxView Color="Orange" />
        <BoxView Color="Purple" />
    </toolkit:UniformItemsLayout >

</ContentPage>
```

### C# Usage

```cs
class MyPage : ContentPage
{
  public MyPage()
  {
    Content = new UniformItemsLayout
    {
      Children = 
      {
         new BoxView { BackgroundColor = Colors.Red },
         new BoxView { BackgroundColor = Colors.Yellow },
         new BoxView { BackgroundColor = Colors.Orange },
         new BoxView { BackgroundColor = Colors.Purple },
      }
    };
  }
}
```

**Comment by VladislavAntonyuk** [comment]
@DoubleDBE UniformGrid doesn't have these properties and for now, measure and align all items automatically.
But we can easily add properties like MaxRows and MaxColumns.
@brminnick , @jsuarezruiz what do you think?

**Comment by DoubleDBE** [comment]
Thanks for the feedback!
I created a [discussion](https://github.com/CommunityToolkit/Maui/discussions/156)

**Comment by jsuarezruiz** [comment]
I think MaxRows and MaxColumns properties are are simple but powerful additions that do not affect the rest of the implementation, the addition seems fine to me. Let's continue the discussion here https://github.com/CommunityToolkit/Maui/discussions/156 (default values, fallbacks, etc).
