### ISSUE TITLE
[BUG] Windows map package not working with .NET 8 Preview

### ISSUE THREAD

**Issue by egvijayanand** [CommunityToolkit/Maui#1243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Getting this error upon App launch on the Windows platform configured with Maps.

"Method not found: 'Void Microsoft.Maui.Platform.MauiWebView..ctor()'."

### Expected Behavior

Quite like .NET 7, the app is expected to launch with the Maps view loaded on the underlying WebView.

### Steps To Reproduce

1. Created an MAUI app on .NET 8 Preview 5
2. Added the newly released "CommunityToolkit.Maui.Maps" NuGet package
3. Chained the extension method in the App startup
4. Set Windows as the target platform and tried to launch the app

### Link to public reproduction project repository

Default template of .NET 8 is suffice, just add Map control to the Main page

### Environment

```markdown
- .NET MAUI CommunityToolkit: 1.0.0 (CommunityToolkit.Maui.Maps package)
- OS: Windows 11 (10.0.22621.1778)
- .NET MAUI:.NET MAUI on .NET 8 Preview 5 (8.0.0-preview.5.8529)
```

### Anything else?

It works fine on .NET 7, facing this issue only on .NET 8.

**Comment by jfversluis** [comment]
This will fix it: https://github.com/dotnet/maui/pull/15541

Nothing we can do on our side. For the next .NET 8 preview it should work.

**Comment by egvijayanand** [comment]
> This will fix it: [dotnet/maui#15541](https://github.com/dotnet/maui/pull/15541)

If this is a known limitation, could have been mentioned in the release notes.

**Comment by jfversluis** [comment]
@egvijayanand you're talking about a preview version, probably not a lot of people are using it, also the same principles don't apply to preview versions.

**Comment by egvijayanand** [comment]
I think once it's available as a public preview, a few people would want to try it. So there's nothing wrong in leaving a word about it in the release notes, the sole purpose of having it.

**Comment by jfversluis** [comment]
@egvijayanand we didn't test it with the preview, we test things with the stable .NET MAUI bits, that is why it wasn't in there. We weren't aware. Thanks for testing it, it's in the release notes now.

**Comment by mikelor** [comment]
Thanks, because I was struggling to get this running in my main project with is running .Net 8 Preview 5.0
