### ISSUE TITLE
[BUG] Navigating back from MediaElement and calling DisconnectHandler results in crash

### ISSUE THREAD

**Issue by sjorsmiltenburg** [CommunityToolkit/Maui#1245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I have the mediaelement working on windows to play my video.
But when i navigate back and, as per the documentation, try to release the resources by calling
`MyMediaElement.Handler?.DisconnectHandler();`
during unload. It crashes with a Catastrophic Failure Exception.

I found multiple issues reporting this problem (like this one: https://github.com/CommunityToolkit/Maui/issues/962), but all issues seem to have been closed as in "fixed". So I don't understand why I'm still seeing this behaviour with the latest version.
Or maybe the documentation is outdated and we no longer need to call the DisconnectHandler method??

I'm using

- CommunityToolkit.Maui 5.2.0
- CommunityToolkit.Maui.MediaElement 2.0.0

### Expected Behavior

no crash on navigate back

### Steps To Reproduce

a reproduction sample is here: https://github.com/sjorsmiltenburg/maui_bugs

Steps to Reproduce
- build and run repro sample on windows
- click the bug 5 button
- navigate back

### Link to public reproduction project repository

https://github.com/sjorsmiltenburg/maui_bugs

### Environment

```markdown
CommunityToolkit.Maui 5.2.0
CommunityToolkit.Maui.MediaElement 2.0.0
```

**Comment by jfversluis** [comment]
So I think we do have a bug that we're calling Dispose twice. However, if I change that to happen only once, still if I call `Player.MediaPlayer.Dispose()` that will _always_ throw an exception and I'm not sure why...

**Comment by ne0rrmatrix** [comment]
I noticed the same thing and can confirm this is an issue.

**Comment by pictos** [comment]
Right now the workaround is to add a delay before calling the `DisconnectHandler`

```csharp
private async void Bug5View_Unloaded(object sender, EventArgs e)
{
    await Task.Delay(2_000);
    MyMediaElement.Handler?.DisconnectHandler();
}
```

The exception is related with the Frame navigation failure, So I don't think we are calling the Dispose method twice. I think the issue is that we dispose the `FramewokElement` (control in winUI) too son
