### ISSUE TITLE
[BUG] DockLayout doesn't update when DockPosition updated via Hot Reload / code behind

### ISSUE THREAD

**Issue by BretJohnson** [CommunityToolkit/Maui#1250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

DockLayout doesn't fully work with Hot Reload - when updating the `DockPosition` attached property, or the `ShouldExpandLastChild`/`HorizontalSpacing`/`VerticalSpacing` regular properties, the change isn't reflected until something forces it to layout again. Updating via code behind doesn't update immediate either (as is typical of these Hot Reload issues - since setting the property is what Hot Reload does).

### Expected Behavior

Property updates should be reflected immediately.

### Steps To Reproduce

1. Open and run the solution from the repro repository, debugging in order to use Hot Reload. I tested with Windows, though the issue likely happens on all platforms.
2. Open MainPage.xaml in VS
3. For the `RightToBottom` button, change the `DockPosition` from `Right` to `Bottom`.
Result: Hot Reload applies the change, but the button doesn't move, demonstrating that Hot Reload is broken here.
4. Click the `Move RightToLeft Button` button, which calls code behind to move the right button to the bottom.
Result: The UI doesn't update here either, demonstrating the same problem happens with code behind.
5. Add `ShouldExpandLastChild`/`HorizontalSpacing`/`VerticalSpacing` properties to the DockLayout.
Result: Hot Reload applies the change, but the layout doesn't update.

Now resize the window.
Result: Buttons are drawn in their new position, demonstrating that the changes were applied but they just didn't trigger the refresh immediately like they should have.

### Link to public reproduction project repository

https://github.com/BretJohnson/DockLayoutHotReloadNotWorking

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.2.0
- OS: Win 11
- .NET MAUI: 7.0.86
```

**Comment by BretJohnson** [comment]
@YBTopaz8 reported this issue on a call with me, so I reproduced it and wrote it up here.

**Comment by YBTopaz8** [comment]
Hi !
I just tried public reproduction project repo linked by @BretJohnson  on ANDROID, and I can confirm that Hot Reload doesn't work as espected too
