### ISSUE TITLE
[BUG] Windows Map Pin Click Event not working

### ISSUE THREAD

**Issue by pkzOR** [CommunityToolkit/Maui#1255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Using the new CommunityToolkit.Maui.Maps and running on Windows, the pin events do not fire.

### Expected Behavior

In the MapsPinPage demo, the MicrosoftPin should display an alert when the marker or info window is clicked

### Steps To Reproduce

- Download the zipped demo from https://github.com/CommunityToolkit/Maui/releases/tag/1.0.0-maps
 (NOTE: You need to add the CommunityToolkit.Maui.Maps package and set a Bing Map Key in MauiProgram.cs.  Should the map be able to run w/o a key?)
- Run the CommunityToolKit.Maui.Sample, 
- Select  the Windows Maps Pins Page
- Set breakpoint on the MapPinsPage.xaml.cs line 108 and 112
- Click Init Region
- Click the Microsoft Pin
- Breakpoint is not hit (An Alert should display)

A few notes:
Hovering over the Pin changes the cursor to a hand
The Info Window appears below the Pin, but there is no background color. Note that in Android, the marker info is not displayed by default and appears above the pin.

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui/releases/tag/1.0.0-maps

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS:Windows
- CommunityToolkit.Maui.Maps
- .NET MAUI:
```

### Anything else?

LOVE that this is now available for Windows!

**Comment by jfversluis** [comment]
Yep! I've seen this happening as well. Thanks for the report!
