### ISSUE TITLE
[BUG] Media Element - Platform Controls Hidden on iOS 16+

### ISSUE THREAD

**Issue by bradencohen** [CommunityToolkit/Maui#1259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

The platform controls are hidden when deploying to iOS 16+.

Using the following XAML:
```xaml
<toolkit:MediaElement Source="https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
                      ShouldAutoPlay="True"
                      ShouldShowPlaybackControls="True"
                      HeightRequest="300"
                      WidthRequest="400" />
```

**iOS 15.5**, when tapped the controls show:
![image](https://github.com/CommunityToolkit/Maui/assets/11482832/fbc9185b-08c4-46c4-9ada-2aedb87cf091)

**iOS 16**, when tapped the controls don't show:
![image](https://github.com/CommunityToolkit/Maui/assets/11482832/a19fa2c0-976a-44d6-ae1a-090bee86d47f)

Tapping the direct center of the video seems to work as a play/pause, but that seems to just be residue of this bug.

### Expected Behavior

The platform controls should be working in new versions of iOS.

### Steps To Reproduce

1. Add a `MediaElement` to a page:
```xaml
<toolkit:MediaElement Source="https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
                      ShouldAutoPlay="True"
                      ShouldShowPlaybackControls="True"
                      HeightRequest="300"
                      WidthRequest="400" />
```
2. See differences when deploying to iOS 16+ devices

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui/tree/main/samples/CommunityToolkit.Maui.Sample

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.2.0
- OS: iOS 16+
- .NET MAUI: .net 7
```

**Comment by bradencohen** [comment]
Could be related: https://github.com/xamarin/XamarinCommunityToolkit/issues/1927

**Comment by jfversluis** [comment]
Would you be able to test the resulting NuGet package from [this PR](https://github.com/CommunityToolkit/Maui/pull/1279) and see if that revolves your issue?

If you're not sure how to do that, please review [this wiki article](https://github.com/CommunityToolkit/Maui/wiki/Preview-Packages#pull-requests-).

**Comment by bradencohen** [comment]
Working like a charm, thanks so much! The controls look a little different, so I thought that was worth mentioning, but definitely seems to be fully functional over here: 
![image](https://github.com/CommunityToolkit/Maui/assets/11482832/e3a325b4-019d-4103-bb17-5fbbbd7c114c)

Thanks again!
