### ISSUE TITLE
[BUG] CommunityToolkit/Maui/Maps MapClicked event doesn't trigger on Windows

### ISSUE THREAD

**Issue by al185104** [CommunityToolkit/Maui#1268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Community toolkit Maps for Windows doesn't trigger the event in code-behind when **MapClicked** is added.

### Expected Behavior

Community toolkit Maps for Windows should trigger the code-behind method set for **MapClicked** in xaml.

### Steps To Reproduce

1. Use https://github.com/jfversluis/MauiToolkitWindowsMapsSample repo.
2. Add **MapClicked** event to the map and assign to a code-behind method.
3. Add a breakpoint in the code-behind method.
4. Run and click the map
Observe: code-behind is not being triggered at all.

### Link to public reproduction project repository

https://github.com/jfversluis/MauiToolkitWindowsMapsSample

### Environment

```markdown
- .NET MAUI CommunityToolkit.Maui.Maps 1.0.2
- OS:Windows 10.0.19041.0
- .NET MAUI: 7.0.81/7.0.100
- .NET Runtime: net7.0
```

**Comment by brminnick** [comment]
Hi @al185104! Could you please provide a completed reproduction sample?

**Comment by al185104** [comment]
Hi @brminnick , thanks for responding so quick. I'm big a fan, but I'm pretty new to reporting bugs so please bear with me..
For the sample, I actually tried the repo from @jfversluis  on this and just added a MapClicked event on top of it, but for your reference I've created a new repo for this (https://github.com/al185104/MyMapsTest)..
I attached the bing map key for a moment while you check it out, but I'll have to remove it soon.. thanks a lot for the help!
👍

**Comment by jfversluis** [comment]
Yeah I think I might have not fixed that one yet. Focused on the pins first.
