### ISSUE TITLE
[Proposal] .Net 8 Preview (Beta) Nuget 

### ISSUE THREAD

**Issue by gktval** [CommunityToolkit/Maui#1284]
### Feature name

.Net 8 Preview (Beta) Nuget

### Link to discussion

https://github.com/CommunityToolkit/Maui/issues/1243

### Progress tracker

- [X] Android Implementation
- [X] iOS Implementation
- [X] MacCatalyst Implementation
- [X] Windows Implementation
- [X] Tizen Implementation
- [ ] Unit Tests
- [ ] Samples
- [ ] Documentation

### Summary

Create a .Net 8 Preview version as a beta nuget. So not the official nuget that people are forced to use, but just a beta nuget that people can optionally upgrade to if they have decided to start using .Net 8 Preview.

### Motivation

A lot of bug fixes are being rolled out for .Net 8 Preview versions of Maui; at this point, the .Net 8 preview is as stable as the .Net 7 (7.0.86) version. 

A beta Nuget will not notify people that they should update to the new version, and will keep the stable .Net 7 version as the official Nuget. But it will allow people who are preparing for .Net 8  to start developing and test for bug in preparation for its official launch. Currently, if you reference the 5.2.0 CommunityToolkit Nuget, it will throw a TypeLoadException on startup. 

### Detailed Design

na

### Usage Syntax

```markdown
Reference .Net 8 Preview5.8529
```

### Drawbacks

The only reason for not preparing for .Net 8 is that it takes extra time to create a new Nuget.

**Comment by IeuanWalker** [comment]
@gktval can you not use a .net 7 nuget in a .net 8 project? _I thought you could_

**Comment by gktval** [comment]
I get a TypeLoadException when I startup in the CommunityToolkit.Maui.dll when starting the project.

**Comment by SpenceDahl** [comment]
This is a terrific idea.
