### ISSUE TITLE
[BUG] plass add Viewbox for MAUI

### ISSUE THREAD

**Issue by AbdalaMask** [CommunityToolkit/Maui#1295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

plass add Viewbox for MAUI

### Expected Behavior

plass add Viewbox for MAUI

### Steps To Reproduce

plass add Viewbox for MAUI

### Link to public reproduction project repository

plass add Viewbox for MAUI

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS:
- .NET MAUI:plass add Viewbox for MAUI
```

### Anything else?

plass add Viewbox for MAUI

**Comment by pictos** [comment]
@AbdalaMask I'll close this issue since you didn't fill in the field correctly. Please follow our template, and help us to help you.
