### ISSUE TITLE
[BUG] The VerticalOptions of Refresh or other Layout is unavaiable  in the StateContainer.StateViews on Android platform

### ISSUE THREAD

**Issue by rwecho** [CommunityToolkit/Maui#1297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

```xaml
             <VerticalStackLayout mct:StateContainer.CurrentState="{Binding RefreshState}"
                                 HeightRequest="100"
                                BackgroundColor="red">
                   <mct:StateContainer.StateViews>
                       <RefreshView mct:StateView.StateKey="Success" VerticalOptions="FillAndExpand">
                           <ScrollView>
                                <Label Text="hello world"></Label>
                           </ScrollView>
                       </RefreshView>
                </mct:StateContainer.StateViews>
            </VerticalStackLayout>
``` 

Like the above code, the RefreshView should be visible if the data loaded success. It's ok on the Windows Machine. But when I debug it on Android emulators and Android phones, the RefreshView is invisible.

### Expected Behavior

The layout in the StateViews display.

### Steps To Reproduce

1. open the sample and change the label with a RefreshView .
2. set the target with an Android emulator.
3. By default the component is not displayed until we set a HeightRequest. 

### Link to public reproduction project repository

https://github.com/rwecho/Maui/blob/c23990f3df8565658670bb7fc2d4a72bde016bb9/samples/CommunityToolkit.Maui.Sample/Pages/Layouts/StateContainerPage.xaml#L204-L229

In the StateContainerPage.xaml page , I add a demo in the bottom of the page.

### Environment

```markdown
- .NET MAUI CommunityToolkit:5.2.0
- OS: Android 11
- .NET MAUI:8.0.0-preview.5.23280.8
```

**Comment by vhugogarcia** [comment]
@rwecho, the behavior you’re experiencing with the RefreshView inside a VerticalStackLayout in .NET MAUI is indeed an issue. [This issue has been reported and is being tracked by the .NET MAUI team](https://github.com/dotnet/maui/issues/14477). Unfortunately, there isn’t a straightforward workaround at the moment, but you can keep an eye on the issue for updates. Hopefully, it will be resolved in a future release!

For the reason mentioned above, I'm closing this ticket.
