### ISSUE TITLE
[BUG] Popup margin on iOS 

### ISSUE THREAD

**Issue by frarcedev** [CommunityToolkit/Maui#1312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Using a Popup I could define the size, because I have to show the popup with a full width, however it is only functional on Android, on iOS it has a different behavior, forcing to show a vertical and horizontal margin(or padding maybe) which cannot be removed.

Android
![Screenshot 2023-07-30 at 21 24 18](https://github.com/CommunityToolkit/Maui/assets/64759374/13f0857c-b49e-4e4e-90a4-621eae8647ed)

iOS
![Screenshot 2023-07-30 at 21 25 01](https://github.com/CommunityToolkit/Maui/assets/64759374/07d83aac-c333-412d-91de-bcdc88897525)

### Expected Behavior

It should be possible to define the full width and full height for iOS in the same way as Android.

### Steps To Reproduce

1. Open and run solution from reproduction repository on iOS.
2. Click the button "Open Popup" and observe the bug.

### Link to public reproduction project repository

https://github.com/frarcedev/PopupApp

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.2.0
- OS: Simulator iPhone 14 PRO iOS 16.4 and Physical Device iPhone 14 PRO iOS 16.6
- .NET MAUI: 7.0.86
```

### Anything else?

The public reproduction project is created using .NET MAUI Blazor but in .NET MAUI the behavior is the same.

**Comment by brminnick** [comment]
Duplicate https://github.com/CommunityToolkit/Maui/issues/1317
