### ISSUE TITLE
[BUG] The size and position of Popup is wrong on Android and iOS.

### ISSUE THREAD

**Issue by cat0363** [CommunityToolkit/Maui#1317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I won't mention the difference between Popup's Margin and CornerRect here.

In order to make it easier to understand the four corners of the Popup, the layout is as follows.

    <toolkit:Popup xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
        xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
        x:Class="MauiComm_IssuePopupSizePosition.PopupPage">
        <Grid VerticalOptions="Fill" HorizontalOptions="Fill" BackgroundColor="Red">
            <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="Start" HorizontalOptions="Start" BackgroundColor="Blue" />
            <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="Start" HorizontalOptions="End" BackgroundColor="Blue" />
            <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="End" HorizontalOptions="Start" BackgroundColor="Blue" />
            <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="End" HorizontalOptions="End" BackgroundColor="Blue" />
        </Grid>
    </toolkit:Popup>

<img width="132" alt="popup" src="https://github.com/CommunityToolkit/Maui/assets/125236133/1e1dcec5-cdfa-48ed-adc7-a6bbdf828ee1">

Specify the following for Size, HorizontalOptions, VerticalOptions of Popup.

    Size = "100, 100"
    HorizontalOptions = "Fill"
    VerticalOptions = "Fill"

Below are the execution results for Android and iOS.

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/27957828-323d-4c76-ade1-aab8fe575262" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/71382545-7eba-4bc5-b140-b8aad7041baf" /></td>
  </tr>
</table>

Android shows the Popup in the center, iOS shows the Popup in the top left, and in iOS it's not showing up in the intended position. I was expecting iOS to show a popup in the middle like Android does.

Next, when you specify a size for the popup that exceeds the screen size.

    Size = "1000, 1000"

I verified by changing HorizontalOptions and VerticalOptions as follows on Android and iOS.

   HorizontalOptions = "Start"
   VerticalOptions = "Start"

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/08a4db94-043f-40c5-b51a-a8bd8e14d89c" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/a76049f4-45ac-47ec-9e6f-7711869a6637" /></td>
  </tr>
</table>

   HorizontalOptions = "Center"
   VerticalOptions = "Start"

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/c7d7913a-04ff-40f4-93d7-5aab0528d6d6" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/9d55ccbb-e0ab-41d6-a2aa-c54f6adebac8" /></td>
  </tr>
</table>

   HorizontalOptions = "End"
   VerticalOptions = "Start"

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/0bbb370b-8720-4d34-a164-c74463450c49" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/4734a6a0-0f6b-4f9a-9908-fe88a2fdfabb" /></td>
  </tr>
</table>

   HorizontalOptions = "Fill"
   VerticalOptions = "Start"

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/cac10a8f-ae3b-4716-b9d8-3fdce6d9c4c2" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/47a04053-398e-4c11-a0f4-684b82800329" /></td>
  </tr>
</table>

   HorizontalOptions = "Start"
   VerticalOptions = "Center"

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/6f4d58f9-0da2-4517-975b-0b190a4a912d" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/46343cf4-8aac-4646-b433-adac7e489ae8" /></td>
  </tr>
</table>

   HorizontalOptions = "Center"
   VerticalOptions = "Center"

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/38e803ea-2d50-4897-8ac8-b690579bd8cc" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/f212fdf0-5f7d-47b0-a019-ec7f6e8eee01" /></td>
  </tr>
</table>

   HorizontalOptions = "End"
   VerticalOptions = "Center"

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/8361ec47-3b64-42bd-bf40-33ab3b28f27e" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/e88d125d-151e-41e5-b042-453247fd1256" /></td>
  </tr>
</table>

   HorizontalOptions = "Fill"
   VerticalOptions = "Center"

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/0ff92f35-4c8b-47c8-be7e-114cc8a93565" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/11140d93-adef-4672-9a89-f5ba93aaf55e" /></td>
  </tr>
</table>

   HorizontalOptions = "Start"
   VerticalOptions = "End"

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/2a3ee846-55b0-4c8c-bd9e-8998a758117b" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/e0c4e6c1-2227-4115-861a-6847a302cbaf" /></td>
  </tr>
</table>

   HorizontalOptions = "Center"
   VerticalOptions = "End"

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/37e268cd-4ad3-4bde-bf50-1b515e80c5e0" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/9c159181-f234-4a1e-ab0a-8a4d03b23640" /></td>
  </tr>
</table>

   HorizontalOptions = "End"
   VerticalOptions = "End"

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/c23e76af-5109-4cec-9b7d-5159c09a0d02" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/f2feabe4-8abf-4a97-80bc-0beb80980051" /></td>
  </tr>
</table>

   HorizontalOptions = "Fill"
   VerticalOptions = "End"

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/2d8019cc-3469-4c99-9241-ed0d3f10fce7" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/6a335269-1dc8-4f4c-8e4f-41f2490cd418" /></td>
  </tr>
</table>

   HorizontalOptions = "Start"
   VerticalOptions = "Fill"

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/8f232dc6-298e-4a62-ae5a-fab3a294e45a" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/40bd81d8-9eaa-4660-8227-442ef80b6c9a" /></td>
  </tr>
</table>

   HorizontalOptions = "Center"
   VerticalOptions = "Fill"

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/986c6ac3-0aea-4462-9c69-107c6de4cbd0" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/62563cfc-17c5-4d4c-87d3-690658029933" /></td>
  </tr>
</table>

   HorizontalOptions = "End"
   VerticalOptions = "Fill"

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/0516d0e3-df09-4312-b9e1-30d99db95331" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/5655707d-f541-4281-a362-7a15c185d673" /></td>
  </tr>
</table>

   HorizontalOptions = "Fill"
   VerticalOptions = "Fill"

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/4148973c-da45-428d-a355-5d2f31ae8d2f" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/8b1b6de4-d6c0-464a-961d-1ea05cedc31f" /></td>
  </tr>
</table>

Everything looks correct on Android, but it is only displayed starting from the top right. I was expected that when I gave a Popup a size greater than the screen size, the size of the Popup would be limited by the screen size.

On iOS, Popups are disappearing or appearing in unintended sizes and positions.
Similarly, I was expected that when I gave a Popup a size greater than the screen size, the size of the Popup would be limited by the screen size.

### Expected Behavior

If the size of the Popup does not exceed the screen size, I was expected it to be displayed in the center if Fill is specified for HorizontalOptions and VerticalOptions.

<table>
  <tr>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/3088673f-2415-4f63-a721-8c38fb1c4539" /></td>
  </tr>
</table>

I was expected the Popup's size to be limited to the screen size if the Popup's size exceeds the screen size.

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/29d24a05-4f88-4f21-95f9-5b8044593cf3" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/688d7b90-1a0a-4f2f-9e91-866adc4f2eb9" /></td>
  </tr>
</table>

### Steps To Reproduce

The steps to reproduce are as follows.

[Case 1]

1. Launch the app uploaded to github with the device on iOS
2. Set With to 100, Height to 100, HorizontalOptions to Fill, VerticalOptions to Fill
3. Press Show button

[Case 2]

1. Launch the app uploaded to github with the device on iOS
2. Set With to 1000, Height to 1000
3. Select any HorizontalOptions
4. Select any VerticalOptions
5. Press Show Button

### Link to public reproduction project repository

https://github.com/cat0363/MauiComm-IssuePopupSizePosition.git

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.2.0
- OS: iOS 16.4, Android 11.0
- .NET MAUI: 7.0.92
```

**Comment by cat0363** [comment]
This issue can be resolved by modifying as follows.

Below is the modified code on the Android side.

[src\CommunityToolkit.Maui.Core\Views\Popup\PopupExtensions.android.cs]

    public static void SetSize(this Dialog dialog, in IPopup popup, in AView container)
    {
        ArgumentNullException.ThrowIfNull(popup.Content);

        int horizontalParams, verticalParams;

        var window = GetWindow(dialog);
        var context = dialog.Context;
        var decorView = (ViewGroup)window.DecorView;
        var child = decorView.GetChildAt(0) ?? throw new NullReferenceException();
        var win = context.GetWindow();
        var density = context.GetDisplayDensity();

        int realWidth = 0,
        realHeight = 0,
        realContentWidth = 0,
        realContentHeight = 0;

        CalculateSizes(popup, context, ref realWidth, ref realHeight, ref realContentWidth, ref realContentHeight);

        if (win is not null)
        {
            realWidth = realWidth <= win.Width * density ? realWidth : (int)(win.Width * density);
            realHeight = realHeight <= win.Height * density ? realHeight : (int)(win.Height * density);
            window.SetLayout(realWidth, realHeight);
        }

        ... omit

    }

Below is the modified code on the iOS side.

[src\CommunityToolkit.Maui.Core\Views\Popup\PopupExtensions.macios.cs]

    public static void SetLayout(this MauiPopup mauiPopup, in IPopup popup)
    {
        if (mauiPopup.View is null)
        {
            return;
        }

        CGRect frame;

        if (mauiPopup.ViewController?.View?.Window is UIWindow window)
        {
            frame = window.Frame;
        }
        else
        {
            frame = UIScreen.MainScreen.Bounds;
        }

        if (mauiPopup.PopoverPresentationController is null)
        {
            throw new InvalidOperationException("PopoverPresentationController cannot be null");
        }

        if (popup.Anchor is null)
        {			
            var originY = popup.VerticalOptions switch
            {
                Microsoft.Maui.Primitives.LayoutAlignment.Start => mauiPopup.PreferredContentSize.Height <= frame.Height ? 0f : -frame.Height,
                Microsoft.Maui.Primitives.LayoutAlignment.End => mauiPopup.PreferredContentSize.Height <= frame.Height ? frame.Height : -frame.Height,
                Microsoft.Maui.Primitives.LayoutAlignment.Center => mauiPopup.PreferredContentSize.Height <= frame.Height ? frame.GetMidY() : -frame.Height,
                _ => mauiPopup.PreferredContentSize.Height <= frame.Height ? frame.Height / 2 : -frame.Height
            };

            var originX = popup.HorizontalOptions switch
            {
                Microsoft.Maui.Primitives.LayoutAlignment.Start => mauiPopup.PreferredContentSize.Width <= frame.Width ? 0f : -frame.Width,
                Microsoft.Maui.Primitives.LayoutAlignment.End => mauiPopup.PreferredContentSize.Width <= frame.Width ? frame.Width : -frame.Width,
                Microsoft.Maui.Primitives.LayoutAlignment.Center => mauiPopup.PreferredContentSize.Width <= frame.Width ? frame.GetMidX() : -frame.Width,
                _ => mauiPopup.PreferredContentSize.Width <= frame.Width ? frame.Width / 2 : -frame.Width
            };

            ... omit
        }
        else
        {
            var view = popup.Anchor.ToPlatform(popup.Handler?.MauiContext ?? throw new InvalidOperationException($"{nameof(popup.Handler.MauiContext)} Cannot Be Null"));
            mauiPopup.PopoverPresentationController.SourceView = view;
            mauiPopup.PopoverPresentationController.SourceRect = view.Bounds;
        }
    }

I will create a PR after refactoring.

Below is the execution result.

    Size = "100, 100"
    HorizontalOptions = "Fill"
    VerticalOptions = "Fill"

<table>
  <tr>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/3088673f-2415-4f63-a721-8c38fb1c4539" /></td>
  </tr>
</table>

    Size = "1000, 1000"
    HorizontalOptions = "Start"
    VerticalOptions = "Start"

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/29d24a05-4f88-4f21-95f9-5b8044593cf3" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/688d7b90-1a0a-4f2f-9e91-866adc4f2eb9" /></td>
  </tr>
</table>

    Size = "300, 1000"
    HorizontalOptions = "Start"
    VerticalOptions = "Start"

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/5ffbf62e-0e52-4c3d-8eef-4df64a7677da" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/5e63f711-3ace-4713-a35b-eaee7d9e630a" /></td>
  </tr>
</table>

    Size = "300, 1000"
    HorizontalOptions = "Center"
    VerticalOptions = "Start"

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/2f102f0b-fca7-4fe2-b173-93fc5a61931e" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/175fc4af-d0ea-48a5-9862-7b11712ab4ac" /></td>
  </tr>
</table>

    Size = "300, 1000"
    HorizontalOptions = "End"
    VerticalOptions = "Start"

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/7da92585-b960-487b-927f-7f922cbfa9b0" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/1e9cf326-0d3d-44da-9b22-753df363f2dc" /></td>
  </tr>
</table>

    Size = "300, 1000"
    HorizontalOptions = "Fill"
    VerticalOptions = "Start"

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/c74993b0-f2f6-4dd7-9bbb-1445603df208" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/8b8a4d51-e076-43c4-90bd-92318f6d14e0" /></td>
  </tr>
</table>

**Comment by cat0363** [comment]
In addition to the fix in the previous post, by adding the following fix, it is possible to resize the Popup after rotation on Android.

    protected override void ConnectHandler(MauiPopup platformView)
    {
        Container = platformView.SetElement(VirtualView);
        if (Container is not null)
        {
            Container.LayoutChange += new EventHandler<AView.LayoutChangeEventArgs>(container_LayoutChange);
        }
    }

    protected override void DisconnectHandler(MauiPopup platformView)
    {
        platformView.Dispose();
        if (Container is not null)
        {
            Container.LayoutChange -= new EventHandler<AView.LayoutChangeEventArgs>(container_LayoutChange);
        }
    }

    void container_LayoutChange(object? sender, EventArgs e)
    {
        if (VirtualView?.Handler?.PlatformView is Dialog dialog && Container is not null)
        {
            PopupExtensions.SetSize(dialog, VirtualView, Container);
        }
    }

The following are the execution results before and after adding this modification.

    Size = "100, 600"
    HorizontalOptions = "Center"
    VerticalOptions = "Center"

[Before fix]

<table>
  <tr>
    <td>[Before rotation]</td>
    <td>[After rotation]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/ce550851-bcec-4eb8-b205-5d0c2fff7f86" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/bb85aec1-824a-4613-8f8d-694354272e3c" /></td>
  </tr>
</table>

[After fix]

<table>
  <tr>
    <td>[Before rotation]</td>
    <td>[After rotation]</td>
  </tr>
  <tr>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/a6ef9aed-720d-4ec6-8ab0-19b78a78f3f5" /></td>
    <td><img width="400" src="https://github.com/CommunityToolkit/Maui/assets/125236133/95c560c9-212e-42d8-a0cc-248ca4335066" /></td>
  </tr>
</table>

With this fix, you can see that it is resized after rotation.

**Comment by brminnick** [comment]
Thanks @cat0363!

Could you please submit a PR with the bug fix?

**Comment by cat0363** [comment]
@brminnick , Thank you for your reply. 
I'll submit a PR once I've done some testing.

**Comment by cat0363** [comment]
By modifying the iOS side as follows, it is possible to cover almost the entire screen.

[src\CommunityToolkit.Maui.Core\Views\Popup\PopupExtensions.macios.cs]

    public static void SetLayout(this MauiPopup mauiPopup, in IPopup popup)
    {
        if (mauiPopup.View is null)
        {
            return;
        }

        CGRect frame;

        if (mauiPopup.ViewController?.View?.Window is UIWindow window)
        {
            frame = window.Frame;
        }
        else
        {
            frame = UIScreen.MainScreen.Bounds;
        }

        if (mauiPopup.PopoverPresentationController is null)
        {
            throw new InvalidOperationException("PopoverPresentationController cannot be null");
        }

        if (popup.Anchor is null)
        {			
            var originY = popup.VerticalOptions switch
            {
                Microsoft.Maui.Primitives.LayoutAlignment.Start => mauiPopup.PreferredContentSize.Height < frame.Height ? mauiPopup.PreferredContentSize.Height / 2 : -frame.GetMidY(),
                Microsoft.Maui.Primitives.LayoutAlignment.End => mauiPopup.PreferredContentSize.Height < frame.Height ? frame.Height - (mauiPopup.PreferredContentSize.Height / 2) : -frame.GetMidY(),
                Microsoft.Maui.Primitives.LayoutAlignment.Center => mauiPopup.PreferredContentSize.Height < frame.Height ? frame.GetMidY() : -frame.GetMidY(),
                _ => mauiPopup.PreferredContentSize.Height < frame.Height ? frame.GetMidY() : -frame.GetMidY()
            };

            var originX = popup.HorizontalOptions switch
            {
                Microsoft.Maui.Primitives.LayoutAlignment.Start => mauiPopup.PreferredContentSize.Width < frame.Width ? mauiPopup.PreferredContentSize.Width / 2 : -frame.GetMidX(),
                Microsoft.Maui.Primitives.LayoutAlignment.End => mauiPopup.PreferredContentSize.Width < frame.Width ? frame.Width - (mauiPopup.PreferredContentSize.Width / 2) : -frame.GetMidX(),
                Microsoft.Maui.Primitives.LayoutAlignment.Center => mauiPopup.PreferredContentSize.Width < frame.Width ? frame.GetMidX() : -frame.GetMidX(),
                _ => mauiPopup.PreferredContentSize.Width < frame.Width ? frame.GetMidX() : -frame.GetMidX()
            };

            ... omit

            mauiPopup.PopoverPresentationController.SourceRect = new CGRect(originX, originY, 0, 0);
            mauiPopup.PopoverPresentationController.PermittedArrowDirections = 0;
            mauiPopup.PopoverPresentationController.PopoverLayoutMargins = new UIEdgeInsets(1, 0, 0, 0);
        }
        else
        {
            var view = popup.Anchor.ToPlatform(popup.Handler?.MauiContext ?? throw new InvalidOperationException($"{nameof(popup.Handler.MauiContext)} Cannot Be Null"));
            mauiPopup.PopoverPresentationController.SourceView = view;
            mauiPopup.PopoverPresentationController.SourceRect = view.Bounds;
        }
    }

The added code is below.

    mauiPopup.PopoverPresentationController.PopoverLayoutMargins = new UIEdgeInsets(1, 0, 0, 0);

For some reason, the Top of UIEdgeInsets must be set to 1 to function. A value of 0 will allocate a margin.
Below is the execution result.

https://github.com/CommunityToolkit/Maui/assets/125236133/806b3d81-fccf-4b8a-b611-a44d840aaddd

The safe area cannot be covered with a popup, but this fix allows you to place a popup using the entire screen.
I will start creating a PR, so please wait for a while.

**Comment by cat0363** [comment]
Hi, @brminnick 
I just finished creating a PR.
I have a question for you. I'd like to hear your thoughts on another PR 
I've created right now, if you have the time.I can't tell if it's a 
.NET MAUI bug or not. Thank you.

**Comment by brminnick** [comment]
> I just finished creating a PR.

Thanks! We'll take a look. 

> I can't tell if it's a
.NET MAUI bug or not.

Feel free to open a new [Bug Report](https://github.com/CommunityToolkit/Maui/issues/new?assignees=&labels=bug%2Cunverified&projects=&template=bug_report_template.yml&title=%5BBUG%5D+), and include a reproduction sample, and we'll take a look.

**Comment by cat0363** [comment]
> > I can't tell if it's a
> > .NET MAUI bug or not.
> 
> Feel free to open a new [Bug Report](https://github.com/CommunityToolkit/Maui/issues/new?assignees=&labels=bug%2Cunverified&projects=&template=bug_report_template.yml&title=%5BBUG%5D+), and include a reproduction sample, and we'll take a look.

@brminnick , Thank you for your reply.
This matter was about the following PR. 
Thanks to many collaborators, I was able to draw conclusions.

    Add routing of BindingContext of Popup
