### ISSUE TITLE
[BUG] IconTintColorBehavior causes image not to load on Windows 

### ISSUE THREAD

**Issue by tomridl** [CommunityToolkit/Maui#1333]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When the IconTintColorBehavior behaviour is applied to the image and the image has a heightrequest or widthrequest set, the image does not appear in the page at all with MCT version 5.3.0. In version 5.2.0, the tinted overlay image was offset, this was fixed in #1271, but in 5.3.0 the original image and tinted overlay don't show at all when run on Windows. Have checked iOS and MacOS and both work fine.
![Screenshot 2023-08-10 at 10 01 24](https://github.com/CommunityToolkit/Maui/assets/2032782/e8dde5ff-f301-4bb2-a29b-b293e513d4e5)

### Expected Behavior

The image should appear with the specified tint colour overlayed on it.

### Steps To Reproduce

1. Create a new blank MAUI project
2. Add CommunityToolkit.Maui version 5.3.0
3. Initialise the toolkit in MauiApp builder
4. Add XAML reference to toolkit
5. Add Image.Behaviors and IconTintColorBehavior with any TintColor to the dotnet_bot image
6. Run the project

Or download and run the project from the linked repo.

### Link to public reproduction project repository

https://github.com/tomridl/IconTintColorBehaviour-Windows-Bug

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.3.0
- OS: Windows 11 Pro Version 22H2 Build 22621.2134
- .NET MAUI: 7.0.92
```

**Comment by Sokol2001** [comment]
I've checked and this bug does exist
