### ISSUE TITLE
[BUG] ContentTemplate missing from Expander

### ISSUE THREAD

**Issue by bradencohen** [CommunityToolkit/Maui#1337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Please feel free to correct me if I'm missing something, but the `ContentTemplate` property seems to be in the original proposal: https://github.com/CommunityToolkit/Maui/issues/109 and doesn't seem to be there now. I can see that in the docs it says not to use `Expander` in `ListView`... Does this also apply to CollectionView? Even when specified as `MeasureAllItems`?

### Expected Behavior

You should be able to provide a template for an expander like such: 

```csharp
var expander = new Expander { ContentTemplate = new DataTemplate( GetItemTemplate ) };
```

### Steps To Reproduce

1. Use an Expander anywhere.
2. Observe the missing property.

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.3.0
- OS:All
- .NET MAUI: .net 8
```

### Anything else?

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/expander

**Comment by VladislavAntonyuk** [comment]
CollectionView works fine.
Initial design was a copy from Xamarin community toolkit. Current implementation was developed from scratch and may differ from the original proposal
