### ISSUE TITLE
[BUG] FileSaver Permission Issues with Android 13.0 API 33

### ISSUE THREAD

**Issue by cworth33** [CommunityToolkit/Maui#1340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

FileSaver.Default.SaveAsync always returns false result with exception message "Microsoft.Maui.ApplicationModel.PermissionException: Storage permission is not granted" 

### Expected Behavior

FileSaver.Default.SaveAsync should be able to work out of the box with android 13.0 and API 33.

### Steps To Reproduce

1. Open and run solution for reproduction repo
2. Click the "Click Me" button

### Link to public reproduction project repository

https://cworth33@dev.azure.com/cworth33/Public/_git/FileSaverBug_API33

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.3.0
- OS: Android 13.0 API Level 33
- .NET MAUI:
```

**Comment by VladislavAntonyuk** [comment]
The issue is with permissions api, not filesaver

**Comment by VladislavAntonyuk** [comment]
https://github.com/CommunityToolkit/Maui/issues/998
