### ISSUE TITLE
[BUG] InvalidOperationException on iOS when opening Popup from FlyoutPage which is opened as modal

### ISSUE THREAD

**Issue by IvanMi773** [CommunityToolkit/Maui#1347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When l'm trying to show popup using `this.ShowPopup` in `FlyoutPage` opened as modal, l'm getting `System.InvalidOperationException` (The Parent must be of type Microsoft.Maui.Handlers.PageHandler). I've checked this behavior on iOS and Android and it seems to be iOS issue.

### Expected Behavior

Calling `ShowPopup` in `FlyoutPage` should not throw an exception

### Steps To Reproduce

1. Open and run on iOS simulator reproduction project;
2. Tap on 'Open modal' button;
3. Tap on 'click' button;

### Link to public reproduction project repository

https://gitlab.com/IvanMi773/flyout-page-bug-reproduction

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.3.0;
- OS: macOS 13.5;
- .NET MAUI: 7.0.92;
```

### Anything else?

Probably similar issue but for `NavigationPage`: https://github.com/CommunityToolkit/Maui/issues/822

**Comment by TRybina132** [comment]
Hello! Could you specify which IOS version are you using?

**Comment by IvanMi773** [comment]
Hi! l was checking this on iOS 16

**Comment by cat0363** [comment]
@IvanMi773 , Is the behavior you're expecting something like the following?

https://github.com/CommunityToolkit/Maui/assets/125236133/a0e74dff-26a5-4bd2-978f-e3711332201c

If the above is what you expect, I can create a PR.

**Comment by IvanMi773** [comment]
@cat0363 Yes. This is what l'm expecting
