### ISSUE TITLE
[BUG] MediaElement does not play audio if 'Silent mode' is switched on in iOS

### ISSUE THREAD

**Issue by ArchangelWTF** [CommunityToolkit/Maui#1358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

iOS currently does not play audio even when a user has requested to play audio / video

### Expected Behavior

Audio is expected to be played, despite silent mode having been switched on.

### Steps To Reproduce

1. Switch silent mode on for your iOS device / Simulator
2. Launch the official CommunityToolkit sample app and go to the MediaElement view
3. Video should play but Audio should be muted (Even if the volume slider in iOS / MediaElement is at 100%)

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui

### Environment

```markdown
- .NET MAUI CommunityToolkit (MediaElement): 2.0.0
- OS: Windows 11
- .NET MAUI: 7.0.92
```

**Comment by brminnick** [comment]
@jfversluis Just curious - when you created `CommunityToolkit.Maui.MediaElement` did you purposely disable iOS media from playing sound when the hardware mute button is toggled to silent?

**Comment by jfversluis** [comment]
I didn't do anything intentionally. I think that is just the default behavior for iOS and you can sort of override it.

Looking at the PR, I definitely think this is something good to have, I'm not sure if just enabling this by default is the way though. I'd love to give developers a little bit more control over it in the form of a property or method call to enable/disable this behavior.

For example, what I love UX wise is with Instagram where it plays muted at first, but if you change the volume it will automatically unmute (and stay unmuted). To be honest I'm not sure if this is something Instagram did or that's how iOS works (and thus it already works for `MediaElement` as well?) but that is the power I would love to give to our consumers.

**Comment by ArchangelWTF** [comment]
I think having it as a property would definitively be the most feasible, as far as I can remember iOS needs to have SetActive set before AVPlayer starts playing else it would not have any effect.

**Comment by ArchangelWTF** [comment]
I have added a property for it, and I've left it opt-in by default so that it keeps the default behavior that you can find in MediaElement now.

**Comment by brminnick** [comment]
Right now the new property, `ShouldBypassSilentMode`, only functions on iOS. 

How can similar functionality also be leveraged for macOS, Android, Windows and Tizen?

**Comment by ArchangelWTF** [comment]
@brminnick I actually agree to this which is why I didn't implement a property for it with my initial PR, as I figured it was more simply overlooked than a feature (And because other devices support outputting Audio even if set to Mute or Do not Disturb)

To get to your point, technically on Android one could get the system service for audio and mute ExoPlayer if the ringer mode is set to silent.. Though I'm not sure if that's within scope of my PR.

**Comment by brminnick** [comment]
> I'm not sure if that's within scope of my PR 

Agreed. 

I see two paths forward: 1. Implement the current PR without the new property, or 2. Open a [New Feature Proposal](https://github.com/CommunityToolkit/Maui/issues/new?assignees=&labels=new%2Cproposal&projects=&template=open-a-new-feature-proposal.yml&title=%5BProposal%5D+) to implement this new API on all platforms. 

My vote is to remove the new property and continue with the current PR, but I'll defer to our resident MediaElement expert, @jfversluis, to help us decide.  

As a long time iPhone user (I've been exclusively using iPhones since the iPhone 3GS), I've experienced that some apps honor the hardware mute switch and some don't. Because of this experience, I personally don't expect the mute switch to mute my apps which is why I'm comfortable moving forward with the current PR as a "bug fix".

**Comment by brminnick** [comment]
FYI - I'll raise this to the team in our monthly standup this Thursday

**Comment by bijington** [comment]
Just to add a little extra docs link with regards to the Apple playback modes which I cannot share on YouTube 

https://developer.apple.com/documentation/avfaudio/avaudiosession/category

**Comment by brminnick** [comment]
Closing in favor of adding the workaround to the Official Docs: https://github.com/brminnick/CommunityToolkitDocs/pull/3
