### ISSUE TITLE
[BUG] AppThemeObject as Image Source throws Exception on net8

### ISSUE THREAD

**Issue by baaaaif** [CommunityToolkit/Maui#1360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/essentials/apptheme-resources
```
<ContentPage
    x:Class="CommunityToolkit.Maui.Sample.Pages.MyPage"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit">
    <ContentPage.Resources>
        <toolkit:AppThemeObject Light="dark.png" Dark="light.png" x:Key="MyImageSource" />
    </ContentPage.Resources>

    <VerticalStackLayout>
        <Image Source="{toolkit:AppThemeResource ImageSource}" />
    </VerticalStackLayout>
</ContentPage>
``` 
-->
System.InvalidCastException: 'Unable to cast object of type 'System.String' to type 'Microsoft.Maui.Controls.ImageSource'.'

Second aproach:
https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/essentials/apptheme-resources#extensibility

"Both AppThemeObject and AppThemeColor inherit from the abstract class AppThemeObject<T>. If you have a need for a more strongly typed resource that is not available in the .NET MAUI Community Toolkit, you can create your own inheritance."

... Resource found for key LogoSource is not of type AppThemeColor or AppThemeObject'
caused by 

```c#
if (!TryGetResource(Key, valueProvider.ParentObjects, out var resource, out var resourceDictionary)
			&& !TryGetApplicationLevelResource(Key, out resource, out resourceDictionary))
		{
			var xmlLineInfo = serviceProvider.GetService(typeof(IXmlLineInfoProvider)) is IXmlLineInfoProvider xmlLineInfoProvider ? xmlLineInfoProvider.XmlLineInfo : null;
			throw new XamlParseException($"Resource not found for key {Key}", xmlLineInfo);
		}
		else if (resource is AppThemeColor color)
		{
			return color.GetBinding();
		}
		else if (resource is AppThemeObject themeResource)
		{
			return themeResource.GetBinding();
		}
		else
		{
			var xmlLineInfo = serviceProvider.GetService(typeof(IXmlLineInfoProvider)) is IXmlLineInfoProvider xmlLineInfoProvider ? xmlLineInfoProvider.XmlLineInfo : null;
			throw new XamlParseException($"Resource found for key {Key} is not of type {nameof(AppThemeColor)} or {nameof(AppThemeObject)}", xmlLineInfo);
		}
``` 

### Expected Behavior

don't crash on net8 and/or provide extensibility as documented :)

### Steps To Reproduce

try the community toolkit sample with net8

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui/tree/main/samples

### Environment

```markdown
- .NET MAUI CommunityToolkit:5.3
- OS: Win11
- .NET MAUI: 8.0.0-preview.7.8842
```

**Comment by brminnick** [comment]
Hi @baaaaif! We don't yet support .NET 8. 

Are you able to duplicate this error on .NET 7?

**Comment by baaaaif** [comment]
AppThemeObject works for images with net7.
But I think it still makes sense to catch bugs that don't work with net8 early on, so that they can be fixed before an official release and not after it ;)

And the extensibility generally does not work as described, since the AppThemeResource Extension always expects AppThemeColor or AppThemeObject

**Comment by VladislavAntonyuk** [comment]
Feel free to reopen the issue if it will not work with .net 8 after release

**Comment by bijington** [comment]
I did mean to reply to this a while ago but somehow forgot. It should still be extensible by inheriting from AppThemeObject and providing your own GetBinding implementation.
