### ISSUE TITLE
[BUG] Loaded event not firing for views in popups

### ISSUE THREAD

**Issue by mattleibow** [CommunityToolkit/Maui#1363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When I subscribe to the Loaded event on my view, it does not fire

### Expected Behavior

The Loaded event fires

### Steps To Reproduce

1. Clone the repro here https://github.com/mono/SkiaSharp.Extended/issues/142
2. Run the app and observe no playing animations
3. Attach a handler to Loaded on the lottie views
4. Run and observe the Loaded event fires for the views in the main page but not the popup

### Link to public reproduction project repository

https://github.com/mono/SkiaSharp.Extended/issues/142

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS: Mac Catalyst and IOS but also reports on Android
- .NET MAUI:
```

**Comment by mattleibow** [comment]
Could it be related to https://github.com/CommunityToolkit/Maui/pull/1342?

**Comment by pictos** [comment]
@mattleibow does this happen on all platforms or just iOS?

**Comment by cat0363** [comment]
Some of the PRs I'm in charge of have not been merged into main, but I verified it with the latest source code I have.

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
    <td>[Windows]</td>
  </tr>
  <tr>
    <td><video controls width="250" src="https://github.com/CommunityToolkit/Maui/assets/125236133/a1d8a12a-5b07-44f3-b8aa-c615632beb6e" /></td>
    <td><video controls width="250" src="https://github.com/CommunityToolkit/Maui/assets/125236133/fb6781f0-b757-4740-a323-5b0c64c67115
" /></td>
    <td><video controls width="250" src="https://github.com/CommunityToolkit/Maui/assets/125236133/d5fff316-98c0-4e40-8875-b7ea9b5e1cf5" /></td>
  </tr>
</table>

Only iOS stops at the first frame.
Android and Windows seem to be working fine at least.

**Comment by cat0363** [comment]
The problem did not reproduce on .NET 8.
Below are the verification results. 

<table>
  <tr>
    <td>[Android]</td>
    <td>[iOS]</td>
    <td>[Windows]</td>
  </tr>
  <tr>
    <td><video controls width="250" src="https://github.com/CommunityToolkit/Maui/assets/125236133/da8f60b9-2ca5-4f42-9240-9b0d4f70c1e3" /></td>
    <td><video controls width="250" src="https://github.com/CommunityToolkit/Maui/assets/125236133/9551a2a7-acab-46fb-9654-4df9ab0ba036" /></td>
    <td><video controls width="250" src="https://github.com/CommunityToolkit/Maui/assets/125236133/270ba6bd-2ec0-4bfc-8d54-fe87615cbcb0" /></td>
  </tr>
</table>

I used the following versions:
Community Toolkit 7.0.1
SkiaSharp.Extended.UI.Maui 2.0.0-preview.86

The problem occurs when using the .NET 7 version of MAUI, but not the .NET 8 version.

**Comment by bijington** [comment]
Amazing work again @cat0363   thank you. I'll close this issue down.
