### ISSUE TITLE
[BUG] MediaElement ShouldMute doesn't mute on iOS

### ISSUE THREAD

**Issue by Varmod** [CommunityToolkit/Maui#1372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

ShouldMute has no effect on iOS

### Expected Behavior

ShouldMute should mute the video

### Steps To Reproduce

Deploy to iOS device, hear audio when video plays.

### Link to public reproduction project repository

https://github.com/Varmod/ShouldMute

### Environment

```markdown
- .NET MAUI MediaElement: 2.0
- OS: iOS 16.6
- .NET MAUI: idk where to find, but VS is on Version 17.7.1
```

**Comment by Varmod** [comment]
Nor does setting ```Volume="0"``` help

**Comment by vhugogarcia** [comment]
I was able to reproduce this issue on iOS with the `ShouldMute` and `Volume` properties.
