### ISSUE TITLE
[BUG] [ANDROID] [SAMSUNG] Badge sample throwing Permission Denial exception for com.sec.android.provider.badge.permission.WRITE

### ISSUE THREAD

**Issue by zleao** [CommunityToolkit/Maui#1376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Trying the Badge sample with a samsung device (Galaxy S23, One UI 5.1, Android 13) and I'm getting an exception:
`java.lang.SecurityException: Permission Denial: writing com.sec.android.provider.badge.BadgeProvider uri content://com.sec.badge/apps?notify=true from pid=24392, uid=10534 requires com.sec.android.provider.badge.permission.WRITE, or grantUriPermission()`

I've tried a lot of different approaches, going into the source projects where this implementation came from, tried to request this permission at runtime but not able to get it to work...

Wondering if anyone else is having this problem? I'm guessing this is a device/model/company specific issue, but I haven't found a way to fix it, yet!

### Expected Behavior

The badge count in the app icon should increase/decrease.

### Steps To Reproduce

1. Run the sample app a samsung device (Galaxy S23 runing One UI 5.1)
2. Go to Menu - Essentials - Badge
3. Click on '+' or '-'

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui

### Environment

```markdown
- .NET MAUI CommunityToolkit: Latest Main branch state (v5.3.0)
- OS: Android 13 (API 33)
- .NET MAUI: 7.xx
- Test device: Samsung Galaxy S23 (One UI 5.1, Android 13)
```

**Comment by VladislavAntonyuk** [comment]
That is because the new ui is used: OneUI.
Current sample is for demo purposes only and uses TouchWiz.
