### ISSUE TITLE
[BUG] Popup instances cannot be reused

### ISSUE THREAD

**Issue by cat0363** [CommunityToolkit/Maui#1377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I verified it with the following screen layout.

    <toolkit:Popup xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
        xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
        x:Class="MauiComm_IssuePopupReuse.PopupPage1">

        <Grid WidthRequest="200" HeightRequest="200">
            <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="Start" HorizontalOptions="Start" BackgroundColor="Blue" />
            <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="Start" HorizontalOptions="End" BackgroundColor="Blue" />
            <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="End" HorizontalOptions="Start" BackgroundColor="Blue" />
            <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="End" HorizontalOptions="End" BackgroundColor="Blue" />
        </Grid>

    </toolkit:Popup>

I hid the popup instance in a class variable.

    PopupPage1 popup = new();

Place a button on the popup caller screen and call the ShowPopupAsync method twice in succession when the button is pressed.

    async void btnShow_Clicked(object sender, EventArgs e)
    {
        await Shell.Current.ShowPopupAsync(popup);
        await Shell.Current.ShowPopupAsync(popup);
    }

I expected the second Popup to appear after closing the first Popup.

Below is the verification result for iOS.

**See [iOS] in Steps To Reproduce.**

Below is the verification result for Android.

**See [Android] in Steps To Reproduce.**

Below is the verification result for Windows.

**See [Windows] in Steps To Reproduce.**

It is not possible to reuse an instance of a Popup to display a Popup on any platform.

### Expected Behavior

1. I would expect the second Popup to appear after the first Popup closes.
2. I would expect the ShowPopupAsync method call to wait until the Popup is closed.
3. I would expect the Popup to be displayed the same as the first time it was displayed, as long as the Popup's content does not change on subsequent calls.

### Steps To Reproduce

The steps to reproduce are as follows.
For the source code downloaded from github, be sure to refer to the latest main project of CommunityToolkit.

1. Launch apps uploaded to GitHub on iOS, Android, Windows
2. Press Show Popup button

[iOS]
In step 2, the first Popup displays fine, but when the second Popup displays, the background is not dimmed and the Popup's content is not displayed as intended. The following warning is displayed.

[0:] Microsoft.Maui.Controls.Element: Warning: Microsoft.Maui.Controls.Grid is already a child of Microsoft.Maui.Controls.ContentPage. Remove Microsoft.Maui.Controls.Grid from Microsoft.Maui.Controls.ContentPage before adding to Microsoft.Maui.Controls.ContentPage.

https://github.com/CommunityToolkit/Maui/assets/125236133/ee9a54d2-6aa9-4be0-8dae-d73d44c54383

Further pressing the Show Popup button will cause an exception.

ObjCRuntime.ObjCException: 'Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: Application tried to present modally a view controller <CommunityToolkit_Maui_Core_Views_MauiPopup: 0x7fc48cb714c0> that is already being presented by <Microsoft_Maui_Controls_Platform_Compatibility_ShellFlyoutRenderer: 0x7fc48bf53e50>.
Native stack trace:
	0   CoreFoundation                      0x000000010c91f78b __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x000000011b447b73 objc_exception_throw + 48
	2   UIKitCore                           0x0000000128cf61ac -[UIViewController _presentViewController:withAnimationController:completion:] + 5648
	3   UIKitCore                           0x0000000128cf6c14 __63-[UIViewController _presentViewController:animated:completion:]_block_invoke + 98
	4   UIKitCore                           0x0000000128d1246a -[_UIViewControllerTransitionCoordinator _applyBlocks:releaseBlocks:] + 297
	5   UIKitCore                           0x0000000128d0e764 -[_UIViewControllerTransitionContext _runAlongsideCompletions] + 126
	6   UIKitCore                           0x0000000128d0e4f8 -[_UIViewControllerTransitionContext completeTransition:] + 117
	7   UIKitCore                           0x0000000129c1a458 __UIVIEW_IS_EXECUTING_ANIMATION_COMPLETION_BLOCK__ + 15
	8   UIKitCore                           0x0000000129c1a832 -[UIViewAnimationBlockDelegate _sendDeferredCompletion:] + 101
	9   libdispatch.dylib                   0x000000011bd58e40 _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x000000011bd5a0d9 _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x000000011bd69b86 _dispatch_main_queue_drain + 1330
	12  libdispatch.dylib                   0x000000011bd69646 _dispatch_main_queue_callback_4CF + 31
	13  CoreFoundation                      0x000000010c87d6cc __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	14  CoreFoundation                      0x000000010c877fbe __CFRunLoopRun + 2429
	15  CoreFoundation                      0x000000010c877264 CFRunLoopRunSpecific + 560
	16  GraphicsServices                    0x00000001217b924e GSEventRunModal + 139
	17  UIKitCore                           0x00000001295ec7bf -[UIApplication _run] + 994
	18  UIKitCore                           0x00000001295f15de UIApplicationMain + 123
	19  libxamarin-dotnet-debug.dylib       0x0000000109c6064a xamarin_UIApplicationMain + 58
	20  libmonosgen-2.0.dylib               0x000000010a46e5a9 do_icall + 345
	21  libmonosgen-2.0.dylib               0x000000010a46d0b3 do_icall_wrapper + 291
	22  libmonosgen-2.0.dylib               0x000000010a45f4af interp_exec_method + 3295
	23  libmonosgen-2.0.dylib               0x000000010a45ce03 interp_runtime_invoke + 259
	24  libmonosgen-2.0.dylib               0x000000010a2820e8 mono_runtime_invoke_checked + 136
	25  libmonosgen-2.0.dylib               0x000000010a28a0fc do_exec_main_checked + 92
	26  libmonosgen-2.0.dylib               0x000000010a3b8ce2 mono_jit_exec + 354
	27  libxamarin-dotnet-debug.dylib       0x0000000109ca4c77 xamarin_main + 1927
	28  MauiComm-IssuePopupReuse            0x0000000100d246f4 main + 68
	29  dyld                                0x0000000109875384 start_sim + 10
	30  ???                                 0x00000002015f3310 0x0 + 8612950800

[Android]
In step 2, the first Popup is displayed successfully, but an exception occurs when displaying the second Popup.

{System.ObjectDisposedException: Cannot access a disposed object.Object name: 'CommunityToolkit.Maui.Core.Views.MauiPopup'.
   at Java.Interop.JniPeerMembers.AssertSelf(IJavaPeerable self) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.cs:line 153
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 57
   at Android.App.Dialog.Show() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.App.Dialog.cs:line 2640
   at CommunityToolkit.Maui.Core.Views.MauiPopup.Show() in C:\Users\tester\Documents\GitHub7\Maui\src\CommunityToolkit.Maui.Core\Views\Popup\MauiPopup.android.cs:line 55
   at CommunityToolkit.Maui.Core.Handlers.PopupHandler.MapOnOpened(PopupHandler handler, IPopup view, Object result) in C:\Users\tester\Documents\GitHub7\Maui\src\CommunityToolkit.Maui.Core\Handlers\Popup\PopUpHandler.android.cs:line 39
   at Microsoft.Maui.CommandMapper`2.<>c__DisplayClass6_0[[CommunityToolkit.Maui.Core.IPopup, CommunityToolkit.Maui.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[CommunityToolkit.Maui.Core.Handlers.PopupHandler, CommunityToolkit.Maui.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v, Object o) in D:\a\_work\1\s\src\Core\src\CommandMapper.cs:line 92
   at Microsoft.Maui.CommandMapper.InvokeCore(String key, IElementHandler viewHandler, IElement virtualView, Object args) in D:\a\_work\1\s\src\Core\src\CommandMapper.cs:line 33
   at Microsoft.Maui.CommandMapper.Invoke(IElementHandler viewHandler, IElement virtualView, String property, Object args) in D:\a\_work\1\s\src\Core\src\CommandMapper.cs:line 51
   at Microsoft.Maui.Handlers.ElementHandler.Invoke(String command, Object args) in D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:line 95
   at CommunityToolkit.Maui.Views.PopupExtensions.CreatePopup(Page page, Popup popup) in C:\Users\tester\Documents\GitHub7\Maui\src\CommunityToolkit.Maui\Views\Popup\PopupExtensions.shared.cs:line 92
   at CommunityToolkit.Maui.Views.PopupExtensions.CreateAndShowPopupAsync[PopupPage1](Page page, PopupPage1 popup) in C:\Users\tester\Documents\GitHub7\Maui\src\CommunityToolkit.Maui\Views\Popup\PopupExtensions.shared.cs:line 115
   at CommunityToolkit.Maui.Views.PopupExtensions.ShowPopupAsync[PopupPage1](Page page, PopupPage1 popup) in C:\Users\tester\Documents\GitHub7\Maui\src\CommunityToolkit.Maui\Views\Popup\PopupExtensions.shared.cs:line 59
   at MauiComm_IssuePopupReuse.MainPage.btnShow_Clicked(Object sender, EventArgs e) in C:\Users\tester\Documents\GitHub7\Maui\src\MauiComm-IssuePopupReuse\MainPage.xaml.cs:line 17
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
   at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 36
   at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Java.Lang.IRunnable.cs:line 84
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22}

https://github.com/CommunityToolkit/Maui/assets/125236133/7acfac50-9af5-4602-a13d-1efb245a1239

[Windows]
In step 2, the first Popup is displayed, but the second Popup is not displayed. The second Popup's ShowPopupAsync method is called without waiting for the first Popup to close.

https://github.com/CommunityToolkit/Maui/assets/125236133/73ec69b4-bf8a-4f80-a3d4-eb03091ef31c

If you continue to press the Show Popup button and close the displayed Popup, the screen will become unresponsive.

https://github.com/CommunityToolkit/Maui/assets/125236133/c6b75f47-16c5-48dd-a213-dd13700f5384

### Link to public reproduction project repository

https://github.com/cat0363/MauiComm-IssuePopupReuse.git

### Environment

```markdown
- .NET MAUI CommunityToolkit: Latest version of main at the time this issue was posted
- OS: iOS 16.4, Android 11.0, Windows 11
- .NET MAUI: 7.0.92
```

### Anything else?

A workaround is to create an instance of Popup each time rather than reusing it.

**Comment by pictos** [comment]
@cat0363 this isn't a bug... It's this way by design. During the Close process, we disconnect the handler and dispose of everything related to Popup. If you think this should be implemented in another way, please open a discussion with your proposal, that way we can validate it and allow the implementation.

For context, when the popup was implemented I had the idea to be very aggressive in releasing resources, and other controls on MCT as well, but I can see value in letting users handle on when/how they want to free resources.

**Comment by cat0363** [comment]
@pictos , I'm sorry for posting it as a bug without knowing the specification.
I would like to be careful where I use it so that I don't reuse the Popup instance.

**Comment by pictos** [comment]
@cat0363 no need to be sorry, it's fine to not know all the specifications about some features... I also didn't do a good job documenting that

**Comment by cat0363** [comment]
@pictos , I'm using Popup to display my own indicator. I think there are people who use Popup to display indicators 
like me, so it might be better to keep the documentation in place. At least as much as I do they will consider reusing 
Popup instances.

**Comment by pictos** [comment]
@cat0363 Yeah, I'm aware of that, you aren't the first one that came up with this idea... And I started to think about and never changed the code because is much easier, for devs in general, to just create a new instance of the popup, than remember that they need to dispose/cleanup it by themself. And if they forget to do that it can cause a lot of memory leaks. So I choose the safe path, which's cleaning up the popup mess right after it gets closed. Does that make sense?

**Comment by cat0363** [comment]
@pictos , The cost of popup creation is much smaller than the cost of creating other pages, so the non-reuse 
concept makes sense. Popups are used as indicators, as dialogs, etc., but they are all small pages. Since it is 
only used temporarily, I think it is short considering its life cycle. I saw a cleanup implementation in the closing 
process, and I heard that it was for that reason, and I was able to understand it. Considering the risk of memory 
leaks, I also think that it is desirable to release after closing.

**Comment by MauiUIui** [comment]
> @cat0363 Yeah, I'm aware of that, you aren't the first one that came up with this idea... And I started to think about and never changed the code. It's much easier, for devs in general, to just create a new instance of the popup, than remember that they need to dispose/cleanup it by themself. And if they forget to do that it can cause a lot of memory leaks. So I choose the safe path, which's cleaning up the popup mess right after it gets closed. Does that make sense?

Hi,
so I was just searching cuz I ran into this issue, only to find out, nothing was wrong with my code and there's no bug. However, I think that at least the user should be able to decide what behaviour they'd need. I'm in a situation where it'd be useful to have my popup not being disposed (I have a control that derives from the `Popup` class and have my own constructor which gets parameters passed to it, which with the current behaviour I have to again pass. This for instance could be an expensive operation in some cases.
Anyway I think, the default behaviour can still be to dispose the popup and all of its garbage but it being optional is a minor (one added `BindableProperty`) and rather useful change.
One question though regarding this. Are all events taken into consideration when disposed? 
Like would my `MyPopup.Opened += MyPopup_Opened;` be `MyPopup.Opened -= MyPopup_Opened;`ed?? ;)

**Comment by MauiUIui** [comment]
Well here I'm speaking with myself again. I now think that disposing is a very bad approach!

**Comment by bijington** [comment]
> Well here I'm speaking with myself again. I now think that disposing is a very bad approach!

You are commenting on a closed issue so you are unlikely to get many responses. I would suggest if you feel strongly about this you should open a discussion where the community can discuss your proposal.
