### ISSUE TITLE
[BUG] MediaElement ShouldLoopPlayback="True" briefly pauses media playback between loops (tested on Windows 11)

### ISSUE THREAD

**Issue by dustuu** [CommunityToolkit/Maui#1408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

The `ShouldLoopPlayback` attribute of `toolkit:MediaElement` briefly pauses media playback between loops when set to `True` as follows:

```xaml
<toolkit:MediaElement
    ShouldAutoPlay="True"
    ShouldLoopPlayback="True"
    Source="embed://WhiteNoise.ogg" />
```

### Expected Behavior

The `MediaElement` should seamlessly return to the start of the audio file without interruption when looping is enabled.

### Steps To Reproduce

I have created a simple example repository showing this behavior: https://github.com/dustuu/HelloMaui

The relevant lines can be found here: https://github.com/dustuu/HelloMaui/blob/357a8fc19301366bbe83db7eded5bc84ae7eff3b/HelloMaui/MainPage.xaml#L21

This is a very minimal application with no custom configuration done. It was built from the default Visual Studio MAUI template with no significant changes beyond this `MediaElement` addition.

### Link to public reproduction project repository

https://github.com/dustuu/HelloMaui

### Environment

```markdown
- .NET MAUI CommunityToolkit: 2.0.0
- OS: Microsoft Windows 11 Pro Version 10.0.22621 Build 22621
- .NET MAUI: 7.0.92
```

**Comment by AustinSnooz** [comment]
I've encountered this as well, and it's putting me back on creating my app.  Hopefully we can get this fixed.  I'm looking into a native platform way of doing it for now, maybe I'll get some insight to help in my journey.

**Comment by AustinSnooz** [comment]
This seems to be an issue even if you try to use native code, especially on Android.  I was actually doing some testing with white noise as well and ended up having to make my own custom players using native controls.  With iOS I was able to do it using a Queue player, on Android it was a lot harder.  I had to create two players that would wait and ready themselves while the other was playing, then set themselves as the next player.  It's essentially a dictionary with two players that juggle themselves.  

Not sure about the Windows option but it may be similar to Android.  If I get the time I'll try to look at the code for the community toolkit and see if I can add in what I made.  Until then hopefully this comments helps someone, or someone else may fix it soon.

**Comment by bijington** [comment]
I am not entirely sure what the underlying implementation inside ExoPlayer uses however the Android implementation might suffer from the same issue we are seeing over here: https://github.com/jfversluis/Plugin.Maui.Audio/issues/44. The proposed solution is to create 2 `MediaPlayer`s and chain them together using the `SetNextMediaPlayer` method.

**Comment by ne0rrmatrix** [comment]
Tested android and windows. NO issues. Gapless playback is working. @vhugogarcia

**Comment by ne0rrmatrix** [comment]
Sample:

https://github.com/CommunityToolkit/Maui/assets/4167863/67658478-7d8e-4fa4-a4ca-d9c567562e1c

**Comment by vhugogarcia** [comment]
The issue appears to be fixed on the latest version. I'm closing this ticket. We can re-open it if the issue persists. Thanks @ne0rrmatrix for sharing a video.
