### ISSUE TITLE
[BUG] speechToText.ListenAsync Function Not Awaiting Completion in iOS

### ISSUE THREAD

**Issue by alaskanrogue** [CommunityToolkit/Maui#1415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

The CommunityToolkit.Maui speechToText.ListenAsync function not awaiting completion in an iOS application instance, but does in an Android app instance. 

### Expected Behavior

The CommunityToolkit.Maui speechToText.ListenAsync function awaits completion in an iOS application instance,

### Steps To Reproduce

Open and run solution in repository. Steps outlined there.

### Link to public reproduction project repository

https://github.com/alaskanrogue/Listen

### Environment

```markdown
- .NET MAUI CommunityToolkit: v5.3.0
- .NET MAUI CommunityToolkit.Maui.Core: v5.3.0
- OS: iOS v16.6.1
```

**Comment by VladislavAntonyuk** [comment]
Use Start/Stop methods
