### ISSUE TITLE
[BUG] IconTintColorBehavior does not "tint" the image (ie. Multiply) but rather replaces every non-transparent pixel with the "tint" color completely

### ISSUE THREAD

**Issue by jonmdev** [CommunityToolkit/Maui#1418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Here is an example of a simple, mostly white rendered rounded cube with some shadowing around the edge (PNG):
<img width="196" alt="bgtint - white unity" src="https://github.com/CommunityToolkit/Maui/assets/43948450/98fb4118-8318-4d80-929b-ec2009750996">

If I apply a red tint to this in UI Toolkit of Unity (similar system to Maui), this is the appearance:

<img width="204" alt="bgtint - red unity" src="https://github.com/CommunityToolkit/Maui/assets/43948450/8434aa0c-f935-4f77-838f-57672429a456">

As can be seen, the shadowing still appears around the edge. This is equivalent to adding a red Color Overlay in Photoshop set to Multiply:

<img width="454" alt="bgtint photoshop multiply" src="https://github.com/CommunityToolkit/Maui/assets/43948450/51e684ee-42fe-4c40-b141-c17883c027af">

However, in Maui, we are getting this instead, where instead of a red tint being applied, all non-transparent pixels are obliterated and set to pure red color:

<img width="225" alt="bgtint - red maui" src="https://github.com/CommunityToolkit/Maui/assets/43948450/36b9222a-71d2-49d2-96af-4ba370fc380b">

### Expected Behavior

Expected behavior is that a "Multiply" type math should be applied with a tint function of this nature. A multiply tint operation, as demonstrated in Photoshop or Unity is described as: 

"Multiply Mode, according to Photoshop help: Looks at the color information in each channel and multiplies the base color by the blend color. The result color is always a darker color. Multiplying any color with black produces black. Multiplying any color with white leaves the color unchanged."

https://www.sitepoint.com/multiply-mode-in-photoshop/

I then think the correct way for this to be applied is for the R, G, and B channels of the image to be taken individually as 0 to 1 range floats, then multiplied each by the corresponding R, G, and B channels of the tint color also as 0 to 1. This way if the tint color is white, all channels are multiplied by 1. If the tint color is black, all channels are multiplied by 0.

This would apply the expected tint behavior.

If this is not something you want to "fix", can you please clarify where in the source this "tint" math is applied so I can at least change or extend the class on my end to apply the correct "tint" behavior (to provide a more appropriate Multiply)?

Thanks for any help or guidance.

### Steps To Reproduce

1. Add any image with any shading and lighter/darker areas to Resources:
2. Run the following code on any ContentPage:

Image img = new();
img .WidthRequest = botImg.HeightRequest = 300;
IconTintColorBehavior tintBehavior = new();
img .Behaviors.Add(tintBehavior);
tintBehavior.TintColor = Colors.Red;
img .Source = ImageSource.FromFile("dotnet_bot.png"); //or any image that is not purely colored and has shading/transparency

3. Observe that all non-transparent pixels have been completely turned red, rather than been "tinted" (Multiplied).
            

### Link to public reproduction project repository

n/a

### Environment

```markdown
- .NET MAUI CommunityToolkit:5.3.0
- OS: Windows 10
- .NET 8.0
```

**Comment by bijington** [comment]
You should be able to view the IconTintBehavior source here https://github.com/CommunityToolkit/Maui/tree/main/src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor

You may notice that at least on macOS and iOS we don't apply any maths, we just delegate down to the platform specific layer that applies a TintColor. I didn't check the other platforms but if it is limited on apple platforms I suspect that is why there isn't this multiply option.

I do suspect though, if you can get it working on all platforms then it would be a welcome feature to the toolkit.

As a possible quick test/workaround, have you tried providing a semi transparent color to the behavior? I can't guarantee it will work but I'm intrigued to see if that might help

**Comment by jonmdev** [comment]
After spending more time with the system and learning Behaviors more and how everything is supposed to work, I am satisfied with my solution and will close issue. Since the built in Tint function works from Native functions otherwise, likely no better solution.

**Comment by bijington** [comment]
Thanks for confirming. Apologies I had a note to get back to you but somehow forgot to do so.

**Comment by jonmdev** [comment]
I have spent some more time in the system and Android at least does support "Multiply" mode tinting:

**ANDROID:**
Needs multiply mode specified here:
https://developer.android.com/reference/android/graphics/PorterDuff.Mode#MULTIPLY

This is specified in line 58 here as `PorterDuff.Mode.SrcIn`, which should be `PorterDuff.Mode.Multiply`:
https://github.com/CommunityToolkit/Maui/blob/5feb465a84edcbe395c01f3a8d4d013f7fa59875/src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.android.cs

**IOS:**
From what I see they don't support any modes for tinting which is crazy. I see discussions on this here:
https://stackoverflow.com/questions/31803157/how-can-i-color-a-uiimage-in-swift
https://developer.apple.com/documentation/uikit/uiimageview/1621059-tintcolor

Maybe no solution except the sort of thing I wrote then to remake a bitmap every time you want to change it. Unless I am missing something.

This is all that is being done here, setting `TintColor`:
https://github.com/CommunityToolkit/Maui/blob/5feb465a84edcbe395c01f3a8d4d013f7fa59875/src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.macios.cs

**WINDOWS:**
From what I see I don't think they support this either. It looks like all we have is this:

https://learn.microsoft.com/en-us/uwp/api/windows.ui.composition.compositionmaskbrush?view=winrt-22621

Which is a brush that can draw (fill) based on opacity values and I believe that is what this solution is using here:

https://github.com/CommunityToolkit/Maui/blob/5feb465a84edcbe395c01f3a8d4d013f7fa59875/src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.windows.cs

So looks like no unified native only solution is possible unless I am missing something still.
