### ISSUE TITLE
[Proposal] Remove `SkiaSharp.Views` Dependency

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#1424]
### Feature name

Remove `SkiaSharp.Views` Dependency

### Link to discussion

(Discord) https://discord.com/channels/1136756209475661914/1136757631550238781/1154823859766308906

### Progress tracker

- [ ] Android Implementation
- [ ] iOS Implementation
- [ ] MacCatalyst Implementation
- [ ] Windows Implementation
- [ ] Tizen Implementation
- [ ] Unit Tests
- [ ] Samples
- [ ] Documentation

### Summary

A direct reference to `SkiaSharp.Views v2.88.6` was added to `CommunityToolkit.Maui.Core` for `net7.0-tizen` after a [security vulnerability was reported on `SkiaSharp`](https://github.com/advisories/GHSA-j7hp-h8jx-5ppr); the vulnerability  is patched in `SkiaSharp v2.88.6`:

https://github.com/CommunityToolkit/Maui/blob/bf9d66dba7dbce149368fc890a988120402ad98e/src/CommunityToolkit.Maui.Core/CommunityToolkit.Maui.Core.csproj#L53-L55

The `tizen-net7.0` library has a transitive dependency to SkiaSharp  via `net7.0-tizen` -> `Tizen.UIExtensions.NUI` -> `Microsoft.Maui.Graphics.Skia` -> `SkiaSharp`.

We should remove this direct package reference once `Microsoft.Maui.Graphics.Skia` has been updated to use `SkiaSharp v2.88.6` and then `Tizen.UIExtensions.NUI` has subsequently been updated to use the latest version of `Microsoft.Maui.Graphics.Skia`.

We are blocked until `Tizen.UIExtensions.NUI` is updated.

### Motivation

The .NET MAUI Community Toolkit strives to avoid adding direct dependencies to external libraries. I created this Issue to ensure that our temporary dependency to `SkiaSharp` to avoid the security vulnerability does not become a permanent dependency in our library.

### Detailed Design

To remove the direct dependency, we must remove following lines of code from `CommunityToolkit.Maui.Core`:

https://github.com/CommunityToolkit/Maui/blob/bf9d66dba7dbce149368fc890a988120402ad98e/src/CommunityToolkit.Maui.Core/CommunityToolkit.Maui.Core.csproj#L53-L55

### Usage Syntax

```markdown
(None)
```

### Drawbacks

(None)

### Alternatives

(None)

### Unresolved Questions

(None)

**Comment by vhugogarcia** [comment]
The .NET MAUI team is bumping up the version now on the .NET MAUI repository: https://github.com/dotnet/maui/commit/c37907a3b74edb4393ad340d63b6ebb0efd5ce97

Hopefully, it will be approved and merged soon. 
🙂🙂

**Comment by brminnick** [comment]
**Update**

The [`Microsoft.Maui.Graphics.Skia v7.0.100`  NuGet Package](https://www.nuget.org/packages/Microsoft.Maui.Graphics.Skia/7.0.100) has been updated to SkiaSharp v2.88.6: https://github.com/dotnet/maui/commit/199adf732f6433e43d6aad86bed8dc2c4adb002b

We are still blocked until `Tizen.UIExtensions.NUI` is updated. We will monitor the progress on their PR here: https://github.com/dotnet/maui/pull/18442

**Comment by jfversluis** [comment]
Oooh well actually, I think we still got work to do here on our side now? @JoonghyunCho?

**Comment by brminnick** [comment]
Awesome!! 

Yup - once the `net7.0-tizen` workload (or the `net8.0-tizen` workload) is updated to use `Tizen.UIExtensions.NUI v9.2.0`, we can remove our [dependency to `SkipSharp.Views`](https://github.com/CommunityToolkit/Maui/blob/bf9d66dba7dbce149368fc890a988120402ad98e/src/CommunityToolkit.Maui.Core/CommunityToolkit.Maui.Core.csproj#L53-L55). 

We'll keep this Proposal open until the PR to remove the `SkiaSharp.Views` dependency is closed:
https://github.com/CommunityToolkit/Maui/blob/bf9d66dba7dbce149368fc890a988120402ad98e/src/CommunityToolkit.Maui.Core/CommunityToolkit.Maui.Core.csproj#L53-L55
