### ISSUE TITLE
[BUG] MediaElement goes into a play/pause frenzy

### ISSUE THREAD

**Issue by Varmod** [CommunityToolkit/Maui#1425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When switching the video source the moment the video state changes the media element has a chance to go crazy. (based on observation)

I have a video dictionary app where the user can play short videos eg. 1-3 seconds long. I've noticed that if the user clicks next video the moment the current one is ending the media element breaks.

### Expected Behavior

The media element should handle the switch.

### Steps To Reproduce

1. Deploy to iOS, (but I think this is also present on android)
2. start pressing the play/pause button at the same time as the next video button 
(this is the fastest way I found to reproduce the bug)
3. after a few clicks the video will start stuttering, playing and pausing at will

### Link to public reproduction project repository

https://github.com/Varmod/Issues

### Environment

```markdown
- .NET MAUI CommunityToolkit: MediaElement 2.0
- OS: iOS
- .NET MAUI: 7
```

### Anything else?

I've also noticed the during this faze the media ended event fires a lot. Which is quite strange as the video usually doesn't end at all.

![IMG_2828](https://github.com/CommunityToolkit/Maui/assets/52281562/10de0b2c-093c-4c6d-810a-cf892d956dd9)

**Comment by Varmod** [comment]
Any idea what could causing the issue? Or what I could do for a temp fix?

**Comment by vhugogarcia** [comment]
Updating to the latest version of .NET MAUI Community Toolkit Media Element 4.0.1 appears to fix this issue. I tried to reproduce the issue using the latest version with the sample repository without luck.

I'm closing this issue, if the issue re-appears again we can always re-open this ticket. Thanks

cc: @brminnick
