### ISSUE TITLE
[BUG] RelayCommand with parameter for menuItem / contextAction on windows

### ISSUE THREAD

**Issue by SamuelJames101** [CommunityToolkit/Maui#1435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I have created a ListView.
Created context actions.
If a menu item in the context action points to a [RelayCommand] which takes a parameter then the list view items don't show.

Take away the parameter and it works.
![Screenshot 2023-10-02 at 10 26 27](https://github.com/CommunityToolkit/Maui/assets/44027336/d3296b8c-238d-4de3-a51d-c0a3ffa5d2c9)

### Expected Behavior

A ListView item pointer to a RelayCommand should show with or without a paramater.

### Steps To Reproduce

1. Create a ListView
2. Populate the list
3. Add ContextActions
4. For one of the menu items point to a RelayCommand that requires a parameter.

### Link to public reproduction project repository

https://github.com/SamuelJames101/comtoolkitIssueMaui

### Environment

```markdown
- .NET MAUI CommunityToolkit: mvvm 8.2.1
- OS: Windows 11
- .NET MAUI: 8 RC-1
```

**Comment by VladislavAntonyuk** [comment]
Please create an issue in https://githib.com/CommunityToolkit/MVVM

**Comment by SamuelJames101** [comment]
https://github.com/CommunityToolkit/dotnet/issues/766

**Comment by SamuelJames101** [comment]
@VladislavAntonyuk They have closed the issue over on Dotnet as well so where am I supposed to raise this?

**Comment by bijington** [comment]
I don't know if this helps at all but shouldn't your `MainViewModel` inherit from `ObservableObject` (I think that's the base class provided by the MVVM toolkit)
