### ISSUE TITLE
[BUG] SpeechToText.ListenAsync function ignores CultureInfo on Android devices

### ISSUE THREAD

**Issue by AncientLust** [CommunityToolkit/Maui#1436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Possible wrong behavior of SpeechToText.ListenAsync on Android devices.

ListenAsync function ignores passed CultureInfo which sets up recognition language. Instead, ListenAsync uses for speech recognition current Android device language. 

Even if the passed language is installed as a second one on an Andriod device it won't be used for the recognition until the user opens device settings and selects the required language as the current device language. In that case, the recognition works well. Tested with US and PL languages.

### Expected Behavior

CultureInfo parameter of ListenAsync function is expected to affect the language of speech recognition. So far the only way to change the recognition language is to set the Android device's language to the desired one.

### Steps To Reproduce

1. Open repro project .
2. Plug an Android device and run the application.
3. Enable an internet connection on the Device.
4. Let's assume the device language is set to US. On the main page select any available language, which differs from the device's system language.
5. Press the "Listen" button. And say a test phrase. You will be prompted with text in English, no matter which language you have chosen. 

### Link to public reproduction project repository

https://github.com/AncientLust/Culture-issue-repro-project

### Environment

```markdown
Build environment:
- .NET MAUI CommunityToolkit: 6.0.0
- OS: Windows 11 Pro Build 22621.2283
- Target framework: net7.0-android

Android device:
- Model: Huawei P20 Pro
- API: 29
- OS: EMUI 12.0.0 Build 12.0.0.225(C432E5R1P1)
```

### Anything else?

The same issue was mentioned by Gerhard Mauerberger's comment:
https://devblogs.microsoft.com/dotnet/speech-recognition-in-dotnet-maui-with-community-toolkit/#comment-18164

"""
I made tests with en-GB, de-DE, pl-PL, fr-FR and found out, that the system language is considered. If you have more than one language selected in your Android phone, then the second language works, too. But not the third.
When I moved Polish from 3rd position in the Android settings to the top of the selected languages, the results were very good, too!
"""

In my case, the second language on Andriod's device didn't work either until I set it as the main language.

I am a newbie in .NET so I could forget something. Please let me know If I can provide you with any additional details to track the issue. I really appreciate your work guys!

**Comment by VladislavAntonyuk** [comment]
as I replied:
As for the culture parameter. the output result (text) is returned in the language you set. If you set a culture that is not supported by your device, it most likely uses the default one. You can set one language, but speak another, but the result may differ from what you expect.

**Comment by AncientLust** [comment]
Hi Vladislav, thanks, I saw your reply. I still don't think it works as expected. 

Please, look into this [video](https://www.youtube.com/watch?v=CI-Fx8_0oYo&t=951s). This approach has the same issue I described above, but I was able to fix this by adjusting one line of code in SpeechToTextImplementation.cs:

From `intent.PutExtra(RecognizerIntent.ExtraLanguage, javaLocale);`
To: `intent.PutExtra(RecognizerIntent.ExtraLanguage, javaLocale.ToString());`

After this, I'm able to recognize Polish even if the default device language is set to US.

I'm not sure, but If your solution for Android uses the same approach under the hood, it could be a solution.

**Comment by VladislavAntonyuk** [comment]
@AncientLust Thank you for your investigation. I will check the solution

**Comment by serkansmg** [comment]
also i need that solution for tr-TR language

**Comment by wellhat** [comment]
I can confirm the solution @AncientLust mentioned works, the java locale does not work properly and the ExtraLanguage intent needs to be passed in as a string. It's a quick fix so I would think this can be released soon.

@serkansmg in the meantime you can copy SpeechToTextImplementation.shared.cs and SpeechToTextImplementation.android.cs (changing line https://github.com/CommunityToolkit/Maui/blob/main/src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SpeechToTextImplementation.android.cs#L53 `intent.PutExtra(RecognizerIntent.ExtraLanguage, javaLocale.ToString());` ) into your Android Platform folder, and change your service setup code in MauiProgram.cs to: 

```
#if ANDROID
        builder.Services.AddSingleton<ISpeechToText>(new MyApp.Platforms.Android.SpeechToTextImplementation());
#else
        builder.Services.AddSingleton<ISpeechToText>(SpeechToText.Default);
#endif
```

**Comment by serkansmg** [comment]
@wellhat i already did a test similar to it and it worked. 
now i will update my code as you suggested.. 
i'll try today.. thanks :) 
good job @AncientLust for the solution, thank you also.. 
@VladislavAntonyuk we will be  waiting for the final release.. :)

**Comment by VladislavAntonyuk** [comment]
I will create a PR today

**Comment by serkanp** [comment]
when will the  nuget packages get this update?

**Comment by brminnick** [comment]
We'll release v6.1.0 this upcoming week
