### ISSUE TITLE
[BUG] Expander in scrollview does not expand on IOS

### ISSUE THREAD

**Issue by AndreasStasny** [CommunityToolkit/Maui#1439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

If an expander is moved outside the visible screen and has to be scrolled into the visible screen, does not react on the click to expand.

### Expected Behavior

The scrolled expander should react on the click and expand the content.

### Steps To Reproduce

1. Open and run solution from the reproduction repository on an ios device.
2. Expand first expander.
3. Expand second expander.
4. Scroll to the third expander.
5. Try to expand third expander.

### Link to public reproduction project repository

https://github.com/AndreasStasny/Expander-in-scrollview-issue

### Environment

```markdown
- .NET MAUI CommunityToolkit: 6.0.0
- .NET MAUI: 7.0.92
```

**Comment by cat0363** [comment]
Maybe this issue is related.
https://github.com/dotnet/maui/issues/14257

**Comment by AndreasStasny** [comment]
Yes it is the same problem. Using the workaround from https://github.com/dotnet/maui/issues/14257 will fix this issue.
Thanks

**Comment by cat0363** [comment]
Is the behavior you expect below?

https://github.com/CommunityToolkit/Maui/assets/125236133/22174982-de88-4cba-b5ea-bfcde6ad6ee8

If you reopen the issue, I can implement a workaround on the Community Toolkit side.
I don't know if the PR will pass review, but guess what?

**Comment by AndreasStasny** [comment]
Yes, this is the correct behavior.
I think there is already a fix in .net 8 preview.
