### ISSUE TITLE
[BUG] IconTintColorBehavior not working with binded hex string. 

### ISSUE THREAD

**Issue by ISSPRO-Eng** [CommunityToolkit/Maui#1441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I am trying to bind a Hex color to IconTintColorBehavior TintColor in my XAML. 

### Expected Behavior

I am expecting my image to be tinted to the current hex color string as I move my color sliders. The hex value is changing as I have that posted to show the user as well, but the image is not tinting. The visual hex string uses the same bindings as the images. 

### Steps To Reproduce

Bind color string from View Model to XAML.

### Link to public reproduction project repository

XAML

<Grid>
                    <Image
                    x:Name="NeedleSVG"
                    WidthRequest="200"
                    HeightRequest="200"
                    Source="needle.png">
                    <Image.Behaviors>
                            <mct:IconTintColorBehavior TintColor="{Binding NeedleColorInHex}" />
                    </Image.Behaviors>
                    </Image>

                    <Image
                    WidthRequest="200"
                    HeightRequest="200"
                    Source="backlight.png">
                    <Image.Behaviors>
                            <mct:IconTintColorBehavior TintColor="{Binding BackColorInHex}" />
                    </Image.Behaviors>
                    </Image>

                    <Image
                    WidthRequest="200"
                    HeightRequest="200"
                    Source="housing.png">
                    <Image.Behaviors>
                            <mct:IconTintColorBehavior TintColor="{Binding BackColorInHex}" />
                    </Image.Behaviors>
                    </Image>
                    <Button ClassId="BackLight" 
                            BackgroundColor="Transparent" 
                            WidthRequest="250" 
                            HorizontalOptions="Center" 
                            Clicked="OnPreviewTapped"/>
                    <Button ClassId="Needle" 
                            BackgroundColor="Transparent" 
                            HeightRequest="80" 
                            WidthRequest="80" 
                            VerticalOptions="Center" 
                            HorizontalOptions="Center" 
                            Margin="0,20,0,0" 
                            Clicked="OnPreviewTapped"/>
                </Grid>

View Model 
```
private string _hex;
        public int R = 0;
        public int G = 0;
        public int B = 0;
        public int W = 0;
        public int max = 255;

        public string Hex
        {
            get
            {
                if (W != 0 & R == 0 & G == 0 & B == 0)
                    return string.Format("#{0:X2}{1:X2}{2:X2}", max, max, max);
                else if (W == 0)
                    return string.Format("#{0:X2}{1:X2}{2:X2}", R, G, B);
                else
                    return string.Format("#{0:X2}{1:X2}{2:X2}", (R + W) / 2, (G + W) / 2, (B + W) / 2);

            }
            set
            {
                _hex = value;
            }
        }
public string SelectedColorInHex
{
            get
            {
                NotifyGaugeOfChangeAsync();
                Task.Delay(50).Wait(); // wait 50ms so that we dont flood the gauge
                if (FocusColorOn == BACKLIGHT)
                    return BackColorInHex;
                else
                    return NeedleColorInHex;
            }
            set
            {
                if (FocusColorOn == BACKLIGHT)
                    _colorBack.Hex = value;
                else
                    _colorNeedle.Hex = value;
            }
}
```

### Environment

```markdown
- .NET MAUI CommunityToolkit: 2.0.0
- OS: Mac OS 13.2.1 (22D68)
- .NET MAUI: 7.0.92
```

**Comment by brminnick** [comment]
Please add a descriptive Title and provide a Sample Reproduction

**Comment by ISSPRO-Eng** [comment]
@brminnick I added the code that is causing this failure.

**Comment by brminnick** [comment]
Thank you. Please provide a link to a reproduction sample app.

Here is additional information from the above Contributing guides required for each Issue:

> - [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug
> > We always request a reproduction sample, and that's not to make your life hard or anything like that... The reason of having a reproduction is to save us time to indentify and fix the bug. Create a new project; download the MCT NuGet; write UI; ViewModel; create a service; run it. As you can see it's a lot of timing consuming for us that we could spend fixing the actual issue. So PLEASE create a small reproduction project, upload it on GitHub or GitLab and paste the link in the issue.
> > > We don't accept .zip files as reproduction samples, for security reasons. So if you send us a .zip file we will kindly ask you to upload it to GitHub or GitLab and share the link

**Comment by pictos** [comment]
From the snippet provided you're doing the Binding wrong, please see how we do it [here](https://github.com/communityToolkit/Maui/blob/main/samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/IconTintColorBehaviorPage.xaml#L92).

**Comment by ISSPRO-Eng** [comment]
@brminnick Can I add you to the private repo for the time being? Or else I will re create a mini app tomorrow to address this issue

**Comment by ISSPRO-Eng** [comment]
@pictos The binding worked with the Xamarin Community Toolkit... why the change?

**Comment by brminnick** [comment]
> Can I add you to the private repo for the time being? Or else I will re create a mini app tomorrow to address this issue

No. Please add a link to a public repository containing the reproduction sample as outlined in our Contributing guidelines. There are a dozen maintainers for `CommunityToolkit.Maui` and the maintainer working on this potential bug will instead require access.

> The binding worked with the Xamarin Community Toolkit... why the change

This is a different library for a different framework. 

> From the snippet provided you're doing the Binding wrong, please see how we do it [here](https://github.com/communityToolkit/Maui/blob/main/samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/IconTintColorBehaviorPage.xaml#L92).
@pictos Can we close this Issue?

**Comment by pictos** [comment]
@ISSPRO-Eng The change is that before we used effects and now we use Platform Behaviors, that has another implementation details. I provided the sample how to do the Binding. I'll close this issue now, but if can't do the Binding work properly open a new issue with a small repro

**Comment by ISSPRO-Eng** [comment]
Okay thanks for the help guys! Will create a small repo today:)
