### ISSUE TITLE
[BUG] Error MSB4018: Popup cannot display Chinese labels

### ISSUE THREAD

**Issue by GXSA-Qi** [CommunityToolkit/Maui#1451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Popup cannot display Chinese labels.When the labels are Chinese,an MSB4018 error occurs.

### Expected Behavior

Popup displays Chinese labels normally.

### Steps To Reproduce

①Follow the https://learn.microsoft.com/zh-cn/dotnet/communitytoolkit/maui/views/popup link to create a popup as normal.
②Follow step① to display the popup of an English label and build it.The project builds normaly and popup can display normally.
③Change the label to Chinese and build it.An MSB4018 error occurs.

![屏幕截图 2023-10-11 171838](https://github.com/CommunityToolkit/Maui/assets/63104968/6042c740-bd28-4dd0-ab8d-0619a1af4ca5)
![屏幕截图 2023-10-11 172036](https://github.com/CommunityToolkit/Maui/assets/63104968/475d000b-5808-4f28-9426-a134a2d3cc88)

### Link to public reproduction project repository

https://github.com/GXSA-Qi/BUGS.git

### Environment

```markdown
- .NET MAUI CommunityToolkit:6.0.0
- OS:Windows 11 Build 22621.2428
- .NET MAUI:7
```

### Anything else?

This issue is a very interesting one, and I am curious as to what causes it.

**Comment by cat0363** [comment]
@GXSA-Qi , There is no Encoding description in the first line of XAMLPopUP.xaml. What will happen if you add it?

    <?xml version="1.0" encoding="utf-8" ?>   
    <toolkit:Popup xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
        xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
        x:Class="MauiApp1.XAMLPopUP">

        <VerticalStackLayout Style="{StaticResource PopupLayout}" BackgroundColor="{AppThemeBinding Light={StaticResource Gray100}, Dark={StaticResource Gray950}}">
            <Label Text="d" Style="{StaticResource Title}"/>
        </VerticalStackLayout>
    </toolkit:Popup>

I referred to the revised contents of [this PR](https://github.com/dotnet/maui/pull/4851).
I don't have a debugging environment at home, so I can't confirm whether the above can solve the problem.

**Comment by cat0363** [comment]
In my environment, the build passed normally without adding the Encoding description.
I set the following characters to the label text. 
"啊这"

<img width="681" src="https://github.com/CommunityToolkit/Maui/assets/125236133/32d4c858-6756-433e-94b0-b2931b18e6da">

https://github.com/CommunityToolkit/Maui/assets/125236133/e1a67f50-c300-47cf-bc78-8857c47f3be9

**Comment by GXSA-Qi** [comment]
> 在我的环境中，构建正常通过，没有添加编码描述。我将以下字符设置为标签文本。 “啊这”
> 
> <img alt="" width="681" src="https://user-images.githubusercontent.com/125236133/274445856-32d4c858-6756-433e-94b0-b2931b18e6da.png">
>  安卓模拟器-.pixel_2_-_api_30_5554.2023-10-12.09-17-15.mp4

I See you are using the preview version of VS2022, which seems to fix the issue in the preview(or in future)🤔?

**Comment by GXSA-Qi** [comment]
> 在我的环境中，构建正常通过，没有添加编码描述。我将以下字符设置为标签文本。 “啊这”
> 
> <img alt="" width="681" src="https://user-images.githubusercontent.com/125236133/274445856-32d4c858-6756-433e-94b0-b2931b18e6da.png">
>  安卓模拟器-.pixel_2_-_api_30_5554.2023-10-12.09-17-15.mp4

I see you are using the preview version of VS2022, which seems to fix the issue🤯.

**Comment by cat0363** [comment]
@GXSA-Qi , Is it okay to say that this is not a problem with Popup, but a problem with Visual Studio?

**Comment by GXSA-Qi** [comment]
> @GXSA-Qi , Is it okay to say that this is not a problem with Popup, but a problem with Visual Studio?

I download the preview version of VS2022 and use .NET 7 to build, still have error MSB4018.
![屏幕截图 2023-10-12 120420](https://github.com/CommunityToolkit/Maui/assets/63104968/d15e203a-5d68-424d-837e-03b0f2972831)
BUT! After upgraded the app from .NET 7 to .NET 8, it build passed normally!
It's really amazing╰(*°▽°*)╯.
