### ISSUE TITLE
[BUG] Popup cannot be display with right angles or rounded angles

### ISSUE THREAD

**Issue by espritm** [CommunityToolkit/Maui#1452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When displaying a CommunityToolkit.Maui.Views.Popup, I would like to be able to define the angles radius.

At this moment, it is follow the native default value, that is right angles on Android and rounded angles on iOS for instance.

On Android :
<img width="501" alt="image" src="https://github.com/CommunityToolkit/Maui/assets/10628946/b6930895-29ce-4c2c-a7e4-2eb6e1ccfe3f">

On iOS : 
![image](https://github.com/CommunityToolkit/Maui/assets/10628946/fd023e98-1f35-4e15-adf0-01bcb70ec2e4)

### Expected Behavior

I would like to have a parameter setting the corner radius.

Or the best would be to draw ourself the view, maybe with a handler and cgrect for iOS for instance ? Any advice or help would be appreciated on this point if it is possible.

I have had a look at the code, and maybe here we could do something for iOS to draw the frame using a CGRect ?
https://github.com/CommunityToolkit/Maui/blob/3b44cc0350d57b196a967d2faa917d7cf23e27fa/src/CommunityToolkit.Maui.Core/Views/Popup/MauiPopup.macios.cs#L142C18-L142C18

OR if it is doing using a handler I would be happy to learn

### Steps To Reproduce

1. Get the sample project  https://github.com/espritm/Maui.Toolkit.Popup
2. Build and run, click the button, the popup is displayed
3. In Controls folder, Popup class, I would like to have a parameter or some native code pour modifiy the angles.

### Link to public reproduction project repository

https://github.com/espritm/Maui.Toolkit.Popup

### Environment

```markdown
- .NET MAUI CommunityToolkit:6.0.0
- OS:iOS, Android
- .NET MAUI:7.0
```

**Comment by maonaoda** [comment]
In order to show rounded corners, I had to do this separately on Android and iOS:
First, use the Border with StrokeShape such as "RoundRectangle 10" in the content of PopUp 
※although the Border`s corner has no effect in iOS ):
Then in iOS, set the background color of Popup to be consistent with Border.
In Android Set the background color of Popup to transparent.

**Comment by cat0363** [comment]
@espritm , It's not perfect, but is this what you're expecting?

To make the corners of an iOS Popup square, you need to modify the code as shown below.
By doing the following, the appearance will be the same as Android.

[src\CommunityToolkit.Maui.Core\Views\Popup\MauiPopup.macios.cs]

    public override void ViewDidLayoutSubviews()
    {
        base.ViewDidLayoutSubviews();

        _ = View ?? throw new InvalidOperationException($"{nameof(View)} cannot be null.");

        View.Superview.Layer.CornerRadius = 0.0f;

        SetElementSize(new Size(View.Bounds.Width, View.Bounds.Height));
    }

By using Border for the Popup content, you can adjust the roundness of the corners.
However, the above measures are essential for this purpose.

You can make the corners rounded by laying it out as shown below.

    <toolkit:Popup xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
        xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
        x:Class="MauiComm_VerityPopupSize.PopupPage6" Size="200,200" Color="Transparent">
        <Border StrokeShape="RoundRectangle 10,10,10,10" BackgroundColor="Red">
            <Grid>
                <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="Start" HorizontalOptions="Start" BackgroundColor="Blue" />
                <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="Start" HorizontalOptions="End" BackgroundColor="Blue" />
                <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="End" HorizontalOptions="Start" BackgroundColor="Blue" />
                <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="End" HorizontalOptions="End" BackgroundColor="Blue" />
            </Grid>
        </Border>
    </toolkit:Popup>

<img width="250" src="https://github.com/CommunityToolkit/Maui/assets/125236133/c7dd0436-ac8b-407f-9bf6-183bc3d8cce1" />

You can make the corners right angles by laying it out as shown below.

    <toolkit:Popup xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
        xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
        x:Class="MauiComm_VerityPopupSize.PopupPage6" Size="200,200" Color="Transparent">
        <Border StrokeShape="RoundRectangle 0,0,0,0" BackgroundColor="Red">
            <Grid>
                <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="Start" HorizontalOptions="Start" BackgroundColor="Blue" />
                <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="Start" HorizontalOptions="End" BackgroundColor="Blue" />
                <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="End" HorizontalOptions="Start" BackgroundColor="Blue" />
                <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="End" HorizontalOptions="End" BackgroundColor="Blue" />
            </Grid>
        </Border>
    </toolkit:Popup>

<img width="250" src="https://github.com/CommunityToolkit/Maui/assets/125236133/4832fb3e-18d7-4f06-9ab2-e1586401a3b1" />

The key is to make the Popup's color transparent, use Border for the Popup's content, and control the roundness of the corners with StrokeShape.

If the above is acceptable, I can create a PR, but since it will have a significant impact on iOS Popup, Community Toolkit will need to make a decision.

**Comment by maonaoda** [comment]
@cat0363 
What if the Size is not fixed, but changes based on the content? eg: height

**Comment by cat0363** [comment]
@maonaoda , I tested it with the layout below.

    <toolkit:Popup xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
        xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
        x:Class="MauiComm_VerityPopupSize.PopupPage6" Color="Transparent">
        <Border StrokeShape="RoundRectangle 10,10,10,10" BackgroundColor="Red" StrokeThickness="0">
            <StackLayout>
                <Label Text="Hello, World!" FontSize="32"/>
                <Button Text="Click me" HorizontalOptions="Center" />
            </StackLayout>
        </Border>
    </toolkit:Popup>

Below is the verification result after changing the StokeShape and adjusting the roundness of the corners.

<table>
  <tr>
    <td>[Corners rounded]</td>
    <td>[Corners right angles]</td>
  </tr>
  <tr>
    <td><img width="250" src="https://github.com/CommunityToolkit/Maui/assets/125236133/4612ecdb-2e1e-41c1-8e57-d1108da7f947" /></td>
    <td><img width="250" src="https://github.com/CommunityToolkit/Maui/assets/125236133/21094fe9-46e0-4a80-a8bf-050bb93304d1" /></td>
  </tr>
</table>

**Comment by espritm** [comment]
@cat0363 
Thank you for that complete answer !

It's hard to take a decision about doing such a breacking change (CornerRadius=0 by default on iOS), whereas the iOS native default behavior is to get rounded angles.

However, by doing so, it make it very easy to customize the angles of popups, and we can do everything (which is not the case at this moment).

I think the final perfect result would be to have a CornerRadius parameter in the popup class, but it is a huge development as it requires to create a shape on Android for instance..And I don't know about others platforms.

Is there a way to modify the ConerRadius with a Handler ? Without modifying the CommunityToolkit source code ?

**Comment by maonaoda** [comment]
@espritm try this?
```
    public class CustomPopUpHandler : PopupHandler
    {
        protected override MauiPopup CreatePlatformElement()
        {
            return new CustomMauiPopup(MauiContext ?? throw new NullReferenceException(nameof(MauiContext)));
        }
    }

    ...
    public class CustomMauiPopup(IMauiContext mauiContext) : MauiPopup(mauiContext)
    {
       base.ViewDidLayoutSubviews();
       View.Superview.Layer.CornerRadius = 0.0f;    // <= Here
    }
```

**Comment by maonaoda** [comment]
@cat0363 
If CornerRadius doesn't want 10, then there's still a problem
`<Border StrokeShape="RoundRectangle 40" BackgroundColor="Red" StrokeThickness="0">`

![image](https://github.com/CommunityToolkit/Maui/assets/32831595/bf02f12b-0d4c-4671-84ac-a8a8a8010ad9)

**Comment by cat0363** [comment]
@maonaoda , I also confirmed this phenomenon. Hmm...

**Comment by espritm** [comment]
Because you need to apply something like this, isn't it ?

       View.Superview.Layer.CornerRadius = 40.0f;    // <= Here

**Comment by cat0363** [comment]
@espritm , As you say, it is possible by changing CornerRadius on iOS.

**Comment by cat0363** [comment]
It seems that it is not enough to simply set it to 40.0f.

**Comment by maonaoda** [comment]
@cat0363 @espritm 
try this, may be iOS`s Default Shadow view for popup

```
base.ViewDidLayoutSubviews();
PresentationController?.ContainerView?.Subviews.OfType<UIImageView>().FirstOrDefault()?.RemoveFromSuperview();
```

I`m using this to remove the Shadow. And it also can fix ↑.
![image](https://github.com/CommunityToolkit/Maui/assets/32831595/5752fd92-a4c1-49a5-a10e-a3af03e0447e)

**Comment by cat0363** [comment]
@maonaoda ,
Your code solved the previous problem. That's excellent.

**Comment by brminnick** [comment]
Thanks all! This is great news! 

Any chance you could open a Pull Request implementing the bug fix?

**Comment by cat0363** [comment]
If the rounded corners of iOS Popups are not intended and are a bug, and you want Popups with right-angled corners by default like Android, this problem can be solved with the code below. 

[src\CommunityToolkit.Maui.Core\Views\Popup\MauiPopup.macios.cs]

    public override void ViewDidLayoutSubviews()
    {
        base.ViewDidLayoutSubviews();

        _ = View ?? throw new InvalidOperationException($"{nameof(View)} cannot be null.");

        View.Superview.Layer.CornerRadius = 0.0f;
        PresentationController?.ContainerView?.Subviews.OfType<UIImageView>().FirstOrDefault()?.RemoveFromSuperview();

        SetElementSize(new Size(View.Bounds.Width, View.Bounds.Height));
    }

Below is the execution result.

<table>
  <tr>
    <td>[Corners rounded]</td>
    <td>[Corners right angles]</td>
  </tr>
  <tr>
    <td><img width="250" src="https://github.com/CommunityToolkit/Maui/assets/125236133/7cbfb201-45a9-4cc1-909a-4ea31d48274f" /></td>
    <td><img width="250" src="https://github.com/CommunityToolkit/Maui/assets/125236133/0b5bde86-579c-4c72-848a-1dddb58a6e46" /></td>
  </tr>
</table>

Can users accept that corners are right angles by default?
To control the roundness of a Popup's corners, you need to wrap the Popup's Content in a Border.

You need to do the following:

    <toolkit:Popup xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
        xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
        x:Class="MauiComm_VerityPopupSize.PopupPage6" Color="Transparent">
        <Border StrokeShape="RoundRectangle 10,10,10,10" BackgroundColor="Red" StrokeThickness="0">
            <StackLayout>
                <Label Text="Hello, World!" FontSize="32"/>
                <Button Text="Click me" HorizontalOptions="Center" />
            </StackLayout>
        </Border>
    </toolkit:Popup>

If you do not surround it with a border, it will look like the following.

<img width="250" src="https://github.com/CommunityToolkit/Maui/assets/125236133/ba5262d7-5466-4be4-aa89-2733beb4e057" />

Being able to control popup corner rounding on all platforms would require major changes, so I think it's best to move the iOS side closer to the Android or Windows side.

@brminnick , What do you think?

**Comment by cat0363** [comment]
Due to the time difference, I created the PR in advance.

**Comment by cat0363** [comment]
If you want to customize it with a handler, please also add the following.

    View.Superview.Layer.MasksToBounds = false;

The above prevents the popup corner curvature from changing after screen rotation.

**Comment by cat0363** [comment]
If you want to add the CornerRadius property to Popup, you can do it by modifying it as shown below.
However, it is assumed that the content of the Popup is not dynamically changed while being displayed.
This method is to replace the parent of Popup's Content with Border.

[src\CommunityToolkit.Maui\Views\Popup\Popup.shared.cs]

    public static readonly BindableProperty CornerRadiusProperty = BindableProperty.Create(nameof(CornerRadius), typeof(CornerRadius), typeof(Popup), new CornerRadius(0, 0, 0, 0), propertyChanged: OnCornerRadiusChanged);

    Border border = new Border() { StrokeShape = new RoundRectangle(), StrokeThickness = 0 }; 

    public Thickness CornerRadius
    {
        get => (Thickness)GetValue(CornerRadiusProperty);
        set => SetValue(CornerRadiusProperty, value);
    }

    static void OnContentChanged(BindableObject bindable, object oldValue, object newValue)
    {		
        var popup = (Popup)bindable;
        var content = popup.Content;
        if (content is not null)
        {
            if (popup.border.Parent is null)
            {
                popup.border.Content = content;
                popup.Content = popup.border;
                popup.border.Parent = popup;
                popup.OnBindingContextChanged();
            }
        }
    }

    static void OnColorChanged(BindableObject bindable, object oldValue, object newValue)
    {
        ArgumentNullException.ThrowIfNull(newValue);

        var popup = (Popup)bindable;
        if (popup.border is Border border)
        {
            border.BackgroundColor = (Color)newValue;
        }
    }

    static void OnCornerRadiusChanged(BindableObject bindable, object oldValue, object newValue)
    {
        var popup = (Popup)bindable;
        if (popup.border.StrokeShape is RoundRectangle strokeShape)
        {
            strokeShape.CornerRadius = (CornerRadius)newValue;
        }
    }

Removes MapColor from Mapper.

[src\CommunityToolkit.Maui.Core\Handlers\Popup\PopupHandler.shared.cs]

    public static IPropertyMapper<IPopup, PopupHandler> PopUpMapper = new PropertyMapper<IPopup, PopupHandler>(ElementMapper)
    {
        [nameof(IPopup.Anchor)] = MapAnchor,
        [nameof(IPopup.Size)] = MapSize,
        [nameof(IPopup.VerticalOptions)] = MapSize,
        [nameof(IPopup.HorizontalOptions)] = MapSize,
        [nameof(IPopup.CanBeDismissedByTappingOutsideOfPopup)] = MapCanBeDismissedByTappingOutsideOfPopup
    };

SetColor method is abolished. Moved the processing in the SetColor method to the SetSize method.

[src\CommunityToolkit.Maui.Core\Views\Popup\PopupExtensions.android.cs]

    public static void SetSize(this Dialog dialog, in IPopup popup, in AView container)
    {
        ArgumentNullException.ThrowIfNull(dialog);
        ArgumentNullException.ThrowIfNull(container);
        ArgumentNullException.ThrowIfNull(popup?.Content);

        int horizontalParams, verticalParams;

        var window = GetWindow(dialog);
        var context = dialog.Context;
        var windowManager = window.WindowManager;

        var decorView = (ViewGroup)window.DecorView;
        var child = decorView.GetChildAt(0) ?? throw new InvalidOperationException($"No child found in {nameof(ViewGroup)}");

        int realWidth = 0,
             realHeight = 0,
             realContentWidth = 0,
             realContentHeight = 0;

        var windowSize = GetWindowSize(windowManager, decorView);

        window.SetBackgroundDrawable(new ColorDrawable(Colors.Transparent.ToPlatform(AColorRes.BackgroundLight, dialog.Context)));

        ... omit
    }

SetBackgroundColor method is abolished. Moved the processing in the SetBackgroundColor method to the SetLayout method.

[src\CommunityToolkit.Maui.Core\Views\Popup\PopupExtensions.macios.cs]

    public static void SetLayout(this MauiPopup mauiPopup, in IPopup popup)
    {
        if (mauiPopup.View is null)
        {
            return;
        }

        CGRect frame;

        if (mauiPopup.ViewController?.View?.Window is UIWindow window)
        {
            frame = window.Frame;
        }
        else
        {
            frame = UIScreen.MainScreen.Bounds;
        }

        if (mauiPopup.PopoverPresentationController is null)
        {
            throw new InvalidOperationException("PopoverPresentationController cannot be null");
        }

        mauiPopup.PopoverPresentationController.PopoverBackgroundViewType = typeof(TransparentPopoverBackgroundView);
        if (mauiPopup.Control is not null)
        {
            mauiPopup.Control.PlatformView.BackgroundColor = Colors.Transparent.ToPlatform();
            if (mauiPopup.Control.ViewController?.View is UIView view)
            {
                view.BackgroundColor = Colors.Transparent.ToPlatform();
            }
        }
        ... omit
    }

SetColor method is abolished. Moved the processing in the SetColor method to the SetSize method.

[src\CommunityToolkit.Maui.Core\Views\Popup\PopupExtensions.windows.cs]

    public static void SetSize(this Popup mauiPopup, IPopup popup, IMauiContext? mauiContext)
    {
        ArgumentNullException.ThrowIfNull(mauiContext);
        ArgumentNullException.ThrowIfNull(popup.Content);

        const double defaultBorderThickness = 0;
        const double defaultSize = 600;

        var popupParent = mauiContext.GetPlatformWindow();
        var currentSize = new Size { Width = defaultSize, Height = defaultSize / 2 };
		
        if (mauiPopup.Child is FrameworkElement content)
        {
            var backgroundProperty = content.GetType().GetProperty("Background");
            backgroundProperty?.SetValue(content, Colors.Transparent.ToPlatform());
        }
        ... omit
    }

MapColor method is abolished. 

[src\CommunityToolkit.Maui.Core\Handlers\Popup\PopUpHandler.android.cs]
[src\CommunityToolkit.Maui.Core\Handlers\Popup\PopupHandler.macios.cs]
[src\CommunityToolkit.Maui.Core\Handlers\Popup\PopUpHandler.windows.cs]

Below is the screen layout.

    <toolkit:Popup xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
        xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
        x:Class="MauiComm_VerityPopupSize.PopupPage6" Size="200,200" Color="Red" CornerRadius="20,20,20,20">
        <Grid>
            <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="Start" HorizontalOptions="Start" BackgroundColor="Blue" />
            <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="Start" HorizontalOptions="End" BackgroundColor="Blue" />
            <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="End" HorizontalOptions="Start" BackgroundColor="Blue" />
            <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="End" HorizontalOptions="End" BackgroundColor="Blue" />
        </Grid>
    </toolkit:Popup>

Below is the execution result.

[Android]

<img width="300" src="https://github.com/CommunityToolkit/Maui/assets/125236133/e80b215d-d9e3-42bd-8b3a-4b36702739d2" />

[iOS]

<img width="300" src="https://github.com/CommunityToolkit/Maui/assets/125236133/8347afd6-4316-4e86-96a6-8d6786b217f6" />

[Windows]

<img width="300" src="https://github.com/CommunityToolkit/Maui/assets/125236133/99f80d51-e94b-47b0-a4fb-9114ff917359" />

This is not a desirable change for users who are already using the trick of wrapping Popup content with a Border.
If you want to dynamically change the Popup's content, wrapping the Popup's content in a Border during the Popup's internal processing will impair customization. After all, it may be better to standardize the rounded corners of iOS Popups to right angles like Windows and Android, and have users wrap them with a Border if they want to round the corners of Popups.
