### ISSUE TITLE
[BUG] [Popup][Windows] Calling Pupop in OnAppearing Causes the Program to Crash

### ISSUE THREAD

**Issue by BaY1251** [CommunityToolkit/Maui#1453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

As shown in the figure,Calling Pupop in OnAppearing Causes the Program to Crash
This issue only occurs onWindows devices, and  Android performs normally.

![popup](https://github.com/CommunityToolkit/Maui/assets/48309205/79661381-4c36-4262-9d25-d995fe604689)

### Expected Behavior

Pupop can be called normally in OnAppearance

### Steps To Reproduce

1. Open Popup_OnAppearing\ Toolkit.sln
2. Click SHELL to open the second page

### Link to public reproduction project repository

https://github.com/BaY1251/MauiDebug.git

### Environment

```markdown
- .NET MAUI CommunityToolkit:6.0.0
- OS:Windows10.0-22H2
- .NET MAUI:7.0.96
```

**Comment by cat0363** [comment]
Below is a workaround.
This can be avoided if the timing is OnLoaded instead of OnAppearing.

    public partial class SecPage : ContentPage
    {
        public SecPage()
        {
            InitializeComponent();
        }

        protected override void OnAppearing()
        {
            base.OnAppearing();
            this.Loaded += OnLoaded;
        }

        async void OnLoaded(object? sender, EventArgs e)
        {
            this.Loaded -= OnLoaded;
            await NewPopup.Show();
        }
    }

Below are the results of the workaround.

https://github.com/CommunityToolkit/Maui/assets/125236133/e89a356f-9908-4b6a-9d20-003ea91e830b

When I called the ToHandler method at OnAppearing timing, it was null.
Can anyone solve it?

[src\CommunityToolkit.Maui\Views\Popup\PopupExtensions.windows.cs]

    static void PlatformShowPopup(Popup popup, IMauiContext mauiContext)
    {
        var window = mauiContext.GetPlatformWindow().GetWindow() ?? throw new NullReferenceException("Window is null.");
        popup.Parent = ((Page)window.Content).GetCurrentPage();
		
        var platform = popup.ToHandler(mauiContext);   // <= Here
        platform?.Invoke(nameof(IPopup.OnOpened));
    }

**Comment by BaY1251** [comment]
@cat0363  Here is my temporary plan, but it is indeed a problem

`		async  void OnLoaded(object sender, EventArgs e)
		{
			Loaded -= OnLoaded;
			await NewPopup.Show();
		}
		protected override void OnNavigatedTo(NavigatedToEventArgs args)
		{
			base.OnNavigatedTo(args);
			if(IsLoaded)
			{
				await NewPopup.Show();
			}
			else
			{
				Loaded += OnLoaded;
			}
		}
`

**Comment by cat0363** [comment]
@BaY1251 , By changing the Show method of the NewPopup class as shown below, it now works without any tricks.

    public static async Task Show()
    {
        var popup = new NewPopup();
        popup.Opened += (s, e) => Task.Delay(500).ContinueWith(s =>
        {
            Thread.Sleep(1000);
            MainThread.BeginInvokeOnMainThread(() => popup.Close());
        });

        await Shell.Current.CurrentPage.ShowPopupAsync(popup);     // Here
    }

When Shell.Current.ShowPopupAsync(popup) is used, XamlRoot becomes null because it is processed in the AppShell Loaded event instead of the Page Loaded event, and it is not processed correctly. 

[src\CommunityToolkit.Maui.Core\Handlers\Popup\PopUpHandler.windows.cs]

    public static void MapOnOpened(PopupHandler handler, IPopup view, object? result)
    {
        ArgumentNullException.ThrowIfNull(view.Parent);
        ArgumentNullException.ThrowIfNull(handler.MauiContext);
        var parent = view.Parent.ToPlatform(handler.MauiContext);
        parent.IsHitTestVisible = false;
        handler.PlatformView.XamlRoot = parent.XamlRoot;    // parent.XamlRoot is null
        handler.PlatformView.IsHitTestVisible = true;
        handler.PlatformView.IsOpen = true;
        view.OnOpened();
    }

**Comment by cat0363** [comment]
By modifying the Community Toolki source code as shown below, it will work even if you use Shell.Current.ShowPopupAsync(popup).

[src\CommunityToolkit.Maui\Views\Popup\PopupExtensions.shared.cs]

    public static void ShowPopup<TPopup>(this Page page, TPopup popup) where TPopup : Popup
    {
    #if WINDOWS
        void handler(object? sender, EventArgs args)
        {
            page.GetCurrentPage().Loaded -= handler;

            CreateAndShowPopup(page, popup);
        }

        page.GetCurrentPage().Loaded += handler;
#else
        if (page.IsPlatformEnabled)
        {
            CreateAndShowPopup(page, popup);
        }
        else
        {
            void handler(object? sender, EventArgs args)
            {
                page.Loaded -= handler;

                CreateAndShowPopup(page, popup);
            }

            page.Loaded += handler;
        }
    #endif
    }

    public static Task<object?> ShowPopupAsync<TPopup>(this Page page, TPopup popup) where TPopup : Popup
    {
    #if WINDOWS
        var taskCompletionSource = new TaskCompletionSource<object?>();

        async void handler(object? sender, EventArgs args)
        {
            page.GetCurrentPage().Loaded -= handler;

            try
            {
                var result = await CreateAndShowPopupAsync(page, popup);

                taskCompletionSource.TrySetResult(result);
            }
            catch (Exception ex)
            {
                taskCompletionSource.TrySetException(ex);
            }
        }
        page.GetCurrentPage().Loaded += handler;

        return taskCompletionSource.Task;
    #else
        if (page.IsPlatformEnabled)
        {
            return CreateAndShowPopupAsync(page, popup);
        }
        else
        {
            var taskCompletionSource = new TaskCompletionSource<object?>();

            async void handler(object? sender, EventArgs args)
            {
                page.Loaded -= handler;

                try
                {
                    var result = await CreateAndShowPopupAsync(page, popup);

                    taskCompletionSource.TrySetResult(result);
                }
                catch (Exception ex)
                {
                    taskCompletionSource.TrySetException(ex);
                }
            }
            page.Loaded += handler;

            return taskCompletionSource.Task;
        }
    #endif
    }

@brminnick , Should I create a PR?

**Comment by BaY1251** [comment]
@cat0363  Very effective, thank you

**Comment by cat0363** [comment]
@brminnick , I will create a PR for this issue tomorrow. If you do not need the created PR, please close it.

**Comment by brminnick** [comment]
Thanks @cat0363 - that'd be great!

**Comment by cat0363** [comment]
@brminnick , Then, I will create a PR tomorrow.
