### ISSUE TITLE
[BUG] FilePicker.Default.PickAsync doesn't request read permissions on Android 8

### ISSUE THREAD

**Issue by pekspro** [CommunityToolkit/Maui#1458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

With `FilePicker.Default.PickAsync` you can select a file. But in Android 8 (and probably more versions), you might not have read access to the file. Which means when you call `result.OpenReadAsync()` an exception will be thrown with message like `Access to the path '/storage/emulated/0/Download/myfile.bin' is denied.` 

### Expected Behavior

`FilePicker.Default.PickAsync` should make sure permissions are granted before selecting a file.

### Steps To Reproduce

1. Create a new MAUI project and add CommunityToolkit.
2. Execute this code in Android 8:

```C#
    private async void OpenFile(object sender, EventArgs e)
	{
        var customFileType = new FilePickerFileType(
            new Dictionary<DevicePlatform, IEnumerable<string>>
            {
                { DevicePlatform.Android, new[] { "application/octet-stream" } }
            });

        PickOptions options = new()
        {
            PickerTitle = "Select file",
            FileTypes = customFileType,
            
        };

        var result = await FilePicker.Default.PickAsync(options);
        if (result != null)
        {
            try
            {
                using var stream = await result.OpenReadAsync();

                using var reader = new StreamReader(stream);

                var text = reader.ReadToEnd();
            }
            catch(Exception ex)
            {
                Debugger.Break();
                string message = ex.Message;
            }
        }
    }
```

Reading will fail if storage permissions hasn't been granted.

### Link to public reproduction project repository

https://github.com/pekspro/MauiIssues/tree/CommunityToolkit_1458_FilePicker.Default.PickAsync_Permissions

### Environment

```markdown
- .NET MAUI CommunityToolkit: 6.0.0.
- OS: Android 8
- .NET MAUI: 7 and 8 RC2
```

### Anything else?

`FileSaver.Default.SaveAsync` does check for permissions.

The storage permissions can be manually changed in the Android settings for the app:

![image](https://github.com/CommunityToolkit/Maui/assets/3163293/fe396506-bc5c-46fd-a8a8-23b2194129cb)

**Comment by VladislavAntonyuk** [comment]
FilePicker is not a part of MCT

**Comment by pekspro** [comment]
Ups, sorry! 😂
