### ISSUE TITLE
[BUG] StatusBarBehavior StatusBarStyle not updating correctly on Android 10

### ISSUE THREAD

**Issue by Cybrosys** [CommunityToolkit/Maui#1466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

The status bar's style is not getting updated correctly on Android 10 when navigating between pages that you have already navigated to and that have different styles configured.

I can reproduce the issue on Android 10 but not on Android 13.

### Expected Behavior

The status bar color and style should update.

### Steps To Reproduce

- Run the repo project
- Navigate to the second and then the third page.
- Press the second page's tab and you will see that the style is light, even though it should be dark (white status bar).
- Navigate to any of the other pages and you will see that the style is becoming the previous's page's style.

### Link to public reproduction project repository

https://github.com/Cybrosys/Sandbox/tree/master/MauiAppStatusBarBehavior

### Environment

```markdown
- .NET MAUI CommunityToolkit: 6.0.0
- OS: Android 10
- .NET MAUI: 8.0.0-rc.2.9373/8.0.100-rc.2
```

### Anything else?

It works as expected on Android 13 or if I set the color and style in OnAppearing on the actual page.

**Comment by cat0363** [comment]
@Cybrosys , Perhaps you are expecting behavior like this?

https://github.com/CommunityToolkit/Maui/assets/125236133/8f9ef28b-e67f-4939-befe-b0cb6fb974cf

Something similar was discussed in Issue #1194, but no conclusion was reached.

If you implement it as shown in the post below, it will work as expected.
https://github.com/CommunityToolkit/Maui/issues/1194#issuecomment-1590731555

Or please refer to the post below.
https://github.com/CommunityToolkit/Maui/issues/1194#issuecomment-1591630987

**Comment by Cybrosys** [comment]
Hello @cat0363 ,

Yes that is the expected behavior I am after.

**Comment by cat0363** [comment]
This is the result of operation verification on Android 10 and 13 emulators.
Both seem to have the same behavior.

<table>
  <tr>
    <td>[Android 10]</td>
    <td>[Android 13]</td>
  </tr>
  <tr>
    <td><video controls width="250" src="https://github.com/CommunityToolkit/Maui/assets/125236133/71e64229-8ed6-4544-99d2-52501795880d" /></td>
    <td><video controls width="250" src="https://github.com/CommunityToolkit/Maui/assets/125236133/e1a668c5-3e4b-4a5f-8c12-0aba08fabede" /></td>
  </tr>
</table>

**Comment by Cybrosys** [comment]
@cat0363 That is interesting. I was using a Samsung S9 (Android 10) and Galaxy XCover 5 (Android 13). On both devices it was changing the status bar color but the style was lagging behind/not updating correctly.

Since I do get the expected behavior when implementing your change, maybe that should be the default for all platforms (remove the two calls from _OnAttachedTo_ and do them in _Page.NavigatedTo_ only). My only concern with that would be if there are any scenarios where _Page.NavigatedTo_ would not fire.
