### ISSUE TITLE
[BUG] Snackbar on Windows - If you pass in an Action that does Shell.Current.GoToAsync a button click launches a new instance of the app

### ISSUE THREAD

**Issue by DP-Technology-LLC** [CommunityToolkit/Maui#1472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Android behaves as expected.

On Windows if you create an action like such:

`async void sbAction() => await Shell.Current.GoToAsync("//Parent1");`

and pass it into `Snackbar.Make` (and show it), the button shows up as expected and your app navigates as expected when clicked.

However a new instance of your App will be created after you click said button so now you have two apps on your screen.

### Expected Behavior

Windows would not create another instance

### Steps To Reproduce

See Current Behavior

### Link to public reproduction project repository

n/a

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.3
- OS: Windows 11 22H2 Build 22621.2428
- .NET MAUI: 7.0.92/7.0.100
```

**Comment by VladislavAntonyuk** [comment]
You have to implement it on your side. See https://github.com/CommunityToolkit/Maui/blob/main/samples/CommunityToolkit.Maui.Sample/Platforms/Windows/App.xaml.cs

**Comment by DP-Technology-LLC** [comment]
Thanks @VladislavAntonyuk , that did it!

However, now the user can't manually launch two instances if they want to.

With the workaround you provided it's more than a head start to solving that issue as well.

**Comment by DP-Technology-LLC** [comment]
It appears to us that you no longer need the Work Around that was suggest if the app is targeting .net 8.
