### ISSUE TITLE
[BUG] [Windows] InitialPath is not being considered in FolderPicker implementation on Windows

### ISSUE THREAD

**Issue by argraur** [CommunityToolkit/Maui#1479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Folder picker opens only in Documents folder `PickerLocationId.DocumentsLibrary` no matter what the value of `initialPath` is

### Expected Behavior

Folder picker starts in `initialPath` if it's not empty

### Steps To Reproduce

1. Open and run solution from reproduction project repository on Windows target
2. You can change initial path on main screen
3. Press button "Pick folder w/ initial path"
4. It will open "Documents" folder regardless of Entry value
5. Ensure that changing initial path on screen doesn't affect either of folder picker buttons

### Link to public reproduction project repository

https://github.com/argraur/FolderPickerInitialPathWindowsBug

### Environment

```markdown
- .NET MAUI CommunityToolkit: 6.0.0
- OS: Windows 11 Build 10.0.25967.1000
- .NET MAUI: 8.0.100-rc.2.23502.2
```

### Anything else?

Only Windows is affected with this issue

https://github.com/CommunityToolkit/Maui/blob/b430ba6a3ebcbca9f004e2430871543e4203551c/src/CommunityToolkit.Maui.Core/Essentials/FolderPicker/FolderPickerImplementation.windows.cs#L10C46-L10C57

Noticeably, initialPath is not used anywhere in Windows implementation

**Comment by VladislavAntonyuk** [comment]
not supported by windows. by design

**Comment by mrwcjoughin** [comment]
Why not if it’s possible to do it?

**Comment by VladislavAntonyuk** [comment]
@mrwcjoughin if you know the solution you can create a pr or point to the documentation

**Comment by mrwcjoughin** [comment]
The logger of this issue already has a proposed solution - which if he
knows it will be accepted I’m sure he will do a pr for it

**Comment by VladislavAntonyuk** [comment]
@mrwcjoughin I don’t see where the solution is proposed, waiting for a PR.
As far as I know currently WinUI doesn’t allow to choose any initialPath, only the list of predefined. We use Documents by default

**Comment by NJullienSweet** [comment]
Hello, I encountered the same issue in my project.
Please excuse me if I'm completely wrong: isn't `Windows.Storage.Pickers.FolderPicker.SuggestedStartLocation` what you're looking for?
https://learn.microsoft.com/en-us/uwp/api/windows.storage.pickers.folderpicker.suggestedstartlocation?view=winrt-22621#windows-storage-pickers-folderpicker-suggestedstartlocation

**Comment by mrwcjoughin** [comment]
Absolutely, thats what the creator of this issue Arseniy Graur suggested -
all thats required is for someone to create a PR with the change

**Comment by VladislavAntonyuk** [comment]
SuggestedStartLocation is enum, in our implementation, it is a string. we don't want to limit the path because of windows limilation
