### ISSUE TITLE
speechToText interferes with textToSpeech on iPhone [BUG] 

### ISSUE THREAD

**Issue by AncientLust** [CommunityToolkit/Maui#1497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

After a call of `speechToText.ListenAsync` or `speechToText.StartListenAsync` every subsequent call of `textToSpeech.SpeakAsync` produces half volume sound. 

If you call `speechToText.ListenAsync` or `speechToText.StartListenAsync` right after or during `textToSpeech.SpeakAsync` pronounces text you will see exception. This doesn't happen on Android. 

[ExceptionMessage.txt](https://github.com/CommunityToolkit/Maui/files/13257829/ExceptionMessage.txt)

### Expected Behavior

1. Calls of `speechToText.ListenAsync` and `speechToText.StartListenAsync` should not affect subsequent calls of `textToSpeech.SpeakAsync`. 
2. `speechToText.ListenAsync` and `speechToText.StartListenAsync` must be callable right after `textToSpeech.SpeakAsync`

### Steps To Reproduce

1. Open CommunityToolkit.Maui.Sample.sln
2. Menu -> Essentials -> SpeechToText
3. Click Play and listen the phrase, keep attention to the volume level.
4. Click ListenAsync or StartListenAsync and say some words.
5. Click Play and keep attention to the volume level, it will be approximately twice weaker.

* if you hit ListenAsync or StartListenAsync while the default phrase "Welcome to ..." is pronounced you will catch the exception.

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui/tree/main/samples

### Environment

```markdown
- .NET MAUI CommunityToolkit: 6.1.0
- OS: Windows 11 Pro Build 22621.2283
- Target framework: net7.0-ios
```

**Comment by AncientLust** [comment]
Based on these two threads the issue might be related to the incorrectly configured `audioSession.SetCategory`. This, looking into the code, has been [configured for MacOS](https://github.com/CommunityToolkit/Maui/blob/main/src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SpeechToTextImplementation.macos.cs), but [omitted for iOS](https://github.com/CommunityToolkit/Maui/blob/main/src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SpeechToTextImplementation.ios.cs).

[Thread 1](https://github.com/AudioKit/AudioKit/issues/2389) describes that incorrectly configured `audioSession.SetCategory` causes `IsFormatSampleRateAndChannelCountValid` exception. Which is exactly the exception I see when  `speechToText.ListenAsync` or `speechToText.StartListenAsync` starts right after or during `textToSpeech.SpeakAsync`.

> It turns out that in the case of my app, this was a result of not having the AVAudioSession category correctly set.

[Thread 2](https://github.com/react-native-voice/voice/issues/50) - Same volume level issue, same symptoms, but on react-native:

> So AVAudioSession is a singleton/shared instance for your whole app. Changing the category of a shared audio session to AVAudioSessionCategoryRecord will interrupt any audio that is playing. react-native-sound and react-native-audio-toolkit don't play nicely with this (when AVAudioSessionCategoryPlayback is used) because it seems to either lose the pointer for the audio resource and replace it with the input/microphone source, interrupt the currently playing audio or decreases the volume of the currently playing audio by 80% and all subsequent audio regardless whether speech recognition is active.

**Comment by AncientLust** [comment]
I was able to fix this issue in the following way:
1. I used Gerald's [SpeechToText implementation for iOS](https://www.youtube.com/watch?v=kxUsmctDyko) to reproduce the issue.
2. Placed two lines of code in `SpeechToTextImplementation` for iOS:

```C#
// At the beginning of the recognition task
var audioSession = AVAudioSession.SharedInstance();
audioSession.SetCategory(AVAudioSessionCategory.PlayAndRecord, AVAudioSessionCategoryOptions.DefaultToSpeaker);
```

With `AVAudioSessionCategory.PlayAndRecord` it works as expected allowing to use simultaneously speech recognition and text-to-speech speaking. 

**Interesting note:** If I use `AVAudioSessionCategory.Record` and don't set it back to `AVAudioSessionCategory.Playback` when recognition ends, the issue persists. So I can assume that `textToSpeech.SpeakAsync` implementation for iOS doesn't set up `AVAudioSessionCategory` to `Playback` at the start and probably requires intervention. 

**Additionals:** Obviously, this is a bare-bones solution since the audio session preset requires not only `AVAudioSessionCategory`, but `AVAudioSessionCategoryOptions` and `AVAudioSessionMode`. I assume it would be a good approach to have this setup for speechToText:

* [AVAudioSessionCategoryRecord](https://developer.apple.com/documentation/avfaudio/avaudiosessioncategoryrecord)
* [AVAudioSessionModeMeasurement](https://developer.apple.com/documentation/avfaudio/avaudiosessionmodemeasurement)

And for textToSpeech:
* [AVAudioSessionCategoryPlayback](https://developer.apple.com/documentation/avfaudio/avaudiosessioncategoryplayback)
* [VAudioSessionModeDefault](https://developer.apple.com/documentation/avfaudio/avaudiosessionmodedefault)

But it's up to your discretion guys.

You can find the project containing the fix [here](https://github.com/AncientLust/MauiSpeechToTextSample).

**Comment by AncientLust** [comment]
If your project requires a temporary solution, just add these lines into `MauiProgram.cs':

```C#
#if IOS
        var audioSession = AVAudioSession.SharedInstance();
        audioSession.SetCategory(AVAudioSessionCategory.PlayAndRecord, AVAudioSessionCategoryOptions.DefaultToSpeaker);
#endif
```

**Comment by brminnick** [comment]
Thanks for the great detective work, @AncientLust! 

I've opened #1513 to resolve this. Feel free to give it a review! 

This fix will be included in our next release, `CommunityToolkit.Maui v7.0.0`.
