### ISSUE TITLE
[BUG] 'Microsoft.NET.Sdk.iOS.Manifest-7.0.100 16.4.7125' has incompatible package type.				

### ISSUE THREAD

**Issue by alaskanrogue** [CommunityToolkit/Maui#1502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Beginning this afternoon, the error message "Process cannot be executed on XMA server. Could not find Microsoft.iOS in /Users/marcgeorge/Library/Caches/Xamarin/XMA/SDKs/dotnet/packs/Microsoft.iOS.Sdk/16.4.7125" is received during build. 

When attempting to install the package, which was published today, 11/7/2023, the package required by my application, the error message "NU1213: The package Microsoft.NET.Sdk.iOS.Manifest-7.0.100 16.4.7125 has a package type DotnetPlatform that is incompatible with this project." is received.

All packages in the project are up to date, however, include pre-releases.  

Builds have been attempted on both Windows and Mac with the latest versions of VS Pr e with same results.

### Expected Behavior

Successful build.

### Steps To Reproduce

Build a MAUI iOS project with the necessary packages from those noted below.

### Link to public reproduction project repository

NA

### Environment

```markdown
VS 17.8.0 Preview 7.0

.NET 7.0.96
ios 16.4.8968-net8-rc2/8.0.100-rc.2

"CommunityToolkit.Maui" Version="6.1.0" />
"CommunityToolkit.Maui.Core" Version="6.1.0" />
"CommunityToolkit.Maui.MediaElement" Version="2.0.0" />
"Geolocator.Plugin" Version="1.0.2" />
"Microsoft.Azure.NotificationHubs" Version="4.1.0" />
"Microsoft.CognitiveServices.Speech" Version="1.33.0" />
"Microsoft.Data.Edm" Version="5.8.5" />
"Microsoft.Data.OData" Version="5.8.5" />
"Microsoft.Data.Services.Client" Version="5.8.5" />
"Microsoft.Extensions.ApiDescription.Client" Version="8.0.0-rc.2.23480.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
"Microsoft.Extensions.Features" Version="8.0.0-rc.2.23480.2" />
"Microsoft.Extensions.Primitives" Version="8.0.0-rc.2.23479.6" />
"Newtonsoft.Json" Version="13.0.3" />
"NSwag.ApiDescription.Client" Version="14.0.0-preview009">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
"Plugin.Maui.Audio" Version="2.0.0" />
"System.ServiceModel.Duplex" Version="6.0.0" />
"System.ServiceModel.Federation" Version="6.1.0" />
"System.ServiceModel.Http" Version="6.1.0" />
"System.ServiceModel.NetTcp" Version="6.1.0" />
"System.ServiceModel.Primitives" Version="6.1.0" />
"System.ServiceModel.Security" Version="6.0.0" />
"System.Spatial" Version="5.8.5" />
"Xamarin.Essentials" Version="1.8.0" />
```

**Comment by brminnick** [comment]
This bug is not related to the .NET MAUI Community Toolkit

**Comment by alaskanrogue** [comment]
Transferred to https://github.com/dotnet/maui/issues/18604
