### ISSUE TITLE
speechToText iOS disposal issue [BUG]

### ISSUE THREAD

**Issue by AncientLust** [CommunityToolkit/Maui#1515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

**The issue itself**
In my application, I noticed that after approximately 20-30 calls of `speechToText.ListenAsync` iOS recognition fails immediately after starting with `kAFAssistantErrorDomain error 7` exception.

**Temporary solution**
I was able to fix it by calling `await speechToText.DisposeAsync();` each time when I'm done with speechToText. 

**Probable cause**
For iOS implementation each `speechToText.ListenAsync` call creates instances like `SFSpeechRecognizer`, `AVAudioEngine`, and `SFSpeechRecognitionTask` which require a call of `Disposal` method once work with them has been finished. All these Disposal methods lie in `DisposeAsync()` method of [SpeechToTextImplementation](https://github.com/CommunityToolkit/Maui/blob/main/src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SharedSpeechToTextImplementation.macios.cs). The issue is that there is no call of this method when the recognition task is finished.

There is no sign in the [documentation](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/essentials/speech-to-text?tabs=ios) that `DisposeAsync()` needs to be called manually after each call of `speechToText.ListenAsync` or using `using` statement. So it is a question for me whether it is by design or not. I assume not, since `speechToText` is a singleton by [documentation](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/essentials/speech-to-text?tabs=ios). 

### Expected Behavior

Disposable objects of `SpeechToTextImplementation` should be automatically disposed when a recognition task has been finished. Otherwise it produces issues in time, like `kAFAssistantErrorDomain error 7` exception. 

### Steps To Reproduce

**Repro project short description**
The StartListen button calls 50 recognition tasks (start and stop) and then 51th requires voice input. If on 51 iteration you see: 
* "Exception: No speech detected" shows that speech recognition ends immediately after the start.
* "Say something" means the issue didn't happen, you can use recognition even after 50 calls.

When you download the repo, two lines with manual disposal will be commented out, so you will start with the Exception case.

**Steps to reproduce**
1. Open and run the solution from the production repository.
2. Run the application on iOS and click StartListen. After 50 calls you will see text: "Exception: No speech detected". If you are lucky, you can see "Say something". Say a test phrase, click StopListen and just click StartListen again the issue will happen in the next iteration. 
3. To get rid of this issue, uncomment two lines in MainPage.xaml.cs - lines 48 and 71. 
4. Redeploy and start the application, click StartListen. After 50 calls you will see "Say something".

### Link to public reproduction project repository

https://github.com/AncientLust/SpeechToText-iOS-Disposal-issue

### Environment

```markdown
- .NET MAUI CommunityToolkit: 6.1.0
- OS: Windows 11 Build 22631.2506
- .NET MAUI: 8.0.0
- Device: iPhone 15 with iOS 17.1.1
```

### Anything else?

I understand the repro project is quite clumsy, but it was a challenge to track this error. Please let me know if you need any further details or help.

**Comment by brminnick** [comment]
@bijington + @VladislavAntonyuk  - I'd love your thoughts on this! It sounds like things work as long as it's Disposed. 

Do you think an update to the XML Comments, the Online Documentation  + the Sample App would suffice for this? Or is there perhaps something we should do better in the source code?

**Comment by VladislavAntonyuk** [comment]
Why it fails only after 50 times?

**Comment by bijington** [comment]
It sounds like our implementation of `ListenAsync` should internally dispose of things once this has completed (e.g. when calling `getRecognitionTaskCompletionSource.SetException` or `getRecognitionTaskCompletionSource.TrySetResult` or when the `cancellationToken` is cancelled). From reading through the code it does look like we will create new instances of members like `audioEngine`, etc. on each call of `ListenAsync`.

I would like to go a step further though and ask whether we could separate out and encapsulate the bits that pair together and remove the combination of methods that do not work together. For example if `ListenAsync` has no interaction with `StartListenAsync` and `StopListenAsync` could we wrap those into some constructs that remove any confusion around thinking they could be used together?

I appreciate this is an extra layer to introduce and massively breaking but what if we had 2 new classes that were created from interacting with `SpeechToText`? We could have a `OneShotSpeechToTextListener` and a `ContinuousSpeechToTextListener` that gets returned to a developer. It would remove the confusion around which methods to use in combination. Thoughts?

**Comment by AncientLust** [comment]
Hi guys, saw your emails, sorry for the late reply, had busy days.

@VladislavAntonyuk, the reason I started using `StopListenAsync` in combination with `ListenAsync` is the following: my first impression was, as you said, to use a cancellation token for `ListenAsync`, but when I implemented this approach I found that once a cancellation token has been canceled, the recognition process indeed stops, but `recognitionResult.IsSuccessfull` is set to `false` and `recognitionResult.Text` is empty. So the only way to stop the recognition process and fetch final results was to use `StopListenAsync`. It's important to fetch the final result since I noticed that on iOS intermediate results can often differ from the final result. It can accidentally split one word into two, but the final result will be fine anyway.   

Seeing your reply I switched my implementation back to cancellation token usage. Just checked it again and saw the same behavior as I described in the lines above. So I fetched the latest version of `CommunityToolkit.Maui.Sample` and looked at how it works there. So.. it works the same. I set up the breakpoint on this if statement in [SpeechToTextViewModel.cs](https://github.com/CommunityToolkit/Maui/blob/main/samples/CommunityToolkit.Maui.Sample/ViewModels/Essentials/SpeechToTextViewModel.cs), hit `ListenAsync`, said some words, saw them popping on the screen, then hit `Canel Token` button. 

```csharp
if (recognitionResult.IsSuccessful)
{
    RecognitionText = recognitionResult.Text;
}
else
{
    await Toast.Make(recognitionResult.Exception?.Message ?? "Unable to recognize speech").Show(CancellationToken.None);
}
```
And the result is the same as I see in my application, `recognitionResult.IsSuccessful = false`, `recognitionResult.Text = ""` @VladislavAntonyuk could you approve this is expected behavior? 

Regarding device tests of the latest `CommunityToolkit.Maui.Sample`:
1. Open Essentials\SpeechToText. 
2. Hit `ListenAsync`, and say some words.
3. After your first word is recognized, you will see the popup "State changed: Stopped". Probably requires attention, not sure it must pop up at this stage. 
4. Hit `Cancel Token`. Recognized text will be erased.
5. Hit `Play`, app crashes. 

And anyway, that's not the point, but at least not the main one. My biggest concern, as @bijington highlighted, is that each call of `ListenAsync` creates new instances of members that are supposed to be disposed. And at least as I see, it is not disposed after each `ListenAsync` call. 

If you guys say, naah, it handled fine, you just don't get it, it's fine. My experience in .NET is about three months. I can oversee some things.

**Comment by VladislavAntonyuk** [comment]
you should click any button. speech recognition stops automatically after some seconds when you stop talking. if you click cancel button, that means you cancel the whole listening process, you won't get final result and is successful is set to false (because operation cancelled). for you scenario you need to use start/stop listen methods.

**Comment by AncientLust** [comment]
Ok, this usage wasn't transparent at all. Because it actually doesn't stop automatically after some seconds of silence on iOS. Right now, it's about 6th minute my iPhone keeps listening and recognizing after `ListenAsync` activation. Until I press the `Cancel Token` button. 

Was it the point of this [bug report](https://github.com/CommunityToolkit/Maui/issues/1415)?

**Comment by VladislavAntonyuk** [comment]
most likely Apple's limitation of many requests:

![](https://i.stack.imgur.com/StMTe.png)

**Comment by CameronVetter** [comment]
I see this issue is closed but there has not been a resolution. @AncientLust is correct, on ios SpeechToText does not behave correctly, it keeps listening even after minutes of silence.  What is the resolution if this was closed?

**Comment by VladislavAntonyuk** [comment]
We made changes in Speech Recognition. 
Use StartListen/StopListen methods to control the recognition process. You can also get current Recognition State.
Technically there is a auto stop timeout. As for iOS see screenshot with limitation above. As for windows we set it to TimeSpan.MaxValue.

And the main rule - do not combine ListenAsync with StopListen. To cancel ListenAsync use cancellation token.

**Comment by CameronVetter** [comment]
I don't mean to be dense but this doesn't really answer the question.  Are you saying that ListenAsync should not be used ever then?  Is it deprecated?  Since ListenAsync does not stop automatically on iOS like it does on Android you must use StopListen with it.  If you don't it runs forever.  If you cancel it as you suggest this causes it to not give a final result.  I have no idea what the image above is supposed to tell me either... I understand what it is saying but no idea what that has to do with ListenAsync not working as expected.

Put another way, when I use the very first code example in your blog article on SpeechToText it never works correctly on IOS as pointed out by @AncientLust and now myself.  

https://devblogs.microsoft.com/dotnet/speech-recognition-in-dotnet-maui-with-community-toolkit/

Looking back in this issue this maybe wasn't the original bug reported here, is it being addressed in a different issue and that is why it was closed?

**Comment by VladislavAntonyuk** [comment]
ListenAsync on iOS (on the device) and Windows runs forever. this is by design. It is not obsolete. You can still use it if you like. By use correctly. to stop listening you need to pass a cancellation token. don't use StopListen with ListenAsync.
From the original issue, the author combines these 2 methods and runs it in the loop without awaiting the result. From the screenshot above, apple limits the number of recognition requests.
The difference between StartListen and ListenAsync is that StartListen allows you to continue running your code without waiting for the recognition result.
