### ISSUE TITLE
[BUG] Android: Popup with Grid and ScrollView fills the whole screen

### ISSUE THREAD

**Issue by WMLPB** [CommunityToolkit/Maui#1516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Popup -> Grid -> ScrollView -> StackLayout -> Some Content

The Popup fills the complete screen on Android.

### Expected Behavior

Popup -> Grid -> ScrollView -> StackLayout -> Some Content

The size of the Popup adjusts to the size of the content on Android.

### Steps To Reproduce

The following layout works as expected on version 5.2.0 of the Community Toolkit:

```
<t:Popup>
    <Grid>
        <ScrollView>
            <StackLayout>
                <Image Source="dotnet_bot.png" HeightRequest="200" />
                <Label Text="Hello, World!" HorizontalTextAlignment="Center" />
            </StackLayout>
        </ScrollView>
    </Grid>
</t:Popup>
```

On versions 5.3.0 and 6.0.0 the layout works as expected on smart phones only, but the content gets truncated on tablets. On version 6.1.0 the Popup fills the complete screen on smart phones – I did not test tablets. 

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui

### Environment

```markdown
- .NET MAUI CommunityToolkit: 6.1.0
- OS: Android 9 to 14
- .NET MAUI: 7.0.100
```

**Comment by bijington** [comment]
@WMLPB are you saying that the sample you created works as expected? If so is it possible to work out the difference between the sample and your project to see how the issue could be solved?

**Comment by cat0363** [comment]
The behavior in version 6.1.0 is correct. I have laid out the content page as shown below.

    <ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
        x:Class="MauiComm_VerifyPopupAndroid.MainPage">
        <Grid BackgroundColor="Red">
            <ScrollView>
                <StackLayout>
                    <Image Source="dotnet_bot.png" HeightRequest="200" />
                    <Label Text="Hello, World!" HorizontalTextAlignment="Center" />
                </StackLayout>
            </ScrollView>
        </Grid>
    </ContentPage>

Below is the execution result.

![Screenshot_1699968545](https://github.com/CommunityToolkit/Maui/assets/125236133/3b3c5ba0-62b6-4d60-ab8b-8da03d108283)

It's spread across the entire screen.

@brminnick , what do you think?

There is no change in this movement with the PR for Issue #1486 that I am currently working on.

**Comment by cat0363** [comment]
It is not possible to change the size of the Popup according to the size of the ScrollView's contents.
You must explicitly specify the size of the Popup's content, or you must explicitly specify the size of the Popup.

As an aside, if I keep increasing the size of the Popup as the size of the ScrollView's content increases, the scrolling will stop working.

**Comment by autodotua** [comment]
Same problem on version 6.1.0 or newer. I wrote a class `PopupMenu` to Mimicking Android's PopupMenu, it works well on 6.0.0 but fill the entire screen in 6.1.0 or 7.0.0.
Here's my codes:
```C#
public static async Task<int> PopupMenuAsync(this View view, IEnumerable<PopupMenuItem> items, string title = null)
{
    Popup ppp = new Popup
    {
        Color = Colors.Transparent,
        Anchor = view,
        CanBeDismissedByTappingOutsideOfPopup = true,
    };
    var template = new DataTemplate(() =>
    {
        TextCell tc = new TextCell();
        tc.SetBinding(TextCell.TextProperty, new Binding(nameof(PopupMenuItem.Text)));
        tc.SetBinding(TextCell.DetailProperty, new Binding(nameof(PopupMenuItem.Detail)));
        tc.SetBinding(TextCell.IsEnabledProperty, new Binding(nameof(PopupMenuItem.IsEnabled)));
        tc.SetAppThemeColor(TextCell.TextColorProperty, Colors.Black, Colors.White);
        return tc;
    });
    ListView list = new ListView()
    {
        BackgroundColor = Colors.Transparent,
        SelectionMode = ListViewSelectionMode.None,
        HorizontalOptions = LayoutOptions.Fill,
        ItemsSource = items,
        ItemTemplate = template,
        WidthRequest = 200,
        VerticalOptions=LayoutOptions.Center
    };
    list.ItemTapped += (s, e) =>
    {
        ppp.Close(e.ItemIndex);
    };
    Grid grid = new Grid()
    {
        Margin = new Thickness(8),
    };
    grid.Add(list);
    if (title != null)
    {
        Label titleLabel = new Label()
        {
            Text = title,
            FontSize = 24,
            Margin = new Thickness(8, 0, 0, 0),
            TextColor = Colors.Gray
        };
        grid.AddRowDefinition(new RowDefinition(GridLength.Auto));
        grid.AddRowDefinition(new RowDefinition(8));
        grid.AddRowDefinition(new RowDefinition(new GridLength(1, GridUnitType.Star)));
        grid.Add(titleLabel);
        Grid.SetRow(list, 2);
    }
    Border bd = new Border()
    {
        Content = grid,
        StrokeThickness = 0,
        StrokeShape = new RoundRectangle()
        {
            CornerRadius = new CornerRadius(4)
        },
        Shadow = new Shadow()
        {
            Opacity = 0.6f
        },
    };
    bd.SetAppThemeColor(Border.BackgroundColorProperty, Colors.White, Colors.Black);
    ppp.Content = bd;
    var result = await MainPage.Current.ShowPopupAsync(ppp);
    if (result == null)
    {
        return -1;
    }
    return (int)result;
}

public class PopupMenuItem
{
    public PopupMenuItem()
    {

    }
    public PopupMenuItem(string text)
    {
        Text = text;
    }
    public string Detail { get; set; }
    public bool IsEnabled { get; set; } = true;
    public string Text { get; set; }
    public object Tag { get; set; }
    public static implicit operator PopupMenuItem(string text) => new PopupMenuItem(text);
}
```
This is screenshot in current version:
![image](https://github.com/CommunityToolkit/Maui/assets/26277009/1d09acff-1109-4752-b60b-cfff117738db)

**Comment by bijington** [comment]
I think there might be some misunderstandings based on reading the comments up to this point.

@cat0363 has done some great work fixing bugs around the popup cropping contents and not growing to meet the size of its children. That was done pretty recently and might be the cause in the change in what you are seeing @WMLPB. 

I think the behaviour that you saw in previous versions @WMLPB was actually an artifact of bugs/bad behaviour on Android. 

Please someone correct me if I am wrong but the default behaviour for a Grid will be to size itself to its children and take all available space it can have. This is likely where you are seeing the difference in the later versions of the toolkit.

Moving forward I suspect you might be able to change the behaviour by some of the following:

1. Swap Grid to something else like VerticalStackLayout
2. Set some maximum size information on the Grid
3. Set the Size property on the Popup

**Comment by cat0363** [comment]
Reverting PR #1456 will resolve this issue. Although the label issue reoccurs.
The platform-side Measure method behaves the same as calling it with MeasureSpecMode.Unspecified.
Therefore, if the length of the label's text becomes longer than the popup's width, the text will be displayed without wrapping. Because the parent does not enforce any constraints on the child's size.

At least the behavior will be to ignore the Size specified in Popup.

The original problem was that the platform's Measure method was not called with Maui's LayoutOptions in mind.

To solve the label problem and prevent the screen from expanding, make the following modifications.
However, this does not strictly reflect the LayoutOptions mentioned above, so various problems will remain.

[src\CommunityToolkit.Maui.Core\Views\Popup\PopupExtensions.android.cs]

    static void Measure(AView view, int width, int height, bool isNanWidth, bool isNanHeight, ref bool isRootView)
    {
        if (view is AppCompatTextView)
        {
            var layoutParams = view.LayoutParameters;
            view.Measure(
                MeasureSpec.MakeMeasureSpec(width, (layoutParams?.Width == LinearLayout.LayoutParams.WrapContent && !isNanWidth) ? MeasureSpecMode.Exactly : MeasureSpecMode.Unspecified),
                MeasureSpec.MakeMeasureSpec(height, (layoutParams?.Height == LinearLayout.LayoutParams.WrapContent && !isNanHeight) ? MeasureSpecMode.Exactly : MeasureSpecMode.Unspecified)
            );
        }
        else
        {
            if (!isRootView)
            {
                view.Measure(width, height);
            }
        }

        if (isRootView)
        {
            isRootView = false;
            view.Measure(
                MeasureSpec.MakeMeasureSpec(width, !isNanWidth ? MeasureSpecMode.Exactly : MeasureSpecMode.Unspecified),
                MeasureSpec.MakeMeasureSpec(height, !isNanHeight ? MeasureSpecMode.Exactly : MeasureSpecMode.Unspecified)
            );
        }

        if (view is ViewGroup viewGroup)
        {
            for (int i = 0; i < viewGroup.ChildCount; i++)
            {
                if (viewGroup.GetChildAt(i) is AView childView)
                {
                    Measure(childView, width, height, isNanWidth, isNanHeight, ref isRootView);
                }
            }
        }
    }

@bijington , Thanks for your comment.

**Comment by autodotua** [comment]
> I think there might be some misunderstandings based on reading the comments up to this point.
> 
> @cat0363 has done some great work fixing bugs around the popup cropping contents and not growing to meet the size of its children. That was done pretty recently and might be the cause in the change in what you are seeing @WMLPB.
> 
> I think the behaviour that you saw in previous versions @WMLPB was actually an artifact of bugs/bad behaviour on Android.
> 
> Please someone correct me if I am wrong but the default behaviour for a Grid will be to size itself to its children and take all available space it can have. This is likely where you are seeing the difference in the later versions of the toolkit.
> 
> Moving forward I suspect you might be able to change the behaviour by some of the following:
> 
> 1. Swap Grid to something else like VerticalStackLayout
> 2. Set some maximum size information on the Grid
> 3. Set the Size property on the Popup

I replaced `Grid` with `VerticalStackLayout` , and it seems work well now. Thank you for your advice.

![image](https://github.com/CommunityToolkit/Maui/assets/26277009/8faca7ca-7698-4d23-8993-d2d484fbd36f)
