### ISSUE TITLE
[Proposal] Enhance PopupService to provide a set of Close methods

### ISSUE THREAD

**Issue by bijington** [CommunityToolkit/Maui#1530]
### Feature name

Enhance PopupService to provide a set of Close methods

### Link to discussion

https://github.com/CommunityToolkit/Maui/discussions/1529

### Progress tracker

- [ ] Android Implementation
- [ ] iOS Implementation
- [ ] MacCatalyst Implementation
- [ ] Windows Implementation
- [ ] Tizen Implementation
- [ ] Unit Tests
- [ ] Samples
- [ ] Documentation

### Summary

We now have the ability to Show popups from view models without any view specific knowledge. Now let's take this functionality further and give developers the ability to Close them too.

### Motivation

To make all of our lives easier. Provides symmetry in the PopupService by enabling the ability to close as well as show.

## `IPopupService`

```csharp
public interface IPopupService
{
    // Closes the currently displayed popup. Optionally returning a result.
    void Close(object? result = null);

    // Closes the currently displayed popup.  Optionally returning a result.
    void CloseAsync(object? result = null, CancellationToken cancellationToken = default);
}
```

## `PopupService`

```csharp
public class PopupService
{
    // Might need to be Stack<Popup> or something else in order to track multiple popups being displayed.
    Popup? currentPopup; // Assigned in each of the ShowPopup calls

    // Closes the currently displayed popup. Optionally returning a result.
    public void Close(object? result = null)
    {
        if (currentPopup is null)
        {
            return; // Should we throw?
        }

        currentPopup.Close(result);
    }

    // Closes the currently displayed popup.  Optionally returning a result.
    public void CloseAsync(object? result = null, CancellationToken cancellationToken = default)
    {
        if (currentPopup is null)
        {
            return; // Should we throw?
        }

        return currentPopup.CloseAsync(result, cancellationToken);
    }
}
```

### Usage Syntax

```markdown
// Closing a popup
popupService.ClosePopup();

// Closing a popup with a result
popupService.ClosePopup(result: true);
```

### Drawbacks

Introduces complexity around maintaining the knowledge of displayed popups.

### Unresolved Questions

Do we want to allow for closing based on the view model type? e.g. `PopupService.Close<TViewModel>();`

**Comment by brminnick** [comment]
Since multiple Popups can be displayed concurrently, it'd be best to have the developer specify which popup they'd like to close.

```cs
void ClosePopup<TPopup>(TPopup poup) where TPopup : IPopup;

void ClosePopup <TPopup>(TPopup poup, object? result = null) where TPopup : IPopup;

void ClosePopup <TPopup>(object? result = null) where TPopup : IPopup;

Task ClosePopupAsync<TPopup>(TPopup poup) where TPopup : IPopup;

Task ClosePopupAsync<TPopup>(TPopup poup, object? result = null) where TPopup : IPopup;

Task ClosePopupAsync<TPopup>(object? result = null) where TPopup : IPopup;
```

Maybe not for this Proposal, but I could also see us adding another API in the future that closes all open popups:

```cs
void CloseAllPopups();
Task CloseAllPopupsAsync();
```

**Comment by brminnick** [comment]
> I think we want to avoid the reliance on a developer providing the Popup type as this is view specific information

Yup - that's totally cool with me, because `ClosePopup<TPopup>()` and `ClosePopupAsync<TPopup>()` still accomplish the same objective 💯

**Comment by bijington** [comment]
I've been thinking on this a little more. While developers can show multiple popups they are effectively stacked on top of each other right? As a user is prevented from interacting with a popup below another popup. 

I need to test some of this further but if it is the case then we could store the displayed popups inside a Stack and pop them off each time we close.

**Comment by bobbydharrell** [comment]
I would like to add another request to this, please. Add a way to close the Popups via ViewModel such as `ClosePopup<TViewModel>()` and `ClosePopupAsync<TViewMOdel>()`

**Comment by bobbydharrell** [comment]
Would it also be possible to get a List of open Popups so that we could implement a CloseAll() on our end? Something like PopupService.OpenPopups() and it return a readonly list

**Comment by bobbydharrell** [comment]
@bijington your proposed stack along with closing via ViewModel is exactly what we need, Thank you .. That would solve all of my concerns
