### ISSUE TITLE
[BUG] PositionChanged not being fired after loading local file from C#

### ISSUE THREAD

**Issue by VideoSystems** [CommunityToolkit/Maui#1545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

After specifying a source in the C# backend, the MediaElement no longer reports the position of the video and PositionChanged never fires.

### Expected Behavior

When the video is playing, or the SeekTo() is complete, the PositionChanged method should fire and the correct position of the video player should be reported.

### Steps To Reproduce

Using the CommunityToolkit.Maui.Sample project, remove the Source of the MediaElement control from the XAML.  Use the button to change the Source of the MediaElement to any other element.  The Position no longer updates in the label, and the slider no longer works.
![Screenshot_20231120_130608](https://github.com/CommunityToolkit/Maui/assets/55301280/7d0dd977-8963-44a6-b66c-5d9c9713ff12)

### Link to public reproduction project repository

https://github.com/VideoSystems/repos

### Environment

```markdown
- .NET MAUI CommunityToolkit: 7.0.0, MediaElement: 3.0.0
- OS: Windows 11 Build 22621.2715
- .NET MAUI: 8.0.3
```

### Anything else?

If you specify the source of the MediaElement in the MainPage() method, then the Position works just like specifying in the XAML.

**Comment by VideoSystems** [comment]
Apologies, here's a gihub link to a small example project that highlights the issue:
https://github.com/VideoSystems/repos

**Comment by ne0rrmatrix** [comment]
I have been looking into this. I can confirm with Toolkit sample. If you switch sources position tracking stops working.  Not an issue for windows. For android changing sources causes position tracking to break. But duration works fine. On IOS both position and duration are not working when you switch sources. This is tested against main.

**Comment by ne0rrmatrix** [comment]
Another note using sample app and selecting any item in source menu will have same effect. So both xaml and code behind will result in position not being tracked. It only works once. This does not affect windows at all. IOS, android both affected. Was unable to test on Mac with sample app. On mac the sample app menu for source fails to load. The issue with menu appears to an issue with Microsoft.Maui.Controls and nothing to do with position bug.

**Comment by zabanet** [comment]
Hi, I can confirm that after upgrading my MediaElement from version 2 to 3 the problem with Position not being updated appeared on Android. Also  PositionChanged is not being fired up. No problem on Windows though. Hopefully, this can be solved quickly as there are no alternative media players for MAUI. There is an option to revert to version 2, but this is not the direction we should sail, right?

**Comment by ne0rrmatrix** [comment]
Can someone mark this as open and not close it till my PR gets reviewed please? @pictos ?

**Comment by pictos** [comment]
@ne0rrmatrix which issue are you talking about? This one remains opened

**Comment by ne0rrmatrix** [comment]
@pictos it was updated a few minutes after I made that comment by @brminnick to keep it open.

**Comment by VideoSystems** [comment]
This is my first post on GitHub, not sure if I'm required to take further action to progress this issue, but am happy to do whatever needed in terms of review or updates to get this solved.  

@ne0rrmatrix , I see that you've made the edits to the code to get the Position working again.  I'm using NuGet to get the MediaElement, do I simply need to wait until the next release to get the updated code in my project?  Is there a different way I can/need to get the updates?

**Comment by ne0rrmatrix** [comment]
@VideoSystems welcome to the community. If you want you can download the PR and build it yourself and see if it fixes your issue. If you are not comfortable building the project yourself it will be out soon. I am waiting on a maintainer to look at it and verify that the code I submitted meets the code standards and does what it is supposed to. I imagine by the end of this week or early next week it should be merge to main. Fingers crossed. 

You can also look at [https://github.com/CommunityToolkit/Maui/wiki/Preview-Packages](https://github.com/CommunityToolkit/Maui/wiki/Preview-Packages) and learn more about how to use Pull requests as a nuget.
There are two feeds on that page from azure. Latest which is the main feed. The pull request feed is the one where you can grab this PR.

**Comment by VideoSystems** [comment]
Fantastic!  Thanks for the information!  😁

**Comment by yureng** [comment]
I'm having the same issue. 
@ne0rrmatrix  Thanks for the fix and hopefully the NuGet update will be released soon

**Comment by DamianMehers** [comment]
I've hit the same issue - is it really unverified?  Can we remove that tag?

**Comment by VideoSystems** [comment]
It seems that @ne0rrmatrix was able to verify the issue and created a fix for it.  Not sure how to get the tag changed though. 
 Anxiously awaiting the new release with the fix!
