### ISSUE TITLE
[BUG] AnimationBehavior - AnimateCommand does not have an accessible setter

### ISSUE THREAD

**Issue by OvrBtn** [CommunityToolkit/Maui#1572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

According to [https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/behaviors/animation-behavior](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/behaviors/animation-behavior) the AnimationCommand property can be used to trigger the animation in code. But trying to set the value in XAML the compilator is throwing error, in my project it's "AnimateCommand does not have an accessible setter", as below:
![image](https://github.com/CommunityToolkit/Maui/assets/76904408/d41600c6-619e-4618-aee5-aa94dcdf2ee8)

In both project's it's not even showing such property in XAML:
![image](https://github.com/CommunityToolkit/Maui/assets/76904408/e0e35943-b132-4b13-a0c1-149dd87b952b)

### Expected Behavior

I should be able to set the AnimationCommand to trigger animation from ViewModel.

### Steps To Reproduce

1. Open repo project
2. Go to MainPage.xaml
3. Try setting AnimationCommand in AnimationBehavior

### Link to public reproduction project repository

https://github.com/OvrBtn/AnimationBehaviorBugReport

### Environment

```markdown
- .NET MAUI CommunityToolkit: 6.1.0 in repo, 6.0.0 in my personal project
- OS: Windows 10 build 10.0.19045
- .NET MAUI: not sure how to check the exact version but both repo and my project target .NET 7 and running dotnet workload list is returning:
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui-android               8.0.3/8.0.100          SDK 8.0.100
```

### Anything else?

I checked this issue on project targeting .NET 8 and with .NET MAUI CommunityToolkit version 7.0.0 and it's the same.
I also looked at the implementation of AnimationBehavior and it seems like the BindableProperty is being created as ReadOnly
![image](https://github.com/CommunityToolkit/Maui/assets/76904408/1e48d5dd-c95b-4b96-a72e-ba042d9c4147)

**Comment by bijington** [comment]
@OvrBtn Thanks for the report. I will try and take a look at it this week. I suspect we may have missed a detail when migrating from the Xamarin Community Toolkit if it is an issue. What you have provided is what I expect to work so it is likely a bug.

**Comment by bijington** [comment]
@OvrBtn so it looks like this isn't an issue and the code is working as intended. `AnimateCommand` is designed to be read-only and comes with a `BindingMode` of `OneWayToSource` meaning that the property in your source (most likely view model) will  be updated to the value created in the `AnimationBehavior`. 

I have updated our sample application in #1577 to show how this can be done. And it does mostly match the details on our docs page at: https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/behaviors/animation-behavior#programmatically-triggering-the-animation

I did notice however that we need to pass in a `CancellationToken` now rather than `null` when calling `Execute` otherwise the command won't be triggered.

**Comment by OvrBtn** [comment]
@bijington Hmm, I tried just using it ignoring what VS was saying and it worked, also after compilation the error about not having accessible setter disappeared. Still strange that such property is not suggested in XAML while typing but anyway thanks and sorry for the trouble 😁
