### ISSUE TITLE
[BUG] Controls in Popup have layout issues since .NET 8 / MAUI 8 (Android)

### ISSUE THREAD

**Issue by tschramme86** [CommunityToolkit/Maui#1575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Since upgrading my project from MAUI 7 to 8, the functionality of the MCT Popup View on Android is somehow broken. A lot of 3rd party controls (not only MCT controls) inside the Popup now have rendering problems, e.g. it looks like their own default style is not fully applied, sometimes text is not properly rendered, etc.

For the sake of simplicity for this bug report, I created a minimal reproducible example just with MCT controls:
- When the `AvatarView` is put on a normal `ContentPage` it is displayed as expected
- When the same `AvatarView` is put in a `Popup` view, the inner text is misplaced

`<toolkit:AvatarView Text="AB" />`

In normal Page:
![image](https://github.com/CommunityToolkit/Maui/assets/54247971/c6f51a85-7ef7-46f7-9e46-f78e642c116d)

In Popup - inner text is aligned top, not centered:
![image](https://github.com/CommunityToolkit/Maui/assets/54247971/75e98789-2710-4187-92c6-463275a25e57)

### Expected Behavior

No layouting/styling issues of controls inside a `Popup` view, e.g. initials are properly centered in the popup of the provided example project.

### Steps To Reproduce

1. Open and run the provided sample project on Android
2. Observe on the main page that the `AvatarView` looks as expected
3. Click the "Open Popup" button
4. See that the same `AvatarView` in the popup has a misplaced text

### Link to public reproduction project repository

https://github.com/tschramme86/BugCTPopupNet8

### Environment

```markdown
- .NET MAUI CommunityToolkit: 7.0.0
- OS: Android 33
- .NET MAUI: 8.0.3
```

### Anything else?

Just to emphasis again: This bug report is not about the `AvatarView` itself. I encounter also rendering/styling problems with other controls that I put into a `Popup` view, since I upgraded my project to .NET8/MAUI8. I just picked the `AvatarView` as an example to demonstrate a general problem with the `Popup` since the upgrade.

What I can see so far is that it only affects Android. When running as Windows App there are no such problems, and on iOS I'm not able to test.

**Comment by yureng** [comment]
I have the similar issue: 

On Android,  the Label  in Popup doesn't wrap automatically; 
Windows doesn't have this problem.

**Comment by tataelm** [comment]
I also have this problem since .net 8. I was using <Frame> as root to have rounded corners. Anything inside Frame is not visible anymore. Also label wrap stopped working as @yureng said.

**Comment by imsam67** [comment]
In my case, the label isn't rendering the text inside the Popup. This is definitely new with .NET 8

**Comment by bijington** [comment]
What version of the toolkit did you upgrade from when updating to support .NET 8? 

I ask because there have been a number of changes in the Popup over the releases before we shipped v7 with .NET 8 support.

Changes like adding styling support to Popups, fixing layout issues.

**Comment by imsam67** [comment]
I went back to my repo history to get the info you were asking for. Looks like on Sep 7, I upgraded my app to the latest version of .NET 8 RC and the version of `CommunityToolkit.Maui` at the time shows as `5.3.0`. I'm 95% sure this issue did not exist at the time.

Prior to upgrading to .NET 8 RC, the app was targeting the lastest version of .NET 7 available at the time and the `CommunityToolkit.Maui` was still `5.3.0`.

Today, the app targets .NET 8.0.100 and it uses `CommunityToolkit.Maui` version `7.0.0`.

The strange thing in my particular case is that I do use `Popup` quite a bit in my app and I don't have this issue in every single one of them. I actually discovered this as I was typing this response. In one particular `Popup` where I have this issue, I use `Label` within a `CollectionView`. By accident I discovered that even though none of the text are rendered, if I scroll up and down, they actually do appear -- see video below:

https://github.com/CommunityToolkit/Maui/assets/15844030/7c50e4a0-39b2-43aa-8467-d2d951613e77

However, in yet another `Popup`, as you can see in the image below, none of the text is rendered and in this case, I have no way of scrolling to re-render elements so I'm completely out of luch on this one. What you're supposed to see is `Label`'s to both right and left of `Switch` controls -- see below:

![Screenshot 2023-12-01 125607](https://github.com/CommunityToolkit/Maui/assets/15844030/b9fa16eb-8b0d-4add-82ad-0e13bf1ebf5a)

I've reported another issue with text color which feels very similar to this issue and I wonder if they're related. Here's that issue: https://github.com/dotnet/maui/issues/17818

Interestingly, that issue points to another text color issue that I'd reported here: https://github.com/dotnet/maui/issues/17413

Hope this helps troubleshoot the problem. Thanks!

**Comment by tschramme86** [comment]
@bijington I also was on MCT v5.3.0 + .NET 7/MAUI 7 when everything worked fine (if you can say so for MAUI ;-) ).

But please also check the Repo I provided in the ticket. It's just a brand new MAUI 8 app created with the latest template + installed MCT v7.0 package + put the AvatarView onto the page and into a Popup. Nothing fancy. And still, on the page it's rendered as expected but in the Popup it's broken.

So maybe there is something wrong with the Popup control, maybe it's a bug of MAUI 8 itself - I don't know.

And please, don't get me wrong - I don't want to blame anybody here for this, despite I see a lot of heated discussions about the overall quality of the MAUI 8 release. As you pointed out, there have been changes in the Popup behaviour in the last versions, and maybe also the MAUI layouting/rendering changed with v8. So if there is something that I need to change/add in my code to make it work, that would be perfectly fine - but then I have to know this. Right now the documentation isn't of any help here.
As of now it looks to me like a severe bug. And despite it comes with the Popup view why I opened the ticket here, I'm a little bit in fear that it's actually a bug in MAUI itself and will take ages to get fixed.

Let me know if you need more information/I can help in any way. Looking forward to your investigation of this.

**Comment by vhugogarcia** [comment]
This issue has been fixed using the latest version of .NET MAUI 8.0.70 and .NET MAUI community toolkit 9.0.2. I'm closing this issue. I also tested another controls such as labels, entries, button, and picker. 

![Screenshot_1721682060](https://github.com/user-attachments/assets/604b5593-3a94-43fc-b494-744589be829f)
