### ISSUE TITLE
[BUG] Popup doesn't work on Android when there is a surrounding Frame element. It works well on Windows.

### ISSUE THREAD

**Issue by GerhardMauerberger** [CommunityToolkit/Maui#1585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

A Popup with a surrounding Frame element does not work on Android. It works well on Windows. 
On Android the correct size of the Popup and the correct background color is visible but none of the controls. The Popup is completly empty. 

### Expected Behavior

On Windows it works as I expect it to. You can even use padding and nice rounded corners.

### Steps To Reproduce

1. Open und run the attached GitHup project.
2. Use an Adroid device and run PopupWithFrame
3. Click on the button of MainPage to see the empty Popup.

### Link to public reproduction project repository

https:://github.com/GerhardMauerberger/PopupWithFrame.git

### Environment

```markdown
- .NET MAUI CommunityToolkit:7.0.0
- OS: Android 10.0 - API 29
- .NET MAUI: 8.0
```

**Comment by cat0363** [comment]
Are the following related?
https://github.com/dotnet/maui/issues/18526

**Comment by vhugogarcia** [comment]
I have tested the sample app provided on this issue, and it is fixed using the latest version of .NET MAUI Community Toolkit 9.0.2 and .NET MAUI 8.0.70. I'm closing this issue.

![Screenshot_1721682954](https://github.com/user-attachments/assets/c3d6e3d0-7a4d-4e50-a73f-1f4ba1b74765)
