### ISSUE TITLE
[BUG] SpeechToText ListenAsync doesn't stop on silence on iOS

### ISSUE THREAD

**Issue by AncientLust** [CommunityToolkit/Maui#1586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Once `LystenAsync` started on iOS, it doesn't end automatically after some time of silence. And can be stopped only by `StopListenAsync` call. Based on this [thread](https://github.com/CommunityToolkit/Maui/issues/1515) this is not by design. 

### Expected Behavior

Once `LystenAsync` started on iOS, it should end automatically after some time of silence. 

### Steps To Reproduce

1. Open Essentials\SpeechToText.
2. Hit ListenAsync, and say some words. After your first word is recognized, you will see the popup "State changed: Stopped". Probably requires attention, because recognition actually continues until you press `Cancel token`.
3. Hit Cancel Token. Recognized text will be erased.

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui/tree/main/samples

### Environment

```markdown
- iOS: 17.1.1 iPhone 15
- .NET MAUI: 8.0.100
```

**Comment by VladislavAntonyuk** [comment]
According to this presentation at the WWDC2019, On-device has no limits. Your device (iPhone 15 uses on-device recognition). Also on Windows we have an infinite timeout, so on iOS on unsupported devices, your request should be declined after 1 minute.

https://developer.apple.com/videos/play/wwdc2019/256/

![](https://i.stack.imgur.com/StMTe.png)
