### ISSUE TITLE
[BUG] [Andriod][FileSaver] Crash when removing USB drive

### ISSUE THREAD

**Issue by BaY1251** [CommunityToolkit/Maui#1588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Crash when removing USB drive in Android7.1 after save a file.
No Exception was throw.

### Expected Behavior

File save Normally

### Steps To Reproduce

1. Open Toolkit\ Toolkit.sln
2. Click 'FileSaver' to save a file to USB drive
3. remove USB drive

### Link to public reproduction project repository

https://github.com/BaY1251/MauiDebug.git

### Environment

```markdown
- .NET MAUI CommunityToolkit:7.0.0
- OS:Android7.1
- .NET MAUI:8.0
```

### Anything else?

![FileSaver](https://github.com/CommunityToolkit/Maui/assets/48309205/b3a1343f-0223-43cb-b2dd-630487d2d962)

adb log here 
"app died" in line 454
[file.log](https://github.com/CommunityToolkit/Maui/files/13543038/file.log)

**Comment by BaY1251** [comment]
another Bug is report "Unable to resolve absolute path where the file was saved 'content://com.android.providers.downloads.documents/document/66'",
when save to the Internal storage.

**Comment by BaY1251** [comment]
@bijington Not really! From Gif, it appears that the 'SaveAsync' method has returned and IsSuccessful==true!
Besides, I even tried to wait for ten minutes before unplugging the USB drive

**Comment by bijington** [comment]
@BaY1251 thanks for the clarification

**Comment by BaY1251** [comment]
have you try the repository?

**Comment by BaY1251** [comment]
I wrote the wrong solution name,Sorry for the mistake. 
it is `Toolkit\ Toolkit.sln`.

**Comment by BaY1251** [comment]
This issue may need to be reopened, #1751 is invalid for #1588

**Comment by VladislavAntonyuk** [comment]
I am not to reproduce the issue after the fix.

From docs:
An OutputStream you can create on a ParcelFileDescriptor, which will take care of calling ParcelFileDescriptor#close ParcelFileDescriptor.close() for you when the stream is closed.

Stream is closed on Dispose.

**Comment by BaY1251** [comment]
`Dispose()` did not close the file.

![Close](https://github.com/CommunityToolkit/Maui/assets/48309205/ac84fd17-6d35-490a-a1e4-2dc2a79600db)
![Dispose](https://github.com/CommunityToolkit/Maui/assets/48309205/ac5bd148-5c4c-4b96-bd6b-3f63b88ede21)

**Comment by VladislavAntonyuk** [comment]
On screenshot you provide, Dispose is not called yet

**Comment by BaY1251** [comment]
The first image shows FD closing after calling Close.
The second image shows that FD is still open after calling Dispose.

I am unable to view the source code of AutoCloseOutputStream. If you can see the source code, it would be best to confirm that 
> Stream is closed on Dispose


I confirm that AutoCloseOutputStream is invalid for all my existing devices.
You'd better test a few more Android devices and USB drives.

**Comment by BaY1251** [comment]
复现问题的log和相关截屏我已经都提交了,#1751并没有解决问题,也没有改变log. 
如果没有更多的人能复现这个问题,那这个问题应该就不是问题.可能大概只是我的问题吧.
