### ISSUE TITLE
[BUG] Bindable property for IconTintBehavior isnt working

### ISSUE THREAD

**Issue by VictorHFerreira** [CommunityToolkit/Maui#1599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When setting tint color from icon tint behavior via binding, the icon's color isn't changing.

### Expected Behavior

When binding a property, and changing the value of this property, the icon's color should change

### Steps To Reproduce

In this scenario I'm using a CollectionView, items source is a list of items that has diferent icon colors.

1. Implement the binding on datatemplate on collection view
![image](https://github.com/CommunityToolkit/Maui/assets/45387530/3982047d-aa3a-4922-b1e6-a5d675bf8d84)
2. Fill the value on the view model
![image](https://github.com/CommunityToolkit/Maui/assets/45387530/eb9ac5c4-233b-4edf-bfc7-5dfcb7051257)
Note that the icon didn't get red
![image](https://github.com/CommunityToolkit/Maui/assets/45387530/27c382d1-2a96-4e0a-b8a8-0efe335bc75e)
3. Change the value in runtime selecting an item from the collection view
Note that the item didn't get white
![image](https://github.com/CommunityToolkit/Maui/assets/45387530/d7d50d7a-c94c-4d13-b06f-b3c68c4f8669)

### Link to public reproduction project repository

-

### Environment

```markdown
- .NET MAUI CommunityToolkit: 6.1.0
- OS: Windows,iOS, Android
- .NET MAUI: .NET 7
```

**Comment by brminnick** [comment]
You must manually set the BindingContext for every Behavior in .NET MAUI

https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/behaviors?view=net-maui-8.0

![image](https://github.com/CommunityToolkit/Maui/assets/13558917/042cee8c-08a5-40fa-b424-83e77f5780e9)

**Comment by VictorHFerreira** [comment]
> You must manually set the BindingContext for every Behavior in .NET MAUI
> 
> https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/behaviors?view=net-maui-8.0
> 
> ![image](https://private-user-images.githubusercontent.com/13558917/289954502-042cee8c-08a5-40fa-b424-83e77f5780e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MDQxNjYsIm5iZiI6MTcwMjQwMzg2NiwicGF0aCI6Ii8xMzU1ODkxNy8yODk5NTQ1MDItMDQyY2VlOGMtMDhhNS00MGZhLWI0MjQtODNlNzdmNTc4MGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE3NTc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlOTgyMjc2ZTA4ZjM1MmUxMjQ4YzBkMjA3NTZmN2E4ODA1MGRiMGNhMDUwZTEyMjhhNzNiOGVjYzc0YmM2YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6StYzA4sXIYar6mSu1J2ZAzPlgdpLLQs7H6YXNg0aA4)

Even setting the binding context, it doens't change the colors

![image](https://github.com/CommunityToolkit/Maui/assets/45387530/f61793ca-d390-4498-aa82-bb1e5e728ea0)

**Comment by bijington** [comment]
@VictorHFerreira without sharing a reproduction sample it would extremely difficult to assist. One initial check I would suggest is to make sure that `BindingContext` from your screenshot is not null. The better approach would be to bind the behaviors `BindingContextProperty` to `BindingContext`.
