### ISSUE TITLE
[BUG] AvatarView not showing if inside a Frame on Android, work on Windows, iOS, macOS

### ISSUE THREAD

**Issue by smardine** [CommunityToolkit/Maui#1600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When an avatarView is "alone", it show without problem on Windows, Android, iOS.
The problem is when the avatarview is within a Frame, it show on Windows, iOS and macOS, but not in Android

| Android | iOS |macOS | Windows |
|--|--|--|--|
|![avatarview android](https://github.com/CommunityToolkit/Maui/assets/13467840/0a4ba836-9202-4b1c-b2f6-8ca0af94ec64) | ![avatarview ios](https://github.com/CommunityToolkit/Maui/assets/13467840/e11e5d62-035d-466f-838f-d965c65fc734) | ![avatarview macos](https://github.com/CommunityToolkit/Maui/assets/13467840/ab63573b-d485-41f9-a623-65d0f18ff3c1) | ![avatarview windows](https://github.com/CommunityToolkit/Maui/assets/13467840/52240b46-bf51-4c02-ada5-e185a33f06ce)|

### Expected Behavior

The avatarView should show in Android too.

### Steps To Reproduce

Open and run the attached GitHub project.
Use an Android device and run MAUIApp4
Observe that the avatar view is not showing on android, when inside a Frame

### Link to public reproduction project repository

https://github.com/smardine/AvatarViewWithFrame.git

### Environment

```markdown
- .NET MAUI CommunityToolkit: 7.0.0
- OS: Android API 33 and 34 (13 and 14)
- .NET MAUI: 8.0.100
```

### Anything else?
It start acting like that since i migrate from .net7 to net8
I use to use Frame to have a CornerRadius.
If i use a Border instead of the Frame, the avatar view is showing on android without problem
from
```
<Frame BackgroundColor="Yellow" BorderColor="Red" CornerRadius="10">
    <Grid RowDefinitions="*,*">
        <Label Text="child label" />
        <mct:AvatarView
            Grid.Row="1"
            HeightRequest="64"
            ImageSource="https://aka.ms/campus.jpg"
            WidthRequest="64" />
    </Grid>
</Frame>
```
to 
```
<Border
    BackgroundColor="Yellow"
    Stroke="Red"
    StrokeShape="RoundRectangle 10">
    <Grid RowDefinitions="*,*">
        <Label Text="child label" />
        <mct:AvatarView
            Grid.Row="1"
            HeightRequest="64"
            ImageSource="https://aka.ms/campus.jpg"
            WidthRequest="64" />
    </Grid>
</Border>
```

it could be related to :

- [[BUG] Controls in Popup have layout issues since .NET 8 / MAUI 8 (Android) #1575](https://github.com/CommunityToolkit/Maui/issues/1575)
- [[BUG] Popup doesn't work on Android when there is a surrounding Frame element. It works well on Windows. #1585](https://github.com/CommunityToolkit/Maui/issues/1585)

The repro sample is based on new MAUI App .net8 project in Visual studio 2022.
I have tried with some nightly build from https://pkgs.dev.azure.com/xamarin/public/_packaging/maui-nightly/nuget/v3/index.json with no succes

**Comment by VladislavAntonyuk** [comment]
Don't use Frame, it's an obsolete control. Use border instead

**Comment by smardine** [comment]
> Don't use Frame, it's an obsolete control. Use border instead

Do you know if there IS a way to add shadow effect to a border?

**Comment by bijington** [comment]
You can add a shadow to pretty much anything these days: https://learn.microsoft.com/en-us/dotnet/maui/user-interface/shadow?view=net-maui-8.0

**Comment by smardine** [comment]
Thanks for the tips.
So the answer is : that's probably a bug but as this component is obsolete, prefer using a border.
Thanks for your help
