### ISSUE TITLE
[BUG] FolderPicker doesn't work on Android 13 - the picked directory is inaccessible

### ISSUE THREAD

**Issue by nanonya** [CommunityToolkit/Maui#1601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

After using FilePicker, the permission to access the directory doesn't seem to be fully granted.
For example, `Directory.EnumerateFiles(folderResult.Folder.Path).Count();` always gets 0; and the `Android.Webkit.WebView.SaveWebArchive` method can't save MHTML to picked directory.

(Also, if this problem can be solved, I wonder if the application can persist the access permission after a restart).

### Expected Behavior

The directory should be accessed with methods from `System.IO` (and other methods) correctly.

### Steps To Reproduce

This issue can be reproduced with the official sample application.
1. Compile and run CommunityToolkit.Maui.Sample on Android platform.
2. Choose Menu -> Essentials -> FolderPicker.
3. Click any button, and pick any folder with files in it.
4. The toast always says "Files count - 0".

![screen-20231129-014606 1 mp4_snapshot_00 23_ 2023 11 29_01 59 23](https://github.com/CommunityToolkit/Maui/assets/25922295/7f061025-f974-41cb-9d6f-56b2ded58aa0)
![screen-20231129-014606 1 mp4_snapshot_00 24_ 2023 11 29_01 58 56](https://github.com/CommunityToolkit/Maui/assets/25922295/0c99b2d7-5692-4f30-8aa2-b653101ca57f)

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui/tree/main/samples

### Environment

```markdown
- .NET MAUI CommunityToolkit: 7.0.0
- OS: Android 13
- .NET MAUI: 8.0
```

**Comment by VladislavAntonyuk** [comment]
System.IO doesn't work. You need to use Android API to work with file system.

**Comment by nanonya** [comment]
> System.IO doesn't work in cross platform applications with the whole file system. It only works with specific folders (AppData, etc - you can find more in documentation). You need to use Android API to work with file system. To save files use FileSaver.

I get it now, thank you.
