### ISSUE TITLE
[BUG] Unable to Save Multi GB Files using FileSaver on Android

### ISSUE THREAD

**Issue by DavidJSnyder** [CommunityToolkit/Maui#1605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I am unable to save 2GB+ files/streams using FileSaver on Android.  The attempt returns an error message of "Stream too long" even when there is enough space to write the file.  It also leaves behind a 0 byte file in the target directory.  I think this would be possible if the Android implementation wrote the contents of the stream in chunks rather than attempting to load it into an array in memory as it currently does.

### Expected Behavior

I would expect FileSaver to be able to handle a file that large when there is sufficient space on the Android instance (such as in the Windows Subsystem for Android.)  This would also eliminate the 0 byte file.

### Steps To Reproduce

1.  Open the solution from the reproduction directory.  Make sure is target an Android instance that has space to write 4 GB+ such as the Windows Subsystem for Android and run the project.
2.  Click the Button and select a target directory such as Download.
3. Note that the call to FileSaver fails with the message "Stream too long."  Check the contents of the directory you selected and notice the 0 byte file left behind.

### Link to public reproduction project repository

https://github.com/DavidJSnyder/NETMAUIBigFileSaveExample

### Environment

```markdown
- .NET MAUI CommunityToolkit: 7.0.1
- OS: Windows 11 22H2 Build 22621.2861
- .NET MAUI: 8.0.3/8.0.100
- Windows Subsystem for Android: 2310.4000.2.0
```

### Anything else?

I previously opened a discussion for this issue at https://github.com/CommunityToolkit/Maui/discussions/1554 and was asked to open a bug report.

**Comment by Eel2000** [comment]
Hi. I think that  you need to add the permission android.permission.WRITE_EXTERNAL_STORAGE in your AndroidManifest.xml
