### ISSUE TITLE
[BUG] Expander resizing preventing user swiping to next item in carousel

### ISSUE THREAD

**Issue by MPearson14** [CommunityToolkit/Maui#1609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

**Context**
I have a CarouselView with two steps. In the first step, there is an Expander control which contains an Editor control with AutoSize="TextChanges". Given that the user is focused on the Editor control and swipes to the next step in the Carousel, the app will update a property of another control within the Expander in the first step. This will cause the other control's visibility to change. When the focus is on the Editor control, the app does not display the second step but instead flicks back and forth between the first and second step in the carousel. This does not happen if any other control has focus.

**Actual Result**
The app switches back and forth between the first and second steps in the carousel.

### Expected Behavior

The next step in the carousel is displayed.

### Steps To Reproduce

1. Build and deploy the project from the repository below.
2. In the app, tap on the button "Go to Expander page".
3. Tap on the Editor with placeholder "Entry 2". The Editor now has focus.
4. Swipe to the next step in the carousel.

### Link to public reproduction project repository

https://github.com/MPearson14/MauiExpander

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS:
- .NET MAUI:
```

**Comment by vhugogarcia** [comment]
The issue has been fixed on the latest version 9.02 and .NET MAUI 8.0.70. Find attached a video sample. 

I'm closing this issue. We can re-open it again if the issue appears again.

https://github.com/user-attachments/assets/113dab73-3545-482f-961f-adcc4870a9f9
