### ISSUE TITLE
[BUG] MauiWinUIApplication resources not set in Popup

### ISSUE THREAD

**Issue by nuxosio** [CommunityToolkit/Maui#1620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I'm styling my Pickers as described here:
https://github.com/dotnet/maui/issues/13418
``` 
   <maui:MauiWinUIApplication.Resources>
        <SolidColorBrush x:Key="ComboBoxItemForegroundPointerOver" Color="LightGreen" /> 
        <SolidColorBrush x:Key="ComboBoxDropDownBackground" Color="#444444" />
        <SolidColorBrush x:Key="ComboBoxItemForeground" Color="White" />
        <SolidColorBrush x:Key="ComboBoxForegroundPointerOver" Color="White" />
        <SolidColorBrush x:Key="ComboBoxItemForegroundSelected" Color="White" />
        <SolidColorBrush x:Key="ComboBoxItemForegroundSelectedPointerOver" Color="LightGreen" />
        <SolidColorBrush x:Key="ComboBoxItemForegroundPressed" Color="Yellow" />
        <SolidColorBrush x:Key="ComboBoxForegroundPressed" Color="White" />
        <SolidColorBrush x:Key="ComboBoxItemForegroundSelectedPressed" Color="LightGreen" />
        <SolidColorBrush x:Key="ComboBoxItemBackgroundSelected" Color="#777777" />
        <SolidColorBrush x:Key="ComboBoxItemBackgroundSelectedPointerOver" Color="#777777" />
        <SolidColorBrush x:Key="ComboBoxItemBackgroundSelectedPressed" Color="#777777" />

    </maui:MauiWinUIApplication.Resources>
```
The pickers get the style when I use them in a ContentPage but not in a Popup

### Expected Behavior

Pickers used in my Popup should have the color brushes set in MauiWinUIApplication but they don't. If I use the pickers in any other place other than the popup, it works.

### Steps To Reproduce

1. Copy the resources into your file Platforms/Windows/App.xml
2. In a content page, add a Picker. It has the color brushes
3. In a Popup, add a Picker. It does not have the color brushes

if you check in my reproduction you will see a picker in the mainPage with green color while hovering. If you open the popup, the same Picker is there but the green color is not seen anymore

### Link to public reproduction project repository

https://github.com/nuxosio/maui-pickers-popup

### Environment

```markdown
- .NET MAUI CommunityToolkit: 6.1.0
- OS: windows10.0.19041.0
- .NET MAUI: net7.0
```

**Comment by cat0363** [comment]
I'm getting a lot of errors in Platforms/Windows/App.xml.

<img width="1128" src="https://github.com/CommunityToolkit/Maui/assets/125236133/11f1e2e4-259d-4c66-a514-6919b3a85fb9">

**Comment by nuxosio** [comment]
@cat0363 thanks for your answer, I pushed a new commit using HEX color instead of named colors. Also, please select net7.0-windows10.0.19041.0 instead net7.0-android in your IDE, that's why it's showing the errors.

**Comment by nuxosio** [comment]
It was reproduced by one Microsoft vendor in MAUI Q&A
https://learn.microsoft.com/en-us/answers/questions/1475070/picker-used-in-popup-not-inheriting-color-brushes

_ToolKit:Popup corresponds to the Microsoft.UI.Xaml.Controls.Primitives.Popup control in WinUI3, and after testing, this issue does not occur in WinUI3 native Popup. Therefore, this issue should be specific to ToolKit:Pupop._

any idea how to solve it?

**Comment by bijington** [comment]
@cat0363 do you think we need to add something to our Popup code to load the resources from this MauiUiApplication?

**Comment by cat0363** [comment]
@bijington , Below are the verification results using MAUI's .NET 8 version and Community Toolkit version 7.0.1.
Is the expected result something like the video?

https://github.com/CommunityToolkit/Maui/assets/125236133/e2a7a50e-ce4a-4c8d-9cdd-ae899571e695

If the above is the expected result, please use .NET 8 version of MAUI and Community Toolkit Version 7.0.1.
I haven't modified the source code.

**Comment by bijington** [comment]
Amazing work @cat0363! @nuxosio Are you able to confirm the behaviour in the video above is what you expect?

**Comment by nuxosio** [comment]
Excellent @cat0363, thank you so much for your support! @bijington I can confirm the issue is solved in NET 8

**Comment by bijington** [comment]
Thanks for confirming. I will close this issue down the
