### ISSUE TITLE
[BUG] The background color of the <toolkit:DrawingView> control in the .NET MAUI Community Toolkit is consistently shown as gray, impacting the appearance of the signature image.

### ISSUE THREAD

**Issue by vplife1** [CommunityToolkit/Maui#1624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

The background of the signature image is consistently shown as gray.

### Expected Behavior

The background of the signature image should be transparent or white, providing a clean appearance.

### Steps To Reproduce

1. Use the <toolkit:DrawingView> control as a signature pad.
2. Draw a signature.
3. Observe that the background of the signature image is shown as gray.

### Link to public reproduction project repository

https://github.com/jfversluis/MauiDrawingViewSample

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS:
- .NET MAUI:
- .NET MAUI Community Toolkit Version: [e.g., v7.0.0]
- .NET MAUI Version: [e.g., v8.0.0]
- Platform: [e.g., Android, iOS]
```

**Comment by VladislavAntonyuk** [comment]
That is because you set the background color to "LightGray". You can set any color you like.
