### ISSUE TITLE
[BUG]  Blazor Hybrid white gap/field below status bar

### ISSUE THREAD

**Issue by nathanjeynes** [CommunityToolkit/Maui#1639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

An out of the box .net 8 maui blazor project, when setting the status bar color either via iOS platform or using .net MAUI toolkit there is a white gap between the blazor webview and the status bar.

Other similar issues have been closed as fixed and therefore wont allow any further comments.  This appears to be an issue in .NET 8 

![WhatsApp Image 2024-01-08 at 18 09 37_17b3c2dd](https://github.com/CommunityToolkit/Maui/assets/7514086/14d03911-e23e-4966-ad97-9e0c715da25d)

### Expected Behavior

No white gap to be present like android.

### Steps To Reproduce

- Create a new .net 8 Maui Blazor App
- Install .Net Maui Toolkit
- Add the following to the content page
  <ContentPage.Behaviors>
      <toolkit:StatusBarBehavior StatusBarColor="Red" StatusBarStyle="LightContent">
      </toolkit:StatusBarBehavior>
  </ContentPage.Behaviors>
  
  

### Link to public reproduction project repository

https://github.com/nathanjeynes/ExampleMauiStatusBarBug

### Environment

```markdown
- .NET MAUI CommunityToolkit: 7.0.1
- .NET MAUI: 8.0.3
- OS: Win 10 Version 10.0.22631 Build 22631
```

### Anything else?

- https://github.com/dotnet/maui/issues/11611
- https://github.com/CommunityToolkit/Maui/issues/762

**Comment by nathanjeynes** [comment]
After some thought I believe this may be a MAUI issue and not the toolkit, have created it at https://github.com/dotnet/maui/issues/19778

**Comment by vhugogarcia** [comment]
Thanks @nathanjeynes for the feedback. This is in needed a .NET MAUI issue, it can be followed here as you mentioned it: https://github.com/dotnet/maui/issues/19778

I'm closing this ticket.
