### ISSUE TITLE
[BUG] Application crashes under Windows when running in desktop mode

### ISSUE THREAD

**Issue by pgrawehr** [CommunityToolkit/Maui#1649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Open the CommunityToolkit.Samples solution and add this line to the csproj to run in Windows desktop mode (not in store mode):

```
<WindowsPackageType Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">None</WindowsPackageType>
```
also change the `commandName` in `launchsettings.json` to `"Project"`. Then run the project and try out the "Snackbar" and "ToastBar" examples. 

The application crashes with some low-level error.

### Expected Behavior

A notification window is shown

### Steps To Reproduce

See above

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui/

### Environment

```markdown
- .NET MAUI CommunityToolkit: Latest
- OS: Windows 10
- .NET MAUI: 8.0
```

### Anything else?

When running as store app, everything works as expected.

**Comment by VladislavAntonyuk** [comment]
Snackbar uses ToastNotificationManager, which is Obsolete on Windows and replaced by AppNotification. However, AppNotification is not displayed in Desktop mode.
