### ISSUE TITLE
[BUG] Popup background not rendering on android 34

### ISSUE THREAD

**Issue by aksik** [CommunityToolkit/Maui#1654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Area outside popup is not grayed out on android api 34.

<img width="397" alt="image" src="https://github.com/CommunityToolkit/Maui/assets/12427813/b114988a-3bb4-4db7-b53c-98ca859b6a00">

### Expected Behavior

Expected to work as in previous apis:

<img width="398" alt="image" src="https://github.com/CommunityToolkit/Maui/assets/12427813/add9c70c-e13b-4cca-acbe-4eb94daafb37">

### Steps To Reproduce

Create default maui project, add community toolkit and add the simplest possible popup. As described here:
https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/popup

### Link to public reproduction project repository

https://github.com/aksik/MauiApp6

### Environment

```markdown
- .NET MAUI CommunityToolkit:7.1
- OS:android api 34
- .NET MAUI:8.0.3
```

**Comment by cat0363** [comment]
As a side note, if you turn on "Developer settings" => "Disable HW overlays" in the Android emulator, overlays will be displayed.
https://issuetracker.google.com/issues/289117017

It might be a bug in the emulator.

[Disable HW overlays : ON]

<img width="250" src="https://github.com/CommunityToolkit/Maui/assets/125236133/557a9300-43b8-4e52-a1b5-ec6d583881b0" />

[Disable HW overlays : OFF]

<img width="250" src="https://github.com/CommunityToolkit/Maui/assets/125236133/a8c8a934-2e35-4978-8ef9-9f6f9367c7fe" />

I'm sorry if I'm wrong.

**Comment by workmail20** [comment]
This problem need fix

**Comment by cat0363** [comment]
@workmail20 , There is a similar description below, but is this problem only with the Emulator?
https://stackoverflow.com/questions/76641510/android-14-outside-of-alertdialog-doesnt-get-dim

**Comment by cat0363** [comment]
Has anyone tested it on a device?

**Comment by aksik** [comment]
> Has anyone tested it on a device?

yes - it's ok.

**Comment by cat0363** [comment]
If you test it on a device and there is no problem, but the problem only occurs in the emulator, it is most likely an issue with the emulator.
At the moment, I'm sorry, but there is no solution other than the workaround I previously presented.

**Comment by vhugogarcia** [comment]
Thanks @cat0363 for the feedback. I also just ran a test on my Android simulator and it works OK. I am guessing Android updated the emulators and fixed the issue. 

I'm closing this issue, since it is not related to the .NET MAUI Community Toolkit itself.
