### ISSUE TITLE
[BUG] iOS: MediaElement Speed not working when media played

### ISSUE THREAD

**Issue by Cyrus-Vance** [CommunityToolkit/Maui#1668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I am trying to play media using MediaElement with specific play rate. And I found when using iOS, the Speed property won't work after first play. But this will work normally in Windows and Android.
Here's the code:
```xaml
            <Button
                x:Name="CounterBtn"
                Text="Play" 
                Clicked="OnPlayButtonClicked"
                HorizontalOptions="Fill" />
            <toolkit:MediaElement x:Name="mediaElement"
                Source="https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
                ShouldAutoPlay="True"
                ShouldShowPlaybackControls="True"
                HeightRequest="300"
                WidthRequest="400"
             />
```

```csharp
        private void OnPlayButtonClicked(object sender, EventArgs e)
        {
            mediaElement.SeekTo(TimeSpan.FromSeconds(0));
            mediaElement.Play();
            mediaElement.Speed = 3;
        }
```

But I found a way to fix that temporarily on iOS: set the speed to 1 before the correct value. For example:
```csharp
mediaElement.Speed = 1;
mediaElement.Speed = theCorrectValue;
```

### Expected Behavior

After play button clicked for multiple times, the speed will set to the specific value.

### Steps To Reproduce

just set the MediaElement Speed after SeekTo() the start and Play()

### Link to public reproduction project repository

https://github.com/Cyrus-Vance/MauiMediaElementExample

### Environment

```markdown
- CommunityToolkit.Maui.MediaElement: 3.0.1
- OS: Windows 11 23H2 Build 22631
- .NET MAUI: 8.0.3
```

**Comment by vhugogarcia** [comment]
Thanks @Cyrus-Vance for reporting this issue. I ran some tests on iOS and the issue has been fixed on the CommunityToolkit.Maui.MediaElement version 4.0.1 using .NET MAUI 8.0.70.

I'm closing this issue. We can re-open it the issue returns.


https://github.com/user-attachments/assets/23cccb14-cae0-478c-823c-242f356cdd9a
