### ISSUE TITLE
XLS0414	The type 'toolkit:TabView' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built

### ISSUE THREAD

**Issue by Kingslee1604** [CommunityToolkit/Maui#1677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Not able to use toolkit:TabView in my project

### Expected Behavior

I need to create new Tabs in MAUI app

### Steps To Reproduce

1. Open the Test Pro project and just build it, we should be able to get the below error. I reference the Community tool kit but still getting same error.
Error	XLS0414	The type 'toolkit:TabView' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.

### Link to public reproduction project repository

https://github.com/Kingslee1604/CsharpProjects/tree/main/TestPro

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS:
- .NET MAUI:
```

**Comment by bijington** [comment]
There isn't a `TabView` as part of the .NET MAUI Community Toolkit. I think @VladislavAntonyuk has some blog posts on how to build one though

**Comment by brminnick** [comment]
Hi @Kingslee1604! TabView does not exist in CommunityToolkit.Maui. 

The Proposal to add TabView has been closed. You're welcome to peruse it for information on why we've decided against adding it to the MAUI Community Toolkit. 

https://github.com/CommunityToolkit/Maui/issues/121

**Comment by Kingslee1604** [comment]
Thank you so much for all the inputs... I came up with approach of using Frame to create specific tabs..

**Comment by G0A75** [comment]
Uranium ui has a TabView that people might want to consider as well
https://enisn-projects.io/docs/en/uranium/latest/themes/material/components/TabView

**Comment by VladislavAntonyuk** [comment]
Adding uranium for just one control is overkill. Also with each new MAUI release you may need to wait until uranium updates its library. 
You can use standard combination of MAUI controls: https://vladislavantonyuk.github.io/articles/Mastering-Composite-Controls-in-.NET-MAUI.-Building-a-TabView-from-Scratch
