### ISSUE TITLE
[BUG] Using IconTintColorBehavior in a Grid in a DataTemplate for a CollectionView results in incorrect size for icon

### ISSUE THREAD

**Issue by StevilKnevil** [CommunityToolkit/Maui#1681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

If you have a collection view and then layout each row of the collection such that it has an ImageButton that has the IconTintColorBehavior applied, then the size of the button is not correctly calculated, meaning it's not rendered correctly in the grid

![image](https://github.com/CommunityToolkit/Maui/assets/1076923/d4d109b3-8979-4d44-a349-53bd13070cad)

### Expected Behavior

The layout should instead be the same as if no tint was applied:

![image](https://github.com/CommunityToolkit/Maui/assets/1076923/3771c8b5-8c44-4d84-bd52-7ea330bc94fc)

### Steps To Reproduce

1. Open and build the repository
2. Run and see how the red tinted icon is the incorrect size

### Link to public reproduction project repository

https://github.com/StevilKnevil/IconTintColorBehavior

### Environment

```markdown
- .NET MAUI CommunityToolkit: 7.0.1
- OS: Windows 10
- .NET MAUI: 8.03
```

**Comment by StevilKnevil** [comment]
Debugging into the source for this, it seems that at some point after applying the colour tint, then the size of the image is later set to 0,0 (by something in native code)

**Comment by brminnick** [comment]
Thanks @StevilKnevil!

Could you submit a pull request with the fix? 

Do you know of other use cases where we would need that line of code?

**Comment by StevilKnevil** [comment]
Created a draft PR to take a look at. I haven't ticked off all the bits of the PR checklist though!

**Comment by StevilKnevil** [comment]
How can I move the status of this bug to "verified" so that I can complete the tasks to move the PR forwards?

**Comment by bijington** [comment]
I've removed the unverified label for you. Hopefully one of us maintainers can take a look soon and test the changes. I know my Windows setup is still in a mess but I need to sort that out soon anyway.
