### ISSUE TITLE
♻ Ensure no references to Xamarin.CommunityTookit in Maui app that uses MCT

### ISSUE THREAD

**Issue by pictos** [CommunityToolkit/Maui#17]
Based on this https://github.com/dotnet/maui/pull/1816

We want to make sure that users don't have both packages added to the project.

**Comment by VladislavAntonyuk** [comment]
Because we use .NET MAUI I suppose we don't need it

**Comment by pictos** [comment]
@VladislavAntonyuk, the idea is to make sure that users that migrate their apps to Maui, don't forget to remove the reference. This also extends to XCT.compat.
I'll there's a msbuild that can do that or we can use some analyzer, maybe inside our source generator?

**Comment by VladislavAntonyuk** [comment]
Can the Maui analyzer do that for us? As XCT uses XF, msbuild should return error. 
as for the MauiCompat, we should not exclude it right now, because it contains features like CameraView and MediaElement which are not available in MCT
