### ISSUE TITLE
[BUG] MediaElement is not currently being Garbage Collected

### ISSUE THREAD

**Issue by marco-skizza** [CommunityToolkit/Maui#1702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

As it seems, the `MediaElement` doesn't ever get Garbage Collected.

### Expected Behavior

The `MediaElement` should get Garbage Collected eventually, and with it the containing page.

### Steps To Reproduce

- Run the sample
- Click the button to get to the page with the `MediaElement` and navigate back
- Do this several times
- In the Debug console observe, that `~MyPage()` never gets called

### Link to public reproduction project repository

https://github.com/marco-skizza/CommunityMauiMediaElement

### Environment

```markdown
- CommunityToolkit.Maui.MediaElement: 3.0.1
- OS: iPadOS 17.3.1 on an iPad mini 6
- .NET MAUI: 8.0.6
```

### Anything else?

Thanks for looking at this!

**Comment by brminnick** [comment]
Hey @marco-skizza! This doesn't fix the bug, but there's a workaround where you should disconnect the handler when you're done using MediaElement to avoid memory leaks. 

Here's a PR we recently merged that demonstrates how we're now doing this work-around in the SampleApp:
https://github.com/CommunityToolkit/Maui/commit/9c83cd4b110fc7564f73b359931a85d755a9efa9

@bijington - Do we have anything in our docs to note this? We totally should!

**Comment by bijington** [comment]
@brminnick we do indeed:

https://learn.microsoft.com/en-gb/dotnet/communitytoolkit/maui/views/mediaelement#clean-up-mediaelement-resources

**Comment by marco-skizza** [comment]
Thanks for your feedback @brminnick

I'm already disposing the handler.
I'm just currently using `OnHandlerChanging` instead of `Unloaded` on iOS.
This is because since .NET 8 the approach with `Unloaded` doesn't work for me anymore on iOS.
See also: https://github.com/CommunityToolkit/Maui/discussions/1663

But even though I'm disconnecting the handler, the `MediaElement` never gets Garbage Collected...

**Comment by pictos** [comment]
> This is because since .NET 8 the approach with Unloaded doesn't work for me anymore on iOS.

@marco-skizza what's happening?

**Comment by marco-skizza** [comment]
@pictos I try to explain...

I just updated my sample project.
Currently there are two points to hightlight:

- 1) When navigating to the page with the `MediaElement` and back again multiple times, the `MediaElement` doesn't get Garbage Collected. Even when the handler was disposed.
    - iOS: Problem exists
    - WinUI: Don't know, because I don't know how to disconnect the handler on WinUI accordingly
    - Android: Couldn't test

- 2) The `Unloaded` event can't be used anymore for disconnecting the handler...
    - a) The `Unloaded` events gets triggered when navigating to a third page, so if I disposed the handler, the `MediaElement` would already be disposed when navigating back.
        - iOS: Problem exists
        - WinUI: Problem exists
        - Android: Couldn't test
    - b) The `Unloaded` event gets also called on iOS when entering the fullscreen mode of the `MediaElement`, so if I disposed the handler, the `MediaElement` would already be disposed when leaving fullscreen mode.
        - iOS: Problem exists
        - WinUI: Don't know - didn't find a way to enter fullscreen mode on WinUI
        - Android: Couldn't test

I hope this makes any sense...

**Comment by brminnick** [comment]
Hey @marco-skizza! 

After some refactoring, I was able to trigger the finalizer in `MyPage` on both iOS + Android, despite it using the MediaElement. I've re-added the https://github.com/CommunityToolkit/Maui/labels/unverified for now.

I've opened a Pull Request to your sample reproduction: https://github.com/marco-skizza/CommunityMauiMediaElement/pull/1

This fork contains the updated sample. To trigger the disposal of `MyPage`, continue to click the Button on each page to navigate back-and-forth between `MyPage` and `MyThirdPage`. With the debugger attached and a breakpoint in `~MyPage()`, you will see the page does get disposed.

<img width="1728" alt="image" src="https://github.com/marco-skizza/CommunityMauiMediaElement/assets/13558917/982f6530-5937-4f5a-92b7-c77d7c67d6e8">

**Comment by marco-skizza** [comment]
Notes from the Pull Request:

I played around with your code a bit and found out that it starts "leaking" again when you add the `MyViewModel` back to the `MyPage` as binding context. So I can imagine that there may be some "leaking" with the source binding `Source="{Binding FilePath}"` in `MediaElement`...

It may be a similar problem as: https://github.com/dotnet/maui/issues/20710
It affects not every binding in .NET MAUI - but I found that on the `CollectionView` by investigating as well.
But we can also wait and see what this MAUI Issue brings to light...

**Comment by marco-skizza** [comment]
Hi @brminnick

After playing around with your code some more I found out the following:

Your code seems to work, because you have a source binding `Source="{Binding FilePath}"` defined, but on ViewModel attached - which left the `MediaElement` uninitialized as I suppose. Only after setting the source to a valid path, even with `Source="embed://Sister.m4a"`, it started leaking again. So I strongly believe that there is a leak in the `MediaElement` itself...

Kind Regards

**Comment by marco-skizza** [comment]
Hi @brminnick

It seems - at least on iOS - that besides disconnecting the handler, one has to dispose the `MediaElement` itself as well:
```cs
        MyMediaElement.Handler?.DisconnectHandler();
        MyMediaElement.Dispose();
```

This fixed the Memory Leak for me - together with the fix above.

I'll open a PR when I tested this some more...
