### ISSUE TITLE
[BUG] White text (LightContent) can not be set on iOS platform with light mode

### ISSUE THREAD

**Issue by RsZoli** [CommunityToolkit/Maui#1712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When setting the StatusBarStyle on iOS platform using the following code

    <ContentPage.Behaviors>
        <toolkit:StatusBarBehavior StatusBarColor="{StaticResource Primary}" StatusBarStyle="LightContent" />
    </ContentPage.Behaviors>

The color of the items in the status bar stay black on iOS platform, when using light mode! On Android, the setting is respected:

![IMG_0004](https://github.com/CommunityToolkit/Maui/assets/28480037/200e6352-05cd-4097-a253-00a9e29ad31e)
![IMG_0005](https://github.com/CommunityToolkit/Maui/assets/28480037/546377ce-2f5b-4843-8ebc-72dd8014f24a)
![Screenshot_20240223_140413](https://github.com/CommunityToolkit/Maui/assets/28480037/42a1582c-b6d9-4d8f-82f2-8d28b9623d5f)
![Screenshot_20240223_140424](https://github.com/CommunityToolkit/Maui/assets/28480037/e0db9371-a6a4-4abf-9e8e-fff860b90362)

### Expected Behavior

Text and icons displayed in white color on iOS platform, according to the setting!

### Steps To Reproduce

Create a new .NET MAUI application, install the NuGet package and use my code above, or please refere to my repro.

### Link to public reproduction project repository

https://github.com/RsZoli/GitHubRepros/

### Environment

```markdown
- .NET MAUI CommunityToolkit: 7.0.1
- OS: iOS 16.7.5, iOS 17.3.1
- .NET MAUI: 8.0.6
```

**Comment by vhugogarcia** [comment]
Thanks @RsZoli for creating the issue. After reviewing the issue, I noticed you were missing the iOS Info.Plist configuration, that is the reason of the status bar not being able to change from light content to dark content:
```xml
<key>UIViewControllerBasedStatusBarAppearance</key>
<false/>
```

Once you apply this change, the status bar content will change from light to dark as needed. Please refer to the official documentation for further details: https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/behaviors/statusbar-behavior?tabs=ios

https://github.com/user-attachments/assets/db77ec16-0bd0-4285-8196-04bd6e0c3a3e

**Comment by RsZoli** [comment]
@vhugogarcia Thank you very much!
