### ISSUE TITLE
[BUG] Crash in MediaElement under iOS when AirPlay a liveStream

### ISSUE THREAD

**Issue by juergenfurrer** [CommunityToolkit/Maui#1718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

1. Use the MediaElement on iOS
2. add a live-stream (video without duration!!!)
3. Cast the video (AirPlay button top-left in the video-player)
4. Chose the AirPlay-device from the list
5. The Video plays on the AirPlay-device
6. In Debug: The app crashes on Main-Thread and the video plays on the TV untill you stop debugging...
7. System.OverflowException: TimeSpan overflowed because the duration is too long.

### Expected Behavior

Stream should play without crash

### Steps To Reproduce

1. Open repo
2. Connect real iOS (local or remote)
3. Debug the Solution
4. Play the video (this has to be a live-stream video!)
5. Turn TV on (or any other air-play device)
6. Click button for Airplay on the player
7. Chose the AirPlay-Device
8. Crash

### Link to public reproduction project repository

https://github.com/juergenfurrer/MauiMediaElementSample

### Environment

```markdown
- .NET MAUI CommunityToolkit: 7.0.1
- OS: iOS 17.4
- .NET MAUI: 8.0.7
```

**Comment by ne0rrmatrix** [comment]
I was unable to replicate the issue on current main using Ipad and casting to a mac mini. Zero issues. Try updating packages to current 4.0.1 for media element and 9.0.2 for toolkit.

**Comment by vhugogarcia** [comment]
Thanks @ne0rrmatrix for sharing feedback. @juergenfurrer please upgrade to the latest version and also to the .NET MAUI 8.0.70 version.

I'm closing this ticket and we can re-open it if needed.
