### ISSUE TITLE
[BUG] Back Button not working in Fullscreen mode

### ISSUE THREAD

**Issue by South2AK** [CommunityToolkit/Maui#1753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When using a back button (tested on two android devices) and having FullScreen toggled via the newly added fullscreen button the page simply goes back when using the back button while the mediaElement is still in fullscreen mode and running.

### Expected Behavior

Back button should simply stop the full screen mode and go back to the page the media element is on. When using the back button then, it should go back a page.

### Steps To Reproduce

1. Be on page 1 and navigate to page 2
2. Play the video
3. Toggle Fullscreen
4. Toggle Back Button on your device 
5. Page 1 is now active in background, while mediaElement is still in foreground fulscreen

### Link to public reproduction project repository

https://github.com/South2AK/MediaElementBackButtonBug

### Environment

```markdown
- .NET MAUI CommunityToolkit:3.1.0
- OS:Android API 33 / 34
- .NET MAUI: 8
```

### Anything else?

Also, if the page has been added via AddTransient, the page crashes since the MediaELement has been disposed of

**Comment by South2AK** [comment]
@ne0rrmatrix Hi,

the pr works, BUT hopefully you don´t get me wrong..

Wouldn´t it be better if the back button just simply toggles the fullscreen button without stopping playback and also stopping the Page Go back Behavior?

A perfect behavior would be:
Full Screen is on --> Back button pressed --> Full Screen is off --> Back Button is pressed a second time --> Page goes back

**Comment by ne0rrmatrix** [comment]
I just fixed the behavior. It no longer overrides the default behavior. It just exits full screen on back button pressed now. It does nothing else. Thank you testing and providing insight into behavior. That PR is to fix an issue with full screen not going back to normal mode when back button is pressed. If you want the behavior changed I suggest opening a discussion about adding a feature/proposal.

**Comment by South2AK** [comment]
Thank you @ne0rrmatrix 

How can I test it? Has the PR been changed?
