### ISSUE TITLE
Media Element does not center vertically inside Absolute Layout (android)[BUG] 

### ISSUE THREAD

**Issue by Realgigabyte** [CommunityToolkit/Maui#1762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

This code:

 AbsoluteLayout.SetLayoutBounds(MediaElement, new Rect(0, 0, 1, 1));
 AbsoluteLayout.SetLayoutFlags(MediaElement, AbsoluteLayoutFlags.All);
 AbsoluteLayout.Add(MediaElement);

works correctly with CommunityToolkit.Maui.MediaElement v2.0.0 and the video always shows in the middle of the layout as expected. This works the same for Image View so I think this is the correct behaviour.

In version 3.1.0 the video only centers horizontally but always starts at the top of the screen so I recon is not centering vertically.
The Windows version works fine. This only happens on android.

### Expected Behavior

I am expecting the Media Element to work as version 2.0.0.

### Steps To Reproduce

AbsoluteLayout.SetLayoutBounds(MediaElement, new Rect(0, 0, 1, 1));
 AbsoluteLayout.SetLayoutFlags(MediaElement, AbsoluteLayoutFlags.All);
 AbsoluteLayout.Add(MediaElement);

### Link to public reproduction project repository

to be added

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS: Android
- .NET MAUI:
```

**Comment by Realgigabyte** [comment]
I double checked and it works fine up to version 3.0.1.
On version 3.1.0 video does not center vertically.

**Comment by bijington** [comment]
@Realgigabyte Can you please provide a sample to help with investigating the issue?

**Comment by Realgigabyte** [comment]
> @Realgigabyte Can you please provide a sample to help with investigating the issue?

Ok, please see sample app with MediaElement version 3.1.0:

https://github.com/Realgigabyte/MauiAppMediaElement

If you run it on an Android phone, the video will position on top of the screen (with phone in vertical position is more noticeable).

If the MediaElement NuGet version is reverted to 3.0.1 the video shows on the middle, which I believe is the expected behaviour.

**Comment by ne0rrmatrix** [comment]
When we added full screen support we switched from using a Relativelayout to a FrameLayout which I am pretty much convinced is causing this issue. We had to do a workaround to have the video centered and we used VideoFlags.CenterHorizontal in the layout which helps but creates its own issues. I think we need to rework how we do the layout.

**Comment by ne0rrmatrix** [comment]
@Realgigabyte  Can you try to PR linked above? Also can you set the width and height request to say 300 each so the video does not fit the bounds automatically? It will try to fit the window otherwise. I have tested it and it is centered vertically and horizontally now.
