### ISSUE TITLE
.net MAUI 8 Snackbar is now crashing on actual iOS devices--- (Release builds only on actual devices)

### ISSUE THREAD

**Issue by plppp2001** [CommunityToolkit/Maui#1768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

.net MAUI 8 Snackbar is now crashing on actual iOS devices now (Release builds only on actual devices)

### Expected Behavior

Snackbar should popup on iOS devices. This still works on all iOS Simulators without issue.

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/alerts/snackbar?tabs=android

### Steps To Reproduce

1. You must install latest versions of the following setup and create a release build on to an actual iOS device and the snackbar will crash the entire app.

(Please see versions section for how to re-create and setup)

### Link to public reproduction project repository

n/a

### Environment

```markdown
- .NET MAUI CommunityToolkit:
<PackageReference Include="CommunityToolkit.Maui" Version="7.0.1" />

- OS:
Windows 11.
VS2022 Version 17.9.4.
Mac M2 with Xcode: Version 15.3


- .NET MAUI:  (Latest .net 8 MAUI LTS)
		<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.10" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.10" />

- MVVM:
<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
```

### Anything else?

I have an Iphone 15 and an Iphone 6 Plus  (The snackbar kills the maui app on both devices - release)

**Comment by brminnick** [comment]
Duplicate: https://github.com/CommunityToolkit/Maui/issues/1752#issuecomment-1999990148

**Comment by plppp2001** [comment]
> Duplicate: [#1752 (comment)](https://github.com/CommunityToolkit/Maui/issues/1752#issuecomment-1999990148)

Ok thanks,  But this one if for the Snackbar.   fyi

**Comment by brminnick** [comment]
The bug has the same root-cause requiring the same [workaround](https://github.com/CommunityToolkit/Maui/issues/1752#issuecomment-1999990148)
