### ISSUE TITLE
[BUG] `TouchBehavior`s (LongPress)CommandParameter is always passed as `null` to the Command method

### ISSUE THREAD

**Issue by hansmbakker** [CommunityToolkit/Maui#1781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

The `TouchBehavior` `LongPressCommandParameter` and `CommandParameter` values are always passed as `null` to the Command method.

### Expected Behavior

The `TouchBehavior` `LongPressCommandParameter` and `CommandParameter` values are actually passed as parameter to the Command method.

This is a regression from the code in https://github.com/Axemasta/Maui.TouchEffect

### Steps To Reproduce

1. Open reproduction solution
2. Tap an item.

Actual behavior: `ShowItem(Command)` is called with `null` as parameter
Expected behavior: `ShowItem(Command)` is called with tapped item as parameter

### Link to public reproduction project repository

https://github.com/hansmbakker/bugrepro-communitytoolkit-maui-touchbehavior-parameter

### Environment

```markdown
- .NET MAUI CommunityToolkit: 8.0.0
- OS: Android, Windows - I expect this is not linked to an OS
- .NET MAUI: 8.0.14
```

### Anything else?

```xaml
<CollectionView x:Name="collectionView"
                ItemsSource="{Binding Items}">
    <CollectionView.ItemTemplate>
        <DataTemplate x:DataType="{x:Type x:String}">
            <Label Padding="10"
                   Text="{Binding .}">
                <Label.Behaviors>
                    <toolkit:TouchBehavior Command="{Binding Source={x:Reference collectionView}, Path=BindingContext.ShowItemCommand}"
                                           CommandParameter="{Binding .}"
                                           LongPressCommand="{Binding Source={x:Reference collectionView}, Path=BindingContext.ShowItemCommand}"
                                           LongPressCommandParameter="{Binding .}"/>
                    <!--
                    CommandParameter and LongPressCommandParameter are always passed as null in the CommunityToolkit.Maui TouchBehavior.
                    this was not the case with https://github.com/Axemasta/Maui.TouchEffect -->
                </Label.Behaviors>
            </Label>
        </DataTemplate>
    </CollectionView.ItemTemplate>
</CollectionView>
```

**Comment by bijington** [comment]
Is this down to:

> .NET MAUI does not set the BindingContext of a behavior, because behaviors can be shared and applied to multiple controls through styles.

![image](https://github.com/CommunityToolkit/Maui/assets/17139988/03cc9ec4-fbe2-463d-8801-9e172e4bb7aa)

Source:
https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/behaviors?view=net-maui-8.0#net-maui-behaviors

**Comment by hansmbakker** [comment]
@bijington I can't comment on that detail about `Behavior`s (didn't debug up to that level), but as a developer I expected this `TouchBehavior` would work as a "`TapGestureRecognizer` with extra features" (kind of as a drop-in replacement) - especially after having used Axemasta's original TouchEffect.

We use it for the LongPress functionality because TapGestureRecognizer doesn't support that.

Is there a solution for this?

I'd say "doing something with the touched item in the triggered Command" is a use case that probably many users will expect to work?

**Comment by brminnick** [comment]
@hansmbakker As Shaun mentioned, you must manually assign the BindingContext for Behaviors in .NET MAUI. 

Here is the updated XAML to get your code working; it uses a view-to-view binding to bind `TouchBehavior.BindingContext` to `Label.BindingContext`:

```xml
<Label Padding="10"
  Text="{Binding .}"
  x:Name="Label">
  <Label.Behaviors>
    <toolkit:TouchBehavior Command="{Binding Source={x:Reference collectionView}, Path=BindingContext.ShowItemCommand}"
      CommandParameter="{Binding .}"
      LongPressCommand="{Binding Source={x:Reference collectionView}, Path=BindingContext.ShowItemCommand}"
      LongPressCommandParameter="{Binding .}"
      BindingContext="{Binding Source={x:Reference Label}, Path=BindingContext}"/>
  </Label.Behaviors>
</Label>
```
<img width="753" alt="image" src="https://github.com/CommunityToolkit/Maui/assets/13558917/a1b6fd52-8a81-4676-88aa-77da052eb361">

Here are our Unit Tests we use to verify the `LongPressCommand` does indeed pass in `LongPressCommandParamenter`;

https://github.com/CommunityToolkit/Maui/blob/51dc63a7642370849e413d87072b668fa022e303/src/CommunityToolkit.Maui.UnitTests/Behaviors/TouchBehaviorTests.cs#L612-L674

And here are our Unit Tests we use to verify the `Command` does indeed pass in `CommandParamenter`;

https://github.com/CommunityToolkit/Maui/blob/51dc63a7642370849e413d87072b668fa022e303/src/CommunityToolkit.Maui.UnitTests/Behaviors/TouchBehaviorTests.cs#L550-L610
