### ISSUE TITLE
[BUG] Native animations not showing. (TouchBehavior)

### ISSUE THREAD

**Issue by vincentlai97** [CommunityToolkit/Maui#1787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Native animations (namely ripple effect on Android) does not show in the sample MCT project.

https://github.com/CommunityToolkit/Maui/assets/8454192/12090b01-603d-44ce-9e06-e11aab5fc248

The additional blue button only had the native animation after removing global Button style from Styles.xml.
Which makes me wonder if it has anything to do with this issue. https://github.com/dotnet/maui/issues/17642

### Expected Behavior

https://github.com/CommunityToolkit/Maui/pull/1673#issuecomment-1978358750
As shown in the PR.

### Steps To Reproduce

1. Load fresh MCT sample.
2. Build and run on physical device.
3. (Optional) To get native animation on Button, remove global Button styling in Styles.xml

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui

### Environment

```markdown
- .NET MAUI CommunityToolkit: 8.0.0
- OS: Android 14 (API 34)
- .NET MAUI: Tested on both 8.0.14 (Fresh from repository) and 8.0.7
- .NET SDK: 8.0.203

Installed Workload Id      Manifest Version       Installation Source
--------------------------------------------------------------------------------------------------
android                    34.0.85/8.0.100        SDK 8.0.200, VS 17.7.34221.43, VS 17.10.34607.79
ios                        17.2.8043/8.0.100      SDK 8.0.200, VS 17.7.34221.43, VS 17.10.34607.79
maccatalyst                17.2.8043/8.0.100      SDK 8.0.200, VS 17.7.34221.43, VS 17.10.34607.79
macos                      14.2.8043/8.0.100      SDK 8.0.200, VS 17.10.34607.79
maui-android               8.0.7/8.0.100          SDK 8.0.200, VS 17.7.34221.43
maui-ios                   8.0.7/8.0.100          SDK 8.0.200, VS 17.7.34221.43
wasi-experimental          8.0.3/8.0.100          SDK 8.0.200
maui-windows               8.0.7/8.0.100          VS 17.7.34221.43, VS 17.10.34607.79
maui-maccatalyst           8.0.7/8.0.100          VS 17.7.34221.43
```

**Comment by brminnick** [comment]
This is by a bug. 

The Xamarin Community Toolkit's Native Animation implementation was not ported to .NET MAUI. 

If you're interested in implementing it, please open a new feature proposal: https://github.com/CommunityToolkit/Maui/issues/new?assignees=&labels=new%2Cproposal&projects=&template=open-a-new-feature-proposal.yml&title=%5BProposal%5D+
