### ISSUE TITLE
[BUG] CollectionView SelectionMode.Multiple doesn't work with TouchBehavior:LongPressCompleted in data template.

### ISSUE THREAD

**Issue by DevDachi** [CommunityToolkit/Maui#1793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

We are using TouchBehavior:LongPressCompleted with in Collection View data template. The Collection View has SelectionMode.Multiple set.

With this configuration, the SelectedItems doesn't work (The selected items are always remains empty)

### Expected Behavior

This usage should not have any impact on collection view with Multiple selection mode.

### Steps To Reproduce

1.  Add a collection view to the page.
2. Add TouchBehavior:LongPressCompleted on data row template, that will enable multi select mode on the collection view.

### Link to public reproduction project repository

N.A.

### Environment

```markdown
- .NET MAUI CommunityToolkit:8.0.0
- OS: Android (Tested only this one)
- .NET MAUI:8.0.14
```

**Comment by brminnick** [comment]
Please provide a link to public reproduction project repository

**Comment by bulletis** [comment]
I had the same problem.
reproduction sample: https://github.com/bulletis/bugTouchBehavior.git

my environment:
- .NET MAUI CommunityToolkit:8.0.1
- OS: Android (Tested only this one)
- .NET MAUI:8.0.100

**Comment by pulmuone** [comment]
same bug issue
