### ISSUE TITLE
[BUG] UniformItemsLayoutManager throws ArgumentException upon removing all children

### ISSUE THREAD

**Issue by Westhes** [CommunityToolkit/Maui#1816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

UniformsItemsLayoutManager throws an ArgumentNullException when all its children are removed.

### Expected Behavior

UniformsItemsLayoutManager doesn't throw an exception and goes back to the state it would be in when instantiating without children.

### Steps To Reproduce

1. Build the provided repository for any platform
2. Click the button.

### Link to public reproduction project repository

- https://github.com/RWesthes/UniformItemsLayoutBug

### Environment

```markdown
- .NET MAUI CommunityToolkit: 8.0.1
- OS: Winodws 10
- .NET MAUI: 8
```

### Anything else?

The exception is thrown by the Math.Clamp method at [UniformItemsLayoutManager.shared.cs#L91](https://github.com/CommunityToolkit/Maui/blob/main/src/CommunityToolkit.Maui.Core/Layouts/UniformItemsLayoutManager.shared.cs#L91) due to visibleChildrenCount being lower than the minimum value.
Simply adding `columnsCount != 0 &&` to the if statement resolves this exception.

**Comment by Westhes** [comment]
@VladislavAntonyuk step 4 was just an quick and generic way of removing a single child from the collection.
Calling `UniformItemsLayout_Default.Children.Clear();` on the collection also throws this exception.

**Comment by RWesthes** [comment]
Added reproduction project repository.

**Comment by Westhes** [comment]
bump.
Also, can you remove the needs reproduction tag?
