### ISSUE TITLE
[BUG] IconTintColorBehavior crash on android.

### ISSUE THREAD

**Issue by PaulNiemiec** [CommunityToolkit/Maui#1819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

IconTintColorBehavior crash while changing tint color.

System.ObjectDisposedException: ObjectDisposed_Generic
ObjectDisposed_ObjectName_Name, AndroidX.AppCompat.Widget.AppCompatImageView
   at Java.Interop.JniPeerMembers.AssertSelf(IJavaPeerable )
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String , IJavaPeerable , JniArgumentValue* )
   at Android.Widget.ImageView.SetColorFilter(ColorFilter )
   at CommunityToolkit.Maui.Behaviors.IconTintColorBehavior.<ApplyTintColor>g__SetImageViewTintColor|2_0(ImageView image, Color color)

### Expected Behavior

IconTintColorBehavior does not crash. 

### Steps To Reproduce

Unfortunately, I have some nuget problems with adding package, but you should be able to reproduce it by changing tint color.

### Link to public reproduction project repository

no link currently

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS:
- .NET MAUI:
```

### Anything else?

I found fix for this. Just remove PropertyChanged event handler in OnDetachedFrom method. In previous version handler is added, but not removed.

public partial class WorkaroundTintedImageBehavior
{
    private View? _bindable;
    private AView? _platformView;
    
    protected override void OnAttachedTo(View bindable, AView platformView)
    {
        _bindable = bindable;
        _platformView = platformView;
        
        bindable.PropertyChanged += OnElementPropertyChanged;
        ApplyTintColor(platformView);
        PropertyChanged += OnTintedImagePropertyChanged;
    }

    protected override void OnDetachedFrom(View bindable, AView platformView)
    {
        ClearTintColor(bindable, platformView);
        bindable.PropertyChanged -= OnElementPropertyChanged;
        PropertyChanged -= OnTintedImagePropertyChanged;
    }

    private void OnTintedImagePropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (e.PropertyName == TintColorProperty.PropertyName && _bindable is not null && _platformView is not null)
        {
            ApplyTintColor(_platformView);
        }
    }

    private void ApplyTintColor(AView control)
    {
        var color = TintColor;

        switch (control)
        {
            case ImageView image:
                SetImageViewTintColor(image, color);
                break;
            case AButton button:
                SetButtonTintColor(button, color);
                break;
            default:
                throw new NotSupportedException($"{nameof(WorkaroundTintedImageBehavior)} only currently supports Android.Widget.Button and {nameof(ImageView)}.");
        }

        static void SetImageViewTintColor(ImageView image, Color? color)
        {
            if (color is null)
            {
                image.ClearColorFilter();
                return;
            }

            image.SetColorFilter(new PorterDuffColorFilter(color.ToPlatform(), PorterDuff.Mode.SrcIn ?? throw new InvalidOperationException("PorterDuff.Mode.SrcIn should not be null at runtime.")));
        }

        static void SetButtonTintColor(AButton button, Color? color)
        {
            var drawables = button.GetCompoundDrawables().Where(d => d is not null);

            if (color is null)
            {
                foreach (var img in drawables)
                {
                    img.ClearColorFilter();
                }

                color = Colors.Transparent;
            }

            foreach (var img in drawables)
            {
                img.SetTint(color.ToPlatform());
            }
        }
    }

    private void OnElementPropertyChanged(object? sender, PropertyChangedEventArgs args)
    {
        if (args.PropertyName is not string propertyName
            || sender is not View bindable
            || bindable.Handler?.PlatformView is not AView platformView)
        {
            return;
        }

        if (!propertyName.Equals(Image.SourceProperty.PropertyName, StringComparison.Ordinal)
            && !propertyName.Equals(ImageButton.SourceProperty.PropertyName, StringComparison.Ordinal))
        {
            return;
        }

        ApplyTintColor(platformView);
    }

    private void ClearTintColor(View element, AView control)
    {
        element.PropertyChanged -= OnElementPropertyChanged;
        switch (control)
        {
            case ImageView image:
                image.ClearColorFilter();
                break;
            case AButton button:
                foreach (var drawable in button.GetCompoundDrawables())
                {
                    drawable?.ClearColorFilter();
                }

                break;
        }
    }
}

**Comment by PaulNiemiec** [comment]
I am sorry, but for now I am not able to reproduce it in sample app

**Comment by PaulNiemiec** [comment]
But take a look at fix which I added in the Anything else? section. Clearly in current code this.PropertyChanged event handler is not disposed properly.

**Comment by KillswitchPrime** [comment]
I believe I have encountered the same issue.
Here is the link to issue I created on Github: https://github.com/CommunityToolkit/Maui/issues/1710
It includes a link to a repo with steps to reproduce the issue consistently.

**Comment by KillswitchPrime** [comment]
I tried to implement your workaround, but I think a little bit of context code is missing? I can't find AView for example

**Comment by PaulNiemiec** [comment]
@KillswitchPrime Take a look [CommunityToolkit tint behavior](https://github.com/CommunityToolkit/Maui/tree/main/src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor) there is event handler added to PropertyChanged event, but this event is not removed in OnDetached method. I added two variables to store _platformView and _bindable and then I changed event handler registration to take method, not lambda expression, so that I could remove it in OnDetached method. AView is alias - using AView = Android.Views.View;

**Comment by KillswitchPrime** [comment]
@PaulNiemiec Thanks for giving more info. I have implemented your fix in my reproduction repo, and the app no longer crashes when following the steps I outlined. Great work!

**Comment by bijington** [comment]
If this solves the issue is someone willing to submit the fix via a PR?

**Comment by PaulNiemiec** [comment]
@bijington  I can try

**Comment by bijington** [comment]
> @bijington  I can try

That would be amazing! Happy to offer any guidance if you need

**Comment by PaulNiemiec** [comment]
@bijington FYI I didn't forget about this PR, just don't have capacity currently. I will do this in couple of days

**Comment by bijington** [comment]
@PaulNiemiec no problem at all! Thank you still for the offer/intention, it is greatly appreciated

**Comment by PaulNiemiec** [comment]
Hi @bijington I think I am not privileged :D I tried to push my branch to remote and I got error: Push failed remote: Permission to CommunityToolkit/Maui.git denied to PaulNiemiec. unable to access 'https://github.com/CommunityToolkit/Maui.git/': The requested URL returned error: 403

**Comment by bijington** [comment]
Oh no you won't be allowed to do that. You will need to create a Fork, do the work on a branch there and then open a Pull Request against this repository. Happy to assist if you aren't familiar with any of that

**Comment by PaulNiemiec** [comment]
Hi @bijington sorry for bothering you, but I have one question. I created PR but pipeline is failing and I cannot check details, could you tell me?

**Comment by bijington** [comment]
@PaulNiemiec thank you for the PR! The failure has nothing to do with your changes. It looks like a new version of MAUI is available and it's broken our pipeline build. We will try and patch that up and then merge this in

**Comment by christian-strydom** [comment]
Thank you for your contribution on this issue and everyone's involvement in making this package a reality.

I think I'm still facing this issue on v9.0.1 of CommunityToolkit.Maui with Microsoft.Maui.Controls & Microsoft.Maui.Controls.Compatibility v8.0.61. Can't seem to reproduce the issue during a local build but my internal Android release reports the issue when navigating to a page that uses the image tinting and app crashing. I don't mind opening a new issue, I just first want to make sure it's not something unrelated I'm doing wrong? Anyone else running into this on 9.0.1?

Dropping back to previous NuGet versions seem to resolve my issue:
CommunityToolkit.Maui - 9.0.0
Microsoft.Maui.Controls - 8.0.40
Microsoft.Maui.Controls.Compatibility - 8.0.40

This is the exception I'm getting on Firebase:
 Fatal Exception: android.runtime.JavaProxyThrowable: [System.ObjectDisposedException]: ObjectDisposed_Generic
ObjectDisposed_ObjectName_Name, AndroidX.AppCompat.Widget.AppCompatImageView
       at Java.Interop.JniPeerMembers.AssertSelf()
       at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod()
       at Android.Widget.ImageView.ClearColorFilter()
       at CommunityToolkit.Maui.Behaviors.IconTintColorBehavior.ClearTintColor()
       at CommunityToolkit.Maui.Behaviors.IconTintColorBehavior.OnDetachedFrom()
       at Microsoft.Maui.Controls.PlatformBehavior`2[[Microsoft.Maui.Controls.View, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Android.Views.View, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken="ommitted"]].FireDetachedFrom()
       at Microsoft.Maui.Controls.PlatformBehavior`2[[Microsoft.Maui.Controls.View, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Android.Views.View, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken="ommitted"]].OnUnloaded()
       at Microsoft.Maui.Controls.VisualElement.SendUnloaded()
       at Microsoft.Maui.Controls.VisualElement.SendUnloaded()
       at Microsoft.Maui.Platform.ViewExtensions+<>c__DisplayClass43_0.<OnUnloaded>b__3()
       at Java.Lang.Thread+RunnableImplementor.Run()
       at Java.Lang.IRunnableInvoker.n_Run()
       at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V()
       at mono.java.lang.RunnableImplementor.n_run(RunnableImplementor.java)
       at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8919)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by PaulNiemiec** [comment]
@christian-strydom  I will take a look during this weekend

**Comment by DavidV1603** [comment]
> I think I'm still facing this issue on v9.0.1 of CommunityToolkit.Maui with Microsoft.Maui.Controls & Microsoft.Maui.Controls.Compatibility v8.0.61. Can't seem to reproduce the issue during a local build but my internal Android release reports the issue when navigating to a page that uses the image tinting and app crashing. I don't mind opening a new issue, I just first want to make sure it's not something unrelated I'm doing wrong? Anyone else running into this on 9.0.1?
> 


I can confirm that I run into the same problem in my app. With 9.0.0 and 8.0.40 the problem seems to be gone too.
