### ISSUE TITLE
[BUG] Inappropriate use of FrozenSet

### ISSUE THREAD

**Issue by jkotas** [CommunityToolkit/Maui#1829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

https://github.com/CommunityToolkit/Maui/pull/1367 changed number of places to use `FrozenSet<T>`. `FrozenSet<T>` is not appropriate to use in most if not all these places.

`FrozenSet<T>` is only meant to be used in situations where the collection is created once and then there are many lookups performed against it. Creating `FrozenSet<T>` has high cost both in terms CPU cycles and static code footprint that is important performance metric for mobile apps.

`FrozenSet<T>` are typically created as singletons or long-lived objects. It is not appropriate to create `FrozenSet<T>` instance per property, for example how it is done in https://github.com/CommunityToolkit/Maui/pull/1367/files#diff-aa117f97732d0f41c0b0444d0ac2415b30b30397a3243a5a166a5e141ff0362fR22 . Properties are meant to be cheap.

### Expected Behavior

`FrozenSet<T>` changes in https://github.com/CommunityToolkit/Maui/pull/1367 should be reverted, unless there are performance measurements performed to prove that `FrozenSet` performance characteristics are the right tradeoff in given situation.

### Steps To Reproduce

NA - found via codereview

### Link to public reproduction project repository

N/A

### Environment

```markdown
N/A
```

**Comment by brminnick** [comment]
Could you please provide performance benchmarks?

**Comment by jkotas** [comment]
> Could you please provide performance benchmarks?

I have found this issue by codereview (when looking at https://github.com/dotnet/runtime/issues/101427). I am sorry I do not have bandwidth to create performance benchmarks to prove the point.

The changes to switch over to `FrozenSet<T>` created in #1367 should have come with performance benchmarks in the first place. `FrozenSet<T>` should be only used for specific performance optimizations. It should not be used as a general exchange.
