### ISSUE TITLE
MAUI picker control support for Mac

### ISSUE THREAD

**Issue by 123JasonWang** [CommunityToolkit/Maui#1849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When using the MAUI Picker control, Windows works fine, but when running on Mac, the program crashes when clicking on the Picker control.

### Expected Behavior

Hopefully, MAUI will support controls like Picker or ComboBox on Mac.

### Steps To Reproduce

<Picker x:Name="picker"
        Title="Select a monkey">
  <Picker.ItemsSource>
    <x:Array Type="{x:Type x:String}">
      <x:String>Baboon</x:String>
      <x:String>Capuchin Monkey</x:String>
      <x:String>Blue Monkey</x:String>
      <x:String>Squirrel Monkey</x:String>
      <x:String>Golden Lion Tamarin</x:String>
      <x:String>Howler Monkey</x:String>
      <x:String>Japanese Macaque</x:String>
    </x:Array>
  </Picker.ItemsSource>
</Picker>

### Link to public reproduction project repository

none

### Environment

```markdown
- .NET MAUI CommunityToolkit:7.0.0
- OS:net8.0-maccatalyst
- .NET MAUI:8.0
```

**Comment by bijington** [comment]
Picker is provided by MAUI and not this toolkit. You can find their repository at: https://github.com/dotnet/maui
