### ISSUE TITLE
[BUG] Binding CommandParameter in a CollectionView Does Not Work

### ISSUE THREAD

**Issue by david-maw** [CommunityToolkit/Maui#1851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

A `LongPress `command initiated from a `Touchbehavior `within a `Collectionview `passes a null `CommandParameter`. This might be part of the more general binding issues that are being worked on at the moment but I couldn't find this specific problem. My XAML is below, it contains a `TapGestureRecognixer` as an example of how I expected it to work. Interestingly that also shows a difference in behavior on Windows and Android, Windows just invokes the long press command, Android also invokes the Tap command. 

``` XAML
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:CollectionView"
             xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
             BindingContext="{local:MainViewModel}"
             x:Name="Page"
             x:DataType="local:MainViewModel"
             x:Class="CollectionView.MainPage">

    <CollectionView ItemsSource="{Binding Path=People}">
        <CollectionView.ItemTemplate>
            <DataTemplate x:DataType="local:Person">
                <VerticalStackLayout x:Name="parentControl">
                    <VerticalStackLayout.Behaviors>
                        <toolkit:TouchBehavior
                            LongPressDuration="750"
                            LongPressCommand="{Binding Source={x:Reference Page}, Path=BindingContext.ShowLongPressCommand}"
                            CommandParameter="{Binding Source={x:Reference parentControl}, Path=BindingContext}"/>
                    </VerticalStackLayout.Behaviors>
                    <VerticalStackLayout.GestureRecognizers>
                        <TapGestureRecognizer Command="{Binding Source={RelativeSource AncestorType={x:Type local:MainViewModel}}, Path=ShowTapCommand}"    
                            CommandParameter="{Binding}"/>
                    </VerticalStackLayout.GestureRecognizers>
                    <Label Text="{Binding Name}" HorizontalOptions="Start" FontSize="Large"/>
                </VerticalStackLayout>
            </DataTemplate>
        </CollectionView.ItemTemplate>
    </CollectionView>
</ContentPage>
```
The tricky thing about commands inside a `ColllectionView `(for me anyway) is that the command itself is usually in the page `BindingContext `but the command parameter is in the current item BindingContext. So the BindingContext of the `Behavior/GetureRecognizer` etc. can't be set explicitly, it must to be inherited because that's how you get access to the current item in the `CollectionView`..  

### Expected Behavior

Same as the `TapGestureRecognixer`.

### Steps To Reproduce

1. Open and run the project from the reproduction project repository
2. tap and then long press on one of the names in the list and observe the difference. 

### Link to public reproduction project repository

https://github.com/david-maw/CollectionView.git

### Environment

```markdown
- .NET MAUI CommunityToolkit: 8.0.1
- OS: Windows 11, Android 14
- .NET MAUI: 8.0.7/8.0.100
```

**Comment by bijington** [comment]
You want to be using `LongPressCommandParameter` instead of `CommandParameter`.

**Comment by david-maw** [comment]
Yep, that's all it was, thanks - I got so wrapped up around the binding issues I missed that. The other things I noticed along the way are either already reported (relative binding) or not important, to me anyway (the Android behavioral difference), so I'll close this. Thanks again for the help.
