### ISSUE TITLE
Duplicate output filenames: fullscreen when using MediaElement

### ISSUE THREAD

**Issue by jfversluis** [CommunityToolkit/Maui#1862]
It seems that with the latest nightly (and maybe even stable now?) there are sometimes issues with a duplicate file name for the fullscreen icon file that is used in MediaElement.

We need to investigate how this happens and how to get rid of it!

---
[...] I am getting this error: Error: One or more duplicate file names were detected.  All image output filenames must be unique: fullscreen (/{path}/.nuget/packages/communitytoolkit.maui.mediaelement/99.0.0-build-1813.105074/buildTransitive/Images/fullscreen.svg), fullscreen (/{path}/.nuget/packages/communitytoolkit.maui.mediaelement/99.0.0-build-1813.105074/buildTransitive/Images/fullscreen.svg)

Any ideas?

_Originally posted by @briankanelson in https://github.com/CommunityToolkit/Maui/issues/1110#issuecomment-2074953533_

**Comment by luisabreu84** [comment]
> Can you provide more info? I created a sample project and tried both media element from latest source (99.0.0-preview1839) and from current release 3.1.1. I had zero issues. Is there a specific setting I need to set in csproj file? I am trying with `<MauiVersion>8.0.21</MauiVersion>` I tried `<MauiVersion>8.0.14</MauiVersion>` with the same result.
> 
> BTW #1813 was merged last week and is/was a PR that fixes ios crash issues and if you want to test the pr where the file was added you can test #1692 which added full screen support. Testing again earlier versions might be useful as you should get zero reference to file at all. It did not exist then.

@ne0rrmatrix could you please take a look to this comment, i described how you can reproduce it. Thanks. 
https://github.com/CommunityToolkit/Maui/issues/1110#issuecomment-2094217710

**Comment by ne0rrmatrix** [comment]
> > Can you provide more info? I created a sample project and tried both media element from latest source (99.0.0-preview1839) and from current release 3.1.1. I had zero issues. Is there a specific setting I need to set in csproj file? I am trying with `<MauiVersion>8.0.21</MauiVersion>` I tried `<MauiVersion>8.0.14</MauiVersion>` with the same result.
> > BTW #1813 was merged last week and is/was a PR that fixes ios crash issues and if you want to test the pr where the file was added you can test #1692 which added full screen support. Testing again earlier versions might be useful as you should get zero reference to file at all. It did not exist then.
> 
> @ne0rrmatrix could you please take a look to this comment, i described how you can reproduce it. Thanks. [#1110 (comment)](https://github.com/CommunityToolkit/Maui/issues/1110#issuecomment-2094217710)

I cannot replicate the issue without a sample. I have tried both the sample app from repo and I created my own. I have had zero success at creating the bug. Please provide or attach a sample that clearly demonstrates the issue.

**Comment by ne0rrmatrix** [comment]
possibly related issue found here: https://github.com/dotnet/maui/issues/19840 Will investigate further and see if they are related.

**Comment by luisabreu84** [comment]
Hi @ne0rrmatrix! any possible date to release this change? Thanks!

**Comment by luisabreu84** [comment]
hello! any news here? 
Thanks!

**Comment by ne0rrmatrix** [comment]
@luisabreu84 I am waiting on review and it looks good to go. Just need approval and then a maintainer with write privileges needs to push the changes.

**Comment by bijington** [comment]
I've approved with one minor comment 👍
