### ISSUE TITLE
[BUG] I'm unable to install the package into my project after version 7.0.1.

### ISSUE THREAD

**Issue by GlacierFox** [CommunityToolkit/Maui#1888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I'm trying to update my CommunityToolkit.Maui package to version 8.0.1 but I'm getting dependency errors in the output window.
```
NU1605: Warning As Error: Detected package downgrade: Microsoft.Maui.Controls.Compatibility from 8.0.14 to 8.0.7. Reference the package directly from the project to select a different version. 
 ProjectBureau -> CommunityToolkit.Maui 8.0.1 -> Microsoft.Maui.Controls.Compatibility (>= 8.0.14) 
 ProjectBureau -> Microsoft.Maui.Controls.Compatibility (>= 8.0.7)
Package restore failed. Rolling back package changes for 'ProjectBureau'.
```

I've installed `Microsoft.Maui.Controls` version `8.0.14` as per the comment at the bottom of [this](https://devblogs.microsoft.com/dotnet/dotnet-maui-community-toolkit-touchbehavior/) blog post but I'm still getting the above error even when I actually install version `8.0.7` of the Microsoft.Maui.Controls.Compatability package and right up to the newest version. (not sure why it wants a downgrade).  I've tried every combination of package version and I can't get the toolkit to update for some reason even when I update all packages to their latest versions. (8.0.40)

![image](https://github.com/CommunityToolkit/Maui/assets/9074086/0535e281-a36f-40cf-9009-bae74f2621fb)

### Expected Behavior

To be able to update the package.

### Steps To Reproduce

Create a quick new fresh MAUI project.

Install required version of Microsoft.Maui.Controls. 8.0.14

Try to update the Community Toolkit package to 8.0.0 / 8.0.1

### Link to public reproduction project repository

Happens in a fresh new project.

### Environment

```markdown
- .NET MAUI CommunityToolkit: 8.0.0?
- OS: Windows 11
- .NET MAUI: Controls version 8.0.14 and later
```

**Comment by brminnick** [comment]
> Install required version of Microsoft.Maui.Controls 8.0.14

Correct, the workaround is to manually install the following NuGet packages:
- `Microsoft.Maui.Controls v8.0.14`
- `Microsoft.Maui.Controls.Compatibility v8.0.14

**Comment by GlacierFox** [comment]
Hi @brminnick , thanks for the reply.

Yeah so the thing is, I've actually done that. I've currently got 

```
<ItemGroup>
	<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.14" />
	<PackageReference Update="Microsoft.Maui.Controls.Compatibility" Version="8.0.14" />
</ItemGroup>
```
in my .csproj.

I've completely removed version 7 of the `CommunityToolkit.Maui` package and I can't seem to install version 8+ It gives me this error.

```
Restoring packages for C:\Users\Danny\Documents\HLX_Workspace\DotNET_MAUI\ProjectBureau\ProjectBureau.csproj...
  GET https://api.nuget.org/v3-flatcontainer/dotnetmeteor.hotreload.plugin/index.json
  GET https://nuget.devexpress.com/uFsy1dNx4dIWeIzF4bV7NErIlL3RTU3cBzazOHGbQk7ee3acx7/api/FindPackagesById()?id='DotNetMeteor.HotReload.Plugin'&semVerLevel=2.0.0
  OK https://nuget.devexpress.com/uFsy1dNx4dIWeIzF4bV7NErIlL3RTU3cBzazOHGbQk7ee3acx7/api/FindPackagesById()?id='DotNetMeteor.HotReload.Plugin'&semVerLevel=2.0.0 186ms
  OK https://api.nuget.org/v3-flatcontainer/dotnetmeteor.hotreload.plugin/index.json 205ms
  CACHE https://api.nuget.org/v3/vulnerabilities/index.json
  CACHE https://api.nuget.org/v3-vulnerabilities/2024.05.16.05.31.08/vulnerability.base.json
  CACHE https://api.nuget.org/v3-vulnerabilities/2024.05.16.05.31.08/2024.05.16.05.31.08/vulnerability.update.json
NU1605: Warning As Error: Detected package downgrade: Microsoft.Maui.Controls.Compatibility from 8.0.14 to 8.0.7. Reference the package directly from the project to select a different version. 
 ProjectBureau -> CommunityToolkit.Maui 8.0.1 -> Microsoft.Maui.Controls.Compatibility (>= 8.0.14) 
 ProjectBureau -> Microsoft.Maui.Controls.Compatibility (>= 8.0.7)
Time Elapsed: 00:00:01.1335389
========== Finished ==========
```

Here's the output of dotnet list package too: 

```
 dotnet list package
Project 'ProjectBureau' has the following package references
   [net8.0-android34.0]:
   Top-level Package                               Requested   Resolved
   > CommunityToolkit.Mvvm                         8.2.2       8.2.2
   > DevExpress.Maui.CollectionView                23.2.3      23.2.3
   > DevExpress.Maui.Controls                      23.2.3      23.2.3
   > DevExpress.Maui.Editors                       23.2.3      23.2.3
   > DotNetMeteor.HotReload.Plugin                 3.*         3.2.0
   > Microsoft.Extensions.Http                     8.0.0       8.0.0
   > Microsoft.Extensions.Logging.Debug            8.0.0       8.0.0
   > Microsoft.Maui.Controls                       8.0.14      8.0.14
   > Microsoft.Maui.Controls.Compatibility         8.0.7       8.0.14
   > Microsoft.NET.ILLink.Tasks              (A)   [8.0.5, )   8.0.5

   [net8.0-ios17.2]:
   Top-level Package                               Requested   Resolved
   > CommunityToolkit.Mvvm                         8.2.2       8.2.2
   > DevExpress.Maui.CollectionView                23.2.3      23.2.3
   > DevExpress.Maui.Controls                      23.2.3      23.2.3
   > DevExpress.Maui.Editors                       23.2.3      23.2.3
   > DotNetMeteor.HotReload.Plugin                 3.*         3.2.0
   > Microsoft.Extensions.Http                     8.0.0       8.0.0
   > Microsoft.Extensions.Logging.Debug            8.0.0       8.0.0
   > Microsoft.Maui.Controls                       8.0.14      8.0.14
   > Microsoft.Maui.Controls.Compatibility         8.0.7       8.0.14
   > Microsoft.NET.ILLink.Tasks              (A)   [8.0.5, )   8.0.5

(A) : Auto-referenced package.
```

**Comment by GlacierFox** [comment]
@brminnick I've done it. Got it installed. No idea what I've done, just literally sat here installing, uninstalling and re-installing packages.
Perhaps some old metadata was holding it up or something, Closing this.
