### ISSUE TITLE
[BUG] AvatarView padding not working if ImageSource is set

### ISSUE THREAD

**Issue by filippomoretto** [CommunityToolkit/Maui#1930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Using an svg MauiImage as ImageSource of AvatarView, the image fills the entire control.

### Expected Behavior

![image](https://github.com/CommunityToolkit/Maui/assets/40571734/a8ebcc6d-9c9c-4743-8bad-0d994c6d0efd)

I would like the image to be positioned in the center keeping some distance from the edge of the control.

### Steps To Reproduce

1. `<MauiImage Update="Resources\Images\my_image.svg" BaseSize="32,32" TintColor="#FFFFFF" />`
2. `<toolkit:AvatarView HeightRequest="45" WidthRequest="45" CornerRadius="23" VerticalOptions="Start" HorizontalOptions="Start" 
                    ImageSource="my_image.png"
                    BackgroundColor="{Binding Color}" Padding="7" BorderWidth="0"/>`

### Link to public reproduction project repository

https://github.com/filippomoretto/TestAvatarViewPadding

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.1
- OS: Windows 11
- .NET MAUI: 8.0.40
```

### Anything else?

As a workaround I tried using the border instead of the padding, but the border is placed over the image so the result is the image of the same size as the control but cropped.

`avatarImage.SetBinding(WidthRequestProperty, new Binding(nameof(WidthRequest), source: this));
		avatarImage.SetBinding(HeightRequestProperty, new Binding(nameof(HeightRequest), source: this));`

I realize that it would be enough to make a new "CircleImage" control and put the image over a circle colored according to my needs instead of using AvatarView which as the name suggests is meant for slightly different purposes.

Sorry for my English.

**Comment by filippomoretto** [comment]
Functionality linked to #564

**Comment by filippomoretto** [comment]
For reproduction:
[AvatarViewPadding.zip](https://github.com/user-attachments/files/15816906/AvatarViewPadding.zip)

**Comment by bijington** [comment]
> For reproduction:
> 
> [AvatarViewPadding.zip](https://github.com/user-attachments/files/15816906/AvatarViewPadding.zip)
> 
> 

Can you please expose this via a public repository rather than a zip file?

**Comment by filippomoretto** [comment]
[https://github.com/filippomoretto/TestAvatarViewPadding/tree/e9873e838ba75ec1474272dc043239bf9753f73f/AvatarViewPadding](repo)

**Comment by filippomoretto** [comment]
[Repo](https://github.com/filippomoretto/TestAvatarViewPadding/tree/e9873e838ba75ec1474272dc043239bf9753f73f/AvatarViewPadding)

**Comment by bijington** [comment]
Thank you for sharing that

**Comment by GeorgeLeithead** [comment]
@bijington  I'll have a look at this, as I have an hour or two available today/tomorrow.

**Comment by bijington** [comment]
> @bijington  I'll have a look at this, as I have an hour or two available today/tomorrow.

Thanks @GeorgeLeithead that would be amazing

**Comment by GeorgeLeithead** [comment]
> > @bijington  I'll have a look at this, as I have an hour or two available today/tomorrow.
> 
> Thanks @GeorgeLeithead that would be amazing

Well, I would if I could get the MediaElement project to build!  Urgh! 
![image](https://github.com/CommunityToolkit/Maui/assets/43666574/c103066b-df08-4851-b616-0041c44262b1)

**Comment by bijington** [comment]
> > @bijington  I'll have a look at this, as I have an hour or two available today/tomorrow.
> 
> Thanks @GeorgeLeithead that would be amazing

🙁 I'm not sure what's going on there but the quick workaround is `Right click -> Unload project`

**Comment by GeorgeLeithead** [comment]
Looks like it is a BUG.

When we display the `UriImageSource` within an avatar, we currently only `clip` it:

`Width - (StrokeThickness * 2) - Padding.Left - Padding.Right
Height - (StrokeThickness * 2) - Padding.Top - Padding.Bottom`

We then apply the appropriate clip shape.  This results in the image dimensions matching the parent.
![image](https://github.com/CommunityToolkit/Maui/assets/43666574/904d2288-d738-492d-b9eb-00d643335178)

This however doesn't apply any distances applied, such as `Padding` or `BorderWidth` which should reduce the dimensions of the child element.  This is what should happen:
![image](https://github.com/CommunityToolkit/Maui/assets/43666574/22f7bd3c-54dc-484c-931c-eec6e3964290)

I believe I have a fix and will work on a PR, after I validate that there is no negative impact.
