### ISSUE TITLE
[BUG] App crashes on OnCaptureSucces callback when take a photo

### ISSUE THREAD

**Issue by czegreanu** [CommunityToolkit/Maui#1951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

App crashes

### Expected Behavior

App does not crash and you are able to capture a photo.

### Steps To Reproduce

1. Run Community Toolkit sample app on android
2. Go to Views -> CameraView Page
3. Grant camera permissions
4. Press on Capture Image button

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui

### Environment

```markdown
CommunityToolkit.Maui.Camera v1.0.1
```

### Anything else?

We integrated the new release **v1.0.1 of Camera** from **Community Toolkit** on a .Net MAUI project and when we take a photo the application crashes. We tested it only on **Android**. Also, we run the Community Toolkit sample app and we get the same crash when we press on Capture Image button from Camera View Page. We tested it on physical device and emulators as well.
 
It crashed on the following method **'public override void OnCaptureSuccess(IImageProxy image)' when it reached 	buffer.Get(imgData);  in class CameraManager.android.cs.**
 
The exception that we receive is:
 
[mono-rt]   --- End of managed Java.Nio.BufferUnderflowException stack trace ---
[mono-rt] java.nio.BufferUnderflowException
[mono-rt] 	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:251)
[mono-rt] 	at java.nio.ByteBuffer.get(ByteBuffer.java:559)
[mono-rt] 	at crc64f1558ff7e185dbfc.CameraManager_ImageCallBack.n_onCaptureSuccess(Native Method)
[mono-rt] 	at crc64f1558ff7e185dbfc.CameraManager_ImageCallBack.onCaptureSuccess(CameraManager_ImageCallBack.java:31)
[mono-rt] 	at androidx.camera.core.imagecapture.TakePictureRequest.lambda$onResult$2$androidx-camera-core-imagecapture-TakePictureRequest(TakePictureRequest.java:200)
[mono-rt] 	at androidx.camera.core.imagecapture.TakePictureRequest$$ExternalSyntheticLambda2.run(Unknown Source:4)
[mono-rt] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
[mono-rt] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
[mono-rt] 	at java.lang.Thread.run(Thread.java:1012)

We did a quick fix on the code that seems to work:
In **OnCaptureSuccess** method, replace the code with:

base.OnCaptureSuccess(image);
var planeProxy = image.GetPlanes()[0];
var buffer = planeProxy.Buffer;
var bytes = new byte[buffer.Remaining()];
buffer.Get(bytes);

var memStream = new MemoryStream(bytes);
cameraView.OnMediaCaptured(memStream);

**Comment by bijington** [comment]
Thank you for the report and code suggestion. I have opened PR #1961 to include those changes
