### ISSUE TITLE
[BUG] Resize popup problem on iOS

### ISSUE THREAD

**Issue by acaliaro** [CommunityToolkit/Maui#1974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

on iOS if the popup content resizes vertically, the popup does not resize (on Android, the popup resizes correctly)

![image](https://github.com/CommunityToolkit/Maui/assets/5759350/350500ab-1782-4071-b717-7afa80b88419)

![image](https://github.com/CommunityToolkit/Maui/assets/5759350/26c32eea-db54-4ba3-b17c-6364bd5bfa06)

### Expected Behavior

the popup should resize depending on the content

### Steps To Reproduce

Run the project
Press the "Popup resize problem" button
The popup appears. Press "press here"
The content of the popup changes, but the size of the popup does not

### Link to public reproduction project repository

https://github.com/acaliaro/MauiPopupResizeProblem

### Environment

```markdown
- .NET MAUI CommunityToolkit:9.0.1
- OS:iphone ios 17.3
- .NET MAUI:8.0.60
```

**Comment by cat0363** [comment]
@acaliaro , Is the behavior below the result you are expecting?

https://github.com/CommunityToolkit/Maui/assets/125236133/71102ddb-4e29-42f3-aebb-2fb9ba0e1a02

**Comment by acaliaro** [comment]
> @acaliaro , Is the behavior below the result you are expecting?
> 
>  iPhone.15.iOS.17.0.2024-06-25.10-09-50.mp4

Hi @cat0363 yes this is what I am expecting!! when popup is resised, if you press the "another button", does it works and open a DisplayAlert?

**Comment by cat0363** [comment]
@acaliaro , yes, that is also possible.

https://github.com/CommunityToolkit/Maui/assets/125236133/7b714759-6b61-406b-b5aa-cd128419a28f
