### ISSUE TITLE
[BUG] Snackbar background color light in dark mode on Android 14

### ISSUE THREAD

**Issue by kofanov** [CommunityToolkit/Maui#1982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I'm setting BackgroundColor = Colors.Black and TextColor = Colors.White in SnackbarOptions
On Android 13 background color appears black, but on Android 14 it is light gray.

### Expected Behavior

Display Background color as set

### Steps To Reproduce

await Current.MainPage.DisplaySnackbar("Text", null, "OK", TimeSpan.FromSeconds(5), new SnackbarOptions
{
    BackgroundColor = Colors.Black,
    TextColor = Colors.White
});

### Link to public reproduction project repository

none

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.1
- OS: Android 14 (API 34)
- .NET MAUI: 8.0.60
```

**Comment by dainius-r** [comment]
I can confirm, this issue still exists
