### ISSUE TITLE
[BUG] Camara package - Getting this Analyzer warning System.Resources.MissingManifestResourceException when Camera is included in the startup pipeline

### ISSUE THREAD

**Issue by egvijayanand** [CommunityToolkit/Maui#1991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Getting this Analyzer warning `System.Resources.MissingManifestResourceException` when Camera initialization is included in the MAUI startup pipeline.

### Expected Behavior

No such warning.

### Steps To Reproduce

* Add MAUI Camera package
* Add the Init code in the MAUI startup pipeline
* Build the project

### Link to public reproduction project repository

Default template of .NET 8 is suffice, just add Camera package and initialize in the startup

### Environment

```markdown
- .NET MAUI CommunityToolkit: Camera package v1.0.2
- OS: Windows 11
- .NET MAUI: .NET MAUI 8 SR6.1
```

### Anything else?

Nope

**Comment by egvijayanand** [comment]
Adding a reference to the Camera package in an MAUI Class Library also triggers this warning, not just the App.

**Comment by egvijayanand** [comment]
This is the exception message:
```
CSC : warning AD0001: Analyzer 'CommunityToolkit.Maui.CameraView.Analyzers.UseCommunityToolkitCameraInitializationAnalyzer' threw an
 exception of type 'System.Resources.MissingManifestResourceException' with message 'Could not find the resource "CommunityToolkit.M
aui.CameraView.Analyzers.Resources.resources" among the resources "CommunityToolkit.Maui.Camera.Analyzers.Resources.resources" embed
ded in the assembly "CommunityToolkit.Maui.Camera.Analyzers", nor among the resources in any satellite assemblies for the specified
culture. Perhaps the resources were embedded with an incorrect name.'. [E:\MauiLib2\MauiLib
2.csproj::TargetFramework=net8.0-windows10.0.19041.0]
```

**Comment by brminnick** [comment]
@jfversluis Did you do the work on adding the Analyzer to `CommunityToolkit.Maui.Camera`?

This reads like either a bug in our Analyzer or a bug in the tooling.

**Comment by jfversluis** [comment]
I did the work on this! 

Coincidentally I also released [a video](https://youtu.be/XFVrIyAzsk4) today. @egvijayanand can you confirm that what I show in this video is not working for you? Could you try this example here: https://github.com/jfversluis/MauiCameraViewSample

Because I did not run into this at all. You can see in the video that IntelliSense is acting up but I think that was my Visual Studio at the time.

**Comment by VladislavAntonyuk** [comment]
@jfversluis I was able to reproduce the issue. 
The interesting fact, is that it happens on the first build, after that, I can build and run the app without issues:
You can try https://github.com/VladislavAntonyuk/MauiSamples/tree/main/MauiBarcode

CI pipeline: https://github.com/VladislavAntonyuk/MauiSamples/actions/runs/9765801661/job/26957336716

**Comment by jfversluis** [comment]
Interesting! I think what might've happened is that I messed up some renaming. I just copied another analyzer project and renamed things. I'll look into it tomorrow.

**Comment by jfversluis** [comment]
@egvijayanand @VladislavAntonyuk would you be able to try the packages from #1996 ?

See instructions [here](https://github.com/CommunityToolkit/Maui/wiki/Preview-Packages#pull-requests-) if needed.

**Comment by VladislavAntonyuk** [comment]
@jfversluis the build failed

**Comment by VladislavAntonyuk** [comment]
@jfversluis the issue still exists
```
1>CSC : error AD0001: Analyzer 'CommunityToolkit.Maui.Camera.Analyzers.UseCommunityToolkitCameraInitializationAnalyzer' threw an exception of type 'System.Resources.MissingManifestResourceException' with message 'Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "CommunityToolkit.Maui.CameraView.Analyzers.Resources.resources" was correctly embedded or linked into assembly "CommunityToolkit.Maui.Camera.Analyzers" at compile time, or that all the satellite assemblies required are loadable and fully signed.'.
```

https://github.com/VladislavAntonyuk/MauiSamples/tree/camera

**Comment by jfversluis** [comment]
OK! Could you maybe try the version that just completed?

**Comment by VladislavAntonyuk** [comment]
Fixed
