### ISSUE TITLE
[BUG] Microsoft.Maui.Controls.Compatibility dependency

### ISSUE THREAD

**Issue by filipnavara** [CommunityToolkit/Maui#2005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

CommunityToolkit.Maui has a transitive dependency to `Microsoft.Maui.Controls.Compatibility` NuGet package. It means that consumers of `CommunityToolkit.Maui` now get the reference whether they want it or not.

Cursory test seems to show that there's very little code depending on the compatibility package (`IVisualNativeElementRenderer` usage in `TouchBehavior.macios.cs`) and `Color.ToAndroid()` extension method. The `ToAndroid` method usage can be replaced with `ToPlatform` extension method in the base MAUI package. Usage of `IVisualNativeElementRenderer` may be a bit more difficult to get rid of but probably solvable by getting rid of that compatibility kludge, using reflection, or rewriting it to detect the situation from the view hierarchy. 

### Expected Behavior

No dependency on `Microsoft.Maui.Controls.Compatibility`.

### Steps To Reproduce

1. Add `CommunityToolkit.Maui` NuGet dependency.
2. Observe that `Microsoft.Maui.Controls.Compatibility` gets transitively included.

### Link to public reproduction project repository

-

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.0
- OS: Android, iOS
- .NET MAUI: 8.0.61
```

**Comment by BaY1251** [comment]
Great

**Comment by GeorgeLeithead** [comment]
@vhugogarcia @brminnick I believe that this has already been merged into main and released, and as such i think this can be closed?

**Comment by brminnick** [comment]
Thanks George! Yup - this is completed via https://github.com/CommunityToolkit/Maui/pull/2006
