### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by NastyaZorro169** [CommunityToolkit/Maui#2007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Good afternoon
When building a project, such an error appears in the debugging information:

```
2>CSC : warning AD0001: Analyzer "CommunityToolkit.Maui.CameraView.Analyzers.UseCommunityToolkitCameraInitializationAnalyzer" created an exception of type "System.Resources.MissingManifestResourceException" with the message "Resources matching the specified culture or a neutral culture could not be found. Check the correct implementation or linking of "CommunityToolkit.Maui.CameraView.Analyzers.Resources.resources" with the "CommunityToolkit.Maui.Camera" build.Analyzers" at compile time, or make sure that all necessary companion assemblies are fully signed and can be downloaded.".
```

I don't know if this is related to this or not, but if you run the application with debugging on an android phone several times, the camera behaves strangely. It turns on and off. I found a small way to accurately turn on the camera during debugging is to change the camera Background, but this is not a good solution for further work.

### Expected Behavior

A working camera every time the application is opened during debugging

### Steps To Reproduce

I use the camera embedding in my project, as in this example: https://github.com/jfversluis/MauiCameraViewSample/tree/main

### Link to public reproduction project repository

https://github.com/jfversluis/MauiCameraViewSample/tree/main

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.1
- OS: Windows 11
- .NET MAUI: 8.0.61
```

**Comment by VladislavAntonyuk** [comment]
Fixed in 1.0.3
