### ISSUE TITLE
[BUG] [Memory leak] Critical MAUI memory leak in transient views

### ISSUE THREAD

**Issue by DarrenStasiak** [CommunityToolkit/Maui#2016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

In recent days our company discovered serious memory leak in MAUI i.e. views set as transient don't get disposed of correctly resulting in linear memory growth. Firstly we tried using MAUI wiki page on memory leaks, but while we were doing it we saw, that destructors in views weren't called on closing it at all. Our team decided to check official MAUI eshop demo, and we found same leak there. 

In demo we added GC.Collect, destructors to each view (on which we put a breakpoints) and label (under "Adventure Works'" title) that displays current heap size.

Examples below:

# Cheap size on startup:
![Pasted image 20240710125722](https://github.com/user-attachments/assets/d3725d63-533c-4fdf-8d4a-76014e5c4010)
# Heap size after opening and closing BasketView 10 times 
![Pasted image 20240710125812](https://github.com/user-attachments/assets/a1ba70aa-a548-4db2-825b-1fc9c71b58d9)

On opening and closing BasketView breakpoints weren't triggered single time and heap size kept increasing.

After deleting command from button in BasketView destructor started working.
![Pasted image 20240710140645](https://github.com/user-attachments/assets/36c19618-bb18-44c7-9954-8aacaae35e10)
![Pasted image 20240710130458](https://github.com/user-attachments/assets/9e7d16bf-5682-4e0a-8744-71447fb4c682)

# Questions
Why does it happen, is there some explanation to why MAUI behaves this way?
If it is not problem with MAUI, then where lays that issue?
Do we need to use some practices that aren't shown in official Microsoft demo?
 

### Expected Behavior

Memory not leaking

### Steps To Reproduce

1. Open repo and change BasketView.xaml.cs in ClientApp to include destructor and GC.Collect
![Pasted image 20240711211836](https://github.com/user-attachments/assets/c0cb5108-fe76-45ef-8a3e-ef4ea3681200)
2. Add those lines to CatalogView.xaml.cs
![image](https://github.com/user-attachments/assets/4cda23e5-e815-494f-8620-2cc58f310e96)
3. Add label to CatalogView.xaml
![Pasted image 20240711212135](https://github.com/user-attachments/assets/7936549b-4b52-4a2a-b4de-752321ba5ef6)
4. Run app and go in and out BasketView couple of times

### Link to public reproduction project repository

https://github.com/dotnet/eShop

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.2
- OS: Windows 10
- .NET MAUI: 8.0.70
```

**Comment by bijington** [comment]
I think this would be best reported in the .NET MAUI repository https://github.com/dotnet/maui
