### ISSUE TITLE
Popup is invisible in Screenshots[BUG] 

### ISSUE THREAD

**Issue by MauiUIui** [CommunityToolkit/Maui#2031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Not sure if this is a Toolkit or a MAUI bug but since I'm using the CommunityToolkit's popup service (and its `Popup` element), I'll just post here first.
Taking a screenshot using the "standard" MAUI way:
`IScreenshotResult screen = await Screenshot.Default.CaptureAsync();`
doesn't show the popup, but rather the current view behind it. 

### Expected Behavior

The popup content should be visible in the screenshot

### Steps To Reproduce

- Make a popup view and a viewmodel, like in the popup sample code and put a main `Border` in it. Put anything into the border to act like visual confirmation like some labels.
- Register as a TransientPopup in the MauiProgram.cs: `appBuilder.Services.AddTransientPopup<MyPopupV, MyPopupVM>();`
- Show the popup at some point (for example on mainpage's appearing) from the mainpage's viewmodel using:
`await _popupService.ShowPopupAsync<MyPopupVM>(vM => vM.Init(your args));`
- To make sure that the popup already showed up when taking the screenshot use your popup's main `Border` to take the screenshot, like:
```
<Border.GestureRecognizers>
    <TapGestureRecognizer Command="{Binding GestureCommand}" />
</Border.GestureRecognizers>
```
- Like microsoft's [example](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/device-media/screenshot?view=net-maui-8.0), the (async) command execute action of your GestureCommand from the viewmodel should then call:
```
IScreenshotResult screen = await Screenshot.Default.CaptureAsync();
Stream stream = await screen.OpenReadAsync();
return ImageSource.FromStream(() => stream);
```
- Saving the image to the (android) device using the code in [this](https://www.youtube.com/watch?v=OB65n17bR98) video by Gerald Versluis (too much [code](https://github.com/jfversluis/MauiDrawingViewSample/blob/main/MainPage.xaml.cs) to write here, used only android portion) would help to see the resulting image but there are certainly other ways.
-The resulting screenshot would only show the mainpage and no sign of the popup.

### Link to public reproduction project repository

No time, sorry

### Environment

```markdown
- .NET MAUI CommunityToolkit:9.0.1
- OS:Android (net8.0-android)
- .NET MAUI:8.0.40
```

**Comment by MauiUIui** [comment]
> Hi @MauiUIui. We have added the "needs reproduction" label to this issue, which indicates that we cannot take further action. This issue will be closed automatically in 5 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.

Well, I'm sorry to hear that, keep up the good work anyway 👍

**Comment by cat0363** [comment]
This problem occurs even if the alert dialog is displayed using the DisplayAlert method provided by MAUI.
I don't think this is limited to Popup.

[Case DisplayAlert]

https://github.com/user-attachments/assets/1c6d92f6-f484-4903-8a15-08ddcf7bee8b

In the verification video, DisplayAlert is displayed, a screenshot is taken 1 second later, and the Source of ImageView is replaced.
In the case of DisplayAlert, only the main page is photographed, similar to Popup.

The same goes for toast.

[Case Toast]

https://github.com/user-attachments/assets/5bbc9ad4-0eba-4632-b250-838ecd66be18

However, the Snackbar is photographed together with the main page.

[Case Snackbar]

https://github.com/user-attachments/assets/25324e25-f7ef-41d3-9e9f-998f5fd39466

As far as I have verified, DisplayAlert, Popup, and Toast do not appear in screenshots.

You may want to check the specifications to see whether the CaptureAsync method captures a view or something that is displayed on the entire screen, and then contact the necessary location.

If you look closely, the time at the top and the buttons at the bottom are not displayed in the screenshot image.

**Comment by MauiUIui** [comment]
@cat0363 Thank you for the nice feedback on that.
> the time at the top and the buttons at the bottom are not displayed in the screenshot image.

This I'm actually glad about. I wouldn't want it there tbh.

> CaptureAsync

MS doc: _Captures a screenshot of the current screen of the running application._
I don't know about you but for me a _screen_ should include anything showing since it's not a known previously defined name of anything.
I thnk it migght be time for the MAUI guys to take a look at that. I'll make sure they see it ;)

**Comment by MauiUIui** [comment]
OMG!
