### ISSUE TITLE
[BUG] Typo in `Camera` documentation for `Stop Preview`

### ISSUE THREAD

**Issue by GeorgeLeithead** [CommunityToolkit/Maui#2033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Current copy:
The CameraView provides the ability to programmatically **start** the preview from the camera. This is possible through both the StopCameraPreview method or the StopCameraPreviewCommand.

### Expected Behavior

Expected copy:
The CameraView provides the ability to programmatically **stop** the preview from the camera. This is possible through both the StopCameraPreview method or the StopCameraPreviewCommand.

### Steps To Reproduce

1. Go to the documentation.

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.2
- OS: N/A
- .NET MAUI: N/A
```

### Anything else?

[CameraView on Learn](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/camera-view?tabs=windows)

**Comment by GeorgeLeithead** [comment]
@ne0rrmatrix FYI

**Comment by GeorgeLeithead** [comment]
@zhitaop FYI

**Comment by bijington** [comment]
I think it's on me rather than the others. We also have a separate reo for the docs where we can open issues if it is specific to the docs

**Comment by GeorgeLeithead** [comment]
Doh! yes there is a separate repository, my bad.  Please close this and I'll rase in the CORRECT repo!
