### ISSUE TITLE
[BUG]  MediaElement Issue on Android - App Reopens on Last Visited Page and Background Audio Continues

### ISSUE THREAD

**Issue by vikher** [CommunityToolkit/Maui#2038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

On Android, when using .NET MAUI CommunityToolkit.MediaElement version 4.0 or higher, if you navigate into an app with 2 or more pages, swipe up to kill the app, and then reopen it, the app opens on the page where you left off.

### Expected Behavior

After swiping up to kill the app, it should reopen to the initial page, and any background audio should stop.

### Steps To Reproduce

1. Open the app on an Android device.
2. Ensure the app has at least 2 pages.
3. Navigate to a page with a media element.
4. Navigate to subsequent pages after the page with the media element.
5. Swipe up to kill the app.
6. Reopen the app.

### Link to public reproduction project repository

https://github.com/vikher/testmedia

### Environment

```markdown
.NET MAUI CommunityToolkit.Core: 9.0.2
.NET MAUI CommunityToolkit.MediaElement: 4.0.1
Microsoft.Maui.Controls: 8.0.70
Microsoft.Maui.Controls.Compatibility: 8.0.70
```

### Anything else?

- This issue is specific to Android devices.
- The problem seems to be related to changes in background playback introduced in version 4.0.
- When rolled back to version 3.1.1, the behavior is as expected, with the app reopening to the homepage and background audio stopping.

One video demonstrating the expected behavior with version 3.1.1.

https://github.com/user-attachments/assets/235b3410-9da7-4687-88d2-ce8149760dea

Another video showing the bug with version 4.0.1.

https://github.com/user-attachments/assets/4f94af75-5bc6-4958-ae39-581f2c6b4df2

These videos highlight the differences in behavior between the two versions and should assist in diagnosing and addressing the issue.

**Comment by Rogelio10Mancilla17** [comment]
We are experiencing the same issue on our Android app using .NET MAUI CommunityToolkit.MediaElement version 4.0 or higher. After swiping up to kill the app and reopening it, the app resumes on the page where it was left off instead of restarting from the initial page, and the background audio does not stop. We have verified this behavior following the same steps to reproduce mentioned in the original post. We hope for a fix that ensures the app reopens to the initial page with the background audio stopped, as it functions correctly when using version 3.1.1. Thank you for addressing this problem.

**Comment by SharpMobileCode** [comment]
Just came here to report the same bug.  We are seeing this behavior as well.  If the video is playing and the app is closed, you still hear the audio, even if you swipe up to kill the app.  Restarting the app goes back to the same page instead of starting at the start up page.

**Comment by ne0rrmatrix** [comment]
There is a linked PR out to fix this issue. Can you try out the PR and tell me if that solves your issue? It is linked above.

**Comment by cris-her** [comment]
I'm noticing the exact same issue and I need it fixed to continue with the development
