### ISSUE TITLE
[BUG] using MultiValueConverter causes "InvalidOperationException: Non-nullable are not valid"

### ISSUE THREAD

**Issue by BeepBeepBopBop** [CommunityToolkit/Maui#2046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

After updating the toolkit to the latest version (9.0.2), I get the following exception using VariableMultiValueConverter:

"InvalidOperationException: Non-nullable are not valid"

### Expected Behavior

No exception thrown. The code was working fine under the previous version  (9.0.1)

### Steps To Reproduce

Launch the app -> Exception gets thrown

### Link to public reproduction project repository

https://github.com/BeepBeepBopBop/VariableMultiConverter_Issue

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.2
- OS: Windows 11
- .NET MAUI: 8
```

**Comment by brminnick** [comment]
Duplicate https://github.com/CommunityToolkit/Maui/issues/2003
