### ISSUE TITLE
[BUG] Community toolkit project cannot build sample project

### ISSUE THREAD

**Issue by ne0rrmatrix** [CommunityToolkit/Maui#2056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Open visual studio with sample project.
You cannot run sample project in IOS, Mac, Windows or Android

### Expected Behavior

You should be able to build and run the project on all supported devices

### Steps To Reproduce

Open sample from this repo.
You cannot build or run app.

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui/tree/main/samples

### Environment

```markdown
- .NET MAUI CommunityToolkit: current main
- OS: ALL
- .NET MAUI: 8.0.21
```

### Anything else?

Please revert removal of  ```<UseMaui>true</UseMaui>``` from csproj file.

**Comment by GeorgeLeithead** [comment]
I get it to build, but it won't deploy, and does not provide any further (relevant) information than this, even when `Output Verbosity` is set to `Diagnostic`:

```
7>------ Deploy started: Project: CommunityToolkit.Maui.Sample, Configuration: Debug Any CPU ------
7>Deploy failed
========== Build: 6 succeeded, 0 failed, 3 up-to-date, 0 skipped ==========
========== Build completed at 14:55 and took 36.458 seconds ==========
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========
========== Deploy completed at 14:55 and took 36.458 seconds ==========

> Deploy started at 14:54 and took 36.335 seconds
```
