### ISSUE TITLE
[BUG] Prefixing a RelayCommand method name with "On" causes command to not trigger

### ISSUE THREAD

**Issue by kiddailey** [CommunityToolkit/Maui#2065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When the name of a RelayCommand is prefixed with "On", the command will never be triggered.  For example:

```
[RelayCommand]
void OnTextChanged()
{
    // Do something.
}
```

### Expected Behavior

The command should trigger as expected.

### Steps To Reproduce

Given the following XAML:

```
<Editor Text="{Binding MyText}">
    <Editor.Behaviors>
        <toolkit:EventToCommandBehavior
            EventName="TextChanged"
            Command="{Binding OnTextChangedCommand}" 
            />
    </Editor.Behaviors>
</Editor>
```

The following RelayCommand will never be triggered:

```
public class MyViewModel
{
    [RelayCommand]
    void OnTextChanged()
    {
        // Do something.
    }

    [ObservableProperty]
    string _myText;
}
```

However, if you instead remove the "On" prefix on the command, it will work as expected:

```
<Editor Text="{Binding MyText}">
    <Editor.Behaviors>
        <toolkit:EventToCommandBehavior
            EventName="TextChanged"
            Command="{Binding TextChangedCommand}" 
            />
    </Editor.Behaviors>
</Editor>
```

```
public class MyViewModel
{
    [RelayCommand]
    void TextChanged()
    {
        // Do something.
    }

    [ObservableProperty]
    string _myText;
}
```

It is worth nothing that using ICommand directly instead of the RelayCommand decorator works as expected, even with the "On" prefix:

```
<Editor Text="{Binding Text}">
    <Editor.Behaviors>
        <toolkit:EventToCommandBehavior
            EventName="TextChanged"
            Command="{Binding OnTextChanged}" 
            />
    </Editor.Behaviors>
</Editor>
```

```
public class MyViewModel
{
    public ICommand OnTextChanged { get; set; }

    public MyViewModel()
    {
        OnTextChanged = new Command(HandleTextChanged);
    }

    void HandleTextChanged()
    {
        // Do something.
    }

    [ObservableProperty]
    string _myText;
}
```

### Link to public reproduction project repository

In progress

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.2
- OS: 11
- .NET MAUI: 8
```

### Anything else?

It may be improper to name commands with "On," and this may be more of a naming convention than a bug, but I am unsure because I couldn't find anything in the documentation or online about the use of "On" in command names.  It would be nice if the documentation for RelayCommand mentioned this detail at the very least to save someone else from thinking that something else was the issue :)

**Comment by bijington** [comment]
The functionality you are referring to is not provided by this toolkit. The toolkit you want is at: 

Following on though I do believe the rule is that the On prefix will be removed. The use of the On prefix is a common pattern when writing the methods manually. As it reads OnSomethingHappening. Is there not documentation relating to this in intellisense in Visual Studio?

Further to this I would thoroughly recommend using Compiled Bindings https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/compiled-bindings?view=net-maui-8.0 because the compiler will error when you refer to something that doesn't exist.

**Comment by vhugogarcia** [comment]
Thanks @kiddailey for posting the issue. However, as our friend @bijington mentioned it, this issue belongs to https://github.com/CommunityToolkit/dotnet feel free to post the issue on that repository.

I'm closing the issue for the reason mentioned above.
