### ISSUE TITLE
[BUG] Media Element Windows Crash on Exit

### ISSUE THREAD

**Issue by ne0rrmatrix** [CommunityToolkit/Maui#2066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When playing video with MediaElement and you click on close window it can crash intermittently. 

### Expected Behavior

When you click close while playing video/audio it should not crash.

### Steps To Reproduce

1. Open solution from Repository.
2. Run solution.
3. Navigate to MediaElement.
4. Exit app while media is playing.

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui/tree/main/samples

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.2
- OS: Windows 10 Build 10.0.19041.0
- .NET MAUI: 8.0.60
- .NET MAUI MediaElement: 3.x - current Main
```

### Anything else?

This issue has been ongoing for more than a year.

https://github.com/user-attachments/assets/04e07a57-5476-4a1b-83ee-267215ffa693

**Comment by chadalon** [comment]
I'm new to MAUI and my project is consistently reproducing this bug. Glad to see you've put out a fix!
