### ISSUE TITLE
[BUG] TouchBehavior Memory Leak once the behavior has been included in a DataTemplate

### ISSUE THREAD

**Issue by sstobinski** [CommunityToolkit/Maui#2082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I have noticed the following problem. As soon as I want to use the touch behavior from the CommunityTool in a DataTemplate, the GarbageCollector no longer manages to clear this and all parent elements from memory.
This problem does not exist with the GestureRecognizer.

I provide a small example application for this.

### Expected Behavior

The expected behavior would be that the GarbageCollector manages to delete the TouchBehavior from memory.

### Steps To Reproduce

In this sample application you can navigate from the MainPage to a page with the implementation of the GestureRecognizer and to a page with the implementation of the Touch behavior. As soon as you navigate back from the respective page to the MainPage, the current memory is displayed in a list. Here you can see the exponential increase in memory when you navigate back and forth between the MainPage and the page with the Touch behavior. If you navigate between the MainPage and the page with the implementation of the GestureRecognizer, the memory remains constant.

I have also implemented the MemoryToolKit by Adam Essenmacher to observe in the debug output which objects are successfully thrown out of memory and which are not.

### Link to public reproduction project repository

https://github.com/sstobinski/TouchBehavior_MemoryLeak

### Environment

```markdown
- .NET MAUI: 8.0.61/8.0.100         SDK 8.0.300
- Microsoft.Maui.Controls: 8.0.61
- Microsoft.Maui.Controls.Compatibility: 8.0.61
- .NET MAUI CommunityToolkit: 9.0.2
- AdamE.MemoryToolkit.Maui: 1.0.0
```

**Comment by DavidV1603** [comment]
I am experiencing the same issue in my app, resulting in huge memory leaks when navigating back and forward in pages that contain elements with the TouchBehavior. I could not find a way to prevent this problem or any way, to detect long-presses without leakage.

**Comment by dantelegacyheating** [comment]
I am also experiencing this issue. Pages are never destroyed if they contain any TouchBehaviors inside DataTemplates.

**Comment by pictos** [comment]
I couldn't reproduce the issue, downloaded you repro and tried on my end. I did some changes, like adding a button to force a collection, and as you can see the memory isn't increasing.

![GC_Collect_TouchBehavior_issue](https://github.com/user-attachments/assets/dcafae66-d456-4bf6-ac42-1c9c4aadec61)

**Comment by DavidV1603** [comment]
With the demo-repo on Windows I do not run into the problem. But when testing on Android, it increases rapidly when navigating between the TouchBehaviorPage and back.

Maybe this is a mobile-only problem?

**Comment by DavidV1603** [comment]
@pictos And it should not be required to manually force the Garbage-Collectors collect when navigating between pages, or am I understanding your test wrong? With gesture recognizer and all the other UI elements, this is not necessary, why should it be for the TouchBehavior?

**Comment by bijington** [comment]
> @pictos And it should not be required to manually force the Garbage-Collectors collect when navigating between pages, or am I understanding your test wrong? With gesture recognizer and all the other UI elements, this is not necessary, why should it be for the TouchBehavior?

The aim of forcing garbage collection here is not to propose that as a solution but it provides a mechanism of reliably knowing when garbage collection is taking place and then also seeing the results of the collection. This allows us to determine if there is a leak but if the TouchBehavior is no longer in memory after the collection then it isn't leaking

**Comment by pictos** [comment]
I'll take a look on android target asap then... Adding to the comment from @bijington, the GC doesn't work like a reference counting (what swift has), so if you navigate back from your page, it can be marked to be GCollected, but that will not happen ASAP, will happen when GC decides to do it, so it's a `no deterministic` operation, and because of that you may see the object alive for a while.
