### ISSUE TITLE
[BUG] IconTintColorBehavior is randomly not applied when navigate to another page on IOS

### ISSUE THREAD

**Issue by TheSundayDev** [CommunityToolkit/Maui#2094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

the image color in the new page is the default one and not the not specified in the IconTintColorBehavior 

### Expected Behavior

the image color in the new page must be the one specified in the IconTintColorBehavior 

### Steps To Reproduce

1. Create a new project
2. Create a new page with an image (or image button) and set IconTintColorBehavior  to red color for example
3. Navigate to this new page using PushModalAsync. The IconTintColorBehavior of the image (or image button) is set randomly, not always is applied.
4. Navigate Back on main page also some IconTintColorBehavior are reset to default

### Link to public reproduction project repository

-

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.2
- OS: IOS
- .NET MAUI: 8.0.61
```

**Comment by brminnick** [comment]
Duplicate https://github.com/CommunityToolkit/Maui/issues/1957
