### ISSUE TITLE
[BUG] Camera View control is not refocusing on Android.

### ISSUE THREAD

**Issue by AlejandroHV** [CommunityToolkit/Maui#2103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Camera View control is not refocusing on Android. I just created a simple sample project with the Camera view control and ran the application in Android it does not changes focus, the only way to get it working is to switch between the cameras and when the camera loads it gets the focus appropriately but when adding an object closer it does not works. I tested the  same feature with the MediaPicker.Default.CapturePhotoAsync() and it worked as expected. I just created a video of the issue on my phone[https://drive.google.com/file/d/1XDBdl6HkAlS2Eyo2UZYN_GnmuI675hBt/view?usp=share_link](url). 
I tested the application in IOS and the focus works appropriately. 

Workloads version: 
maui-tizen                 8.0.61/8.0.100         SDK 8.0.300        
ios                        17.2.8078/8.0.100      SDK 8.0.300        
maccatalyst                17.2.8078/8.0.100      SDK 8.0.300        
android                    34.0.113/8.0.100       SDK 8.0.300    

.NET Version: 8

Device: Xiaomi Redmi Note 13 pro+ 5g.  OS Version: Xiaomi HyperOS: 1.0.4.0. 

`  .xaml 

 <Grid RowDefinitions="Auto,*,40,40" ColumnDefinitions="*,*,*,*" BackgroundColor="Black">
            <Label Text="Camera" TextColor="White" Grid.Row="0" Grid.Column="0" Grid.ColumnSpan="4"/>
           
            
            <Border Grid.Row="1" Grid.Column="0" Grid.ColumnSpan="4" StrokeShape="RoundRectangle" >
                <toolkit:CameraView x:Name="CameraView" MediaCaptured="CameraView_OnMediaCaptured" 
                        />
            </Border>
            <Button Grid.Row="2" Grid.Column="0" FontSize="10" Text="Switch Camera" Clicked="CameraSwitch_OnClicked"></Button>
            <Button Text="Capture " Clicked="Button_OnClicked"  FontSize="10" Grid.Row="2" Grid.Column="1"  ></Button>
            <Button Text="Flash" Clicked="Flash_OnClicked" FontSize="10" Grid.Row="2" Grid.Column="2"   />
            <Button Text="+" Clicked="ZoomIn_OnClicked" FontSize="10" Grid.Row="2" Grid.Column="3"   ></Button>
            <Button Text="-" Clicked="ZoomOut_OnClicked" FontSize="10" Grid.Row="3" Grid.Column="0"   />
        </Grid>

.xaml.cs

private async  void Button_OnClicked(object? sender, EventArgs e)
    {
        
        await  CameraView.CaptureImage(CancellationToken.None);
    }

    private async void CameraView_OnMediaCaptured(object? sender, MediaCapturedEventArgs e)
    {
        if (Dispatcher.IsDispatchRequired)
        {
            Dispatcher.Dispatch( async () => await Navigation.PushAsync(new Tagging()
            {
                BindingContext = new TaggingViewModel()
                {
                    CurrentImage = ImageSource.FromStream(() => e.Media)
                }
            })); 
        }
        

        //Image.Source = ImageSource.FromStream(() => e.Media);
    }`

### Expected Behavior

Camera View should automatically adjust the focus as the native camera of the phone. 

### Steps To Reproduce

1. Add the Camera View control on a xaml. 
2. Run the app. 
3. Play with the focus of the camera changing objects. 

### Link to public reproduction project repository

https://drive.google.com/file/d/1XDBdl6HkAlS2Eyo2UZYN_GnmuI675hBt/view?usp=share_link

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.2
- OS: Android Xiaomi Hyper OS
- .NET MAUI: 8.0.6
```

**Comment by pictos** [comment]
@AlejandroHV can you please add a title to this issue?

**Comment by AlejandroHV** [comment]
@pictos Done

**Comment by pictos** [comment]
Not sure if it's a bug or something that isn't implemented... I believe that we don't implemented the auto-focus, but need to double check. I believe that you can extend the current camera view to add it on the CameraManager

**Comment by AlejandroHV** [comment]
Hi @pictos. Is there an example of how to extend the CameraManager or any of the tools from the CommunityToolkit. 
Additionally is there a default image resolution/ quality the Camera View has? For me the quality of the images taken is lower that the regular one control in MAUI.

**Comment by pictos** [comment]
There's no example, AFAIK, but you should be able to inherit from `CameraManager` and override the necessary code to make it work for you.

about the resolution, on android you can take a look [here](https://github.com/CommunityToolkit/Maui/blob/main/src/CommunityToolkit.Maui.Camera/CameraManager.android.cs#L71)

**Comment by Jake-Derrick** [comment]
For me, auto focus worked when opening the camera the first time. After stopping and starting the CameraPreview, auto focus would no longer work.

In CameraManager.android.cs there is
```csharp
//start the camera with AutoFocus
MeteringPoint point = previewView.MeteringPointFactory.CreatePoint(previewView.Width / 2.0f, previewView.Height / 2.0f, 0.1f);
FocusMeteringAction action = new FocusMeteringAction.Builder(point)
    .DisableAutoCancel()
    .Build();
```

Removing `.DisableAutoCancel()` fixed the issue for me.

**Comment by AlejandroHV** [comment]
@Jake-Derrick @pictos   So I would have to branch off the Camera project and make the modifications and then add it to my project?

**Comment by bijington** [comment]
We should get this change into a PR if it solves the issue
