### ISSUE TITLE
[BUG] Referencing the .NET MAUI Toolkit in a .NET MAUI 9 Preview 7 project fails to build

### ISSUE THREAD

**Issue by egvijayanand** [CommunityToolkit/Maui#2120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Referencing the .NET MAUI Toolkit in a .NET MAUI 9 Preview 7 project fails to build.

Processing Resources failed with the error: Duplicate Entry.

Kindly look into this earlier issue: [#7420](https://github.com/dotnet/maui/issues/7420)

### Expected Behavior

The project should build without any errors.

### Steps To Reproduce

1. Create a new .NET MAUI 9 Preview 7 project
2. Add a reference to .NET MAUI Toolkit
3. Build the project

### Link to public reproduction project repository

Default template is suffice, just add a reference to .NET MAUI Toolkit

### Environment

```markdown
- .NET MAUI CommunityToolkit: v9.0.2
- OS: Windows 11 (10.0.22631.3958)
- .NET MAUI: 9.0.0-preview.7.24407.4
```

### Anything else?

Build log:

You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  MauiApp3 net9.0-windows10.0.19041.0 failed with 2 error(s) (30.3s) → bin\Debug\net9.0-windows10.0.19041.0\win10-x64\MauiApp3.dll
    WINAPPSDKGENERATEPROJECTPRIFILE : error : PRI175: 0x80073b0f - Processing Resources failed with error: Duplicate Entry.
    WINAPPSDKGENERATEPROJECTPRIFILE : error : PRI277: 0x80073b0f - Conflicting values for resource 'Files/Microsoft.Maui/Platform/Windows/Styles/WindowRootViewStyle.xbf'

**Comment by brminnick** [comment]
Hi Vijay! We don't currently support .NET 9. 

We will release .NET 9 support once it GAs in November 👍

**Comment by egvijayanand** [comment]
> Hi Vijay! We don't currently support .NET 9.
> 
> We will release .NET 9 support once it GAs in November 👍

Not ever for critical build issues? That's a surprise to hear.

**Comment by brminnick** [comment]
.NET 9 is in Preview. 

Same as Microsoft, we don't support non-GA versions of .NET.

**Comment by DDHSchmidt** [comment]
To anyone else desperately trying to test .Net 9 and reading this: It might be worth playing a game of whack-a-mole with your NuGet dependencies.
I got the exact same error as the original poster. Through a time-consuming trial & error session I found out that the build works, if I make sure that [BarcodeScanning.Native.Maui](https://github.com/afriscic/BarcodeScanning.Native.Maui) is excluded , when building for windows:
```
<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) != 'windows'">
	<PackageReference Include="BarcodeScanning.Native.Maui" Version="1.5.7" />
</ItemGroup>
```

That needed some other "fun" workarounds in my Xaml, where I now had to avoid the namespace for its controls like the plague, but after figuring that out and removing it from my windows build pipeline completely, the error disappeared.

**Comment by egvijayanand** [comment]
For me, the build error occurs immediately after creating the project from the plain template, with only this toolkit added.

**Comment by Stedy59** [comment]
> .NET 9 is in Preview.
> 
> Same as Microsoft, we don't provide support for non-GA versions of .NET.

We?

**Comment by bijington** [comment]
The team that work on this toolkit
