### ISSUE TITLE
[Proposal] Project Reorganization

### ISSUE THREAD

**Issue by pictos** [CommunityToolkit/Maui#213]
# Project Reorganization
* [x] Proposed
* [x] Prototype: Not Started
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Sample

## Link to Discussion

- https://github.com/CommunityToolkit/Maui/discussions/208

## Summary
[summary]: #summary

We will change the project structure to mimic the .NET MAUI structure, placing all code that doesn't use `Microsoft.Maui.Controls` into a new project, `CommunityToolkit.Maui.Core`.

This creates a new NuGet Package, `CommunityToolkit.Maui.Core` that new Toolkits like `CommunityToolkit.Comet` can leverage.

![](https://user-images.githubusercontent.com/13558917/145694198-7addbd35-0e5f-4816-b351-759a01ec2672.png)

## Motivation
[motivation]: #motivation

Make our implementation as close as possible from .NET MAUI implementation, which will make it possible to easily support frameworks that are built on top of .NET MAUI and promote our features to the .NET MAUI.

## Detailed Design
[design]: #detailed-design

![image](https://user-images.githubusercontent.com/20712372/145692003-db90c860-a0a6-4243-8046-02c656a2b56f.png)

## CommunityToolkit.Maui.Core

In general, this project will have all the basement to develop our Toolkit, including some primitive types, interfaces and base classes, base views, and common code. This will be referenced by other Frameworks/Toolkit based on .NET MAUI that wants to have the same features that us.

Here we will have some:

- BaseViews, could be `Views` that will be used by other Views, like [`PaddingButton`](https://github.com/CommunityToolkit/Maui/blob/pj%2Freorganize-project/src/CommunityToolkit.Maui.Core/Platform/iOS/PaddedButton.ios.cs) (that's used by Snackbar) or the [`MCTPopup`](https://github.com/CommunityToolkit/Maui/blob/pj%2Fpopup-port/src/CommunityToolkit.Maui/Platform/Android/MCTPopup.android.cs) that will be a native control implemented in a way that can work with our handler. This same approach is used [here](https://github.com/dotnet/maui/blob/main/src/Core/src/Platform/iOS/MauiLabel.cs)

- Primitives, which will be base types that can be used by everyone, like our [`MathOperator`](https://github.com/CommunityToolkit/Maui/blob/pj%2Freorganize-project/src/CommunityToolkit.Maui.Core/Primitives/MathOperator.shared.cs). So other frameworks may not have the concept of `Behavior` or `Converter` but they can mimic them as helper classes/methods and use our primitives.

- Common Code, this will be all generic code (platform-specific or not) that can be used by other Frameworks/Toolkits

- Layout Managers, were introduced on .NET MAUI and [they live on `Microsoft.Maui.Core`](https://github.com/dotnet/Maui/blob/main/src/Core/src/Layouts/AbsoluteLayoutManager.cs) so makes sense to have our managers on `Core` as well.

- Handlers, on Core will be the most general Handler with the majority of features.

## CommunityToolkit.Maui:

This project has a reference to the `Core` project. Here will live the implementation of our Controls, Views, Behaviors, Animations, etc. In other words, this project will work with the .NET MAUI and will be MVVM friendly. Also, other Toolkits/Frameworks can reference this package if needed.

Here we will have some:

- View Implementation, with `BindableProperties`, support to attach effects, behaviors, triggers, and all that jazz. 

- Platform Configuration, that is Platform-specific features, that can relate to some control - like the `ArrowDirection` that is part of Popup and works just on iOS - or the application itself - like the `StatusBarColorEffect` from XCT.

- Handlers Implementation, We will add to our `PropertyMapper` and/or `CommandMapper` any Platform Configuration that some Handler/View may have. We also can implement here some features that we think will not be great to have on `Core`. [Here is a reference for this](https://github.com/dotnet/maui/tree/main/src/Controls/src/Core/HandlerImpl/Button)

- Layout, will be the implementation of ours custom layouts and will use the Layout Managers on `Core`

## Drawbacks
[drawbacks]: #drawbacks

- Adds an additional NuGet packages
  - Requires adjustments to the CI Pipeline to publish two Nuget Packages 
  - Additional dependencies increase compilation 
- Reorganizing the entire project may lead to unintentional breaking changes
  - This work requires touching every file; some files may be forgotten, some files may be miscopied

**Comment by brminnick** [comment]
I see two benefits to rearchitecting the repo:
- More-easily promote our code into the .NET MAUI repo if the namespaces are aligned
- Share code with future Toolkits, like `CommunityToolkit.Comet` and `CommunityToolkit.Blazor`

I prefer to create a new repository for future frameworks such as `CommunityToolkit.Maui.Comet` and `CommunityToolkit.Maui.Blazor` so that we can keep their DevOps pipelines and release schedules separate from `CommunityToolkit.Maui`, similar to how we are handling `CommunityToolkit.Maui.Markup`

This means that we would publish two NuGet Packages from this repo:
- CommunityToolkit.Maui
- CommunityToolkit.Maui.Core

Here's my recommendation:
- Create a new CSPROJ, `CommunityToolkit.Maui.Core`
  - Move all Interfaces and common code to this new CSPROJ
  - Create a new NuGet Package: `CommunityToolkit.Maui.Core`
- Keep the current name of `CommunityToolkit.Maui` instead of renaming it to `CommunityToolkit.Maui.Controls`
  - Renaming the project to `CommunityToolkit.Maui.Controls` requires renaming the NuGet package
  - The `CommunityToolkit.Maui` NuGet Package will then have a dependency on the `CommunityToolkit.Maui.Core` NuGet Package
  - In the `dotnet/maui` repo, `[InternalsVisibleTo]` [is already enabled for `CommunityToolkit.Maui`](https://github.com/dotnet/maui/pull/1970)
    - Right now, we are experiencing breaking changes in `Snackbar.android.cs` because it cannot access internals 
- Do not follow the `dotnet/maui` folder structure
  - I'd like to avoid their confusing + unnecessary nesting e.g. `src/core/src/core...`

### Recommended Architecture

```bash
CommunityToolkit/Maui
└───src
│   │   CommunityToolkit.Maui.sln
│   │
│   └───CommunityToolkit.Maui
│       │   CommunityToolkit.Maui.csproj
│   └───CommunityToolkit.Core
│       |   CommunityToolkit.Maui.Core.csproj
│   └───CommunityToolkit.UnitTests
│       |   CommunityToolkit.Maui.UnitTests.csproj
└───samples
    │   CommunityToolkit.Maui.Samplescsproj
```

**Comment by brminnick** [comment]
My other question is "Will we actually share code between other toolkits like `CommunityToolkit.Maui.Comet`?

Looking at the [Comet source code](https://github.com/dotnet/comet), I'm not sure how much code we would be able to share between `CommunityToolkit.Maui` and `CommunityToolkit.Comet`. 

For example, Comet doesn't use Converters (that's mostly an MVVM/XAML thing), Comet doesn't have Behaviors, Comet uses its own unique Animation implementation and Comet creates its own Controls (e.g. it provides its own implements of `IButton`, `IImage`, etc.).

**Comment by VladislavAntonyuk** [comment]
I suggest to keep in CommunityToolkit.Maui.Core only interfaces and base classes, so it will be platform agnostic (net6.0).
We put ISnackbar, BaseAnimation, IValidator etc here.

Then CommunityToolkit.Maui contains animations, converters, validators, but not Controls (Views). So it can be net6.0 as well. This library doesn't need UseCommunityMauiToolkit().

Finally CommunityToolkit.Maui.Controls implementation contains only controls and depends on Platforms.

**Comment by pictos** [comment]
@brminnick I agree with everything in your first comment, I'll apply those changes and push them to my working branch.

About the Comet, as you can see [here](https://github.com/dotnet/Comet/blob/3625b1d88ec42ec0d5ab7b173117f3f038831b2c/src/Comet/Controls/ControlsGenerator.cs) controls are generated using Source Generator, the input needed is the interfaces, so Comet will need just to reference the `CommunityToolkit.Maui.Core`. About other features like Behaviors, Converters, etc we don't need to share with Comet if there's no support for it.

I'll add @Clancey to add anything else.

Expanding a little bit, I believe that any UI framework built on top of .NET MAUI can reference `CommunityToolkit.Maui.Core`.

**Comment by pictos** [comment]
@VladislavAntonyuk 

I'm not sure if makes sense to restrict one package to be platform agnostic, as you can see [here](https://github.com/dotnet/maui/blob/main/src/Core/src/MauiContext.cs) this class lives in `Core` and has platform code.

Are you suggesting to have three `csproj`s? 
How that will be in terms of NuGet, will we release one NuGet per package, or we can merge `Core` and `Controls` into a single package? 
Why split Views and other features (Animation, behaviors, etc)?

**Comment by saint4eva** [comment]
> ### Will we actually share code between other Toolkits?
> Looking at the [Comet source code](https://github.com/dotnet/comet), I'm not sure how much code we would be able to share between `CommunityToolkit.Maui` and `CommunityToolkit.Comet`.
> 
> For example, Comet doesn't use Converters (that's mostly an MVVM/XAML thing), Comet doesn't have Behaviors, Comet uses its own unique Animation implementation and Comet creates its own Controls (e.g. it provides its own implements of `IButton`, `IImage`, etc.).
> 
> If there isn't a future where new toolkits would leverage `CommunityToolkit.Maui.Core`, does it make sense to separate it into its own CSPROJ + its own NuGet Package?

`CommunityToolkit.Maui.Comet`  -  Comet app model
`CommunityToolkit.Maui.Blazor` - Blazor app model
`CommunityToolkit.Maui.Controls`  -  Xaml app model
`CommunityToolkit.Maui.Fabulous`  -  Fabulous app model

**Comment by pictos** [comment]
@VladislavAntonyuk I'm sorry for the late reply, yesterday was a rush day.

So I can see what you mean, and I would say that we don't need more than 2 projects. From the MS.SDK project style all platforms targets have the NET 6 reference, so if we don't want to throw `NotImplementedException` we can do that by not adding the NET 6 as a TFM, in other words, that project can be referenced, just by the platforms that we add as TFM.

Also, since this project targets specific platforms (mobile and desktop) it's fine, IMHO, that we have platform code on `Core` and `CommunityToolkit` projects.

**Comment by VladislavAntonyuk** [comment]
@pictos no problem.

if we do not include net6.0 in target frameworks we will receive an issue similar to this: https://github.com/xamarin/XamarinCommunityToolkit/issues/1645

Maybe we can rename Core to Shared in that case we receive
- CommunityToolkit.Maui.Shared (it includes all control interfaces and platform-agnostic code like validators and converters)
- CommunityToolkit.Maui (if we want to keep the original name) or CommunityToolkit.Maui.Controls (which doesn't include net6.0 and contains all platform-specific code)

**Comment by pictos** [comment]
@VladislavAntonyuk this makes sense to me. Like, if someone references the `Controls` project it's because that person wants to use platform-specific code. I know that we don't need to be 100% equals to MAUI, but I'll take a look to see if I can discover why Behavior is on `Controls` project instead of `Core`

**Comment by pictos** [comment]
@brminnick @VladislavAntonyuk just pushed the changes based on our conversation. I didn't rename the `Core` to `Shared` yet

**Comment by brminnick** [comment]
@pictos Could you please provide a definition for `CommunityToolkit.Maui.Core`? Providing a drawing/diagram of the architecture will also help clarify this.

I'm still having trouble understanding what belongs into `CommunityToolkit.Maui.Core` and what remains in `CommunityToolkit.Maui`, and reading through the discussions in the PR Review, it's clear that we have not properly defined it yet.

Here's some questions I have for `CommunityToolkit.Maui.Core`:
- Will it contain code from the `Microsoft.Maui` namespace?
  - I vote that it should
- Will it contain code from the `Microsoft.Maui.Controls` namespace?
  - I vote that it should not
- Will it contain code from `Microsoft.Maui.Graphics` namespace?
  - I vote that it should be allowed, but not required
- Will it contain platform-specific Handlers?
  - I vote that it should contain all Handlers
  - For example, if `ICalendar` and its platform-specific Handlers are defined in `CommunityToolkit.Maui.Core`, separate Toolkits, like `CommunityToolkit.Comet`, just need to implement the MVU implementation of `ICalendar` and the platform-specific implementation will just work ™️

**Comment by brminnick** [comment]
Removing the `approved` tag until we define the architecture and add it to the `Detailed Design` section of the Proposal

**Comment by pictos** [comment]
@brminnick and @VladislavAntonyuk just a heads up that I updated the description with a more complete information

**Comment by brminnick** [comment]
Thanks @pictos!

 The core library will need to be called `CommunityToolkit.Maui.Core` for a couple reasons:
- The CommunityToolkit org already has a [`CommunityToolkit.Common` NuGet Package](https://www.nuget.org/packages/CommunityToolkit.Common/)
  - Creating `CommunityToolkit.Core` would cause confusion between the two packages
- It relies on `Microsoft.Maui`
  - Including `Maui` in `CommunityToolkit.Maui.Core` easily notifies developers about the dependence on .NET MAUI

It sounds like we're aligned on the architecture. 👇Do you concur with this flow diagram? If so, we should add it to the README and the Contribution Guidelines (FYI - @bijington for when you update them).

<img width="1706" alt="image" src="https://user-images.githubusercontent.com/13558917/145694198-7addbd35-0e5f-4816-b351-759a01ec2672.png">

**Comment by pictos** [comment]
@brminnick I agree with the image.

**Comment by Clancey** [comment]
The talk, on how comet would work is correct. You would be able to re-use anything in CommunityToolkit.Maui.Core for Comet. So all the handlers should work. If the handlers use interfaces, you can auto generate the comet code!

https://github.com/dotnet/Comet/blob/dev/src/Comet/Controls/ControlsGenerator.cs

This is how comet actually adds most of its controls!

**Comment by brminnick** [comment]
Right on! @pictos - When you get a chance, update the `Detailed Design` to use `CommunityToolkit.Maui.Core`, and then we'll do a quick vote on it with the team to approve it 🙌 

Normally, we'd wait to vote until the next standup, but since this is a blocking PR, we can have everyone comment on this Proposal with "Approved" then we'll add the `approved` tag 👍

**Comment by pictos** [comment]
@brminnick I will update everything until tomorrow. Anyway I'll ping the team on discord when I do it.

**Comment by brminnick** [comment]
I vote to Approve ✅

**Comment by pictos** [comment]
I vote to Approve ✅

**Comment by VladislavAntonyuk** [comment]
Approve

**Comment by bijington** [comment]
I vote to Approve

**Comment by jfversluis** [comment]
Lets approve this one!
