### ISSUE TITLE
[BUG] IOS Status Bar color error  in last version 9.0.3

### ISSUE THREAD

**Issue by TheSundayDev** [CommunityToolkit/Maui#2136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

app closes due to exception with this message
System.NotSupportedException: PlatformSetColor is only supported on iOS and Android 23 and later
   at CommunityToolkit.Maui.Core.Platform.StatusBar.PlatformSetColor(Color color)
   at CommunityToolkit.Maui.Core.Platform.StatusBar.SetColor(Color color)

### Expected Behavior

color is applied as in the previuos version

### Steps To Reproduce

1 add in app.xaml.cs
MainThread.BeginInvokeOnMainThread(() =>
{
    CommunityToolkit.Maui.Core.Platform.StatusBar.SetColor(Colors.Red);
});

### Link to public reproduction project repository

-

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.3
- OS: ios 17.6.1
- .NET MAUI:8.0.61
```

**Comment by bijington** [comment]
What platform are you seeing this on? I'm surprised by this issue as I cannot see any changes in 9.0.3.

**Comment by TheSundayDev** [comment]
Hi,
I'm testing on iphone 15 plus with 17.6.1

**Comment by TheSundayDev** [comment]
Hi all,
I updated VS to the new version 17.11 with MAUI 8.0.72 and now it's working.
thanks a lot.

**Comment by randyburden** [comment]
I had the same issue but it is now working after upgrading Visual Studio from version 17.10.4 to 17.11.4.

For posterity, the the error message was "PlatformSetColor is only supported on iOS and Android 23 and later" even though I was using iOS 18 on an iPhone 14 Pro Max.

**Comment by TheSundayDev** [comment]
Hi all, the same issue is still present using the new version 9.1.0

**Comment by RsZoli** [comment]
i can confirm this, its getting really annoying that every 2nd or 3rd time when we update our nugets, the ios build gets broken :(

**Comment by TheSundayDev** [comment]
Please someone can you reopen this issue? thanks

**Comment by bijington** [comment]
> Please someone can you reopen this issue? thanks

Can you confirm your environment setup? If you have dotnet 9.0 RC 1 then you should update to RC 2 and also make sure you have all maui workloads up to date

**Comment by TheSundayDev** [comment]
Hi,
maui 8.0.82, ios 17.6, VS 17.11.5, .NET 8
thanks

**Comment by bijington** [comment]
> Hi,
> maui 8.0.82, ios 17.6, VS 17.11.5, .NET 8
> thanks

If you run the following in a command prompt what does it report?

```
dotnet --info
```

**Comment by TheSundayDev** [comment]
.NET SDK:
 Version:           8.0.403
 Commit:            c64aa40a71
 Workload version:  8.0.400-manifests.e99c892e
 MSBuild version:   17.11.9+a69bbaaf5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.403\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [maccatalyst]
   Installation Source: VS 17.11.35327.3
   Manifest Version:    18.0.8303/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\18.0.8303\WorkloadManifest.json
   Install Type:        FileBased

 [android]
   Installation Source: VS 17.11.35327.3
   Manifest Version:    34.0.113/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.113\WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: VS 17.11.35327.3
   Manifest Version:    18.0.8303/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\18.0.8303\WorkloadManifest.json
   Install Type:        FileBased

 [maui-windows]
   Installation Source: VS 17.11.35327.3
   Manifest Version:    8.0.82/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.82\WorkloadManifest.json
   Install Type:        FileBased

 [aspire]
   Installation Source: VS 17.11.35327.3
   Manifest Version:    8.1.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.1.0\WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.10
  Architecture: x64
  Commit:       81cabf2857

.NET SDKs installed:
  8.0.403 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
