### ISSUE TITLE
[Bug] Snackbar does not show on windows when referencing the nuget package

### ISSUE THREAD

**Issue by CodedBeard** [CommunityToolkit/Maui#215]
### Description

I tried using `DisplaySnackbar()` in my project and while I got no errors, the notification did not display when debugging on windows. 
I then created a brand new project from the latest preview 10 templates, added a reference to the toolkit, and updated the `OnCounterClicked` method to show a snackbar like so:

```csharp
private async void OnCounterClicked(object sender, EventArgs e)
{
    await this.DisplaySnackbar("TEST");
    count++;
    CounterLabel.Text = $"Current count: {count}";

    SemanticScreenReader.Announce(CounterLabel.Text);
}
```
This still does not show a notification.

I then cloned the repo and added a direct reference to the project so I could step through what was going wrong, however, this time the notification displayed as expected.

### Stack Trace

N/A

### Steps to Reproduce

1. create new project from maui preview 10 templates
2. reference pre3 nuget
3. attempt to display a Snackbar

### Expected Behavior

Notification displays in windows

### Actual Behavior

nothing happens on windows

### Basic Information

- Version with issue: pre3
- Last known good version: N/A
- IDE: Visual studio
- Platform Target Frameworks:
- UWP:  same as preview 10 template
- Nuget Packages: same as preview 10 template
- Affected Devices: windows

### Workaround

clone the repo and reference the project directly

**Comment by pictos** [comment]
@CodedBeard 
Could you attach a small repro?

**Comment by CodedBeard** [comment]
@pictos this repros the issue on my machine: https://github.com/CodedBeard/notoast

If I only update the nuget reference to be a project reference from cloning the repo, it works fine.

**Comment by brminnick** [comment]
@CodedBeard On Windows, `Snackbar` uses the native toast library.

You'll need to disable silent mode.

👇 Here's a video of how it looks on Windows


![](https://user-images.githubusercontent.com/13558917/143683127-5b455f19-7def-463b-b9b9-b4ad3b299a90.gif)

**Comment by CodedBeard** [comment]
@brminnick the sample app works fine on my machine, I only have an issue when referencing the nuget package in a seperate project.

**Comment by brminnick** [comment]
Interesting! @VladislavAntonyuk is our resident `Snackbar` expert - can you take a look, Vlad, and see if you can repro/fix it?

**Comment by CodedBeard** [comment]
@brminnick heres a video showing whats happening on my machine. All I did is switch to a branch that referenced the cloned project instead of the nuget package.

https://user-images.githubusercontent.com/4446559/145632749-860044c6-d7ea-43c1-941f-1e284995692d.mp4

**Comment by VladislavAntonyuk** [comment]
that is because our package is not build for Windows
![image](https://user-images.githubusercontent.com/33021114/145634133-3cb997f8-b8ab-4e28-9ceb-ed071795ce09.png)

**Comment by brminnick** [comment]
Oh good catch! In that case, we'll hand this Issue over to our NuGet Release guru, @jfversluis 👍

**Comment by CodedBeard** [comment]
Thanks, should have spotted that, clearly to late on a friday 👍

**Comment by VladislavAntonyuk** [comment]
@brminnick the issue is with our pipeline. Windows requires MsBuild. I can fix it, if you assign package back to me)

**Comment by pictos** [comment]
@VladislavAntonyuk go for it!

**Comment by VladislavAntonyuk** [comment]
@CodedBeard please try this package: https://dev.azure.com/dotnet/CommunityToolkit/_build/results?buildId=62360&view=results

**Comment by CodedBeard** [comment]
@VladislavAntonyuk yep that works fine.

**Comment by brminnick** [comment]
Closed #217

**Comment by acrigney** [comment]
Thanks but this snackbar and Toast are not working for me on Windows for .net 6 or 7. But what is silent mode? Is that my problem.
I can't find how to turn it off. Is this how to do it? But I don't see any get button.
https://support.microsoft.com/en-us/windows/switching-out-of-s-mode-in-windows-4f56d9be-99ec-6983-119f-031bfb28a307

**Comment by VladislavAntonyuk** [comment]
Silent mode is when you forbid your app to show notifications
