### ISSUE TITLE
[BUG] LongPressCompleted event won't fire unless LongPressCommand is bound

### ISSUE THREAD

**Issue by velocitysystems** [CommunityToolkit/Maui#2164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When using the `TouchBehavior` the `LongPressCompleted` event will not fire unless the `LongPressCommand` is bound.
Note: This does not affect the `TouchGestureCompleted` event which fires regardless of whether its command is bound.

### Expected Behavior

The `LongPressCompleted` event should fire on a long-press regardless of whether its command is bound.

### Steps To Reproduce

1. Create a new MAUI project.
2. Attach a `TouchBehavior` to a control i.e. `Grid`
3. Wire up the `LongPressCompleted` event to an event handler

### Link to public reproduction project repository
[LongPressSample.zip](https://github.com/user-attachments/files/16818802/LongPressSample.zip)

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.3
- OS: iOS/Android
- .NET MAUI: 8.0.82
```

**Comment by velocitysystems** [comment]
I have added a repro project (see attached).

**Comment by brminnick** [comment]
Thanks! I suspect we're checking for whether `ICommand?.CanExecute() is true` which would block it from executing. 

I'll dive into the code and take a look when I return from my work trip this week.

**Comment by velocitysystems** [comment]
Thanks @brminnick. I note this issue still occurs in 9.1.0.
