### ISSUE TITLE
[BUG] Badge Error

### ISSUE THREAD

**Issue by gwise-vision** [CommunityToolkit/Maui#2176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Java.Lang.SecurityException: 'Permission Denial: writing com.sec.android.provider.badge.BadgeProvider uri content://com.sec.badge/apps?notify=true from pid=11498, uid=10649 requires com.sec.android.provider.badge.permission.WRITE, or grantUriPermission()'

### Expected Behavior

Java.Lang.SecurityException: 'Permission Denial: writing com.sec.android.provider.badge.BadgeProvider uri content://com.sec.badge/apps?notify=true from pid=11498, uid=10649 requires com.sec.android.provider.badge.permission.WRITE, or grantUriPermission()'

### Steps To Reproduce

Java.Lang.SecurityException: 'Permission Denial: writing com.sec.android.provider.badge.BadgeProvider uri content://com.sec.badge/apps?notify=true from pid=11498, uid=10649 requires com.sec.android.provider.badge.permission.WRITE, or grantUriPermission()'

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui/blob/main/samples/CommunityToolkit.Maui.Sample/Pages/Essentials/BadgePage.xaml

### Environment

```markdown
- .NET MAUI CommunityToolkit:9.0.3
- OS: Android
- .NET MAUI: 8.0.82
```

**Comment by bijington** [comment]
Can you please provide some actual detail on the issue? Like what version of Android? Are you really using the sample app or your own project? There really isn't anything to go on right now

**Comment by VladislavAntonyuk** [comment]
As you try to run it on your UI Wizard, you need to provide permission for it: com.sec.android.provider.badge.permission.WRITE

**Comment by gwise-vision** [comment]
> As you try to run it on your UI Wizard, you need to provide permission for it: com.sec.android.provider.badge.permission.WRITE

https://github.com/CommunityToolkit/Maui/blob/main/samples/CommunityToolkit.Maui.Sample/Platforms/Android/AndroidManifest.xml

It is already declared in the official sample source.

**Comment by gwise-vision** [comment]
> Can you please provide some actual detail on the issue? Like what version of Android? Are you really using the sample app or your own project? There really isn't anything to go on right now

https://github.com/CommunityToolkit/Maui/blob/main/samples/CommunityToolkit.Maui.Sample/Pages/Essentials/BadgePage.xaml
I tested it using the source here.
I tested it on Galaxy S20+.

**Comment by gwise-vision** [comment]
https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/essentials/badge?tabs=android#android-1

MS manual needs to be modified.
Error occurs in SamsungBadgeProvider source.
I tested using the sample source here, and the smartphones I tested are Samsung Galaxy S20 and Samsung Z Folder 5.

**Comment by VladislavAntonyuk** [comment]
With the CommunityToolkit we provide you the way implement your own badge counter logic for providers you want to support.
If Samsung made changes in there ui wizard, you need to change the BadgeProvider.
We don't provide you any BadgeProvider out of the box.
