### ISSUE TITLE
[BUG] Toast clicked action

### ISSUE THREAD

**Issue by bindalf** [CommunityToolkit/Maui#2177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

a click on an open Toast starts another instance of the application(windows)

### Expected Behavior

no action or configurable action for click on Toast

### Steps To Reproduce

1. Display a Toast Message
2. Click on the Toast Message

### Link to public reproduction project repository

every app

### Environment

```markdown
- .NET MAUI CommunityToolkit:7.0.1
- OS: Win 10
- .NET MAUI: net8.0
```

**Comment by bijington** [comment]
Have you followed the platform setup instructions in the docs? https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/alerts/toast?tabs=windows%2Candroid
