### ISSUE TITLE
[BUG] When using a ListView with bound data, sometimes fields do not wordwrap correctly.

### ISSUE THREAD

**Issue by KrimsonWolf** [CommunityToolkit/Maui#2186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

This seems to happen if the last character in the line ends in a special character like a . or a ) and when it's length is EXACTLY right.  I've seen this happen in our production product for a few strings which happen to be the exact right length to reproduce this.

In the reproduction example all the strings end with a ) or a . and on the 4 records you see

the first record both the first and last column cut off the last word.
the second record doesn't cut off anything and word wraps correctly
the third record cuts off the last column but not the first
the fourth record cuts off the first column but not the last.

This seems to be dependent on the exact pixel-length of the text, is only reproducible on iOS (I reproduced this on a 10th Generation iPad iOS Version 17.5)

### Expected Behavior

The word wrap should wrap and not cut off the last words of the fields.

### Steps To Reproduce

1.  Download, build the provided project.
2.  Observe the data in the first and last column of the grid.
![image](https://github.com/user-attachments/assets/f9a14417-1697-4305-b810-eceb240094a6)

### Link to public reproduction project repository

https://github.com/KrimsonWolf/DebugWordwrap

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS:  iOS 17.5 
- iPad (10th Generation)
- Reproduced on the iOS simulator but can also be reproduced on real devices.
- .NET MAUI:
```

**Comment by bijington** [comment]
Did you mean to raise this against the MAUI repository? https://github.com/dotnet/maui. This repository is for the community toolkit. I'll close this issue
