### ISSUE TITLE
[BUG] IconTintColorBehavior in listview item loose setting (or not updated) after item filtering

### ISSUE THREAD

**Issue by TheSundayDev** [CommunityToolkit/Maui#2219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I have a listview and as item template I have images with IconTintColorBehavior.
If I filter the items multiple times the color set in TintColor is not always applied correctly and seems that is applied to the wrong item.
This not happens always but often.
Eg list of contacts where the background image color it's based on the initial of the name (a red, b yellow ecc...)
I play with filter, I select A, then B ecc... and then all.
The image color for some items is not the correct one.

IconTintColorBehavior is a very important feature but seems is not working properly

### Expected Behavior

the color is the right one

### Steps To Reproduce

create a list and as item template put an image with binding as

<Image.Behaviors>
<toolkit:IconTintColorBehavior TintColor="{Binding ImageColor}" />
</Image.Behaviors>

2 fill the list with 20/30 items
3 filter the list based on item property (eg contact name)
4 remove filter in order to see again all items. Some of them don't have the correct ImageColor but seems are shuffled

### Link to public reproduction project repository

-

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.3
- OS: ios android
- .NET MAUI: 8.0.82
```

**Comment by davidschlabach** [comment]
I have the same issue. If I have items in a listview or a collectionview 

<toolkit:IconTintColorBehavior TintColor="{Binding ImageColor}" />

does not work. All the images are just the black image with no color applied. I've had to remove all IconTintColor from my items and add colored icons so my app can be published.

**Comment by TheSundayDev** [comment]
Let me attach a video as sample.
The IconTintColorBehavior  is applied to the circle image in the center of each item.

We have 2 possible scenario:
1. Item not tapped= black background and black image color
2. Item tapped= red background and yellow image color
Random tap on some items.

then randon filter tapping on 1,2,3 multiple time
then click an all
as you can see same images lose color setting. 
We have red background but black image color or black background and yellow image color.
Seems that the  IconTintColorBehavior  is applied to wrong item index.
Since I'm using a non standard List I'm also in contact with the list provider in order to check if it's related to their component.

https://github.com/user-attachments/assets/01efcc72-226c-4787-8c23-63f17aae83ac

thanks
