### ISSUE TITLE
[BUG] Snackbar on iOS

### ISSUE THREAD

**Issue by agcavaleiro** [CommunityToolkit/Maui#2223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When the snackbar is activated, instead of appearing at the bottom, it appears at the top, cutting off a portion of the panel.

### Expected Behavior

When activated, the snackbar should be displayed at the bottom.

### Steps To Reproduce

Below is the code snippet:
```
SnackbarOptions snackbarOptions = new SnackbarOptions();
snackbarOptions.BackgroundColor = RSColors.WarningPalette[90];
snackbarOptions.TextColor = RSColors.WarningPalette[20];
await AppBase.Current.MainPage.DisplaySnackbar("teste", null, "Fechar", null, snackbarOptions, default);
```
![Simulator Screenshot - iPhone 15 - 2024-09-22 at 11 35 37](https://github.com/user-attachments/assets/fedd4421-86ab-4251-94d4-6a5a2c16d592)

### Link to public reproduction project repository

I don't have

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.3
- OS: iPhone 15, iOS 18
- .NET MAUI: 8.0
```

**Comment by agcavaleiro** [comment]
I don't understand.
Do you need the full code?

**Comment by brminnick** [comment]
Here is the information from the `Reporting a bug` section in our `Contributing.md` file:

> - [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

> ### Bug reproduction
> 
> We always request a reproduction sample, and that's not to make your life hard or anything like that... The reason of having a reproduction is to save us time to indentify and fix the bug. Create a new project; download the MCT NuGet; write UI; ViewModel; create a service; run it. As you can see it's a lot of timing consuming for us that we could spend fixing the actual issue. So PLEASE create a small reproduction project, upload it on GitHub or GitLab and paste the link in the issue.
> 
> We don't accept .zip files as reproduction samples, for security reasons. So if you send us a .zip file we will kindly ask you to upload it to GitHub or GitLab and share the link
> And most important: Please, help us to help you ❤️

**Comment by agcavaleiro** [comment]
Ok, I get it. Sorry, this is my first interaction, so I'm still learning.
I found the bug, it happens in the extension:
```
public static Task DisplaySnackbar(this VisualElement? visualElement, string message, Action? action = null, string actionButtonText = "OK", TimeSpan? duration = null, SnackbarOptions? visualOptions = null, CancellationToken token = default(CancellationToken))
{
return Snackbar.Make(message, action, actionButtonText, duration, visualOptions, visualElement).Show(token);
}
```
When I used the snackbar directly passing the anchor as null, it worked perfectly.

**Comment by espenrl** [comment]
I can confirm this is an issue and this bug surfaced sometime during the summer. Either after updating Community Toolkit or MAUI.

**Comment by espenrl** [comment]
> Ok, I get it. Sorry, this is my first interaction, so I'm still learning. I found the bug, it happens in the extension:
> 
> ```
> public static Task DisplaySnackbar(this VisualElement? visualElement, string message, Action? action = null, string actionButtonText = "OK", TimeSpan? duration = null, SnackbarOptions? visualOptions = null, CancellationToken token = default(CancellationToken))
> {
> return Snackbar.Make(message, action, actionButtonText, duration, visualOptions, visualElement).Show(token);
> }
> ```
> 
> When I used the snackbar directly passing the anchor as null, it worked perfectly.

Thanks for the solution @agcavaleiro - I started using `Snackbar.Make()` without passing `visualElement` and now it's all working like it did previously. Meaning the snackbar is at the bottom of the page/screen again.
