### ISSUE TITLE
[BUG] [iOS] KeyboardExtensions, throws exception 'System.NotSupportedException: Arg_NotSupportedException'

### ISSUE THREAD

**Issue by mnowacki** [CommunityToolkit/Maui#2244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I use bool KeyboardExtensions.IsSoftKeyboardShowing(ITextInput) in my code. It worked ok but when i upgraded to new version 9.1.0 it started throwing exception System.NotSupportedException: Arg_NotSupportedException. The problem is just in release mode. In debug is ok. When i downgraded to version 9.0.3 it works ok again.

### Expected Behavior

Works without throwing exceptions in Release mode.

### Steps To Reproduce

1. Just use in code bool KeyboardExtensions.IsSoftKeyboardShowing(ITextInput).
2. Compile in Release mode .
3. Run on ios.

### Link to public reproduction project repository

none

### Environment

```markdown
- .NET MAUI CommunityToolkit:9.1.0
- OS:ios 17.6.1
- .NET MAUI:8.0.8
```

### Anything else?

I think it's related to aot.

**Comment by bijington** [comment]
We do ask for a reproduction sample to help us prove the issue exists and also that it has been fixed. That said I believe this issue might be solved in PR #2243
