### ISSUE TITLE
[BUG] Android Media Element crash on ArgumentNullException in MediaControlsService

### ISSUE THREAD

**Issue by vikher** [CommunityToolkit/Maui#2269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

The application throws an ArgumentNullException when starting the media controls service without a valid intent.

### Expected Behavior

The media controls service should start without throwing exceptions, even if the intent is null.

### Steps To Reproduce

1. Trigger the media controls service without providing a valid intent.
2. Observe the application throwing an ArgumentNullException.

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui/tree/main/samples

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.2
- OS: Android 14 and 13
- .NET MAUI: 8.0.72
- CommunityToolkit.Maui.MediaElement: 4.1.0
```

### Anything else?

Stack traces:

CommunityToolkit.Maui.Media.Services.MediaControlsService.OnStartCommand(Intent intent, StartCommandFlags flags, Int32 startId)
Android.App.Service.n_OnStartCommand_Landroid_content_Intent_II(IntPtr jnienv, IntPtr native__this, IntPtr native_intent, Int32 native_flags, Int32 startId)
Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLII_I(_JniMarshal_PPLII_I callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, Int32 p1, Int32 p2)

I noticed that your team closed issue https://github.com/CommunityToolkit/Maui/issues/2163 with a similar stack trace.

Most affected Devices:

- Allmoto g 5G 
- Moto g stylus 5G 
- Galaxy A35 5G
- Galaxy Z Fold6
- Galaxy S23+
- Galaxy S24+
- Galaxy Z Fold5
- Galaxy A14 5G

Screenshot from App Center demonstrating the bug.

<img width="1665" alt="image" src="https://github.com/user-attachments/assets/1c0e867b-f53b-4b44-a748-9dc772a6301b">

**Comment by brminnick** [comment]
> Trigger the media controls service without providing a valid intent.

Please be more specific. 

Please provide a reproduction sample.
