### ISSUE TITLE
[BUG] IconTintColorBehavior Not Reapplied When Reusing Views

### ISSUE THREAD

**Issue by RiyashameedM** [CommunityToolkit/Maui#2275]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [x] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

The IconTintColorBehavior does not correctly reapply the tint color when switching views in a ContentView and returning to a previously used view. When a view that uses IconTintColorBehavior is recycled and displayed again, the tint color is not applied to the image. The converter is not invoked when the recycled view is displayed. I have attached a sample to replicate the issue. I tested it with a background color instead of the tint color for a view, and it worked as expected.

### Expected Behavior

IconTintColor Should be applied for the recycled view.

### Steps To Reproduce

1.click the button 3 times 
2.check the image color.

### Link to public reproduction project repository

https://github.com/RiyashameedM/TintColorSample/tree/main

### Environment

- .NET MAUI CommunityToolkit:9.0.1
- OS:android ios
- .NET MAUI:8.0.82

**Comment by TheSundayDev** [comment]
I have the same issue.

**Comment by TheSundayDev** [comment]
Hope to see this issue close in order to finally migrate to MUAI from XF.
Thanks

**Comment by TheSundayDev** [comment]
Hi,
seems working now with version 10.
thanks

**Comment by brminnick** [comment]
Thanks for confirming!
