### ISSUE TITLE
[Bug] Type com.google.common.util.concurrent.ListenableFuture is defined multiple times

### ISSUE THREAD

**Issue by confessore** [CommunityToolkit/Maui#228]
Type com.google.common.util.concurrent.ListenableFuture is defined multiple times

### Stack Trace

`Using "D8" task from assembly "C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.101-preview.11.117\tools\Xamarin.Android.Build.Tasks.dll".`

`1>      Task "D8"`

`1>          processing ClassesZip, JavaLibrariesToEmbed...`

`1>        C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\java.exe -Xmx1G -classpath "C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.101-preview.11.117\tools\r8.jar" com.android.tools.r8.D8 --debug --min-api 21 --output obj\Debug\net6.0-android\android\bin\ --lib "C:\Program Files (x86)\Android\android-sdk\platforms\android-31\android.jar" obj\Debug\net6.0-android\android\bin\classes.zip "C:\Program Files\dotnet\packs\Microsoft.Android.Ref.31\31.0.101-preview.11.117\ref\net6.0\mono.android.jar" "C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.101-preview.11.117\tools\java_runtime_fastdev_net6.jar" C:\Users\confessore\.nuget\packages\xamarin.google.guava.listenablefuture\1.0.0.4\buildTransitive\net6.0-android31.0\..\..\jar\guava-listenablefuture.jar 
C:\Users\confessore\.nuget\packages\xamarin.androidx.annotation\1.2.0.3\buildTransitive\net6.0-android31.0\..\..\jar\androidx.annotation.annotation.jar C:\Users\confessore\.nuget\packages\xamarin.androidx.collection\1.1.0.10\buildTransitive\net6.0-android31.0\..\..\jar\androidx.collection.collection.jar C:\Users\confessore\.nuget\packages\xamarin.androidx.lifecycle.common\2.3.1.3\buildTransitive\net6.0-android31.0\..\..\jar\androidx.lifecycle.lifecycle-common.jar C:\Users\confessore\.nuget\packages\xamarin.androidx.arch.core.common\2.1.0.11\buildTransitive\net6.0-android31.0\..\..\jar\androidx.arch.core.core-common.jar C:\Users\confessore\.nuget\packages\xamarin.androidx.constraintlayout.core\1.0.1.2\buildTransitive\net6.0-android31.0\..\..\jar\androidx.constraintlayout.constraintlayout-core.jar C:\Users\confessore\.nuget\packages\xamarin.androidx.concurrent.futures\1.1.0.5\buildTransitive\net6.0-android31.0\..\..\jar\androidx.concurrent.concurrent-futures.jar C:\Users\confessore\.nuget\packages\xamarin.android.glide.disklrucache\4.12.0.2\buildTransitive\net6.0-android31.0\..\..\jar\disklrucache.jar obj\Debug\net6.0-android\lp\100\jl\classes.jar obj\Debug\net6.0-android\lp\101\jl\classes.jar obj\Debug\net6.0-android\lp\102\jl\classes.jar obj\Debug\net6.0-android\lp\103\jl\classes.jar obj\Debug\net6.0-android\lp\104\jl\classes.jar obj\Debug\net6.0-android\lp\105\jl\classes.jar obj\Debug\net6.0-android\lp\106\jl\classes.jar obj\Debug\net6.0-android\lp\107\jl\classes.jar obj\Debug\net6.0-android\lp\109\jl\classes.jar obj\Debug\net6.0-android\lp\110\jl\classes.jar obj\Debug\net6.0-android\lp\111\jl\classes.jar obj\Debug\net6.0-android\lp\112\jl\classes.jar obj\Debug\net6.0-android\lp\115\jl\libs\BAE8126850903A44.jar obj\Debug\net6.0-android\lp\121\jl\libs\009E21B983A37ED6.jar obj\Debug\net6.0-android\lp\64\jl\classes.jar obj\Debug\net6.0-android\lp\65\jl\classes.jar obj\Debug\net6.0-android\lp\66\jl\classes.jar obj\Debug\net6.0-android\lp\67\jl\classes.jar obj\Debug\net6.0-android\lp\68\jl\classes.jar obj\Debug\net6.0-android\lp\69\jl\classes.jar obj\Debug\net6.0-android\lp\70\jl\classes.jar obj\Debug\net6.0-android\lp\71\jl\classes.jar obj\Debug\net6.0-android\lp\72\jl\classes.jar obj\Debug\net6.0-android\lp\73\jl\classes.jar obj\Debug\net6.0-android\lp\74\jl\classes.jar obj\Debug\net6.0-android\lp\75\jl\classes.jar obj\Debug\net6.0-android\lp\76\jl\classes.jar obj\Debug\net6.0-android\lp\77\jl\classes.jar obj\Debug\net6.0-android\lp\78\jl\classes.jar obj\Debug\net6.0-android\lp\79\jl\classes.jar obj\Debug\net6.0-android\lp\80\jl\classes.jar obj\Debug\net6.0-android\lp\81\jl\classes.jar obj\Debug\net6.0-android\lp\82\jl\classes.jar obj\Debug\net6.0-android\lp\83\jl\classes.jar obj\Debug\net6.0-android\lp\84\jl\classes.jar obj\Debug\net6.0-android\lp\85\jl\classes.jar obj\Debug\net6.0-android\lp\86\jl\classes.jar obj\Debug\net6.0-android\lp\87\jl\classes.jar obj\Debug\net6.0-android\lp\88\jl\classes.jar obj\Debug\net6.0-android\lp\89\jl\classes.jar obj\Debug\net6.0-android\lp\90\jl\classes.jar obj\Debug\net6.0-android\lp\91\jl\classes.jar obj\Debug\net6.0-android\lp\92\jl\classes.jar obj\Debug\net6.0-android\lp\93\jl\classes.jar obj\Debug\net6.0-android\lp\94\jl\classes.jar obj\Debug\net6.0-android\lp\95\jl\classes.jar obj\Debug\net6.0-android\lp\96\jl\classes.jar obj\Debug\net6.0-android\lp\97\jl\classes.jar obj\Debug\net6.0-android\lp\98\jl\classes.jar obj\Debug\net6.0-android\lp\99\jl\classes.jar`

`1>        Error in C:\Users\confessore\.nuget\packages\xamarin.google.guava.listenablefuture\1.0.0.4\buildTransitive\net6.0-android31.0\..\..\jar\guava-listenablefuture.jar:com/google/common/util/concurrent/ListenableFuture.class:`

`1>        Type com.google.common.util.concurrent.ListenableFuture is defined multiple times: C:\Users\confessore\.nuget\packages\xamarin.google.guava.listenablefuture\1.0.0.4\buildTransitive\net6.0-android31.0\..\..\jar\guava-listenablefuture.jar:com/google/common/util/concurrent/ListenableFuture.class, obj\Debug\net6.0-android\lp\121\jl\libs\009E21B983A37ED6.jar:com/google/common/util/concurrent/ListenableFuture.class`

`1>        Compilation failed`

`1>        C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.101-preview.11.117\tools\Xamarin.Android.D8.targets(79,5): error MSB6006: "java.exe" exited with code 1.`

`1>      Done executing task "D8" -- FAILED.`

### Steps to Reproduce

1. install CommunityToolkit.Maui from nuget
2. compile against android
3. get java.exe exit code 1

### Expected Behavior

successful compilation

### Actual Behavior

error

### Basic Information

- Version with issue: 1.0.0-pre3
- Last known good version: ?
- IDE: VS 17.1.0 Preview 1.1
- Platform Target Frameworks:
  - Android: sdk30
- Android Support Library Version: 
- Nuget Packages: CommunityToolkit.Maui
- Affected Devices: ?

no work around at the moment.
i don't even know where the official git repo is... it doesn't even look like this is the right one to begin working on this issue

**Comment by VladislavAntonyuk** [comment]
It is not an issue of CommunityToolkit.Maui.

Workaround: Rollback to MAUI preview 10.
Use `Maui-check` for that.

**Comment by VladislavAntonyuk** [comment]
@confessore I am closing it:
Issue: https://github.com/xamarin/GooglePlayServicesComponents/issues/379
and the workaround
https://github.com/xamarin/GooglePlayServicesComponents/issues/379#issuecomment-733266753

**Comment by confessore** [comment]
if it is not an issue with CommunityToolkit.Maui, why is it the only
package that throws the error?
