### ISSUE TITLE
[BUG] [9.1.0 Regression] Toasts do not show up any more on iOS

### ISSUE THREAD

**Issue by janusw** [CommunityToolkit/Maui#2281]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [x] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

After upgrading CommunityToolkit.Maui from 9.0.3 to 9.1.0, my toast messages are not showing up any more on iOS. On Android they still work well.

### Expected Behavior

Toasts should show up.

### Steps To Reproduce

I'm simply showing toasts via:

```
string msg = " ... my error message ...";
await Toast.Make(msg, ToastDuration.Long).Show();
```

I do not have a minimal reproducer yet, but I'll try if it is reproducible with the `CommunityToolkit.Maui.Sample` app.

### Link to public reproduction project repository

--

### Environment

- .NET MAUI CommunityToolkit: 9.1.0
- OS: iOS (seen on v16 and v18)
- .NET MAUI: 8.0.72
- .NET SDK 8.0.402
- XCode 15.4

**Comment by janusw** [comment]
> I do not have a minimal reproducer yet, but I'll try if it is reproducible with the `CommunityToolkit.Maui.Sample` app.

Unfortunately I was not able to reproduce it with the sample at tag `9.1.0`. I'll check which conditions are necessary to trigger it ...

**Comment by janusw** [comment]
I made another attempt to produce it, based on the ShellTabBarSample from the maui-samples repo, see:

https://github.com/janusw/maui-samples/commits/CTM_toast_bug/8.0/Navigation/ShellTabBarSample

With version 9.0.3 the toasts work well here, but with 9.1.0 the sample even crashes at startup on iOS with a very strange error message:

```
System.TypeLoadException: Could not set up parent class, due to: Invalid generic instantiation assembly:/private/var/containers/Bundle/Application/7410D186-CA6A-4556-8F62-20840661F928/ShellTabBarSample.app/Microsoft.Maui.dll type:ViewHandler`2 member:(null)
  at at CommunityToolkit.Maui.AppBuilderExtensions.<>c.<UseMauiCommunityToolkit>b__0_0(IMauiHandlersCollection h)
  at at Microsoft.Maui.Hosting.HandlerMauiAppBuilderExtensions.HandlerRegistration.AddRegistration(IMauiHandlersCollection builder)
```

Note that I'm still using XCode 15.4 and .NET SDK 8.0.402. This is my global.json:

```
{
  "sdk": {
    "version": "8.0.402",
    "workloadVersion": "8.0.402",
    "rollForward": "patch"
  }
}
```

**Comment by brminnick** [comment]
This is most likely a misconfiguration of your local environment. Please open a new Issue with a reproduction sample if you are unable to resolve your problem.

Please ensure you have installed the following items:
- [ ] Update Xcode
  - As of today, the supported version of Xcode is 16.0.0 
  - Read the [latest .NET iOS Release Notes](https://github.com/xamarin/xamarin-macios/releases) to always find the latest-supported version) of Xcode for .NET MAUI 
  - I HIGHLY recommend using the open-source tool [Xcodes](https://github.com/XcodesOrg/xcodes) to easily manage your installed Xcode versions
- [ ] Update to the latest stable version of Visual Studio (or Jet Brains Rider)
- [ ] Download/install the [latest stable (non-preview) version of the .NET SDK](https://dotnet.microsoft.com/en-us/download/dotnet/)
- [ ] After installing the latest stable .NET SDK, update to the latest stable version of the .NET MAUI workload
  - On macOS, open the Terminal and enter the following command: `sudo dotnet workload install maui`
  - On Windows, open the command prompt (or Powershell) and enter the following command: `dotnet workload install maui`
- [ ] Add a [`global.json`](https://learn.microsoft.com/dotnet/core/tools/global-json) file to your application with the following parameters to ensure you're not using a unsupported preview version of .NET (example below)
  - The .NET MAUI Community Toolkit does not support preview releases of .NET 

### global.json
```
{
  "sdk": {
    "version": "8.0.403", 
    "rollForward": "latestMajor",
    "allowPrerelease": false
  }
}

```

**Comment by janusw** [comment]
> This is most likely a misconfiguration of your local environment.

Well, I wouldn't quite put it like that. My local environment works flawlessly in other cases (with XCode 15.4) ... 😉 

But indeed I can confirm that the problem goes away when switching to .NET SDK 8.0.403 and XCode 16. So the issue seems to be that version 9.1.0 is not compatible with XCode 15 any more. Your release notes do not mention any of that (otherwise I wouldn't even have opened this issue in the first place).
