### ISSUE TITLE
[BUG] Adding CommunityToolkit.MAUI package to .NET 9 based MAUI app prevents Debug configuration from running

### ISSUE THREAD

**Issue by UnusualJustin** [CommunityToolkit/Maui#2283]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [x] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Using the default MAUI project template targeting .NET 9, once you add the CommunityToolkit.MAUI reference, the project throws an exception during startup when attempting to run a Debug configuration.

![Image](https://github.com/user-attachments/assets/4f1507da-1c27-4bfd-a30f-06751904934b)

Running in Release configuration appears to be working.

Tested on iOS 17.4 and 17.5 (XCode 15.4, Visual Studio 17.12.0 Preview 2.1)

### Expected Behavior

App will start a debug session without throwing an exception.

### Steps To Reproduce

1. Open and run solution in Debug configuration

### Link to public reproduction project repository

https://github.com/UnusualJustin/CommunityToolkit-Debug-Exception

### Environment

- .NET MAUI CommunityToolkit: 9.1.0
- OS: iOS 17.4 & 17.5
- .NET MAUI: 9.0.0-rc.1.24453.9

**Comment by brminnick** [comment]
We don't yet support .NET 9. 

We will release .NET 9 support when it GAs next month. You may follow our progress here: https://github.com/CommunityToolkit/Maui/pull/2215
