### ISSUE TITLE
[BUG] Please specify file versions for CommunityToolkit.Maui and CommunityToolkit.Maui.Core

### ISSUE THREAD

**Issue by GuidoNeele** [CommunityToolkit/Maui#2299]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [x] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

File version is fixed at 1.0.0.0
![Image](https://github.com/user-attachments/assets/a0529117-9f45-497f-8ed1-1d8c551bd93a)

### Expected Behavior

Please update file version to resemble the running version, like 9.1.0.0 (which is the current version).

### Steps To Reproduce

Nothing to reproduce.

### Link to public reproduction project repository

No link

### Environment

- .NET MAUI CommunityToolkit: 9.1.0
- OS: All

### Anything else?

We are using MAUI on Windows as an unpacked app and have a VS installer project to be able to install and distribute the app easily. This works great except for CommunityToolkit files not being updated because the file version prevents the new dll files from being recognized as new.

**Comment by jfversluis** [comment]
@GuidoNeele would you be able to confirm that [the PR](https://github.com/CommunityToolkit/Maui/pull/2328) here produces libraries with the version in the correct places where you expect them?

Don't worry the sample app build failed, the packages are still produced.

To confirm use this: https://github.com/CommunityToolkit/Maui/wiki/Preview-Packages#pull-requests-
