### ISSUE TITLE
Add `.net6` target  framework

### ISSUE THREAD

**Issue by maxkoshevoi** [CommunityToolkit/Maui#23]
Currently it's not possible to move UI into a separate project (that targets just `.net6`) due to MauiToolkint not targeting that framework. In XCT it was possible. `Microsoft.Maui.Dependencies` has `.net6`, so it's also possible in vanilla Maui.

Could you please add `.net6` and another target framework to Maui toolkit (and `Xamarin.CommunityToolkit.MauiCompat`)?

**Workardond**:
Replace `.net6` with `net6.0-android30` (and all other frameworks that your app builds for) in all of app's projects. 
Downsides: increases build time, and enables platform specific code in project where there shouldn't be any.

**Comment by brminnick** [comment]
.NET MAUI only currently supports `net6.0-ios`, `net6.0-android`, `net6.0-maccatalyst` and `net6.0-windows10.0.19041`.

It does not yet include support for `net6.0`.

**Comment by maxkoshevoi** [comment]
Seems like it does. I was able to build `.net6` projects that reference `Microsoft.Maui.Dependencies`.

https://www.nuget.org/packages/Microsoft.Maui.Dependencies/6.0.100-preview.7.1345

![image](https://user-images.githubusercontent.com/6609929/131991246-eed97fe2-fc33-4599-97f0-f257c92245f2.png)

**Comment by maxkoshevoi** [comment]
Everything builds without issues: https://github.com/CommunityToolkit/Maui/pull/24

**Comment by brminnick** [comment]
Great! `net6.0` must've made it into the latest preview!

I'll review the PR today 👍

**Comment by maxkoshevoi** [comment]
@brminnick Thanks for approving the PR! Could you please make the same change for `Xamarin.CommunityToolkit.MauiCompat`?

**Comment by RajuGadda** [comment]
the above solution is'nt working for my solution I am adding blazor web assembly reference to .NET Maui Blazor project 
i have added this ```<UseMaui>true</UseMaui>```  and added target frameworks for all builds  in the Blazor Wasm project  , please help with a workaround
