### ISSUE TITLE
[BUG] - Problem with MaskedBehavior - cursor doesn't position correctly

### ISSUE THREAD

**Issue by marcelozanetti** [CommunityToolkit/Maui#2300]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [x] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I'm using the last version of Community Tookit MAUI (9.1.0), and MaskedBehavior dont work correctly. When I try to change any digit in the middle of the numbering, before any mask character, the cursor is thrown to the last position of the element.

https://github.com/user-attachments/assets/96fa408d-df22-49fd-ad38-bac4c9f6df50

### Expected Behavior

The expected behavior is that the cursor is moved to the next position in the numbering, not to the end of the numbering.

### Steps To Reproduce

https://github.com/user-attachments/assets/dd6106dc-ea97-49c1-bb6d-bb881f77ef28

### Link to public reproduction project repository

-

### Environment

- .NET MAUI CommunityToolkit:
- OS:
- .NET MAUI:

**Comment by brminnick** [comment]
Duplicate: https://github.com/CommunityToolkit/Maui/issues/2301
