### ISSUE TITLE
[BUG] IOS Status Bar color error in last version 9.1.0

### ISSUE THREAD

**Issue by TheSundayDev** [CommunityToolkit/Maui#2305]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [x] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

app closes due to exception with this message
System.NotSupportedException: PlatformSetColor is only supported on iOS and Android 23 and later
at CommunityToolkit.Maui.Core.Platform.StatusBar.PlatformSetColor(Color color)
at CommunityToolkit.Maui.Core.Platform.StatusBar.SetColor(Color color)

### Expected Behavior

color is applied as in the previuos version

### Steps To Reproduce

1 add in app.xaml.cs
MainThread.BeginInvokeOnMainThread(() =>
{
CommunityToolkit.Maui.Core.Platform.StatusBar.SetColor(Colors.Red);
});

### Link to public reproduction project repository

-

### Environment

- .NET MAUI CommunityToolkit: 9.1.0
- OS: ios 17.6.1
- .NET MAUI:8.0.82
VS 17.11.5

### Anything else?

THis is the same of #2136 but it's closed.
thanks

**Comment by bijington** [comment]
Please follow these steps

https://github.com/CommunityToolkit/Maui/issues/2284#issuecomment-2417806376

**Comment by TheSundayDev** [comment]
> Please follow these steps
> 
> [#2284 (comment)](https://github.com/CommunityToolkit/Maui/issues/2284#issuecomment-2417806376)

thanks for your response.
Now it's working fine after unistall and reinstall xcode.
Thanks a lot for your support during Sunday!!!!
You can close this, Thanks!
