### ISSUE TITLE
[BUG] Cancel being called on a disposed CancellationTokenSource

### ISSUE THREAD

**Issue by matt-bartholomew** [CommunityToolkit/Maui#2310]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [x] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

The app is a fairly basic app that renders questionnaires (from JSON) into popups, or pages, that can be filled out. This is used as a package in other apps we have. Inside of the code is a sample app. When you load up a form and click into a textbox, the app crashes, with the following being printed to the console. From the best I can tell, it looks like Cancel() is called on a disposed cancellationtokensource. The app uses validation behaviors based on the question type.

**System.ObjectDisposedException:** 'Loading...'

**System.ObjectDisposedException:** 'The CancellationTokenSource has been disposed.'

[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.ObjectDisposedException: The CancellationTokenSource has been disposed.
[mono-rt]    at System.Threading.CancellationTokenSource.ThrowIfDisposed()
[mono-rt]    at System.Threading.CancellationTokenSource.Cancel(Boolean throwOnFirstException)
[mono-rt]    at System.Threading.CancellationTokenSource.Cancel()
[mono-rt]    at CommunityToolkit.Maui.Behaviors.ValidationBehavior.ResetValidationTokenSource(CancellationTokenSource newTokenSource)
[mono-rt]    at CommunityToolkit.Maui.Behaviors.ValidationBehavior.UpdateStateAsync(VisualElement view, ValidationFlags flags, Boolean isForced, Nullable`1 parentToken)
[mono-rt]    at CommunityToolkit.Maui.Behaviors.ValidationBehavior.OnViewPropertyChanged(VisualElement sender, PropertyChangedEventArgs e)
[mono-rt]    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
[mono-rt]    at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
[mono-rt]    at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 37
[mono-rt]    at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Java.Lang.IRunnable.cs:line 84
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22

### Expected Behavior

You should be able to open the form, click into a textbox, and fill out the form w/o issue.

### Steps To Reproduce

1. Open solution, navigate to main branch, and build and run for Android.
2. Once app loads, select button "Fill Out Form".
3. Click into the "Number of Milk Crates Delivered" entry and app will crash.

### Link to public reproduction project repository

https://github.com/matt-bartholomew/MobileForms

### Environment

- .NET MAUI CommunityToolkit: 9.0.3
- OS: Android XT3 running Android 9
- .NET MAUI: 9.0.0-rc.1.24453.9

**Comment by bijington** [comment]
Do you see this issue when using .NET 8.0? We don't officially support .NET 9.0 yet

**Comment by matt-bartholomew** [comment]
> Do you see this issue when using .NET 8.0? We don't officially support .NET 9.0 yet

I'm targeting .net 8. 
![Image](https://github.com/user-attachments/assets/894dbbd2-4642-437d-8a1c-b355d6a7c6a6)
![Image](https://github.com/user-attachments/assets/0f3531ef-174a-4573-8a38-e178c5071c7a)

**Comment by bijington** [comment]
But you are depending on .NET 9.0 MAUI libraries...

**Comment by matt-bartholomew** [comment]
![Image](https://github.com/user-attachments/assets/4b170da7-a5e1-4c44-90e6-c30a8baee833)
When I downgrade the packages to what's shown in the picture the issues still persist.

**Comment by pictos** [comment]
@matt-bartholomew your repro url gives a 404. Can you fix that?

**Comment by pictos** [comment]
could confirm the issue

**Comment by matt-bartholomew** [comment]
@bijington I just wanted to check in and see if you had any thoughts.

**Comment by matt-bartholomew** [comment]
@pictos Do you have any insight into what the process and/or timeline is like for getting assistance with these bugs? I've never put in a bug before, so I don't really know what the process/timeline looks like, and this is a pretty critical fix for my company.

**Comment by bijington** [comment]
@matt-bartholomew we don't usually put any timelines on things because the contributors work on this in their spare time. If there hasn't been any progress I doubt anyone has had a chance to look into it.

If it is a critical issue for you/your company then perhaps you would consider contributing in some way towards the fix? We accept PRs and any other assistance
