### ISSUE TITLE
[BUG] StatusBarBehavior does not display the screen correctly

### ISSUE THREAD

**Issue by DaoChiMinh** [CommunityToolkit/Maui#2342]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [x] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

MainPage PushModalAsync to  NewPage1, 

at screen NewPage1 Set

```
<ContentPage.Behaviors>
    <toolkit:StatusBarBehavior StatusBarColor="Fuchsia" StatusBarStyle="LightContent" />
</ContentPage.Behaviors> 
```

but it shows Fuchsia color on mainpage

https://github.com/user-attachments/assets/fbd3ff51-9907-423a-a9ba-25a6b799d93a

### Expected Behavior

StatusBarBehavior displays the screen correctly

### Steps To Reproduce

1. Open and run solution from reproduction repository.
2. click button in MainPage

### Link to public reproduction project repository

https://github.com/CyberSoft-manager/MauiAppStatusBarBehavior

### Environment

```markdown
- .NET MAUI CommunityToolkit:9.1.1
- OS: Windows 11 22631.4317
- .NET MAUI: 9.0.0
android 34.0.138/8.0.100 SDK 8.0.400, VS 17.11.35327.3
ios 18.0.8303/8.0.100 SDK 8.0.400, VS 17.11.35327.3
```

**Comment by brminnick** [comment]
We do not yet support .NET 9. 

Please test this again with `CommunityToolkit.Maui v10.0.0` once it is available and reopen if the issue persists.
