### ISSUE TITLE
[BUG] Typed bindings cause exception

### ISSUE THREAD

**Issue by owl-guy** [CommunityToolkit/Maui#2343]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [x] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When entering a page with typed bindings, we get the following error message:
![Image](https://github.com/user-attachments/assets/b906fbbf-1332-4ae7-a1e8-2c6aa15439b4)

### Expected Behavior

The bindings should resolve without problem

### Steps To Reproduce

1. Create a new .NET MAUI App with .NET 9
2. Add a typed binding to the MainPage
3. Start the app and navigate to the MainPage
4. The app crashes

### Link to public reproduction project repository

https://github.com/owl-guy/TypedBindingExample

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.1.1
- OS: Android
- .NET MAUI: 9.0.0
```

**Comment by MichaelLHerman** [comment]
@owl-guy getting a 404 for your link

**Comment by owl-guy** [comment]
> [@owl-guy](https://github.com/owl-guy) getting a 404 for your link

My bad, i accidentally made the repo private. Should work now

**Comment by bijington** [comment]
One obvious issue I can see with the sample is that it doesn't call the `UseMauiCommunityToolkitMarkup` method. You can find how to use it in the docs:

https://learn.microsoft.com/dotnet/communitytoolkit/maui/get-started?tabs=CommunityToolkitMauiMarkup

Also the markup code is held in a different repo. Once I'm on my laptop I'll see if I can transfer this issue to the other repo

**Comment by brminnick** [comment]
Please wait until we release support for .NET 9. 

MAUI completely reengineered compiled bindings in NET 9 and our NuGet package is not yet compatible until we release `CommunityToolkit.Maui v10.0.0`.

**Comment by brminnick** [comment]
Closing as this is an issue for https://github.com/communitytoolkit/maui.markup
