### ISSUE TITLE
Toolkit causes build to fail with .Net Maui Prev. 11

### ISSUE THREAD

**Issue by Phil4121** [CommunityToolkit/Maui#236]
After updating my working solution form .Net Maui Prev. 10 to Prev. 11 the build failed.

The error I get is:
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.101-preview.11.117\tools\Xamarin.Android.D8.targets(79,5): error MSB6006: "java.exe" exited with code 1.

I tried a few possible reasons and after removing the  <PackageReference Include="CommunityToolkit.Maui" Version="1.0.0-pre3" /> the project compiled again.

There is also another report of this issue in the .Net Maui Project:
https://github.com/dotnet/maui/issues/3965

Maybe someone faces the same issue and found a workaround?

**Comment by VladislavAntonyuk** [comment]
there were breaking changes in MAUI Preview 11. MCT is built using Preview 10. As soon as the new build is available the issue should be solved.
duplicate: https://github.com/CommunityToolkit/Maui/issues/228

**Comment by brminnick** [comment]
Thanks @Phil4121 + @VladislavAntonyuk!

We will push a new release, CommunityToolkit.Maui-pre4, this week that is built against .NET MAUI Preview 11 to fix this bug 👍

**Comment by brminnick** [comment]
Closed via [`CommunityToolkit.Maui-pre4`](https://www.nuget.org/packages/CommunityToolkit.Maui/1.0.0-pre4)
