### ISSUE TITLE
[Proposal] Toast

### ISSUE THREAD

**Issue by VladislavAntonyuk** [CommunityToolkit/Maui#238]
### Discussed in https://github.com/CommunityToolkit/Maui/discussions/209

<div type='discussions-op-text'>

<sup>Originally posted by **VladislavAntonyuk** November 27, 2021</sup>

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Sample
* [x] Documentation: Not Started

# Toast

## Summary
[summary]: #summary

Adds a toast.
It should use Native Toast on Android and Windows.
All other platforms implement a default popup container with message.

## Detailed Design
[design]: #detailed-design

### Toast.shared.cs

```cs
namespace CommunityToolkit.Maui.Alerts.Toast;

public class Toast: IToast
{
	ToastDuration Duration { get; set; }
	string Text { get; set; }

	Task Dismiss();
	Task Show();

    public static IToast Make(string text, ToastDuration duration = ToastDuration.Short);
}

public interface IToast
{
	ToastDuration Duration { get; }
	bool IsShown { get; }
	string Text { get; }

	Task Dismiss();
	Task Show();
}

public enum ToastDuration
{
    Short,
    Long
}
```

**Comment by VladislavAntonyuk** [comment]
changing DetailedDesign according to the latest changes in Android 11:
Since Android 11, custom toasts/ toast modifications are deprecated, according to Google to "protect users". Hence why your app in Android 30 is not able to display custom toasts.

From Android Developers documentation:

Custom toast views are deprecated. Apps can create a standard text toast with the makeText(android.content.Context, java.lang.CharSequence, int)

**Comment by pictos** [comment]
Thanks Vlad! 

I implemented Pedro's recommendation to remove `SemaphoreSlim` by ensuring that `Snackbar.Show`, `Snackbar.Dismiss`, `Toast.Show` and `Toast.Dismiss` always run on the Main Thread.

I approve of this PR, although it looks like Pedro still has two requests:

- Make `Toast.String` readonly
  - I see a valid use-case for keeping this writeable

```cs
IToast? toast = Toast.Make("5 seconds remaining");

async void HandleToastButtonClicked(sender object, EventArgs e)
{
    toast.Text = "3 Minutes Remaining";
    await toast.Show();
}
```
- Update `DisposeAsyncCore` for `Toast.shared.cs` and `Snackbar.shared.cs`

### Current

```cs
        /// <summary>
	/// Dispose Toast
	/// </summary>
	protected virtual async ValueTask DisposeAsyncCore()
	{
#if ANDROID
		if(NativeToast is not null)
		{
			await Device.InvokeOnMainThreadAsync(() => NativeToast.Dispose());
		}
#else
		await ValueTask.CompletedTask;
#endif
	}
```

### Updated

```cs
#if ANDROID
	protected virtual async ValueTask DisposeAsyncCore()
	{
		if(NativeToast is not null)
		{
			await Device.InvokeOnMainThreadAsync(() => NativeToast.Dispose());
		}
        }
#else
	protected virtual ValueTask DisposeAsyncCore()
	{
		return ValueTask.CompletedTask;
        }
#endif
```

**Comment by pictos** [comment]
> * Make `Toast.String` readonly
>   
>   * I see a valid use-case for keeping this writeable
> 
> ```cs
> IToast? toast = Toast.Make("5 seconds remaining");
> 
> async void HandleToastButtonClicked(sender object, EventArgs e)
> {
>     toast.Text = "3 Minutes Remaining";
>     await toast.Show();
> }
> ```

In this case, we need to care about thread-safe, we should `Show` and `Dismiss` on the UI thread, but we can create and change the Toast values in any thread, and in real-world apps, with Rx, Messaging patterns, ViewModels, etc this can be tricky.
Making this immutable, we make it safer, making sure that the latest created Toast will be the presented one. I can reference the Roslyn team that decided to be immutable to avoid odd scenarios with multi-thread. That said, I can say that advantage of making Toast `immutable` is higher than the advantage of don't.

**Comment by brminnick** [comment]
Good point! There may be devs who expect the text on the displayed `Toast` to update immediately when `IToast.Text` changes (similar to how `ILabel.Text` changes immediately when changed.

There's also a similar point to be made about applying the same behavior to `SnackBar` (which _is_ mutable), and I'll spin up a new Discussion for that.

Since we have a release scheduled for this week, and we're 99% of the way to finishing the PR, let's make `Toast` immutable for this PR to push out the feature and get feedback/examples from the community if they'd like to add mutability to Toast 👍 

```cs
public string Text { get; init; } = string.Empty;

public ToastDuration Duration { get; init; } = ToastDuration.Short;

public double TextSize { get; init; } = Defaults.FontSize;
```

**Comment by pictos** [comment]
That works for me 🚀

**Comment by brminnick** [comment]
Ah - looks like this proposal was missing the `proposal` label which is what @msftbot looks for

**Comment by brminnick** [comment]
Fixed! I changed the rule from just requiring the `proposal` tag to also checking if it's in the `New Feature Proposals` project board. I'll re-add the `proposal` tag now that I'm done testing.

Thanks Shaun!
