### ISSUE TITLE
[BUG] LongPressCommand no longer working in 10.0.0.0, but it works in 9.0.0.1

### ISSUE THREAD

**Issue by takkiemon** [CommunityToolkit/Maui#2422]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [x] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I have added Touchbehaviors to a VerticalStacklayout and it works fine in 9.0.0.1 version of the CommunityToolkit. In this VerticalStackLayout, there's a 2x2 grid. In this grid, there are four rectangles that have different colors. After long pressing this grid (anywhere), two of the colors in these rectangles change. There's also a button beneath that does the same thing.
After upgrading to 10.0.0.0 this has ceased to work. Longpressing this grid no longer does anything.

### Expected Behavior

I expect the colors in two rectangles to change after longpressing the grid with CommunityToolkit 10.0.0.0

### Steps To Reproduce

1. Open the project
2. Run the program in Windows or Android
3. Longpress the grid (consisting of the four rectangles above the button that says "Selected is set to true"/"Selected is set to false"
4. See that nothing happens

### Link to public reproduction project repository

https://github.com/takkiemon/TouchbehaviorBug10000

### Environment

```markdown
- .NET MAUI CommunityToolkit: 10.0.0.0
- OS: Windows 11, Android
- .NET MAUI: 9.0.21
```

### Anything else?

I have a repo for the 9.0.0.1 version https://github.com/takkiemon/TouchbehaviorBug9001 for those who are unable/unwilling to downgrade the project themselves to see that it works in that version

**Comment by bijington** [comment]
Please check our release notes because there was a breaking change made to behaviors

https://github.com/CommunityToolkit/Maui/releases/tag/10.0.0

![image](https://github.com/user-attachments/assets/3c03d27b-cc55-4b06-9037-65db18707e13)
