### ISSUE TITLE
[Proposal] Xmlns Definition

### ISSUE THREAD

**Issue by bijington** [CommunityToolkit/Maui#245]
# Add Xmlns Definition

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests: (Not Required)
* [x] Sample
* [x] Documentation

## Link to Discussion

https://github.com/CommunityToolkit/Maui/discussions/144

## Summary
[summary]: #summary

This proposal will result in reducing the number of `xmlns` declarations required in XAML files when using different parts of the toolkit. It would result in only needing to use a single declaration e.g.

`xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/tookit"`

## Motivation
[motivation]: #motivation

To reduce the number of `xmlns` declarations required in XAML files.

## Detailed Design
[design]: #detailed-design

More implementation detail than design but we should just require adding this for each part of the namespace:

```csharp
[assembly: XmlnsDefinition("http://schemas.microsoft.com/dotnet/2022/maui/tookit", "CommunityToolkit.Maui.Behaviors")]
[assembly: XmlnsDefinition("http://schemas.microsoft.com/dotnet/2022/maui/tookit", "CommunityToolkit.Maui.Converters")]
// ...
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:toolkit="http://schemas.microsoft.com/dotnet/2021/maui/tookit"
             x:Class="MauiApp2.MainPage">
</ContentPage>
```

## Drawbacks
[drawbacks]: #drawbacks

There has been a discussion around whether this could introduce the linking issue that we saw in XCT (https://github.com/xamarin/XamarinCommunityToolkit/issues/1311) however it is believed that this should not be an issue in the Maui Community Toolkit given we will actually have to call code that will prevent the linker from removing it.

## Alternatives
[alternatives]: #alternatives

Do nothing?

## Unresolved Questions
[unresolved]: #unresolved-questions

N/A

**Comment by pictos** [comment]
Approved

**Comment by bijington** [comment]
Given we now have our docs repository setup this change will drastically simplify the writing of the docs. I think this alone also then shows how it would simplify writing XAML in apps :)

Please vote:
- 👍 for
- 👎 against (with reason in case we are missing something)

**Comment by egvijayanand** [comment]
Hello folks,

Having a suggestion on this one, the xmlns prefix can be made smaller because they need to be typed every time to refer to any of the types such as `<toolkit:BadgeView>`: 

* `mct` - Sounds similar to `xct` and corresponds to Maui CommunityToolkit
* `t` - Similar to that `x` XAML xmlns prefix

Saves a lot of keystrokes and precious time.

Another one is a typo error in the current xmlns value. Note that it ends with `tookit` and not `toolkit`, the letter `l` is missing.

`xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/tookit"`

Notify to @brminnick @bijington

**Comment by bijington** [comment]
@egvijayanand Thank you for this. I can't believe we missed the typo I will get that fixed shortly. 

For the first point about the prefix this is entirely up to you as a consumer you can call it whatever you like e.g.

```xml
xmlns:mct="http://schemas.microsoft.com/dotnet/2022/maui/tookit"
```

**Comment by egvijayanand** [comment]
Hi @bijington,

I do agree that preference on prefixes' is left to the user.

But I hope there'll be a default prefix value (defined with `[XmlnsPrefix]`) with which it'll ship, request to consider using a shorter prefix as most of the time we as end-users accept the default value and focus on the core logic at hand.

Regards,
Vijay Anand E G

**Comment by bijington** [comment]
@egvijayanand thanks for this. I have a fix for the typo over at this PR #263 along with an initial discussion on what the prefix should be :)

**Comment by bijington** [comment]
To

**Comment by bijington** [comment]
Docs completed at: https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/get-started.md
