### ISSUE TITLE
System.Exception: 'Handler not found for view Xamarin.CommunityToolkit.UI.Views.Expander.'[Bug] 

### ISSUE THREAD

**Issue by vplife1** [CommunityToolkit/Maui#249]
I have used Visual studio 2022  preview 2.0 MAUI.I want to used a expander using Community toolkit ,But right now i am facing a exception " System.Exception: 'Handler not found for view Xamarin.CommunityToolkit.UI.Views.Expander.'" How can i resolve this issue please Guide me .

Also I have download the nuget.
1)Xamarin Community Toolkit Markup MauiCompat 
2)Xamarin.CommunityToolkit.MauiCompat
NOTE:--I want a MAUI Expander Control Please share me a solution
My View Is:-

**NameSpace:-**
        xmlns:behaviors="http://xamarin.com/schemas/2020/toolkit"
**View:-**

<behaviors:Expander>
                            <behaviors:Expander.Header>
                                <HorizontalStackLayout Margin="33,-10,22,10">
                                    <Label FontAttributes="Bold" WidthRequest="230" VerticalOptions="Center" Text="Monday" TextColor="{DynamicResource Black}" FontSize="{DynamicResource AppFontSize_Default}"></Label>
                                    <Image Margin="0,0,30,0" Source="plus.png"  HorizontalOptions="StartAndExpand" VerticalOptions="CenterAndExpand" WidthRequest="15" HeightRequest="20">
                                        <Image.Triggers>
                                            <DataTrigger TargetType="Image" Binding="{Binding Source={RelativeSource AncestorType={x:Type behaviors:Expander}}, Path=IsExpanded}" Value="True">
                                                <Setter Property="Source" Value="plus.png" />
                                            </DataTrigger>
                                        </Image.Triggers>
                                    </Image>
                                    <RadioButton  BackgroundColor="Transparent" BorderColor="{DynamicResource DefaultColor}"></RadioButton>
                                </HorizontalStackLayout>
                            </behaviors:Expander.Header>
                            <behaviors:Expander.ContentTemplate>
                                <DataTemplate>
                                    <Label Text="{Binding CustomerNotes}" HorizontalOptions="StartAndExpand" TextColor="Black" FontSize="14" Padding="10,0,0,0"></Label>
                                </DataTemplate>
                            </behaviors:Expander.ContentTemplate>
                        </behaviors:Expander>

**Comment by brminnick** [comment]
Hi @vplife1! This sounds like a bug with `Xamarin.CommunityToolkit.MauiCompat`  

Please open a bug report on its repo: https://github.com/xamarin/XamarinCommunityToolkit/issues/new?assignees=&labels=bug%2C+unverified%2C+maui-compat&template=maui_compat_bug_report_template.md&title=%5BBug%5D+%5BMauiCompat%5D+
