### ISSUE TITLE
[Bug] Errors after upgrade to .net MAUI Preview 12

### ISSUE THREAD

**Issue by ggutschi** [CommunityToolkit/Maui#253]
Cannot build (for Windows) with new .net MAUI Preview 12.

### Description

If you add CommunityToolkit.Maui to a .net MAUI Preview 12 project, the windows build fails with two errors:
PRI175: 0x80073b0f - Processing Resources failed with error: Duplicate Entry. INAPPSDKGENERATEPROJECTPRIFILE
PRI222: 0x80073b0f - Unspecified error occurred.	WINAPPSDKGENERATEPROJECTPRIFILE

### Steps to Reproduce

1. Create a new .net MAUI project (from VS template)
2. Add the CommunityTookit nuget package.

### Expected Behavior

Successful build

### Actual Behavior

Build errors:

PRI175: 0x80073b0f - Processing Resources failed with error: Duplicate Entry. INAPPSDKGENERATEPROJECTPRIFILE
PRI222: 0x80073b0f - Unspecified error occurred.	WINAPPSDKGENERATEPROJECTPRIFILE

### Basic Information

- Version with issue: 1.0.0-pre4
- IDE: Visual Studio 2022 17.1.0 Preview 3

**Comment by VladislavAntonyuk** [comment]
pre4 is built using preview 11. the next release (pre5) will use preview 12

**Comment by MacrayBlackhand** [comment]
I'm getting this exact problem when migrating from net7 to net8.  My CommunityToolkit.Maui is at 6.1.0 and my CommunityToolkit.Mvvm is at 8.2.2

**Comment by MacrayBlackhand** [comment]
Didn't know that was available, it didn't show in the package manager.  I change the version in my csproj file and it seemed to restore the package.  I deleted my bin and obj folders, cleaned and rebuilt the solution. Same error.

**Comment by MacrayBlackhand** [comment]
This was caused by aa 3rd-party library not ready for the update, thanks for the input.
