### ISSUE TITLE
[Proposal] CameraView minimal port

### ISSUE THREAD

**Issue by pictos** [CommunityToolkit/Maui#259]
# [CameraView minimal port]

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
  * [ ] iOS Support
  * [ ] Android Support
  * [ ] macOS Support
  * [ ] Windows Support
* [ ] Unit Tests: Not Started
* [ ] Sample: Not Started
* [ ] Documentation: Not Started

## Link to Discussion

- #106 
- #206

## Summary
[summary]: #summary

Today on XCT we have a very complete `CameraView` implementation but with a lot of bugs and a complex codebase to maintain. In the table below you can see all features implemented by each platform.

||Android|iOS|Windows|
|---|:---:|:---:|:---:|
|Preview|✅|✅|✅|
|Preview Aspect|✅|🚫|🚫|
|Mirror preview|✅|🚫|🚫|
|Zoom|✅|✅|✅|
|Take photo|✅|✅|✅|
|Flash|✅|✅|✅|
|Take video|✅|✅|✅|
|Record audio|✅|✅|✅|
|Video stabilization|✅|✅|✅|

My plan, described in discussion #206, is to drop some features for the v1.0 of this lib. and use `CameraX` implementation for Android. You can see in the table below what features we will have for v1.0.

||Android|iOS|Windows|
|---|:---:|:---:|:---:|
|Preview|✅|✅|✅|
|Take photo|✅|✅|✅|
|Flash|✅|✅|✅|

After this first implementation, we can add the missing features to all platforms.

## Motivation
[motivation]: #motivation

The motivation for this plan was the fact that `CameraView` lacks in quality right now and this's our chance to fix it and provide a more reliable Camera control for our community.

## Detailed Design
[design]: #detailed-design

### CameraView.shared.cs

```cs
public class CameraView : View
{
  public static readonly BindableProperty IsCameraViewBusyProperty;
  public static readonly BindableProperty IsAvailableProperty;
  public static readonly BindableProperty FlashModeProperty;
  
  // Use WeakEventManager 
  public event EventHandler<bool>? OnAvailable;
  public event EventHandler<MediaCapturedEventArgs>? MediaCaptured; 
  public event EventHandler<string>? MediaCaptureFailed;
  
  public bool IsCameraViewBusy { get; }
  public bool IsAvailable { get; }
  public CameraOptions CameraOptions { get; set; } 
  public void Shutter();
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
             x:Class="MyLittleApp.MainPage">

     <StackLayout>
        <xct:CameraView
                x:Name="cameraView"
                FlashMode="On"
                MediaCaptured="CameraView_MediaCaptured"
                HorizontalOptions="FillAndExpand"
                VerticalOptions="FillAndExpand" />
    </StackLayout>
</ContentPage>
```

### C# Usage

```cs
class MyPage : ContentPage
{
  public MyPage()
  {
    Content = new CameraView
    {
      FlashMode = CameraFlashMode.Off,
    }.FillAndExpand()
     .Invoke(cameraView => cameraView.MediaCaptured += HandleMediaCaptured);
  }

  void HandleMediaCaptured(object? sender, MediaCapturedEventArgs e)
  {
    //...
  }
}
```

## Drawbacks
[drawbacks]: #drawbacks

We will (probably*) break our users on v1.0 since the API will be missing a lot of features.

* there's a chance that we can implement all features for v1.0 if we have a lot of community help.

## Alternatives
[alternatives]: #alternatives

- Follow the #106 proposal and just port the XCT code to here, but with that, we will bring all issues (if we don't solve them during the port, what I believe it's very hard to do)

## Unresolved Questions
[unresolved]: #unresolved-questions

**Comment by VladislavAntonyuk** [comment]
I suggest to add TakeVideo. In that case we cover major Camera features.

**Comment by brminnick** [comment]
Thanks Pedro! This is a great start! Here's a couple recommendations I have for the API design:

### `public bool IsBusy { get; set; }`
- Can we rename this to something more descriptive? 
  - I.e. What does `IsBusy` mean? Does it mean the CameraView is in use? Or does it mean the the camera shutter is in use? etc
- Should this be `{ get; private set; }`? I doubt we'd want the user to toggle `IsBusy`.

### `public bool IsAvailable {get; set; }`
- I recommend removing this property, and following the `Maui.Essentials` example of throwing a `FeatureNotSupportedException` if a user attempts to use the CameraView on a device where it is not supported
   - If we decide instead to keep this property, I recommend making it's setter private, e.g. `{ get; private set; }`

### `public void Shutter()`
- Let's change this name to be a verb (an action word), and be more descriptive, e.g. `CloseShutter`, `OpenShutter`, etc

### `CameraOptions`
- Could you include the API Surface for `CameraOptions` in the Detailed Design?

### `public event EventHandler<bool>? OnAvailable`
- Could this be changed to `public event EventHandler<CameraAvailabilityStatus> CameraAvailablityChanged;`?
  - `CameraAvailabilityStatus` would be an `enum`
  ```cs
   public enum CameraAvailabilityStatus { Unknown, Available, NotAvailable }
   ```
- Let's use `WeakEventManager` to ensure we don't induce memory leaks and that the `event` doesn't need to be nullable
    ```cs
    readonly WeakEventManager eventManager = new();
  
    public event EventHandler<CameraAvailabilityStatus> CameraAvailablityChanged
    {
      add => eventManager.AddEventHandler(value);
      remove => eventManager.RemoveEventHandler(value);
    }
    ```

### `public event EventHandler<MediaCapturedEventArgs>? MediaCaptured`
- Let's use `WeakEventManager` to ensure we don't induce memory leaks and that the `event` doesn't need to be nullable
    ```cs
    readonly WeakEventManager eventManager = new();
  
    public event EventHandler<MediaCapturedEventArgs> MediaCaptured
    {
      add => eventManager.AddEventHandler(value);
      remove => eventManager.RemoveEventHandler(value);
    }
    ```

### `public event EventHandler<string>? MediaCaptureFailed`
- Let's use `WeakEventManager` to ensure we don't induce memory leaks and that the `event` doesn't need to be nullable
    ```cs
    readonly WeakEventManager eventManager = new();
  
    public event EventHandler<string> MediaCaptureFailed
    {
      add => eventManager.AddEventHandler(value);
      remove => eventManager.RemoveEventHandler(value);
    }
    ```

**Comment by Mzazvor** [comment]
Hi, Is this camera view also the solution to barcode scanning in MAUI? It seems that way from some Zxing repos comments. Is there any estimate of when this could be avaliable ?

Thanx. 

PS: If this question does not belong here im sorry and feel free to delete it.

**Comment by pictos** [comment]
@Mzazvor, So this cameraView will not be the solution for barcode scanning, the ZXing is another project that you can see [here](https://github.com/Redth/BigIslandBarcoding). But there are plans to use the CameraView from this package on the ZXing project.

I can't tell you right now when we will release this feature. It's in progress the Android implementation is almost done

**Comment by thra02ad** [comment]
Hi all - wanted to ask what’s the status on this? I am not a developer myself but I am building an app where I need a customized camera as part of it. Thanks in advance! :-)

**Comment by pictos** [comment]
Hey, @thra02ad the implementation for Android is pretty much done... I'm learning about the camera on iOS. I'm building some CameraViews apps in swift to see how that goes and then I'll move to C# and start an implementation for this lib. Right now I don't have any deadline to share with you

**Comment by thra02ad** [comment]
> Hey, @thra02ad the implementation for Android is pretty much done... I'm learning about the camera on iOS. I'm building some CameraViews apps in swift to see how that goes and then I'll move to C# and start an implementation for this lib. Right now I don't have any deadline to share with you

Thank you so much @pictos for swift reply. Apologies for multiple questions, and fully understand that deadline is unknown at the moment. But would you say realistically there is a chance that it will come for iOS this year? Just trying to figure out contingency plans for my app (wait for it vs change back to Xamarin). :-)

**Comment by pictos** [comment]
@thra02ad my intention is to have this ticket closed before December kkkkk

**Comment by thra02ad** [comment]
> @thra02ad my intention is to have this ticket closed before December kkkkk

Thank you very much for coming back to me! Highly appreciated

**Comment by mapo80** [comment]
Hi @pictos, can you share github branch where Is your implementation so we can help you to complete this task?

Thanks

**Comment by pictos** [comment]
@mapo80, [here is](https://github.com/CommunityToolkit/Maui/tree/pj/cameraView-initial-work) the branch. Right now I'm blocked by the tooling... I couldn't deploy/debug using a physical device... So I'll wait until the next release and see if that fixes my issue and move forward.

**Comment by andreasbrostencab** [comment]
Great news there is a maui version on the way! :)

When using the cameraview from XCT, the flash causes over (or sometimes under) exponation of the image. Often making it way to white, if taking a photo in a dark room. Will photos with flash work better with this MAUI-version?

**Comment by pictos** [comment]
@andreasbrostencab, the short answer is "I hope so". The long answer is, that we use the default and simple APIs from the Cameras APIs, because we want to be more general and simple... So we will expose APIs to control the flash intensity or something like, but the new implementation will be easier to expand.

**Comment by andreasbrostencab** [comment]
Hope work is going well with this new Cameraview. I have another question around it.
In the Xamarin version, you can't zoom to a lower value then 1.0. Now a days meny phones have "wide angel" letting the user "zoom out" to e.g. 0.5. Will this be supported in this new cameraview?

**Comment by pictos** [comment]
Hey @andreasbrostencab, so for the first release the zoom feature will not be supported. But the architecture that I'm thinking of will make easier for you, as a developer, to override or add new features to the CameraView.

**Comment by E75** [comment]
@pictos when will a first version be released?

**Comment by MGohil** [comment]
@pictos : Is there any date we can know when the very first version is available at-least with very minimal basic feature would be great?
Eagerly waiting for this to get released soon.

Thanks.

**Comment by pictos** [comment]
@lpappas28, last that I checked winUI doesn't have a cameraView control. Not sure if they provided one so far

**Comment by vanyok1991** [comment]
Hi, any updates when Camera View will be released?

**Comment by kfrancis** [comment]
Where is this proposal? Can this get moving?

**Comment by kfrancis** [comment]
> Where is this proposal? Can this get moving?

Alternatively, how can we help get this moving?

**Comment by quanzhenying** [comment]
很久没更新了，还在继续编码吗?我很需要CameraView
It hasn't been updated for a long time. Are you still coding? I really need CameraView

**Comment by frarcedev** [comment]
Hello guys, any news about using CameraView in .NET MAUI?

**Comment by CliffAgius** [comment]
Hey all,

I see this issue raised on the recent community stand-up and as I am working on a personal app that needs the camera thought I would take a look.  I am a little confused however as it looks like this will be adding Camera function like Take Photo or Shoot Video, however there is already `MediaPicker` that will do this within MAUI the docs are [here](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/device-media/picker?tabs=android&view=net-maui-7.0)

So is the MCT team adding to this or re-inventing? or is it that the MCT team and the MAUI team are both doing the same work in the same area?

The  V1.0 above shows that you want to Take a Photo, preview and use the flash but the Media Picker already does this I've been using it.

**Comment by thra02ad** [comment]
For my purpose, I am looking to customize the camera screen to fit my app design.

**Comment by CliffAgius** [comment]
Ahhh I understand and yes that would be helpful, so if the MAUI team have it working for calling the Native camera app as it looks like we have a starting point that we need to build on.

I guess also we would want to match the API so that if/when this is added to MAUI it merges in a nice way with the same naming and the way it works.  This means we should maybe take the API currently in use and overload the methods with what we want.

**Comment by bijington** [comment]
@CliffAgius the plan is not to match what the essentials APIs offer but instead allow a developer to build the preview into their own app. Essentially giving them the ability to build a camera app in itself but with the added benefit of being able to process the images and other things.

**Comment by CliffAgius** [comment]
Ok I understand now. Where are we at with this then is the API designed or someone working on the code?

Happy to dive in I have some time at the moment unless you want help elsewhere that is.

**Comment by bijington** [comment]
Thanks @CliffAgius. As far as status, @pictos has a branch with Android in and working and is hopeful of opening a draft PR for us to get some understanding of the progress. The task is then to provide a matching iOS implementation based on the detail higher up in this proposal. I had offered my time for it but if it is something you are keen to do then I would be happy to assist where you need.

**Comment by alexvarel** [comment]
Thank you very much @CliffAgius @bijington @pictos. I hope to use the CameraView preview in the future to migrate my application from Xamarin to MAUI. 
Grateful to you guys!

**Comment by hjam40** [comment]
Hi,

I have implemented a CameraView for all platforms with Zxing codebar detecting integrated if you wanna try it [Camera.MAUI](https://github.com/hjam40/Camera.MAUI). If you are interested I could integrate it here.

**Comment by CliffAgius** [comment]
This is awesome @hjam40 and could be a perfect starting point for this proposal.

**Comment by bijington** [comment]
@hjam40 thank you for sharing this. I am taking over this proposal from @pictos so I will aim to see what he has implemented in this initial PR at: and then see if we have some kind of overlap in terms of what we want to achieve.

**Comment by nurfitri97** [comment]
Is it possible to use it in the Blazor Webview?

**Comment by bijington** [comment]
> Is it possible to use it in the Blazor Webview?

No this proposal won't be providing support for Blazor WebView

**Comment by Cybrosys** [comment]
This might be a silly question, but you mentioned CameraX, so I was wondering how you would get access to it since it's a Jetpack library? My initial reaction would be to update the build.gradle in the main .NET MAUI repo, to pull in the CameraX dependencies, is there some other way?

**Comment by zhitaop** [comment]
Hi, any updates for this proposal? We are looking to implement a camera view in our MAUI app and are considering different options

**Comment by bijington** [comment]
It is on my list of things to pick up, hopefully going to take a look in August.

**Comment by StonedHackerman** [comment]
maybe you could yoink some code from this: https://github.com/hjam40/Camera.MAUI

**Comment by Dresel** [comment]
@bijington would you mind if I takeover some parts or start with an initial draft PR?

**Comment by Dresel** [comment]
> > @bijington would you mind if I takeover some parts or start with an initial draft PR?
> 
> Please feel free to get involved. I see you have grabbed @pictos draft PR for this work

Alright, let's go. I have scheduled sometime next weeks, let's see how far I get.

**Comment by kfrancis** [comment]
Will the proposal API allow for real-time usage of the camera frame data (ie, constant vs discreet capture) so that we can do things like barcode (by far the most requested use of this feature) or OCR (tesseract)?

**Comment by pictos** [comment]
@kfrancis you can see what will be support on the first spec of this issue

**Comment by peruchali** [comment]
Hi folks, just curious if there's any update on this?

**Comment by Dresel** [comment]
Work in progress, see https://github.com/CommunityToolkit/Maui/pull/1387#issuecomment-1740322198

**Comment by LeoJHarris** [comment]
Jumping on the back of this, thread as we are middle of migrating to MAUI. We want to find the easiest route with least friction on integrating a camera plugin and hoping this will be included very soon in this library so we wont have to find a temporary work around library. Is there any ETA for this to be completed?

**Comment by mroseberry99** [comment]
Any updates on the CameraView, specifically for Android and iOS?  Is this still being worked on?

**Comment by bijington** [comment]
I believe @jfversluis is waiting on some feedback on this. And if that doesn't pan out I'll be jumping on this

**Comment by jfversluis** [comment]
Correct! I actually pinged them today, which is people from the community who have a working CameraView in their app and are willing to put that in the Toolkit so we have the support for MAUI. Hopefully I'll get word on that soon and else @bijington has offered to take a look, so should be news soon!

**Comment by mroseberry99** [comment]
Fantastic guys, can't wait to get it.  Thanks for the update.

**Comment by bijington** [comment]
Not sure if this should be included in the description but this is the API design that the kind team are going to be contributing:

## `CameraView`

The UI element/view that can be added to an applications UI and renders the preview from a connected camera.

```csharp
public class CameraView
{
    public static readonly BindableProperty SelectedCameraProperty; // Or possibly ActiveCameraProperty
    public static readonly BindableProperty ZoomFactorProperty;
    public static readonly BindableProperty ResolutionProperty;
    public static readonly BindableProperty IsCameraBusyProperty;
    public static readonly BindableProperty IsAvailableProperty;
    public static readonly BindableProperty FlashModeProperty;
    public static readonly BindableProperty IsTorchOnProperty;

    public event EventHandler<MediaCapturedEventArgs> MediaCaptured;
    public event EventHandler<MediaCaptureFailedEventArgs> MediaCaptureFailed;

    public CameraInfo? SelectedCamera { get; set; } // Or possibly ActiveCamera
    public float ZoomFactor { get; set; }
    public Size Resolution { get; set; } // I believe this only covers the capture resolution - perhaps it should be named `CaptureResolution`?
    public bool IsCameraBusy { get; set; }
    public bool IsAvailable { get; set; }
    public bool IsTorchOn { get; set; }
    public CameraFlashMode FlashMode { get; set; }

    public void Shutter()
    public void Start()
    public void Stop()
}
```

## `CameraFlashMode`

Enumeration of the possible modes the flash can be set to.

```csharp
public enum CameraFlashMode
{
    Off,
    On,
    Auto
}
```

## `CameraInfo`

Provides information about a camera that is connected to a device.

```csharp
public class CameraInfo
{
    public string Name { get; }

    public string DeviceId { get; }

    public CameraPosition Position { get; }

    public bool IsFlashSupported { get; } // Could/should we enhance this to be a list of capabilities to cover other features like Auto Focus, etc.?

    public float MinimumZoomFactor { get; }

    public float MaximumZoomFactor { get; }

    public ObservableCollection<Size> AvailableResolutions { get; } // two questions; 1. does this need to be observable? 2. maybe SupportedResolutions is a better name?
}
```

## `CameraPosition`

Enumeration of the possible positions a camera can take.

```csharp
public enum CameraPosition // Should we have an External value? Can we determine that?
{
    Unknown,
    Rear,
    Front
}
```

## `CameraProvider`

Provides the ability to obtain information about the cameras connected to the device.

```csharp
public class CameraProvider
{
    public ObservableCollection<CameraInfo> AvailableCameras { get; }

    public void RefreshAvailableCameras();
}
```

It would be great if the `CameraView` could make use of the `CameraProvider` class internally by default but allow a developer to interact with it as well.

**Comment by aritchie** [comment]
Any chance you guys would consider adding the ability to have a stream come out of the cameraview for processing through things like AI, barcode scanners, etc?

```csharp
public class CameraView
{
    public Stream OpenStream();
}
```

Maybe a binding point to Command<Stream>?

**Comment by bijington** [comment]
> Any chance you guys would consider adding the ability to have a stream come out of the cameraview for processing through things like AI, barcode scanners, etc?
> 
> 
> 
> ```csharp
> 
> public class CameraView
> 
> {
> 
>     public Stream OpenStream();
> 
> }
> 
> ```
> 
> 
> 
> Maybe a binding point to Command<Stream>?
> 
> 
> 
> 

Yes definitely! There isn't anything really documented but this is something that we hope to follow up on once the CameraView gets merged. 

The current thinking is to provide potentially 2 mechanisms of achieving this:
- through some level of access at the platform level, this is to avoid unnecessary allocations/conversions between platform types and common types if a dev wants to process the data on the platform itself. 
- through some common API that is accessible in the common code. 

The thought behind this would allow developers to build something as performant as possible which would likely be important if doing something like image processing. 

That's a just a conceptual description but how does that sound? I know we have a discussion on barcode scanning that I've been meaning to update. This would likely be a first good use case for it.

**Comment by MagicAndre1981** [comment]
Does it support [camera extensions](https://developer.android.com/media/camera/camera-extensions) of the Phone in Android like the [Google Camera Service](https://play.google.com/store/apps/details?id=com.google.android.apps.camera.services&hl=gsw) to get Google optimizations? 

> Pixel Camera Services is a system component that **brings Pixel Camera features like Night Sight to some 3rd party apps** that you’ve granted permission to use your camera. This component is pre-installed on your device and should be kept up to date to ensure you have the latest image processing updates and other bug fixes.
