### ISSUE TITLE
[Bug] Spurious warnings generated after adding CommunityToolkit.Maui to project

### ISSUE THREAD

**Issue by IndianaGary** [CommunityToolkit/Maui#268]
### Description
After a recent update to Pre5, I noted that any time I add CommunityToolkit.Maui to a Project, it begins generating spurious warning messages referencing TextColorToGenerator and nullability whenever I Build it. 

### Stack Trace

Not applicable, however an binlog is attached (see below)

### Steps to Reproduce

1.  Launch VS 2022 17.1 Preview 4.0
2.  Create a new OOTB Maui application
3.  Add the CommunityToolkit.Maui Pre5 NuGet package to the Solution 
4.  Build
5. Observe the Output window during the build to see the warnings

### Expected Behavior
No warnings

### Actual Behavior
Warnings generated

### Basic Information

- Version with issue: Maui Preview 12, CommunityToolkit.Maui Pre5
- Last known good version: Unknown
- IDE: VS 2022 17.1 Preview 4.0
- Platform Target Frameworks: 
  - iOS:  Not tested
  - Android: Supported = 21, Target = N/A
  - WinUI: Supported = 10.0.17763.0, Target = 10.0.19041
- Android Support Library Version: 21
- Nuget Packages: Default for new OOTB Maui app, added CommunityToolkit.Maui Pre5
- Affected Devices: N/A, build issue

### Workaround
Adding `<Nullable>enable</Nullable>` to the Project file eliminates these warnings.

### Reproduction imagery

Output Window contents:
    See attached files: Warnings.txt and unzip Binlog.zip

    [Warnings.txt](https://github.com/CommunityToolkit/Maui/files/7980215/Warnings.txt)

    [Binlog.zip](https://github.com/CommunityToolkit/Maui/files/7980240/Binlog.zip)

**Comment by pictos** [comment]
@IndianaGary can you attach the project that you saw this issue?

**Comment by IndianaGary** [comment]
The project, minus the bin and obj folders, is attached
[OOTBMauiApp1.zip](https://github.com/CommunityToolkit/Maui/files/7981207/OOTBMauiApp1.zip)
,

**Comment by brminnick** [comment]
Adding additional info provided by @IeuanWalker in Discussion https://github.com/CommunityToolkit/Maui/discussions/272#discussioncomment-2099908:


![](https://user-images.githubusercontent.com/6544051/152239847-b3b5173e-f35c-40f7-92b9-74e2c2fdc3f0.png)

**Comment by IeuanWalker** [comment]
Also getting a warning for android - 
![image](https://user-images.githubusercontent.com/6544051/152242516-5df60ba2-d6e8-427e-9e3c-39b66821c80a.png)

**Comment by brminnick** [comment]
Confirmed that the `CommunityTolkit.Maui-pre5` DLL shows `SupportedOSPlatform("Android31.0")`, even though we use 21.0 in the [CSPROJ file](https://github.com/CommunityToolkit/Maui/blob/a62ca26c1d9693fba24b67b5eb3c3c4697ae2573/src/CommunityToolkit.Maui/CommunityToolkit.Maui.csproj#L13-L17).

Perhaps this is a problem with our CI Pipeline?

<img width="1226" alt="Screen Shot 2022-02-02 at 3 13 44 PM" src="https://user-images.githubusercontent.com/13558917/152253798-e0313d53-0f0d-4b2a-986c-c408d4274236.png">
7

**Comment by brminnick** [comment]
Confirmed the same problem in exists in `CommunityToolkit.Maui-pre4`

Confirmed the problem does not exist in `CommunityToolkit.Maui-pre3`

**Comment by brminnick** [comment]
Confirmed the Issue occurs with the `VSBuild@1` task in our CI Pipeline.

Using `dotnet pack -c Release` in our CI Pipeline creates a NuGet Package targeting `net6.0`, `net6.0-ios`, `net6.0-android` and `net6.0-maccatalyst` whose DLLs all contain the correct `OSSupportedVersion` and correct `TargetPlatform`. But it does not include the `net6.0-windows` DLL.

Using the `VSBuild@1` task in our CI Pipeline creates a NuGet Package targeting `net6.0`, `net6.0-ios`, `net6.0-android`, `net6.0-maccatalyst` and `net6.0-windows` whose DLLs all contain the **incorrect** `OSSupportedVersion` and **incorrect** `TargetPlatform`.

`VSBuild@1` currently uses VS v17.0 (Current Stable release of VS 2022) and does **not** yet have support for VS v17.1 (Current Preview release of VS 2022) which is required for .NET MAUI.

I have a hunch that once VS v17.1 is promoted to Stable and the `VSBuild@1` adds support for it, that this problem may resolve itself.
