### ISSUE TITLE
[Proposal] Ship ReadMe.txt file with packages to inform consumers of necessary steps

### ISSUE THREAD

**Issue by bijington** [CommunityToolkit/Maui#273]
# [FEATURE_NAME] Ship `ReadMe.txt` file with packages to inform consumers of necessary steps

* [x] Proposed
* [x] Prototype
* [ ] Implementation: Not Started
  * [ ] iOS Support
  * [ ] Android Support
  * [ ] macOS Support
  * [ ] Windows Support
* [ ] Unit Tests: Not Started
* [ ] Sample: Not Started
* [ ] Documentation: Not Started

## Link to Discussion

This is being raised as a result of discussion #272 where the consumer saw that using a converter in XAML only was reporting build issues.

## Summary
[summary]: #summary

Add a README.txt to the NuGet Package that provide guidance to consumers on how to Use the toolkit upon installation.

The Getting Started step should detail the extension method usage to initialise the library:

```csharp
builder.UseMauiApp<App>().UseMauiCommunityToolkit();
```

And then refer the developer on to the docs website for further details.

Also add the Getting Started steps to the GitHub Repository README.md, along with a NuGet Package badge:
 
[![NuGet](https://buildstats.info/nuget/CommunityToolkit.Maui?includePreReleases=true)](https://www.nuget.org/packages/CommunityToolkit.Maui/)

## Motivation
[motivation]: #motivation

To make it easier to get going in using the toolkit packages.

## Detailed Design
[design]: #detailed-design

It should involve the addition of a readme.txt to each project and then adding this line to each project:

```xml
<None Include="readme.txt" pack="true" PackagePath="." />
```

## Usage Syntax
[usage]: #usage-syntax

N/A

## Drawbacks
[drawbacks]: #drawbacks

We would need to cover what happens if both `CommunityToolkit.Maui` and `CommunityToolkit.Maui.Core` are added. We don't need to inform the user they need to use both methods.

## Alternatives
[alternatives]: #alternatives

Do nothing? Leave it in the documentation online.

## Unresolved Questions
[unresolved]: #unresolved-questions

**Comment by brminnick** [comment]
Thanks Shaun! Love this idea to help devs get up and running quickly with the .NET MAUI Community Toolkit! 💯 

As a part of this effort, could we also add the Getting Started info to our GitHub Repository `README.md` too? 

We can put the Getting Started info in the top of the `README.md` before the [Submitting a New Feature section]([https://github.com/CommunityToolkit/Maui#submitting-a-new-feature), along with a NuGet Package badge:
 
[![NuGet](https://buildstats.info/nuget/CommunityToolkit.Maui?includePreReleases=true)](https://www.nuget.org/packages/CommunityToolkit.Maui/)

## Getting Started

// ...

**Comment by bijington** [comment]
Yes great idea!

**Comment by VladislavAntonyuk** [comment]
I think we can move it to completed

**Comment by bijington** [comment]
thanks @VladislavAntonyuk msftbot seemed to want to keep it open for some reason :shrug:
