### ISSUE TITLE
[Proposal] Replace all NotImplementedException throws with NotSupportedException

### ISSUE THREAD

**Issue by bijington** [CommunityToolkit/Maui#292]
# [CHANGE] Replace all `NotImplementedException` throws with `NotSupportedException`

* [x] Proposed
* [x] Prototype
* [ ] Implementation: Not Started
  * [ ] iOS Support
  * [ ] Android Support
  * [ ] macOS Support
  * [ ] Windows Support
* [ ] Unit Tests: Not Started
* [ ] Sample: Not Started
* [ ] Documentation: Not Started

## Link to Discussion

Came out of PR #289

## Summary
[summary]: #summary

Replace all `NotImplementedException` throws with `NotSupportedException` to give a clearer indication that something is not supported rather than not supported yet or we forgot to implement it.

## Motivation
[motivation]: #motivation

To provide a clearer indication to consumers that we have decided not to support something.

## Detailed Design
[design]: #detailed-design

~`throw new NotImplementedException();`~

becomes

`throw new NotSupportedException("Meaningful reason why.");`

**Bonus points:** find a way to make usage of `NotImplementedException` a warning/error. Likely a `.editorconfig` rule if possible.

## Usage Syntax
[usage]: #usage-syntax

N/A

## Drawbacks
[drawbacks]: #drawbacks

None I can think of.

## Alternatives
[alternatives]: #alternatives

Do nothing?

## Unresolved Questions
[unresolved]: #unresolved-questions

None I can think of.

**Comment by brminnick** [comment]
Thanks @bijington! Do you want to Champion this Proposal? 

I also know you're also working hard on writing the docs!

**Comment by bijington** [comment]
Yeah I'll happily do it
