### ISSUE TITLE
[Bug] Getting build error when configured with `UseMauiCommunityToolkit()` and targeting the Windows platform

### ISSUE THREAD

**Issue by egvijayanand** [CommunityToolkit/Maui#299]
### Description

Getting the below-mentioned error when configured with UseMauiCommunityToolkit() initialization and building for the Windows target

### Stack Trace

Here is the Build Output log:

Build started...
1>------ Build started: Project: TestApp, Configuration: Debug Any CPU ------
1>TestApp -> E:\Tasks\Projects\Maui\TestApp\TestApp\bin\Debug\net6.0-windows10.0.19041\win10-x64\TestApp.dll
1>WINAPPSDKGENERATEPROJECTPRIFILE : error : PRI175: 0x80073b0f - Processing Resources failed with error: Duplicate Entry.
1>WINAPPSDKGENERATEPROJECTPRIFILE : error : PRI222: 0x80073b0f - Unspecified error occurred.
1>Done building project "TestApp.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

### Steps to Reproduce

1. Create a new .NET MAUI App (Preview 12/Preview 13) and add a reference to the latest release of CommunityToolkit.Maui NuGet package (1.0.0-pre6)
2. Configure the `UseMauiCommunityToolkit()` initialization method call in the `MauiProgram.cs`
3. Switch the Target platform to Windows (in supported VS2022 Preview IDE) and build the project
4. Ends up in the build error

### Expected Behavior
Build should succeed without any error.

### Actual Behavior
Ends up in build error.

### Basic Information

- Version with issue: .NET MAUI Preview 12 or higher and CommunityToolkit.Maui 1.0.0-pre6
- Last known good version: NA
- IDE: VS2022 17.1 Preview 3.0 or later
- Platform Target Frameworks: 
  - iOS:  NA
  - Android:  NA
  - UWP:   **net6.0-windows10.0.19041**
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

None found so far

**Comment by VladislavAntonyuk** [comment]
It will be fixed with pre7

**Comment by brminnick** [comment]
Reopening this after confirming it continues to exist on `CommunityToolkit.Maui-pre7`.

Here is a reproduction sample app I made using the latest .NET MAUI Template in Visual Studio 2022 Preview v17.2.0 Preview 1: https://github.com/brminnick/WINAPPSDKGENERATEPROJECTPRIFILE_ReproductionSample/tree/main

### Reproduction Steps
1. Download/Clone the reproduction sample repository: https://github.com/brminnick/WINAPPSDKGENERATEPROJECTPRIFILE_ReproductionSample/tree/main
2. In Visual Studio 2022 Preview, open `MauiApp1.sln`
3. In Visual Studio 2022 Preview, select framework `net6.0-windows10.0.19041`
4. In Visual Studio 2022 Preview, build 
4. Confirm `WINAPPSDKGENERATEPROJECTPRIFILE` error

**Comment by egvijayanand** [comment]
Hi @brminnick,

I just now tried with a blank .NET MAUI App (Preview 13), including the latest (1.0.0-pre7) package, and then added the UseMauiCommunityToolkit() initialization call to verify whether the build issue is resolved.

Build completed successfully and able to launch the app and work with it on Windows platform.

Maybe I'll give it a try by cloning your reproduction sample.

Regards,
Vijay Anand E G

**Comment by VladislavAntonyuk** [comment]
@brminnick probably you need to clean bin/obj and restore nuget packages again. I had the same issue

**Comment by brminnick** [comment]
@VladislavAntonyuk Are you able to reproduce the error using the [reproduction sample](https://github.com/CommunityToolkit/Maui/issues/299#issuecomment-1041904208)?

**Comment by VladislavAntonyuk** [comment]
@brminnick you missed Properties/launchSettings.json file
After adding it I was able to run the app
![image](https://user-images.githubusercontent.com/33021114/154329402-1d9c7385-1645-457b-94d3-10f9e0dd386c.png)

**Comment by VladislavAntonyuk** [comment]
```
{
  "profiles": {
    "Windows Machine": {
      "commandName": "MsixPackage",
      "nativeDebugging": false
    }
  }
}
```

**Comment by brminnick** [comment]
Ok, great! 

I'll let the MAUI team know that this file is missing from the template 👍

**Comment by VladislavAntonyuk** [comment]
@brminnick it is available. for some reason it was in gitignore in your repo

**Comment by brminnick** [comment]
🤦‍♂️
