### ISSUE TITLE
[Bug] CommunityToolkit.Maui 1.0.0-pre7 is broken in .NET MAUI Preview 14

### ISSUE THREAD

**Issue by rjygraham** [CommunityToolkit/Maui#328]
### Description

CommunityToolkit.Maui 1.0.0-pre7 seemingly broken in .NET MAUI Preview 14. Builds for Windows are broken after adding 
CommunityToolkit.Maui package to the project.

### Stack Trace

N/A

### Link to Reproduction Sample

N/A

### Steps to Reproduce

1. File -> New Project .NET MAUI Preview 14 App
2. Install CommunityToolkit.Maui 1.0.0-pre7 package
3. Ensure build target is set to Windows
4. Build

### Expected Behavior

Build completes successfully.

### Actual Behavior

Build fails with various messages depending on build target.

####Windows
````Severity	Code	Description	Project	File	Line	Suppression State
Error		PRI175: 0x80073b0f - Processing Resources failed with error: Duplicate Entry.	MauiApp2	C:\Users\user1\source\repos\MauiApp2\MauiApp2\WINAPPSDKGENERATEPROJECTPRIFILE	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error		PRI222: 0x80073b0f - Unspecified error occurred.	MauiApp2	C:\Users\user1\source\repos\MauiApp2\MauiApp2\WINAPPSDKGENERATEPROJECTPRIFILE	1	
````

### Basic Information

- Version with issue: 1.0.0-pre7 + .NET MAUI Preview 14
- Last known good version: 1.0.0-pre7 + .NET MAUI Preview 13
- IDE: Visual Studio 2022 17.2.0 Preview 2.0
- Platform Target Frameworks: 
  - UWP:  19041
- Nuget Packages:
  - Microsoft.WindowsAppSDK 1.0.1
  - Microsoft.Graphics.Win2D 1.0.0.30
  - CommunityToolkit.Maui 1.0.0-pre7
  - CommunityToolkit.Mvvm 8.0.0-preview2

### Workaround

N/A

**Comment by brminnick** [comment]
Thanks @rjygraham!

This is expected as each new Preview release of .NET MAUI contains breaking changes.

Fixed in #325
