### ISSUE TITLE
[Bug] Fresh copy of CommunityToolkit.Maui.Sample results in multiple "CS0016	Could not write to output file" errors

### ISSUE THREAD

**Issue by WillAutioItrax** [CommunityToolkit/Maui#340]
I updated to the latest version of Microsoft Visual Studio Professional 2022 (64-bit) - Preview
Version 17.2.0 Preview 2.1
Then I downloaded CommunityToolkit.Maui.Sample and tried to run it. 
Instead of getting a sample app to run on an Android, I got 4 errors like the one below:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0016	Could not write to output file 
'C:\Users\<myID>\Maui-main\samples\CommunityToolkit.Maui.Sample\obj\GeneratedFiles\CommunityToolkit.Maui.SourceGenerators\
CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\DatePickerTextColorTo_dd52ff70-c0f6-46b1-a1bd-d89ff31ea2f0.g.shared.cs' -- 
'Could not find a part of the path 
'C:\Users\<myID>\Maui-main\samples\CommunityToolkit.Maui.Sample\obj\GeneratedFiles\CommunityToolkit.Maui.SourceGenerators\
CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\DatePickerTextColorTo_dd52ff70-c0f6-46b1-a1bd-d89ff31ea2f0.g.shared.cs'.'	
CommunityToolkit.Maui.Sample (net6.0-ios)	
C:\Users\<myID>\Maui-main\samples\CommunityToolkit.Maui.Sample\CSC	1	Active

I checked and the indicated file (DatePickerTextColorTo_dd52ff70-c0f6-46b1-a1bd-d89ff31ea2f0.g.shared.cs in the case above) does not exist. 

Thanks for looking at this.

### Steps to Reproduce

1. See the Description above.
2. 
3. 

### Expected Behavior
The app compile and run.
### Actual Behavior
The app gives error messages during compile.
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - Samsung SM-G970W (Android 12.0 - API31)
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: Default ones
- Affected Devices:

**Comment by brminnick** [comment]
Hi @WillAutioItrax! 

This is a bug in Visual Studio on Windows, specifically with Win32 + MAX_PATH.

The fix is to increase the maximum path length limitation in the Windows Registry to allow for file paths longer than 260 Characters.

Here's the steps to fix it in Windows 10, Version 1607, and Later:

https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?WT.mc_id=mobile-0000-bramin#enable-long-paths-in-windows-10-version-1607-and-later

**Comment by brminnick** [comment]
Oh and one more thing: when you launch Visual Studio, ensure that you are running it as an administrator:

> 1. Open the Start menu, and scroll to Visual Studio.
> 2. From the right-click or context menu of Visual Studio 2019 or Visual Studio 2022, select More > Run as administrator.
> 
> When Visual Studio starts, (Administrator) appears after the product name in the title bar.

https://docs.microsoft.com/en-us/visualstudio/ide/user-permissions-and-visual-studio?view=vs-2022?WT.mc_id=mobile-0000-bramin#run-visual-studio-as-an-administrator

**Comment by WillAutioItrax** [comment]
@brminnick Thanks for your reply. 
I had a look at your links and the first one mentioned making a change to the Registry as well as the app manifest file.
I was able to change the Registry. In the Maui app, I could not find a manifest file. So, I ran it only with the Registry change.
That worked for me.
Thanks!
