### ISSUE TITLE
[Bug] iOS SnackBar Message Doesn't Have Action Button

### ISSUE THREAD

**Issue by mpkagel** [CommunityToolkit/Maui#344]
### Description
I've attached a sample project that demonstrates the issue.
The snackbar message doesn't show the action button in iOS. The action button for the snackbar does
show in Android.
As an additional note changing font size doesn't seem to affect this.

### Steps to Reproduce
In iOS
1. Run sample project.
2. Click "Open Snack Bar Message"
3. The snackbar message appears without an action OK button.

### Expected Behavior
The snackbar message should have an action button in iOS.

### Actual Behavior
The snackbar message does not have an action button in iOS.

### Basic Information
- Version with issue: CommunityToolkit.Maui 1.0.0-pre8, Maui 14
[MauiFlyout.zip](https://github.com/CommunityToolkit/Maui/files/8383946/MauiFlyout.zip)

**Comment by mpkagel** [comment]
Also, this looks like a similar issue that was fixed in the Xamarin Community Toolkit:
https://github.com/xamarin/XamarinCommunityToolkit/issues/1777
https://github.com/xamarin/XamarinCommunityToolkit/pull/1783

**Comment by mpkagel** [comment]
I set an action for the Snackbar of: async () => { await Shell.Current.GoToAsync($"///{nameof(ItemsPage)}"); } in the sample project that I attached above. I couldn't see the OK button in iOS after making this change.

**Comment by VladislavAntonyuk** [comment]
Reproduced, thank you.
I have an ugly hot fix, but I will try to find a better solution.
