### ISSUE TITLE
[Proposal] Animation Behavior

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#35]
# Animation Behavior

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Documentation: https://github.com/MicrosoftDocs/CommunityToolkit/pull/121
* [x] Sample: https://github.com/CommunityToolkit/Maui/blob/main/samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/AnimationBehaviorPage.xaml

## Summary
[summary]: #summary

`AnimationBehavor` is a `Behavior` that can be attached to any `VisualElement`, allowing developers to trigger the following animations via `ICommand AnimateCommand`:
* [x] #519
* [ ] FlipHorizontalAnimation
* [ ] FlipVerticalAnimation
* [ ] RotateAnimation
* [ ] ScaleAnimation
* [ ] ShakeAnimation

## Motivation
[motivation]: #motivation

`AnimationBehavior` solves the following challenges:
- [x] Animations are not easily accomplished in XAML
- [x] Animations are not easily accomplished using `ICommand`

Following the implementation of `AnimationBehavior`, developers will easily be able to create bindable animations for any `VisualElement`

## Detailed Design
[design]: #detailed-design

### AnimationBehavior.shared.cs

`AnimationBehavior` is a `Behavior` can be attached to any `VisualElement`.

`AnimationBehavior` implements `EventToCommandBehavior`.

```cs
public class AnimationBehavior : EventToCommandBehavior
{
    public static readonly BindableProperty AnimationTypeProperty;
    public static readonly BindableProperty AnimateCommandProperty;

    public AnimationBase? AnimationType { get; set; }
    public ICommand AnimateCommand { get; }
}
```

### AnimationBase<TView>

`AnimationBase` is an `abstract` class implementing `BindableObject` that allows for creating animations.

```cs
public abstract class AnimationBase<TView> : BindableObject where TView : View
{
    public static readonly BindableProperty DurationProperty;
    public static readonly BindableProperty EasingTypeProperty

    public uint Duration { get; set; }
    public Easing Easing { get; set; }

    public abstract Task Animate(TView? view);
}
```

**Comment by stefanbogaard86** [comment]
Hi @brminnick, I love this feature. I can have a go at implementing it if you like.

**Comment by brminnick** [comment]
Thanks @stefanbogaard86! Assigned 👍
