### ISSUE TITLE
[Bug] Snackbar opens a new app process on Windows

### ISSUE THREAD

**Issue by emorell96** [CommunityToolkit/Maui#353]
### Description

Snackbar opens a new window as shown here when you click the action button on Windows.

### Steps to Reproduce

1. Place a snackbar inside the default template.
2. Click on the toast action button
3. See how a new window appears.

### Expected Behavior
Action executes inside the current open app without opening a new app.

### Actual Behavior

Action executes and a new app process is opened.

### Basic Information

- Version with issue: prev 8 (MAUI prev 14)
- Last known good version: unknown
- IDE: VS

### Workaround
None without modifying the snackbar files, since the snackbar registers itself to the Activated event instead of using the solution below:

I just wanted to share a little what I've discovered after quite a bit of experimentation. I thought it might be useful for your nuget.

On Windows there's two kind of activations for UWP apps: foreground and background. The former will use the current app but you need to modify the package.appxmanifext file if you want to use `ToastNotificationManagerCompat.OnActivated`. You must both modify the appxmanifest as indicated [here](https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/send-local-toast?tabs=uwp#step-3-handling-activation) in order to make this work without opening a new window. The background activation uses background tasks instead but they require the background tasks to be either registered as an In-Process background task or Out-of-Process background task as shown [here](https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/send-local-toast?tabs=uwp#handling-background-activation).

For my use case the background task sounded ideal, but I was unable to make it work with MAUI (at least for the In-Process Background tasks). I kept getting argument out of range exception.

I might try the out-of-process background tasks later.

In any case, one way I found to solve this issue using the foreground activation (the one currently used [here](https://github.com/CommunityToolkit/Maui/blob/main/src/CommunityToolkit.Maui/Alerts/Snackbar/Snackbar.windows.cs)), you need to make this change to the `package.appxmanifest`:

in the Package element this needs to be added:
```xml
xmlns:desktop="http://schemas.microsoft.com/appx/manifest/desktop/windows10" 
xmlns:com="http://schemas.microsoft.com/appx/manifest/com/windows10"
IgnorableNamespaces="uap rescap com desktop"
```

Inside of the applications:
```xml
<Applications>
    <Application Id="App" Executable="$targetnametoken$.exe" EntryPoint="$targetentrypoint$">
      <uap:VisualElements />
     <Extensions>

        <!-- Specify which CLSID to activate when toast clicked -->
        <desktop:Extension Category="windows.toastNotificationActivation">
          <desktop:ToastNotificationActivation ToastActivatorCLSID="guid-used-in-maui-csproj" /> 
        </desktop:Extension>

        <!--Register COM CLSID LocalServer32 registry key-->
        <com:Extension Category="windows.comServer">
          <com:ComServer>
            <com:ExeServer Executable="filename-used-for-the-exe-usually-the-assembly-name.exe" Arguments="-ToastActivated" DisplayName="Toast activator">
              <com:Class Id="guid-used-in-maui-csproj" DisplayName="Toast activator"/>
            </com:ExeServer>
          </com:ComServer>
        </com:Extension>

      </Extensions>
    </Application>
  </Applications>
```
Using `$targetnametoken$.exe` for the executable in com:ExeServer didn't work. I had to manually enter the assembly name.

Finally I register in the MauiProgram.cs the event:

```csharp
using Microsoft.Toolkit.Uwp.Notifications;
builder.
... (every other build action)
.ConfigureLifecycleEvents(configure =>
            {
				configure.AddWindows(c =>
				{
					c.OnLaunched((window, args) =>
					{
						ToastNotificationManagerCompat.OnActivated += WindowsNotificationService.OnActivated;
					});
                });
            });
```

I made this minimal repo that works:
https://github.com/emorell96/MauiWithWindowsToasts

I guess to make the snackbar work you could do:

```csharp
	/// <summary>
	/// Show Snackbar
	/// </summary>
	private partial async Task ShowNative(CancellationToken token)
	{
		await DismissNative(token);
		token.ThrowIfCancellationRequested();
		var toastContentBuilder = new ToastContentBuilder()
			.AddText(Text)
			.AddButton(
				new ToastButton { ActivationType = ToastActivationType.Foreground }.SetContent(ActionButtonText));

		var toastContent = toastContentBuilder.GetToastContent();
		toastContent.ActivationType = ToastActivationType.Background;

		dismissedTCS = new();

		var xmlDocument = new XmlDocument();
		xmlDocument.LoadXml(toastContent.GetContent());

		NativeSnackbar = new ToastNotification(xmlDocument);
		//NativeSnackbar.Activated += OnActivated; //this is not needed anymore
		NativeSnackbar.Dismissed += OnDismissed;
		NativeSnackbar.ExpirationTime = DateTimeOffset.Now.Add(Duration);

		ToastNotificationManager.CreateToastNotifier().Show(nativeSnackbar);

		OnShown();
	}

public static void OnActivated(ToastNotification sender, object args)
	{
		if (NativeSnackbar is not null && Action is not null)
		{
			MainThread.BeginInvokeOnMainThread(Action);
		}
	}

```

And you would register OnActivated in an extension method that the user would have to register if he wants to use snackbar on windows? 

I'd be happy to contribute to it.

Hope it helps.

### Reproduction imagery

![gif](https://user-images.githubusercontent.com/13558917/143683127-5b455f19-7def-463b-b9b9-b4ad3b299a90.gif)

**Comment by VladislavAntonyuk** [comment]
What you described is true for UWP and compatible package ToastNotificationManagerCompat.
We use package for WinU.

As a solution you can allow only 1 instance of the app: https://github.com/CommunityToolkit/Maui/blob/3b78714fac18c132d85948c11651132580e91c59/samples/CommunityToolkit.Maui.Sample/Platforms/Windows/App.xaml.cs#L24

**Comment by VladislavAntonyuk** [comment]
I see you take the guide from https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/toast-notifications
But it is migration like from Xamarin to .NET MAUI. It can be used in XCT MauiCompat package, but not in this library

**Comment by VladislavAntonyuk** [comment]
As a workaround you can implement your own Snackbar

**Comment by emorell96** [comment]
> What you described is true for UWP and compatible package ToastNotificationManagerCompat. We use package for WinU.
> 
> As a solution you can allow only 1 instance of the app:
> 
> https://github.com/CommunityToolkit/Maui/blob/3b78714fac18c132d85948c11651132580e91c59/samples/CommunityToolkit.Maui.Sample/Platforms/Windows/App.xaml.cs#L24

I don't know why you say you cannot use "ToastNotificationManagerCompat" in here if you use the package already on Windows. I saw it the source code: https://github.com/CommunityToolkit/Maui/blob/c319bc9f3a09fcb217654a05e3c586c800ac8c11/src/CommunityToolkit.Maui/Alerts/Snackbar/Snackbar.windows.cs#L1

The solution of limiting instances is not good enough on Desktop where users and app developers might need more than one instance. Desktop apps usually use multiple instances. As such you need to be able to make the distinction between an instance launched by the user and another by the toast notification. That's what the com line in the package manifest does. And what the CommunityToolkit.WinUI.Notifications package uses to know if it should open a new window.

Finally I saw this bug was marked as unverified so I made this reproduction repo: https://github.com/emorell96/SnackbarBug

For the work around, I am using my own implementation anyways since I need more than one button sometimes. But I was having the same issue than in here, so I came to your library to see if you had the same issue, which you did. Having solved mine, I thought you could use the solution.

**Comment by VladislavAntonyuk** [comment]
We use ToastNotificationManager, ToastNotificationManagerCompat doesn’t exist in the package.
Also it is up to you how to handle it OnActivated.
We cannot pass Action() as a parameter of the application.
You need to override OnActivated and run whatever action you need.

As I mentioned we use foreground activation. I will double check if we can switch to background activation.

**Comment by emorell96** [comment]
> We use ToastNotificationManager, ToastNotificationManagerCompat doesn’t exist in the package. Also it is up to you how to handle it OnActivated. We cannot pass Action() as a parameter of the application. Single instance is an example of usage. Not a part of the library. You need to override OnActivated and run whatever action you need.
> 
> As I mentioned we use foreground activation. I will double check if we can switch to background activation.

![image](https://user-images.githubusercontent.com/20151415/162612365-c208f90f-8d10-4b0e-b652-135b639cf264.png)
It is available on that nuget. Of course on Windows only.

**Comment by emorell96** [comment]
> On Windows there's two kind of activations for UWP apps: foreground and background. The former will use the current app but you need to modify the package.appxmanifext file if you want to use `ToastNotificationManagerCompat.OnActivated`. You must both modify the appxmanifest as indicated [here](https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/send-local-toast?tabs=uwp#step-3-handling-activation) in order to make this work without opening a new window. The background activation uses background tasks instead but they require the background tasks to be either registered as an In-Process background task or Out-of-Process background task as shown [here](https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/send-local-toast?tabs=uwp#handling-background-activation).
> 
> For my use case the background task sounded ideal, but I was unable to make it work with MAUI (at least for the In-Process Background tasks). I kept getting argument out of range exception.
> 
> I might try the out-of-process background tasks later.

As for background activation you'd need to use background tasks either in-process or out of process tasks. I couldn't get the in process tasks to work on MAUI out of the box. Registering them threw an argument out of bounds exception. Probably because you need to define the package as have multiple instances which requires a package.appxmanifest change. But I didn't experiment too much since the solution I mentioned worked well enough for me. 

Background Out of Process are probably not a very good option for the nuget since it also requires a package.appxmanifest change.

To be honest all solutions require either a package.appxmanifest change or the super blunt workaround of enabling only one instance of the app (again a bad solution for desktop apps).

**Comment by VladislavAntonyuk** [comment]
We do not use ToastNotificationManagerCompat. It is used only for building ToastContent, I plan to remove it.
We use only ToastNotificationManager which is a part of Windows.SDK. There is no events in this static class

**Comment by emorell96** [comment]
> We do not use ToastNotificationManagerCompat. It is used only for building ToastContent, I plan to remove it. We use only ToastNotificationManager which is a part of Windows.SDK. There is no events in this static class

That's different from saying `ToastNotificationManagerCompat doesn’t exist in the package.` because it does exist in the package. I cannot know what you plan to do. I wrote what I said based on the source code you have available right now.

Now if you do not plan to use ToastNotificationManagerCompat how do you plan to get rid of this bug?

**Comment by VladislavAntonyuk** [comment]
It is up to you. It is a side effect of the Windows Toast Notification. As a workaround, if you do not need a new window, you can close it as the example app does

**Comment by VladislavAntonyuk** [comment]
![image](https://user-images.githubusercontent.com/33021114/162616700-ea35cdfb-1b1b-48d2-b61a-1cbabd4a2e1b.png)

**Comment by emorell96** [comment]
> It is up to you. It is a side effect of the Windows Toast Notification. As a workaround, if you do not need a new window, you can close it as the example app does

It's not a side effect. It's a bug. You cannot truly believe that anyone is happy to have a new app window open when clicking on the action button.

The workaround misses the whole point that if it's a Desktop app you might need more that one window but without this at least well documented, the snackbar is unusable on Windows. Closing every new window might not be ideal for desktop apps.

At least this should be documented here: https://docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/alerts/snackbar

**Comment by emorell96** [comment]
> ![image](https://user-images.githubusercontent.com/33021114/162616700-ea35cdfb-1b1b-48d2-b61a-1cbabd4a2e1b.png)

Also, this works on MAUI as shown on the UWP tab AFAIK. Change it to activation type to background and you'll see that it doesn't open a new app, it just does nothing.

**Comment by VladislavAntonyuk** [comment]
> > ![image](https://user-images.githubusercontent.com/33021114/162616700-ea35cdfb-1b1b-48d2-b61a-1cbabd4a2e1b.png)
> 
> Also, this works on MAUI as shown on the UWP tab AFAIK. Change it to activation type to background and you'll see that it doesn't open a new app, it just does nothing.

I know that. That is why we use Foreground activation. it is better than nothing

**Comment by VladislavAntonyuk** [comment]
> > ![image](https://user-images.githubusercontent.com/33021114/162616700-ea35cdfb-1b1b-48d2-b61a-1cbabd4a2e1b.png)
> 
> Also, this works on MAUI as shown on the UWP tab AFAIK. Change it to activation type to background and you'll see that it doesn't open a new app, it just does nothing.

I know that. That is why we use Foreground activation. it is better than nothing

**Comment by VladislavAntonyuk** [comment]
> > ![image](https://user-images.githubusercontent.com/33021114/162616700-ea35cdfb-1b1b-48d2-b61a-1cbabd4a2e1b.png)
> 
> Also, this works on MAUI as shown on the UWP tab AFAIK. Change it to activation type to background and you'll see that it doesn't open a new app, it just does nothing.

I know that. That is why we use Foreground activation. it is better than nothing

**Comment by VladislavAntonyuk** [comment]
> > ![image](https://user-images.githubusercontent.com/33021114/162616700-ea35cdfb-1b1b-48d2-b61a-1cbabd4a2e1b.png)
> 
> Also, this works on MAUI as shown on the UWP tab AFAIK. Change the activation type to background and you'll see that it doesn't open a new app, it just does nothing.

I know that. That is why we use Foreground activation. it is better than nothing

**Comment by emorell96** [comment]
> 

But using the 

> > > ![image](https://user-images.githubusercontent.com/33021114/162616700-ea35cdfb-1b1b-48d2-b61a-1cbabd4a2e1b.png)
> > 
> > 
> > Also, this works on MAUI as shown on the UWP tab AFAIK. Change the activation type to background and you'll see that it doesn't open a new app, it just does nothing.
> 
> I know that. That is why we use Foreground activation. it is better than nothing

Sure, but that's why I don't understand wanting not to use `ToastNotificationManagerCompat` which fixes the problem. And it's only a dependency for Windows on `CommunityToolkit.WinUI.Notifications` which is already used anyways, and written by Microsoft too, it's not like using a Google dependency. 

But then if you really didn't want to use that dependency, maybe checking what `ToastNotificationManagerCompat` and bring that into this code base, but that would be rewriting the wheel needlessly.

Another option would be if it's possible to get the background processes working.

I experimented a little this path using:

```csharp
protected static async Task RegisterBackgroundTask()
        {
            const string taskName = "ToastBackgroundTask";

            // If background task is already registered, do nothing
            if (BackgroundTaskRegistration.AllTasks.Any(i => i.Value.Name.Equals(taskName)))
                return;

            // Otherwise request access
            BackgroundAccessStatus status = await BackgroundExecutionManager.RequestAccessAsync();

            // Create the background task
            BackgroundTaskBuilder builder = new BackgroundTaskBuilder()
            {
                Name = taskName
            };

            // Assign the toast action trigger
            builder.SetTrigger(new ToastNotificationActionTrigger());

            // And register the task
            BackgroundTaskRegistration registration = builder.Register();
        }
```
but I didn't try much further since I found that `ToastNotificationManagerCompat` just fixes it all and it's simpler to use.

If that registration of a background task is possible, then it would be a matter of listening to the `OnBackgroundActivated` event. And maybe this could work:

```csharp
.ConfigureLifecycleEvents(configure =>
            {
				configure.AddWindows(c =>
				{
					c.OnLaunched((window, args) =>
					{
//option1
						ToastNotificationManagerCompat.OnActivated += WindowsNotificationService.OnActivated;
					});
					c.AddEvent<OnBackgroundActivated>("OnBackgroundActivated", (w, a) =>
					{
//option2
					Console.WriteLine("Background");
					});
                });

public delegate void OnBackgroundActivated(Microsoft.UI.Xaml.Window window, IBackgroundActivatedEventArgs backgroundActivatedEventArgs);
```
I haven't tested this but I thought something like that *could* work? 

In any case this should be documented. Because right now the [docs](https://docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/alerts/snackbar) have 0 mention of this issue.

**Comment by VladislavAntonyuk** [comment]
ToastNotificationManagerCompat is a temporary solution to migrate from UWP to WinUI. It can be used in MauiCompat package, but not MAUI package (It can, but I think it is not correct). When WinUI support `ToastNotificationManager.OnActivated`, we will add it.

**Comment by emorell96** [comment]
Wouldn't make more sense to use it until WinUI supports `ToastNotificationManager.OnActivated`? Instead of shipping a buggy experience by relabeling it a "side effect"?

**Comment by VladislavAntonyuk** [comment]
1. ToastNotificationManagerCompat is not supported on Windows 17763
2.  You can use ToastNotificationManagerCompat in your application. There is no need to update CommunityToolkit code

**Comment by VladislavAntonyuk** [comment]
@emorell96 the docs PR is merged.
I am closing the issue.

**Comment by brminnick** [comment]
Just a thought for a future feature - maybe we could add an extension to `CommunityToolit.Maui` that adds the [single-instance code for Windows](https://docs.microsoft.com/dotnet/communitytoolkit/maui/alerts/snackbar#winui-specifics) easily into the Toolkit?


```cs
protected override void OnLaunched(LaunchActivatedEventArgs args)
{
    CommunityToolkit.Maui.Windows.EnableSingleInstance();
    base.OnLaunched(args);
}
```

**Comment by VladislavAntonyuk** [comment]
I would rather wait for the ToastNotificationManagerCompat features to migrate to ToastNotificationManager.
I agree with @emorell96 that SingleInstance may not satisfy all customers.

**Comment by DamianSuess** [comment]
This issue is still happening with MAUI on .NET 8 on Windows 10. Shall I recreate this issue or will it be reopened?

```cs
  var toast = Toast.Make(msg, ToastDuration.Short);
  await toast.Show();

  // Also occurs with
  await toast.Show(new CancellationTokenSource(TimeSpan.FromSeconds(3)).Token);
```

**Comment by VladislavAntonyuk** [comment]
Another alternative, you check the execution type of the application:
```csharp
var activatedArgs = Microsoft.Windows.AppLifecycle.AppInstance.GetCurrent().GetActivatedEventArgs();
var activationKind = activatedArgs.Kind;
if (activationKind == ExtendedActivationKind.ToastNotification)
{
	/// do something
}
```

But if you want to get full experience, follow this guide: https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/toast-notifications?tabs=appsdk

**Comment by Strypper** [comment]
> It is up to you. It is a side effect of the Windows Toast Notification. As a workaround, if you do not need a new window, you can close it as the example app does

Listen up, chum. This ain't flyin' coach, it's first class. We don't deal in "shipping bugs" or sugarcoat glitches with "side effects." This is a well-oiled machine, and hiccups are dealt with swiftly and silently. Fix that mess, or find another hangar.

**Comment by jfversluis** [comment]
@Strypper I do not find your comment respectful, helpful nor constructive. This same thing has been pointed out to you on our Discord server and is unfortunately not the first time. Please review the [code of conduct](https://dotnetfoundation.org/code-of-conduct). I appreciate the work you do on top of .NET MAUI and that you're passionate about it, but that is no excuse to show this kind of behavior. Not here, not anywhere.
