### ISSUE TITLE
[Proposal] Email Validation Behavior

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#38]
# EmailValidationBehavior

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Sample
* [x] Documentation

## Summary
[summary]: #summary

The `EmailValidationBehavior` is a behavior that allows users to determine whether or not text input is a valid e-mail address. For example, an `Entry` control can be styled differently depending on whether a valid or an invalid e-mail address is provided. The validation is achieved through a regular expression that is used to verify whether or not the text input is a valid e-mail address. It can be overridden to customize the validation through the properties it inherits from `ValidationBehavior`.

## Motivation
[motivation]: #motivation

Many forms applications require email input, e.g. Sign up, Sign in. The `EmailValidationBehavior` ensures that users enter a valid email address before submitting the information.

## Detailed Design
[design]: #detailed-design

### EmailValidationBehavior.shared.cs

```cs
public class EmailValidationBehavior : TextValidationBehavior
{
    readonly Regex normalizerRegex = new Regex(@"(@)(.+)$");
   
    protected override string DefaultRegexPattern
			=> @"^(?("")("".+?(?<!\\)""@)|(([0-9a-z]((\.(?!\.))|[-!#\$%&'\*\+/=\?\^`\{\}\|~\w])*)(?<=[0-9a-z])@))" +
				@"(?(\[)(\[(\d{1,3}\.){3}\d{1,3}\])|(([0-9a-z][-0-9a-z]*[0-9a-z]*\.)+[a-z0-9][\-a-z0-9]{0,22}[a-z0-9]))$";
    protected override RegexOptions DefaultRegexOptions => RegexOptions.IgnoreCase;

    protected override object? Decorate(object? value)
    {
	    var stringValue = base.Decorate(value)?.ToString();
	    if (string.IsNullOrWhiteSpace(stringValue))
		    return stringValue;
    
	    try
	    {
		    static string DomainMapper(Match match)
		    {
			    // Use IdnMapping class to convert Unicode domain names.
			    var idn = new IdnMapping();
    
			    // Pull out and process domain name (throws ArgumentException on invalid)
			    var domainName = idn.GetAscii(match.Groups[2].Value);
			    return match.Groups[1].Value + domainName;
		    }
    
		    // Normalize the domain
		    return normalizerRegex.Replace(stringValue, DomainMapper);
	    }
	    catch (ArgumentException)
	    {
		    return stringValue;
	    }
    }
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<Entry Placeholder="Email">
    <Entry.Behaviors>
        <toolkit:EmailValidationBehavior
            DecorationFlags="Trim"
        />
    </Entry.Behaviors>
</Entry>
```

### C# Usage

```cs
var emailEntry = new Entry();
emailEntry(new EmailValidationBehavior
{
    DecorationFlags = TextDecorationFlags.Trim,
});
```

**Comment by VladislavAntonyuk** [comment]
@brminnick I would like to implement this feature. please assign it on me

**Comment by brminnick** [comment]
Thanks @VladislavAntonyuk! Assigned to you 👍
