### ISSUE TITLE
[Bug] Build error with SelectedItemEventArgsConverter

### ISSUE THREAD

**Issue by intellimedhu** [CommunityToolkit/Maui#382]
### Description

I have a .NET MAUI Class Library with a MAUI ContentPage.
I'm trying to use the EventToCommandBehavior behaviour, but I'm getting a build error.

### Stack Trace

Error	XFC0000	Cannot resolve type "http://schemas.microsoft.com/dotnet/2022/maui/toolkit:mct:SelectedItemEventArgsConverter".

### Basic Information

- Version with issue: RC1
- Last known good version: -
- IDE: VS 2022 Preview 4.0
- Nuget Packages: CommunityToolkit.Maui

### Reproduction imagery

![image](https://user-images.githubusercontent.com/65296389/165070500-4377dcab-0667-4343-a53a-f026e7305a6b.png)

**Comment by bijington** [comment]
Thanks for the report. Just to confirm have you confirmed your app builder to call `UseMauiCommunityToolkit` as per this:

https://github.com/CommunityToolkit/Maui#getting-started

**Comment by intellimedhu** [comment]
In the MAUI App project (where this MAUI Class Library is referenced), I added the UseMauiCommunityToolkit line.

**Comment by VladislavAntonyuk** [comment]
@intellimedhu Could you please attach a small repro?

**Comment by intellimedhu** [comment]
I managed build it. The problem was, that I added UseMauiCommunityToolkit line in the MAUI App project, not in the MAUI Class Library, where the Community Toolkit is used.

**Comment by VladislavAntonyuk** [comment]
@intellimedhu could you please close the issue if it is fixed?

**Comment by Elangovan4ever** [comment]
@intellimedhu I'm also having a similar issue when trying to use the InvertedBoolConverter from toolkit inside the maui class library. Can you please let me know from which class you called the UseMauiCommunityToolkit() method in the class library. If you can share that particular line how you called the UseMauiCommunityToolkit method it would be great
