### ISSUE TITLE
[Bug] Popup height doesn't resize based on content

### ISSUE THREAD

**Issue by Giuseppetm** [CommunityToolkit/Maui#388]
### Description

It appears that the popup has a fixed height regardless of the content that is placed inside it.
The yellow part indicates the space occupied by the popup; regardless of the content it will always have that fixed height.

![image](https://user-images.githubusercontent.com/52317197/165914296-02c39c1a-91d9-4006-b0f7-4312c293ece6.png)

### Steps to Reproduce

1. Create a popup;
2. Place something inside, in this case a VerticalStackLayout with some stacklayouts inside;
3. Run app on android;
4. Open popup.

### Expected Behavior
The expected behavior would be to occupy only the orange space that is a basic verticalStackLayout (and the other space for the stackLayout for buttons).

![image](https://user-images.githubusercontent.com/52317197/165914877-6390b495-c79a-43ce-84a8-48beedaf9afa.png)

### Actual Behavior
The current behavior on the other hand does not dynamically resize the popup based on its content.

![image](https://user-images.githubusercontent.com/52317197/165914907-55a65f2c-b79c-45e2-9778-4bfdfe4ba714.png)

### Basic Information

- Version with issue: 1.0.0-rc2 (and 1.0.0-rc1 too)
- Last known good version: none
- IDE: VS2022 Preview
- Platform Target Frameworks: 
  - Android: 11.0

### Workaround
None.

**Comment by pictos** [comment]
@Giuseppetm 
Could you attach a small repro?

**Comment by Giuseppetm** [comment]
> @Giuseppetm Could you attach a small repro?

@pictos 👍🏻 
[PopupTest.zip](https://github.com/CommunityToolkit/Maui/files/8591672/PopupTest.zip)

**Comment by pictos** [comment]
Hey @Giuseppetm, I tried on my end and I couldn't reproduce the same behavior. To me it looks quite good, what do you think?

Using `HorizontalStackLayout`
![image](https://user-images.githubusercontent.com/20712372/167514539-96407848-ac0c-49b7-945e-b1142ba1dcc1.png)

using `StackLayout + Orientation = Horizontal`
![image](https://user-images.githubusercontent.com/20712372/167514603-a8018e8d-733a-45a3-8da2-311345a20a5a.png)


Can you try using the latest .NET MAUI release?

**Comment by DENLN** [comment]
> 

![image](https://user-images.githubusercontent.com/4215311/167599244-c4baa49d-3f37-4b28-924f-13c2db4fd9b1.png)

me the same behavior

**Comment by Giuseppetm** [comment]
> Hey @Giuseppetm, I tried on my end and I couldn't reproduce the same behavior. To me it looks quite good, what do you think?

It's the same behaviour, as you can see the height of the popup doesn't resize based on its content.

> Can you try using the latest .NET MAUI release?

I will let you know if it fixes it.

**Comment by pictos** [comment]
Oh, my bad, I just saw the buttons miss-aligned and I thought the main issue was a wrong measure on that layout.

**Comment by Giuseppetm** [comment]
MAUI RC3 didn't solve this.

**Comment by pictos** [comment]
@Giuseppetm, this is awkward because this isn't a bug it's how I implemented it. So I changed the label to `enhancement`.

So let me explain how it works so far. As you can see in this part of the code

https://github.com/CommunityToolkit/Maui/blob/2af75d3e6eb522d3b17ffc7cd2d5fef005ca885a/src/CommunityToolkit.Maui.Core/Views/Popup/PopupExtensions.android.cs#L109-L122

If we can't find a size granter than zero we calculate using a constant value based on the screen size.
For some scenarios, those sizes can't fit very well, so I'm opening a PR to add more steps to calculate the correct size.

Right now these are the results of the new code:
Using the `Padding = 35`
![image](https://user-images.githubusercontent.com/20712372/168446947-4f63f8dd-cfb8-4ec2-980a-753f3628cd1c.png)
Using the `Padding = 0`
![image](https://user-images.githubusercontent.com/20712372/168446973-5d28cfd7-429b-453c-b660-56249d44aceb.png)

**Comment by Giuseppetm** [comment]
@pictos Hello, I have encountered some quite significant problems that I would like to show you.

1) Indicating a text that is too long does not wrap automatically and overrides the width of the popup, completely breaking the visualization (this did not happen in 1.0.0-rc3);

![image](https://user-images.githubusercontent.com/52317197/170208971-fb197453-2906-4796-a743-a0774d94d76e.png)

2) Switching the content of the popup through a property which then replaces the current content, the height of the popup does not change dynamically, and we have the original problem.

|  |  |
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/52317197/170209193-fcb37d92-0aa0-459e-8bf2-7c05e1fd327e.png) | ![image](https://user-images.githubusercontent.com/52317197/170209453-d729f023-4957-46fd-8785-d9161cc188a7.png)|

This problem also applies to the horizontal width of the popup content: in this case the text that I was speaking about in 1st point is not visible anymore, but the width remains broken.

|  |  |
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/52317197/170209986-09fa421c-3115-4243-a192-9be43c3383eb.png)| ![image](https://user-images.githubusercontent.com/52317197/170209708-8f405898-b03e-4882-bd53-28dfd39a0051.png)|

Here's the sample project:
[PopupTest.zip](https://github.com/CommunityToolkit/Maui/files/8768991/PopupTest.zip)


Let me know what you think and if you have any suggestions.

**Comment by Giuseppetm** [comment]
@pictos Hello, any update?

**Comment by pictos** [comment]
@Giuseppetm the fix for this ticket isn't in the stable package. If you are running the code from our main branch, then open a new issue please
