### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by dseph** [CommunityToolkit/Maui#395]
### Description

I downloaded VS 2022 Pre and updated and downloaded the Community Toolkit and tried to build and got an error due to the code generator not being able to write to a folder.  Other files were written to the folder without issue.

Error code: CS0016

This is the error message:

Description: Could not write to output file 'C:\Maui\Maui-main\Maui-main\src\CommunityToolkit.Maui.UnitTests\obj\GF\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\PublicTextStyleViewTextColorTo_0e56d97a-ac1e-4e91-9165-1766226cc8bb.g.shared.cs' -- 'Could not find a part of the path 'C:\Maui\Maui-main\Maui-main\src\CommunityToolkit.Maui.UnitTests\obj\GF\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\PublicTextStyleViewTextColorTo_0e56d97a-ac1e-4e91-9165-1766226cc8bb.g.shared.cs'.'

--

Error code:  CS0016
Description:  Could not write to output file 'C:\Maui\Maui-main\Maui-main\src\CommunityToolkit.Maui.UnitTests\obj\GF\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\InternalTextStyleViewTextColorTo_4ade1f27-ea2b-44dd-8144-50972ec3992c.g.shared.cs' -- 'Could not find a part of the path 'C:\Maui\Maui-main\Maui-main\src\CommunityToolkit.Maui.UnitTests\obj\GF\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\InternalTextStyleViewTextColorTo_4ade1f27-ea2b-44dd-8144-50972ec3992c.g.shared.cs'.'

--

Error code:  CS0104

Description:   'Resource' is an ambiguous reference between 'Microsoft.Maui.Controls.Resource' and 'Microsoft.Maui.Graphics.Resource'
Project:  CommunityToolkit.Maui (net6.0-android)
File:  C:\Maui\Maui-main\Maui-main\src\CommunityToolkit.Maui\Alerts\Snackbar\Snackbar.android.cs
Line:  89

The same error also happens on line 104.

 
### Link to Reproduction Sample

https://github.com/CommunityToolkit/Maui

### Steps to Reproduce

1. Download VS 2022 Pre and update.
2. Download the MAUI Community toolkit
3. Clean build
4. Run – you will see the error

### Expected Behavior
No error

### Actual Behavior

See above errors
### Basic Information

- Version with issue: Current

- Last known good version: N/A
- IDE:
- Platform Target Frameworks: core
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: N/A
- Affected Devices:

### Workaround
None

**Comment by brminnick** [comment]
Hi @dseph!

This is a bug in Visual Studio on Windows. 

See this duplicate Issue for the solution:  https://github.com/CommunityToolkit/Maui/issues/340
