### ISSUE TITLE
[Bug] Error in installing the package via NuGet

### ISSUE THREAD

**Issue by mcanyucel** [CommunityToolkit/Maui#403]
### Description

When trying to install the toolkit using NuGet, I get the NU1605 exception and the package installation fails. 

### Stack Trace

```
Error	NU1605	Detected package downgrade: Microsoft.Maui.Dependencies from 6.0.300-rc.3.5667 to 6.0.300-rc.2.5513. Reference the package directly from the project to select a different version. 
 istanbul-bridge-conference-maui -> CommunityToolkit.Maui 1.0.0-rc3 -> Microsoft.Maui.Dependencies (>= 6.0.300-rc.3.5667) 
 istanbul-bridge-conference-maui -> Microsoft.Maui.Dependencies (>= 6.0.300-rc.2.5513)	<project>.csproj	

Error	NU1605	Detected package downgrade: Microsoft.Maui.Extensions from 6.0.300-rc.3.5667 to 6.0.300-rc.2.5513. Reference the package directly from the project to select a different version. 
 istanbul-bridge-conference-maui -> CommunityToolkit.Maui 1.0.0-rc3 -> Microsoft.Maui.Extensions (>= 6.0.300-rc.3.5667) 
 istanbul-bridge-conference-maui -> Microsoft.Maui.Extensions (>= 6.0.300-rc.2.5513)	<project>.csproj	


```

### Steps to Reproduce

1. Tools>Nuget Package Manager>Manage NugetPackages for Solution
2. Try to intall Community.Toolkit.Maui

### Expected Behavior

Community toolkit to be installed.

### Actual Behavior

Community toolkit failed to install.

### Basic Information

- Version with issue: 1.0.0-rc3
- Last known good version: -
- IDE: VS Community Preview Version 17.2.0 Preview 6.0
- Platform Target Frameworks: 
  - iOS:  15.4
- Nuget Packages:
 - Microsoft.Graphics.Win2D 1.0.1
 - Microsoft.Maui.Dependencies 6.0.300-rc.2.5513
 - Microsoft.Maui.Extensions 6.0.300-rc.2.5513
 - Microsoft.Toolkit.Mvvm 7.1.2
 - Microsopft.Windows.SDK.BuildTools 10.0.22000.194
 - Microsoft.WindowsAppSDK 1.0.3
 - System.Runtime.InteropServices.NFloat.Internal 6.0.1

### Workaround
None

**Comment by bijington** [comment]
Looking at the NuGet Packages under the Basic information section you have provided you are using rc2 for .NET MAUI. You need to upgrade to RC3 in order to use the latest toolkit version.

**Comment by brminnick** [comment]
You also note that you have the following NuGet packages installed:
- Microsoft.Maui.Dependencies 6.0.300-rc.2.5513
- Microsoft.Maui.Extensions 6.0.300-rc.2.5513

This is not the correct way to use .NET MAUI. 

I highly recommend removing these NuGet packages from your app; this is the root cause of your error.

**Comment by bijington** [comment]
And thank you for providing the information requested it really helps us 🙂

**Comment by mcanyucel** [comment]
Wow, thanks for that fast and extensive responses :)


```
You also note that you have the following NuGet packages installed:

    Microsoft.Maui.Dependencies 6.0.300-rc.2.5513
    Microsoft.Maui.Extensions 6.0.300-rc.2.5513

This is not the correct way to use .NET MAUI; it is meant to be installed + consumed as a .NET Workload, not as a NuGet Package. You should install .NET MAUI via the CLI: dotnet workload install maui.

I highly recommend removing these NuGet packages from your app; this is the root cause of your error.
```

That's interesting. To be fair I have worked with WPF in .NET 4.7 for some time but I am quite new to .NET 6 and especially MAUI. And honestly MAUI's documentation is not on par with WPF or any other framework. Obviously this is very normal for a framework which is still in preview, but still it causes a lot of time to find out things. I initiated this project in VS Preview for Mac using workloads, but then cloned it and opened it in a Windows VS Preview, where cli and workloads were not installed. I am guessing this flow is the reason these packages are installed. Very surprising (well for me at least :) ) This may be the reason the MAUI nuget packages are left with rc2 and not updated. 
So do you think I can install MAUI over workloads and remove the NuGet packages? I really prefer to do the things in their correct ways.

Btw thanks for this package :)

**Comment by mcanyucel** [comment]
> You also note that you have the following NuGet packages installed:
> 
>     * Microsoft.Maui.Dependencies 6.0.300-rc.2.5513
> 
>     * Microsoft.Maui.Extensions 6.0.300-rc.2.5513
> 
> 
> This is not the correct way to use .NET MAUI; it is meant to be installed + consumed as a .NET Workload, not as a NuGet Package. You should install .NET MAUI via the CLI: `dotnet workload install maui`.
> 
> I highly recommend removing these NuGet packages from your app; this is the root cause of your error.

I have updated the MAUI using cli but I still cannot remove these packages from NuGet. Are they supposed to be stay in there forever? Also now I cannot build the project with a bunch of errors in the format 👍🏻 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	IDE1100	Error reading content of source file 'D:\programming\istanbul-bridge-conference-maui\obj\Debug\net6.0-ios\iossimulator-x64\.NETCoreApp,Version=v6.0.AssemblyAttributes.cs' -- 'Could not find file 'D:\programming\istanbul-bridge-conference-maui\obj\Debug\net6.0-ios\iossimulator-x64\.NETCoreApp,Version=v6.0.AssemblyAttributes.cs'.'.	istanbul-bridge-conference-maui (net6.0-ios)	D:\programming\istanbul-bridge-conference-maui\obj\Debug\net6.0-ios\iossimulator-x64\.NETCoreApp,Version=v6.0.AssemblyAttributes.cs	1	Active

```

Any ideas how to solve this problem :/ I updated the MAUI workload in the connected Mac as well.

**Comment by mcanyucel** [comment]
So for testing I initialized a new MAUI app from within VS with the updated workload. Now I was able to install the community toolkit. However, the packages Microsoft.Maui.Dependencies (6.0.400-rc.3.5667) and Microsoft.Maui.Extensions (6.0.400-rc.3.5667) are again listed in the NuGet Installed Packages list. The uninstall button is also not enabled so they cannot be removed. 
Is this the expected behaviour? Based on the previous answers on this thread, it does not feel like it.

**Comment by bijington** [comment]
@mcanyucel I noticed you closed this issue down but for reference a .NET MAUI application will show those packages (`Microsoft.Maui.Dependencies` and `Microsoft.Maui.Extensions`) but are not included in the csproj file. These dependencies are managed instead through this line in your csproj file:

```xml
<UseMaui>true</UseMaui>
```
