### ISSUE TITLE
[Bug] Unable to use MultiConverter with non matching targetTypes

### ISSUE THREAD

**Issue by bijington** [CommunityToolkit/Maui#410]
### Description

It appears impossible to bind a `MultiConverter` containing at least one converter that does not match the target type of the property it is bound to. It may be easier to explain through an example using the sample page:

```csharp
<pages:BasePage 
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:mct="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
    xmlns:pages="clr-namespace:CommunityToolkit.Maui.Sample.Pages"
    x:Class="CommunityToolkit.Maui.Sample.Pages.Converters.MultiConverterPage"
    xmlns:vm="clr-namespace:CommunityToolkit.Maui.Sample.ViewModels.Converters"
    x:TypeArguments="vm:MultiConverterViewModel"
    x:DataType="vm:MultiConverterViewModel">

    <pages:BasePage.Resources>
        <ResourceDictionary>
            <mct:MultiConverter x:Key="MyMultiConverter">
                <mct:TextCaseConverter />
                <mct:IsNotEqualConverter />
            </mct:MultiConverter>
            <x:Array x:Key="MultiParams"
                     Type="{x:Type mct:MultiConverterParameter}">
                <mct:MultiConverterParameter
                    ConverterType="{x:Type mct:TextCaseConverter}"
                    Value="{x:Static mct:TextCaseType.Upper}" />
                <mct:MultiConverterParameter
                    ConverterType="{x:Type mct:IsNotEqualConverter}"
                    Value="MAUI" />
            </x:Array>
        </ResourceDictionary>
    </pages:BasePage.Resources>
    <pages:BasePage.Content>
        <VerticalStackLayout Padding="20"
                             Spacing="20">
            <Label Text="This sample demonstrates how to use the MultiConverter with the IsNotEqualConverter and the TextCaseConverter. It converts the entered text to Upper Case and checks that it is Not Equal to the string 'MAUI'."/>
            <Entry Text="{Binding EnteredName}"/>
            <Label IsVisible="{Binding EnteredName, Converter={StaticResource MyMultiConverter}, ConverterParameter={StaticResource MultiParams}, Mode=OneWay}"
                   HorizontalOptions="CenterAndExpand"/>
        </VerticalStackLayout>
    </pages:BasePage.Content>
</pages:BasePage>
```

The second Label here has its `IsVisible` property bound to the result of the converters. This will throw an exception due to the check on this line: https://github.com/CommunityToolkit/Maui/blob/2af75d3e6eb522d3b17ffc7cd2d5fef005ca885a/src/CommunityToolkit.Maui/Extensions/ValueConverterExtension.shared.cs#L62

This is down to the fact that the first converter expects a `targetType` of `string`.

I don't know what the right answer is for a fix. I like the validation of the `targetType`s when dealing with single converters but when we are chaining we only care that the last converter has a valid `targetType`.

### Link to Reproduction Sample

This unit test reproduces the issue:

```sharp
[Fact]
public void ChainingConvertersOfDifferentTargetTypes()
{
    var multiConverter = new MultiConverter();
    
    multiConverter.Add(new TextCaseConverter());
    multiConverter.Add(new IsEqualConverter());

    var multiParams = new List<MultiConverterParameter>();
    
    multiParams.Add(new MultiConverterParameter { ConverterType = typeof(TextCaseConverter), Value = TextCaseType.Upper });
    multiParams.Add(new MultiConverterParameter { ConverterType = typeof(IsEqualConverter), Value = "MAUI" });
    
    var result = multiConverter.Convert("JOHN", typeof(bool), multiParams, CultureInfo.CurrentCulture);
    
    Assert.Equal(false, result);
}
```

### Steps to Reproduce

Use the example of unit test from above.

### Expected Behavior

No exception should be thrown

### Actual Behavior

An exception is thrown

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

Don't use it

**Comment by brminnick** [comment]
`MultiConverter` is passing in its `Type targetType` to each converter. The problem is that the final `targetType` for `MultiConverter` doesn't always match the `targetType` for the individual converter.

The solution to the bug would be to determine the `targetType` for each individual converter and pass that in for its `targetType` parameter.

### Workaround
One workaround would be to pass in `typeof(string)` for the `targetType`:

```cs
public object? Convert(object? value, Type targetType, object? parameter, System.Globalization.CultureInfo? culture)
=> parameter is IList<MultiConverterParameter> parameters
? this.Aggregate(value, (current, converter) => converter.Convert(current, typeof(string),
			parameters.FirstOrDefault(x => x.ConverterType == converter.GetType())?.Value, culture))
: this.Aggregate(value, (current, converter) => converter.Convert(current, typeof(string), parameter, culture));
```

This workaround "fixes" the bug because our logic to validate the `tagetType`, `IsValidTargetType<T>`, will always return `true` if we are converting to a `string`:
https://github.com/CommunityToolkit/Maui/blob/2af75d3e6eb522d3b17ffc7cd2d5fef005ca885a/src/CommunityToolkit.Maui/Extensions/ValueConverterExtension.shared.cs#L34

**Comment by bijington** [comment]
> I don't recommend this workaround, however, because it is a bit of a hack that could induce unforeseen bugs in the future.

You beat me to that comment 😄 

It is true that it would 'work' as the `ToString` is a bit of a catch all scenario. I suspect we could determine what `targetType` is via Reflection but that doesn't feel like the solution

**Comment by brminnick** [comment]
Hey Shaun! I took at stab at fixing this without the [`string` targetType workaround](https://github.com/CommunityToolkit/Maui/issues/410#issuecomment-1130387621).

I've opened #412 as a draft PR to demonstrate one way that I came up with to solve it. 

Let me know what you think!
