### ISSUE TITLE
[Bug] Samples will not build on windows

### ISSUE THREAD

**Issue by TonyK-FmGroup** [CommunityToolkit/Maui#418]
### Description

Trying to build the samples on windowd 10 returns the following errors:

Error	CS0016	Could not write to output file 'C:\repos\Maui\samples\CommunityToolkit.Maui.Sample\obj\GeneratedFiles\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\CommunityToolkit.Maui.Sample.ViewModels.Converters.MathExpressionConverterViewModel.cs' -- 'Could not find a part of the path 'C:\repos\Maui\samples\CommunityToolkit.Maui.Sample\obj\GeneratedFiles\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\CommunityToolkit.Maui.Sample.ViewModels.Converters.MathExpressionConverterViewModel.cs'.'	CommunityToolkit.Maui.Sample (net6.0-ios)	C:\repos\Maui\samples\CommunityToolkit.Maui.Sample\CSC

Error	CS0016	Could not write to output file 'C:\repos\Maui\samples\CommunityToolkit.Maui.Sample\obj\GeneratedFiles\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\CommunityToolkit.Maui.Sample.ViewModels.Converters.MultiMathExpressionConverterViewModel.cs' -- 'Could not find a part of the path 'C:\repos\Maui\samples\CommunityToolkit.Maui.Sample\obj\GeneratedFiles\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\CommunityToolkit.Maui.Sample.ViewModels.Converters.MultiMathExpressionConverterViewModel.cs'.'	CommunityToolkit.Maui.Sample (net6.0-ios)	C:\repos\Maui\samples\CommunityToolkit.Maui.Sample\CSC	1	Active

Error	CS0016	Could not write to output file 'C:\repos\Maui\samples\CommunityToolkit.Maui.Sample\obj\GeneratedFiles\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\CommunityToolkit.Maui.Sample.ViewModels.Converters.StateToBooleanConverterViewModel.cs' -- 'Could not find a part of the path 'C:\repos\Maui\samples\CommunityToolkit.Maui.Sample\obj\GeneratedFiles\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\CommunityToolkit.Maui.Sample.ViewModels.Converters.StateToBooleanConverterViewModel.cs'.'	C:\repos\Maui\samples\CommunityToolkit.Maui.Sample\CSC	

### Stack Trace

None available

### Link to Reproduction Sample

Pulled master at  f27b02f "Fixed measurement on Android (#404)

### Steps to Reproduce

1.  Pull mast at the above mentioned commit
2.  Open CommunityToolkit.Maui.Sample.sln in VS 2022 17.3.0 preview
3.  Build the solution for windows machine

Also the same outcome attempting to compile for Android emulator.

### Expected Behavior
Solution should build without errors.

### Actual Behavior
Above errors observed.

### Basic Information

- Version with issue: 
- Last known good version: I've not previously pulled or tried this.
- IDE: VS 2022 17.3.0 preview
- Platform Target Frameworks: 
  - iOS:  N/A
  - Android: 31
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: As per the solution
- Affected Devices:

### Workaround
None

### Reproduction imagery
N/A

**Comment by IeuanWalker** [comment]
https://github.com/CommunityToolkit/Maui/discussions/399
