### ISSUE TITLE
[Proposal] Text Validation Behavior

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#42]
# TextValidationBehavior

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Sample
* [x] Documentation

## Summary
[summary]: #summary

The `TextValidationBehavior` is a `Behavior` that allows the user to validate a given text depending on specified parameters. By adding this behavior to an `Entry` control it can be styled differently depending on whether a valid or an invalid text value is provided. It offers various built-in checks such as checking for a certain length or whether or not the input value matches a specific regular expression. Additional properties handling validation are inherited from `ValidationBehavior`.

## Detailed Design
[design]: #detailed-design

### TextValidationBehavior.shared.cs

```cs
public class TextValidationBehavior : ValidationBehavior
{
    public static readonly BindableProperty MinimumLengthProperty;
    public static readonly BindableProperty MaximumLengthProperty;
    public static readonly BindableProperty DecorationFlagsProperty;
    public static readonly BindableProperty RegexPatternProperty;
    public static readonly BindableProperty RegexOptionsProperty;

    public int MinimumLength { get; set; }
    public int MaximumLength { get; set; }
    public TextDecorationFlags DecorationFlags { get; set; }
    public string? RegexPattern { get; set; }
    public RegexOptions RegexOptions { get; set; }
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<Entry>
    <Entry.Behaviors>
        <toolkit:TextValidationBehavior
            MinimumLength="1"
            MaximumLength="10"
        />
    </Entry.Behaviors>
</Entry>
```

### C# Usage

```cs
var entry = new Entry();
entry.Behaviors.Add(new TextValidationBehavior
{
    MinimumLength = 1
    MaximumLength = 10
});
```

**Comment by VladislavAntonyuk** [comment]
@brminnick I would like to implement this feature. please assign it on me
