### ISSUE TITLE
[Bug] iOS Popup size and position

### ISSUE THREAD

**Issue by ViktorArbuzov** [CommunityToolkit/Maui#428]
Hello, when I'm creating default popup the position and sizing on iOS doesn't correspond to the Android and code. 
### Description

When creating default popup by the guidance: https://docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/popup
Facing an issue - the size of the popup is not depended on the content, and the position is not centered.

I think this is can be related to the MAUI issues on iOS, but maybe this is something different: https://github.com/dotnet/maui/issues/7507

### Steps to Reproduce
1. Create popup

`<?xml version="1.0" encoding="utf-8" ?>
<toolkit:Popup
    x:Class="MauiApp1.SimplePopup"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit">
    <StackLayout BackgroundColor="Yellow">
        <Label Text="This is a very important message!" />
    </StackLayout>
</toolkit:Popup>`

2. Open popup: 

`public void DisplayPopup()
    {
        var popup = new SimplePopup();

        Application.Current?.MainPage.ShowPopup(popup);
    }`

3. See the result.  (screenshot is attached below)

ps: 4. after closing the popup by click outside the content - the initial page becomes empty. 
 
### Expected Behavior
Popup size corresponding to the content size,
Blur effect appears behind popup,
Popup centered,
After closing - previous page has no changes.

### Actual Behavior
Popup size is not depends on the content
Blur effect behind popup is absent,
Popup positioned at left top corner with some margin, this is not symmetrical,
After closing the popup - previous page is empty.

### Basic Information

- Version with issue: 1.0.0
- IDE: Microsoft Visual Studio Professional 2022 (64-bit) - Preview Version 17.3.0 Preview 1.1
- Platform Target Frameworks:
  - iOS:  14.5, 15.5
- Nuget Packages: CommunityToolkit.Maui 1.0.0, Microsoft.Maui.Dependencies 6.0.312

### Reproduction imagery
![image](https://user-images.githubusercontent.com/54932228/170671469-94436964-bb54-4f0d-9b3a-be8f5ab42462.png)

Thanks!

**Comment by naweed** [comment]
I am facing the same issue with v.1.0.0

**Comment by fireking220** [comment]
I too has this same issue with Microsoft Visual Studio Professional 2022 (64-bit) - Preview Version 17.3.0 Preview 1.1 with iOS 14.5, 15.5
