### ISSUE TITLE
Getting Error In installing the CommunityToolKit.Maui package[Bug] 

### ISSUE THREAD

**Issue by sanjanapatel2409Unthinkable** [CommunityToolkit/Maui#435]
Hello, and thanks for your interest in contributing to the .NET MAUI Toolkit! 

Please describe the issue below, including detailed steps for reproduction. If we are unable to reproduce the bug we will be unable to fix the issue and may close this Issue.

I just created a new project .net Maui and trying to install the CommunityTollKit.Maui Nuget package But I am unable to install the package.

_Restoring packages for C:\Users\unthinkable-lap-0045\source\repos\CommunityToolKit\CommunityToolKit\CommunityToolKit.csproj...
NU1605: Detected package downgrade: Microsoft.Maui.Dependencies from 6.0.312 to 6.0.300-rc.2.5513. Reference the package directly from the project to select a different version. 
 CommunityToolKit -> CommunityToolkit.Maui 1.0.0 -> Microsoft.Maui.Dependencies (>= 6.0.312) 
 CommunityToolKit -> Microsoft.Maui.Dependencies (>= 6.0.300-rc.2.5513)
NU1605: Detected package downgrade: Microsoft.Maui.Extensions from 6.0.312 to 6.0.300-rc.2.5513. Reference the package directly from the project to select a different version. 
 CommunityToolKit -> CommunityToolkit.Maui 1.0.0 -> Microsoft.Maui.Extensions (>= 6.0.312) 
 CommunityToolKit -> Microsoft.Maui.Extensions (>= 6.0.300-rc.2.5513)
Package restore failed. Rolling back package changes for 'CommunityToolKit'.
Time Elapsed: 00:00:00.9330572
========== Finished ==========_

**Comment by brminnick** [comment]
Hi @sanjanapatel2409Unthinkable! Please add a reproduction sample app so that we can reproduce the error.

**Comment by bijington** [comment]
@sanjanapatel2409Unthinkable Your error message indicates you have an older version of the .NET MAUI workload installed.

Can you try running the following from a command prompt/terminal session

`dotnet workload install maui`

**Comment by VladislavAntonyuk** [comment]
Or even better use Visual Studio Installer and update to the latest preview version. It should automatically update the old .NET MAUI workloads

**Comment by VladislavAntonyuk** [comment]
`dotnet workload update` solves the issue if you are running on Mac.
Use VS Installer on Windows.
