### ISSUE TITLE
[Bug] PopupHandler is incompatible

### ISSUE THREAD

**Issue by gironymo** [CommunityToolkit/Maui#438]
### Description
Showing a popup based on XAML leads to the error

`CommunityToolkit.Maui.Core.Handlers.PopupHandler found for TestApp.ProfilePopup is incompatible`

### Steps to Reproduce

1. Create a new MAUI Application
2. Install CommunityToolkit 
3. Create a Popup-XAML
4. Change the `OnCounterClicked` in `Mainpage` to show popup using `this.ShowPopup(popup)`

XAML:

```
<?xml version="1.0" encoding="utf-8" ?>
<toolkit:Popup xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
               xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
               xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
               x:Class="TestApp.ProfilePopup">

    <VerticalStackLayout>
        <Label Text="This is a very important message!" />
    </VerticalStackLayout>

</toolkit:Popup>
```

OnCounterClicked:

```
 private void OnCounterClicked(object sender, EventArgs e)
    {

        var popup = new ProfilePopup();

        this.ShowPopup(popup);

    }
```

Creating the popup in Code works as expected:

```
    private void OnCounterClicked(object sender, EventArgs e)
    {
        var popup = new Popup
        {
            Content = new VerticalStackLayout
            {
                Children =
        {
            new Label
            {
                Text = "This is a very important message!"
            }
        }
            }
        };

        this.ShowPopup(popup);

    }
```

**Comment by pictos** [comment]
@gironymo 
Could you attach a small repro?

**Comment by ToolmakerSteve** [comment]
Close this. It isn't a bug. I explain what was done wrong in [my StackOverflow answer](https://stackoverflow.com/a/72510771/199364).

**Comment by bijington** [comment]
> The bug is in poster's code, not in Toolkit Popup. I explain what was done wrong in [my StackOverflow answer](https://stackoverflow.com/a/72510771/199364).
> 
> 
> 
> (There is no ProfilePopup.xaml.cs file, so no `InitializeComponent` call.)

Thanks @ToolmakerSteve

**Comment by gironymo** [comment]
Thank you very much! I'm missing this information in the documentation on the Microsoft page https://docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/popup which I used as template.

**Comment by bijington** [comment]
@gironymo thanks for this feedback, we have assumed some initial knowledge around XAML files with our documentation specifically around this page: https://docs.microsoft.com/en-gb/dotnet/maui/xaml/fundamentals/get-started#anatomy-of-a-xaml-file

I appreciate that even the linked page doesn't give a good insight to developers new to XAML
