### ISSUE TITLE
[Proposal] Event-To-Command Behavior

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#44]
# EventToCommandBehavior

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Documentation
* [x] Sample

## Summary
[summary]: #summary

The `EventToCommandBehavior` is a `Behavior` that allows the user to invoke an `ICommand` through an `Event`. It is designed to associate `ICommand` to events exposed by controls that were not designed to support Commands. It allows you to map any arbitrary event on a control to an `ICommand`.

## Detailed Design
[design]: #detailed-design

```cs
public class EventToCommandBehavior : BaseBehavior<VisualElement>
{
    public static readonly BindableProperty EventNameProperty;
    public static readonly BindableProperty CommandProperty;
    public static readonly BindableProperty CommandParameterProperty;
    public static readonly BindableProperty EventArgsConverterProperty;

    public string? EventName { get; set; }
    public ICommand? Command { get; set; }
    public object? CommandParameter { get; set; }
    public IValueConverter EventArgsConverter { get; set; }
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<Button.Behaviors>
    <toolkit:EventToCommandBehavior
        EventName="Clicked"
        Command="{Binding MyCustomCommand}" />
</Button.Behaviors>
```

### C# Usage

```cs
var button = new Button();
button.Behaviors.Add(new EventToCommandBehavior
{
    EventName = nameof(Button.Clicked),
    Command = new MyCustomCommand()
});
```

## Drawbacks
[drawbacks]: #drawbacks

## Alternatives
[alternatives]: #alternatives

## Unresolved Questions
[unresolved]: #unresolved-questions

**Comment by IndianaGary** [comment]
This would be my first OSS contribution but I think I could documennt this if I knew what was expected...

**Comment by brminnick** [comment]
Tha is @indianagary! We are still setting up the Docs repo. 

Once it's ready, we will certainly loop you in!

https://github.com/MicrosoftDocs/CommunityToolkitDocs

**Comment by IndianaGary** [comment]
In the meantime, do you have any guidelines on doc format that I could start reviewing?

**Comment by bijington** [comment]
Oh I have just read the last few comments. @IndianaGary would you still be keen to write the docs for this?

**Comment by IndianaGary** [comment]
Hi Shaun,

Sorry. I missed this email. I will be available starting Wednesday. Can you point me at where to start? This will be my first OSS contribution and I'm running a bit blind.

Regards
Gary

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by bijington** [comment]
@IndianaGary no problem.

The docs writing process is still extremely fresh and we are learning as we go but if you fancy writing some it could be a nice introduction to contributing for sure. I will aim to get some documentation set up before Wednesday to hopefully help guide you but of course feel free to reach out with any questions.

**Comment by IndianaGary** [comment]
Great I look forward to hearing from you. As for this particular Behavior, I've used it quite a lot so I don't think l have any trouble documenting it. Are you looking for sample code as well?

**Comment by bijington** [comment]
@IndianaGary sorry this completely slipped through and I forgot to gets those docs for you.

## The content

That's great to hear you have a good understanding of the Behavior. My current approach is to look at the existing documentation from Xamarin Community Toolkit and borrow whatever feels current but don't be afraid to rewrite it.

This behavior is documented at: https://docs.microsoft.com/en-gb/xamarin/community-toolkit/behaviors/eventtocommandbehavior

> Are you looking for sample code as well?
Yes please. As an example I have this PR (https://github.com/MicrosoftDocs/CommunityToolkit/pull/11) open at the moment. It currently only has a XAML based sample however we are also working on adding a sample from the `CommunityToolkit.Maui.Markup` package. I would ideally like 3 types of sample:
- XAML
- Standard C#
- Markup C#

Then ideally if the subject of the documentation offers multiple different ways of functioning or more complex approaches we would look to cover those in separate examples.

### Of course you don't have to submit all of that in terms of examples, I will be happy to contribute towards some examples there.

Also for examples I recommend checking out the samples app from this repository as it should give a good example of how to use it if you are ever unsure.

## How to contribute

The documentation repository is located at: https://github.com/MicrosoftDocs/CommunityToolkit so this would need to be forked and a PR submitted in the same process as contributing to this toolkit. You mentioned it was your first OSS contribution so the 2 key parts you will want to know is:
- [How to fork a repo](https://docs.github.com/en/get-started/quickstart/fork-a-repo)
- [How to create a PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)

With the minor added point: **make sure you create a branch in your fork before submitting the PR.** This should help reduce any problems if the repository gets updated by others before you are ready to submit.

## Finally

Sadly there isn't any contribution guides or related bits for the docs yet, we were hoping to plough through the docs on the outstanding proposals before opening up to community contributions but I see this as a good way to learn how much information the community might need to get started 😄 . Would you feel comfortable writing down any points that you are unsure on during this process and sending them my way? This will help structure our guides and the next person coming in.

Let me know if anything is unclear and thanks again for looking at this

**Comment by IndianaGary** [comment]
Hi Shaun,

Yes, this looks quite doable, although I happen to be in the middle of a project that will need to take priority for now. I should be far enough along midweek that I can jump on this. I do have one question that requires some setup:

One of my pet peeves is that often an architectural element, like a Behavior, is not clearly deefined, leaving a contextual hole in the continuity of the documentation. My approach tends to be along the line of:

1. What is a Behavior
2. What does a Behavior do from a high level
3. What does this specific Behavior do and why is it needed
4. Identify the elements of the Behavior and document them
5. Provide examples of the behavior in XAML, and in C#

Items 1 and 2 are usually just a paragraph or two, depending on the complexity of what I’m documenting. Items 4 and 5 can start from the existing XF docs and example(s) with tailoring depending on the differences in platform. Any differences from Xamarin Forms need to be explicitly highlighted.

My question is: does this sound like an approach you could support?

One point of clarification: I got XAML and C# Markup. What do you mean by “Standard C#?” A Behavior is an architectural element that is closely coupled to the platform, and it is implemented, in this case, in C#. Consumption of a Behavior can be in either C# or XAML. Am I overlooking something?

Regards,
Gary

**Comment by bijington** [comment]
Hey @IndianaGary I am really sorry for the delayed response I completely missed your reply somehow. Please see my responses to your questions below:

> One of my pet peeves is that often an architectural element, like a Behavior, is not clearly deefined, leaving a contextual hole in the continuity of the documentation. My approach tends to be along the line of:

> 1. What is a Behavior
> 2. What does a Behavior do from a high level
> 3. What does this specific Behavior do and why is it needed
> 4. Identify the elements of the Behavior and document them
> 5. Provide examples of the behavior in XAML, and in C#

> Items 1 and 2 are usually just a paragraph or two, depending on the complexity of what I’m documenting. Items 4 and 5 can start from the existing XF docs and example(s) with tailoring depending on the differences in platform. Any differences from Xamarin Forms need to be explicitly highlighted.

> My question is: does this sound like an approach you could support?

I like your breakdown of concepts. I would like to suggest that we shouldn't write points 1 and 2 but simply link across to the .NET MAUI docs that already cover this: https://docs.microsoft.com/en-gb/dotnet/maui/fundamentals/behaviors. In fact I will make a point of doing the same for the existing docs pages thanks.

As for starting with XF docs, I assume you mean the XCT docs there. We can and should take those as a base example, sadly some of that documentation is at times lacking in depth or even non-existent so I am keen to review it and decide on what fits best with this new toolkit being MAUI focused. I don't think we need to worry about the differences between MAUI and XF at least for behaviour and converter usage, I fully expect them to behave the same from a conceptual point of view. Of course there may be behavioural changes that we have introduced in our conversion from XCT to MCT but I think that could be additional documentation to add outside of these specific pages.

> One point of clarification: I got XAML and C# Markup. What do you mean by “Standard C#?” A Behavior is an architectural element that is closely coupled to the platform, and it is implemented, in this case, in C#. Consumption of a Behavior can be in either C# or XAML. Am I overlooking something?

Sorry I meant we are currently providing an example that shows how a developer could consume the Behavior in XAML, C# (if they aren't using the Markup package) and then also the Markup package. Basically to show off how much value they could get by using the Markup package. I am also finding that this exercise is helping to think of more ways to enhance the Markup package.

Does this help?

**Comment by CliffAgius** [comment]
Has this one stalled at all?  I was just about to work on it as I have just linked to this doc from the `ItemTappedEventArgsConverter` docs page and realised the current Docs repo doesn't have the page.  

I have named the doc file in my link "event-to-command-behavior.md" to match the naming convention used in the rest of the docs.

**Comment by bijington** [comment]
It doesn't look like it has had any updates for a month @IndianaGary are you still hoping to work on this?

**Comment by IndianaGary** [comment]
I'm afraid that the window of opportunity for me to work on this closed several weeks ago. I haven't heard from anyone for quite a long time with information on how to proceed. I won't be available again until after my current project completes which won't be until at least the end of June.

Sorry for the confusion.
Gary

**Comment by CliffAgius** [comment]
Hey @IndianaGary don't worry we all have busy times and projects to complete. I'm between projects at the moment so will pick this one up.

**Comment by IndianaGary** [comment]
Thanks, Cliff! I really appreciate it! As soon as I free up again, I'll let Brandon know that I'm available.

Regards,
Gary

**Comment by CliffAgius** [comment]
Can I be assigned to this one please.

**Comment by bijington** [comment]
Done. Thanks @CliffAgius
