### ISSUE TITLE
[Bug] Dynamic content doesn't change popup size / height

### ISSUE THREAD

**Issue by Giuseppetm** [CommunityToolkit/Maui#440]
### Description
Switching the content of the popup through a property that replaces the current content doesn't change the height / size of the popup.

### Reproduction Sample
[PopupTest.zip](https://github.com/CommunityToolkit/Maui/files/8843382/PopupTest.zip)

### Steps to Reproduce

1. Press the button "Press me" to change the content of the popup.

### Expected Behavior
The size / height of the popup changes dynamically based on its content.

### Actual Behavior
The size / height of the popup remains the same as the first content rendered.

### Basic Information

- Version with issue: `1.0.0`
- Last known good version: `none`
- IDE: VS
- Platform Target Frameworks: 
  - Android: `11.0`

### Workaround
None

### Reproduction imagery

|  |  |
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/52317197/170209193-fcb37d92-0aa0-459e-8bf2-7c05e1fd327e.png) | ![image](https://user-images.githubusercontent.com/52317197/170209453-d729f023-4957-46fd-8785-d9161cc188a7.png)|

This problem also applies to the horizontal width of the popup content: in this case the text I mentioned in #439 is not visible anymore, but the width remains broken.

|  |  |
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/52317197/170209986-09fa421c-3115-4243-a192-9be43c3383eb.png)| ![image](https://user-images.githubusercontent.com/52317197/170209708-8f405898-b03e-4882-bd53-28dfd39a0051.png)|

**Comment by Giuseppetm** [comment]
Any update on this?

**Comment by pictos** [comment]
@Giuseppetm didn't look into this issue yet. For the next release I focused on apple platform.

**Comment by manuelelucchi** [comment]
Any news on this @pictos ?

**Comment by pictos** [comment]
Looks like it has something to do with the ScrollView. Need more investigation

**Comment by EduardoReisDev** [comment]
Same problem here

![image](https://user-images.githubusercontent.com/52722526/189470867-3178ed1e-162a-4e25-9e9a-a05a96430699.png)

**Comment by EduardoReisDev** [comment]
@pictos, não sei se isso ajuda kk

**Comment by pictos** [comment]
@EduardoReisDev if you set the horizontal/verticalOptions = "Center" does it fix on iOS?

**Comment by EduardoReisDev** [comment]
@pictos, nop!

![image](https://user-images.githubusercontent.com/52722526/189493167-3273fb14-225a-478e-b3b2-2ca1687e7da9.png)

**Comment by pictos** [comment]
@EduardoReisDev I'm talking about the popup control and not the layout

**Comment by SymxnCreator** [comment]
Does not work too.
Same problem on Windows and Android. Height is miscalculated on Windows and width on Android.

**Comment by MateuszLas421** [comment]
Any idea how to solve this on iOS ?

**Comment by brminnick** [comment]
Fixed in https://github.com/CommunityToolkit/Maui/pull/1320
