### ISSUE TITLE
[Bug] UriValidationBehavior didn't change style of Border

### ISSUE THREAD

**Issue by KafkaWannaFly** [CommunityToolkit/Maui#442]
### Description

I try using this behaviour to update the style of a Border based on the validation result of an Entry. The validation result is updated correctly as the user types but the Border's style is not updated

### Stack Trace

No Stack Trace

### Link to Reproduction Sample

Check out this branch: https://github.com/KafkaWannaFly/WibuTube/tree/UriValidationBehavior-Bug-Reproduction at `MainPage.xaml`

Example code
```xaml
<Border x:Name="urlEntryBorder"
                            Padding="0"
                            Margin="0">
	<Entry x:Name="urlEntry"
                             ClearButtonVisibility="WhileEditing"
                             IsSpellCheckEnabled="false"
                             Keyboard="Url"
                             Grid.Column="0"
                             Placeholder="YouTube url..."
                             ReturnCommand="{Binding SearchVideoCommand}"
                             ReturnType="Search"
                             Text="{Binding Url, Mode=TwoWay}"
                             VerticalTextAlignment="Center"></Entry>
	<Border.Behaviors>
		<toolkit:UriValidationBehavior x:Name="validator"
                                                         Value="{Binding Url}"
                                                         InvalidStyle="{StaticResource InvalidEntryStyle}"
                                                         ValidStyle="{StaticResource ValidEntryStyle}"
                                                         Flags="ValidateOnValueChanged"
                                                         UriKind="Absolute" />
	</Border.Behaviors>
</Border>
<Button Grid.Column="1"
                          IsEnabled="True"
                          Padding="12"
                          FontFamily="Segoe MDL2 Assets"
                          FontSize="20"
                          BindingContext="{x:Reference validator}"
                          x:DataType="toolkit:UriValidationBehavior"
                          Text="{Binding Path=IsValid}" />
```

### Steps to Reproduce

1. Run the code, targeting the Window machine. You will see 1 text input and 1 button
2. Input random characters on the text input. Button text change to False
3. Input a valid URL (eg. https://github.com/). Button text change to True

### Expected Behavior

The border colour of the text input should be red when False and green when True

### Actual Behavior

The border colour of the text input doesn't change

### Basic Information

- Version with issue: 1.0.0
- Last known good version: 1.0.0
- IDE: Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.3.0 Preview 1.1
- Platform Target Frameworks: net6.0-windows10.0.19041.0

### Workaround
No workaround

### Reproduction imagery

![image](https://user-images.githubusercontent.com/47100782/172365490-ae2667c5-f000-42e4-941c-ac6e00328c81.png)

![image](https://user-images.githubusercontent.com/47100782/172365549-b0351ee4-55ea-41df-97b6-11c24681afa3.png)

**Comment by bijington** [comment]
@KafkaWannaFly thank you for the bug report. The link to your reproduction sample is giving me a 404, is it a private repository?

**Comment by VladislavAntonyuk** [comment]
Could you also try on Android or iOS. There may be an issue with Fluent Windows style

**Comment by bijington** [comment]
I wonder if this relates in some way to this discussion: https://github.com/CommunityToolkit/Maui/discussions/385 it appears at least in the discussion that visual states are replacing the styling that we are setting through the behavior

**Comment by KafkaWannaFly** [comment]
Hi @bijington 

I think I found the solution. The root cause may come from default Border style in `Style.xaml`. Which is:
```xaml
    <Style TargetType="Border">
        <Setter Property="Stroke" Value="{AppThemeBinding Light={StaticResource Gray200}, Dark={StaticResource Gray500}}" />
        <Setter Property="StrokeShape" Value="Rectangle"/>
        <Setter Property="StrokeThickness" Value="1"/>
    </Style>
```

There might be something wrong with the `StrokeShape` property. Sadly, the IDE didn't prompt any error. 
I change from:
```xaml
<Style x:Key="InvalidEntryStyle"
               TargetType="Border">
            <Setter Property="Stroke"
                    Value="Red" />
            <Setter Property="StrokeShape"
                    Value="Rectangle" />
            <Setter Property="StrokeThickness"
                    Value="1" />
        </Style>
```

To:
```xaml
<Style x:Key="InvalidEntryStyle"
               TargetType="Border">
            <Setter Property="Stroke"
                    Value="Red" />
            <Setter Property="StrokeThickness"
                    Value="1" />
            <Setter Property="StrokeShape">
                <Setter.Value>
                    <RoundRectangle CornerRadius="8" />
                </Setter.Value>
            </Setter>
        </Style>
```

So, I conclude that there is nothing wrong with the `UriValidationBehavior` and we can close this issue.

**Comment by bijington** [comment]
@KafkaWannaFly thank you for the update and investigating the issue
