### ISSUE TITLE
[Bug] Rounded corners not working with the .NET MAUI GA release and its compatible v1.0.0 release of CommunityToolkit.Maui package

### ISSUE THREAD

**Issue by egvijayanand** [CommunityToolkit/Maui#447]
### Description

Rounded corners not working with the .NET MAUI GA release and its compatible v1.0.0 release of CommunityToolkit.Maui package.

The same code worked fine in the earlier version providing a rounded corner effect for the Popup.

### Steps to Reproduce

1. Add a Popup in the new or existing .NET MAUI App
2. Refer to the below code for adding a rounded corner look that worked in the earlier version
3. Build and run the project

Only the necessary properties are shown for brevity

```xml
<mct:Popup xmlns="http://schemas.microsoft.com/dotnet/2021/maui" 
    xmlns:mct="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
    Color="Transparent">
    <Frame BackgroundColor="Transparent"
        CornerRadius="8"
        HasShadow="True">
        <!-- Popup Content -->
    </Frame>
</mct:Popup>
```
### Expected Behavior
A popup with a rounded corner

### Actual Behavior
A Popup with sharp edges

### Basic Information

- Version with issue: v1.0.0 (GA compatible release)
- Last known good version: Preview 14 compatible version, referring the discussion thread associated with it #352 
- IDE: VS2022 17.3.0 Preview 1.1
- Platform Target Frameworks: 
  - iOS:  
  - Android:  Android SDK 31.0
  - UWP/WinUI:   Windows 10.0.19041.0
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

Not yet.

**Comment by pictos** [comment]
@egvijayanand just to make sure... The rounded corners isn't working with anything on .NET MAUI or it's not working on Popups?

**Comment by egvijayanand** [comment]
Facing this issue only with Popup, rounded corners with Frame work fine on other MAUI controls.
