### ISSUE TITLE
[Bug] Background Blur Effect not working on iOS

### ISSUE THREAD

**Issue by naweed** [CommunityToolkit/Maui#449]
Hi,
I am creating a default popup and noticed that the background blur effect does not work in iOS.

### Description

When creating a default popup based on the guidance: https://docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/popup, I am facing the issue that the background blur effect does not work in iOS. It works fine for Android. This is also a continuation of: https://twitter.com/xgeno/status/1535172798481571840

### Link to Reproduction Sample

Plz see a sample repository for this: 
[PopupTest.zip](https://github.com/CommunityToolkit/Maui/files/8880486/PopupTest.zip)

### Steps to Reproduce

1.  Create a simple popup (as in the attached)
2.  Open the Popup 

### Expected Behavior

Blur effect appears behind popup

### Actual Behavior

Blur effect does not appear behind popup on iOS. It does work fine for Android.

### Basic Information

- Version with issue: 1.0.0
- Last known good version: N/A
- IDE: VS for Mac 17.3 Preview
- Platform Target Frameworks: 
  - iOS:  15.5
  - Android: 12
- Nuget Packages: CommunityToolkit.Maui 1.0.0

### Workaround
None at the moment. I tried everything. Couldn't find a workaround.

### Reproduction imagery
![FU4HCYLWYAEgcOA](https://user-images.githubusercontent.com/103980/173110133-447d11ad-371e-42f4-a19e-702ddecc4fe0.jpeg)

**Comment by pictos** [comment]
@naweed thanks for reporting this here, please fill the title section

**Comment by naweed** [comment]
Sorry, my bad.
