### ISSUE TITLE
[Proposal] Implied Order Grid Behavior

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#45]
# ImpliedOrderGridBehavior

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
  * [ ] iOS Support
  * [ ] Android Support
  * [ ] macOS Support
  * [ ] Windows Support
* [ ] Unit Tests: Not Started
* [ ] Documentation: Not Started
* [ ] Sample: Not Started

## Summary
[summary]: #summary

The ImpliedOrderGridBehavior enables you to automatically assign a Grid row and column to a view based on the order the view is added to the Grid. You only need to setup the row and column definitions and then add children to the Grid. You may still assign RowSpan and ColumnSpan to views and their values will be taken into account when assigning a row and column to a view. If a view has a user defined row or column value it will be honored.

## Detailed Design
[design]: #detailed-design

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<Grid x:Name="TestGrid" Margin="30" BackgroundColor="Gray">
    <Grid.Behaviors>
    <autoLayoutGrid:ImpliedOrderGridBehavior />
    </Grid.Behaviors>

    <Grid.RowDefinitions>
        <RowDefinition Height="*" />
        <RowDefinition Height="*" />
    </Grid.RowDefinitions>

    <Grid .ColumnDefinitions>
        <ColumnDefinition Width="*" />
        <ColumnDefinition Width="*" />
    </Grid.ColumnDefinitions>

    <!-- Row 0 -->
    <Label Grid.RowSpan="2"/>
    <Label />
    <Label />
    <Label Grid.ColumnSpan="2"/>

    <!-- Row 1 -->
    <Label/>
    <Label />
    <Label Grid.ColumnSpan="2" Grid.RowSpan="2" />

</Grid >
```

### C# Usage

```cs
var grid = new Grid
{
    RowDefinitions = 
    {
         new RowDefinition { Height = GridLength.Auto },
         new RowDefinition { Height = GridLength.Auto },
    },

    ColumnDefinitions =
    {
         new ColumnDefinition { Width = GridLength.Auto },
         new ColumnDefinition { Width = GridLength.Auto },
    },
};
grid.Behaviors.Add(new ImpliedOrderGridBehavior());

grid.Children.Add(new Label());
grid.Children.Add(new Label());
grid.Children.Add(new Label());
grid.Children.Add(new Label());

```

## Drawbacks
[drawbacks]: #drawbacks

This is a very complicated feature that may or may not add much value.

## Alternatives
[alternatives]: #alternatives

The alternative is to manually assign each `VisualElement` to a row + column.

## Unresolved Questions
[unresolved]: #unresolved-questions

I'm not sure if this feature has enough value to merit its complexity and maintenance.

**Comment by pictos** [comment]
I agree with what is said on `Unresolved Questions`. Also, with the simplified way to declare `Row/ColumnDefinitions` we can drop this control.
