### ISSUE TITLE
[Bug] Popup color issues on iOS

### ISSUE THREAD

**Issue by imsam67** [CommunityToolkit/Maui#450]
### Description
Reporting three issues here:
1. I set the `color` of the popup but it completely disregards it and goes with the color of theme on device
2. I open the popup from the view model of a page with white background. When I close the popup, the background of page changes to the color of theme on device.
3. Popup also seems to ignore position settings on iOS

Please note that popup behaves exactly the way it should on Android but not on iOS.

I'm testing this on an iPhone Xs with theme set to dark. I, however, wanted my app to have a white background so I manually set the `BackgroundColor="White"` on the page and `Color="White"` on the popup.

When the popup opens up, its background is black even though I set it to white. Once I close the popup by clicking the button, it closes but the background color of my page also becomes black. Here are the screen shots in sequence. Notice the background of the page has already turned black once the popup opens up.

![1](https://user-images.githubusercontent.com/15844030/173116752-fafcee44-9005-494b-8aee-1fd39e6b7247.png)
![2](https://user-images.githubusercontent.com/15844030/173116798-fbd82891-fa96-4a49-bb8b-60f1a49f346a.png)
![3](https://user-images.githubusercontent.com/15844030/173116810-80914b84-53d3-4c24-be76-7556923bc55b.png)

As mentioned, I specifically set page background to white  and set the background of popup to white as well using code below:

```
<?xml version="1.0" encoding="utf-8" ?>
<mct:Popup xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
           xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
           xmlns:mct="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
           xmlns:vm="clr-namespace:Ingrid.Connect.ViewModels.Personal"
           x:Class="Ingrid.Connect.Views.Personal.ConfirmCouponSubmission"
           x:DataType="vm:ConfirmCouponSubmissionViewModel"
           Color="{StaticResource White}"
           HorizontalOptions="Center"
           VerticalOptions="Center"
           Size="250,250">
</mct:Popup>
```

- Version with issue: CommunityToolkit.Maui 1.0.0
- IDE: Visual Studio 2022 17.3.0 Preview 1.1
- Platform Target Frameworks: 
  - iOS:  10
  - Android: 21
- Nuget Packages: CommunityToolkit.Maui, CommunityToolkit.Mvvm, Plugin.InApp, MonkeyCache.FileStore, sqlite-net-pcl
- Affected Devices: iPhone Xx

### Workaround
No workaround that I'm aware of.

**Comment by imsam67** [comment]
@pictos Yes, I thought about that but that doesn't address the issue of changing the background of the page, right?

**Comment by pictos** [comment]
Page or pop-up? Pop-up can't change anything on the page, by default

**Comment by pictos** [comment]
@imsam67 can you attach a small sample showing the first issue?

**Comment by imsam67** [comment]
@pictos Unfortunately, after struggling with the popup for a while, I gave up and moved on to another approach so I don't have the actual code anymore but it was straight from the documentation.

I also want to mention that I open the popup when the user taps on the green button in the first image which calls a command method in my view model.

As far as the effect, you can just look at the images I posted, in the correct order. In image one, you're looking at the page with the green button. Once tapped, the popup opens up as seen in image 2. It's important to notice that in image 2, you can see that the page background already turned black. And finally in image 3, the popup is closed and the page is completely black and you can't see anything.

Another important point to mention is that I don't think the background is being changed to black. But rather, the color set for the  theme used by the device. In my case, I have the dark theme on in my iPhone and I'm pretty sure the page turns black because in the .NET MAUI app setting, the page background color is set to black if dark mode is used.

**Comment by pictos** [comment]
@imsam67 are you using Shell?

**Comment by imsam67** [comment]
Yes, I am

**Comment by pictos** [comment]
This is blocked by
- https://github.com/dotnet/maui/issues/7912
