### ISSUE TITLE
[Bug] Popup not displaying in Maui Embedding application

### ISSUE THREAD

**Issue by jdunaway** [CommunityToolkit/Maui#451]
### Description

Was attempting to use the Community Toolkit popup as a workaround for https://github.com/dotnet/maui/issues/7887 but now I'm running into this issue when trying to display a popup in a MAUI embedding application.

### Error

Attempt to present <CommunityToolkit_Maui_Core_Views_MauiPopup: 0x7fa618c5f0f0> on <Microsoft_Maui_Platform_PageViewController: 0x7fa618933f50> (from <Microsoft_Maui_Platform_PageViewController: 0x7fa618933f50>) whose view is not in the window hierarchy.

### Steps to Reproduce

1. Download code from here https://github.com/jdunaway/MauiEmbeddingDisplayAlertError
2. Open MauiEmbeddingDisplayAlertError.sln
3. Make sure MauiEmbeddingiOSAlertTest is set as the startup project.
4. Run the application on an iOS simulator.  
5. When clicking the button the popup is not displayed and the following error shows up in the output: Attempt to present <CommunityToolkit_Maui_Core_Views_MauiPopup: 0x7fa618c5f0f0> on <Microsoft_Maui_Platform_PageViewController: 0x7fa618933f50> (from <Microsoft_Maui_Platform_PageViewController: 0x7fa618933f50>) whose view is not in the window hierarchy.
6. If you stop debugging and set the MauApp1 as the startup project you will see that the popup is displayed for the Maui application but not the Maui embedded application.  

### Basic Information

- Version with issue: 1.0.0 (latest)
- Last known good version: n/a
- IDE: Microsoft Visual Studio Professional 2022 Preview
Version 17.3.0 Preview 1.1
Platform Target Frameworks: iOS and Android
  - iOS:  15.8.0.3
  - Android: 12.2.4.3

### Workaround
No

**Comment by pictos** [comment]
@jdunaway this looks like a .NET MAUI issue, so I'll close this issue.
