### ISSUE TITLE
[Proposal] Masked Behavior

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#46]
# MaskedBehavior

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Documentation
* [x] Sample

## Summary
[summary]: #summary

The `MaskedBehavior` is a `Behavior` that allows the user to define an input mask for data entry. Adding this behavior to an `Entry` control will force the user to only input values matching a given mask. Examples of its usage include input of a credit card number or a phone number

## Detailed Design
[design]: #detailed-design

### MaskedBehavior.shared.cs

```cs
public class MaskedBehavior : BaseBehavior<InputView>
{
    public static readonly BindableProperty MaskProperty;
    public static readonly BindableProperty UnMaskedCharacterProperty;

    public string? Mask { get; set; }
    public char UnMaskedCharacter { get; set; }
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<Entry>
    <Entry.Behaviors>
        <xct:MaskedBehavior 
            Mask="AA-AA-AA" 
            UnMaskedCharacter="A"
        />
    </Entry.Behaviors>
</Entry>
```

### C# Usage

```cs
var entry = new Entry();
entry.Behaviors.Add(new MaskedBehavior
{
    Mask="AA-AA-AA" 
    UnMaskedCharacter="A"
});
```

**Comment by IeuanWalker** [comment]
@brminnick I contributed this original, and am happy to do a PR for it if you want.

**Comment by brminnick** [comment]
No worries @IeuanWalker! We've already added it to the Maui Community Toolkit: https://github.com/CommunityToolkit/Maui/blob/bc44e35f133c8d3e0e727135336656877103588c/src/CommunityToolkit.Maui/Behaviors/MaskedBehavior.shared.cs#L12

I'm opening all of these Proposals this week to basically just catch up on the paperwork. We are implementing a [new workflow](https://github.com/CommunityToolkit/Maui/projects/1) for the Toolkit which'll help us keep track of not just the Code, but the associated Documentation as well!
