### ISSUE TITLE
[Bug] Last popup rendered appears at right-click mouse location 

### ISSUE THREAD

**Issue by ericnev** [CommunityToolkit/Maui#462]
### Description

Saw this with my own project, then downloaded and reproduced it on the MCT popup sample app. Choose "Views" from the flyout, and go to the "Multiple Popups" page. Click on any popup, for example, "Toggle Size Popup". The popup appears as intended. Dismiss it by clicking outside its bounds. Right click on any area in the page after dismissal, and you'll see the same popup reappear, seemingly tied to the mouse click position.

### Steps to Reproduce

1. Launch sample app. Go to Views->Multiple Popups Page sample.
2. Click "Toggle Size" button to launch appropriate popup.
3. Click outside popup to dismiss it.
4. Right click anywhere on MultiplePopups page.

### Expected Behavior
No popup will appear.
### Actual Behavior
Last launched popup appears.
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  X- UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:
Tested on Windows MAUI GA.

**Comment by pictos** [comment]
@ericnev can you test with the new version?

**Comment by ericnev** [comment]
> 

Upgraded to 1.1.0, and the issue persists.

**Comment by pictos** [comment]
@ericnev 
Could you attach a small repro?

**Comment by imms20** [comment]
@brminnick I have just cloned the repo, ran the samples. on the multiplePopupPage, I have opened simple popups. dismissed it when I have clicked outside the popup. now when I click on the page anywhere using right click, the same popups keeps appearing. in fact when I open any kind of popup, the behaviour is the same.

**Comment by imms20** [comment]
I am running windows 10 21H2, 19044.1826 though

**Comment by imms20** [comment]
it is trying to open the popup on the clicked location

**Comment by pictos** [comment]
@imms20 I could confirm the issue, but didn't find anything on docs about how to disable it. So I'll presume this is something on WinUI not on us. Please open an issue there.
If you or anyone knows how to disable this behavior please tell us or open a PR (:
