### ISSUE TITLE
[Bug] iOS ShellContent gets cleared on ShowPopup

### ISSUE THREAD

**Issue by mariusmcalpine** [CommunityToolkit/Maui#466]
### Description

Whenever doing a ShowPopup() from a ShellContent page in iOS, the page content first gets cleared before the popup is displayed.

### Link to Reproduction Sample
[Test.CommunityToolkit.Popups.iOS.zip](https://github.com/CommunityToolkit/Maui/files/8958141/Test.CommunityToolkit.Popups.iOS.zip)

### Steps to Reproduce
1. Create a new .NET MAUI App project in Visual Studio.
2. Add CommunityToolkit.Maui (1.0.0) nuget package to project.
3. Add a simple popup class inheriting from CommunityToolkit.Maui.Views.Popup
```
using CommunityToolkit.Maui.Views;

namespace MauiApp1
{
    public class SimplePopup : Popup
    {
        public SimplePopup() : base()
        {
            Content = new StackLayout
            {
                Children =
            {
                new Label { Text = "This is a simple popup!" }
            }
            };
        }
    }
}
```

4. Add .UseMauiCommunityToolkit() to your CreateMauiApp() method and resolve as per nuget readme.txt

5. Add the popup as a Transient to Service list in MauiProgram
```
using CommunityToolkit.Maui;

namespace MauiApp1;

public static class MauiProgram
{
	public static MauiApp CreateMauiApp()
	{
		var builder = MauiApp.CreateBuilder();
		builder
			.UseMauiApp<App>()
            .UseMauiCommunityToolkit()					// Initialise the toolkit
            .ConfigureFonts(fonts =>
			{
				fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
				fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
			});

		builder.Services.AddTransient<SimplePopup>();	// Register SimplePopup

		return builder.Build();
	}
}
```

6. Replace content of OnCounterClicked() method in MainPage.xaml.cs
```
private void OnCounterClicked(object sender, EventArgs e)
   {
        var popup = new SimplePopup();
        this.ShowPopup(popup);
    }
```

### Expected Behavior
On Android platform, popup shows over ShellContent page layout.

![Expected behavior Android 2](https://user-images.githubusercontent.com/5115444/175046516-80c9a376-8d0a-4216-b228-fd879459eb98.png)

On iOS on a screen that is not part of the AppShell, the popup shows correctly.

![Expected behavior iOS 1](https://user-images.githubusercontent.com/5115444/175047990-23f35e2f-9936-44e9-bbae-9a279e44df94.PNG)

### Actual Behavior
On iOS, popup clears ShellContent page, and then displays popup.

![Unexpected behavior iOS 2](https://user-images.githubusercontent.com/5115444/175048325-7ad3413c-0461-47e3-b9ec-e00b57cea55c.PNG)

Content is blanked out.

![Unexpected behavior iOS 3](https://user-images.githubusercontent.com/5115444/175048364-f2c4710a-a1a7-431c-983f-ecb4ad0a50ac.PNG)

Looks similar to this issue https://github.com/CommunityToolkit/Maui/issues/463 

### Basic Information

- Version with issue: 1.0.0
- IDE: Visual Studio 17.3.0 Preview 1.1

**Comment by pictos** [comment]
Related to 
- https://github.com/dotnet/maui/issues/7941
