### ISSUE TITLE
[Bug]  MultiMathExpressionConverter works in android but fails on windows and ios

### ISSUE THREAD

**Issue by craigbosward** [CommunityToolkit/Maui#467]
made a clean maui app to confirm behavior.  added MultiMathExpressionConverter on main page based on example and added VM.  Works as expected on android simulator but fails on ios (iphone 11 15.5 ) simulator and windows with 
![image](https://user-images.githubusercontent.com/96669462/175249479-db848082-66d3-4b23-a420-dffd34f2316a.png)

same for ios and windows.  android is successful.
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>MainPage.xaml(8,14): XamlC error XFC0000: Cannot resolve type "http://schemas.microsoft.com/dotnet/2022/maui/toolkit:tt:MultiMathExpressionConverter".
1>Done building project "MauiApp5.csproj" -- FAILED.

### Steps to Reproduce

<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
             xmlns:vm="MultiMathExpressionConverterViewModel"   xmlns:tt="http://schemas.microsoft.com/dotnet/2022/maui/toolkit" 
             x:Class="MauiApp5.MainPage">

    <ContentPage.Resources>
        <ResourceDictionary>
            <tt:MultiMathExpressionConverter x:Key="MultiMathExpressionConverter" />
        </ResourceDictionary>
    </ContentPage.Resources>

    <Grid Padding="20"
          RowSpacing="20"
          ColumnSpacing="12"
          ColumnDefinitions="*,*,*,*,*,*,*"
          RowDefinitions="100, *">
        <Label Grid.ColumnSpan="7"
               Grid.Row="0"
               Text="This sample demonstrates the use of the MultiMathExpressionConverter. It utilizes the converter to perform various math operations of multiple variables."/>

        <Entry Grid.Column="0"
               Grid.Row="1"
               VerticalTextAlignment="Center"
               VerticalOptions="Center"
               Text="{Binding X0}"/>

        <Label Grid.Column="1"
               Grid.Row="1"
               VerticalTextAlignment="Center"
               VerticalOptions="Center"
               Text="+" />

        <Entry Grid.Column="2"
               Grid.Row="1"
               VerticalTextAlignment="Center"
               VerticalOptions="Center"
               Text="{Binding X1}"/>

        <Label Grid.Column="3"
               Grid.Row="1"
               VerticalTextAlignment="Center"
               VerticalOptions="Center"
               Text="+" />

        <Entry Grid.Column="4"
               Grid.Row="1"
               VerticalTextAlignment="Center"
               VerticalOptions="Center"
               Text="{Binding X2}"/>

        <Label Grid.Column="5"
               Grid.Row="1"
               VerticalTextAlignment="Center"
               VerticalOptions="Center"
               Text="=" />

        <Label Grid.Column="6"
               Grid.Row="1"
               VerticalTextAlignment="Center"
               VerticalOptions="Center">
            <Label.Text>
                <MultiBinding Converter="{StaticResource MultiMathExpressionConverter}"
                              ConverterParameter="x0 + x1 + x2">
                    <Binding Path="X0" Mode="OneWay"/>
                    <Binding Path="X1" Mode="OneWay"/>
                    <Binding Path="X2" Mode="OneWay"/>
                </MultiBinding>
            </Label.Text>
        </Label>
    </Grid>
</ContentPage>

using MauiApp5.VM;
namespace MauiApp5;
public partial class MainPage : ContentPage
{
    private readonly MultiMathExpressionConverterViewModel mathExpressionConverterViewModel;
    public MainPage()
    {
        InitializeComponent();
        BindingContext = mathExpressionConverterViewModel = new MultiMathExpressionConverterViewModel();

    }

}

using CommunityToolkit.Mvvm.ComponentModel;
namespace MauiApp5.VM;

public partial class MultiMathExpressionConverterViewModel : BaseVM
{
    [ObservableProperty]
    double x0 = 10;

    [ObservableProperty]
    double x1 = 20;

    [ObservableProperty]
    double x2 = 30;
}

using CommunityToolkit.Mvvm.ComponentModel;
namespace MauiApp5.VM;

public partial class BaseVM : ObservableObject
{
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(IsNotBusy))]
    bool isBusy;

    [ObservableProperty]
    bool isBusy2;

    [ObservableProperty]
    string title;

    public bool IsNotBusy => !IsBusy;
}

### Expected Behavior
ios and windows work like android.

### Actual Behavior
ios and windows not working.
### Workaround
None

### Reproduction imagery
android:
![Screenshot_1655972146](https://user-images.githubusercontent.com/96669462/175251466-537bb806-1959-4dbf-8aba-dac36a7278fa.png)

**Comment by VladislavAntonyuk** [comment]
could you please attach a small repro, looks like you incorrectly define the namespace or forgot to add UseMauiCommunityToolkit in MainProgram

**Comment by bijington** [comment]
@craigbosward did you attach the repo in the email you replied with? I'm not sure GitHub includes attachments that way

**Comment by craigbosward** [comment]
I did attach an attachment to the email reply.  I’ll try and upload Github.

**Comment by craigbosward** [comment]
[MauiApp5.zip](https://github.com/CommunityToolkit/Maui/files/8986068/MauiApp5.zip)
a small sample.

**Comment by pictos** [comment]
@craigbosward, I downloaded and ran your sample. You forgot to call the `builder.UseMauiCommunityToolkit()` in `MauiProgram` class. If you don't do that you can't use our custom xml-schema. The info about it is on the README file that is opened when you install the nuget.
