### ISSUE TITLE
[Android] Cant click anything (ALL Buttons dont work)[Bug] 

### ISSUE THREAD

**Issue by DeepWorksStudios** [CommunityToolkit/Maui#473]
### Link to Reproduction Sample

Pull current Maui CommunityToolkit Sample 

### Steps to Reproduce

1. Pull current Maui CommunityToolkit Sample 
2. Target Android
3. Start Emulator/Device
4. try click an entry

### Expected Behavior

Opens the desired function

### Actual Behavior

Does not regonize click

### Basic Information

- Version with issue: Current
- Last known good version: Unknown
- IDE: Current VS22 Preview

### Workaround
None

**Comment by VladislavAntonyuk** [comment]
If you try to click on CollectionView item, it's a known .NET MAUI issue.

> try click an entry
What entry do you try to click?

**Comment by VladislavAntonyuk** [comment]
https://github.com/dotnet/maui/issues/8416
