### ISSUE TITLE
[Bug] CharactersValidationBehavior  Bindings missing

### ISSUE THREAD

**Issue by DeepWorksStudios** [CommunityToolkit/Maui#474]
### Steps to Reproduce

1. Pull current sample
2. start windows device
3. open section CharactersValidationBehavior  

### Expected Behavior
No binding failures
### Actual Behavior
7 binding failures
### Basic Information

- Version with issue: current
- Last known good version: unknown
- IDE: vs22 prewiev

**Comment by DeepWorksStudios** [comment]
I took a picture from the issue hope it will help 
![image](https://user-images.githubusercontent.com/59297046/176835397-90c9977a-7d4f-4357-a9ae-f054d79382b4.png)

**Comment by bijington** [comment]
From that image these look like a bug in the tooling rather than us.

**Comment by andrewhenry3** [comment]
Those bindings are pointing to controls whose names were removed. 
An undocumented change to CharactersValidationBehaviorPage.xaml slipped into commit 1bd3586dc27c603fa5ac682aa5bf9df201ac9482
If that is reverted, the binding errors go away.

**Comment by bijington** [comment]
> These aren't just background binding errors, they actually prevent the sample on that page from functioning.  Those bindings are pointing to controls whose names were removed. 
> 
> An undocumented change to CharactersValidationBehaviorPage.xaml slipped into commit 1bd3586dc27c603fa5ac682aa5bf9df201ac9482
> 
> If that is reverted, the binding errors go away.  

Great spot! Yes we should add the names back to solve this issue thanks

**Comment by Tviljan** [comment]
Oof. Is there any workaround for this?

**Comment by bijington** [comment]
The bug is inside our sample application so we do have a reproduction
