### ISSUE TITLE
[Bug] SelectAllTextBehaviorPage Causes Freez

### ISSUE THREAD

**Issue by DeepWorksStudios** [CommunityToolkit/Maui#475]
### Steps to Reproduce

1. Pull current MauiToolKit Sample
2. Start Device
3. Open tab behavior
4. Open SelectAllTextBehavior

### Expected Behavior
Opens the Page SelectAllTextBehavior
### Actual Behavior
Freezes
### Basic Information

- Version with issue: current
- Last known good version: unknown
- IDE: vs22 Preview
- Platform: Windows

**Comment by VladislavAntonyuk** [comment]
What do you mean by Freezes? Does the app stop responding/crash?
What device do you use?

CollectionView clicks don't work on Android (known .NET MAUI issue)

**Comment by DeepWorksStudios** [comment]
The app stop responding under windows seems working fine on android

**Comment by VladislavAntonyuk** [comment]
Reproduced, the issue with Frame. I will create a PR
