### ISSUE TITLE
[Proposal] IServiceCollection extension methods to register Views & ViewModels

### ISSUE THREAD

**Issue by rjygraham** [CommunityToolkit/Maui#479]
# IServiceCollection extension methods to register Views & ViewModels

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Sample
* [x] Documentation: https://github.com/MicrosoftDocs/CommunityToolkit/pull/118

## Link to Discussion

#430

## Summary

[summary]: #summary

This proposal is to add `IServiceCollection` extension methods to `CommunityToolkit.Maui` which registers Views and the corresponding ViewModels together. These extension methods would also allow for optionally registering Shell routes for pages not explicitly added to `AppShell.xaml`

## Motivation

[motivation]: #motivation

When implementing the MVVM pattern, it is common to resolve Views, ViewModels, and required dependencies from the `IServiceCollection` container. Since Views and ViewModels need to be registered in the `IServiceCollection` and they typically share a direct 1:1 relationship, it makes sense to provide helper methods to register both the View and ViewModel in a single line of code versus having to register them independently.

Furthermore, there may be requirements to register specific pages with Shell routing in code using `Routing.RegisterRoute()` instead of directly adding pages to the markup of `AppShell.xaml`. The extension methods to register Views and ViewModels in `IServiceCollection` could further simplify development by providing a means to register pages in Shell routing.

## Detailed Design

[design]: #detailed-design

This proposal introduces the following `IServiceCollection` extension methods. This option introduces more extension methods in a slightly more verbose yet fluent API with the `ServiceLifetime` part of the method name.

```cs
public static class IServiceCollectionExtensions
{
    /// <summary>
    /// Adds a Page or View of the type specified in <typeparamref name="TView"/> and a ViewModel
    /// of the type specified in <typeparamref name="TViewModel"/> to the specified
    /// <see cref="IServiceCollection"/> with <see cref="ServiceLifetime.Singleton"/> lifetime.
    /// </summary>
    /// <typeparam name="TView">The type of the View to add. Constrained to <see cref="Microsoft.Maui.Controls.VisualElement"/></typeparam>
    /// <typeparam name="TViewModel">The type of the ViewModel to add. Constrained to <see cref="INotifyPropertyChanged"/></typeparam>
    /// <param name="services">The <see cref="IServiceCollection"/> to add the service to.</param>
    /// <returns>A reference to this instance after the operation has completed.</returns>
    public static IServiceCollection AddSingletonViewAndViewModel<TView, TViewModel>(this IServiceCollection services)
        where TView : Microsoft.Maui.Controls.BindableObject
        where TViewModel : INotifyPropertyChanged
    {
        services.AddSingleton<TViewModel>();
        return services.AddSingleton<TView>();
    }

    /// <summary>
    /// Adds a Page of the type specified in <typeparamref name="TView"/> and a ViewModel
    /// of the type specified in <typeparamref name="TViewModel"/> to the specified
    /// <see cref="IServiceCollection"/> with <see cref="ServiceLifetime.Singleton"/> lifetime
    /// and registers a MAUI Shell route in <see cref="Routing"/> using the value of <paramref name="route"/> as the route.
    /// </summary>
    /// <typeparam name="TView">The type of the View to add. Constrained to <see cref="Microsoft.Maui.Controls.Page"/></typeparam>
    /// <typeparam name="TViewModel">The type of the ViewModel to add. Constrained to <see cref="INotifyPropertyChanged"/></typeparam>
    /// <param name="services">The <see cref="IServiceCollection"/> to add the service to.</param>
    /// <returns>A reference to this instance after the operation has completed.</returns>
    public static IServiceCollection AddSingletonViewAndViewModelWithShellRoute<TView, TViewModel>(this IServiceCollection services, string route, RouteFactory? factory = null)
        where TView : Microsoft.Maui.Controls.Page
        where TViewModel : INotifyPropertyChanged
    {
        if(factory is null)
        {
            Routing.RegisterRoute(route, typeof(TView));
        }
        else
        {
            Routing.RegisterRoute(route, factory);
        }

        return services.AddSingletonViewAndViewModel<TView, TViewModel>();
    }

    /// <summary>
    /// Adds a Page or View of the type specified in <typeparamref name="TView"/> and a ViewModel
    /// of the type specified in <typeparamref name="TViewModel"/> to the specified
    /// <see cref="IServiceCollection"/> with <see cref="ServiceLifetime.Scoped"/> lifetime.
    /// </summary>
    /// <typeparam name="TView">The type of the View to add. Constrained to <see cref="Microsoft.Maui.Controls.VisualElement"/></typeparam>
    /// <typeparam name="TViewModel">The type of the ViewModel to add. Constrained to <see cref="INotifyPropertyChanged"/></typeparam>
    /// <param name="services">The <see cref="IServiceCollection"/> to add the service to.</param>
    /// <returns>A reference to this instance after the operation has completed.</returns>
    public static IServiceCollection AddScopedViewAndViewModel<TView, TViewModel>(this IServiceCollection services)
        where TView : Microsoft.Maui.Controls.BindableObject
        where TViewModel : INotifyPropertyChanged
    {
        services.AddScoped<TViewModel>();
        return services.AddScoped<TView>();
    }

    /// <summary>
    /// Adds a Page of the type specified in <typeparamref name="TView"/> and a ViewModel
    /// of the type specified in <typeparamref name="TViewModel"/> to the specified
    /// <see cref="IServiceCollection"/> with <see cref="ServiceLifetime.Scoped"/> lifetime
    /// and registers a MAUI Shell route in <see cref="Routing"/> using the value of <paramref name="route"/> as the route.
    /// </summary>
    /// <typeparam name="TView">The type of the View to add. Constrained to <see cref="Microsoft.Maui.Controls.Page"/></typeparam>
    /// <typeparam name="TViewModel">The type of the ViewModel to add. Constrained to <see cref="INotifyPropertyChanged"/></typeparam>
    /// <param name="services">The <see cref="IServiceCollection"/> to add the service to.</param>
    /// <returns>A reference to this instance after the operation has completed.</returns>
    public static IServiceCollection AddScopedViewAndViewModelWithShellRoute<TView, TViewModel>(this IServiceCollection services, string route, RouteFactory? factory = null)
        where TView : Microsoft.Maui.Controls.Page
        where TViewModel : INotifyPropertyChanged
    {
        if(factory is null)
        {
            Routing.RegisterRoute(route, typeof(TView));
        }
        else
        {
            Routing.RegisterRoute(route, factory);
        }

        return services.AddScopedViewAndViewModel<TView, TViewModel>();
    }

    /// <summary>
    /// Adds a Page or View of the type specified in <typeparamref name="TView"/> and a ViewModel
    /// of the type specified in <typeparamref name="TViewModel"/> to the specified
    /// <see cref="IServiceCollection"/> with <see cref="ServiceLifetime.Transient"/> lifetime.
    /// </summary>
    /// <typeparam name="TView">The type of the View to add. Constrained to <see cref="Microsoft.Maui.Controls.VisualElement"/></typeparam>
    /// <typeparam name="TViewModel">The type of the ViewModel to add. Constrained to <see cref="INotifyPropertyChanged"/></typeparam>
    /// <param name="services">The <see cref="IServiceCollection"/> to add the service to.</param>
    /// <returns>A reference to this instance after the operation has completed.</returns>
    public static IServiceCollection AddTransientViewAndViewModel<TView, TViewModel>(this IServiceCollection services)
        where TView : Microsoft.Maui.Controls.BindableObject
        where TViewModel : INotifyPropertyChanged
    {
        services.AddTransient<TViewModel>();
        return services.AddTransient<TView>();
    }

    /// <summary>
    /// Adds a Page of the type specified in <typeparamref name="TView"/> and a ViewModel
    /// of the type specified in <typeparamref name="TViewModel"/> to the specified
    /// <see cref="IServiceCollection"/> with <see cref="ServiceLifetime.Transient"/> lifetime
    /// and registers a MAUI Shell route in <see cref="Routing"/> using the value of <paramref name="route"/> as the route.
    /// </summary>
    /// <typeparam name="TView">The type of the View to add. Constrained to <see cref="Microsoft.Maui.Controls.Page"/></typeparam>
    /// <typeparam name="TViewModel">The type of the ViewModel to add. Constrained to <see cref="INotifyPropertyChanged"/></typeparam>
    /// <param name="services">The <see cref="IServiceCollection"/> to add the service to.</param>
    /// <returns>A reference to this instance after the operation has completed.</returns>
    public static IServiceCollection AddTransientViewAndViewModelWithShellRoute<TView, TViewModel>(this IServiceCollection services, string route, RouteFactory? factory = null)
        where TView : Microsoft.Maui.Controls.Page
        where TViewModel : INotifyPropertyChanged
    {
        if(factory is null)
        {
            Routing.RegisterRoute(route, typeof(TView));
        }
        else
        {
            Routing.RegisterRoute(route, factory);
        }

        return services.AddTransientViewAndViewModel<TView, TViewModel>();
    }
}
```

## Usage Syntax

[usage]: #usage-syntax

This example illustrates how the extension methods could be used within `MauiProgram`

```cs
public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp.CreateBuilder();
        builder
            .UseMauiApp<App>()
            .UseMauiCommunityToolkit()
            .ConfigureFonts(fonts =>
            {
                fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
            })
            .Services
                // Adds HomePage and HomePageViewModel with ServiceLifetime.Transient
                .AddTransientViewAndViewModel<HomePage, HomePageViewModel>()
                // Adds HomePage and HomePageViewModel with ServiceLifetime.Singleton
                .AddSingletonViewAndViewModel<HomePage, HomePageViewModel>()
                // Adds HomePage and HomePageViewModel with ServiceLifetime.Transient and Shell route: "HomePage"
                .AddTransientViewAndViewModelWithShellRoute<HomePage, HomePageViewModel>()
                // Adds HomePage and HomePageViewModel with ServiceLifetime.Transient and Shell route: "MyCustomRoute"
                .AddTransientViewAndViewModelWithShellRoute<HomePage, HomePageViewModel>("MyCustomRoute")
                // Adds HomePage and HomePageViewModel with ServiceLifetime.Singleton and Shell route: "HomePage"
                .AddSingletonViewAndViewModelWithShellRoute<HomePage, HomePageViewModel>()
                // Adds HomePage and HomePageViewModel with ServiceLifetime.Singleton and Shell route: "MyCustomRoute"
                .AddSingletonViewAndViewModelWithShellRoute<HomePage, HomePageViewModel>("MyCustomRoute");

        return builder.Build();
    }
}
```

## Drawbacks

[drawbacks]: #drawbacks

These extension methods are MVVM specific and this repo/package is MAUI specific. Due to the necessary `Microsoft.Maui.Controls.VisualElement` and `Microsoft.Maui.Controls.Page` type constraints needed on the methods they cannot be moved to the `CommunityToolkit.Mvvm` which is a more natural fit. Adding the methods to this repo/package may be confusing to some developers.

These methods also do not address the following scenarios:
- What if the Views and ViewModels need different lifetimes? E.g. Scoped for `TView` and Transient for `TViewModel`?
- What if multiple Views/Pages use the same ViewModel?
- Why doesn't the helper method confirm `TView`s `BindingContext` is `TViewModel`?

## Alternatives

[alternatives]: #alternatives

These extension methods are merely convenience methods for developers. The alternative is to continue registering Views and ViewModels in the `IServiceCollection` independently and then separately registering routes via `Routing.RegisterRoute();` if needed.

## Unresolved Questions

[unresolved]: #unresolved-questions

1. Does `ServiceLifetime.Scoped` make sense in the context of a MAUI application for Pages, Views, and ViewModels? Can someone provide a concrete example of using the `Scoped` lifetime?
1. If Option 1 were to be chosen, should the `lifetime` parameter have a default value set? If yes, is `ServiceLifetime.Transient` the correct value or should it be `ServiceLifetime.Singleton`?
1. Are method names too verbose? If yes, how would you reduce the verbosity?
1. Is there a better API surface we should consider?

### Option 1

This option introduces fewer extension methods by utilizing a parameter to specify the `IServiceCollection` container lifetime of the Page or View and ViewModel. In this option, `ServiceLifetime` has a default value of `ServiceLifetime.Transient`. This may or may not be the correct default value, or perhaps a default value should not be provided at all.

```cs
public static class IServiceCollectionExtensions
{
    /// <summary>
    /// Adds a Page or View of the type specified in <typeparamref name="TView"/> and a ViewModel
    /// of the type specified in <typeparamref name="TViewModel"/> to the specified
    /// <see cref="IServiceCollection"/>.
    /// </summary>
    /// <typeparam name="TView">The type of the Page or View to add. Constrained to <see cref="Microsoft.Maui.Controls.VisualElement"/></typeparam>
    /// <typeparam name="TViewModel">The type of the ViewModel to add. Constrained to <see cref="INotifyPropertyChanged"/></typeparam>
    /// <param name="services">The <see cref="IServiceCollection"/> to add the service to.</param>
    /// <param name="lifetime">The <see cref="ServiceLifetime"/> by which the View and ViewModel will be registered in <see cref="IServiceCollection"/>. Defaults to <see cref="ServiceLifetime.Transient"/></param>
    /// <returns>A reference to this instance after the operation has completed.</returns>
    public static IServiceCollection AddViewAndViewModel<TView, TViewModel>(this IServiceCollection services, ServiceLifetime lifetime = ServiceLifetime.Transient)
        where TView : Microsoft.Maui.Controls.VisualElement
        where TViewModel : INotifyPropertyChanged
    {
        switch (lifetime)
        {
            case ServiceLifetime.Singleton:
                services.AddSingleton<TViewModel>();
                return services.AddSingleton<TView>();
            case ServiceLifetime.Scoped:
                services.AddScoped<TViewModel>();
                return services.AddScoped<TView>();
            case ServiceLifetime.Transient:
                services.AddTransient<TViewModel>();
                return services.AddTransient<TView>();
            default:
                throw new ArgumentOutOfRangeException(nameof(lifetime));
        }
    }

    /// <summary>
    /// Adds a Page of the type specified in <typeparamref name="TView"/> and a ViewModel
    /// of the type specified in <typeparamref name="TViewModel"/> to the specified
    /// <see cref="IServiceCollection"/> and registers a MAUI Shell route in
    /// <see cref="Routing"/> using <typeparamref name="TView"/> type name as the route.
    /// </summary>
    /// <typeparam name="TView">The type of the Page to add. Constrained to <see cref="Microsoft.Maui.Controls.Page"/></typeparam>
    /// <typeparam name="TViewModel">The type of the ViewModel to add. Constrained to <see cref="INotifyPropertyChanged"/></typeparam>
    /// <param name="services">The <see cref="IServiceCollection"/> to add the service to.</param>
    /// <param name="lifetime">The <see cref="ServiceLifetime"/> by which the View and ViewModel will be registered in <see cref="IServiceCollection"/>. Defaults to <see cref="ServiceLifetime.Transient"/></param>
    /// <returns>A reference to this instance after the operation has completed.</returns>
    public static IServiceCollection AddViewAndViewModelWithShellRoute<TView, TViewModel>(this IServiceCollection services, ServiceLifetime lifetime = ServiceLifetime.Transient)
        where TView : Microsoft.Maui.Controls.Page
        where TViewModel : INotifyPropertyChanged
    {
        return services.AddViewAndViewModelWithShellRoute<TView, TViewModel>(typeof(TView).Name, lifetime);
    }

    /// <summary>
    /// Adds a Page of the type specified in <typeparamref name="TView"/> and a ViewModel
    /// of the type specified in <typeparamref name="TViewModel"/> to the specified
    /// <see cref="IServiceCollection"/> and registers a MAUI Shell route in
    /// <see cref="Routing"/> using the value of <paramref name="route"/> as the route.
    /// </summary>
    /// <typeparam name="TView">The type of the Page to add. Constrained to <see cref="Microsoft.Maui.Controls.Page"/></typeparam>
    /// <typeparam name="TViewModel">The type of the ViewModel to add. Constrained to <see cref="INotifyPropertyChanged"/></typeparam>
    /// <param name="services">The <see cref="IServiceCollection"/> to add the service to.</param>
    /// <param name="route">Route at which this page will be registered with Shell routing.</param>
    /// <param name="lifetime">The <see cref="ServiceLifetime"/> by which the View and ViewModel will be registered in <see cref="IServiceCollection"/>. Defaults to <see cref="ServiceLifetime.Transient"/></param>
    /// <returns>A reference to this instance after the operation has completed.</returns>
    public static IServiceCollection AddViewAndViewModelWithShellRoute<TView, TViewModel>(this IServiceCollection services, string route, ServiceLifetime lifetime = ServiceLifetime.Transient)
        where TView : Microsoft.Maui.Controls.Page
        where TViewModel : INotifyPropertyChanged
    {
        Routing.RegisterRoute(route, typeof(TView));
        return services.AddViewAndViewModel<TView, TViewModel>(lifetime);
    }
}
```

This example illustrates how the extension methods in Option 1 could be used within `MauiProgram`

```cs
public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp.CreateBuilder();
        builder
            .UseMauiApp<App>()
            .UseMauiCommunityToolkit()
            .ConfigureFonts(fonts =>
            {
                fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
            })
            .Services
                // Adds HomePage and HomePageViewModel with ServiceLifetime.Transient (defualt value)
                .AddViewAndViewModel<HomePage, HomePageViewModel>()
                // Adds HomePage and HomePageViewModel with ServiceLifetime.Transient
                .AddViewAndViewModel<HomePage, HomePageViewModel>(ServiceLifetime.Singleton)
                // Adds HomePage and HomePageViewModel with ServiceLifetime.Transient (defualt value) and Shell route: "HomePage"
                .AddViewAndViewModelWithShellRoute<HomePage, HomePageViewModel>()
                // Adds HomePage and HomePageViewModel with ServiceLifetime.Transient (defualt value) and Shell route: "MyCustomRoute"
                .AddViewAndViewModelWithShellRoute<HomePage, HomePageViewModel>("MyCustomRoute")
                // Adds HomePage and HomePageViewModel with ServiceLifetime.Singleton and Shell route: "MyCustomRoute"
                .AddViewAndViewModelWithShellRoute<HomePage, HomePageViewModel>("MyCustomRoute", ServiceLifetime.Singleton);

        return builder.Build();
    }
}
```

**Comment by brminnick** [comment]
Thanks @rjygraham for this incredible write up! Top notch work 💯 👏 

My vote is for `Option 1`, above. Almost every time, a `ContentPage` will be added as a Transient and, as a best practice, _should_ use be added as a Transient. `Option 1` covers this best practice as the default case.

Here's a couple thoughts I had:

1. (Non-shell) Replace `TView : VisualElement` with `TView : BindableObject`
    - The [`BindingContext` property lives in the `BindableObject` class](https://github.com/dotnet/maui/blob/4aaa996db6506844836036a5d115f2220cf7cdd6/src/Controls/src/Core/BindableObject.cs#L41-L45)
    - Both `Page`, and `VisualElement` inherit from `BindableObject`
    - This would allow us to cover _any_ possible view/viewmodel combination  
2. (Shell) Let's remove the default route API for `AddViewAndViewModelWithShellRoute`
    - I.e. Let's remove this API: 
      ```cs
       public static IServiceCollection AddViewAndViewModelWithShellRoute<TView, TViewModel>(this IServiceCollection services, ServiceLifetime lifetime = ServiceLifetime.Transient)
      ```
    - This API may cause more problems than solutions for folks consuming the API
      - Folks unfamiliar with Shell may use this API and be confused why pages don't navigate as they expected
    - Let's let users use the other API (where they're forced to provide `string route`) for now, then we can let them submit ideas on how to auto-implement routes
      - I could see a would where we create additional APIs like these (but for now, let's get community feedback and add these in a future release):
      ```cs
      public static IServiceCollection AddViewAndViewModelWithShellRoute<TView, TViewModel>(this IServiceCollection services, TView navigateFromPage, ServiceLifetime lifetime = ServiceLifetime.Transient)
      ```
3. (Shell) Could we also add `TView` support for `DataTemplate`? 
    - **Caveat:** I don't think this is required for this first Proposal and we can always add it later
    - `ShellContent` doesn't actually require a `Page`, rather it accepts both [`object Content` and `DataTemplate ContentTemplate`](https://github.com/dotnet/maui/blob/4aaa996db6506844836036a5d115f2220cf7cdd6/src/Controls/src/Core/Shell/ShellContent.cs#L37-L48)
      - I think constraining `TView` to `object` is too generic, so I'd like to continue using `TView : Page`
        - Maybe the community will disagree and we can always broaden the constraint from `Page` to `object` without introducing a breaking change in a later release
    - Maybe the solution is to add another method like this?
      ```cs
      public static AddDataTemplateAndViewModelWithShellRoute<TDataTemplate, TViewModel>() where TDataTemplate : DataTemplate 
                                                                where TViewModel : INotifyPropertyChanged
      ```

**Comment by bijington** [comment]
Thanks @rjygraham this is a great write up! I think @brminnick has covered the topic pretty well. My only differing opinion would be to provide no default value for `ServiceLifetime`, this might just be me wanting to force the developer to really think about what they want. Of course in this scenario a singleton is very rarely a good idea.

**Comment by rjygraham** [comment]
Not gonna lie, I included Option 1 only for completeness and was hoping we'd lean towards Option 2... 😜

There reasons I personally prefer Option 2 are:
- The syntax aligns with the existing `AddSingleton`, `AddTransient`, `AddScoped` extension methods of `IServiceCollection` 
- We may determine that `ServiceLifetime.Scoped` is irrelevant and therefore we can guide new developers by providing methods only for `Transient` and `Singleton`
- Although extremely unlikely, Option 2 shields us from the edge case pointed out by @brminnick of a new `ServiceLifetime` value being added which would go unhandled

If we feel the syntax for Option 2 is too verbose, we could consider shortening it to something like the following (at the risk of being slightly less discoverable):

```cs
public static class IServiceCollectionExtensions
{
	/// <summary>
	/// Adds a Page or View of the type specified in <typeparamref name="TView"/> and a ViewModel
	/// of the type specified in <typeparamref name="TViewModel"/> to the specified
	/// <see cref="IServiceCollection"/> with <see cref="ServiceLifetime.Transient"/> lifetime.
	/// </summary>
	/// <typeparam name="TView">The type of the View to add. Constrained to <see cref="Microsoft.Maui.Controls.VisualElement"/></typeparam>
	/// <typeparam name="TViewModel">The type of the ViewModel to add. Constrained to <see cref="INotifyPropertyChanged"/></typeparam>
	/// <param name="services">The <see cref="IServiceCollection"/> to add the service to.</param>
	/// <returns>A reference to this instance after the operation has completed.</returns>
	public static IServiceCollection AddTransient<TView, TViewModel>(this IServiceCollection services)
		where TView : Microsoft.Maui.Controls.VisualElement
		where TViewModel : class, INotifyPropertyChanged
	{
		services.AddTransient<TViewModel>();
		return services.AddTransient<TView>();
	}

	/// <summary>
	/// Adds a Page of the type specified in <typeparamref name="TView"/> and a ViewModel
	/// of the type specified in <typeparamref name="TViewModel"/> to the specified
	/// <see cref="IServiceCollection"/> with <see cref="ServiceLifetime.Transient"/> lifetime
	/// and registers a MAUI Shell route in <see cref="Routing"/> using <typeparamref name = "TView" />
	/// type name as the route.
	/// </summary>
	/// <typeparam name="TView">The type of the View to add. Constrained to <see cref="Microsoft.Maui.Controls.Page"/></typeparam>
	/// <typeparam name="TViewModel">The type of the ViewModel to add. Constrained to <see cref="INotifyPropertyChanged"/></typeparam>
	/// <param name="services">The <see cref="IServiceCollection"/> to add the service to.</param>
	/// <returns>A reference to this instance after the operation has completed.</returns>
	public static IServiceCollection AddTransientWithShellRoute<TView, TViewModel>(this IServiceCollection services)
		where TView : Microsoft.Maui.Controls.Page
		where TViewModel : class, INotifyPropertyChanged
	{
		return services.AddTransientWithShellRoute<TView, TViewModel>(typeof(TView).Name);
	}

	/// <summary>
	/// Adds a Page of the type specified in <typeparamref name="TView"/> and a ViewModel
	/// of the type specified in <typeparamref name="TViewModel"/> to the specified
	/// <see cref="IServiceCollection"/> with <see cref="ServiceLifetime.Transient"/> lifetime
	/// and registers a MAUI Shell route in <see cref="Routing"/> using the value of <paramref name="route"/> as the route.
	/// </summary>
	/// <typeparam name="TView">The type of the View to add. Constrained to <see cref="Microsoft.Maui.Controls.Page"/></typeparam>
	/// <typeparam name="TViewModel">The type of the ViewModel to add. Constrained to <see cref="INotifyPropertyChanged"/></typeparam>
	/// <param name="services">The <see cref="IServiceCollection"/> to add the service to.</param>
	/// <returns>A reference to this instance after the operation has completed.</returns>
	public static IServiceCollection AddTransientWithShellRoute<TView, TViewModel>(this IServiceCollection services, string route)
		where TView : Microsoft.Maui.Controls.Page
		where TViewModel : class, INotifyPropertyChanged
	{
		Routing.RegisterRoute(route, typeof(TView));
		return services.AddTransient<TView, TViewModel>();
	}
}
```
@brminnick for non-Shell method(s), I agree `TView : VisualElement` should be `TView : BindableObject` given that is where `BindingContext` is defined.

For Shell method(s), `DataTemplate` doesn't have `BindingContext` so I'm having difficulty envisioning how that extension method would be used if we were to change the constraint to `DataTemplate`. Additionally, since there is no inheritance relationship between `BindableObject` and `DataTemplate`, the Shell method(s) wouldn't be able to leverage the non-Shell method and would have to instead register the `TView` and `TViewModel` itself:

```cs
public static class IServiceCollectionExtensions
{
	public static IServiceCollection AddTransientWithShellRoute<TView, TViewModel>(this IServiceCollection services, string route)
		where TView : Microsoft.Maui.Controls.DataTemplate
		where TViewModel : class, INotifyPropertyChanged
	{
		Routing.RegisterRoute(route, typeof(TView));
		services.AddTransient<TViewModel>();
                return services.AddTransient<TView>();
	}
}
```

Instead of existing:

```cs
public static class IServiceCollectionExtensions
{
	public static IServiceCollection AddTransientWithShellRoute<TView, TViewModel>(this IServiceCollection services, string route)
		where TView : Microsoft.Maui.Controls.Page
		where TViewModel : class, INotifyPropertyChanged
	{
		Routing.RegisterRoute(route, typeof(TView));
		return services.AddTransient<TView, TViewModel>();
	}
}
```

Finally, not trying to be difficult, but I disagree with removing the Shell method registering the route value as the View's Type name (e.g. ` AddTransientWithShellRoute<TView, TViewModel>(this IServiceCollection services)`). I believe this method would be beneficial for simple/flat applications as well as "auxiliary" pages you don't want to appear in Shell Flyout, Tabs, etc. For example, I use `Routing.RegisterRoute()` for pages that are part of my welcome, registration, and login flows. But I've only started using Shell with .NET MAUI and it's entirely possible I'm doing it completely wrong... 🤷‍♂️

Look forward to everyone's thoughts!

**Comment by brminnick** [comment]
I'll Champion this Proposal and bring it up for an Approval vote at our stand up on Thursday. 

We'll see how the team aligns on the options + the discussion here and move forward with the majority vote 👍

**Comment by rjygraham** [comment]
Hey @brminnick, I just wanted to follow up on this and provide some thoughts below on the questions raised during the July 2022 community standup.

@jfversluis
- [`ServiceLifetime`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.servicelifetime?view=dotnet-plat-ext-6.0) is defined in `Microsoft.Extensions.DependencyInjection`. Thankfully it seems like everyone (including community) preferred Option 2 so this doesn't even matter.
- Helper method not setting ViewModel to View `BindingContext`.
  - Agree this is a pitfall. IMO, auto-wireup of View/ViewModel is something that should be baked into MAUI proper. Perhaps we can start with XML docs for v1, implement an analyzer for v2, and eventually get the auto-wireup implemented in MAUI?

@pictos
- Add overload method for `Routing.RegisterRoute(string route, RouteFactory factory)`. Agreed this overload method should be available as well.
- `BindableObject` as constraint for registering Views and ViewModels. As mentioned by @brminnick the non-Shell methods would use `BindableObject` as the TView constraint to allow for the widest usage possible.

@VladislavAntonyuk 
- Different lifetimes for Views and ViewModels. I can't think of a use-case where this would apply, but if it did come up, the developer would just have to fall back to registering the View and ViewModel separately as they do today.

Semi-related to the scenario @VladislavAntonyuk mentioned is what happens if there are multiple Views/Pages that use the same ViewModel? I can envision this in scenarios where a View is purpose-built for Desktop/TV (Mac/Windows/Tizen) and another View is created for Mobile.

The original intent of these helper extension methods iso make developers' lives easier within the 80/20 rule. There's no way we'll be able to cover 100% of the real-life scenarios, but I think we can capture at least 80% of the use-cases and that seems like a "win" to me.

Look forward to everyone's thoughts and guidance for moving forward (or not)!

**Comment by brminnick** [comment]
Thanks so much @rjygraham! 

I've updated the details of the Proposal above to reflect the [notes above](https://github.com/CommunityToolkit/Maui/issues/479#issuecomment-1183305815) from our monthly standup.

Let's keep the scope small for this Proposal, saving the `Different lifetimes for Views and ViewModels` and `Multiple Views/Pages that use the same ViewModel` features for a future Proposal.

I'll now reach out the maintainers asking for a vote for approval to move forward with implementing this Proposal!

**Comment by bijington** [comment]
Gets my vote 👍

**Comment by brminnick** [comment]
I too vote to approve this Proposal ✅

**Comment by pictos** [comment]
I approve this feature ✅

**Comment by VladislavAntonyuk** [comment]
I approve it. The only suggestion is to simplify the name to AddSingleton and AddTransient

**Comment by brminnick** [comment]
We've reached the minimum threshold of 50% approval and you are now clear to move forward and implement this Proposal, @rjygraham! 🎉 

I've moved this to the [`Proposal Approved Column on our Project Board`](https://github.com/CommunityToolkit/Maui/projects/1#column-16085863), added the `approved` tag and assigned it to @rjygraham.

**Comment by rjygraham** [comment]
@brminnick @bijington @pictos @VladislavAntonyuk - Is there a preference on a mocking library (Moq, NSubstitute, etc) for testing? Looks like MAUI proper uses NSubstitute, so I'm inclined to lean towards that.

Rationale: I need to mock IServiceCollection to verify the various AddTransient, AddSingleton, AddScoped methods are invoked. Alternatively, I can create a dummy class that implements IServiceCollection, but that feels... dirty.

**Comment by brminnick** [comment]
You shouldn't need to mock `IServiceCollection` because `CommunityToolkit.Maui.UnitTests` implements .NET MAUI (`<UseMaui>true</UseMaui>`) which includes `IServiceCollection`

**Comment by rjygraham** [comment]
Yep, I'll just new up `ServiceCollection` and roll with that! Thanks!

**Comment by brminnick** [comment]
I recommend using `var services = MauiApp.CreateBuilder().Services` To access .NET MAUI’s implementation of `IServiceCollection`. 

Here’s an example from the Sample App:
https://github.com/CommunityToolkit/Maui/blob/38ec66fbb102c51aab6ad7a0a00edbed5531eaa2/samples/CommunityToolkit.Maui.Sample/MauiProgram.cs#L23
