### ISSUE TITLE
[Proposal] ProgressBar Animation Behavior

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#48]
# ProgressBarAnimationBehavior

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Documentation
* [x] Sample

## Summary
[summary]: #summary

A behavior that animates a ProgressBar based on `double AnimateProgress`.

## Detailed Design
[design]: #detailed-design

### ProgressBarAnimationBehavior.shared.cs

```cs
public class ProgressBarAnimationBehavior : BaseBehavior<ProgressBar>
{
    public static readonly BindableProperty ProgressProperty;
    public static readonly BindableProperty LengthProperty;
    public static readonly BindableProperty EasingProperty;

    public double Progress { get; set; }
    public uint Length { get; set; }
    public Easing Easing { get; set; }
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<ProgressBar>
    <ProgressBarBehaviors>
        <toolkit: ProgressBarAnimationBehavior
            AnimateProgress = { Binding ProgressValue}
        />
    </ProgressBar.Behaviors>
</ProgressBar>
```

### C# Usage

```cs
var behavior = new ProgressBarAnimationBehavior();
behavior.SetBinding(ProgressBarAnimationBehavior.AnimateProgressProperty, nameof(ViewModel.ProgressValue);

var progressBar = new ProgressBar();
phoneEntry.Behaviors.Add(behavior);
```

**Comment by CliffAgius** [comment]
Happy to pick up the docs for this one.

I notice this wasn't in XCT or at least the docs anyway.

**Comment by bijington** [comment]
Awesome thanks @CliffAgius. It's all yours! Let me know if you have any questions on it

**Comment by CliffAgius** [comment]
My only point is that it's difficult to see what has been picked up for docs as this repo has things still open which I know are done as I can see the Docs in the Docs Repo.

Not sure if there is a better way to link the two so we know what needs doing maybe having issues over on the Docs Repo so we know what is left to be done for example.

**Comment by brminnick** [comment]
> I notice this wasn't in XCT or at least the docs anyway.

There are quite a few docs missing from Xamarin.CommunityToolkit. I took inventory in December, noting all of the features missing documentation, and `ProgressBarAnimationBehavior` is indeed missing:
https://github.com/xamarin/XamarinCommunityToolkit/wiki/Features-List

My goal for the .NET MAUI Community Toolkit is to avoid that by improving the [New Feature Submission process](https://github.com/CommunityToolkit/Maui#submitting-a-new-feature) to avoid missing documentation.

**Comment by bijington** [comment]
@CliffAgius oh really? I can take a look at tidy up any issues if they are still open. The general approach will change once we hit GA. We had to wait for the docs repo to be set up so allowed PRs to be merged without docs however going forward a PR will require the docs so they can be merged at the same time

**Comment by CliffAgius** [comment]
Before I write the docs for this one I wanted to check as there is already a C# method for Animating the progress bar which is here:

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/progressbar#animate-a-progressbar

So I am wondering should we highlight this in the MCT docs that instead of using the C# & C# Mark-up when doing it from C# land it's better to use the direct built in animation rather then extra code of the behavior?

The issue I see with this is that it breaks from the way all the pages currently look but it seems wrong to promote and show doing it with this behavior when it's not needed.

Unless I am missing something!

**Comment by bijington** [comment]
> Before I write the docs for this one I wanted to check as there is already a C# method for Animating the progress bar which is here:
> 
> https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/progressbar#animate-a-progressbar
> 
> So I am wondering should we highlight this in the MCT docs that instead of using the C# & C# Mark-up when doing it from C# land it's better to use the direct built in animation rather then extra code of the behavior?
> 
> The issue I see with this is that it breaks from the way all the pages currently look but it seems wrong to promote and show doing it with this behavior when it's not needed.
> 
> Unless I am missing something!

I think there is still value is showing the C# and C# Markup examples as we currently do. The `ProgressTo` method only works if you have direct access to the ProgressBar (basically in code behind). Our examples typically still make use of the MVVM architecture where we bind. In this scenario a developer would still want to use the behavior so they can trigger it from their View Model.

By all means include a link to that page to show how it is implemented under the hood if you like.

**Comment by CliffAgius** [comment]
Ok sounds good I will add it into the Doc anyway just to highlight it as you suggest.

**Comment by bijington** [comment]
Awesome thanks @CliffAgius we really appreciate the effort. I hope you get to enjoy some good bank holiday too 😃

**Comment by CliffAgius** [comment]
I'm heading to Seattle so lots of time to write some docs. 😜

**Comment by bijington** [comment]
> I'm heading to Seattle so lots of time to write some docs. 😜

Or sleep or watch a movie or two. Definitely appreciate the effort! Safe flights!

**Comment by CliffAgius** [comment]
Doc's complete awaiting checks etc.

https://github.com/MicrosoftDocs/CommunityToolkit/pull/84

**Comment by bijington** [comment]
Thanks @CliffAgius
