### ISSUE TITLE
[Bug] Anchor cause crash when using Popup on MacOS

### ISSUE THREAD

**Issue by arkadym** [CommunityToolkit/Maui#485]
Created simple app from VS 2022 on Mac OS with AppShel and MainPage
Added ComminutyToolkit.Maui 1.0
Created Popup control
On MainPage replace counter button click handler with
```
var popup = new Controls.Popup1();
popup.Anchor = CounterBtn;
this.ShowPopup(popup);
```

Add UseMauiCommunityToolkit() to MainProgram.cs

Run app - click on 'Click me' button - app will crash (that is with 6.0.400 maui)

Goto App.xaml.cs and replace
`MainPage = new AppShell();`
with `MainPage = new MainPage();`

Run app - click on 'Click me' button - app will work as expected

### Stack Trace

see attached PopupCrash.txt

### Link to Reproduction Sample

see attached

[MauiPopup1.zip](https://github.com/CommunityToolkit/Maui/files/9038406/MauiPopup1.zip)
[PopupCrash.txt](https://github.com/CommunityToolkit/Maui/files/9038408/PopupCrash.txt)
![Screenshot 2022-07-04 at 17 00 48](https://user-images.githubusercontent.com/7422012/177132225-ae2cbfed-ff19-4617-9c7b-e70aa2baffe0.png)

**Comment by pictos** [comment]
@arkadym thanks for the report we'll take a look at this after our next release. I did a lot of fixes on popup in apple's platform, so maybe this's already fixed. If not we will solve it (:

**Comment by arkadym** [comment]
I updated MAUI to latest SR3 (419) and Community Toolkit to 1.1.0 - there is no more crash, it works correct now. Can close issue.
