### ISSUE TITLE
[Bug] Popup crashing on WinUI & Android

### ISSUE THREAD

**Issue by nickidentivue** [CommunityToolkit/Maui#489]
### Description

Adding the C#  example popup from the docs to a brand new MAUI project crashes WinUI and Android projects (unable to test iOS). 

I feel like I must be doing something wrong for such basic functionality to be broken but I can't see anything obvious?

### Stack Trace

Exception thrown: 'System.InvalidOperationException' in CommunityToolkit.Maui.dll. Could not locate MauiContext.
The program '[24368] TestPopup.exe' has exited with code 4294967295 (0xffffffff).

### Link to Reproduction Sample

https://github.com/1888games/MauiPopupTest

### Steps to Reproduce

1. Create new MAUI project
2. Add Community Toolkit via Nuget.
3. Add .UseMauiCommunityToolkitCore() to builder.
4. Add basic popup to MainPage and call this.ShowPopup().

### Expected Behavior

Popup shown on screen.

### Actual Behavior

App crashes.

### Basic Information

- Version with issue: 1.00 (Maui 6.0.400)
- Last known good version: n/a
- IDE: Visual Studio 2022 Preview
- Platform Target Frameworks: 

  - WinUI:  19041
  - Android 21.0

**Comment by VladislavAntonyuk** [comment]
1. You haven't initialized toolkit. Instead of UseMauiCommunityToolkitCore you have to call UseMauiCommunityToolkit
2. it's not the right place to call Popup. because you can display  popup only after page is displayed.

**Comment by bijington** [comment]
> Ah thanks....the Core readme was the one that flashed up after installing through Nuget so I used that. In the real app I wasn't showing within the page constructor, just being lazy for the purposes of the test....

Did you add the Core package to your project as well as the other one? If so you don't need to add it, if not then we need to consider removing the readme file for it to avoid some confusion

**Comment by nickidentivue** [comment]
> > Ah thanks....the Core readme was the one that flashed up after installing through Nuget so I used that. In the real app I wasn't showing within the page constructor, just being lazy for the purposes of the test....
> 
> Did you add the Core package to your project as well as the other one? If so you don't need to add it, if not then we need to consider removing the readme file for it to avoid some confusion

Yes I added it, I had assumed it followed a similar structure to something like Syncfusion where you have to install the Core library that all the others require first.

**Comment by bijington** [comment]
> > > Ah thanks....the Core readme was the one that flashed up after installing through Nuget so I used that. In the real app I wasn't showing within the page constructor, just being lazy for the purposes of the test....
> 
> > 
> 
> > Did you add the Core package to your project as well as the other one? If so you don't need to add it, if not then we need to consider removing the readme file for it to avoid some confusion
> 
> 
> 
> Yes I added it, I had assumed it followed a similar structure to something like Syncfusion where you have to install the Core library that all the others require first.

Oh I see. Our package depends on Core so it pulls it in for you. Perhaps we need to make this part clear somewhere. Out of interest how did you come into using the package? Was it a video, the docs or something else?

**Comment by nickidentivue** [comment]
We are porting a very large app from XF that uses a lot of Syncfusion controls, rather than wait a year for their MAUI library to be ready we are seeing what can be done using only built-in controls, a lot of which have been added since the Xamarin project started in 2018. 

I was looking for a way to replace SfPopup which we use all over the place, and found this on the Microsoft docs pages.
