### ISSUE TITLE
[Bug] CI Pipeline Does Not Fail when Vulnerable Dependencies Found

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#493]
### Description

Our Azure DevOps CI Pipeline current checks for security vulnerabilities in our dependencies:
https://github.com/CommunityToolkit/Maui/blob/38ec66fbb102c51aab6ad7a0a00edbed5531eaa2/azure-pipelines.yml#L103-L109

This step is currently reporting 3 vulnerable packages, however, the `Check Dependencies` step continues to pass (green):
https://dev.azure.com/dotnet/CommunityToolkit/_build/results?buildId=74857&view=logs&j=792604ca-8f43-5a41-d895-10758edbd758&t=9cdee477-4d1a-5acd-94fa-d5e164beb4af&l=18
[![](https://user-images.githubusercontent.com/13558917/179091351-c4cbfb3e-9e14-4f1e-b9f7-d09fd321e785.png)](https://dev.azure.com/dotnet/CommunityToolkit/_build/results?buildId=74857&view=logs&j=792604ca-8f43-5a41-d895-10758edbd758&t=9cdee477-4d1a-5acd-94fa-d5e164beb4af&l=18)

### Stack Trace

N/A

### Link to Reproduction Sample

N/A

### Expected Behavior

The `Check Dependencies` step should fail when it detects any vulnerable dependency

### Actual Behavior

The `Check Dependencies` step passes despite detecting any vulnerable dependency

**Comment by VladislavAntonyuk** [comment]
There is an open issue for it: https://github.com/NuGet/Home/issues/11315
