### ISSUE TITLE
[Bug] Popup color not applied on ios

### ISSUE THREAD

**Issue by yurkinh** [CommunityToolkit/Maui#499]
### Description
Setting Color on Popup page is ignored on iOS.
While it works fine on Android

### Link to Reproduction Sample

[Sample.zip](https://github.com/CommunityToolkit/Maui/files/9141976/Sample.zip)

### Steps to Reproduce

1. Run the attached sample on ios
2. Press the button  "Show" Popup
3. Notice that popup background is not Transparent

### Expected Behavior
Popup background is Transparent

### Actual Behavior
Popup background is default grey (on ios)

- Version with issue:
- Platform Target Frameworks: 
  - iOS:  
### Reproduction imagery
<p float="left">
<img src="https://user-images.githubusercontent.com/17849938/179776661-cff78564-6c8f-44e1-9cde-014340736d87.png" width="40%" height="40%">
<img src="https://user-images.githubusercontent.com/17849938/179776829-3e2605dd-f238-4271-bac9-1d5211501e57.png" width="40%" height="40%">
</p>

**Comment by pictos** [comment]
@yurkinh I believe this is the normal behavior for iOS. My first test was changing the Popup.Color to Red and that work as expected as you can see in the screenshot below:
![Screen Shot 2022-07-19 at 20 57 41](https://user-images.githubusercontent.com/20712372/179867686-a3917668-71cb-4d87-9463-66a6089a4cc0.png)

Second I debug the code to see if for some reason the `Colors.Transparent` were converted wrong, and looks like that isn't the case as well. So I would say this is the normal behavior on Apple's platform.

If you don't want that extra space, don't use the `Size` property, that way the Popup you measure itself, doing that, and some changes to your layout you will be able to not have that extra space.

And remember to use the Vertical/HorizontalOptions = Center if you want the Popup to be centered on the screen.

Not sure if you reported the error, but I saw a NRE on `DrawingView` when I press the `Done` button.

**Comment by yurkinh** [comment]
Hi @pictos ,
Thanks for the explanation regarding popup background color.
Yes, I have reported NRE [here](https://github.com/CommunityToolkit/Maui/issues/500). 
I just made one sample for two issues)

**Comment by MGohil** [comment]
@pictos 

Does this mean that I will not be able to achieve the similar result in iOS as like in Android in below screenshot?

Is there any way to prevent that grey background and keep the content attached to the bottom and touching to both (Left and Right) edges in iOS?

![popup-bug](https://user-images.githubusercontent.com/16605284/203773464-37134cec-b75c-4f85-9255-28637f7cb96a.png)
