### ISSUE TITLE
[Bug] Type Converter Error when running Popup on iOS without debugging.

### ISSUE THREAD

**Issue by DanielMuhlig** [CommunityToolkit/Maui#514]
### Description

Eg. setting popup.Size = new Size(640, 480) works fine when running the app on an iPad in debug mode from Visual Studio, but crashes with error "Position 5:75. Type converter failed: Cannot convert "" into Microsoft.Maui.Graphics.Size" when starting app directly from the iPad (same error even if not setting the Size property on the popup)!

This may be Maui/compiler related and not CommunityToolkit?

- CommunityToolkit.Maui 1.1.0 and 1.2.0
- Last known good version: n/a
- IDE: Visual Studio 17.3.0 preview 4.0
- Platform Target Frameworks: net6.0-ios
  - iOS:  14.2
  - Android: n/a
  - UWP:  n/a
- Android Support Library Version: n/a
- Nuget Packages: 
    - CommunityToolkit.Maui 1.2.0
    - CommunityToolkit.Mvvm8.0.0-preview4
    - Microsoft.Maui.Dependencies 6.0.419
    - Microsoft.Maui.Extensions 6.0.419
    - Microsoft.Windows.SDK.BuildTools 10.0.22000.194
    - System.Runtime.InteropServices.NFloat.Internal 6.0.1
- Affected Devices: iPad (2021, OS 15.5)

**Comment by VladislavAntonyuk** [comment]
could you please attach a small repro?

**Comment by pictos** [comment]
Closing this issue because we don't get any response.
