### ISSUE TITLE
[Proposal] `Color`-To-`string` Converters

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#54]
# ColorToStringConverter

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Documentation
* [x] Sample

## Summary
[summary]: #summary

Converts a `Color` to its associated `string`, e.g. RGB, RGBA, HEX, CMYK, etc.

## Detailed Design
[design]: #detailed-design

### ColorToStringConverter.shared.cs

```cs
public class ColorToRgbStringConverter : BaseConverterOneWay<Color, string>;
public class ColorToRgbaStringConverter : BaseConverterOneWay<Color, string>;
public class ColorToHexRgbStringConverter : BaseConverter<Color, string>;
public class ColorToHexRgbaStringConverter : BaseConverter<Color, string>;
public class ColorToCmykStringConverter : BaseConverterOneWay<Color, string>;
public class ColorToCmykaStringConverter : BaseConverterOneWay<Color, string>;
public class ColorToHslStringConverter : BaseConverterOneWay<Color, string>;
public class ColorToHslaStringConverter : BaseConverterOneWay<Color, string>;
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
             x:Class="MyLittleApp.MainPage">
    <ContentPage.Resources>
         <ResourceDictionary>
             <toolkit: ColorToRgbStringConverter x:Key="ColorToRgbStringConverter" />
         </ResourceDictionary>
    </ContentPage.Resources>

    <StackLayout>

        <Label Text="{Binding LabelTextColor, Converter={StaticResource ColorToRgbStringConverter}}" />

    </StackLayout>
</ContentPage>
```

### C# Usage

```cs
class MyPage : ContentPage
{
  public MyPage()
  {
    Content = new Label().Bind(Image.TextProperty, named(ViewModel.LabelTextColor), converter: new ColorToRgbStringConverter());
  }
}
```

**Comment by juansturla** [comment]
Hi! 
I will try to create the sample for this

**Comment by stefanbogaard86** [comment]
Hello @brminnick, I can write unittests for this one.

**Comment by brminnick** [comment]
Fantastic! I recommend submitting two separate PRs because `dotnet test` support is coming in the next .NET MAUI release. Unit Testing support was recently added in this PR: https://github.com/dotnet/maui/pull/3017

Right now, .NET MAUI projects throw this error when running `dotnet test`: 
> Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.Maui.Core', version '**FromWorkload**' (x64) was not found.
