### ISSUE TITLE
[Bug] Popup transparent color is white on iOS

### ISSUE THREAD

**Issue by HobDev** [CommunityToolkit/Maui#548]
### Description
The Popup color is set to Transparent. But it still have white background on iOS.

### Link to Reproduction Sample
https://github.com/HobDev/MauiBugs/tree/PopupColorIssue

### Steps to Reproduce

1. Run the app on iOS . The popup will run for 8 seconds with white background. But the Color property is set to Transparent. 

### Basic Information
- Version with issue: 1.2.0
- Last known good version: Unknown
- IDE: 17.3.0 
- Platform Target Frameworks: 
  - iOS:  15.12.0.2
- Affected Devices: iOS

### Workaround
 No workround

**Comment by pictos** [comment]
@HobDev thanks for the report, but this is how iOS handles that, as you can see [here](https://github.com/CommunityToolkit/Maui/issues/499#issuecomment-1189662437).

Feel free to re-open this issue if you find some apple docs that say the opposite.
