### ISSUE TITLE
[Bug] ShouldDismissKeyboardAutomatically Not Working 

### ISSUE THREAD

**Issue by LeanTolo** [CommunityToolkit/Maui#549]
### Description

When running the project on Android the keyboard does not close automatically

### Relevant log output
No response

### Steps to Reproduce

1. Create a blank project 
2. Add `xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"` 
3. Add `<SearchBar Placeholder="Test Keyboard" 
                                HorizontalTextAlignment="Center"
                                HorizontalOptions="Center"
                                x:Name="searchBar">
                <SearchBar.Behaviors>
                    <toolkit:UserStoppedTypingBehavior 
                                    ShouldDismissKeyboardAutomatically="True"
                                    StoppedTypingTimeThreshold="1000" />
                </SearchBar.Behaviors>
            </SearchBar>`
          On Main page  
4. Expect keyboard closes automatically

### Expected Behavior

Keyboard close Automatically after user stop type

### Actual Behavior

Keyboard Not Close after user stop type

### Version with bug
Android 12.0 - API 31 // Android 7.0 -API 24

### Last version that worked well
Unknown/Other

### Affected 
Android

**Comment by kphillpotts** [comment]
Thanks for the reporting @LeanTolo. I reproduced this on Android API 30.
I believe this is related to https://github.com/dotnet/maui/issues/6933

**Comment by bijington** [comment]
> Thanks for the reporting @LeanTolo. I reproduced this on Android API 30.
> I believe this is related to [dotnet/maui#6933](https://github.com/dotnet/maui/issues/6933)

I see that the linked issue has now been resolved. Also testing this on an Android 30 device I can confirm that this issue has now been resolved
