### ISSUE TITLE
[Bug] Fatal Crash using UniformItemsLayout on Windows

### ISSUE THREAD

**Issue by Cywizz** [CommunityToolkit/Maui#550]
### Description

On Windows, using a UniformItemsLayout and setting a margin and its VerticalOptions = "StartAndExpand" causes a crash with error: 
Exception = {"Element not found. (0x80070490)"}

### Stack Trace

>	MauiApp2.dll!MauiApp2.WinUI.App.InitializeComponent.AnonymousMethod__3_1(object sender, Microsoft.UI.Xaml.UnhandledExceptionEventArgs e) Line 68	C#

### Link to Reproduction Sample

Easy to reproduce, see below

### Steps to Reproduce

1. Create brand new MAUI app 
2. Add latest MCT nuget release 1.2.0
3. Hookup the toolkit in the MauiProgram
4. In MainPage.xaml add the reference to mct and replace the ScrollView root control with the UniformItemsLayout control
5. Set a Margin = 20 and VerticalOptions = StartAndExpand for the UniformItemsLayout control
6. Run app for Windows...crashes

### Expected Behavior
Should not crash

### Actual Behavior
Crashes with error

### Basic Information
- Version with issue: MCT: 1.2.0 .Net MAUI: latest Service release 4
- Last known good version: Unknown (believe previous 1.1 was fine)
- IDE: VS 2022 17.4.0 Preview 1.0
- Platform Target Frameworks:
  - net6.0-windows10.0.19041.0 
- Nuget Packages: CommunityToolkit.Maui v1.2.0
- Affected Devices:
ONLY Windows. Android is fine (Have not tested with iOS yet)
### Workaround
Do not specify Margin and VerticalOptions

### Reproduction imagery
N/A

**Comment by VladislavAntonyuk** [comment]
It should be already fixed by https://github.com/CommunityToolkit/Maui/commit/0518cfb512894a39a43d69f337a44d56273989f1

**Comment by Cywizz** [comment]
Ok great, thanks @VladislavAntonyuk . I will check again upon new version release.

**Comment by VladislavAntonyuk** [comment]
@Cywizz Do you still have the issue?

**Comment by Cywizz** [comment]
@VladislavAntonyuk It seems to be fine now, thank you.
