### ISSUE TITLE
[Bug] MaskedBehavior does not allow writing on entry

### ISSUE THREAD

**Issue by LeanTolo** [CommunityToolkit/Maui#559]
### Description

When i try to implement `<toolkit:MaskedBehavior Mask="####-####-####-####" />` cannot write on entry

### Steps to Reproduce

1.  Create MAUI project and add maui toolkit
2. Add `xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"` on main page
3. Add `<Entry HorizontalOptions="FillAndExpand"
                       HorizontalTextAlignment="Center"
                       Keyboard="Numeric"
                   TextColor="Black">
                    <Entry.Behaviors>
                        <toolkit:MaskedBehavior Mask="####-####-####-####" />
                    </Entry.Behaviors>
                </Entry>`

### Expected Behavior

Write on the entry and get text masked

### Actual Behavior

Cannot write

### Basic Information

- Version with issue: 6.0.400
- Last known good version: - 
- IDE: VS Preview 17.4.0 Preview 1.0
- Platform Target Frameworks: 
  - Android: 13.0 - API 33
- Nuget Packages: CommunityToolkit.Maui 1.2.0

**Comment by IeuanWalker** [comment]
@LeanTolo the default unmasked character is `X`, so changing the `#` to `X` should work.

Or you can add the property `UnMaskedCharacter="A"` to the behavior

**Comment by LeanTolo** [comment]
> @LeanTolo the default unmasked character is `X`, so changing the `#` to `X` should work.
> 
> Or you can add the property `UnMaskedCharacter="#"` to the behavior

Changed # to X and it works! Thanks
