### ISSUE TITLE
[Proposal] DateTimeOffsetConverter

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#56]
# DateTimeOffsetConverter

* [x] Proposed
* [x] Prototype
* [x] Implementation: Not Started
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Documentation: Not Started
* [x] Sample

## Summary
[summary]: #summary

The `DateTimeOffsetConverter` is a converter that allows users to convert a `DateTimeOffset` to a `DateTime`. Sometimes a `DateTime` value is stored with the offset on a backend to allow for storing the timezone in which a `DateTime` originated from. Controls like the `Microsoft.Maui.Controls.DatePicker` only work with `DateTime`. This converter can be used in those scenarios.

## Detailed Design
[design]: #detailed-design

### DateTimeOffsetConverter.shared.cs

```cs
public class DateTimeOffsetConverter : ValueConverterExtension, IValueConverter
{
  public object Convert(object? value, Type targetType, object? parameter, System.Globalization.CultureInfo culture)=> value is DateTimeOffset dateTimeOffset
    ? dateTimeOffset.DateTime
    : throw new ArgumentException("Value is not a valid DateTimeOffset", nameof(value));

  public object ConvertBack(object? value, Type targetType, object? parameter, System.Globalization.CultureInfo culture) => value is DateTime dateTime
    ? dateTime.Kind switch
    {
	    DateTimeKind.Local => new DateTimeOffset(dateTime, DateTimeOffset.Now.Offset),
	    DateTimeKind.Utc => new DateTimeOffset(dateTime, DateTimeOffset.UtcNow.Offset),
	    _ => new DateTimeOffset(dateTime, TimeSpan.Zero),
    }
    : throw new ArgumentException("Value is not a valid DateTime", nameof(value));
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
             x:Class="MyLittleApp.MainPage">
    <ContentPage.Resources>
         <ResourceDictionary>
             <xct:DateTimeOffsetConverter x:Key="DateTimeOffsetConverter" />
         </ResourceDictionary>
    </ContentPage.Resources>

    <StackLayout>

        <Label Text="{Binding MyDateTimeOffset, Converter={StaticResource DateTimeOffsetConverter}}" />

    </StackLayout>
</ContentPage>
```

### C# Usage

```cs
class MyPage : ContentPage
{
  public MyPage()
  {
    Content = new StackLayout
    {
      Children = 
      {
          new Label().Bind(Label.TextProperty, nameof(ViewModel. MyDateTimeOffset), converter: new DateTimeOffsetConverter()),
      };
    }
  }
}

```

**Comment by CliffAgius** [comment]
Happy to pick up the Docs for this one as a starter before I dive in fully.  I want to get the process right my end.

Can someone assign me please and I will get it done this week.

**Comment by bijington** [comment]
Thanks @CliffAgius I have assigned you

**Comment by bijington** [comment]
@CliffAgius sorry to add to the work I have recently added an `index.md` file under the converters folder that contains a full table of all converters. If you can, could you add this converter to that file when you get round to writing the doc :)

**Comment by CliffAgius** [comment]
Not sure if I linked the Docs PR correctly but they have been merged over on the Docs repo.
@jfversluis @bijington can you let me know if I should have included a link to the proposal so that it closed this now that the Docs are done?

**Comment by jfversluis** [comment]
O shoot, I should be more aware of if the actual feature is merged as well. My bad. 😬 

I guess this one is done now though with the Docs also being complete?

**Comment by bijington** [comment]
@CliffAgius no you linked it fine. The proposal won't automatically be closed as a result of the docs PR being closed. We need to manually drag the issue over to the complete column in the Project board. This is down to the fact that a feature/proposal should not be merged before the docs are done. Don't worry I'll sort this proposal.

Thanks again for the contribution!
