### ISSUE TITLE
[Proposal] `enum`-To-`int` Converter

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#59]
# EnumToIntConverter

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Sample
* [x] Documentation: Started at https://github.com/MicrosoftDocs/CommunityToolkit/pull/57

## Summary
[summary]: #summary

The `EnumToIntConverter` is a converter that allows you to convert a standard `Enum` (extending int) to its underlying primitive `int` type. It is useful when binding a collection of values representing an enumeration type with default numbering to a control such as a `Picker`.

For localization purposes or due to other requirements, the `enum` values often need to be converted to a human-readable string. In this case, when the user selects a value, the resulting `SelectedIndex` can easily be converted to the underlying enum value without requiring additional work in the associated ViewModel.

## Detailed Design
[design]: #detailed-design

### EnumToIntConverter.shared.cs

```cs
public class EnumToIntConverter : ValueConverterExtension, IValueConverter
{
  public object Convert(object? value, Type? targetType, object? parameter, CultureInfo? culture) =>value is Enum ? System.Convert.ToInt32(value) : throw new ArgumentException($"{value?.GetType().Name} is not a valid enumeration type");

  public object ConvertBack(object? value, Type targetType, object? parameter, CultureInfo? culture) => value is int enumIntVal && Enum.IsDefined(targetType, enumIntVal) ? Enum.ToObject(targetType, enumIntVal) : throw new ArgumentException($"{value} is not valid for {targetType.Name}");
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<ContentPage
  x:Class="Xamarin.CommunityToolkit.Sample.Pages.Converters.EnumToIntConverterPage"
  xmlns="http://xamarin.com/schemas/2014/forms"
  xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
  xmlns:vm="clr-namespace:Xamarin.CommunityToolkit.Sample.ViewModels.Converters"
  xmlns:xct="http://xamarin.com/schemas/2020/toolkit">
  <ContentPage.BindingContext>
    <vm:EnumToIntConverterViewModel />
  </ContentPage.BindingContext>
  
  <StackLayout Padding="10,10" Spacing="10">
    <Picker ItemsSource="{Binding AllStates}" SelectedIndex="{Binding SelectedState, Converter={xct:EnumToIntConverter}}" />
    <Label Text="{Binding Path=SelectedState, Converter={xct:EnumToIntConverter}}" />
  </StackLayout>
</ContentPage>
```

### C# Usage

```cs
class MyPage : ContentPage
{
  public MyPage()
  {
    Content = new StackLayout
    {
      Children = 
      {
        new Picker()
          .Bind(Picker.ItemSource, nameof(ViewModel.AllStates)
          .Bind(Picker.SelectedIndex, nameof(ViewModel.SelectedState),

          new Label()
            .Bind(Label.TextPropoerty, nameof(ViewModel.SelectedState), converter: new EnumToIntConverter()),
      };
    }
  }
}
```

**Comment by brminnick** [comment]
Thanks @StevenHanquez! It's all yours 🙌

**Comment by CliffAgius** [comment]
Can someone add me to pickup the Docs for this one please.

**Comment by brminnick** [comment]
Thanks @CliffAgius! Done ✅

**Comment by CliffAgius** [comment]
Docs added with a PR - https://github.com/MicrosoftDocs/CommunityToolkit/pull/32
