### ISSUE TITLE
Enum was created in interface folder

### ISSUE THREAD

**Issue by MuhammadKasimov** [CommunityToolkit/Maui#597]
# [FEATURE_NAME]

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
  * [ ] iOS Support
  * [ ] Android Support
  * [ ] macOS Support
  * [ ] Windows Support
* [ ] Unit Tests: Not Started
* [ ] Sample: Not Started
* [ ] Documentation: Not Started

## Summary
[summary]: #summary

## Motivation
[motivation]: #motivation

## Detailed Design
[design]: #detailed-design

## Usage Syntax
[usage]: #usage-syntax

## Drawbacks
[drawbacks]: #drawbacks

## Alternatives
[alternatives]: #alternatives

## Unresolved Questions
[unresolved]: #unresolved-questions

**Comment by MuhammadKasimov** [comment]
Enum Toast duration wass created in interface folder and namespace naming was wrong

**Comment by MuhammadKasimov** [comment]
- [ ]

**Comment by MuhammadKasimov** [comment]
`namespace CommunityToolkit.Maui.Core.Enums;
/// <summary>
/// Toast duration
/// </summary>
public enum ToastDuration
{
	/// <summary>
	/// Displays Toast for a short time
	/// </summary>
	Short,

	/// <summary>
	/// Displays Toast for a long time
	/// </summary>
	Long
}`



all namespace in interface folder should be changed to 

`namespace CommunityToolkit.Maui.Core.Interfaces;`

**Comment by MuhammadKasimov** [comment]
```
namespace CommunityToolkit.Maui.Core.Enums;
public enum ToastDuration
{
Short,
Long
}
```
all namespace in interface folder should be changed to

`namespace CommunityToolkit.Maui.Core.Interfaces;`

**Comment by bijington** [comment]
@MuhammadKasimov Please stop. The updates to this is spamming us maintainers. This is also not a change that we want or need. 

If you would like to contribute in a way that helps us I would be happy to provide assistance there
