### ISSUE TITLE
Localization classes migration

### ISSUE THREAD

**Issue by maxkoshevoi** [CommunityToolkit/Maui#6]
Migrate XCT localization classes to Maui CT.

Classes list:
- LocalizationResourceManager
- TranslateExtension
- LocalizedString

I am willing to take this on myself

**Comment by maxkoshevoi** [comment]
@brminnick @pictos Hi, didn't found `[Proposal]` issues for these classes. Would they be migrated to a different package?

**Comment by angelru** [comment]
@brminnick  and where will it be included? thanks

**Comment by VladislavAntonyuk** [comment]
@brminnick I see it may be useful. We can discuss it at the Monthly meeting. I will prepare a small demo.
