### ISSUE TITLE
[BUG] IOS version supported

### ISSUE THREAD

**Issue by ForkBug** [CommunityToolkit/Maui#609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A project said the following errors when being compiled: "warning CA1416: This call site is reachable on: 'iOS' 10.0 and later, 'maccatalyst' 10.0 and later. 'ColorConversionExtensions.WithRed(Color, double)' is only supported on: 'iOS' 14.2 and later, 'maccatalyst' 14.2 and later."

And these lines found in the CommunityToolkit.Maui/CommunityToolkit.Maui.csproj project file:
```
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">14.0</SupportedOSPlatformVersion>
```

But according to the document, https://docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/, 
iOS 10 or higher is supported.

Which one is correct?

### Expected Behavior

iOS 10 or higher is supported.

### Steps To Reproduce

No

### Link to public reproduction project repository

https://github.com/ForkBug/MauiIOSVersion

### Environment

```markdown
- .NET MAUI CommunityToolkit:1.2.0
- .NET MAUI: 6.0
```

**Comment by VladislavAntonyuk** [comment]
These are the same lines of code which are in default .NET MAUI template.

**Comment by ForkBug** [comment]
Hope Ukraine get peace soon.


MAUI supports IOS 10 or higher [(doc)](https://docs.microsoft.com/en-us/dotnet/maui/supported-platforms)

**Comment by VladislavAntonyuk** [comment]
Thank you @ForkBug. Could you please send a link to a small repro project. It will help us investigate the issue

**Comment by VladislavAntonyuk** [comment]
I confirm it is reproduced. We will discuss the issue on next stand up

**Comment by LennoxP90** [comment]
I second this issue, I cannot use the community toolkit unless ios 11 is at least supported
