### ISSUE TITLE
[Proposal] ImageResourceConverter

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#61]
# ImageResourceConverter

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Sample
* [x] Documentation

## Summary
[summary]: #summary

Converts embedded image resource ID to it ImageSource

## Detailed Design
[design]: #detailed-design

### ImageResourceConverter.shared.cs
```cs
public class ImageResourceConverter : IValueConverter
{
  public object? Convert(object? value, Type? targetType, object? parameter, CultureInfo? culture)
  {
	if (value == null)
		return null;

	if (value is not string imageId)
		throw new ArgumentException("Value is not a string", nameof(value));

	return ImageSource.FromResource(imageId, Application.Current.GetType().GetTypeInfo().Assembly);
  }

  public object ConvertBack(object? value, Type? targetType, object? parameter, CultureInfo? culture) => throw new NotImplementedException();
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
             xmlns:myEnum="MyLittleApp.Models"
             x:Class="MyLittleApp.MainPage">

    <ContentPage.Resources>
        <ResourceDictionary>
            <xct: ImageResourceConverter x:Key="ImageResourceConverter" />
        </ResourceDictionary>
    </ContentPage.Resources>

    <StackLayout>

        <Image Source="{Binding ImageResource, Converter={StaticResource ImageResourceConverter}}" />

    </StackLayout>
</ContentPage>

```

### C# Usage

```cs
class MyPage : ContentPage
{
  public MyPage()
  {
    Content = new StackLayout
    {
      Children = 
      {
          new Image().Bind(Image.SourceProperty, nameof(ViewModel.ImageResource), converter: new ImageResourceConverter()),
      };
    }
  }
}

```

**Comment by CalvinAllen** [comment]
![raw](https://user-images.githubusercontent.com/41448698/140981350-f07df71b-9518-487d-82e0-9e99e686d2f6.gif)

**Comment by CalvinAllen** [comment]
@brminnick @jfversluis - I need some guidance on this one :)

Working on the tests, which seem easy enough by just having a resource embedded into the test assembly, doesn't work because the converter assumes the resources will be in the same assembly as the converter itself -

```cs
return ImageSource.FromResource(imageId, Application.Current?.GetType()?.Assembly);
```

Changing that assembly piece a smidge to -

```cs
return ImageSource.FromResource(imageId, Assembly.GetCallingAssembly());
```

Allows the tests to pass, but I'm not sure if that's a change worth pursuing (to the converter) or if I need to handle the test differently.  Thoughts?

**Comment by brminnick** [comment]
My concern is that using `Assembly.GetCallingAssembly()` could break functionality for folks using multiple `csproj` files, like so:

    solution
    │
    └───MyMauiApp.csproj
        │   CompanyLogo.png
    │   
    └───MyLoginPage.csproj

If `MyLoginPageProject.LoginPage` used the `ImageResourceConverter`, it would fail, because `Assembly.GetCallingAssembly()` would be searching for `CompanyLogo.png` in the wrong assembly.

You may need to mock-out `Application` for your tests to get the unit tests working.

**Comment by CalvinAllen** [comment]
@brminnick Thanks, exactly why I asked :)

**Comment by CalvinAllen** [comment]
@brminnick I created a draft PR to resolve the test portion of this issue - can you take a look and let me know what I screwed up before I make it an official PR :)

**Comment by CalvinAllen** [comment]
What is the proper documentation repo?  (README doesn't have a link to it)

**Comment by brminnick** [comment]
The documentation repo is here: https://github.com/MicrosoftDocs/CommunityToolkitDocs

But we haven't set it up just yet! We'll get it up an running by Q1 2022 in preparation for GA in Q2 2022.

**Comment by CalvinAllen** [comment]
Ah, gotcha.  Okay, I'll pivot to the sample app instead :)

**Comment by pictos** [comment]
Hey @CalvinAllen 
friendly asking if you still want to work on this feature. If you can't move forward with this there's no problem at all, we know that life happens (:
