### ISSUE TITLE
[BUG] Simple Exception Syntax Error.

### ISSUE THREAD

**Issue by Rashidovicc** [CommunityToolkit/Maui#612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The exception message should be corrected for syntax.

### Expected Behavior

 Letter case should be default case, old version is pascal case...

### Steps To Reproduce

1.Open and run solution fron reproduction repository.
2.If you get an exception message when you run the program, there are syntax errors.

### Link to public reproduction project repository

No

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS:
- .NET MAUI:
```

**Comment by VladislavAntonyuk** [comment]
Approve
