### ISSUE TITLE
[ENHANCEMENT - ANDROID] Implement the new API to change the StatusBar style

### ISSUE THREAD

**Issue by pictos** [CommunityToolkit/Maui#626]
# [Update StatusBar Style implementation for Android]

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
  * [ ] Android Support
* [ ] Unit Tests: Not Started
* [ ] Sample: Not Started
* [ ] Documentation: Not Started

## Summary
[summary]: #summary

In order to ship the `StatusBarBehavior`, we used a deprecated API to change the appearance of Android's StatusBar. We want to implement the new way for devices running the Android API 30 and above.

## Detailed Design
[design]: #detailed-design

The public APIs will not change.

## Drawbacks
[drawbacks]: #drawbacks

None.

**Comment by maxkoshevoi** [comment]
Could you assign this to me please? 
I'll be able to work on it starting Friday evening (EEST time). If it's needed sooner, feel free to assign it to someone else

**Comment by pictos** [comment]
@maxkoshevoi no need to rush, we still need to merge the #617
