### ISSUE TITLE
EmptyView not showing on Android

### ISSUE THREAD

**Issue by 99067718** [CommunityToolkit/Maui#630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The emptyView in my program won't show on android, it only shows on Windows, I don't know why thats happening

Android:
![image_2022-09-15_154555471](https://user-images.githubusercontent.com/89968831/190420275-abf17bcd-bbba-42ef-a90f-d2a290d08cd3.png)

Windows:
![image](https://user-images.githubusercontent.com/89968831/190420561-5f65bced-4c77-4951-a3b7-c439319a2b4b.png)

### Expected Behavior

It should look the exact same as on windows, but it doesn't look like that at all

### Steps To Reproduce

I don't know how to Reproduce this sadly.
This is my code:
![image_2022-09-15_154843430](https://user-images.githubusercontent.com/89968831/190420937-52774169-bd06-4ebd-a944-6ec88db7d0ae.png)

### Link to public reproduction project repository

I can't give this, sorry

### Environment

```markdown
- .NET MAUI CommunityToolkit: Not installed
- OS: Samsung Galaxy A52 S
- .NET MAUI: Latest update 15/09/2022
```

**Comment by pictos** [comment]
@99067718, I believe this is a .NET MAUI issue, so you should report it [here](https://github.com/dotnet/maui/issues/new/choose)

**Comment by 99067718** [comment]
> @99067718, I believe this is a .NET MAUI issue, so you should report it [here](https://github.com/dotnet/maui/issues/new/choose)

oops, Didn't see that, thanks for letting me know
