### ISSUE TITLE
[BUG] AvatarView clipping on Windows isn't applied correctly to UriImageSource

### ISSUE THREAD

**Issue by GeorgeLeithead** [CommunityToolkit/Maui#632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When applying a `StrokeShape`, such as `PolyLine` to `AvatarView`, clipping on Windows where the `ImageSource` is a `UriImageSource` clipping is not applied correctly. 
![image](https://user-images.githubusercontent.com/43666574/190586089-58257619-f94e-4900-ad64-511f70e1cbb1.png)

### Expected Behavior

On Windwos the image should be clipped to the `AvatarView` stroke shape.

### Steps To Reproduce

1. Add an `AvatarView` control.
2. Set as the `ImageSource` a Uri.

### Link to public reproduction project repository

https://github.com/GeorgeLeithead/CommunityToolkitMaui/tree/632-BUG-AvatarView-clipping-on-Windows

### Environment

```markdown
- .NET MAUI CommunityToolkit: 1.2.0
- OS: windows10.0.19041.0
- .NET MAUI: 6.0.408
```

**Comment by brminnick** [comment]
Hey @GeorgeLeithead! I just tried the link for the reproduction sample and it looks to be dead. 

When you get a chance, could update the link so that we can dig into it? Apologies for not jumping on this sooner.

**Comment by GeorgeLeithead** [comment]
> Hey @GeorgeLeithead! I just tried the link for the reproduction sample and it looks to be dead. 
> 
> When you get a chance, could update the link so that we can dig into it? Apologies for not jumping on this sooner.

@brminnick I'll actually "have" time to look into this next week. Will keep this thread updated accordingly.

**Comment by brminnick** [comment]
Oh - no way! Thanks George!! 

In the meantime, I'll assign this one to you.

**Comment by GeorgeLeithead** [comment]
Looks like having .NET MAUI upgraded from 6.0.408 to 7.0.200 has solved the clipping issue when using an `ImageSource` with a `Uri`.
