### ISSUE TITLE
[BUG] StatusBar color doesn't update for landscape mode

### ISSUE THREAD

**Issue by pictos** [CommunityToolkit/Maui#637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This was reported by @jfversluis 

![image](https://user-images.githubusercontent.com/20712372/190876876-6f1d0c99-aa04-4e29-88f0-cdba31694040.png)

### Expected Behavior

The status bar looks gourgeous

### Steps To Reproduce

No needed

### Link to public reproduction project repository

N/A

### Environment

```markdown
- .NET MAUI CommunityToolkit:1.3.0
- OS:MacOS
- .NET MAUI: 6.0.400
```

**Comment by KSemenenko** [comment]
We need to call these method when page appear and change size.

**Comment by Greg-Bates-Trimble** [comment]
I have seen this occurring on iOS 16.2 with MCT v4.0
Can I confirm with others if they are also experiencing this? I have not been able to test on iOS 15.5 sorry.

**Comment by Greg-Bates-Trimble** [comment]
@pictos does you solution work with Shell?

**Comment by pictos** [comment]
@Greg-Bates-Trimble yes. If you can't make it work, please open a new issue providing a sample that reproduces the issue

**Comment by Greg-Bates-Trimble** [comment]
@pictos this happens when I try it on the sample app. Changing the color fixes the problem.

**Comment by johannes-steurer** [comment]
Hi, I have a similar issue when I switch to landscape. The color is Ok when, but I have a very similar bar appearing that is on top of my header-buttons which makes them unusable in landscape. Any ideas?
