### ISSUE TITLE
Controlling the toolkit:popup using MVVM

### ISSUE THREAD

**Issue by samir-dahal** [CommunityToolkit/Maui#639]
Recently I found out that when I wanted to display the popup I have to call the popup from code behind file `.xaml.cs` and call the extension method `ShowPopup/ShowPopupAsync`. It would be a lot easier for us to call that method from `ViewModel` instead.

For now I have a work around but introducing the feature on upcoming release would be better than to relay on that workaround.
Thanks!

**Comment by VladislavAntonyuk** [comment]
How do you propose to call it from VM?

Popup is UI element and related to the specific Page. 
you can create a DialogService and call it from there:
Application.Current.MainPage.ShowPopup(Popup);

**Comment by samir-dahal** [comment]
> How do you propose to call it from VM?
> 
> Popup is UI element and related to the specific Page. you can create a DialogService and call it from there: Application.Current.MainPage.ShowPopup(Popup);

Oh got it. I was used to Rg Plugin in xamarin forms and it has the PopupNavigationService to show and hide the popup, I thought of implementing it like that from the view model.


Thanks!

**Comment by aakash44** [comment]
@VladislavAntonyuk , @samir-dahal can you guys guide me towards any sample code/tutorial for implementing the dialog service for calling/opening the popup from vm?

**Comment by samir-dahal** [comment]
> @VladislavAntonyuk , @samir-dahal can you guys guide me towards any sample code/tutorial for implementing the dialog service for calling/opening the popup from vm?

I hope you already have created a popup.
To actually show the popup from vm you have to reference the MainPage from

 `await App.Current.MainPage.ShowPopupAync(new YourPopup());`
You can create a helper as well

**Comment by symbiogenesis** [comment]
I think this should be re-opened. Ideally under MVVM, you would want the popup itself to have a ViewModel and be able to return a result in a process entirely driven by the ViewModel.

But currently the Popup's Close() method is only available inside of the Popup's codebehind. There is no ICommand interface that can drive the Close event. And the Popup doesn't even support Behaviors, so you cannot use the EventToCommandBehavior.

**Comment by symbiogenesis** [comment]
I had been using code like this to support an awaitable popup using the Rg package

`public static async ValueTask<T?> NavigateToPopup<T>(this PopupPage popup)
        {
            if (popup.BindingContext == null)
                throw new ArgumentNullException(nameof(popup), "BindingContext for page is null");

            try
            {
                bool isPushed = false;
                var viewModel = (IModalViewModel<T>)popup.BindingContext;
                var oldViewModelId = viewModel.ViewModelId; // to help with nested modals
                viewModel.ViewModelId = Guid.NewGuid();
                var source = new TaskCompletionSource<T?>();

                // When PresentationMode is Modal, the Disappearing event runs when you do a Push() for some reason
                // That is why the isPushed variable is used.
                // https://github.com/xamarin/Xamarin.Forms/issues/10115
                void disappearingAction(object? f, EventArgs f2)
                {
                    if (isPushed && !source.Task.IsCompleted)
                    {
                        source.SetResult(default);
                    }
                }

                popup.Disappearing += disappearingAction;
                viewModel.ResultActions.Add(viewModel.ViewModelId, new(source.SetResult));
                await Shell.Current.Navigation.PushPopupAsync(popup);
                isPushed = true;
                var result = await source.Task;
                viewModel.ResultActions.Remove(viewModel.ViewModelId);
                await Shell.Current.Navigation.PopPopupAsync();
                viewModel.ViewModelId = oldViewModelId;
                popup.Disappearing -= disappearingAction;
                return result;
            }
            catch (Exception e)
            {
                await LogUtil.LogExceptionAsync(e);
                return default;
            }
        }`

**Comment by LeoJHarris** [comment]
Can we not make toolkit:popup MVVM friendly? Kind of makes this hard to integrated with app using MVVM first.

**Comment by symbiogenesis** [comment]
> Can we not make toolkit:popup MVVM friendly? Kind of makes this hard to integrate with apps using the MVVM pattern.

What a silly comment. Having Commands exposed doesn't preclude you from subscribing to events.

**Comment by LeoJHarris** [comment]
@symbiogenesis thats what I have since opted to do but that doesnt make it the most elegant solution.
