### ISSUE TITLE
[BUG] [Android] Snackbar is displayed over the navigation buttons.

### ISSUE THREAD

**Issue by JosueDM94** [CommunityToolkit/Maui#642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The snackbar is not anchored to the VisualElement when using the Application.Current.MainPage or Shell.Current

### Expected Behavior

The snackbar should be aligned to the VisualElement.

### Steps To Reproduce

1. Open and run solution from reproduction repository
2. Click the button and observe the bug.

`Shell.Current.DisplaySnackbar("Lorem ipsum dolor sit amet, consectetur adipiscing elit.", duration: TimeSpan.FromSeconds(5));` or `Application.Current.MainPage.DisplaySnackbar("Lorem ipsum dolor sit amet, consectetur adipiscing elit.", duration: TimeSpan.FromSeconds(5));`

<img width="438" alt="Screen Shot 2022-09-19 at 13 00 45" src="https://user-images.githubusercontent.com/32943371/191083532-098fcd83-bdab-466a-9031-7669533d1191.png">

### Link to public reproduction project repository

https://github.com/JosueDM94/MauiSnackbarBug

### Environment

```markdown
- .NET MAUI CommunityToolkit: 1.3.0
- OS: Android All version
- .NET MAUI: 6.0.486
```

**Comment by VladislavAntonyuk** [comment]
That is expected, because you don't set the anchor.

**Comment by JosueDM94** [comment]
Thank you for the quick response,  about the extension method "DisplaySnackbar" which is supposed that use the anchor of the VisualElement that is firing the method in this case the MainPage or the top page from shell or hierarchal navigation.

I'm using the Snackbar as a service and calling from my ViewModel, so I'm not able to pass the reference from the page or any VisualElement. I'm trying to always display the snackbar at the bottom of the pages.  

If using the main page or top page from the navigation stack as an anchored visual element in the snackbar will result in android overlapping the navigation button, I will update my code, but please confirm that there is no other way.

**Comment by VladislavAntonyuk** [comment]
you can use static Snackbar.Make().Show() if you don't need anchor. But because anchor is visual element, you still need to pass it to your VM/Service

**Comment by VladislavAntonyuk** [comment]
I found the root cause of the issue. I will submit PR the next weekend
