### ISSUE TITLE
[BUG] AvatarView clipping on Android isn't applied correctly

### ISSUE THREAD

**Issue by Javierflo95** [CommunityToolkit/Maui#646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I updated to latest version yesterday and this issue appeared, when I use toolkit AvatarView

![image](https://user-images.githubusercontent.com/11860518/191311722-2856e9c6-2498-4a19-8d5c-2ae52746c3a6.png)

![image](https://user-images.githubusercontent.com/11860518/191312015-b68a90cc-3059-4494-be89-bbff2e402df0.png)

### Expected Behavior

before update the AvatarView control was working well as I expected .. the circle image showing well without black borders or black background as I show you in Current Behavior section in images. 

### Steps To Reproduce

1. Add an **AvatarView** control.
2. Set as the **ImageSource** a Uri as image.

### Link to public reproduction project repository

https://github.com/GeorgeLeithead/CommunityToolkitMaui/tree/510-Bug

### Environment

```markdown
- .NET MAUI CommunityToolkit: 1.2.0
- OS: Windows 10 Build 10.0.19041.0
- .NET MAUI: 6.0.408
```

**Comment by FM1973** [comment]
I can confirm this bug.

**Comment by Javierflo95** [comment]
@jsuarezruiz 
@jfversluis 
@pictos

**Comment by jfversluis** [comment]
No need to tag us, if its in an issue we will see it and get to it, thanks :)

**Comment by GeorgeLeithead** [comment]
> @GeorgeLeithead, is this familiar to you?

@pictos No, but I very much suspect it is an effect from applying the clip rect bounds and starting from 0,0 instead of taking into account the border width. Assign to me and I can investigate and resolve as appropriate.
