### ISSUE TITLE
[BUG] IconTintColorBehavior not working in windows

### ISSUE THREAD

**Issue by victorsigga** [CommunityToolkit/Maui#647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello guys, I'm trying to use IconTintColorBehavior to tint some icons in my application, but it isn't working as expected.
I'm trying to use the implementaion example in https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/behaviors/icon-tint-color-behavior .
class IconTintColorBehaviorPage : ContentPage
{
    public IconTintColorBehaviorPage()
    {
        var img = new Image();

        var behavior = new IconTintColorBehavior
        {
            TintColor = Color.Red
        };

        img.Behaviors.Add(behavior);

        Content = entry;
    }
}

My code is like this: 

In my view
Image firstIcon = new Image();
                firstIcon.Aspect = Aspect.Fill;
                firstIcon.HeightRequest = 30;
                firstIcon.WidthRequest = 30;
                firstIcon.SetBinding(Image.SourceProperty, "FirstIcon");
                //var firstIconColor = new IconTintColorBehavior();
                //firstIconColor.SetBinding(IconTintColorBehavior.TintColorProperty, "FirstIconColor");
                var behavior = new IconTintColorBehavior
                {
                    TintColor = Colors.Red
                };
                firstIcon.Behaviors.Add(behavior);
                grid.Add(firstIcon, 0, 2);

I also tried the commented code but doesn't work as well, and i have the correct bindings in my view model

I'm using the last stable version for Community Toolkit, 1.3.0

I also tried filling the tintcolor property with Color.FromARGB, but with no success 

### Expected Behavior

The icon be tinted with the choosen color

### Steps To Reproduce

1. Create a Image in the view;
2. Create IconTintColorBehavior behavior
3. Add the behavior in te image as the sample in https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/behaviors/icon-tint-color-behavior
4. Run the code and verify that the image dont tint

### Link to public reproduction project repository

Enterprise project

### Environment

```markdown
- .NET MAUI CommunityToolkit: 1.3.0
- OS: Windows 10 Pro 19044.2006
- .NET MAUI: Visual Studio Version 17.4.0 Preview 2.0
```

**Comment by pictos** [comment]
@victorsigga there's no implementation for Windows, didn't find the API that allows customizing the status bar color on `Windows`. You should see a warning telling you, this feature doesn't support Windows.

https://github.com/CommunityToolkit/Maui/blob/9de9ec676972a390d534a155a4c4ac38cee2f06a/src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.shared.cs#L8

**Comment by victorsigga** [comment]
@pictos there is any plannig to develop this to UWP ?

**Comment by pictos** [comment]
@victorsigga if we found an implementation for that for sure we will. Feel free to investigate that and if you're comfortable open a PR

**Comment by victorsigga** [comment]
Ok, thank you @pictos
