### ISSUE TITLE
[BUG] GetImageStream wrong when lines populated from code

### ISSUE THREAD

**Issue by cornem** [CommunityToolkit/Maui#649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the `DrawingView.Lines` is bound to a view model property and initalized with some lines, the `DrawingView` displays the lines correctly, but `GetImageStream` returns a bitmap of only a portion of the view. After the user has interacted with the `DrawingView`, a proper bitmap will be returned.

### Expected Behavior

When the view is initialized with a binding on `Lines` already containing some lines, `GetImageStream` should return a bitmap of the same size as if the lines were drawn on the view by the user.

### Steps To Reproduce

1. Create a view model with a property `ObservableCollection<IDrawingLine>`
2. Initialize the property with some `DrawingLine` instances
3. Create a view with a `DrawingView` and bind the `Lines` to the view model property
4. Show bitmap using `DrawingView.GetImageStream`
5. Observe the difference after interacting with the `DrawingView`

### Link to public reproduction project repository

https://github.com/cornem/maui-drawingview-repro

### Environment

```markdown
- .NET MAUI CommunityToolkit: 1.3.0
- OS: Windows 11
- .NET MAUI: 6.0.486
```

### Anything else?

Confirmed not working on Windows and Android. Other targets were not tested.

**Comment by cornem** [comment]
Looking at this more, what actually appears to happen is that somehow all lines except the last `DrawingLine` somehow are removed from the `Lines` collection.

In my repro, if you the constructor in `MainPage.xaml.cs` to the following, and then set a breakpoint to inspect `drawingView.Lines`, it only contains one line, though seven lines were added on the view model.

```csharp
public MainPage()
{
	InitializeComponent();
	BindingContext = new MainViewModel();

	Loaded += (_, __) => OnShowImageClicked(ShowImageBtn, EventArgs.Empty);
}
```

**Comment by bijington** [comment]
@cornem It looks like you haven't set `ClearOnFinish` to false as per the docs here: https://learn.microsoft.com/en-gb/dotnet/communitytoolkit/maui/views/drawingview#multiline-usage

@VladislavAntonyuk I do wonder if we should either automatically set `ClearOnFinish` if `IsMultiLineModeEnabled` is set to true, or ignore the flag?

**Comment by cornem** [comment]
@bijington Setting that property actually makes no difference; `Lines.Count` is still `1` instead of `7`.

**Comment by VladislavAntonyuk** [comment]
> @cornem It looks like you haven't set `ClearOnFinish` to false as per the docs here: https://learn.microsoft.com/en-gb/dotnet/communitytoolkit/maui/views/drawingview#multiline-usage
> 
> @VladislavAntonyuk I do wonder if we should either automatically set `ClearOnFinish` if `IsMultiLineModeEnabled` is set to true, or ignore the flag?

no, they are independent. I may have 5 lines (IsMultiLineModeEnabled = true). I want to clean on drawing 6th line. I set ClearOnFinish = true.
