### ISSUE TITLE
[Proposal] Is In Range Converter

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#65]
# IsInRangeConverter

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Sample
* [x] Documentation

## Summary
[summary]: #summary

The IsInRangeConverter is a converter that allows users to convert a object value into a boolean value, checking if the value is between MinValue and MaxValue, returning true if the value is within the range and false if the value is out of the range

## Detailed Design
[design]: #detailed-design

### IsInRangeConverter.shared.cs
```cs
public class IsInRangeConverter : ValueConverterExtension, IValueConverter
{
  public static readonly BindableProperty MinValueProperty = BindableProperty.Create(nameof(MinValue), typeof(object), typeof(IsInRangeConverter));

  public static readonly BindableProperty MaxValueProperty = BindableProperty.Create(nameof(MaxValue), typeof(object), typeof(IsInRangeConverter));

  public object? MinValue
  {
	get => GetValue(MinValueProperty);
	set => SetValue(MinValueProperty, value);
  }

  public object? MaxValue
  {
	get => GetValue(MaxValueProperty);
	set => SetValue(MaxValueProperty, value);
  }

  public object Convert(object? value, Type? targetType, object? parameter, CultureInfo? culture)
  {
	if (value is not IComparable comparable)
		throw new ArgumentException("is expected to implement IComparable interface.", nameof(value));

	if (MinValue is not IComparable)
		throw new ArgumentException("is expected to implement IComparable interface.", nameof(MinValue));

	if (MaxValue is not IComparable)
		throw new ArgumentException("is expected to implement IComparable interface.", nameof(MaxValue));

	return comparable.CompareTo(MinValue) >= 0 && comparable.CompareTo(MaxValue) <= 0;
  }

  public object? ConvertBack(object? value, Type? targetType, object? parameter, CultureInfo? culture) => throw new NotImplementedException();
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
             xmlns:myEnum="MyLittleApp.Models"
             x:Class="MyLittleApp.MainPage">

    <ContentPage.Resources>
        <ResourceDictionary>
          <xct:IsInRangeConverter
                          x:Key="IsInRangeConverter"
                          MaxValue= "1"
                          MinValue= "3" />
        </ResourceDictionary>
    </ContentPage.Resources>

    <StackLayout>
        <Label IsVisible="{Binding Number, Converter={StaticResource IssueStateConverter } }" />

    </StackLayout>
</ContentPage>

```

### C# Usage

```cs
class MyPage : ContentPage
{
  public MyPage()
  {
    Content = new StackLayout
    {
      Children = 
      {
          new Label().Bind(Label.IsVisibleProperty, nameof(ViewModel.Number), converter: new IsInRangeConverter { MinValue = 1, MaxValue = 3 }),
      };
    }
  }
}
```

**Comment by GeorgeLeithead** [comment]
I have a working prototype here: [65-IsInRangeConverter](https://github.com/GeorgeLeithead/CommunityToolkitMaui/tree/65-IsInRangeConverter).
I have samples for most of the `IComparable` derived types and will work on the others for completeness.
NOTE: I have left in GreaterThan and LessThan capabilities as these are easy in the converter (, but I do know that `CompareConverter` already does this.
![image](https://user-images.githubusercontent.com/43666574/185429177-1b8b23c5-ac48-4053-8a99-142d89fb174d.png)

**Comment by GeorgeLeithead** [comment]
Bump

**Comment by brminnick** [comment]
Hey George! I've added the https://github.com/CommunityToolkit/Maui/labels/needs%20discussion label, which means we'll discuss this in our next standup.

In other words, I'll bring raise this to the team to see if any of the maintainers have the bandwidth to `Champion` this proposal.

**Comment by JoonghyunCho** [comment]
Hi George! Thanks for your work on this proposal. I will be championing this proposal. I will bring this to a vote to be approved so you can create a pull request. Thanks.

**Comment by GeorgeLeithead** [comment]
@brminnick  I think that this proposal an be moved to the `Closed` project column and `Completed` project column to close.
