### ISSUE TITLE
[Proposal] IsStringNullOrEmpty Converters

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#66]
# IsStringNullOrEmptyConverter

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Sample
* [x] Documentation

## Summary
[summary]: #summary

The `IsStringNullOrEmptyConverter` is a converter that allows users to convert an incoming `string` binding to a `bool` value. This value represents if the incoming binding value is null or empty using `string.IsNullOrEmpty`.

The `IsStringNotNullOrEmptyConverter` is a converter that allows users to convert an incoming `string` binding to a `bool` value. This value represents if the incoming binding value is null or empty using `string.IsNullOrEmpty`.

## Detailed Design
[design]: #detailed-design

### IsStringNullOrEmptyConverter.shared.cs
```cs
public class IsStringNullOrEmptyConverter : ValueConverterExtension, ICommunityToolkitValueConverter
{
  public object Convert(object? value, Type? targetType, object? parameter, CultureInfo? culture) => value is string stringValue ? string.IsNullOrEmpty(stringValue) : throw new InvalidArgumentException("Binding must be of type string")

  public object? ConvertBack(object? value, Type? targetType, object? parameter, CultureInfo? culture) => throw new NotImplementedException();
}
```

### IsStringNotNullOrEmptyConverter.shared.cs
```cs
public class IsStringNullOrEmptyConverter : ValueConverterExtension, ICommunityToolkitValueConverter
{
  public object Convert(object? value, Type? targetType, object? parameter, CultureInfo? culture) => value is string stringValue ? !string.IsNullOrEmpty(stringValue) : throw new InvalidArgumentException("Binding must be of type string")

  public object? ConvertBack(object? value, Type? targetType, object? parameter, CultureInfo? culture) => throw new NotImplementedException();
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
             x:Class="MyLittleApp.MainPage">

    <ContentPage.Resources>
        <ResourceDictionary>
            <xct: IsStringNullOrEmptyConverter x:Key="IsStringNullOrEmptyConverter" />
        </ResourceDictionary>
    </ContentPage.Resources>

    <StackLayout>

        <Label IsVisible="{Binding MyStringValue, Converter={StaticResource IsStringNullOrEmptyConverter}}" />

    </StackLayout>
</ContentPage>
```

### C# Usage

```cs
class MyPage : ContentPage
{
  public MyPage()
  {
    Content = new StackLayout
    {
      Children = 
      {
          new Label().Bind(Label.IsVisibleProperty, nameof(ViewModel.MyString), converter: new IsStringNullOrEmptyConverter()),
      };
    }
  }
}
```

**Comment by juansturla** [comment]
Hi again! I added the ViewModel for this sample on #132 PR, so the only thing left is modifying the XAML. I can do that if you like :)

**Comment by juansturla** [comment]
Well it looks like you already did that before being assigned hahaha

**Comment by brminnick** [comment]
Thanks @StevenHanquez! It is assigned to you.
