### ISSUE TITLE
[BUG] IconTintColorBehavior is not working inside popup #Android

### ISSUE THREAD

**Issue by xDaijobu** [CommunityToolkit/Maui#663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

IconTintColorBehavior is not working inside popup 

<img width="1515" alt="Screen Shot 2022-09-29 at 09 02 29" src="https://user-images.githubusercontent.com/22674537/192921715-887d2514-fdaf-490f-a234-4cf4f5594df2.png">

### Expected Behavior

the image be tinted with the choosen color

### Steps To Reproduce

1. Open & run the solution
2. click the button & observe the bug

### Link to public reproduction project repository

https://github.com/xDaijobu/behaviorPopup

### Environment

```markdown
- .NET MAUI CommunityToolkit: 1.3.0
- OS: MacOS Monterey
- .NET MAUI: 7 RC1
- Android API 30
- iOS 15.5
```

**Comment by xDaijobu** [comment]
https://github.com/CommunityToolkit/Maui/blob/bbf49eca6b2ee27f70e39aa08bd2ac75b17c42e2/src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.shared.cs#L9

https://github.com/CommunityToolkit/Maui/blob/bbf49eca6b2ee27f70e39aa08bd2ac75b17c42e2/src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.android.cs#L15-L16

CustomBehavior (PlatformBehavior) also not working
`OnAttachedTo` method are not getting called.

<img width="1755" alt="Screen Shot 2022-09-29 at 09 19 40" src="https://user-images.githubusercontent.com/22674537/192923836-adb21fd1-b694-4922-b83a-cf4f44d403c9.png">

**Comment by pictos** [comment]
@xDaijobu do you mind testing with this image?
https://github.com/CommunityToolkit/Maui/blob/main/samples/CommunityToolkit.Maui.Sample/Resources/Images/shield.png

**Comment by xDaijobu** [comment]
https://raw.githubusercontent.com/CommunityToolkit/Maui/main/samples/CommunityToolkit.Maui.Sample/Resources/Images/shield.png

<img width="1984" alt="Screen Shot 2022-09-29 at 09 37 16" src="https://user-images.githubusercontent.com/22674537/192925971-06a2904a-cbdb-4e74-99b9-f5d0adc204d1.png">

**Comment by borisblizzard** [comment]
I have the same issue, but it appears to not be working on Windows either (haven't tested iOS yet).
I also noticed that some other properties (such as "Command") aren't working on any controls either.

**Comment by gktval** [comment]
I can verify that this is working on Android, but not in Windows.

**Comment by gktval** [comment]
I looked at the code for Windows, and it says unsupported: https://github.com/CommunityToolkit/Maui/blob/main/src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.shared.cs

I was able to create an effect behavior for it. Essentially, it would look similar to this
```
using System.ComponentModel;
using Microsoft.UI.Xaml.Controls;
using Microsoft.Maui.Platform;
using Microsoft.UI.Xaml;
using Color = Microsoft.Maui.Graphics.Color;
using Microsoft.UI.Composition;
using Microsoft.UI.Xaml.Hosting;
using Microsoft.Graphics.Canvas.Effects;

namespace CommunityToolkit.Maui.Behaviors;

public partial class IconTintColorBehavior
{
    SpriteVisual _tintSprite;

    protected override void OnAttachedTo(View bindable, FrameworkElement platformView)
    => ApplyTintColor(bindable, platformView);

    protected override void OnDetachedFrom(View bindable, FrameworkElement platformView)
    => ClearTintColor(bindable, platformView);

    void ApplyTintColor(View element, FrameworkElement control)
    {
        var color = TintColor;
        element.PropertyChanged += OnElementPropertyChanged;

        SetTintColor(control, color);
    }

    void SetTintColor(FrameworkElement element, Color tintColor)
    {
        if (tintColor == null)
            return;

        var hostVisual = ElementCompositionPreview.GetElementVisual(element);
        var compositor = hostVisual.Compositor;

        TintEffect tintEffect = new TintEffect()
        {
            Name = "Tint",
            Color = tintColor.ToWindowsColor(),
        };

        tintEffect.Source = new CompositionEffectSourceParameter("source");

        CompositionEffectFactory effectFactory = compositor.CreateEffectFactory(tintEffect);
        CompositionEffectBrush effectBrush = effectFactory.CreateBrush();

        // Create a BackdropBrush and bind it to the EffectSourceParameter “source” 
        CompositionBrush backdropBrush = compositor.CreateBackdropBrush();
        effectBrush.SetSourceParameter("source", backdropBrush);

        // This will cause everything behind this SpriteVisual to be tinted 
        _tintSprite = compositor.CreateSpriteVisual();
        _tintSprite.Size = element.ActualSize;
        _tintSprite.Brush = effectBrush;
        element.SizeChanged += ViewSizeChanged;

        // Set tintSprite as a child visual of a XAML element 
        ElementCompositionPreview.SetElementChildVisual(element, _tintSprite);
    }

    private void ViewSizeChanged(object sender, SizeChangedEventArgs e)
    {
        UIElement element = sender as UIElement;
        if (element == null || _tintSprite ==null)
            return;

        _tintSprite.Size = element.ActualSize;
    }

    void OnElementPropertyChanged(object sender, PropertyChangedEventArgs args)
    {
        if (args.PropertyName is not string propertyName
            || sender is not View bindable
            || bindable.Handler?.PlatformView is not FrameworkElement platformView)
        {
            return;
        }

        if (!propertyName.Equals(TintColorProperty.PropertyName, StringComparison.Ordinal))
        {
            return;
        }

        ApplyTintColor(bindable, platformView);
    }

    void ClearTintColor(View view, FrameworkElement element)
    {
        view.PropertyChanged -= OnElementPropertyChanged;
        element.SizeChanged -= ViewSizeChanged;

        _tintSprite?.Dispose();
        _tintSprite = null;
    }
}
```
 
Could this be added to the platform specific behaviors for tinting in Windows, please.

**Comment by pictos** [comment]
This could be fixed by another PR.

@xDaijobu fell free to reopen this issue or open a new if this bug still happens for you.

**Comment by brminnick** [comment]
Thanks @vhugogarcia! 

Could you open a PR adding this new test code to the sample app?

This'll allow us to include it in our testing of future Popup PRs. Plus you already wrote the code and I'd hate for it to go to waste ❤️
