### ISSUE TITLE
[BUG] StatusBarBehavior throws "Android Activity can't be null" exception if used in Page without Shell.

### ISSUE THREAD

**Issue by MGohil** [CommunityToolkit/Maui#685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am changing the StatusBar color using this sample: https://github.com/jfversluis/MauiToolkitStatusBarBehaviorSample  in .NET Maui project.

However, the sample works good if "Shell" is used in Android.

But instead, if we load the first page without Shell, then it crashes with error "Android activity can't be null" in android platform.

### Expected Behavior

The StatusBarBehavior should also work with Page without Shell and should not throw exception: "Android Activity can't be null"

### Steps To Reproduce

1. Download sample from : https://github.com/jfversluis/MauiToolkitStatusBarBehaviorSample
2. in App.xaml.cs change to : `MainPage = new NavigationPage(new MainPage());`
3. Run in Android.
4. You will see this exception:
![image](https://user-images.githubusercontent.com/16605284/195068037-b0eee66d-aef7-4bed-8dd3-a7fac392c2b4.png)

### Link to public reproduction project repository

https://github.com/jfversluis/MauiToolkitStatusBarBehaviorSample

### Environment

```markdown
- .NET MAUI CommunityToolkit:1.3.0
- OS: Android
```

### Anything else?

![image](https://user-images.githubusercontent.com/16605284/195068569-f7bb4c3d-f23b-4c1f-a472-9da8d58d5ed2.png)

![image](https://user-images.githubusercontent.com/16605284/195068481-cc3b2b73-6099-47c2-bb04-2abb34b1a822.png)

**Comment by pictos** [comment]
@MGohil can you move your code to `OnNavigatedFrom` or `OnAppearing`?

**Comment by MGohil** [comment]
@pictos : Yes it works if I put this into OnAppearing.

But this means that, we can not set the StatusBarColor and StatusBarStyle from XAML page itself. We have to do this in code behind. 

```
protected override void OnAppearing()
{
    base.OnAppearing();
    statusBar.StatusBarColor = Colors.Gray;
    statusBar.StatusBarStyle = CommunityToolkit.Maui.Core.StatusBarStyle.DarkContent;
}
```
As per what @jfversluis mentioned in one of the YouTube videos https://www.youtube.com/watch?v=dWj0PdImH10, it would be great if this works as expected in XAML as well.

Thanks.

**Comment by PureWeen** [comment]
Why the requirement of order with the behavior? Can't the behavior just store those colors at the xplat level and then once OnPlatformAttached is called with StatusBarBehavior it sets those? 

Like, just don't fire any of this code here

https://github.com/CommunityToolkit/Maui/blob/9de9ec676972a390d534a155a4c4ac38cee2f06a/src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/StatusBar/StatusBarBehavior.shared.cs#L64-L81

Until PlatformAttached is called

**Comment by borrmann** [comment]
I can confirm what @PureWeen said. Line 79 is what my App caused to crash too.
Maybe it's possible to store those colors elsewhere like he said or at least there could be a try catch or some checks with some log output so at least the app doesnt crash? 

`System.InvalidOperationException: Android Activity can't be null.
[AppCenterXamarinCrashes]    at CommunityToolkit.Maui.Core.Platform.StatusBar.get_Activity() in /_/src/CommunityToolkit.Maui.Core/Platform/StatusBar/StatusBar.android.cs:line 13
[AppCenterXamarinCrashes]    at CommunityToolkit.Maui.Core.Platform.StatusBar.PlatformSetStyle(StatusBarStyle style) in /_/src/CommunityToolkit.Maui.Core/Platform/StatusBar/StatusBar.android.cs:line 38
[AppCenterXamarinCrashes]    at CommunityToolkit.Maui.Core.Platform.StatusBar.SetStyle(StatusBarStyle statusBarStyle) in /_/src/CommunityToolkit.Maui.Core/Platform/StatusBar/StatusBar.shared.cs:line 20
[AppCenterXamarinCrashes]    at CommunityToolkit.Maui.Behaviors.StatusBarBehavior.OnPropertyChanged(String propertyName) in /_/src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/StatusBar/StatusBarBehavior.shared.cs:line 79`
