### ISSUE TITLE
[Proposal] IsListNullOrEmptyConverter Converters

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#69]
# IsListNullOrEmpty Converters

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Sample
* [x] Documentation

## Summary
[summary]: #summary

The IsListNullOrEmpty is a converter that allows users to convert an incoming binding that implements IEnumerable to a bool value. This value represents if the incoming binding value is either null or an empty list.

The IsListNotNullOrEmpty is a converter that allows users to convert an incoming binding that implements IEnumerable to a bool value. This value represents if the incoming binding value is not null or an empty list.

## Detailed Design
[design]: #detailed-design

### IsListNullOrEmptyConverter.shared.cs

```cs
public class IsListNullOrEmptyConverter : ValueConverterExtension, IValueConverter
{
  public object Convert(object? value, Type? targetType, object? parameter, CultureInfo? culture) => ConvertInternal(value);

  internal static bool ConvertInternal(object? value)
  {
	if (value == null)
		return true;

	if (value is IEnumerable list)
		return !list.GetEnumerator().MoveNext();

	throw new ArgumentException("Value is not a valid IEnumerable or null", nameof(value));
  }

  public object? ConvertBack(object? value, Type? targetType, object? parameter, CultureInfo? culture) => throw new NotImplementedException();
}
```

### IsListNotNullOrEmptyConverter.shared.cs

```cs
public class IsListNotNullOrEmptyConverter : ValueConverterExtension, IValueConverter
{
  public object Convert(object? value, Type? targetType, object? parameter, CultureInfo? culture) => !ListIsNullOrEmptyConverter.ConvertInternal(value);

  public object ConvertBack(object? value, Type? targetType, object? parameter, CultureInfo? culture) => throw new NotImplementedException();
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
             x:Class="MyLittleApp.MainPage">

    <ContentPage.Resources>
        <ResourceDictionary>
            <xct: IsListNullOrEmptyConverter x:Key="IsListNullOrEmptyConverter" />
        </ResourceDictionary>
    </ContentPage.Resources>

    <StackLayout>

        <Label IsVisible="{Binding MyListValue, Converter={StaticResource IsListNullOrEmptyConverter}}" />

    </StackLayout>
</ContentPage>
```

### C# Usage

```cs
 class MyPage : ContentPage
{
  public MyPage()
  {
    Content = new Label().Bind(Label.IsVisible, nameof(ViewMode.MyList), converter: new IsListNullOrEmptyConverter();
  }
}
```

**Comment by brminnick** [comment]
Thanks @juansturla! It's now assigned to you!

We are waiting to add Windows support to the Toolkit until WinUI is fully supported: https://devblogs.microsoft.com/dotnet/update-on-dotnet-maui/

> To use Windows, you first need to install the Windows App SDK extension for Visual Studio 2022, and then uncomment the TargetFramework node at the top of your csproj file. In a future release, this will be available by default with the extension pre-installed with .NET MAUI.

**Comment by brminnick** [comment]
Hey @juansturla! We are deferring MVVM-specific features to [`CommunityToolkit.MVVM`](https://www.nuget.org/packages/CommunityToolkit.Mvvm/).

> Should we move into ObservableCollection and Command?
Yup, that's a great solution! We also plan on referencing [`CommunityToolkit.MVVM`](https://www.nuget.org/packages/CommunityToolkit.Mvvm/) in the sample app, so you're welcome to add it as a NuGet Package to the sample app and reference its tools like [`ObservableObject`](https://docs.microsoft.com/en-us/windows/communitytoolkit/mvvm/observableobject) and [`AsyncRelayCommand`](https://docs.microsoft.com/en-us/windows/communitytoolkit/mvvm/asyncrelaycommand).

**Comment by juansturla** [comment]
I am a little confused here.

Is [CommunityToolkit.MVVM](https://www.nuget.org/packages/CommunityToolkit.Mvvm/) and [Microsoft.Toolkit.MVVM](https://www.nuget.org/packages/Microsoft.Toolkit.Mvvm/) becomming the same ? Both Nugets aim to the same Project page and they have almost the same information.

But Microsoft's was updated 20 days ago and Community's 4 months ago
