### ISSUE TITLE
[BUG] Popup displays hidden navigation bars in Android.

### ISSUE THREAD

**Issue by mikmat** [CommunityToolkit/Maui#698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a Popup is displayed, the <Andoid> navigation buttons are shown even if the app is in Fullscreen & Immersive mode.

In a shell-based app the navigation controls stays visible after closing the Popup.   In my non-shell app, the navigation controls are hidden after closing the Popup.

![shown](https://user-images.githubusercontent.com/13150173/196355452-e44c7e60-4e81-44de-95c6-5e8c550c780c.png)
![hidden](https://user-images.githubusercontent.com/13150173/196355510-16f0057e-d080-4e4a-9903-998826ac08c9.png)

### Expected Behavior

The navigation buttons should stay hidden even if a popup is displayed

### Steps To Reproduce

Open and run solution from repo.
On android: click button and the builtin Android navigation controls are displayed.

### Link to public reproduction project repository

https://github.com/mikmat/PopupNavigationButtons

### Environment

```markdown
- .NET MAUI CommunityToolkit:1.3.0
- OS: Android 11, Kernel 4.19.157-perf
- .NET MAUI: 6.0.541
```

**Comment by bijington** [comment]
I can confirm this issue is reproducible. I have been playing around with solving it. 

I can prevent the navigation bar from showing but it requires using the `SetWindowLayout` method in the popup code. I haven't been able to find a way of getting some of the information set in that method to know how to apply it when showing the popup. I'll keep digging

**Comment by bijington** [comment]
As I mentioned I can reproduce this issue however retrieving the full screen settings deep down in the Android layer when displaying the Popup seems to be proving a real challenge (for me at least). The best I can come up with for now is to make use of the handler architecture, for more information on the use of handlers check out the [Microsoft Docs](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/handlers/customize)

I have modified your `MainActivity.cs` file to look as follows and now this behaves as you expect.

To break down the change we are registering for the `SetWindow` method to be called whenever `OnOpened` is called on a Popup.

```csharp
using Android.App;
using Android.Content.PM;
using Android.OS;
using Android.Views;
using CommunityToolkit.Maui.Core;
using CommunityToolkit.Maui.Core.Handlers;

namespace CommunityToolkit.Maui.Sample;

[Activity(Theme = "@style/Maui.SplashTheme", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation | ConfigChanges.UiMode | ConfigChanges.ScreenLayout | ConfigChanges.SmallestScreenSize)]
public class MainActivity : MauiAppCompatActivity
{
	protected override void OnCreate(Bundle? savedInstanceState)
	{
		base.OnCreate(savedInstanceState);
		Platform.Init(this, savedInstanceState);

		//--------------

		if (Window is not null)
		{
			SetWindow(Window);
		}

		PopupHandler.PopUpCommandMapper.AppendToMapping(
			nameof(IPopup.OnOpened),
			(handler, popup, value) =>
			{
				SetWindow(handler.PlatformView.Window!);
			});
	}

	static void SetWindow(Android.Views.Window window)
	{
		if (Build.VERSION.SdkInt >= BuildVersionCodes.R)
		{
#pragma warning disable CA1416

			IWindowInsetsController wicController = window.InsetsController!;

			//window.SetDecorFitsSystemWindows(false);
			window.SetFlags(WindowManagerFlags.Fullscreen, WindowManagerFlags.Fullscreen);

			if (wicController != null)
			{
				//wicController.Hide(WindowInsets.Type.Ime());
				wicController.Hide(WindowInsets.Type.NavigationBars());
			}
#pragma warning restore CA1416
		}
		else
		{
#pragma warning disable CA1422

			window.SetFlags(WindowManagerFlags.Fullscreen, WindowManagerFlags.Fullscreen);

			window.DecorView.SystemUiVisibility = (StatusBarVisibility)(SystemUiFlags.Fullscreen |
																		 SystemUiFlags.HideNavigation |
																		 SystemUiFlags.Immersive |
																		 SystemUiFlags.ImmersiveSticky |
																		 SystemUiFlags.LayoutHideNavigation |
																		 SystemUiFlags.LayoutStable |
																		 SystemUiFlags.LowProfile);
#pragma warning restore CA1422
		}
	}
}
```

**Comment by jenscski** [comment]
@bijington thank you for your saving my day, your code did what I was missing
