### ISSUE TITLE
[Proposal] `List`-To-`string` Converter

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#70]
# ListToStringConverter

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Sample
* [x] Documentation

## Summary
[summary]: #summary

The ListToStringConverter is a converter that allows users to convert an incoming binding that implements IEnumerable to a single string value. The Separator property is used to join the items in the IEnumerable.

## Motivation
[motivation]: #motivation

## Detailed Design
[design]: #detailed-design

### ListToStringConverter.shared.cs

```cs
public class ListToStringConverter : ValueConverterExtension, IValueConverter
{
  public string Separator { get; set; } = string.Empty;

  public object? Convert(object? value, Type? targetType, object? parameter, CultureInfo? culture)
  {
	if (value == null)
		return string.Empty;

	if (value is not IEnumerable enumerable)
		throw new ArgumentException("Value cannot be casted to IEnumerable", nameof(value));

	if ((parameter ?? Separator ?? string.Empty) is not string separator)
		throw new ArgumentException("Parameter cannot be casted to string", nameof(parameter));

	var collection = enumerable
		.OfType<object>()
		.Select(x => x.ToString())
		.Where(x => !string.IsNullOrWhiteSpace(x));

	return string.Join(separator, collection);
  }

  public object? ConvertBack(object? value, Type? targetType, object? parameter, CultureInfo? culture) => throw new NotImplementedException();
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:xct="clr-namespace:Xamarin.CommunityToolkit.Converters;assembly=Xamarin.CommunityToolkit"
             x:Class="MyLittleApp.MainPage">

    <ContentPage.Resources>
        <ResourceDictionary>
            <xct:ListToStringConverter x:Key="ListToStringConverter" Separator=", " />
        </ResourceDictionary>
    </ContentPage.Resources>

    <StackLayout>

        <Label IsVisible="{Binding MyListValue, Converter={StaticResource ListToStringConverter}}" />

    </StackLayout>
</ContentPage>
```

### C# Usage

```cs
new Label().Bind(Label.TextPropoerty, nameof(ViewModel.MyListValue), converter: = new ListToStringConverter());
```

**Comment by juansturla** [comment]
Hi! I know it's not much but i want to help with the sample. 
Also, why it is not available for windows ?

**Comment by brminnick** [comment]
Thanks @juansturla! It's now assigned to you!

We are waiting to add Windows support until WinUI is fully supported: https://devblogs.microsoft.com/dotnet/update-on-dotnet-maui/

> To use Windows, you first need to install the Windows App SDK extension for Visual Studio 2022, and then uncomment the TargetFramework node at the top of your csproj file. In a future release, this will be available by default with the extension pre-installed with .NET MAUI.
