### ISSUE TITLE
[BUG]  CommunityToolkit.Maui.Core.Platform.StatusBar.SetColor(color) is not working in .net7 rc2 for iOS

### ISSUE THREAD

**Issue by KSemenenko** [CommunityToolkit/Maui#735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

``` cs
class MyPage : ContentPage
{
    protected override void OnNavigatedTo(NavigatedToEventArgs args)
    {
        base.OnNavigatedTo(args);
        CommunityToolkit.Maui.Core.Platform.StatusBar.SetColor(statusBarColor);
        CommunityToolkit.Maui.Core.Platform.StatusBar.SetStyle(StatusBarStyle.LightContent);
    }
}
```

### Expected Behavior

Color for statusbar is not changed

### Steps To Reproduce

Create MAUI app for .NET7-RC2
put code snippet into page.

### Link to public reproduction project repository

no

### Environment

```markdown
- .NET MAUI CommunityToolkit: 1.3.0
- OS: iOS
- .NET MAUI:.net7 rc-2
```

### Anything else?

Still investigating

**Comment by KSemenenko** [comment]
<img width="1203" alt="Screenshot 2022-11-07 at 18 22 50" src="https://user-images.githubusercontent.com/4385716/200374546-2e17c40b-8549-4c70-8675-a12e8e064ff0.png">

**Comment by KSemenenko** [comment]
@brminnick thanks!
![Screenshot 2022-11-07 at 21 43 07](https://user-images.githubusercontent.com/4385716/200411435-b1bff040-ea2b-4708-8039-7b045b1334eb.png)

So I get where I miss it:
<img width="939" alt="Screenshot 2022-11-07 at 21 43 46" src="https://user-images.githubusercontent.com/4385716/200411613-ed85c7a4-462e-4008-8dcf-ee3d1bfcec12.png">

For some reason I thought it was possible not to add behavior

**Comment by pictos** [comment]
@KSemenenko it's possible, but probably you add those lines inside your `MainPage`, and probably the platform-specific world isn't ready yet. I'm talking with the .NET MAUI team to see how we can workaround that.

**Comment by KSemenenko** [comment]
Maybe we can change documention to make it clear, like "just add Behaivor" 
also this code in constructor, is not working widouth adding Behaivor

**Comment by pictos** [comment]
@KSemenenko yeap, that will always occurs on your first navigation page... Now if your mainPage is a page that navigates to another page, you can use the code in docs inside the `ctor` and that will work, because all the platform-specific world will be initialized.

**Comment by KSemenenko** [comment]
yeah, I understand it =) thanks a lot! anyway so good that we have it in toolkit
