### ISSUE TITLE
[BUG] Add `CollectionView` and `ListView` Support to `Expander`

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When `Expander` is used inside of a `CollectionView` or a `ListView`, a `NotSupportedException` is thrown:
https://github.com/CommunityToolkit/Maui/blob/1ea488c9be7aac234af32e1ab5b014d6a52a5ff0/src/CommunityToolkit.Maui/Views/Expander/Expander.shared.cs#L197-L202

### Expected Behavior

When an `Expander` is expanded, its parent controls should re-measure their size and layouts.

Here is a incomplete sample at how we could approach solving this problem:

```cs
if (element is ListView listView)
{
  foreach (var child in listView.AllChildren.OfType<Cell>())
  {
	  child.ForceUpdateSize();
  }
  listView.InvalidateMeasureInternal(Microsoft.Maui.Controls.Internals.InvalidationTrigger.MeasureChanged);
}
else if (element is CollectionView collectionView)
{
  collectionView.InvalidateMeasureInternal(Microsoft.Maui.Controls.Internals.InvalidationTrigger.MeasureChanged);
}
```

### Steps To Reproduce

1. Download/Clone the [Expander-ItemsView-NotSupportedException branch in `CommunityToolkit.Maui`](https://github.com/CommunityToolkit/Maui/tree/Expander-ItemsView-NotSupportedException)
2. In Visual Studio, open `CommunityToolkit.Maui.Samples.sln`
3. Navigate to the [`ExpanderPage`](https://github.com/CommunityToolkit/Maui/blob/d93f2aa8cda296de2ae39e9c294b891065c7a6bc/samples/CommunityToolkit.Maui.Sample/Pages/Views/Expander/ExpanderPage.xaml#L51-L96)
4. Confirm the app crashes when the ExpanderPage opens

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui/blob/d93f2aa8cda296de2ae39e9c294b891065c7a6bc/samples/CommunityToolkit.Maui.Sample/Pages/Views/Expander/ExpanderPage.xaml#L51-L96

### Environment

```markdown
- .NET MAUI CommunityToolkit: v1.4.0
- OS: All
- .NET MAUI: 6.0.312
```

### Anything else?

This is a known-issue, documented in the .NET MAUI Community Toolkit documentation: https://learn.microsoft.com/dotnet/communitytoolkit/maui/views/expander

**Comment by miah62** [comment]
I had a use for an Expander in a CollectionView, but I understand this is not supported, at least for now. However I get a NullReferenceException instead of the NotSupportedException. A race condition with parentElement exists since it can get set to null before the NotSupportedException message is created and formatted. It seems the loop should be exited once the not supported condition is hit.
