### ISSUE TITLE
[BUG] Frame caused System.ObjectDisposedException: Cannot access a disposed object.

### ISSUE THREAD

**Issue by karamfilov555** [CommunityToolkit/Maui#753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have a .NET Maui project with simple AppShell navigation. For some pages of our app (for example /ClientsPage) we have nested page (e.g. ClientsPage/CreateClientPage). 
When we are at this page and go to another random tab from the shell navigation (e.g /AboutPage) and than return to the Clients tab we get System.ObjectDisposedException: Cannot access a disposed object. 
Workaround: After few hours of debugging we found out that if we replace Frame tags with Borders in our xaml file the issue is resolved.  
**P.S. This issue was encountered after we updated our app to .NET 7 and ComunityToolkit 3**

### Expected Behavior

We don't expect exception when we are using frames.

### Steps To Reproduce

1. Create/Use a .NET 7 MAUI app with simple navigation as:
<FlyoutItem FlyoutDisplayOptions="AsMultipleItems"  x:Name="menu" >
        <ShellContent 
            Title="Home"
            x:Name="homeItem"
            Icon="tab_home.svg"
            ContentTemplate="{DataTemplate local:HomePage}"
            Route="HomePage"/>

        <ShellContent 
            Title="Clients"
            Icon="tab_clients.png"
            ContentTemplate="{DataTemplate local:ClientsPage}"
            Route="ClientsPage"/>

        <ShellContent
            Title="Calendar"
            Icon="calendar_icon.png"
            ContentTemplate="{DataTemplate local:CalendarPage}"
            Route="CalendarPage"/>

        <ShellContent 
            Title="Services"
            Icon="tab_haircut.png"
            ContentTemplate="{DataTemplate local:ServicesPage}"
            Route="ServicesPage"/>
        
        <ShellContent 
            Title="Profile"
            Icon="tab_profile.png"
            ContentTemplate="{DataTemplate local:ProfilePage}"
            Route="ProfilePage"/>
    </FlyoutItem>
2. Create a nested page in a random page (e.g ClientsPage -> Client Details, Create Clients, etc.)
3. Add some frames in the nested page
4. Run the app 
5. Go to the nested page, than click on a random tab from the navigation (e.g. Services)
6. Return to ClientsPage
7. System.ObjectDisposedException: Cannot access a disposed object. is thrown

### Link to public reproduction project repository

....

### Environment

```markdown
- .NET MAUI CommunityToolkit: 3
- OS: Android, Windows
- .NET MAUI: 7
```

**Comment by VladislavAntonyuk** [comment]
How is it related to CommunityToolkit.MAUI library?

**Comment by VladislavAntonyuk** [comment]
You should create this issue in dotnet/maui repository
