### ISSUE TITLE
[BUG] [iOS] StatusBarBehavior Frame is not proper when shell navigation bar is hidden

### ISSUE THREAD

**Issue by hemantbeast** [CommunityToolkit/Maui#762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When setting statusbar behavior on a ContentPage with the navigation bar hidden, the frame of the status bar is not proper on devices like iPhone 14 Pro. There is a space between the status bar & the content view.

This is affected on the iPhone 14 Pro & Pro Max as seen below.. Other iPhones don't seem to have this issue. Android is also working properly.

![Simulator Screen Shot - iPhone 14 Pro - 2022-11-14 at 17 28 41](https://user-images.githubusercontent.com/10476066/201658259-307dfb60-20d9-44f4-b85a-59515cd68151.png)

### Expected Behavior

There shouldn't be any space on iPhone 14 Pro/Pro Max devices.

### Steps To Reproduce

1. Open and run the solution from reproduction repository
2. Observe the bug

### Link to public reproduction project repository

https://github.com/hemantbeast/StatusBarSample

### Environment

```markdown
- .NET MAUI CommunityToolkit: 3.0.0
- OS: Mac OS 13.0.1
- .NET MAUI: 7.0
```

**Comment by VladislavAntonyuk** [comment]
It is a part of ContentPage:
<img width="882" alt="image" src="https://user-images.githubusercontent.com/33021114/216414425-cdc5580c-e70d-45e8-a808-3c4dae9c04d0.png">

**Comment by VladislavAntonyuk** [comment]
Related to https://github.com/dotnet/maui/issues/11611
