### ISSUE TITLE
[Proposal] Variable Multi-Value Converter

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#77]
# VariableMultiValueConverter

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Sample
* [x] Documentation:https://github.com/MicrosoftDocs/CommunityToolkit/pull/108

## Summary
[summary]: #summary

The `VariableMultiValueConverter` is a converter that allows users to convert multiple `bool` value bindings to a single `bool`. It does this by enabling them to specify whether All, Any, None or a specific number of values are true as specified in `ConditionType`. This is useful when combined with `MultiBinding`

## Detailed Design
[design]: #detailed-design

### VariableMultiValueConverter.shared.cs

```cs
public class VariableMultiValueConverter : MultiValueConverterExtension, IMultiValueConverter
{
  public MultiBindingCondition ConditionType { get; set; }

  public int Count { get; set; }

  public object Convert(object[]? values, Type? targetType, object? parameter, CultureInfo? culture)
  {
	if (values == null || values.Length == 0)
		return false;

	var boolValues = values.OfType<bool>().ToArray();

	if (boolValues.Length != values.Length)
		return false;

	var count = boolValues.Count(v => v);

	return ConditionType switch
	{
		MultiBindingCondition.Any => count >= 1,
		MultiBindingCondition.None => count == 0,
		MultiBindingCondition.Exact => count == Count,
		MultiBindingCondition.GreaterThan => count > Count,
		MultiBindingCondition.LessThan => count < Count,
		_ => count == boolValues.Count(),
	};
  }

  public object[]? ConvertBack(object? value, Type[]? targetTypes, object? parameter, CultureInfo? culture)
  {
	if (value is not bool boolValue || targetTypes?.Any(t => !t.IsAssignableFrom(typeof(bool))) is true)
		return null;

	return boolValue ? targetTypes?.Select(t => ConditionType == MultiBindingCondition.All).OfType<object>().ToArray() : null;
  }
}
```

## Usage Syntax
[usage]: #usage-syntax

<!-- Here is an example from CharactersValidationBehavior:

### XAML Usage

```xml
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
             x:Class="MyLittleApp.MainPage">

    <ContentPage.Resources>
        <ResourceDictionary>
            <xct: VariableMultiValueConverter x:Key="VariableMultiValueConverter" />
        </ResourceDictionary>
    </ContentPage.Resources>

    <StackLayout>

        <Label IsVisible="{Binding MyListValue, Converter={StaticResource VariableMultiValueConverter}}" />

    </StackLayout>
</ContentPage>
```

### C# Usage

```cs
 class MyPage : ContentPage
{
  public MyPage()
  {
    Content = new Label().Bind(Label.IsVisible, nameof(ViewMode.MyList), converter: new VariableMultiValueConverter { ConditionType = MultiBindingCondition.Exact, Count = 2 });
  }
}

```

**Comment by marsscotia** [comment]
@brminnick Commenting as requested.

**Comment by brminnick** [comment]
Thanks! Yea, GitHub has a weird quirk that we can't assign an Issue to anyone who isn't a maintainer or who hasn't commented directly on the Issue 🤷‍♂️

**Comment by CliffAgius** [comment]
Happy to have a go at the docs for this one if someone can assign me please.

**Comment by bijington** [comment]
Done thanks @CliffAgius

**Comment by CliffAgius** [comment]
Hey @bijington sorry been busy with NDCLondon then flying and now DevSUM Stockholm. I made a start just not had time to finish but will make sure it's done by next week. I get home Friday and then I'm free been a crazy 2 weeks.

**Comment by bijington** [comment]
> Hey @bijington sorry been busy with NDCLondon then flying and now DevSUM Stockholm. I made a start just not had time to finish but will make sure it's done by next week. I get home Friday and then I'm free been a crazy 2 weeks.

No problem at all! I am happy to finish off whatever you have if you are too busy, please don't feel you have to finish it.

**Comment by bijington** [comment]
@CliffAgius I hope you don't mind but I went ahead and created some docs for this proposal, I wanted to have a complete list ready for when the announcement goes live. Really sorry if it results in any wasted effort on your part.

It can be found at: https://github.com/MicrosoftDocs/CommunityToolkit/pull/108

**Comment by CliffAgius** [comment]
Hey @bijington don't worry I had it all done except for the C# Mark code section. Been a crazy few weeks with NDC, DevSUM conferences straight into family parties this weekend.

Sorry it wasn't done before that's totally on me for picking it up going into 2 conferences I should know better.

Thanks for doing it in my place and I'll try harder next time.

What is the plan now? To hold for a bit while GA happens and pick it all back up in a few weeks?

I'm busy with Build things this week but keen to continue helping after that.

**Comment by pictos** [comment]
@CliffAgius feel free to review the docs PR, maybe we can add something that you did there (?)

> What is the plan now? To hold for a bit while GA happens and pick it all back up in a few weeks?

Basically, we will just work on bug fixes until GA. After that, we will move back to adding new features. Is there some `issue` that you would like to work on?
