### ISSUE TITLE
[Proposal] IconTintColor Effect

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#78]
# IconTintColorEffect

* [x] Proposed
* [x] Prototype: (It's the same as XCT)
* [x] Implementation:
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [ ] Windows Support
* [x] Unit Tests
* [x] Sample
* [x] Documentation

## Summary
[summary]: #summary

An `Effect` to set the tint color of an ImageButton or an Image.

### IconTintColorEffect.shared.cs

```cs
public class IconTintColorEffect
{
  public static readonly BindableProperty TintColorProperty;

  public static Color GetTintColor(BindableObject view);
  public static void SetTintColor(BindableObject view, Color value);
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<ImageButton
  Source="https://image.flaticon.com/icons/png/512/48/48639.png"
  xct:IconTintColorEffect.TintColor="Red"
  Grid.Row="2"
  Grid.Column="1" />
```

### C# Usage

```cs
var button = new ImageButton
{
  Source="https://image.flaticon.com/icons/png/512/48/48639.png"
};
button.Effects.Add(new IconTintColorEffect());
IconTintColorEffect.SetTintColor(button, Colors.Red);
```

**Comment by pictos** [comment]
Hey @victorsigga, this will be implemented after our code freeze. This will become a Behavior instead of an Effect (:

**Comment by victorsigga** [comment]
Thank you @pictos . Can you inform how long this code freeze will last ?

**Comment by pictos** [comment]
We will work in new APIs after MAUI GA

**Comment by victorsigga** [comment]
@pictos ok, thank you very much

**Comment by HausBJB** [comment]
Hello, may I ask the status of the development? this feature is very useful

**Comment by pictos** [comment]
@HausBJB there's no work started on this one. But is planned to be on v1.1.0

**Comment by HausBJB** [comment]
I have one more question, will this only be available for android? since it also works for iOS if we use the example

  <Setter Property="Shell.TabBarForegroundColor" Value="Red" />

or how does it work?

**Comment by HausBJB** [comment]
Hello, my question was if this will also be available for iOS?

since only Android is selected above

![image](https://user-images.githubusercontent.com/53478848/171453861-53ff1b09-e4c8-49ac-b3d8-8e455011ab1d.png)
Thanks

**Comment by HausBJB** [comment]
Hello, I see there is already a pull request, thank you very much. I have one more question, couldn't this be solved with attached behavior? is easier to use. or does that not work with net maui


just like here

```
<ImageButton
  Source="https://image.flaticon.com/icons/png/512/48/48639.png"
  xct:IconTintColorEffect.TintColor="Red"
  Grid.Row="2"
  Grid.Column="1" />
```

**Comment by pictos** [comment]
@HausBJB yes, but for attached properties, AFAIK there are 2 two ways of doing it. 
1. You need to control using the `PropertyChanged` delegate, and it's not prepared for the multi-target. We need to perform some checks
2. You can add a property and an `Action` to the Handler Mapper, that will work but all controls that use that Handler will call the method, even if you don't use the property. This add a little overhead during the initialization phase. Of course, one method will not impact that much, but imagine a lot of controls/features doing that.

For more info in this subject you can see my talk on Maui-Fest [here](https://youtu.be/pnkHTyRYiTY)

**Comment by HausBJB** [comment]
Ok, thanks again for the great work

**Comment by TheSundayDev** [comment]
waiting also for win implementation, thanks!
