### ISSUE TITLE
[BUG] [RelayCommand] Doesn't work if added to the bottom of a class with several [RelayCommand]s

### ISSUE THREAD

**Issue by jee-mj** [CommunityToolkit/Maui#782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[RelayCommand] Doesn't work if added to the bottom of a class with several [RelayCommand]s

### Expected Behavior

Well, CommunityToolkit.Mvvm.SourceGenerators.RelayCommandGenerator should generate the associated method

### Steps To Reproduce

1. Open and run solution
2. You'll get the error message.

### Link to public reproduction project repository

https://github.com/jee-mj/MonkeyFinder

### Environment

```md
- .NET MAUI CommunityToolkit:
- OS: Windows 10
- IDE: Visual Studio 2022 Community Edition
- .NET MAUI:
```
```xaml
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net6.0-android;net6.0-ios;net6.0-maccatalyst</TargetFrameworks>
	</PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="CommunityToolkit.Mvvm" Version="8.0.0" />
	</ItemGroup>
</Project>
```

**Comment by VladislavAntonyuk** [comment]
Please create this issue in CommunityToolkit/dotnet. RelayCommand is not related to MAUI
