### ISSUE TITLE
[BUG] StateContainer with CollectionView/ScrollView with grid

### ISSUE THREAD

**Issue by angelru** [CommunityToolkit/Maui#792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a CollectionView is used, it stops scrolling. I noticed that it also happens with ScrollView, any ideas?

### Expected Behavior

StateContainer works with scrollable views.

### Steps To Reproduce

    <Grid toolkit:StateContainer.CurrentState="{Binding CurrentState}">
        <toolkit:StateContainer.StateViews>
            <StackLayout toolkit:StateView.StateKey="Success">
                <ScrollView>
                    <StackLayout>
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="sa" />
                        <Label Text="fin" />
                    </StackLayout>
                </ScrollView>
            </StackLayout>
        </toolkit:StateContainer.StateViews>
    </Grid>

### Link to public reproduction project repository

https://github.com/angelru/StateContainerGrid

### Environment

```markdown
- .NET MAUI CommunityToolkit: 3.0.0
- OS: Android
- .NET MAUI: 7
```

**Comment by angelru** [comment]
done

**Comment by angelru** [comment]
@brminnick  ping

**Comment by VladislavAntonyuk** [comment]
The problem is with StackLayout. Replace it with Grid

**Comment by angelru** [comment]
> The problem is with StackLayout. Replace it with Grid

The problem is that I have a base layout with StateContainer

```
<?xml version="1.0" encoding="utf-8" ?>
<StackLayout
    x:Class="ValdemoroEn1.Controls.BaseStateLayout"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:localization="clr-namespace:ValdemoroEn1.Resources.Localization"
    xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
    x:Name="this"
    toolkit:StateContainer.CurrentState="{Binding Source={x:Reference this}, Path=CurrentState}"
    CompressedLayout.IsHeadless="true">
    <toolkit:StateContainer.StateViews>
        <VerticalStackLayout
            toolkit:StateView.StateKey="Loading"
            CompressedLayout.IsHeadless="true"
            VerticalOptions="CenterAndExpand">
            <ActivityIndicator IsRunning="True" Color="{StaticResource BlueGeneral}" />
        </VerticalStackLayout>
        <VerticalStackLayout
            Padding="16"
            toolkit:StateView.StateKey="ConexError"
            CompressedLayout.IsHeadless="true"
            Spacing="16"
            VerticalOptions="CenterAndExpand">
            <Image
                HeightRequest="250"
                Source="conexerror"
                WidthRequest="250" />
            <Label
                HorizontalTextAlignment="Center"
                Text="{localization:Translate ConexError}"
                TextColor="{StaticResource BlueGeneral}" />
            <Button
                Clicked="Button_Clicked"
                Style="{StaticResource ButtonGeneral}"
                Text="{localization:Translate TryAgain}" />
        </VerticalStackLayout>
        <VerticalStackLayout
            Padding="16"
            toolkit:StateView.StateKey="CrtmError"
            CompressedLayout.IsHeadless="true"
            Spacing="16"
            VerticalOptions="CenterAndExpand">
            <Image
                HeightRequest="250"
                Source="crtmerror"
                WidthRequest="250" />
            <Label
                HorizontalTextAlignment="Center"
                Text="{localization:Translate CrtmError}"
                TextColor="{StaticResource BlueGeneral}" />
            <Button
                Clicked="Button_Clicked"
                Style="{StaticResource ButtonGeneral}"
                Text="{localization:Translate TryAgain}" />
        </VerticalStackLayout>
        <VerticalStackLayout
            Padding="16"
            toolkit:StateView.StateKey="Error"
            CompressedLayout.IsHeadless="true"
            Spacing="16"
            VerticalOptions="CenterAndExpand">
            <Image Source="error" WidthRequest="250" />
            <Label
                HorizontalTextAlignment="Center"
                Text="{localization:Translate Error}"
                TextColor="{StaticResource BlueGeneral}" />
            <Button
                Clicked="Button_Clicked"
                Style="{StaticResource ButtonGeneral}"
                Text="{localization:Translate TryAgain}" />
        </VerticalStackLayout>
        <StackLayout
            x:Name="StackSuccess"
            toolkit:StateView.StateKey="Success"
            CompressedLayout.IsHeadless="true"
            VerticalOptions="FillAndExpand" />
    </toolkit:StateContainer.StateViews>
</StackLayout>
```

**Comment by VladislavAntonyuk** [comment]
StackLayout (+ Vertical and Horizontal) currently doesn't work well with scrollview. Replace them with grid

**Comment by angelru** [comment]
> StackLayout (+ Vertical and Horizontal) currently doesn't work well with scrollview. Replace them with grid

replace all Stack by Grid? Let's see how I manage it for the baselayout...

**Comment by VladislavAntonyuk** [comment]
@angelru Could you please create an issue in .NET MAUI repo?

**Comment by angelru** [comment]
@VladislavAntonyuk Do you mean that it is a problem of .NET MAUI?

**Comment by VladislavAntonyuk** [comment]
As you closed the issue I suppose replacing StackLayout with Grid solved the issue, but scrolling should work with StackLayout as well
