### ISSUE TITLE
[BUG] CompareConverter sample does not work (Label does not change color)

### ISSUE THREAD

**Issue by michelmoorlag** [CommunityToolkit/Maui#796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I open the samples and go to the CompareConverterPage the Label does not change color when sliding the range silder.

### Expected Behavior

I expect the label to change between Lightgreen and PaleVioletRed but it has always the default background color

### Steps To Reproduce

1. Checkout this repository
2. Open the samples solution
3. Set the CommunityToolkit.Maui.Sample as start project
4. Run it on Android
5. Open the Converters/CompareConverter Page
6. Move the range silder back and forth

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui

### Environment

```markdown
- .NET MAUI CommunityToolkit: Latest Repository
- OS: Windows10 Pro (22H2) Build: 19045.2251
- .NET MAUI: 7.1.00
```

### Anything else?

It can be fixed by adding the following to the page resource dictionary:

`            <Color x:Key="LightGreen">LightGreen</Color>
            <Color x:Key="PaleVioletRed">PaleVioletRed</Color>  
`
And the set the True- and FalseObject like this:
`TrueObject={StaticResource LightGreen}, FalseObject={ StaticResource PaleVioletRed}`

I created a branch with the fix but I get a 403 when I try to Push the branch.

**Comment by VladislavAntonyuk** [comment]
@michelmoorlag you need to fork the repository and then you will be able to push your changes

**Comment by michelmoorlag** [comment]
@VladislavAntonyuk, Can I then make a pull request from the fork and would that be helpfull?

**Comment by VladislavAntonyuk** [comment]
Yes, sure. All PRs are welcome, if you follow the flow described in readme. You are on the right way.

we have a plan to create some demos for newcomers from discussion to merged PRs

**Comment by michelmoorlag** [comment]
@VladislavAntonyuk 
Ok thank you. Should this bug be verified and approved first before I start? Or can I just fork, fix and request a pr?

I read the readme but its about the flow requesting new features, not about the technical details like you need to fork etc

**Comment by VladislavAntonyuk** [comment]
I reproduced the issue and removed the unverified label.

**Comment by pictos** [comment]
@michelmoorlag for bug fixes you can go and open a PR and reference this issue. Let me know if you need any help
