### ISSUE TITLE
[BUG] Popup height incorrect on iOS

### ISSUE THREAD

**Issue by WebGoose** [CommunityToolkit/Maui#800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Popup height on iOS is not calculated correctly when no size is set. The popup container is much bigger than the content it contains. 

iOS (incorrect)
![image](https://user-images.githubusercontent.com/5024960/205024153-41d47710-2f91-4be8-81af-36c3e22b90ce.png)

![image](https://user-images.githubusercontent.com/5024960/205024060-80f59ba4-def0-4c41-a9a4-79e4a9a2a594.png)

In the second image I set the VerticalLayoutOptions of the VerticalStackLayout to Center. 

I have tried setting the Color of the Popup to Transparent to see if it will hide it but that doesn't seem possible on iOS. It just stays white /grey. 

### Expected Behavior

The popup is the correct height without having to set a specific size

Android (correct)
![image](https://user-images.githubusercontent.com/5024960/205023913-7cc5733b-4b81-4ba2-98ea-6713a8a3f87e.png)

### Steps To Reproduce

Open the attached solution on iOS device

Click the button.

### Link to public reproduction project repository

https://dev.azure.com/gooseza/MauiBugs/_git/Popup

### Environment

```markdown
- .NET MAUI CommunityToolkit: 3.0.0
- OS: iOS
- .NET MAUI: Using VS 17.5.0 Preview 1.0
```

**Comment by sbkrishnan2506** [comment]
I am also facing the same issue; we cannot set the height of the popup dynamically. It should have the property to set the height based on the content height.

**Comment by janeyuhwian** [comment]
I'm also having the same issue...Can the height of the popup be set up dynamically?
