### ISSUE TITLE
[Proposal] SpeechToText

### ISSUE THREAD

**Issue by VladislavAntonyuk** [CommunityToolkit/Maui#808]
### Feature name

SpeechToText

### Link to discussion

https://github.com/CommunityToolkit/Maui/discussions/727

### Progress tracker

- [ ] Android Implementation
- [ ] iOS Implementation
- [ ] MacCatalyst Implementation
- [ ] Windows Implementation
- [ ] Tizen Implementation
- [ ] Unit Tests
- [ ] Samples
- [ ] Documentation

### Summary

Free Speech recognition functionality that is available online and offline.

More details with samples at https://vladislavantonyuk.azurewebsites.net/articles/Speech-recognition-with-.NET-MAUI

### Motivation

.NET MAUI has TextToSpeech. It's time to convert SpeechToText

### Detailed Design

https://developer.apple.com/documentation/speech
https://developer.android.com/reference/android/speech/SpeechRecognizer
https://learn.microsoft.com/en-us/uwp/api/windows.media.speechrecognition?view=winrt-22621

```csharp
public interface ISpeechToText: IAsyncDisposable
{
	Task<bool> RequestPermissions(CancellationToken cancellationToken);
	Task<string> Listen(CultureInfo culture, IProgress<string>? recognitionResult, CancellationToken cancellationToken);
}
```

### Usage Syntax

```markdown
var isAuthorized = await speechToText.RequestPermissions();
		if (isAuthorized)
		{
			try
			{
				RecognitionText = await speechToText.Listen(CultureInfo.GetCultureInfo(Locale?.Language ?? "en-us"), new Progress<string>(partialText =>
					{
						RecognitionText += partialText + " ";
					}), cancellationToken);
			}
			catch (Exception ex)
			{
				await Toast.Make(ex.Message).Show(cancellationToken);
			}
		}
		else
		{
			await Toast.Make("Permission denied").Show(cancellationToken);
		}
```

**Comment by brminnick** [comment]
Thanks @VladislavAntonyuk! 

Promoting to https://github.com/CommunityToolkit/Maui/labels/approved as we voted to approve it in the [December Standup](https://www.youtube.com/watch?v=JgRCbWTop64).

Technically, we should've opened the Proposal first before voting to approve said Proposal, but we'll let this one slide.

Submitting a Proposal doesn't require a vote from the core maintainers. It should start as a Discussion, and then once the Discussion is deemed feature-complete a Proposal can be opened.
