### ISSUE TITLE
[Proposal] SafeAreaEffect

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#81]
# SafeAreaEffect

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
  * [ ] iOS Support
  * [ ] Android Support
  * [ ] macOS Support
  * [ ] Windows Support
* [ ] Unit Tests: Not Started
* [ ] Sample: Not Started
* [ ] Documentation: Not Started

## Summary
[summary]: #summary

The SafeAreaEffect is an effect that can be added to any element through an attached property to indicate whether or not that element should take current safe areas into account. This is an area of the screen that is safe for all devices that use iOS 11 and greater. Specifically, it will help to make sure that content isn't clipped by rounded device corners, the home indicator, or the sensor housing on an iPhone X. The effect only targets iOS, meaning that on other platforms it does not do anything.

## Motivation
[motivation]: #motivation

## Detailed Design
[design]: #detailed-design

### SafeAreaEffect.shared.cs

```cs
public static class SafeAreaEffect
{
  public static readonly BindableProperty SafeAreaProperty ;

  public static SafeArea GetSafeArea(BindableObject view);
  public static void SetSafeArea(BindableObject view, SafeArea value);
}
```

### SafeAreaEffectRouter.shared.cs
```cs
public class SafeAreaEffectRouter : RoutingEffect
{

}
```

### SafeAreaEffectRouter.iOS.cs

```cs
public class SafeAreaEffectRouter : PlatformEffect
{
  protected override void OnAttached()
  {
	if (!IsEligibleToConsumeEffect)
		return;

	orientationDidChangeNotificationObserver = NSNotificationCenter.DefaultCenter.AddObserver(
		UIDevice.OrientationDidChangeNotification, _ => UpdateInsets());

	initialMargin = Element.Margin;
	UpdateInsets();
  }

  protected override void OnDetached()
  {
	if (!IsEligibleToConsumeEffect)
		return;

	if (orientationDidChangeNotificationObserver != null)
	{
		NSNotificationCenter.DefaultCenter.RemoveObserver(orientationDidChangeNotificationObserver);
		orientationDidChangeNotificationObserver?.Dispose();
		orientationDidChangeNotificationObserver = null;
	}

	Element.Margin = initialMargin;
  }
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<StackLayout VerticalAlignment="Center" SafeAreaEffect.SafeArea="true" HorizontalAlignment="Center" Width="400" Height="400">
  ...
</StackLayout>
```

### C# Usage

```cs
var stackLayout = new StackLayout();
SafeAreaEffect.SetSafeArea(stackLayout, new SafeArea(true));
```

**Comment by bcaceiro** [comment]
Hi! Will this be ported to MAUI?

**Comment by vhugogarcia** [comment]
Hello @brminnick,

I believe, we can fully discard/close this feature issue since it is already implemented by .NET MAUI natively. It is documented here: [https://learn.microsoft.com/en-us/dotnet/maui/ios/platform-specifics/page-safe-area-layout](https://learn.microsoft.com/en-us/dotnet/maui/ios/platform-specifics/page-safe-area-layout)

On the official documentation there is the following statement:
> The [Layout](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.layout) class defines a [IgnoreSafeArea](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.layout.ignoresafearea#microsoft-maui-controls-layout-ignoresafearea) property that ensures that content is positioned on an area of the screen that is safe for all iOS devices. This property can be set to false on any layout class, such as a [Grid](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.grid) or <Microsoft.Maui.Controls.StackLayout>, to perform the equivalent of this platform-specific.

I personally could confirm on my own personal projects that this indeed works as expected for the .NET MAUI layouts.

<img width="484" alt="image" src="https://github.com/CommunityToolkit/Maui/assets/1047398/d31a3b91-92ae-4cd2-9723-84eb781d9a42">


Let me know what do you think, please 👍🏻

**Comment by brminnick** [comment]
Right in! Thanks @vhugogarcia!
