### ISSUE TITLE
[BUG] "Snackbar" popup button pretty much unclickable

### ISSUE THREAD

**Issue by Mielesgames** [CommunityToolkit/Maui#812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The button you can add is almost completely behind the back button.
![image](https://user-images.githubusercontent.com/83580270/205924771-af604f25-ffe9-4fee-99d6-c95d5f809b6b.png)

These are the sizes of the buttons (the white part of the button is the only clickable part)

![image (10)](https://user-images.githubusercontent.com/83580270/205933541-3579d99f-80ac-4b6d-9815-d18bf002d3de.png)

### Expected Behavior

Its supposed to be above the back button of android

### Steps To Reproduce

1. Add "Snackbar" popup to your application.
2. Open the app in an android version where the back button isn't physical but just on your screen.
3. try clicking the button without pressing the "<" button

### Link to public reproduction project repository

Shouldn't be necessary, since it's really easy to reproduce

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS: Samsung galaxy A52s (the only phone I am able to test on)
- .NET MAUI:
I have no idea
```

### Proposal

1. an option to make the button move the "snackbar" a bit upwards so the button is easier to press
2. add a scale option so you get a bigger button/popup
3. make the popup move up a bit when it detects the back-button UI being in front of it

**Comment by Mielesgames** [comment]
And yes, it looks easy to press, but you have to realise that the Android buttons stretch over the entire bottom of your screen

**Comment by pictos** [comment]
@Mielesgames 
Could you attach a small repro?

**Comment by VladislavAntonyuk** [comment]
it was fixed by https://github.com/CommunityToolkit/Maui/issues/642. what is your library version?

**Comment by Mielesgames** [comment]
> it was fixed by #642. what is your library version?

1.3.0 since I am not able to update it.
(it will come up with this error)
![image](https://user-images.githubusercontent.com/83580270/206120508-01ec89a8-b8ce-4977-9e45-7b3cc7cbe9e7.png)

**Comment by VladislavAntonyuk** [comment]
Try update to version 2.0

**Comment by Mielesgames** [comment]
> Try update to version 2.0

I did that and now my app keeps crashing, I think that version isn't stable

**Comment by Mielesgames** [comment]
I ended up fixing it by upgrading to .NET 7 and updating the community toolkit.
Thanks for your help @VladislavAntonyuk
