### ISSUE TITLE
[BUG]  CS0436 "conflicts with the imported type"  when using community toolkit with a shared maui project

### ISSUE THREAD

**Issue by norfus** [CommunityToolkit/Maui#814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using .net communityToolkit  maui for two projects in a solution, one main executable and one shared library, the following error occurs

MainTest-master\MainTest-master\MainTest\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\TimePickerTextColorTo.g.shared.cs(41,89,41,124): warning CS0436: The type 'ColorAnimationExtensions_TimePicker' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\TimePickerTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_TimePicker' in 'MainTest.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\TimePickerTextColorTo.g.shared.cs'.

### Expected Behavior

No build errors should occur

### Steps To Reproduce

1. I create two maui project, one main that can run, and one with shared code
2. Reference the shared project from the main project
3. Then i add the community toolkit to the shared code projet
4. Then build the main project, build warnings/errors occur 

See below:

>C:\Users\xxx\source\repos\MainTest\MainTest\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\TimePickerTextColorTo.g.shared.cs(41,89,41,124): warning CS0436: The type 'ColorAnimationExtensions_TimePicker' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\TimePickerTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_TimePicker' in 'MainTest.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\TimePickerTextColorTo.g.shared.cs'.
2>C:\Users\xxx\source\repos\MainTest\MainTest\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\EditorTextColorTo.g.shared.cs(41,89,41,120): warning CS0436: The type 'ColorAnimationExtensions_Editor' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\EditorTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_Editor' in 'MainTest.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\EditorTextColorTo.g.shared.cs'.
2>C:\Users\xxx\source\repos\MainTest\MainTest\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\PickerTextColorTo.g.shared.cs(41,89,41,120): warning CS0436: The type 'ColorAnimationExtensions_Picker' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\PickerTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_Picker' in 'MainTest.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\PickerTextColorTo.g.shared.cs'.
2>C:\Users\xxx\source\repos\MainTest\MainTest\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\SearchBarTextColorTo.g.shared.cs(41,89,41,123): warning CS0436: The type 'ColorAnimationExtensions_SearchBar' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\SearchBarTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_SearchBar' in 'MainTest.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\SearchBarTextColorTo.g.shared.cs'.
2>C:\Users\xxx\source\repos\MainTest\MainTest\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\DatePickerTextColorTo.g.shared.cs(41,89,41,124): warning CS0436: The type 'ColorAnimationExtensions_DatePicker' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\DatePickerTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_DatePicker' in 'MainTest.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\DatePickerTextColorTo.g.shared.cs'.
2>C:\Users\xxx\source\repos\MainTest\MainTest\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\ButtonTextColorTo.g.shared.cs(41,89,41,120): warning CS0436: The type 'ColorAnimationExtensions_Button' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\ButtonTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_Button' in 'MainTest.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\ButtonTextColorTo.g.shared.cs'.
2>C:\Users\xxx\source\repos\MainTest\MainTest\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\RadioButtonTextColorTo.g.shared.cs(41,89,41,125): warning CS0436: The type 'ColorAnimationExtensions_RadioButton' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\RadioButtonTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_RadioButton' in 'MainTest.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\RadioButtonTextColorTo.g.shared.cs'.
2>C:\Users\xxx\source\repos\MainTest\MainTest\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\EntryTextColorTo.g.shared.cs(41,89,41,119): warning CS0436: The type 'ColorAnimationExtensions_Entry' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\EntryTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_Entry' in 'MainTest.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\EntryTextColorTo.g.shared.cs'.
2>C:\Users\xxx\source\repos\MainTest\MainTest\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\LabelTextColorTo.g.shared.cs(41,89,41,119): warning CS0436: The type 'ColorAnimationExtensions_Label' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\LabelTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_Label' in 'MainTest.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\LabelTextColorTo.g.shared.cs'.

### Link to public reproduction project repository

https://github.com/norfus/MainTest

### Environment

```markdown
- .NET MAUI CommunityToolkit: 2.0 or 3.0
- OS:Windows 10
- .NET MAUI: 6 or 7
```

**Comment by norfus** [comment]
> 
Great that its already fixed! Any idea when a new release will be available?

**Comment by brminnick** [comment]
Thanks! 

Short answer: Soon; in about a week. 

Long answer: We have a [high-priority bug](https://github.com/CommunityToolkit/Maui/issues/785) that will be fixed within the next few days. Once the fix for #785 has been merged we will publish a new Release 👍

**Comment by norfus** [comment]
Great, i saw the new release and no more build errors!  

Will you only support net7 forward or will there be any releases for net6?

**Comment by VladislavAntonyuk** [comment]
We do not plan downgrade to net 6.

so we nightly recommend upgrading to net 7
