### ISSUE TITLE
[BUG] Version 3.0.0 of the Maui Toolkit won't build for iOS .Net Maui app running Asp.net 7 targeting iOS 16

### ISSUE THREAD

**Issue by faceoffers28** [CommunityToolkit/Maui#817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I just updated the Maui Toolkit from 1.3.0 to 3.0.0. After upgrading, the app won't build using my Azure Pipeline. There is no real error. Downgrading to version 2.0.0 solved the problem.

### Expected Behavior

The app should build.

### Steps To Reproduce

Try to build an iOS app with Maui Toolkit 3.0.0 using Asp.net 7 targeting iOS 16.

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui/

### Environment

```markdown
- .NET MAUI CommunityToolkit: 3.0.0
- OS: iOS 16
- .NET MAUI: Asp.net 7 current
xamarin-sdk.sh 17_4_0_301
```

**Comment by brminnick** [comment]
Could you please provide a reproduction sample?

We build the .NET MAUI Community Toolkit using Azure Pipelines and can confirm it works.

My guess is there is something incorrect in your pipeline configuration.

**Comment by brminnick** [comment]
> Try to build an iOS app with Maui Toolkit 3.0.0 using Asp.net 7 targeting iOS 16

Why are you using the .NET MAUI Community Toolkit in an ASP.NET Core app?

**Comment by faceoffers28** [comment]
> 

Thanks! My pipeline is already using .Net 7.

**Comment by faceoffers28** [comment]
> Could you please provide a reproduction sample?
> 
> We build the .NET MAUI Community Toolkit using Azure Pipelines and can confirm it works.
> 
> My guess is there is something incorrect in your pipeline configuration.

Here is my build pipeline. https://github.com/microsoft/azure-pipelines-tasks/issues/17293

**Comment by brminnick** [comment]
The warning is in your Pipeline logs:
> ILLINK : warning MT0079: The recommended Xcode version for Microsoft.iOS 16.0.1478 is Xcode 14.0 or later. The current Xcode version (found in /Applications/Xcode_13.2.1.app/Contents/Developer) is 13.2.1. [/Users/runner/work/1/s/MyApp.csproj::TargetFramework=net7.0-ios15.4]

You need to use Xcode 14.0 or later.

**Comment by faceoffers28** [comment]
> The warning is in your Pipeline logs:
> 
> > ILLINK : warning MT0079: The recommended Xcode version for Microsoft.iOS 16.0.1478 is Xcode 14.0 or later. The current Xcode version (found in /Applications/Xcode_13.2.1.app/Contents/Developer) is 13.2.1. [/Users/runner/work/1/s/MyApp.csproj::TargetFramework=net7.0-ios15.4]
> 
> You need to use Xcode 14.0 or later.

@brminnick I already fixed that issue by using macos-12. That's not the problem.

**Comment by brminnick** [comment]
I assume your build works locally. 

If your builds only fail in your CI Pipeline, there is a misconfiguration in your CI pipeline. The logs from your CI pipeline is telling you that you are using the incorrect version of Xcode.

Here's information about how to select a different version of Xcode in Azure Pipelines: https://10xlearner.com/2021/12/15/how-to-specify-your-xcode-version-on-azure-pipelines/

I'm happy to re-open this if you can put together a reproduction sample that proves we have a bug in .NET MAUI Community Toolkit. But all of the data points you've provided point to a misconfiguration in your CI pipeline.

**Comment by faceoffers28** [comment]
@brminnick Again, I was just sharing my Azure Pipeline with you. I made a change to mac-os12 in order to build for iOS 16. That all works just fine. Anyway, I can close the issue. I just upgraded back to version 3.0.0 and the build worked. I have no idea why it didn't work the first time.

**Comment by faceoffers28** [comment]
brminnick Again, I was just sharing my Azure Pipeline with you. I made a change to mac-os12 in order to build for iOS 16. That all works just fine. Anyway, I can close the issue. I just upgraded back to version 3.0.0 and the build worked. I have no idea why it didn't work the first time.
