### ISSUE TITLE
[BUG] RefreshView doesn't hide loading icon when viewmodel inherits ObservableObject 

### ISSUE THREAD

**Issue by vankraster** [CommunityToolkit/Maui#819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the viewmodel binded to the page inherits from ObservableObject the RefreshView doesn't hide the loading icon after the command completes and it will reload but the loader will always be visible as in screenshot below
![image](https://user-images.githubusercontent.com/27769564/206729319-e503d170-40fe-44d4-8a3e-6243920d148f.png)

### Expected Behavior

The loader icon on RefreshView should hide after command finished

### Steps To Reproduce

I have downloaded the MAUI samples from   
https://github.com/dotnet/maui-samples/tree/main/6.0/UserInterface/Views/RefreshViewDemo
And I have installed on that project the CommunityToolkit.Mvvm version 8.0 then 8.1.0-preview1 and both has the same problem when the viewmodel inherits ObservableObject the scrollview doesn't hide the loading icon.

I have changed only this line of code, from this 
![image](https://user-images.githubusercontent.com/27769564/206729082-60e0e7e9-d2eb-4287-af97-93d1d5f3122e.png)

to this
![image](https://user-images.githubusercontent.com/27769564/206728947-ad8a15a1-f3f3-4000-9421-6c6fa3bdaf02.png)

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/6.0/UserInterface/Views/RefreshViewDemo

### Environment

```markdown
- .NET MAUI CommunityToolkit: 8.00 and 8.1.0 preview 1
- OS:
- .NET MAUI: 6.0.547+4-sha.10a8bbaaa-azdo.6885293
```

**Comment by pictos** [comment]
@vankraster, thanks for reporting an issue and helping these products to be better.
This issue has nothing to do with this project, you may want to raise this issue on the [Maui repo](https://github.com/dotnet/maui/issues/new/choose) or on the [MVVM repo](https://github.com/CommunityToolkit/dotnet/issues/new/choose)
