### ISSUE TITLE
[Proposal] SelectAllTextEffect

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#82]
# SelectAllTextEffect

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [ ] Unit Tests: Not Started
* [x] Sample
* [ ] Documentation: Not Started

## Summary
[summary]: #summary

Highlights all text when an InputView is selected

## Detailed Design
[design]: #detailed-design

### SelectAllTextEffect.shared.cs

```cs
public class SelectAllTextEffect : RoutingEffect
{
}
```

### SelectAllTextEffect.android.cs

```cs
public class SelectAllTextEffect : PlatformEffect
{
  EditText EditText => (EditText)Control;
  
  protected override void OnAttached() => EditText?.SetSelectAllOnFocus(true);
  
  protected override void OnDetached() => EditText?.SetSelectAllOnFocus(false);
}
```

### SelectAllTextEffect.ios.cs

```cs
public class SelectAllTextEffect : PlatformEffect
{
  protected override void OnAttached() => ApplyEffect(true);
  
  protected override void OnDetached() => ApplyEffect(false);
  
  void ApplyEffect(bool apply) => ApplyToControl(Control, apply);

  bool ApplyToControl<T>(T controlType, bool apply) => controlType switch
  {
	UITextField textField => ApplyToUITextField(textField, apply),
	UITextView => ApplyToUITextView(apply),
	_ => throw new NotSupportedException($"Control of type: {controlType?.GetType()?.Name} is not supported by this effect.")
  };
}
```

## Usage Syntax
[usage]: #usage-syntax

<!-- Here is an example from CharactersValidationBehavior:

### XAML Usage

```xml
<Entry
    <Entry.Effects>
        <local: SelectAllTextEffect/>
    </Entry.Effects>
</Entry>

```

### C# Usage

```cs
var entry = new Entry();
entry.Effects.Add(new SelectAllTextEffect());
```

**Comment by brminnick** [comment]
Blocked. Pending the result of https://github.com/CommunityToolkit/Maui/issues/124

**Comment by jsuarezruiz** [comment]
Will review this point in a .NET MAUI team meeting next week and after that, we can validate this proposal!

**Comment by pictos** [comment]
I'll use this one to draw the API to implement our `Effect`s as `Behavior` and after that go through all other `Effects` and see if it makes sense for all.

**Comment by VladislavAntonyuk** [comment]
@brminnick, @pictos seems like it can be closed as completed. any objections?
