### ISSUE TITLE
[BUG] CommunityToolkit.Maui 3.x isn't support for .Net6

### ISSUE THREAD

**Issue by JosueSquareSix** [CommunityToolkit/Maui#829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

CommunityToolkit.Maui 3.x isn't able to install in Maui Apps that uses .Net6

### Expected Behavior

CommunityToolkit.Maui 3.x should be able to install in Projects that have a reference of .Net6 likes CommunityToolkit.MVVM to keep using new features and avoid bugs fixed in the newest versions.

### Steps To Reproduce

1.- Create a Maui Blank project using .Net6.
2.- Install CommunityToolkit.Maui 3.x error message appears.

### Link to public reproduction project repository

VS Maui Blank projects.

### Environment

```markdown
- .NET MAUI CommunityToolkit: 3.x
- .NET MAUI: 6.0.547
```

**Comment by brminnick** [comment]
CommunityToolkit.Maui v3.0.0+ only target .NET 7

More information is available in the release announcement here: https://devblogs.microsoft.com/dotnet/whats-new-in-the-dotnet-maui-community-toolkit/#versions
