### ISSUE TITLE
[Proposal] SemanticEffect

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#83]
# SemanticEffect

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
  * [ ] iOS Support
  * [ ] Android Support
  * [ ] macOS Support
  * [ ] Windows Support
* [ ] Unit Tests: Not Started
* [ ] Sample: Not Started
* [ ] Documentation: Not Started

## Summary
[summary]: #summary

Provides descriptive text for screen readers to any VisualElement

## Detailed Design
[design]: #detailed-design

### SemanticEffect.shared.cs

```cs
public static class SemanticEffect
{
  public static readonly BindableProperty HeadingLevelProperty;
  public static readonly BindableProperty SemanticInclusionProperty;
  public static readonly BindableProperty DescriptionProperty;
  public static readonly BindableProperty HintProperty;

  public static HeadingLevel GetHeadingLevel(BindableObject view);
  public static void SetHeadingLevel(BindableObject view, HeadingLevel value);
  public static SemanticInclusion GetSemanticInclusion(BindableObject view) ;
  public static void SetSemanticInclusion(BindableObject view, SemanticInclusion value);
  public static string GetDescription(BindableObject bindable);
  public static void SetDescription(BindableObject bindable, string value);
  public static string GetHint(BindableObject bindable);
  public static void SetHint(BindableObject bindable, string value);
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<Entry local: SemanticEffect.Description="Text Input" />
```

### C# Usage

```cs
var entry = new Entry();
SemanticEffect.SetDescription(entry, "Text Input");
```

**Comment by pictos** [comment]
I believe that we will have this on .NET MAUI, so we don't need to migrate this one.
I'll ping @pureween and @rachelkang  to give the final word and close this issue.

**Comment by brminnick** [comment]
@jfversluis Just to verify before closing this - Semantic Effect can be closed because it will be included in .NET MAUI, right?

**Comment by PureWeen** [comment]
@brminnick yes

SemanticOrderView is the only thing currently in XCT that won't be apart of the first .NET MAUI release
