### ISSUE TITLE
[BUG] Cannot resolve type toolkit:mct:EventToCommandBehavior

### ISSUE THREAD

**Issue by enjoysmath** [CommunityToolkit/Maui#845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/1606391/209497606-9e39ad85-259e-4437-9f89-39906b38f934.png)

### Expected Behavior

For EventToCommandBehavior to be found

### Steps To Reproduce

Follow the instructions for installing the NuGet package.  A ReadMe.txt pops up.  Copy / paste in the xmlns include line into your MainPage.xaml.  Try to create a behavior on "Appearing" like the screenshot shows.

### Link to public reproduction project repository

I don't have one (it's for a private project).

### Environment

```markdown
- .NET MAUI CommunityToolkit: Latest Release
- OS: Windows 10 21H2 (11?)
- .NET MAUI: Just installed this last month
```

### Anything else?

I followed the instructions.  What I want is a refreshed CollectionView each page load - that's my ultimate goal.  Which is why I'm using Maui's Toolkit.  But it doesn't work out-of-the-box.

Any ideas?

**Comment by pictos** [comment]
@enjoysmath 
Could you attach a small repro?

**Comment by marcmognol** [comment]
Hi,

Isn't it a Typo?
As per the issue's title, you wrote:

toolkit:mct:EventToCommandBehavior

Instead of:

mct:EventToCommandBehavior

Because your namespace is "mct"

Marc

**Comment by enjoysmath** [comment]
No Typo.  Found the issue.  You have to append
builder[....].UseMauiToolkit() (or something similar) in your
MauiProgram.cs (wherever the builder code is)

**Comment by brminnick** [comment]
Thanks for confirming @enjoysmath!

For anyone else finding this Issue in the future, here's more info in our docs: https://learn.microsoft.com/dotnet/communitytoolkit/maui/get-started#using-the-nuget-packages
