### ISSUE TITLE
Popup Position in Mac Desktop off bound when moving across screen (Multiple Monitor)

### ISSUE THREAD

**Issue by cgp1976** [CommunityToolkit/Maui#857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have tested the following only of Mac Desktop.

Before Moving Screen
<img width="567" alt="Untitled" src="https://user-images.githubusercontent.com/82589862/210165306-81057f3d-0631-4779-ae8b-7d51acceba15.png">

After Moving To another Screen
<img width="567" alt="Untitled 2" src="https://user-images.githubusercontent.com/82589862/210165309-8d0bd8a6-b28b-4e54-b501-0071b7a34db7.png">

### Expected Behavior

 it should be positioned  correctly within the popup page area

### Steps To Reproduce

Just go multiple popup page and click on the simple popup and move across screen, eventually you will get the popup position moving of out bound.

### Link to public reproduction project repository

nil

### Environment

```markdown
nil
```

**Comment by pictos** [comment]
Maybe it's fixed by #831

**Comment by cgp1976** [comment]
Hi,  thanks for the info.

Based on my understanding after looking at it. it's a separate issues . The issue I am reporting is on multiple screen when moving across monitor. it will reposition the popup randomly be it center popup or anchor popup.

**Comment by cgp1976** [comment]
some key findings..  perhaps will be helpful.  it only happen when you move your window across monitor from up and down direction. 

My monitor layout

<img width="573" alt="Untitled 3" src="https://user-images.githubusercontent.com/82589862/210288415-8c9be874-c2d4-49a6-bb4a-2d69bc324d92.png">

From Bottom Screen Move to Top Right or Top Right move back to bottom screen.

**Comment by vhugogarcia** [comment]
This issue has been fixed as our friend @pictos mentioned on a previous comment using the latest version of .NET MAUI Community Toolkit. I'm attaching a video sample below using 2 monitors _(extended, moving the window from one monitor to another on the first 5 seconds of the video, and more tests in the following seconds of the video)_ :


https://github.com/CommunityToolkit/Maui/assets/1047398/1fffe1b5-6f94-4b53-a81b-f73a7ab60bae



@brminnick I believe we can safely close this issue.
