### ISSUE TITLE
[Proposal] Make StateContainer work with ContentPage 

### ISSUE THREAD

**Issue by Strypper** [CommunityToolkit/Maui#859]
### Feature name

StateContainer

### Link to discussion

[Discussion](https://github.com/CommunityToolkit/Maui/discussions/860)

### Progress tracker

- [X] Android Implementation
- [X] iOS Implementation
- [X] MacCatalyst Implementation
- [X] Windows Implementation
- [X] Tizen Implementation
- [X] Unit Tests
- [X] Samples
- [X] Documentation

### Summary

I use the state container to create adaptive layout but the problem is 
toolkit:StateContainer.CurrentState="{x:Binding CurrentDeviceState}" MUST be attached to Stacklayout or a grid
It would be awesome if it work with Content Page

### Motivation

Adaptive layout

### Detailed Design

None

### Usage Syntax

```markdown
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
             
             x:Class="TestStateContainer.MainPage"
             SizeChanged="BasePage_SizeChanged"
toolkit:StateContainer.CurrentState="{Binding MyCurrentState}">

    <ScrollView>
            <toolkit:StateContainer.StateViews>
                <VerticalStackLayout toolkit:StateView.StateKey="Phone">
                    <ActivityIndicator IsRunning="True" />
                    <Label Text="Loading Content..." />
                    <Rectangle HeightRequest="1000"
                               WidthRequest="100"
                               Fill="Red"/>
                </VerticalStackLayout>
                <Label toolkit:StateView.StateKey="Tablet" Text="Success!" />
                <Label toolkit:StateView.StateKey="Desktop" Text="Default Content" />
            </toolkit:StateContainer.StateViews>
    </ScrollView>

</ContentPage>
```

**Comment by brminnick** [comment]
Thanks for the proposal @Strypper!

Please first open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) where you can propose its API design and iterate over it with fellow community members. 

I am closing this Proposal because it lacks a detailed design and doesn't link to a Discussion where we can review the conversation around its design/implementation.

Once you have matured its design and prototyped the implementation, please open a new Proposal that we can review/approve before moving forward to implementing the feature via a PR.

**Comment by Strypper** [comment]
> Thanks for the proposal @Strypper!
> 
> Please first open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) where you can propose its API design and iterate over it with fellow community members.
> 
> I am closing this Proposal because it lacks a detailed design and doesn't link to a Discussion where we can review the conversation around its design/implementation.
> 
> Once you have matured its design and prototyped the implementation, please open a new Proposal that we can review/approve before moving forward to implementing the feature via a PR.

Hi Brandon I have create a discussion please check it out
