### ISSUE TITLE
[BUG] UseMauiCommunityToolkitMediaElement()` must be chained to `.UseMauiApp<T>()`

### ISSUE THREAD

**Issue by JoacimWall** [CommunityToolkit/Maui#867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi 
I have done a MAUI library(nuget) that implements a videoPlayer(fullscreen Droid and other stuff that is specific for my customers) that use the MAUI MediaElement. 

I do the registration of the 
UseMauiCommunityToolkitMediaElement() inside the library so I don't want the be forced to add this to the consuming app of the lib.  

//Regards Joacim

### Expected Behavior

Not e forced to do this twice.

### Steps To Reproduce

Create a MAUI lib 
create a function in the lib that you use from the apps MauiProgram.cs

  
public static MauiAppBuilder UseFmShared(this MauiAppBuilder builder)
{
   builder.UseMauiCommunityToolkitMediaElement();
  return builder;
}

### Link to public reproduction project repository

Not needed

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS: MAC Ventura 13.1 
- .NET MAUI:
Visual Studio Professional 2022 for Mac Preview
Version 17.5 Preview (17.5 build 1095)

Xamarin.Mac
Version: 9.0.0.27 Visual Studio Professional
Hash: 933c6c2c9
Branch: xcode14.1
Build date: 2022-11-22 02:00:36-0500

Xamarin.iOS
Version: 16.1.1.27 Visual Studio Professional
Hash: 933c6c2c9
Branch: xcode14.1
Build date: 2022-11-22 02:00:37-0500

Xamarin Designer
Version: 17.5.2.64
Hash: 627f860876
Branch: remotes/origin/d17-5
Build date: 2022-12-13 00:19:58 UTC

Xamarin.Android
Version: 13.1.0.1 (Visual Studio Professional)
Commit: xamarin-android/d17-4/13ba222
Android SDK: /Users/joacimwall/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)
		8.1  (API level 27)
		11.0 (API level 30)
		10.0 (API level 29)
		9.0  (API level 28)
		13.0 (API level 33)
```

### Anything else?

I can move this line UseMauiCommunityToolkitMediaElement() to the consuming app but it would be nice if I was not force to do this. The previous preview versions of MediaElement did not force me to do this.

//Thanks Joacim

**Comment by brminnick** [comment]
Duplicate https://github.com/CommunityToolkit/Maui/issues/501
