### ISSUE TITLE
[BUG] ReadMe.Txt doesn't match MAUI template 

### ISSUE THREAD

**Issue by CliffAgius** [CommunityToolkit/Maui#868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you install the CT from NuGet it displays a ReadMe.txt in VS22 this is very good but the code snippet of how to initialise CT with the Builder isn't using the same format as the File->New template.

### Expected Behavior

It currently has:

```
public static MauiApp CreateMauiApp()
{
    var builder = MauiApp.CreateBuilder();

    // Initialise the toolkit
	builder.UseMauiApp<App>().UseMauiCommunityToolkit();

    // the rest of your logic...
}

```
But really it should be:

```
public static MauiApp CreateMauiApp()
	{
		var builder = MauiApp.CreateBuilder();
		builder
			.UseMauiApp<App>()
            // Initialise the toolkit
			.UseMauiCommunityToolkit()
			.ConfigureFonts(fonts =>
			{
				fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
				fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
			});

		return builder.Build();
	}
```

I know it's a small change and a fairly obvious one but for those new to Dotnet and MAUI this could be confusing, plus it's nice for the ability to copy and paste the snippet from the ReadMe.txt into the MainProgram.cs file.

### Steps To Reproduce

text changes to Init text file no repo needed.

### Link to public reproduction project repository

N/A

### Environment

```markdown
- .NET MAUI CommunityToolkit: 3.1.0
- OS: Windows VS22
- .NET MAUI:
```

### Anything else?

Happy to fix this if the team think it needs fixing.

**Comment by kphillpotts** [comment]
Agree that we could make the format the same as in the default template.

eg. `.UseMauiCommunityToolkit()` on it's own line.

**Comment by brminnick** [comment]
Good call out @CliffAgius! As a new developer, I know how tricky it can be when one sample doesn't exactly match my code (or, in this case, my templated code).

My only concern is that we will be implying that the developer must also use those fonts to use `CommunityToolkit.Maui`.

Maybe there's a way we could use comments to let users know that they don't _have_ to add the fonts to use the toolkit.

```cs
public static MauiApp CreateMauiApp()
{
  var builder = MauiApp.CreateBuilder();
  builder
	  .UseMauiApp<App>()
            // Initialize the toolkit here
	  .UseMauiCommunityToolkit()
            // After initializing the toolkit, optionally add additional fonts
	  .ConfigureFonts(fonts =>
	  {
		  fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
		  fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
	  });
  
  return builder.Build();
}

**Comment by brminnick** [comment]
@CliffAgius Could you also help us cover the same scenario in `CommunityToolkit.Maui.Markup` and the Docs for both:
- `CommunityToolkit.Maui` Docs: https://learn.microsoft.com/dotnet/communitytoolkit/maui/get-started#using-the-nuget-packages
- `CommunityToolkit.Maui.Markup` `Readme.txt`: https://github.com/CommunityToolkit/Maui.Markup/blob/main/src/CommunityToolkit.Maui.Markup/ReadMe.txt
- `CommunityToolkit.Maui.Markup` Docs: https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/markup/markup
  - I see know that we are missing the [same Getting Started steps that are included in the `CommunityToolkit.Maui` docs](https://learn.microsoft.com/dotnet/communitytoolkit/maui/get-started#using-the-nuget-packages)

**Comment by VladislavAntonyuk** [comment]
maybe we should omit `.ConfigureFonts(fonts =>`. I would suggest removing it from .NET MAUI template as well
