### ISSUE TITLE
[Proposal] VisualFeedbackEffect

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#87]
# VisualFeedbackEffect

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
  * [ ] iOS Support
  * [ ] Android Support
  * [ ] macOS Support
  * [ ] Windows Support
* [ ] Unit Tests: Not Started
* [ ] Sample: Not Started
* [ ] Documentation: Not Started

## Summary
[summary]: #summary

Adds color to a VisualElement when touched

## Detailed Design
[design]: #detailed-design

```cs
public class VisualFeedbackEffect : RoutingEffect
{
  public static readonly BindableProperty FeedbackColorProperty;

  public static Color GetFeedbackColor(BindableObject view);
  public static void SetFeedbackColor(BindableObject view, Color value);
  public static bool IsFeedbackColorSet(BindableObject element);
}
```

### XAML Usage

```xml
<Button VisualFeedbackEffect.Color="Red" />
```

### C# Usage

```cs
var button = new Button();
VisualFeedbackEffect.SetColor(button, Colors.Red):
```

**Comment by brminnick** [comment]
Blocked. Pending the result of https://github.com/CommunityToolkit/Maui/issues/124

**Comment by vhugogarcia** [comment]
@brminnick @pictos , I think this issue can be closed in favor of TouchEffect, TouchEffect in MAUI will cover this feature automatically, per what I understand so far. However, let me know what you think. 

Thank you 😃

**Comment by CliffAgius** [comment]
This issue is stale and as mentioned is also covered by the TouchEffect.

Happy to re-open if I am wrong. 😉
