### ISSUE TITLE
[BUG] IconTintColorBehavior doesnt work inside SwipeItemView

### ISSUE THREAD

**Issue by get-flat** [CommunityToolkit/Maui#886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file.

### Current Behavior

IconTintColorBehavior not applied to SwipeItemView

![IconTint_Issue](https://user-images.githubusercontent.com/74671895/211511361-070f4d55-6680-4fc1-9578-5e247f7bbf62.png)

```
<Grid RowDefinitions="Auto, *">
        <Image Source="dotnet_bot.png" WidthRequest="50" HeightRequest="50">
            <Image.Behaviors>
                <!--WORKS-->
                <toolkit:IconTintColorBehavior TintColor="Red" />
            </Image.Behaviors>
        </Image>

        <CollectionView Grid.Row="1" VerticalScrollBarVisibility="Never">
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <SwipeView>
                        <SwipeView.RightItems>
                            <SwipeItems>
                                <SwipeItemView>
                                    <Image Source="dotnet_bot.png" WidthRequest="50" HeightRequest="50">
                                        <Image.Behaviors>
                                            <!--DOES NOT WORK-->
                                            <toolkit:IconTintColorBehavior TintColor="Yellow" />
                                        </Image.Behaviors>
                                    </Image>
                                </SwipeItemView>
                            </SwipeItems>
                        </SwipeView.RightItems>

                        <!-- Content -->
                        <HorizontalStackLayout>
                            <Label BackgroundColor="Green" Margin="0,0,0,15" Padding="10" FontSize="Large" Text="{Binding .}" />
                            <Image Source="dotnet_bot.png" WidthRequest="50" HeightRequest="50">
                                <Image.Behaviors>
                                    <!--WORKS-->
                                    <toolkit:IconTintColorBehavior TintColor="Blue" />
                                </Image.Behaviors>
                            </Image>
                        </HorizontalStackLayout>
                </SwipeView>
                </DataTemplate>
            </CollectionView.ItemTemplate>
            <CollectionView.ItemsSource>
                <syscollections:ArrayList>
                    <x:String>Item 1</x:String>
                    <x:String>Item 2</x:String>
                </syscollections:ArrayList>
            </CollectionView.ItemsSource>
        </CollectionView>
    </Grid>
```

### Expected Behavior

IconTintColorBehavior should work inside SwipeItemView

### Steps To Reproduce

1. Create a new MAUI app
2. use code snippet provided

### Link to public reproduction project repository

[maui_toolkit_886](https://github.com/get-flat/maui_toolkit_886)

### Environment

```markdown
- .NET MAUI CommunityToolkit: 3.1.0
- OS: Android NET 7
- .NET MAUI:
```

**Comment by get-flat** [comment]
:(
https://github.com/get-flat/maui_toolkit_886

**Comment by vhugogarcia** [comment]
After reviewing the issue more in depth. I found the following insights that may help to solve the issue or maybe set a note in the documentation about it.

- The issue also occurs in iOS
- By debugging the MCT source code project with the sample code shared on this ticket, I noticed that the Behavior is never attached to the element using the `OnAttachedTo`. For example, I set a few breakpoints on the [https://github.com/CommunityToolkit/Maui/blob/main/src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.ios.cs](IconTintColorBehavior.ios.cs) and they are never hit.

My guess is that due to the SwipeView hides the element on screen when loaded, the Behavior is not attached, so it needs to manually be attached when reveling the element in the screen. So, the solution would be adding the Behavior to the image during the Swipe reveal event.

I'm not sure if this is an expected result or if there is something that can be fixed. 

I just wanted to share some insights and feedback. Thank you 👍🏻 

cc: @brminnick @pictos

**Comment by pictos** [comment]
@vhugogarcia You're my hero. Thankcyou so much for taking time to look into it. Yeah, we can investigate a little bit more, but looks like a maui issue. Maybe there's something missing on the implementation.
One question, does the swipe view content appears on the live visual tree? when it's hide

**Comment by vhugogarcia** [comment]
Hello @pictos ,

The SwipeView content appears on the live visual tree, however, the SwipeItemView content (image) does not appear when it is hidden and even after I reveal it the SwipeItemView content does not appear in the live visual tree.

I even tried to add other elements different from image and they just don't appear on the live visual tree. Maybe as you said. it can be an issue on .NET MAUI, if yes, how can we transfer this ticket to the **dotnet/maui** repository or what do you suggest?

<img width="530" alt="image" src="https://user-images.githubusercontent.com/1047398/211825747-93f4834d-8252-49ff-8e70-4edc96cd6ff3.png">

cc: @brminnick

**Comment by pictos** [comment]
Closing this issue here, please track its progress on the .NET MAUI repo.

**Comment by BlackThornMusang** [comment]
#13765 fixes do not fix this bug
