### ISSUE TITLE
[Proposal] Color Conversion Extensions

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#89]
# ColorConversionExtensions

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Sample
* [x] Documentation

## Summary
[summary]: #summary

Extension methods for Color, e.g. ToRgbString, ToCmykString

## Detailed Design
[design]: #detailed-design

```cs
    public static class ColorConversionExtensions
    {
        /// <returns>RGB(255, 255, 255)</returns>
        public static string ToRgbString(this Color c) => $"RGB({c.GetByteRed()},{c.GetByteGreen()},{c.GetByteBlue()})";

        /// <returns>RGBA(255, 255, 255, 255)</returns>
        public static string ToRgbaString(this Color c) =>
            $"RGBA({c.GetByteRed()}, {c.GetByteGreen()}, {c.GetByteBlue()}, {c.GetByteAlpha()})";

        /// <returns>#FFFFFF</returns>
        public static string ToHexRgbString(this Color c) =>
            $"#{c.GetByteRed():X2}{c.GetByteGreen():X2}{c.GetByteBlue():X2}";

        /// <returns>#FFFFFFFF</returns>
        public static string ToHexRgbaString(this Color c) =>
            $"#{c.GetByteRed():X2}{c.GetByteGreen():X2}{c.GetByteBlue():X2}{c.GetByteAlpha():X2}";

        /// <returns>CMYK(100%,100%,100%,100%)</returns>
        public static string ToCmykString(this Color c) =>
            $"CMYK({c.GetPercentCyan():P},{c.GetPercentMagenta():P},{c.GetPercentYellow():P},{c.GetPercentBlackKey():P})";

        /// <returns>CMYK(100%,100%,100%,100%,100%)</returns>
        public static string ToCmykaString(this Color c) =>
            $"CMYKA({c.GetPercentCyan():P},{c.GetPercentMagenta():P},{c.GetPercentYellow():P},{c.GetPercentBlackKey():P},{c.Alpha:P})";

        /// <returns>HSLA(360,100%,100%)</returns>
        public static string ToHslString(this Color c) => $"HSL({c.GetHue():P},{c.GetSaturation():P},{c.GetLuminosity():P})";

        /// <returns>HSLA(360°,100%,100%,100%)</returns>
        public static string ToHslaString(this Color c) =>
            $"HSLA({c.GetDegreeHue()}°,{c.GetSaturation():P},{c.GetLuminosity():P},{c.Alpha:P})";

        public static Color WithRed(this Color baseColor, double newR) =>
            Color.FromRgba(newR, baseColor.Green, baseColor.Blue, baseColor.Alpha);

        public static Color WithGreen(this Color baseColor, double newG) =>
            Color.FromRgba(baseColor.Red, newG, baseColor.Blue, baseColor.Alpha);

        public static Color WithBlue(this Color baseColor, double newB) =>
            Color.FromRgba(baseColor.Red, baseColor.Green, newB, baseColor.Alpha);

        public static Color WithAlpha(this Color baseColor, double newA) =>
            Color.FromRgba(baseColor.Red, baseColor.Green, baseColor.Blue, newA);

        public static Color WithRed(this Color baseColor, byte newR) =>
            Color.FromRgba((double)newR / 255, baseColor.Green, baseColor.Blue, baseColor.Alpha);

        public static Color WithGreen(this Color baseColor, byte newG) =>
            Color.FromRgba(baseColor.Red, (double)newG / 255, baseColor.Blue, baseColor.Alpha);

        public static Color WithBlue(this Color baseColor, byte newB) =>
            Color.FromRgba(baseColor.Red, baseColor.Green, (double)newB / 255, baseColor.Alpha);

        public static Color WithAlpha(this Color baseColor, byte newA) =>
            Color.FromRgba(baseColor.Red, baseColor.Green, baseColor.Blue, (double)newA / 255);

        public static Color WithCyan(this Color baseColor, double newC) =>
            Color.FromRgba((1 - newC) * (1 - baseColor.GetPercentBlackKey()),
                           (1 - baseColor.GetPercentMagenta()) * (1 - baseColor.GetPercentBlackKey()),
                           (1 - baseColor.GetPercentYellow()) * (1 - baseColor.GetPercentBlackKey()),
                           baseColor.Alpha);

        public static Color WithMagenta(this Color baseColor, double newM) =>
            Color.FromRgba((1 - baseColor.GetPercentCyan()) * (1 - baseColor.GetPercentBlackKey()),
                           (1 - newM) * (1 - baseColor.GetPercentBlackKey()),
                           (1 - baseColor.GetPercentYellow()) * (1 - baseColor.GetPercentBlackKey()),
                           baseColor.Alpha);

        public static Color WithYellow(this Color baseColor, double newY) =>
            Color.FromRgba((1 - baseColor.GetPercentCyan()) * (1 - baseColor.GetPercentBlackKey()),
                           (1 - baseColor.GetPercentMagenta()) * (1 - baseColor.GetPercentBlackKey()),
                           (1 - newY) * (1 - baseColor.GetPercentBlackKey()),
                           baseColor.Alpha);

        public static Color WithBlackKey(this Color baseColor, double newK) =>
            Color.FromRgba((1 - baseColor.GetPercentCyan()) * (1 - newK),
                           (1 - baseColor.GetPercentMagenta()) * (1 - newK),
                           (1 - baseColor.GetPercentYellow()) * (1 - newK),
                           baseColor.Alpha);

        public static byte GetByteRed(this Color c) => ToByte(c.Red * 255);

        public static byte GetByteGreen(this Color c) => ToByte(c.Green * 255);

        public static byte GetByteBlue(this Color c) => ToByte(c.Blue * 255);

        public static byte GetByteAlpha(this Color c) => ToByte(c.Alpha * 255);

        // Hue is a degree on the color wheel from 0 to 360. 0 is red, 120 is green, 240 is blue.
        public static double GetDegreeHue(this Color c) => c.GetHue() * 360;

        // Note : double Percent R, G and B are simply Color.R, Color.G and Color.B

        public static double GetPercentBlackKey(this Color c) => 1 - Math.Max(Math.Max(c.Red, c.Green), c.Blue);

        public static double GetPercentCyan(this Color c) =>
            (1 - c.Red - c.GetPercentBlackKey()) / (1 - c.GetPercentBlackKey());

        public static double GetPercentMagenta(this Color c) =>
            (1 - c.Green - c.GetPercentBlackKey()) / (1 - c.GetPercentBlackKey());

        public static double GetPercentYellow(this Color c) =>
            (1 - c.Blue - c.GetPercentBlackKey()) / (1 - c.GetPercentBlackKey());

        public static Color ToInverseColor(this Color baseColor) =>
            Color.FromRgb(1 - baseColor.Red, 1 - baseColor.Green, 1 - baseColor.Blue);

        public static Color ToBlackOrWhite(this Color baseColor) => baseColor.IsDark() ? Colors.Black : Colors.White;

        public static Color ToBlackOrWhiteForText(this Color baseColor) =>
            baseColor.IsDarkForTheEye() ? Colors.White : Colors.Black;

        public static Color ToGrayScale(this Color baseColor)
        {
            var avg = (baseColor.Red + baseColor.Blue + baseColor.Green) / 3;
            return Color.FromRgb(avg, avg, avg);
        }

        public static bool IsDarkForTheEye(this Color c) =>
            (c.GetByteRed() * 0.299) + (c.GetByteGreen() * 0.587) + (c.GetByteBlue() * 0.114) <= 186;

        public static bool IsDark(this Color c) => c.GetByteRed() + c.GetByteGreen() + c.GetByteBlue() <= 127 * 3;

        static byte ToByte(double input)
        {
            if (input < 0)
                return 0;
            if (input > 255)
                return 255;
            return (byte)Math.Round(input);
        }
    }
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

N/A

### C# Usage

```cs
var rgbString = Colors.Grey.ToRgbString();
```

**Comment by PieEatingNinjas** [comment]
I could write some unit tests for this, if you want.

**Comment by brminnick** [comment]
Thanks @PieEatingNinjas! That'd be great!!

Assigned ✅

**Comment by PieEatingNinjas** [comment]
The RGBA string is produced as follows: `RGBA(255, 255, 255, 255)` (mind the space after each comma)
All other outputs (like `RGB(255,255,255)`) are without a space after each comma. 

I'd propose to make this consistent. What is preferred, with or without a space?

**Comment by PieEatingNinjas** [comment]
I’ve got some test data by now. 
Just curious about what is preferred: adding the test data (about 200 different colors) hardcoded in code (ClassData) or reading it from a local csv file?

**Comment by brminnick** [comment]
Nice! Let's just add it in code 👍

**Comment by PieEatingNinjas** [comment]
I’ll make it so! 😁
It’s a lot of work generating all the test data, so it’ll probably take a while before I got everything tested.

**Comment by PieEatingNinjas** [comment]
Just a small update: making good progress on this! Writing the unit tests already has been valuable as I identified some 'issues', but I'll elaborate on that when the PR arrives.
![image](https://user-images.githubusercontent.com/13808075/144402243-95b58633-dd42-454c-8333-02b5a567c67b.png)
(that's currently 4451 tests)

Got a small question though: The `GetPercentXXX`-methods and the `GetDegreeHue`-method return doubles. Is that intentionally? Do we really need this precision? Any decimal value in `Color` and in our extension methods is of type `float`.

**Comment by brminnick** [comment]
> Do we really need this precision

Good catch! We do not need the precision of `double`. I'm ok with changing it to `float` if doesn't introduce cascading breaking changes.

**Comment by PieEatingNinjas** [comment]
Still going strong with these tests, there is light at the end of the tunnel😅
While writing tests for the `With*` methods, I started to wonder what behavior we want to have when passing in 'out-of-bound' values. The current behavior is that when passing in values that are too large, the max value will be set. When passing in too little values, the minimum value is set. 

This is also how I was writing my tests, BUT while doing tests, I noticed that the `Color `class already implements a `WithAlpha` method. So unknowingly I was testing that method instead of our extension method and that's how I noticed that the behavior of that method is different. See [MAUI.Graphics.Color](https://github.com/dotnet/Microsoft.Maui.Graphics/blob/1dd8e4060afa031c8f568f8341e16244d752bd8b/src/Microsoft.Maui.Graphics/Color.cs#L125). They do a check: if the provided value doesn't fall withing the expected range, the original Color is returned.

Wouldn't it be better to align with this behavior as well?

**Comment by PieEatingNinjas** [comment]
While looking at the `Color` class, I noticed the [Parse method](https://github.com/dotnet/Microsoft.Maui.Graphics/blob/1dd8e4060afa031c8f568f8341e16244d752bd8b/src/Microsoft.Maui.Graphics/Color.cs#L508). If you look at the comments, you'll notice that they expect an Alpha always as a value between 0 and 1, where as we return it as a percentage. Should we align with this in the `To*String` methods? Also notice that for the Hue degree value, they don't expect a '°' sign.

**Comment by PieEatingNinjas** [comment]
@brminnick Have you been able to look at my comments above? Now that the holidays are over, I would love to pick up where I left and finalize these unit tests.
Let me list my remark for convenience's sake :-)
* The behavior of current implementation of the `With*` extension methods is different compared to the baked-in [WithAlpa](https://github.com/dotnet/Microsoft.Maui.Graphics/blob/1dd8e4060afa031c8f568f8341e16244d752bd8b/src/Microsoft.Maui.Graphics/Color.cs#L125) method. We return min/max values if the given value doesn't fall within the expected range, whereas the baked-in `WithAlpa` returns the original color when the provided value isn't correct. Should we align with this behavior?
* As there is already a `WithAlpha` method on the `Color` class, I guess we can omit the `WithAlpha` extension method from the toolkit?
* The static [Parse method](https://github.com/dotnet/Microsoft.Maui.Graphics/blob/1dd8e4060afa031c8f568f8341e16244d752bd8b/src/Microsoft.Maui.Graphics/Color.cs#L508) of the `MAUI.Graphics.Color` class supports some particular strings as input. If you look at the comments, you'll notice that they expect an Alpha value to be always between 0 and 1. In our `To*String` extension methods, we return Alpha values as a percentage (or percentage of 255). Should we align with what the MAUI framework supports? Also, notice that for the Hue degree value for example, they don't expect a '°' sign which we do include.

**Comment by brminnick** [comment]
Hey @PieEatingNinjas! So sorry for not responding and thus blocking you on this 

> If we align, devs could call one of our To*String methods and use that result again in the Color Parse method to recreate the color.

I think that's a great idea!

> The behavior of current implementation of the With* extension methods is different compared to the baked-in [WithAlpa](https://github.com/dotnet/Microsoft.Maui.Graphics/blob/1dd8e4060afa031c8f568f8341e16244d752bd8b/src/Microsoft.Maui.Graphics/Color.cs#L125) method. We return min/max values if the given value doesn't fall within the expected range, whereas the baked-in WithAlpa returns the original color when the provided value isn't correct. Should we align with this behavior?

Let's throw an `ArgumentOutOfRangeException` if the given value is outside of the expected range.

> As there is already a WithAlpha method on the Color class, I guess we can omit the WithAlpha extension method from the toolkit?

Good catch! Yup, we can drop `WithAlpha` from the .NET MAUI Community Toolkit

> The static [Parse method](https://github.com/dotnet/Microsoft.Maui.Graphics/blob/1dd8e4060afa031c8f568f8341e16244d752bd8b/src/Microsoft.Maui.Graphics/Color.cs#L508) of the MAUI.Graphics.Color class supports some particular strings as input. If you look at the comments, you'll notice that they expect an Alpha value to be always between 0 and 1. In our To*String extension methods, we return Alpha values as a percentage (or percentage of 255). Should we align with what the MAUI framework supports? Also, notice that for the Hue degree value for example, they don't expect a '°' sign which we do include.

Yup, let's align to what the .NET MAUI Framework supports. We can drop the '°' sign, then

**Comment by PieEatingNinjas** [comment]
Thank you for your feedback @brminnick ! I'll continue on this as soon as I can 😊
