### ISSUE TITLE
[Proposal] ImageResource Markup Extension

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#90]
# ImageResourceMarkupExtension

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
  * [ ] iOS Support
  * [ ] Android Support
  * [ ] macOS Support
  * [ ] Windows Support
* [ ] Unit Tests: Not Started
* [ ] Sample: Not Started
* [ ] Documentation: Not Started

## Summary
[summary]: #summary

`MarkupExtension` for `ImageSource`.

## Detailed Design
[design]: #detailed-design

### ImageResourceMarkupExtension.shared.cs

```cs
[ContentProperty(nameof(Id))]
public class ImageResourceExtension : IMarkupExtension<ImageSource>
{
  public string Id { get; set; } = string.Empty;
  
  public ImageSource ProvideValue(IServiceProvider serviceProvider) => ImageSource.FromResource(Id, Application.Current.GetType().Assembly);

  object? IMarkupExtension.ProvideValue(IServiceProvider serviceProvider) => ProvideValue(serviceProvider);
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<Image>
  <local:ImageResourceExtension: Id="photo.png" />
</Image>
```

### C# Usage

N/A

**Comment by Rashidovicc** [comment]
Hi @brminnick I want to start solving this issue ;) that I will benefit too
 i have one question: 
Do I create ImageResourceExtension in this path?

![image](https://user-images.githubusercontent.com/105649270/211371477-6ab6473f-abdb-470a-96a4-2e527df3f8c1.png)

**Comment by brminnick** [comment]
Thanks for the offer, @Rashidovicc! But after discussing this with the team, this feature is basically included in .NET MAUI via `MauiImage`: https://learn.microsoft.com/dotnet/maui/user-interface/images/images?view=net-maui-7.0

Moving this Proposal to closed.
