### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by pierre01** [CommunityToolkit/Maui#901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file.

### Current Behavior

Toast and Snackbar don't wok on windows

### Expected Behavior

Toasts and snackbars should work on windows

### Steps To Reproduce

Run Community Samples on Windows and notice that the toast and snackbars don't work

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui/tree/main/samples/CommunityToolkit.Maui.Sample/Pages/Alerts

### Environment

```markdown
- .NET MAUI CommunityToolkit: 3.1
- OS: Windows 11
- .NET MAUI: 7
```

**Comment by pierre01** [comment]
Works fine on Android

**Comment by VladislavAntonyuk** [comment]
We use Toast Notifications on Windows. Make sure you haven't enabled Do Not Disturb mode and allow to send notifications.

**Comment by pierre01** [comment]
Thank you!. You were right. Toast and snackbar work. I was in DND.
