### ISSUE TITLE
[BUG] Wrong version for Nightly builds

### ISSUE THREAD

**Issue by twsl** [CommunityToolkit/Maui#909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file.

### Current Behavior

As shown in https://github.com/CommunityToolkit/Maui/discussions/852, the regular release on nuget is tagged with version 3.1.0, the nightly builds are tagged as 1.0.0-preview. Which means it always shows the regular build as latest version and causes issues with other libraries that require CommunityToolkit >= 3.0.0

### Expected Behavior

Tag nightly library accordingly

### Steps To Reproduce

1. Add nuget feed
2. try to update

### Link to public reproduction project repository

https://github.com/twsl/Maui/tree/feature/version

### Environment

```markdown
- .NET MAUI CommunityToolkit:3.1.0
- OS: Windows 11
- .NET MAUI: 7
```

**Comment by twsl** [comment]
A simple fix has been proposed because azure pipelines offer no way for me to test the code locally

**Comment by vhugogarcia** [comment]
@brminnick I believe this can maybe be moved to a discussion about the versioning strategy first, and so everybody can share ideas for nightly builds, etc. I noticed the PR was closed and not anymore movement there. 

So, I think we can also close this issue.

Regards,
Victor

**Comment by VladislavAntonyuk** [comment]
@vhugogarcia we had an open PR. For nightly builds for simplicity we decided to use version 99 to ensure it is higher than our regular version

**Comment by bijington** [comment]
I did also have a branch working with GitVersion but we didn't work out the tagging approach
