### ISSUE TITLE
[BUG] Swipe gestures blocked when enabling MediaPlayer controls

### ISSUE THREAD

**Issue by ne0rrmatrix** [CommunityToolkit/Maui#911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file.

### Current Behavior

When using toolkit:MediaPlayer if you enable video controls it blocks swipe gestures.

### Expected Behavior

Swipe gestures should work with media player controls active

### Steps to Reproduce

Steps to reproduce.
- Create new maui project
- Add following Nuget Packages, CommunityToolkit.Maui, CommunityToolkit.Maui.Core, CommunityToolkit.Maui.MediaPlayer
- add a second page to solution
- put a button that navigates to second page
- set up code behind for navigation
- on second page add a media element source
- enable video controls
- add swipe right gesture to second page that navigates back to first page
- launch app and navigate to video
- try and swipe right

Steps to mitigate:
-Do all of the steps to reproduce
-set player controls to disabled
-swipe right

### Link to public reproduction project repository

https://github.com/ne0rrmatrix/MediaPlayerBugSwipeGestures

### Environment

```markdown
- .NET MAUI CommunityToolkit:MediaPlayer
- OS: Android 13.0
- .NET MAUI: current 7.0.100
```

**Comment by ne0rrmatrix** [comment]
Ok closing this report now. I found out the behavior I described was working as intended with exoplayer controls. I will work on implementing it myself by adding a override.

**Comment by pictos** [comment]
@ne0rrmatrix if you are able to make that work, please comment on this issue sharing the solution, if it's possible. I can imagine a lot of devs looking for it (; . Thanks in advance

**Comment by rupisaini123** [comment]
@ne0rrmatrix i am having same issue, i tried to use TapGestureRecognizer within a MediaElement. But it won't work at all. Please post if you have an override for Gestures. Thanks in advance

**Comment by ne0rrmatrix** [comment]
I wrote my own custom UI to replace the built in controls and that worked for me. I implemented full screen controls for android, windows, and ios.

**Comment by rupisaini123** [comment]
That would be great. If you can post the sample. Really appreciated
