### ISSUE TITLE
[BUG] Binding for DrawingView.Lines does not work

### ISSUE THREAD

**Issue by Glorfindel83** [CommunityToolkit/Maui#932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file.

### Current Behavior

I'm binding a property `public ObservableCollection<IDrawingLine> Lines` to DrawingView.Lines; after drawing, it does not contain any lines.

### Expected Behavior

The property should be filled, just like the Lines property of the DrawingView itself.

### Steps To Reproduce

- Create a new MAUI template app with name MyMAUIApp and add the CommunityToolkit NuGet package.
- Add `.UseMauiCommunityToolkit()` to MauiProgram.cs
- Change MainPage.xaml to
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
             xmlns:mymauiapp="clr-namespace:MyMAUIApp"
             x:DataType="mymauiapp:MainPage"
             x:Class="MyMAUIApp.MainPage">
    <toolkit:DrawingView
        x:Name="DrawingView"
        Lines="{Binding Lines}"
        DrawingLineCompleted="DrawingView_DrawingLineCompleted" />
</ContentPage>
```
- Change MainPage.xaml.cs to
```
using System.Collections.ObjectModel;
using CommunityToolkit.Maui.Core;
using CommunityToolkit.Maui.Views;

namespace MyMAUIApp;

public partial class MainPage : ContentPage {
    public MainPage() {
        InitializeComponent();
    }

    public ObservableCollection<IDrawingLine> Lines { get; set; } = new ObservableCollection<IDrawingLine>();

    void DrawingView_DrawingLineCompleted(Object sender, DrawingLineCompletedEventArgs e) {
        Console.WriteLine(Lines.Count + ", " + ((DrawingView)sender).Lines.Count);
    }
}
```
- Run the app and draw something - you'll see this in the output:
> 0, 1

### Link to public reproduction project repository

n/a

### Environment

```markdown
- .NET MAUI CommunityToolkit: 4.0.0
- OS: Visual Studio for macOS (13.1), observable on both iOS and Android
- .NET MAUI: 7.0.102

It's also happening with CommunityToolkit 2.0.0 on .NET 6.0
```

**Comment by VladislavAntonyuk** [comment]
Have you set the binding context?

**Comment by Glorfindel83** [comment]
@VladislavAntonyuk thanks for catching that - I don't have much experience with MAUI, Xamarin Forms or MVVM in general - I'd expect a NullReferenceException if a forgot to do something like that.
However, in my real project, the binding context _is_ set, but it's hard to make a minimal reproducible example (it's a page deep down an application using Shell, Syncfusion TabView with asynchronous page loading, etc.). I do have a workaround so that will suffice for now.
