### ISSUE TITLE
[BUG] CommunityToolkit.Maui.MediaElement 1.0.1 Crash on iOS

### ISSUE THREAD

**Issue by JoacimWall** [CommunityToolkit/Maui#937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file.

### Current Behavior

The new nuget crash on trying to init the player. This worked when it was in preview.
Error:  
Objective-C exception thrown.  Name: UIViewControllerHierarchyInconsistency Reason: child view controller:<AVPlayerViewController: 0x10f722600> should have parent view controller:<Microsoft_Maui_Platform_PageViewController: 0x10eda1a40> but actual parent is:<Microsoft_Maui_Controls_Platform_Compatibility_ShellFlyoutRenderer: 0x101665ac0>
Native stack trace:
	0   CoreFoundation                      0x00000001b3b31e54 725E49F4-653B-39BF-9A7A-8A3250911ECB + 40532
	1   libobjc.A.dylib                     0x00000001acdfb8d8 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001b3c21c38 725E49F4-653B-39BF-9A7A-8A3250911ECB + 1023032
	3   UIKitCore                           0x00000001b5dacc04 59CBC9B5-30AE-396E-A269-A986640001BC + 719876
	4   UIKitCore                           0x00000001b5daca1c 59CBC9B5-30AE-396E-A269-A986640001BC + 719388
	5   UIKitCore                           0x00000001b5d12008 59CBC9B5-30AE-396E-A269-A986640001BC + 86024
	6   UIKitCore                           0x00000001b5d12044 59CBC9B5-30AE-396E-A269-A986640001BC + 86084
	7   UIKitCore                           0x00000001b5d12044 59CBC9B5-30AE-396E-A269-A986640001BC + 86084
	8   UIKitCore                           0x00000001b5d12044 59CBC9B5-30AE-396E-A269-A986640001BC + 86084
	9   UIKitCore                           0x00000001b5d12044 59CBC9B5-30AE-396E-A269-A986640001BC + 86084
	10  UIKitCore                           0x00000001b5d1ada8 59CBC9B5-30AE-396E-A269-A986640001BC + 122280
	11  UIKitCore                           0x00000001b5fb409c 59CBC9B5-30AE-396E-A269-A986640001BC + 2846876
	12  UIKitCore                           0x00000001b5fb35a4 59CBC9B5-30AE-396E-A269-A986640001BC + 2844068
	13  UIKitCore                           0x00000001b64f70ac 59CBC9B5-30AE-396E-A269-A986640001BC + 8364204
	14  UIKitCore                           0x00000001b5f02928 59CBC9B5-30AE-396E-A269-A986640001BC + 2119976
	15  UIKitCore                           0x00000001b5fb3020 59CBC9B5-30AE-396E-A269-A986640001BC + 2842656
	16  UIKitCore                           0x00000001b5ef3e40 59CBC9B5-30AE-396E-A269-A986640001BC + 2059840
	17  UIKitCore                           0x00000001b5ef3cfc 59CBC9B5-30AE-396E-A269-A986640001BC + 2059516
	18  UIKitCore                           0x00000001b6460a38 59CBC9B5-30AE-396E-A269-A986640001BC + 7748152
	19  UIKitCore                           0x00000001b5ea09f4 59CBC9B5-30AE-396E-A269-A986640001BC + 1718772
	20  UIKitCore                           0x00000001b5ea0928 59CBC9B5-30AE-396E-A269-A986640001BC + 1718568
	21  UIKitCore                           0x00000001b5ea0834 59CBC9B5-30AE-396E-A269-A986640001BC + 1718324
	22  UIKitCore                           0x00000001b5d3bda0 59CBC9B5-30AE-396E-A269-A986640001BC + 257440
	23  UIKitCore                           0x00000001b62010b4 59CBC9B5-30AE-396E-A269-A986640001BC + 5259444
	24  UIKitCore                           0x00000001b634f498 59CBC9B5-30AE-396E-A269-A986640001BC + 6628504
	25  UIKitCore                           0x00000001b699b410 59CBC9B5-30AE-396E-A269-A986640001BC + 13231120
	26  UIKitCore                           0x00000001b699a5dc 59CBC9B5-30AE-396E-A269-A986640001BC + 13227484
	27  CoreFoundation                      0x00000001b3bfdf34 725E49F4-653B-39BF-9A7A-8A3250911ECB + 876340
	28  CoreFoundation                      0x00000001b3c0a30c 725E49F4-653B-39BF-9A7A-8A3250911ECB + 926476
	29  CoreFoundation                      0x00000001b3b8e1d0 725E49F4-653B-39BF-9A7A-8A3250911ECB + 418256
	30  CoreFoundation                      0x00000001b3ba3b8c 725E49F4-653B-39BF-9A7A-8A3250911ECB + 506764
	31  CoreFoundation                      0x00000001b3ba8ec0 CFRunLoopRunSpecific + 612
	32  GraphicsServices                    0x00000001edbff368 GSEventRunModal + 164
	33  UIKitCore                           0x00000001b609e86c 59CBC9B5-30AE-396E-A269-A986640001BC + 3807340
	34  UIKitCore                           0x00000001b609e4d0 UIApplicationMain + 340
	35  Fm.PetCaregiver                     0x00000001008e4714 xamarin_UIApplicationMain + 60
	36  Fm.PetCaregiver                     0x0000000100c864b0 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2720096
	37  Fm.PetCaregiver                     0x0000000100c851d0 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2715264
	38  Fm.PetCaregiver                     0x0000000100c7abac _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2672732
	39  Fm.PetCaregiver                     0x0000000100c787ec _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2663580
	40  Fm.PetCaregiver                     0x0000000100c408f8 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2434472
	41  Fm.PetCaregiver                     0x0000000100b7e3e0 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1638544
	42  Fm.PetCaregiver                     0x0000000100b85ff0 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1670304
	43  Fm.PetCaregiver                     0x0000000100c46a08 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2459320
	44  Fm.PetCaregiver                     0x0000000100926110 xamarin_get_original_working_directory_path + 4016
	45  Fm.PetCaregiver                     0x0000000100cb8c40 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2926832
	46  dyld                                0x00000001d23ca960 7B63C573-6161-3B33-A3A2-9944BA59722F + 88416

### Expected Behavior

Show the form and play the video

### Steps To Reproduce

open solution. 
Debug 
Click button ShowVideo

### Link to public reproduction project repository

https://github.com/JoacimWall/Joacim_Bug_Report/tree/main/MediaElementBug/MediaElementBug

### Environment

```markdown
- .NET MAUI CommunityToolkit.Maui.MediaElement:1.0.1 public 
- OS:Mac
- .NET MAUI:
Visual Studio Professional 2022 for Mac Preview
Version 17.5 Preview (17.5 build 1728)
Installation UUID: e4fe7c5d-c8cd-4a3a-b543-c4742420b947

Runtime
.NET 7.0.1 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 12.3.2372; git-rev-head:754abbf6a3563f6267e5717ae832b4ac25b1f2fb; git-branch:release/7.0.1xx-xcode13.3

Roslyn (Language Service)
4.5.0-3.23056.2+97881342e427ff5cdcba8f12b12ff8e6f3564431

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.200-preview.22628.1/Sdks
SDK Versions:
	7.0.200-preview.22628.1
	7.0.102
	7.0.101
	7.0.100
	7.0.100-rc.2.22477.23
	6.0.405
	6.0.404
	6.0.403
	6.0.402
	6.0.401
MSBuild SDKs: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	3.1.426
	3.1.425
	3.1.424
	3.1.423

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.2
	7.0.1
	7.0.0
	7.0.0-rc.2.22472.3
	6.0.13
	6.0.12
	6.0.11
	6.0.10
	6.0.9

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	3.1.32
	3.1.31
	3.1.30
	3.1.29

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode: 14.2 21534
Build: 14C18

Xamarin.Mac
Version: 9.1.0.2 Visual Studio Professional
Hash: 956a059ba
Branch: xcode14.2
Build date: 2022-12-15 06:15:43-0500

Xamarin.iOS
Version: 16.2.0.2 Visual Studio Professional
Hash: 956a059ba
Branch: xcode14.2
Build date: 2022-12-15 06:15:44-0500

Xamarin Designer
Version: 17.5.3.46
Hash: e4dd80b2bb
Branch: remotes/origin/d17-5
Build date: 2023-01-20 16:18:58 UTC

Xamarin.Android
Version: 13.2.0.0 (Visual Studio Professional)
Commit: xamarin-android/d17-5/797e2e1
Android SDK: /Users/joacimwall/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)
		8.1  (API level 27)
		11.0 (API level 30)
		10.0 (API level 29)
		9.0  (API level 28)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.3
SDK Build Tools Version: 32.0.0

Build Information: 
Mono: 6dd9def
Java.Interop: xamarin/java.interop/main@149d70fe
SQLite: xamarin/sqlite/3.40.0@fdc1e34
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@9f02d77

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.5.0.26
Hash: 2ea
```

**Comment by JoacimWall** [comment]
if I change the navigation pattern from 
await Shell.Current.Navigation.PushModalAsync(new VideoFullPage("https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"));

to 

await Shell.Current.GoToAsync($"{nameof(VideoFullPage)}?VideoBlob={"https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"}");

then it works

**Comment by jfversluis** [comment]
I'm pretty sure https://github.com/CommunityToolkit/Maui/pull/1008 will fix this one too. @JoacimWall could you try this maybe?

**Comment by JoacimWall** [comment]
> I'm pretty sure #1008 will fix this one too. @JoacimWall could you try this maybe?

Yes @jfversluis  now it's working in ios with Shell.PresentationMode="Modal"

//Thanks
