### ISSUE TITLE
[Proposal] WeakEventManager<T>

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#94]
# WeakEventManager<T>

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
  * [ ] iOS Support
  * [ ] Android Support
  * [ ] macOS Support
  * [ ] Windows Support
* [ ] Unit Tests: Not Started
* [ ] Sample: Not Started
* [ ] Documentation: Not Started

## Summary
[summary]: #summary

An event implementation that enables the garbage collector to collect an object without needing to unsubscribe event handlers.

Inspired by Microsoft.Maui.Controls.WeakEventManager.

## Detailed Design
[design]: #detailed-design

```cs
public class WeakEventManager<TEventArgs> : WeakEventManager
{
  public void AddEventHandler(EventHandler<TEventArgs> handler, [CallerMemberName] string eventName = "");
  public void AddEventHandler(Action<TEventArgs> action, [CallerMemberName] string eventName = "");

  public void RemoveEventHandler(EventHandler<TEventArgs> handler, [CallerMemberName] string eventName = "");
  public void RemoveEventHandler(Action<TEventArgs> action, [CallerMemberName] string eventName = "");

  public void RaiseEvent(object? sender, TEventArgs eventArgs, string eventName)
}

public static class WeakEventManagerExtensions
{
  public static void RaiseEvent(this WeakEventManager weakEventManager, object? sender, object eventArgs, string eventName)
  {
	ArgumentNullException.ThrowIfNull(weakEventManager);

	weakEventManager.HandleEvent(sender, eventArgs, eventName);
  }
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

N/A

### C# Usage

```cs
var weakEventManager = new WeakEventManager<bool>();

public event EventHandler Completed<bool>
{
  add => weakEventManager.AddEventHandler(value);
  remove => weakEventManager.RemoveEventHander(value);
}

void OnCompleted(bool isSuccessful) => weakEventManager.RaiseEvent(this, isSuccessful, nameof(Completed));
```

**Comment by maxkoshevoi** [comment]
@brminnick I thought, `WeakEventManager` is not coming to this Nuget: https://github.com/CommunityToolkit/Maui/pull/7#issuecomment-892332156.
Is something changed after your comment above?

**Comment by brminnick** [comment]
The hope is that we will promote `DelegateWeakEventManager` to .NET MAUI: 
https://github.com/dotnet/maui/issues/2703 

If that happens, we won't need `WeakEventManager` in the .NET MAUI Community Toolkit. 

If we cannot promote `DelegateWeakEventManager`, we'll likely move `WeakEventManager` to the MVVM Toolkit.

**Comment by brminnick** [comment]
Not required now that DelegateWeakEventManager has been promoted into .NET MAUI https://github.com/dotnet/maui/issues/2703#issuecomment-966312097

**Comment by charlesroddie** [comment]
I don't think this is not required as the thing specced in https://github.com/dotnet/maui/issues/2703 is non-generic (and so only supports patterns in dotnet that came from its unfortunate pre-generics history), whereas this proposal is for generic `WeakEventManager<T>`.

**Comment by brminnick** [comment]
True that .NET MAUI's `WeakEventManager` isn't generic. 

The addition of `WeakEventManager<T>` to `CommunityToolkit.Maui` doesn't justify the the implementation and maintenance cost over using .NET MAUI's `WeakEventManager`; ie it doesn't add much functionality compared to the suite of Unit Tests, future bug reports and future PRs required to support it. 

I recommend using [`AsyncAwaitBestPractices.MVVM`](https://www.nuget.org/packages/AsyncAwaitBestPractices.MVVM/) if you're looking for `WeakEventManager<T>`. When I wrote Xamarin Community Toolkit's implementation of `WeakEventManager<T>`, I heavily based it upon my `AsyncAwaitBestPractices` library.
