### ISSUE TITLE
[BUG] MediaElement 1.0.1. ShouldAutoPlay = False not working on iOS

### ISSUE THREAD

**Issue by derekpapworth** [CommunityToolkit/Maui#943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file.

### Current Behavior

Using the latest MediaElement 1.0.1, when setting the ShouldAutoPlay = False this is being ignored in iOS as when running it starts playing automatically both for audio files and video files. It works ok with Windows target and also Android which from the release notes was fixed in this release but it looks like iOS still has an issue

### Expected Behavior

With ShouldAutoPlay = False one would expect the media not to start automatically

### Steps To Reproduce

Took new Maui project and added MediaElement as per docs and run.

### Link to public reproduction project repository

https://github.com/derekpapworth/MediaElementTest

### Environment

```markdown
- .NET MAUI CommunityToolkit MediaElement: 1.0.1 
- OS: Windows 11 Pro 21H2
- .NET MAUI: 7.0.52
```

**Comment by derekpapworth** [comment]
Here's a link to sample repository I created from standard Maui project with single MediaElement added in MainPage.xml using embedded test mp3 that exhibits the problem. Run it for Windows or Android and all works ok (i.e. it doesn't auto start) but run it for iOS it starts automatically when it shouldn't. Note also same issue if target is Mac Catalyst. Wasn't sure how to edit my original post to add the repository link so added it here : 

https://github.com/derekpapworth/MediaElementTest

**Comment by jfversluis** [comment]
Hey @derekpapworth thanks for this! I opened a PR to fix this this should do the trick for iOS and macOS at the same time :)

**Comment by derekpapworth** [comment]
Hi Gerald,

Great, thanks for quick fix! 👍

What’s the normal cycle time for the next NuGet package version that will include this?

Best regards,

Derek

**Comment by jfversluis** [comment]
We don't really have a fixed schedule. I don't think it will be too long. In the meantime you might want to check out our [preview packages](https://github.com/CommunityToolkit/Maui/wiki/Preview-Packages) and verify it's actually fixed!
