### ISSUE TITLE
[BUG] FolderPicker Error when trying to open a second time on MacCatalyst

### ISSUE THREAD

**Issue by brightertools** [CommunityToolkit/Maui#949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

There is an Exception with the error:

Message "Cannot access a disposed object.\nObject name: 'UIKit.UIDocumentPickerViewController'."

### Expected Behavior

The folder picker dialog should show again to allow the selection of another folder.

### Steps To Reproduce

Clone the latest MAUI samples (main branch)
Run the CommunityToolkit,Maui.Sample app using MacCatalyst
Click Menu > Essentials > FolderPicker
Click Pick Folder and choose a folder
Click Pick Folder and choose a folder (this time there is an error)

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui.git

### Environment

```markdown
Application Versions
- .NET MAUI CommunityToolkit: 4.0.0
- OS: MacOS / Monterey Version 12.6.2
- .NET MAUI: Microsoft.NetMaui.Core 7.0.5.8
- XCode: Version 14.2 (14C18)

Reproduced on Main branch as of today
```

### Anything else?

Sorry missed the Title, cant seem to edit it now?

**Comment by pictos** [comment]
@brightertools can you add a title/

**Comment by brightertools** [comment]
I left a note that I tried, will try again..
