### ISSUE TITLE
[BUG] IconTintColorBehavior does not work for Button with ImageSource on Android

### ISSUE THREAD

**Issue by karlandin** [CommunityToolkit/Maui#955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

IconTintColorBehavior on Button does not affect Image added by ImageSource property on Android.

### Expected Behavior

The TintColor should be added to the image in the same way as on iOS. 

### Steps To Reproduce

Run solution from reproduction repository on Android and look at the second column in the Grid on MainPage. (Or look at the screenshot in Readme of reproduction repository)

### Link to public reproduction project repository

https://github.com/karlandin/maui-toolkit-icon-tint-color-bug

### Environment

```markdown
- .NET MAUI CommunityToolkit: 4.0.0
- OS: MacOS 13.2 (22D49)
- .NET MAUI: 7.0.58
```

### Anything else?

The repro repository contains a copy of IconTintColorBehavior that works. I notised that the control was of the type MaterialButton and that I could add same color filter for MaterialButton.Icon as for ImageView. See SetMaterialButtonTintColor here: https://github.com/karlandin/maui-toolkit-icon-tint-color-bug/blob/main/Behaviors/IconTintColorBehavior.android.cs

I am new to MAUI (and mobile app development) so I don't know the different between Android.Widget.Button and MaterialButton. Will the button sometimes not be a MaterialButton? The current solution for Button (SetButtonTintColor) tries to find "drawables", but all returned in my example are null. `var drawables = button.GetCompoundDrawables().Where(d => d is not null);`

I can try to create a PR if my solution looks good to you.

**Comment by UkeHa** [comment]
This is still buggy, reproduced with CommunityToolkit 6.0.0, .net7 on both Android (13) and iOS (16)

```
<ImageButton
    Grid.Column="2"
    BackgroundColor="{StaticResource Primary}"
    Source="barcode_scan.png"
    VerticalOptions="CenterAndExpand"
    Command="{Binding Scannen, Source={x:Reference this}}">
    <ImageButton.Behaviors>
        <toolkit:IconTintColorBehavior TintColor="Red" />
    </ImageButton.Behaviors>
</ImageButton>
```

**Comment by UkeHa** [comment]
It also doesn't work when using an image inside a devexpress simplebutton

```
<controls:SimpleButton
    Grid.Column="2"
    HorizontalOptions="Center"
    VerticalOptions="Center"
    WidthRequest="75"
    HeightRequest="50"
    Command="{Binding Scannen, Source={x:Reference this}}">
    <Image
        Source="{AppThemeBinding Light='barcode_scan.png', Dark='barcode_scan_white.png'}">
        <Image.Behaviors>
            <toolkit:IconTintColorBehavior TintColor="{StaticResource Gray500}"/>
        </Image.Behaviors>
    </Image>
</controls:SimpleButton>
```

**Comment by CorentinSwiss4** [comment]
Same as iOS for ImageButton, any update for this ?

**Comment by janusw** [comment]
Two cases where I saw problems with `IconTintColorBehavior` on Android (using .net8, MAUI 8.0.10, CommunityToolkit 7.0.1):
* specifying a TintColor via `DynamicResource` (using `StaticResource` works)
* setting up UI elements off the main thread (using `Dispatcher.Dispatch` helps)

**Comment by bijington** [comment]
> Two cases where I saw problems with `IconTintColorBehavior` on Android (using .net8, MAUI 8.0.10, CommunityToolkit 7.0.1):
> 
> * specifying a TintColor via `DynamicResource` (using `StaticResource` works)
> 
> * setting up UI elements off the main thread (using `Dispatcher.Dispatch` helps)

If you are seeing issues can you please open an issue for them so it makes it easier to track them? For what it's worth though I would say you should always interact with UI elements in the main thread.

**Comment by janusw** [comment]
> > * setting up UI elements off the main thread (using `Dispatcher.Dispatch` helps)
>
> For what it's worth though I would say you should always interact with UI elements in the main thread.

Yes, I'm aware of that. It's basically a usage error. However, many things also work off the UI thread, and this kind of problem can be easy to miss, so I thought I'd mention it here.

 
> > * specifying a TintColor via `DynamicResource` (using `StaticResource` works)
>
> If you are seeing issues can you please open an issue for them so it makes it easier to track them?

Yes, indeed the `DynamicResource` did not seem to be the problem in the other code examples given in this issue, so apparently it's a different problem.

Actually I also had problems with `DynamicResource` in the context of `StatusBarBehavior`, so maybe it's a common issue with the toolkit behaviors? I will open a new issue for it.

**Comment by vhugogarcia** [comment]
I can see the issue has been fixed. Recently, the team improved the behaviors architecture and released a new version a couple of months ago, and probably that change fixed the issue. 

I'm attaching screenshots below with the results of the tests. For that reason, I'm closing this ticket.


<img width="950" alt="Screenshot 2024-06-21 at 11 59 29 a m" src="https://github.com/CommunityToolkit/Maui/assets/1047398/9f6aad3e-7fd0-440c-8049-0f08fd2da1d8">
<img width="983" alt="Screenshot 2024-06-21 at 11 56 37 a m" src="https://github.com/CommunityToolkit/Maui/assets/1047398/b4aecdff-6059-466e-a4d4-bc0afa91389d">
