### ISSUE TITLE
[BUG] mediaelement on android，playing video is a empty screen

### ISSUE THREAD

**Issue by BlueCapo** [CommunityToolkit/Maui#958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [x] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

My phone is lenovo zuk z2. System is android 8.0.0. Using Mediaelement play a video, have a audio, but no picture, it always is a empty screen.

### Expected Behavior

play any video，always get a empty screen.

### Steps To Reproduce

<toolkit:MediaElement x:Name="MyPlayer" WidthRequest="320" HeightRequest="240"
                                      Source="https://learn.microsoft.com/video/media/a11cac3e-a121-492f-8246-aef2fb3e341a/csharp101whatiscsharp_high.mp4"  ShouldAutoPlay="True"/>

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui/tree/main/samples/CommunityToolkit.Maui.Sample/Pages/Views/MediaElement

### Environment

```markdown
- CommunityToolkit.Maui.MediaElement: 1.0.1
- OS: Android 8.0.0
- .NET MAUI: 7.0
```

**Comment by ne0rrmatrix** [comment]
Have you tried setting width and height and checking if video plays? Older versions of media element in certain scenarios would have no display if you did not wet height and width. It is fixed now in current nuget package. Do you have audio playback at all?

**Comment by BlueCapo** [comment]
> If you hook up the `MediaFailed` event, does that give you any additional information? Or the application output window in Visual Studio?
> 
> Without any logs or error messages or anything this is pretty much impossible to diagnose and fix unfortunately.

Thanks. I have found the cause of the problem. Because I put the Mediaelement in the Border Control, it will not display any picture. Like this: 
*           <Border Stroke="Gray" StrokeThickness="1" >
                         <toolkit:MediaElement x:Name="MyPlayer"
                                       ShouldAutoPlay="True" ShouldShowPlaybackControls="True"
                                       WidthRequest="320" HeightRequest="240"/>
            </Border>

**Comment by BlueCapo** [comment]
> Have you tried setting width and height and checking if video plays? Older versions of media element in certain scenarios would have no display if you did not set height and width. It is fixed now in current nuget package. Do you have audio playback at all?

Thanks. I have found the cause of the problem. Because I put the Mediaelement in the Border Control, it will not display any picture. Like this: 
*           <Border Stroke="Gray" StrokeThickness="1" >
                         <toolkit:MediaElement x:Name="MyPlayer"
                                       ShouldAutoPlay="True" ShouldShowPlaybackControls="True"
                                       WidthRequest="320" HeightRequest="240"/>
            </Border>

**Comment by ScottyLightnin** [comment]
FYI, I had this same issue.
I was able to workaround it by wrapping my MediaElement in a Frame as a border, which worked. But still weird that I can't use a Border and that it only failed on Android (tested on two Lenovo tablets). 
It worked fine on Windows and iOS when wrapped in a border.
