### ISSUE TITLE
[BUG] Clicking Cancel on Folder Picker Throws Error

### ISSUE THREAD

**Issue by gktval** [CommunityToolkit/Maui#974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

On Windows, if you hit cancel on the Open Folder Dialog, and error will be thrown "Folder doesn't exist."

### Expected Behavior

Maybe instead of throwing an error, it can return null. The easy workaround is to put it in a try/catch and ignore it.

### Steps To Reproduce

I have not tested in other platforms. But the steps to reproduce are to open the Folder dialog, then click cancel instead of choosing a folder and selecting "Select Folder".

The code I am using
```
 var folderPicker = CommunityToolkit.Maui.Storage.FolderPicker.Default;
var tokenSource = new CancellationTokenSource();
try
{
      var pickedFolder = await folderPicker.PickAsync("C:\\", tokenSource.Token);
}
catch (Exception ex)
{
    System.Diagnostics.Debug.WriteLine(ex.Message);
}
```

### Link to public reproduction project repository

NA

### Environment

```markdown
- .NET MAUI CommunityToolkit: 4.0.0
- OS: Windows 11
- .NET MAUI: .Net 7
```

**Comment by VladislavAntonyuk** [comment]
That is by design.
The bug here is the invalid error message. It should be Operation canceled.

**Comment by gktval** [comment]
OK thanks I will close this then.
