### ISSUE TITLE
[Proposal] Add a behavior (or attached property) to allow users the ability to close the soft keyboard when clicking outside of a view

### ISSUE THREAD

**Issue by PureWeen** [CommunityToolkit/Maui#978]
### Feature name

SoftKeyboardBehavior

### Link to discussion

https://github.com/CommunityToolkit/Maui/discussions/967

### Progress tracker

- [ ] Android Implementation
- [ ] iOS Implementation
- [ ] MacCatalyst Implementation
- [ ] Windows Implementation
- [ ] Tizen Implementation
- [ ] Unit Tests
- [ ] Samples
- [ ] Documentation

### Summary

There are a number of users that want to be able to tap into the nothingness and close the soft keyboard. 

https://github.com/dotnet/maui/issues/12002#issuecomment-1385826740

We didn't copy this behavior over from XF because the mechanism used to implement this behavior was to make the `PageRenderer` focusable/clickable which wreaked havoc on accessibility. 

I have a proposal here for some APIs we could add to MAUI
https://github.com/dotnet/maui/issues/12003
https://github.com/dotnet/maui/issues/11983

I feel like this type of behavior should live inside the community toolkit, so it can be refined and added to out of band from the MAUI. We can release these initial features inside a NET 7 version of the community toolkit. Since this is added on behavior it seems like it would survive and iterate better inside the toolkit vs inside the core code. 

The core MAUI code just needs to provide the APIs necessary to enable this type of feature. 

I already have a behavior built here
https://github.com/PureWeen/ShanedlerSamples/tree/main/ShanedlerSamples/Library/TapToCloseBehavior
and the iOS code can be easily removed from MAUI core and put into a behavior as well. 

```XAML
            <Entry Placeholder="Text Field" Text="Starting text" WidthRequest="300">
                <Entry.Behaviors>
                    <local:SoftKeyboardBehavior CloseOnTapOutsideBounds="true"></local:SoftKeyboardBehavior>
                </Entry.Behaviors>
            </Entry>
```

### Motivation

Being able to close the soft keyboard when you tap off of an entry is a use case that a number of users really want. 
https://github.com/dotnet/maui/issues/12002

The implementation of this feature in Android was done in such a way that broke accessibility. 

This type of behavior is an add-on to the platform not something that we should adopt by default in core. 

Even on the iOS side this behavior can have negative impacts on accessibility. 
https://github.com/dotnet/maui/pull/10948

This is a type of feature that shouldn't be a first-class citizen of MAUI it should be something that's implemented on top of existing APIs. 

Having this in the MCT is also preferred because we can iterate quicker on additional APIs around SoftKeyboard interactions. Things that don't really make sense to have in core. 

### Detailed Design

I have the implementations pretty much done for iOS/Android

Android: https://github.com/PureWeen/ShanedlerSamples/tree/main/ShanedlerSamples/Library/TapToCloseBehavior
iOS: https://github.com/dotnet/maui/pull/10948

So those would just need to be extracted from the platform 

### Usage Syntax

```markdown
<Entry Placeholder="Text Field" Text="Starting text" WidthRequest="300">
                <Entry.Behaviors>
                    <local:SoftKeyboardBehavior CloseOnTapOutsideBounds="true"></local:SoftKeyboardBehavior>
                </Entry.Behaviors>
            </Entry>
```

**Comment by pictos** [comment]
I approve this feature ✅

**Comment by VladislavAntonyuk** [comment]
Approve

**Comment by JoonghyunCho** [comment]
I approve this feature

**Comment by bijington** [comment]
It's a 👍 from me

**Comment by bstallter3** [comment]
Is this going to happen?

**Comment by brminnick** [comment]
The .NET MAUI team added it into the official .NET MAUI repo: https://github.com/CommunityToolkit/Maui/pull/1064

**Comment by brminnick** [comment]
Hi @bstallter3! Would you like to implement this feature? 

As you can see by the tags, this Proposal has been `approved` and we are actively looking for a contributor to implement it (the `help wanted` tag).

**Comment by pictos** [comment]
I believe this will be on .NET 8 MAUI, can you confirm that @PureWeen ?

**Comment by bstallter3** [comment]
> Hi @bstallter3! Would you like to implement this feature?
> 
> As you can see by the tags, this Proposal has been `approved` and we are actively looking for a contributor to implement it (the `help wanted` tag).

Man, I so wish I was that good.  If I knew I was even close to capable of that I'd give it a whirl.  Unfortunately I'm way too much of a noob.  Just wondering. I appreciate the quick feedback already, if it's going to be in .net 8, I may just wait until november when that is released, and in the meantime come up with a workaround.

**Comment by pictos** [comment]
@bstallter3 you probably can find that feature on this package
https://www.nuget.org/packages/PureWeen.Maui.FixesAndWorkarounds, as mentioned by Shane in the first issue. You feel like a noob isn't a blocker, we can help you onboard the project and improve (: 
any time that you see an issue that you would like to work on, let us know and we can have members of the team helping you out

**Comment by vhugogarcia** [comment]
You are correct @pictos this feature has been implemented on **.NET MAUI 8** and it is available now.

- Use `ContentPage.HideSoftInpuOnTapped` to [dismiss the keyboard](https://learn.microsoft.com/dotnet/maui/user-interface/pages/contentpage?view=net-maui-8.0) when tapping anywhere on the page
- Controls that support text input gain extension methods that support hiding and showing the soft input keyboard. For more information, see [Hide and show the soft input keyboard](https://learn.microsoft.com/dotnet/maui/user-interface/controls/entry?view=net-maui-8.0#hide-and-show-the-soft-input-keyboard).

It was announced officially on the DevBlogs, two weeks ago: https://devblogs.microsoft.com/dotnet/announcing-dotnet-maui-in-dotnet-8/

@brminnick I think we can safely close this issue.
