### ISSUE TITLE
[BUG] NumericValidationBehavior throws error "value cannot be null"

### ISSUE THREAD

**Issue by williambuchanan2** [CommunityToolkit/Maui#979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Trying to use NumericValidationBehavior. As soon as I include the below I get an error:

System.ArgumentNullException: 'Value cannot be null. (Parameter 'value')'

<toolkit:NumericValidationBehavior  x:Name="TextVal"
                            InvalidStyle="{StaticResource InvalidEntryStyle}"
                            ValidStyle="{StaticResource ValidEntryStyle}"
                            Flags="ValidateOnValueChanged"
                            MinimumValue="0"
                            MaximumValue="9999"
                            MaximumDecimalPlaces="0" />

I noticed it has a 'Value' property. Not sure what the purpose of that is but I tried to include it - still get the error.

 Value="1"

### Expected Behavior

Should not throw an error

### Steps To Reproduce

Create a ContentView
Insert the code below into it.
Try to use it.

    <Border BindingContext="{x:Reference thisValidatedNumberEntry}" x:Name="MainBorder">

        <StackLayout Orientation="Horizontal">
            <Entry Style="{StaticResource Key=EntryInverted}" x:Name="TheEntry" Placeholder="{Binding PlaceholderText}" Text="{Binding IntNumber}" 
                   IsPassword="{Binding IsPassword}" Keyboard="Numeric">
                <Entry.Behaviors>
                    <toolkit:NumericValidationBehavior  x:Name="TextVal"
                            InvalidStyle="{StaticResource InvalidEntryStyle}"
                            ValidStyle="{StaticResource ValidEntryStyle}"
                            Flags="ValidateOnValueChanged"
                            MinimumValue="0"
                            MaximumValue="9999"
                            MaximumDecimalPlaces="0" />
                </Entry.Behaviors>
            </Entry>
        </StackLayout>
        <Border.Style>
            <Style TargetType="Border" BasedOn="{StaticResource Key=EntryBorder}">
                <Style.Triggers>
                    
                </Style.Triggers>
            </Style>
        </Border.Style>

    </Border>

### Link to public reproduction project repository

?

### Environment

```markdown
- .NET MAUI CommunityToolkit:4.0
- OS: Android 13
- .NET MAUI: 
Installed Workload Id      Manifest Version       Installation Source           
--------------------------------------------------------------------------------
ios                        16.1.1481/7.0.100      SDK 7.0.100, VS 17.4.33213.308
wasm-tools                 7.0.2/7.0.100          SDK 7.0.100                   
maui-windows               7.0.52/7.0.100         VS 17.4.33213.308             
maui-maccatalyst           7.0.52/7.0.100         VS 17.4.33213.308             
maccatalyst                16.1.1481/7.0.100      VS 17.4.33213.308             
maui-ios                   7.0.52/7.0.100         VS 17.4.33213.308             
android                    33.0.4/7.0.100         VS 17.4.33213.308             
maui-android               7.0.52/7.0.100         VS 17.4.33213.308
```

**Comment by bijington** [comment]
You can opt out of exceptions by setting these options:

https://learn.microsoft.com/en-gb/dotnet/communitytoolkit/maui/get-started?tabs=CommunityToolkitMaui#using-the-nuget-packages

**Comment by chriszuercher** [comment]
I face the same issue after updating from Maui .net 6 to 8 (and the toolkit from 6.0.0 to 9.1.1). The following code was working and is now throwing the exception in the title. But only on iOS (18), not on Android, Windows or MacOS.

i did the change @bijington suggested, the result is the same. Any idea?

``` xaml
<Entry
    x:Name="ProductQuantity"                                   
    Text="{Binding Quantity, Mode=TwoWay}" 
    BackgroundColor="{StaticResource White}" 
    WidthRequest="1"
    MaxLength="2"
    Keyboard="Numeric" ReturnType="Send" Completed="ProductQuantity_Completed">
        <Entry.Behaviors>
            <toolkit:NumericValidationBehavior 
                InvalidStyle="{StaticResource InvalidEntryStyle}"
                ValidStyle="{StaticResource ValidEntryStyle}"
                Flags="ValidateOnValueChanged"
                MinimumValue="0.0"
                MaximumValue="100.0"
                MaximumDecimalPlaces="2" />
        </Entry.Behaviors>
</Entry>
```

**Comment by bijington** [comment]
@chriszuercher are you able to provide a sample that reproduces the issue?
