### ISSUE TITLE
[Proposal] PopupService

### ISSUE THREAD

**Issue by bijington** [CommunityToolkit/Maui#981]
### Feature name

PopupService

### Link to discussion

https://github.com/CommunityToolkit/Maui/discussions/933

### Progress tracker

- [x] Android Implementation
- [x] iOS Implementation
- [x] MacCatalyst Implementation
- [x] Windows Implementation
- [x] Tizen Implementation
- [x] Unit Tests
- [x] Samples
- [ ] Documentation

### Summary

The following proposal provides the ability to register and show popups with associated view models. It will also allow this to be done from a view model.

### Motivation

To make it easier to show popups from a view model.

## PopupService 

```csharp
using System.ComponentModel;
using CommunityToolkit.Maui.Views;

namespace Popups;

public class PopupService
{
    private readonly IServiceProvider serviceProvider;

    private readonly static IDictionary<Type, Type> viewModelToViewMappings = new Dictionary<Type, Type>();

    public PopupService(IServiceProvider serviceProvider)
    {
        this.serviceProvider = serviceProvider;
    }

    public static void AddTransientPopup<TPopupView, TPopupViewModel>(IServiceCollection services)
        where TPopupView : Popup
        where TPopupViewModel : INotifyPropertyChanged
    {
        viewModelToViewMappings.Add(typeof(TPopupViewModel), typeof(TPopupView));

        services.AddTransient(typeof(TPopupView));
        services.AddTransient(typeof(TPopupViewModel));
    }

    public Task<object> ShowPopupAsync<TViewModel>()
    {
        var viewModelType = typeof(TViewModel);

        var viewModel = (TViewModel)this.serviceProvider.GetService<TViewModel>();

        if (viewModel is null)
        {
            throw new InvalidOperationException($"Unable to resolve type {viewModelType} please make sure that you have called RegisterPopup");
        }

        return ShowPopupAsync<TViewModel>(viewModel);
    }

    public Task<object> ShowPopupAsync<TViewModel>(TViewModel viewModel)
    {
        var viewModelType = typeof(TViewModel);

        var view = (Popup)this.serviceProvider.GetRequiredService(viewModelToViewMappings[viewModelType]);

        view.BindingContext = viewModel;

        // TODO: Do we need to provide an override for determine the main page? Or we at least need to verify there is a main page.
        return Application.Current.MainPage.ShowPopupAsync(view);
    }
}
```

## ServiceCollectionExtension

```csharp
public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddTransientPopup<TPopupView, TPopupViewModel>(this IServiceCollection services)
        where TPopupView : Popup
        where TPopupViewModel : INotifyPropertyChanged
    {
        PopupService. AddTransientPopup<TPopupView, TPopupViewModel>(services);

        return services;
    }
}
```

### Usage Syntax

```cs
// Registration in MauiProgram.cs
builder.Services.AddTransientPopup<ConfirmationPopupView, ConfirmationPopupViewModel>();

// Showing of popup from a VM
popupService.ShowPopupAsync<ConfirmationPopupViewModel>();
```

### Drawbacks

It is heavily MVVM focused

**Comment by VladislavAntonyuk** [comment]
approve

**Comment by acaliaro** [comment]
is not possible to use the current "AddTransient" instead of a new method?

**Comment by bijington** [comment]
> is not possible to use the current "AddTransient" instead of a new method?

We can utilise the `AddTransient` extension method in this method but it needs to do a little more by storing the mapping between view and view model. This then allows us from another view model to ask to show the popup for the view model and therefore removing the need for any view information in the view model. I might consider going a step further and allowing a string to be registered a bit like with Shell routes so we don't have to know the view model either.

**Comment by bijington** [comment]
Investigate the concept of `AddTransientPopup` to register just a PopupView and not also the view model

**Comment by bijington** [comment]
Also possibly the concept of registering the view model lifetime differently to the view

**Comment by gabsamples6** [comment]
@bijington  very interested in your proposal, currently we cannot use this popup because we are using MVVM.. do you have a working sample that we could look at and use till this becomes official?

many thanks

**Comment by bijington** [comment]
> @bijington very interested in your proposal, currently we cannot use this popup because we are using MVVM.. do you have a working sample that we could look at and use till this becomes official?
> 
> many thanks

Apologies for the delayed response. I do have a draft PR open here that you could check out: https://github.com/CommunityToolkit/Maui/pull/1165

**Comment by hansmbakker** [comment]
Will this proposal also cover [`Page.DisplayAlert(...)`](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/pop-ups#display-an-alert)?

**Comment by bijington** [comment]
> Will this proposal also cover [`Page.DisplayAlert(...)`](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/pop-ups#display-an-alert)?

No that is not my intention. This is purely focussed around the toolkits `Popup` implementation

**Comment by acaliaro** [comment]
Hi @bijington , do you have an ETA for this?

**Comment by bijington** [comment]
I forgot about this. As far as I am aware the PR is good to go so I should poke the team to review it.

**Comment by santo998** [comment]
Is this implemented?
There is an IPopupService implementation I can use or I have to define mine?

**Comment by Ruddy2007** [comment]
> `AddTransientPopup`

Was this overlooked? I'm a little confused, at the moment is it not possible to register a Popup without a View model.

In my case I have generic popups in my application, they do not need a VM due to be super simple, I cant see a way to register them without a VM?

**Comment by bijington** [comment]
It was necessarily overlooked, we decided to get just the view model support in for v1. I'm currently working on adding in Close support and the display of a popup without having to create a Popup. Then I'm planning on addressing this, I've had some thoughts but if you wanted to get involved I'd happily back the idea.
