### ISSUE TITLE
[BUG] MultiTrigger Conditions all contions must be true

### ISSUE THREAD

**Issue by Luke-leeCoder** [CommunityToolkit/Maui#982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

![image](https://user-images.githubusercontent.com/54387261/218285659-62814cb5-3c66-4d69-b555-3a5336e5298e.png)

'All conditions must be true' but will be true if only one condition is met.

### Expected Behavior

[Setter] All conditions must be true

### Steps To Reproduce

'https://learn.microsoft.com/ko-kr/dotnet/maui/fundamentals/triggers?view=net-maui-7.0'

**multiple trigger** example source Test

### Link to public reproduction project repository

?

### Environment

```markdown
<font class="papago-parent"><font class="papago-source" style="display:none;">- .NET MAUI Community</font>- .NET MAUI 커뮤니티</font><font class="papago-parent"><font class="papago-source" style="display:none;">Toolkit:</font>툴킷:</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>
</font><font class="papago-parent"><font class="papago-source" style="display:none;">- OS:
</font>- OS:</font><font class="papago-parent"><font class="papago-source" style="display:none;">- .NET MAUI:
</font>- .NET MAUI :</font>
```

**Comment by bijington** [comment]
@jfversluis i doubt I have the power but it looks like this issue is against .NET MAUI and not the toolkit. Are you able to transfer it?

**Comment by Luke-leeCoder** [comment]
I think I posted it wrong.
So I put it up there.

https://github.com/dotnet/maui/issues/13280
