### ISSUE TITLE
[BUG] MediaElement stutters when changing Speed on Windows

### ISSUE THREAD

**Issue by wldevries** [CommunityToolkit/Maui#983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Changing the `Speed` of video playback in `MediaElement` is not smooth. When you change `Speed` the timeline jumps back just slightly and continues playback with the new speed.

Note that `MediaElement` on UWP has the exact same behaviour.

### Expected Behavior

Playback timeline remains continuous while changing playback speed.

### Steps To Reproduce

1. Open and run the solution from the reproduction project
2. Choose "Open movie page"
3. Change playback speed using the slider

### Link to public reproduction project repository

https://github.com/wldevries/MauiMediaElementCrash/commit/cd31c83e9555c84ef66ac1a1bb00aae33f7a6cc6

### Environment

```markdown
- .NET MAUI CommunityToolkit MediaElement: 1.0.1
- OS: Win 10 22H2
- .NET MAUI: bundled with VS 2022 17.4.4
```

**Comment by jfversluis** [comment]
I think this might be fixed but we need to do a new release. Might do that this week, please try that one out and let me know if it still happens with that.

**Comment by jfversluis** [comment]
Oh yeah I think I see what you mean. I think that might be due to it not being buffered enough? It definitely isn't as smooth as on the other platforms.

I'm not sure this is anything that we can do much about. As an experiment. If you create a WinUI app with a MediaPlayer in there and set the speed, does it show the same behavior?

**Comment by wldevries** [comment]
I have tried both UWP and WinUI and they both exhibit the same behaviour. I believe that they are all the same component, but you may know better. I'm not sure where else to report this issue.

**Comment by jfversluis** [comment]
UWP is not supported anymore, so we probably don't want to report there 😄 For WinUI, I think the right place is here: https://github.com/microsoft/WindowsAppSDK/issues

Thanks!
