### ISSUE TITLE
[BUG] MediaElement outside of Shell based App causing exception(s) - iOS

### ISSUE THREAD

**Issue by derekpapworth** [CommunityToolkit/Maui#985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When using the MediaElement in a non-Shell based (iOS) app (i.e. NavigationPage based) getting an exception when Push'ing to a page containing a MediaElement whereas works fine if Shell based or if no MediaElement present on page.

### Expected Behavior

Should work fine when Push'ing to a page containing a MediaElement whether Shell based or not.

### Steps To Reproduce

Referring to repository inked below .. 
1. Created a new project from standard Maui template and added a an additional page (MediaPage) and added a button on the MainPage to Navigation.PushAsync to the new page. Then changed in App.Xaml.cs to create a NavigationPage with MainPage as root instead of AppShell. Run the app and all works with button on MainPage pushing MediaPage fine and Back oprtation all good too.
2. Added MediaElement to MediaPage and run again and when MediaPage is pushed and exception occurs "Message=Objective-C exception thrown.  Name: CALayerInvalid Reason: layer <CALayer: 0x600001cca780> is a part of cycle in its layer tree .." - full exception in "Anything else" box below
3. If you switch back in App.Xaml.cs to use Shell and run again all works fine
4. Additionally, if you leave App.Xmal.cs using the NavigationPage but switch the PushAsync of MediaPage to PushModalAsync that works ok.

### Link to public reproduction project repository

https://github.com/derekpapworth/MediaElementTest

### Environment

```markdown
- .NET MAUI CommunityToolkit: 1.0.1
- OS: Windows 11
- .NET MAUI: 7.0.52
```

### Anything else?

ObjCRuntime.ObjCException
  Message=Objective-C exception thrown.  Name: CALayerInvalid Reason: layer <CALayer: 0x600001cca780> is a part of cycle in its layer tree
Native stack trace:
	0   CoreFoundation                      0x00007ff8004288ab __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff80004dba3 objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff800428789 -[NSException initWithCoder:] + 0
	3   QuartzCore                          0x00007ff808989913 _ZN2CA5Layer30ensure_transaction_recursivelyEPNS_11TransactionE + 99
	4   QuartzCore                          0x00007ff808989964 _ZN2CA5Layer30ensure_transaction_recursivelyEPNS_11TransactionE + 180
	5   QuartzCore                          0x00007ff808989964 _ZN2CA5Layer30ensure_transaction_recursivelyEPNS_11TransactionE + 180
	6   QuartzCore                          0x00007ff808989964 _ZN2CA5Layer30ensure_transaction_recursivelyEPNS_11TransactionE + 180
	7   QuartzCore                          0x00007ff808989964 _ZN2CA5Layer30ensure_transaction_recursivelyEPNS_11TransactionE + 180
	8   QuartzCore                          0x00007ff808989964 _ZN2CA5Layer30ensure_transaction_recursivelyEPNS_11TransactionE + 180
	9   QuartzCore                          0x00007ff808989964 _ZN2CA5Layer30ensure_transaction_recursivelyEPNS_11TransactionE + 180
	10  QuartzCore                          0x00007ff808989964 _ZN2CA5Layer30ensure_transaction_recursivelyEPNS_11TransactionE + 180
	11  QuartzCore                          0x00007ff80898e808 _ZN2CA5Layer15insert_sublayerEPNS_11TransactionEP7CALayerm + 488
	12  QuartzCore                          0x00007ff80897ef62 -[CALayer insertSublayer:below:] + 300
	13  UIKitCore                           0x000000011ec07816 -[UIView _backing_insertSubview:belowSubview:] + 93
	14  UIKitCore                           0x000000011f832f7f -[UIView(Internal) _addSubview:positioned:relativeTo:] + 1622
	15  UIKitCore                           0x000000011e94cd05 __53-[_UINavigationParallaxTransition animateTransition:]_block_invoke.163 + 597
	16  UIKitCore                           0x000000011f82ca31 __UIVIEW_IS_EXECUTING_ANIMATION_COMPLETION_BLOCK__ + 15
	17  UIKitCore                           0x000000011f82cd50 -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:] + 797
	18  UIKitCore                           0x000000011f7fc91e -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 190
	19  UIKitCore                           0x000000011f7fcf39 -[UIViewAnimationState animationDidStop:finished:] + 263
	20  UIKitCore                           0x000000011f7fd0ba -[UIViewAnimationState animationDidStop:finished:] + 648
	21  QuartzCore                          0x00007ff808997756 _ZN2CA5Layer23run_animation_callbacksEPv + 318
	22  libdispatch.dylib                   0x00007ff80013ca3a _dispatch_client_callout + 8
	23  libdispatch.dylib                   0x00007ff80014c32c _dispatch_main_queue_drain + 1338
	24  libdispatch.dylib                   0x00007ff80014bde4 _dispatch_main_queue_callback_4CF + 31
	25  CoreFoundation                      0x00007ff800387b1f __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	26  CoreFoundation                      0x00007ff800382436 __CFRunLoopRun + 2482
	27  CoreFoundation                      0x00007ff8003816a7 CFRunLoopRunSpecific + 560
	28  GraphicsServices                    0x00007ff809cb128a GSEventRunModal + 139
	29  UIKitCore                           0x000000011f206ad3 -[UIApplication _run] + 994
	30  UIKitCore                           0x000000011f20b9ef UIApplicationMain + 123
	31  libxamarin-dotnet-debug.dylib       0x000000010c4f5a5a xamarin_UIApplicationMain + 58
	32  libmonosgen-2.0.dylib               0x000000010cd03609 do_icall + 345
	33  libmonosgen-2.0.dylib               0x000000010cd02113 do_icall_wrapper + 291
	34  libmonosgen-2.0.dylib               0x000000010ccf452c interp_exec_method + 3276
	35  libmonosgen-2.0.dylib               0x000000010ccf1e93 interp_runtime_invoke + 259
	36  libmonosgen-2.0.dylib               0x000000010cb16e68 mono_runtime_invoke_checked + 136
	37  libmonosgen-2.0.dylib               0x000000010cb1ee7c do_exec_main_checked + 92
	38  libmonosgen-2.0.dylib               0x000000010cc4dec2 mono_jit_exec + 354
	39  libxamarin-dotnet-debug.dylib       0x000000010c539e77 xamarin_main + 1927
	40  MediaElementNavPage                 0x000000010baa9f54 main + 68
	41  dyld                                0x000000010c1d32bf start_sim + 10
	42  ???                                 0x000000010f00152e 0x0 + 4546630958

  Source=Microsoft.iOS
  StackTrace:
   at ObjCRuntime.Runtime.ThrowNSException(IntPtr ns_exception)
   at ObjCRuntime.Runtime.throw_ns_exception(IntPtr exc)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at MediaElementNavPage.Program.Main(String[] args) in C:\Users\Derek\Documents\Visual Studio 2022\Projects\MediaElementNavPage\Platforms\iOS\Program.cs:line 13

**Comment by Kapusch** [comment]
Similar error here:
`Terminating app due to uncaught exception 'CALayerInvalid', reason: 'layer <CALayer: 0x600002d8ab80> is a part of cycle in its layer tree'`

But also, I have encountered exact same error as in #959 when ContentPage was the root page:
```
System.InvalidOperationException: ViewController can't be null.
   at CommunityToolkit.Maui.Core.Views.MauiMediaElement..ctor(AVPlayerViewController playerViewController)
   at CommunityToolkit.Maui.Core.Handlers.MediaElementHandler.CreatePlatformView()
```

I initially thought it was somehow because I'm not using XAML files, but as soon as I switched to AppShell, it worked.

**Comment by jfversluis** [comment]
Hm that is definitely no intentional. I'll have a look.

**Comment by jfversluis** [comment]
Would any of you be able to test the NuGet package that results from [this PR](https://github.com/CommunityToolkit/Maui/pull/999) to confirm that this is OK now?

The instructions for that can be found here: https://github.com/CommunityToolkit/Maui/wiki/Preview-Packages#pull-requests-

**Comment by Kapusch** [comment]
Sure @jfversluis , but the CI actually failed:
<img width="698" alt="image" src="https://user-images.githubusercontent.com/9576733/219159535-609fb7fa-e166-4955-9a19-ebb9e94eeea3.png">

I'm assuming I can still give it a try with the macOS version of the library. Will keep you posted.

**Comment by jfversluis** [comment]
Yeah sorry about that. See if there are still any artifacts to try. If not, I will make sure the build works again tomorrow. Thank you!

**Comment by Kapusch** [comment]
Ok, but the only artifacts I was able to find are:
- [CommunityToolkit.Maui.MediaElement 4.1.0-build-910.86591+7351a1d](https://dev.azure.com/dotnet/CommunityToolkit/_artifacts/feed/CommunityToolkit-PullRequests/NuGet/CommunityToolkit.Maui.MediaElement/overview/4.1.0-build-910.86591%207351a1d) (29th January)
- or else there was [CommunityToolkit.Maui.MediaElement 1.0.0-preview3823](https://dev.azure.com/dotnet/CommunityToolkit/_artifacts/feed/CommunityToolkit-MainLatest/NuGet/CommunityToolkit.Maui.MediaElement/overview/1.0.0-preview3823) (13th February)

So unless I'm doing wrong, there is no chance I can try your fix ^^
But no worries, I'm already grateful that you planned to work on this so quickly, and I would like to thank you for that 👍

**Comment by derekpapworth** [comment]
I should be able to give it a try tomorrow.. out today.

Derek



Sent from my Galaxy



-------- Original message --------
From: Gerald Versluis ***@***.***>
Date: 15/02/2023 21:05 (GMT+00:00)
To: CommunityToolkit/Maui ***@***.***>
Cc: derekpapworth ***@***.***>, Author ***@***.***>
Subject: Re: [CommunityToolkit/Maui] [BUG] MediaElement outside of Shell based App causing exception(s) - iOS (Issue #985)


Yeah sorry about that. See if there are still any artifacts to try. If not, I will make sure the build works again tomorrow. Thank you!

**Comment by jfversluis** [comment]
@Kapusch there should be a version along the lines of 1.0.0-build-999.87563 now, that should have the fix

**Comment by Kapusch** [comment]
That works ! Thank you very much @jfversluis  🥇 

I was not able to find the NuGet package from the [Pull-Request Feed](nuget add Plugin.Firebase.1.1.1.nupkg -Source /Users/kapusch/WORKSPACE/SOURCES/Libs/Packages), but still I was able to download the artifact from the Azure DevOps pipeline and add it to my local NuGet source.

**Comment by jfversluis** [comment]
Perfect, thank you!

**Comment by Kapusch** [comment]
Actually, I wonder if this has solved #959 but not the current one #985.
In another project, I still get this error:
`Terminating app due to uncaught exception 'CALayerInvalid', reason: 'layer <CALayer: 0x6000001a0a80> is a part of cycle in its layer tree`

I will do further tests later, based on Derek procedure.

**Comment by Kapusch** [comment]
Hi @jfversluis , please find a minimal repro project ([here](https://github.com/Kapusch/CommunityToolkit_MediaElement_Issue_985)) where you can test the MediaElement:

- when it's defined in a ContentPage as the application root page **--> fixed thanks to your PR #999** 
- or when navigating to a ContentPage where it's defined

The first fix you provided actually closed #959 , while the second issue is actually referred as part of this ticket.
Shall you reopen this one ? If no, let me know so that I can log a separated issue.

Thanks in advance 🙏

**Comment by derekpapworth** [comment]
Sorry guys, didn't get a chance to review yesterday as tied up workwise but looks like still an issue from other folks tests?

Also, I'm not up on how exactly to get preview NuGet to test as via the various links I couldn't find anywhere to download it and also not via Visual Studio preview option .. is there a bit more detailed instructions somewhere on how to do that so I can give it a go and/or test when next PR is ready?

Thanks 🙏

**Comment by jfversluis** [comment]
No worries @derekpapworth!

Yeah basically we have these scenarios:
* MediaElement with Shell: just works, worked before
* MediaElement on a ContentPage being the first page: now works after my last change
* MediaElement on a ContentPage, wrapped in a NavigationPage and you navigate to it, still a crash, but another one.

Which is kind of weird as Shell is technically also a NavigationPage... So will have to see to get a decent fix for this one now.

As for testing, that should be described here: https://github.com/CommunityToolkit/Maui/wiki/Preview-Packages

**Comment by jfversluis** [comment]
OK I think I have a solution that works in every scenario! Just need to finish it up a bit more, will do that ASAP for you to test!

Hopefully later today, else it might be over the weekend or early next week. Stay tuned!

**Comment by jfversluis** [comment]
Could you try this one please? https://github.com/CommunityToolkit/Maui/pull/1008

**Comment by Kapusch** [comment]
FYI @derekpapworth , here is how I've been able to test the PR:

1. Go to the PR https://github.com/CommunityToolkit/Maui/pull/1008
2. At the very bottom, show all the checks and find the latest successful build for `CommunityToolkit.Maui`
![image](https://user-images.githubusercontent.com/9576733/219799293-46c874b1-5abc-491f-8285-8631dc0ea4bc.png) and click on the details link

3. Under the build details, to the very bottom, navigate to the Azure Pipelines
<img width="271" alt="image" src="https://user-images.githubusercontent.com/9576733/219799516-c1f52add-23ce-4dd9-8b13-9d4344097fa7.png">

4. Then checkout to the published artifacts 
![image](https://user-images.githubusercontent.com/9576733/219799699-370d7271-0adb-418d-93fc-1c5e8816ff1c.png)

5. And now you can download the NuGet package generated by the PR
<img width="604" alt="image" src="https://user-images.githubusercontent.com/9576733/219799864-cabd1a4a-e948-45fe-b661-44509a83fcef.png">

Finally, all you'll have to do now is configuring a local NuGet source, add the NuGet package to your local source, and install the NuGet package in your project from Visual Studio.

If this last part is a bit new for you, you will have to explore a bit the [documentation](https://learn.microsoft.com/en-us/nuget/reference/nuget-exe-cli-reference), or find some demos on the internet.

**Comment by bijington** [comment]
> FYI @derekpapworth , here is how I've been able to test the PR:
> 
> 
> 
> 1. Go to the PR https://github.com/CommunityToolkit/Maui/pull/1008
> 
> 2. At the very bottom, show all the checks and find the latest successful build for `CommunityToolkit.Maui`
> 
> ![image](https://user-images.githubusercontent.com/9576733/219799293-46c874b1-5abc-491f-8285-8631dc0ea4bc.png) and click on the details link
> 
> 
> 
> 3. Under the build details, to the very bottom, navigate to the Azure Pipelines
> 
> <img width="271" alt="image" src="https://user-images.githubusercontent.com/9576733/219799516-c1f52add-23ce-4dd9-8b13-9d4344097fa7.png">
> 
> 
> 
> 4. Then checkout to the published artifacts 
> 
> ![image](https://user-images.githubusercontent.com/9576733/219799699-370d7271-0adb-418d-93fc-1c5e8816ff1c.png)
> 
> 
> 
> 5. And now you can download the NuGet package generated by the PR
> 
> <img width="604" alt="image" src="https://user-images.githubusercontent.com/9576733/219799864-cabd1a4a-e948-45fe-b661-44509a83fcef.png">
> 
> 
> 
> Finally, all you'll have to do now is configuring a local NuGet source, add the NuGet package to your local source, and install the NuGet package in your project from Visual Studio.
> 
> 
> 
> If this last part is a bit new for you, you will have to explore a bit the [documentation](https://learn.microsoft.com/en-us/nuget/reference/nuget-exe-cli-reference), or find some demos on the internet.

This is great! We should turn this into a docs page

**Comment by Kapusch** [comment]
Thanks! Actually, I can maybe provide a more complete procedure (including the NuGet install in VS).

So based on your comment, I did want to update the Wiki but after I forked the project, I was not able to retrieve the documentation page (I thought Wiki was from built from markdown files that are part of the repo 😄).

Please let me know what's more convenient for you and I'll proceed that way.

**Comment by derekpapworth** [comment]
Thanks @Kapusch / @bijington  - I followed the instructions and got the NuGet files and installed local in VS2022 and managed to test! :) Really useful for futures, thanks again!

@jfversluis - And thanks Gerald! that fixed the issue in my scenario (pushed page with media) so appreciate the quick solution.

Just out of interest, without going into full detail ;) what was the issue? As you say, the Shell is in effect a Navigation Page at heart but presumably there's something different it does perhaps? 

Thanks again all!

**Comment by DerErbil** [comment]
Hello Gerald (@jfversluis), I am using **CommunityToolkit.Maui.MediaElement 3.1.0** which is the Current Up-To-Date Version I believe.

I have a ContentPage "LibraryPage" thats wrapped in a NavigationPage, after the Login this is my Base Page (Application.Current.MainPage):

`Application.Current.MainPage = new NavigationPage(new LibraryPage()); `

from which I launch the ContentPage that contains the MediaElement (Player) per PushAsync

`await Application.Current.MainPage.Navigation.PushAsync(new Player(libraryID), true);`

On Android this seems to work fine, but on iOS I immediately get this Error when the Page opens:

> ObjCRuntime.ObjCException: 'Objective-C exception thrown.  Name: CALayerInvalid Reason: layer <CALayer: 0x600000995f00> is a part of cycle in its layer tree

Can you/anyone help me find a fix for this?

Best Regards,
Erbil
