### ISSUE TITLE
[BUG] MediaElement - iOS doesn't play audio on Stream

### ISSUE THREAD

**Issue by ArchangelWTF** [CommunityToolkit/Maui#989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

iOS does not seem to play audio while the video is watchable, on Android both Audio & Video work just fine.

### Expected Behavior

iOS should be playing audio just like Android does.

### Steps To Reproduce

1. Open and build the sample solution
2.  See the difference between iOS & Android

### Link to public reproduction project repository

https://github.com/ArchangelWTF/iOSStreamSample

### Environment

```markdown
- .NET MAUI CommunityToolkit: 1.0.1
- iOS: 16.3
- OS: Windows 11 22H2
- .NET MAUI: 7.0.52
```

**Comment by jfversluis** [comment]
Are you sure you have audio enabled and/or setup? I've just tried your stream link in the sample app on this repo and it works fine, both video and audio.

If you're using a physical iOS device, make sure to flip the silent switch on the side!

**Comment by ArchangelWTF** [comment]
Huh, weird I switched silent mode to on and then back to off once more and now the issue's gone away for me too!

Thanks, closing this ;)
