### ISSUE TITLE
[Proposal] ObservableRangeCollection

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#99]
# ObservableRangeCollection

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
  * [ ] iOS Support
  * [ ] Android Support
  * [ ] macOS Support
  * [ ] Windows Support
* [ ] Unit Tests: Not Started
* [ ] Sample: Not Started
* [ ] Documentation: Not Started

## Summary
[summary]: #summary

Represents a dynamic data collection that provides notifications when items get added, removed, or when the whole list is refreshed

## Detailed Design
[design]: #detailed-design

```cs
public class ObservableRangeCollection<T> : ObservableCollection<T>
{
  public ObservableRangeCollection() : base()
  {
  }

  public ObservableRangeCollection(IEnumerable<T> collection) : base(collection)
  {
  }

  public void AddRange(IEnumerable<T> collection, NotifyCollectionChangedAction notificationMode = NotifyCollectionChangedAction.Add);

  public void RemoveRange(IEnumerable<T> collection, NotifyCollectionChangedAction notificationMode = NotifyCollectionChangedAction.Reset);

  public void Replace(T item);

  public void ReplaceRange(IEnumerable<T> collection);
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

N/A

### C# Usage

```cs
public ObservableRangeCollection<int> collection = new();

public void AddNumbers(int count)
{
  var startingNumber = collection.Length;
  collection.AddRange(Enumerable.Range(startingNumber, count));
}
```

## Drawbacks
[drawbacks]: #drawbacks

We aredeferring all MVVM components to the [MVVM Toolkit](https://docs.microsoft.com/en-us/windows/communitytoolkit/mvvm/introduction), keeping the .NET MAUI Community Toolkit focused on .NET MAUI-specific tools.

## Alternatives
[alternatives]: #alternatives

- [MvvmHelpers](https://www.nuget.org/packages/Refractored.MvvmHelpers)
- [BulkObservableCollection](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.language.intellisense.bulkobservablecollection-1?view=visualstudiosdk-2019)
- [RangeObservableCollection](https://gist.github.com/weitzhandler/65ac9113e31d12e697cb58cd92601091)

**Comment by brminnick** [comment]
Recommend adding this to the MVVM Toolkit: https://docs.microsoft.com/en-us/windows/communitytoolkit/mvvm/introduction

**Comment by angelru** [comment]
do you know when it will be?

**Comment by bijington** [comment]
I wonder is this a good candidate for the dotnet toolkit?

https://github.com/CommunityToolkit/dotnet

@brminnick what do you think?

**Comment by brminnick** [comment]
Agreed. 

There are efforts being made internally to still sneak it into .NET 7.

But if it were to be added to a Community Toolkit, then https://github.com/CommunityToolkit/dotnet would be the best toolkit for it.

**Comment by maxkoshevoi** [comment]
@brminnick Have it make it to .NET 7? (since it's in RC now)

**Comment by kkppstudios** [comment]
Looks like it's marked for .NET 8. Is this correct?
https://github.com/dotnet/runtime/issues/18087

This is a big gap. One of the few issues remaining for me to migrate to Maui. Any suggestions?

**Comment by pictos** [comment]
@kkppstudios you can copy the implementation to your code and use it there

**Comment by BillyMartin1964** [comment]
ObservableRangeCollection doesn't seem to be in .net 8 either. When will it be done?

**Comment by bijington** [comment]
> ObservableRangeCollection doesn't seem to be in .net 8 either. When will it be done?

That's outside of your hands. I did read that it's being evaluated for .NET 9. For now you can bring in one of the documented options in the Alternatives section if you need it

**Comment by chrisc-ona** [comment]
It appears it has now slipped to .NET 10 at the earliest per https://github.com/dotnet/runtime/issues/18087#issuecomment-2266244088
