### ISSUE TITLE
[BUG]  2 Projects in a solution gives Cannot resolve type "http://schemas.microsoft.com/dotnet/2022/maui/toolkit:SetFocusOnEntryCompletedBehavior".

### ISSUE THREAD

**Issue by gabsamples6** [CommunityToolkit/Maui#991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Hi I was really excited to start working with the maui toolkit, and I hope is something I have missed.

If you have a single project all works fine and you dont see the issue , but in a real world project where my main projects reference other Maui class libraries with views and models that are shared you get the error,

### Expected Behavior

You should be able to use MCT with many projects and not just a single one. You would not be able to use with Prism Modules or any maui class library that has views in it

### Steps To Reproduce

1. Create a maui app
2. Add  .UseMauiCommunityToolkit() to maui project
3. add a maui class library
4. add a Page to a class library 
5. Add an entry with a behavior 
6. build the project and you will see

Error	XFC0000	Cannot resolve type "http://schemas.microsoft.com/dotnet/2022/maui/toolkit:SetFocusOnEntryCompletedBehavior".

### Link to public reproduction project repository

https://github.com/gabsamples6/MauiAppSampleMCT

### Environment

```markdown
- .NET MAUI CommunityToolkit: 4.0
- iOS: 16.3
- OS: Windows 11 22H2
- .NET MAUI: 7.0.52
```

### Anything else?

I really appreciate the work you guys do for FREE.. If you could easily spot where its going wrong and issue a release that would be fantastic.

We cannot use this library till this is sorted

Many thanks
gab

**Comment by pictos** [comment]
This isn't a bug... By design to use the custom schema you need to reference anything on CommunityToolkit using C#. Your `lib` project just use that on xaml, so that will fail. The workaround is to use the old way

`xmlns:mct="clr-namespace:CommunityToolkit.Maui.Behaviors;assembly=CommunityToolkit.Maui"`

or adding some reference using C#
```csharp
public SamplePage()
{
	InitializeComponent();
	_ = new CommunityToolkit.Maui.Behaviors.AnimationBehavior();
}
```

You can read more about it [here](https://learn.microsoft.com/en-us/dotnet/maui/xaml/namespaces/custom-namespace-schemas?view=net-maui-7.0#consume-a-custom-namespace-schema)

**Comment by gabsamples6** [comment]
@pictos  thank you very much for your time and reply your workaround works, but I have to say that this is a big MAUI xml definitions limitation!.

In the real world people used shared libraries and they have more than 1 project, this is not a problem in Xamarin.

Again thanks

**Comment by bijington** [comment]
Sadly the underlying issue is with the XAML compiler. There has been an ongoing issue for some time to look into it but I think it's considered too difficult or low priority to get fixed.

**Comment by gabsamples6** [comment]
@bijington  thanks for the extra info..  this maui is really turning into a nightmare ....

**Comment by bijington** [comment]
It took a while to find but this was the issue I was referring to

https://github.com/dotnet/maui/issues/7503

It hasn't been open for as long as I thought but I am not expecting too much to happen on it. It does look like some level of compiler or linker ripping out the reference when it doesn't believe any of it is actually used. This is why the workaround suggested by @pictos will tell the compiler that it is used. This is not a new issue to .NET MAUI as we have had to deal with this pain on the Xamarin Community Toolkit also

**Comment by gabsamples6** [comment]
hmmm for some reasons I didnt notice in XF but we had most of the converters prior the community toolkit and the main thing we use/used in XF was shimmering and toucheffect

**Comment by pictos** [comment]
@gabsamples6 for XCT we used a SourceGenerator to create the C# code for you secretly, on MCT we rely on `UseCommunityToolkit` call on MauiProgram

**Comment by gabsamples6** [comment]
@pictos  oh that explains it then... and I guess UseCommunityToolkit might not be as clever... as XCT .. its annoying but your suggestions works..

**Comment by pictos** [comment]
Yeah, the reason is that this package is designed to be in the mobile app project and not in a `lib` project... So we didn't do anything to make it cleaver in that area. Not sure if will change at some point in the future

**Comment by brminnick** [comment]
@pictos What do you think about adding a public api like `CommunityToolkit.Maui.LibrarySupport.Initialize()`?

It could basically just be a dummy method that doesn't execute anything but ensures that the Linker doesn't remove CommunityToolkit.Maui when used in a library:

```cs
namespace CommunityToolkit.Maui

public static class LibrarySupport()
{
    public static void Initialize()
    {
        var date = DateTime.Now;
    }
}
```

**Comment by pictos** [comment]
@brminnick I suggest doing anything that can make people feel comfortable about using MCT on libs... Give me some time I'll open a discussion with some scenarios that could be dangerous, that way we can discuss that and see if makes sense to make MCT _lib friendly_ or not

**Comment by gabsamples6** [comment]
Hi just to say brilliant. This will be definitely needed as more people embrace maui , and as soon as framework like prism becomes RTM where there is a concept of modules (libs) than it will be very much needed as people will get errors as soon as they trying to use converters etc...

Remember lots of big projects are not embracing maui because its reputation and stability at the moment - as soon they do than they will need this workaround embedded.

**Comment by hosamyousof** [comment]
@pictos We appreciate if you give a work around to make MCT work on libs.
