### ISSUE TITLE
[PROBLEM] CS0122	'ItemsViewHandler<ReorderableItemsView>.Controller' is inaccessible due to its protection level	CommunityToolkit.Maui (net7.0-ios)

### ISSUE THREAD

**Issue by Erenn36** [CommunityToolkit/Maui#993]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

![Screenshot_1](https://user-images.githubusercontent.com/103508008/218750940-3e86049c-b67b-498a-af9b-57d89eb8c400.png)

I tried to run toolkit and I got that error. I am new about everything, so can anyone explain me how can I run that toolkit?

### Expected Behavior

I am expecting to works

### Steps To Reproduce

Open and run solituon and got error

### Link to public reproduction project repository

a

### Environment

```markdown
- .NET MAUI CommunityToolkit: Latest
- OS: Latest
- .NET MAUI: Latest
```

**Comment by VladislavAntonyuk** [comment]
If you have this issue, that your .NET MAUI version is less then 7.0.59.
Update to the latest .NET MAUI using VS Installer or running dotnet workload update
