### ISSUE TITLE
[BUG] READ_EXTERNAL_STORAGE permission on Android 13

### ISSUE THREAD

**Issue by zZHorizonZz** [CommunityToolkit/Maui#998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

The newly added feature FolderPicker is not working properly on Android 13. As of Android 13 (Api 33), it is no longer possible to use READ_EXTERNAL_STORAGE.
The new permissions are:

- Images and photos: READ_MEDIA_IMAGES
- Videos: READ_MEDIA_VIDEO
- Audio files: READ_MEDIA_AUDIO

As can be seen here [Android 13 Behavior Changes](https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions),

### Expected Behavior

We could just probably check if API is smaller than API 33 and then use READ_EXTERNAL_STORAGE otherwise request READ_MEDIA_IMAGES, READ_MEDIA_VIDEO, READ_MEDIA_AUDIO, or from my testing we don't need to request permission at all since if we want to request folder to which we don't we have permission this permission will be automatically requested via folder picker.

### Steps To Reproduce

Try to run the FilePicker on a device with Android 13 (API 33).

### Link to public reproduction project repository

We can just use Sample from https://github.com/CommunityToolkit/Maui/tree/main/samples/CommunityToolkit.Maui.Sample itself.

### Environment

```markdown
- .NET MAUI CommunityToolkit: 4.0.0
- OS: Windows 10 Enterprise Build 19044.2486
- .NET MAUI: 7.0.59 Service Release 3
```

**Comment by Christerad** [comment]
When is The Upcoming Release ?

**Comment by zZHorizonZz** [comment]
> When is The Upcoming Release ?

I think they are usually every month.

**Comment by thatkidyousaw1** [comment]
Was this fixed on your end? @zZHorizonZz It is still not working on mine.

**Comment by zZHorizonZz** [comment]
Hi, since I was waiting for the fix I just tested on 32 and then I kinda forgot about that, but now since you reminded it to me I have done some digging and found out that it still doesn't work. But I was able to create the workaround:

```C#
#if ANDROID
    public async Task<bool> RequestPermissionAsync()
    {
        var activity = Platform.CurrentActivity ?? throw new NullReferenceException("Current activity is null");

        if (ContextCompat.CheckSelfPermission(activity, Manifest.Permission.ReadExternalStorage) == Permission.Granted)
        {
            return true;
        }

        if (ActivityCompat.ShouldShowRequestPermissionRationale(activity, Manifest.Permission.ReadExternalStorage))
        {
            await Toast.Make("Please grant access to external storage", ToastDuration.Short, 12).Show();
        }

        ActivityCompat.RequestPermissions(activity, new[] { Manifest.Permission.ReadExternalStorage }, 1);

        return false;
    }
#endif
```

And you can use it:

```C#
#if ANDROID

            await RequestPermissionAsync();
#endif

            var folder = await mFolderPicker.PickAsync(cancelToken);
            folder.EnsureSuccess();
```

You also need to make sure to import the android imports:
```C#
#if ANDROID
using Android;
using Android.Content.PM;
using AndroidX.Core.App;
using AndroidX.Core.Content;
#endif
```

**Comment by zZHorizonZz** [comment]
@brminnick Could you reopen this issue since this still doesn't seem like it's fixed and also [your comment](https://github.com/CommunityToolkit/Maui/issues/998#issuecomment-1431419516) linked to writing an issue and not read issue.

**Comment by thatkidyousaw1** [comment]
This works. Thanks alot @zZHorizonZz

**Comment by MichaelStett** [comment]
Thank you for this workaround! @zZHorizonZz :)

**Comment by cworth33** [comment]
Special thanks to @zZHorizonZz for the workaround

I was having similar issues with the FileSaver.
With knowledge of the above workaround I made similar adjustments to get FileSaver to work with API 33.

AndroidManifest.xml

```html
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
	<application android:allowBackup="true" android:icon="@mipmap/appicon" android:supportsRtl="true"></application>
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="33" />
	<queries>
		<intent>
			<action android:name="android.intent.action.SENDTO" />
			<data android:scheme="mailto" />
		</intent>
	</queries>
</manifest>
``` 

Content Page or Content View code behind

```c#
#if ANDROID
using Android;
using Android.Content.PM;
using AndroidX.Core.App;
using AndroidX.Core.Content;
#endif
``` 

Using the FileSaver in your page or view

```c#
            // this will run for Android 33 and greater
            if (DeviceInfo.Platform == DevicePlatform.Android && OperatingSystem.IsAndroidVersionAtLeast(33))
            {
#if ANDROID
                var activity = Platform.CurrentActivity ?? throw new NullReferenceException("Current activity is null");
                if (ContextCompat.CheckSelfPermission(activity, Manifest.Permission.ReadExternalStorage) != Permission.Granted)
                {
                    ActivityCompat.RequestPermissions(activity, new[] { Manifest.Permission.ReadExternalStorage }, 1);
                }
#endif
            }

            var fileSaverResult = await FileSaver.Default.SaveAsync(attachment.AttachmentName, stream, cancellationToken);
```

**Comment by elTRexx** [comment]
Hi, is the above workaround the final solution ? I can't save a file on Android in a custom folder (under builtin Document folder) (well the file is created, but is empty since writing the saving content to it end up in the access denied exception).

**Comment by bijington** [comment]
In case it helps I believe this PR should have helped https://github.com/dotnet/maui/pull/23909
